{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "75hjafas2bcyriu3ba6eqlelyi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.0.7.jar",
          "url": "injected-client-3.0.7.jar",
          "size": 2266379,
          "sha512": "48dac5e774ebb549d3443723446261f81375ad537f99565dfd6a29e7e05935827c49c8ade4be990b5346199e0089b14c47e831ec3318390bf2d45938dd520389",
          "sha256": "69ac7820bec8f1def12940ca196368dda8146ac164f932895c5478cb51c2305e",
          "sha1": "2d1c47794606be09cc721db43bc56155dc707d55",
          "md5": "d89f5467407c66df60d99b37c6cc64a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.0.7.jar",
          "url": "injected-client-3.0.7.jar",
          "size": 2266379,
          "sha512": "48dac5e774ebb549d3443723446261f81375ad537f99565dfd6a29e7e05935827c49c8ade4be990b5346199e0089b14c47e831ec3318390bf2d45938dd520389",
          "sha256": "69ac7820bec8f1def12940ca196368dda8146ac164f932895c5478cb51c2305e",
          "sha1": "2d1c47794606be09cc721db43bc56155dc707d55",
          "md5": "d89f5467407c66df60d99b37c6cc64a3"
        }
      ]
    }
  ]
}
