{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "36hbq5herfeilevtvng3rccmvu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.0.7.jar",
          "url": "injected-client-3.0.7.jar",
          "size": 2266379,
          "sha512": "c667b3214ff52c181418f04afc81dd749c08e67d0b04e4cdfa98a210639a99f9382ed5fcf6c6c8190f1265a996b363a95b64a127d429cac05223e5aeeed6117c",
          "sha256": "b68efafee204aed8ccc21876f71a3330d29fd4d97847429bb98a7ac0791579d0",
          "sha1": "cc17c5e3bb11504822f203783c7811500990d7ad",
          "md5": "b122e7a72c49842d434adafbba6f96a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.0.7.jar",
          "url": "injected-client-3.0.7.jar",
          "size": 2266379,
          "sha512": "c667b3214ff52c181418f04afc81dd749c08e67d0b04e4cdfa98a210639a99f9382ed5fcf6c6c8190f1265a996b363a95b64a127d429cac05223e5aeeed6117c",
          "sha256": "b68efafee204aed8ccc21876f71a3330d29fd4d97847429bb98a7ac0791579d0",
          "sha1": "cc17c5e3bb11504822f203783c7811500990d7ad",
          "md5": "b122e7a72c49842d434adafbba6f96a4"
        }
      ]
    }
  ]
}
