{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "aoj22sqspjeojhy343ufcvh7qu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.8.jar",
          "url": "runelite-api-3.3.8.jar",
          "size": 1214215,
          "sha512": "d0d3ae08694c7e5ae605eda04f1f2e10574e5385b2b467baec1ca2376a2dd82b67028c3ff383865c9bb756e5eec951b221d00682e9a25e5e53adc1ad3a2d4781",
          "sha256": "3012d1f3f238a300c6d51fa2a9c2f6d0b54b3517847513b8e0aa7e82fc55c296",
          "sha1": "ce9c20e1dd08966971c1f6cf044664a99bcb0001",
          "md5": "f872c4a1301091363e78b1830db7949d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.8.jar",
          "url": "runelite-api-3.3.8.jar",
          "size": 1214215,
          "sha512": "d0d3ae08694c7e5ae605eda04f1f2e10574e5385b2b467baec1ca2376a2dd82b67028c3ff383865c9bb756e5eec951b221d00682e9a25e5e53adc1ad3a2d4781",
          "sha256": "3012d1f3f238a300c6d51fa2a9c2f6d0b54b3517847513b8e0aa7e82fc55c296",
          "sha1": "ce9c20e1dd08966971c1f6cf044664a99bcb0001",
          "md5": "f872c4a1301091363e78b1830db7949d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.8-sources.jar",
          "url": "runelite-api-3.3.8-sources.jar",
          "size": 888647,
          "sha512": "645d06fd36669bafdc5affe687924eb431e59820e9f22f8aa67705e2c8fce37a69d9f39aae126917f6965d83d2d5700952718a09f337879c4f5f4a2a816a23f6",
          "sha256": "50e9e9ec8fd040511979d9b6564528f22288e50b0f1674402371e8b6d415ea98",
          "sha1": "fb357a06d822dcbbce072a97c6d6dfcc801d8aee",
          "md5": "cad4bfdd85ebd73abfea29e1d4aac854"
        }
      ]
    }
  ]
}
