{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "bncfqybm4vcnvmczuittknzmf4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.8.jar",
          "url": "runelite-api-3.3.8.jar",
          "size": 1214215,
          "sha512": "4c5b633e099bd4213de8e5954461e22d44f7eb18225f55b7ccbd4da2172f9417701b632a1c1cd2f41ff618a16d1af25262d5e26431acc8d31d5e03378cc3dd8e",
          "sha256": "eba68db6778a5dd9fd6f279baa9bb8bb355e29603d6bf101be24e829727c3ad4",
          "sha1": "166aa1026158b67365dbdb77687575ed352081bc",
          "md5": "2a654aee1d3fe231ff39574974b9d5fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.8.jar",
          "url": "runelite-api-3.3.8.jar",
          "size": 1214215,
          "sha512": "4c5b633e099bd4213de8e5954461e22d44f7eb18225f55b7ccbd4da2172f9417701b632a1c1cd2f41ff618a16d1af25262d5e26431acc8d31d5e03378cc3dd8e",
          "sha256": "eba68db6778a5dd9fd6f279baa9bb8bb355e29603d6bf101be24e829727c3ad4",
          "sha1": "166aa1026158b67365dbdb77687575ed352081bc",
          "md5": "2a654aee1d3fe231ff39574974b9d5fd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.8-sources.jar",
          "url": "runelite-api-3.3.8-sources.jar",
          "size": 888647,
          "sha512": "e8c86dc9675c096594e4d394f3d9204c942acffa02b936df316545555fdf74e4bd0db8f1abc309c75bf21a2efc33e786bf00697de88d0155363439af155f5b29",
          "sha256": "cb28b185855143dbd5edda038555fc3a2b7afec06e0a62c93a447a56fe80c377",
          "sha1": "7613d9f930413840e4b6937be38961f476a5248f",
          "md5": "12bfa6a248a4075d305da5c92aea4dbe"
        }
      ]
    }
  ]
}
