{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "cstu7h7ytjhk7c5jq2afpe77xe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.6"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.6.jar",
          "url": "runescape-api-3.3.6.jar",
          "size": 103730,
          "sha512": "924cc3a246d9178b136ac92b9e128bb6ed743a785cbc1c02b6a9ee5d1c9ec5a2517056beb51877c4027e348cbf218412da396d31778df8e17a233845b45c3343",
          "sha256": "5cbd99e9c51badc204ba1563c60a3f4c6609fb1c8d594b4036fac1cf00a1dbc9",
          "sha1": "e138eaa49fc4ba2aeddc4f4b69a2427ee74e9ef4",
          "md5": "612ee041f7b40b86cae027bc556c57d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.6"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.6.jar",
          "url": "runescape-api-3.3.6.jar",
          "size": 103730,
          "sha512": "924cc3a246d9178b136ac92b9e128bb6ed743a785cbc1c02b6a9ee5d1c9ec5a2517056beb51877c4027e348cbf218412da396d31778df8e17a233845b45c3343",
          "sha256": "5cbd99e9c51badc204ba1563c60a3f4c6609fb1c8d594b4036fac1cf00a1dbc9",
          "sha1": "e138eaa49fc4ba2aeddc4f4b69a2427ee74e9ef4",
          "md5": "612ee041f7b40b86cae027bc556c57d8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.6-sources.jar",
          "url": "runescape-api-3.3.6-sources.jar",
          "size": 99829,
          "sha512": "ae6eab3931a3a9f90b661061a441a8cb659478fd74d64a6d7853bc1dc73bfb3168cd48b2f0a3965f82148081237f75d299cd71f89695066c25dc98e2fa4871a1",
          "sha256": "2f328c89fa68a6f9ef01e8c989a1f689984b77181db06a2bd105f19dcd432a97",
          "sha1": "8045a53c86c2054166b7b86a95f65a759cc6fd9d",
          "md5": "d1c001fefdf63a2380bb3cf549f8c0e6"
        }
      ]
    }
  ]
}
