{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ggaw6frbljekpfvvsureab2nea"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.6"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.6.jar",
          "url": "runescape-api-3.3.6.jar",
          "size": 103730,
          "sha512": "da70c19a2a14460a96f41ca44c16f082d58e0334c0033e30a1519d2d70cb565cd7dfda380f5154ab94ee1c66a1cc4ae5c7620338a85b1e240c1f32af98acb35d",
          "sha256": "e2b17bae30f5a667e1e537e9b544e14112a9950879e2272a85c5192a08f902c5",
          "sha1": "c31fffc5a0fa8585a1708c0d1ec225a45a919bf9",
          "md5": "8373d97fb9b0958334c281a49563803b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.6"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.6.jar",
          "url": "runescape-api-3.3.6.jar",
          "size": 103730,
          "sha512": "da70c19a2a14460a96f41ca44c16f082d58e0334c0033e30a1519d2d70cb565cd7dfda380f5154ab94ee1c66a1cc4ae5c7620338a85b1e240c1f32af98acb35d",
          "sha256": "e2b17bae30f5a667e1e537e9b544e14112a9950879e2272a85c5192a08f902c5",
          "sha1": "c31fffc5a0fa8585a1708c0d1ec225a45a919bf9",
          "md5": "8373d97fb9b0958334c281a49563803b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.6-sources.jar",
          "url": "runescape-api-3.3.6-sources.jar",
          "size": 99829,
          "sha512": "dac1e235c2e4545daa8e349e83b67fa641f98464bb6310693f9ba1446e52727abf753b787b7199f3c8fbd358f4ed691a49696a2988bc2bfd9b6d7527182f91cc",
          "sha256": "65aa8b35f4147d6df07549b13dc42bde314cfe2ac8153c2726b9b669431dbfde",
          "sha1": "f26a530365467f46fc7e9c18c45a8b79ba6605cd",
          "md5": "963512d111193e4b1438565a6018a956"
        }
      ]
    }
  ]
}
