{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "zuo67pdli5aqbc5lz6uu7btsfy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.2.jar",
          "url": "runescape-api-3.3.2.jar",
          "size": 103468,
          "sha512": "f9f8329da68c895adeaccc27b7b89c928976fa82b17b45e7cd70be3f227d16b3eb75d38158fd37318c479ef13b8ff6e8c1095f60cfcb6fa5dc5e1cc95cf34848",
          "sha256": "1ed4d608bfa969f60b6ff52ff039706fb81053bafb942cdd22a460c28cff7ce6",
          "sha1": "6c1d76cd272a6415fb8c48be9d457101391c9488",
          "md5": "aa4674bdb866457e637196e55c618c68"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.2.jar",
          "url": "runescape-api-3.3.2.jar",
          "size": 103468,
          "sha512": "f9f8329da68c895adeaccc27b7b89c928976fa82b17b45e7cd70be3f227d16b3eb75d38158fd37318c479ef13b8ff6e8c1095f60cfcb6fa5dc5e1cc95cf34848",
          "sha256": "1ed4d608bfa969f60b6ff52ff039706fb81053bafb942cdd22a460c28cff7ce6",
          "sha1": "6c1d76cd272a6415fb8c48be9d457101391c9488",
          "md5": "aa4674bdb866457e637196e55c618c68"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.2-sources.jar",
          "url": "runescape-api-3.3.2-sources.jar",
          "size": 99524,
          "sha512": "c05360cd5d200931a43a41858a5c072916cc350dac282f8a7b743e06ea08ecc66eee015a409cd8d8fcbe650aeffb38d13e1bdf2fc5e4b97a62aabd7fdce58346",
          "sha256": "ca702c31d1c2d74874b01aca5d447ca888efbc830af38769153cb93416e324ca",
          "sha1": "7bbf3ddac85584a386afb0a57f466a6707ef64c3",
          "md5": "f5b2d9b7aa713651deae0115fe2b83df"
        }
      ]
    }
  ]
}
