{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "26dtyx2cdjdxlixvuquhnbcngy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.2.jar",
          "url": "runescape-api-3.3.2.jar",
          "size": 103468,
          "sha512": "99c2fca7be6d88fd45f60e7a375e551bf8eb026c18785bf37fd5379e4d32a44ccd966fec7bd5fdcfc66dc63a732eaba6e94cbfa01dc094ddb49039aea1d8f7d7",
          "sha256": "95ea050b1e6d5752f7818818bfff3e900c9a835253ce64632d2e2b5e02840cb1",
          "sha1": "bfc5030fc696b864662a5e35360b70d7d91fc67a",
          "md5": "3ced9f43665ea3bc637e6a2da65ee56d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.2.jar",
          "url": "runescape-api-3.3.2.jar",
          "size": 103468,
          "sha512": "99c2fca7be6d88fd45f60e7a375e551bf8eb026c18785bf37fd5379e4d32a44ccd966fec7bd5fdcfc66dc63a732eaba6e94cbfa01dc094ddb49039aea1d8f7d7",
          "sha256": "95ea050b1e6d5752f7818818bfff3e900c9a835253ce64632d2e2b5e02840cb1",
          "sha1": "bfc5030fc696b864662a5e35360b70d7d91fc67a",
          "md5": "3ced9f43665ea3bc637e6a2da65ee56d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.2-sources.jar",
          "url": "runescape-api-3.3.2-sources.jar",
          "size": 99524,
          "sha512": "02fab08a68909cfbcc1057fc5d2cbfe1285c0568c44d3b156d645f2a4e4d69f590c6ac7c997eee0b7564ebb512876f19a6a82b94849d792a202b289226c6192e",
          "sha256": "9561d115232e03316e794a8058d6a751d254f877c70a1d9e2987cc9ffc91e6c2",
          "sha1": "bce013a4aad39ca31f419cf53ca90605e26605a5",
          "md5": "112c800ed55285ccb68847a4d474df20"
        }
      ]
    }
  ]
}
