{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "qwvznazs55bspbzum2sha3mize"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": []
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.4.0.jar",
          "url": "injected-client-3.4.0.jar",
          "size": 2305007,
          "sha512": "07794bfb1269a838bafc0dfdb5a83daa80a9f14c8a39742bbc39d2e31593ae377da1b8a03c296feada7a9ef29b216e145cc2d56a823dd7a761d3141ffd7747ec",
          "sha256": "745d60f652e4ad0ce23a41cd28cb86c8cc8630d5f54d79e2a008c277beba39f0",
          "sha1": "49b3eaa3e5725f147b973bd63b39e20ca936e8fe",
          "md5": "6c20a4bb49eb4c840321f62522aa2da9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": []
    }
  ]
}
