{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "mmz6kfk2kbfxffiaxxldwd7ydi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": []
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.4.0.jar",
          "url": "injected-client-3.4.0.jar",
          "size": 2305007,
          "sha512": "6ccdcefc86362c766cc6018b7b6177abb08e080d7f09a692227196860bcd2963730d632823ca5d36711f9b7c28d09cd5816012ba0c3bdb3f8a6484f87d57b696",
          "sha256": "3746c39b13d0cc9b3ef7daa76cbc5a91791f885d2e2ba9beb496aa2cacba99e5",
          "sha1": "4b98734755f8ddef034c4bb9529753839f113015",
          "md5": "80ab28d1c77b22dbef1a3293718a31b4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": []
    }
  ]
}
