{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "hpacueuzsfdvlc4qylu66vwfp4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": []
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.4.0.jar",
          "url": "injected-client-3.4.0.jar",
          "size": 2305033,
          "sha512": "89d8ffd5f813fd9c943b24b194d45c1a1f8ea1ec0b7b1c473708f19d546737c55e1dfaa5d3a5ea168d524b21d4a8230046983c229a6e46746feecc6ce3ced4fa",
          "sha256": "68449d1649f33d49568e7db170ff1d9ca378778a0b0ec790060735329a4c1c62",
          "sha1": "36d95d407eb9325910e2d9de41232db25d5ddf88",
          "md5": "24f825464e139299cabc72fec0caeb51"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": []
    }
  ]
}
