{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "2yty7ku6y5hslg3tf45hxegi6m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.3-SNAPSHOT.jar",
          "url": "runescape-api-1.6.3-20200121.000800-1.jar",
          "size": 55242,
          "sha512": "0d8a09ebfec7e88617502459ab279040823e780f24877e5479582102fa3ab08f0cad07fc76c660bafb145110a821fef001896026c55c99be28a867af4a643a76",
          "sha256": "1c2decc5478df6291bf7b8a80ef4db2bcf2022beeefdad436c8146c9aec83720",
          "sha1": "8e2ad1d3ed20c9cedf718df4fb81de6ff5e26fe4",
          "md5": "b99e0a5b6b05b3228585725288083331"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.3-SNAPSHOT.jar",
          "url": "runescape-api-1.6.3-20200121.000800-1.jar",
          "size": 55242,
          "sha512": "0d8a09ebfec7e88617502459ab279040823e780f24877e5479582102fa3ab08f0cad07fc76c660bafb145110a821fef001896026c55c99be28a867af4a643a76",
          "sha256": "1c2decc5478df6291bf7b8a80ef4db2bcf2022beeefdad436c8146c9aec83720",
          "sha1": "8e2ad1d3ed20c9cedf718df4fb81de6ff5e26fe4",
          "md5": "b99e0a5b6b05b3228585725288083331"
        }
      ]
    }
  ]
}
