{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "kwndnbmqzvg7roez2rv3mhfbna"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.3-SNAPSHOT.jar",
          "url": "runescape-api-1.6.3-20200118.222052-1.jar",
          "size": 55242,
          "sha512": "a1be7079af2398ebe3a81ebc440393afd128d8c238019c903241ec8632c179a27fdc8cc4ba3bbbc8751d9f14b04d508f86337ef58a12dc783c3f130f53abd839",
          "sha256": "9dc02472db5d59f48c3b2076b4b8cb8f25eec5be91e8e198781b4df451d1fea6",
          "sha1": "f02a7d346cf6d2699adcdf7cdc6cd79d3429f5fa",
          "md5": "81f9ddbf85e4cefc11ea9db335f8df45"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.3-SNAPSHOT.jar",
          "url": "runescape-api-1.6.3-20200118.222052-1.jar",
          "size": 55242,
          "sha512": "a1be7079af2398ebe3a81ebc440393afd128d8c238019c903241ec8632c179a27fdc8cc4ba3bbbc8751d9f14b04d508f86337ef58a12dc783c3f130f53abd839",
          "sha256": "9dc02472db5d59f48c3b2076b4b8cb8f25eec5be91e8e198781b4df451d1fea6",
          "sha1": "f02a7d346cf6d2699adcdf7cdc6cd79d3429f5fa",
          "md5": "81f9ddbf85e4cefc11ea9db335f8df45"
        }
      ]
    }
  ]
}
