{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "d5obn643gnaffn4hwffstj5tai"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.3-SNAPSHOT.jar",
          "url": "runescape-api-1.6.3-20200118.000825-1.jar",
          "size": 55242,
          "sha512": "d8e06ddebd6b7839a66cbeb5a4d0a40e86e82b26c0a41239a1191fc0d03301cf9678c198388ccad628a8beec53ead71bda28fda56200b983d7d7f72584888867",
          "sha256": "33f9490e3c4190372385e2e1c894b5da5e0f2bcd4a08f5d3aa10f707374fe730",
          "sha1": "aa345730114526d0ea2e0f747c8f10940af21bfc",
          "md5": "8985d8ec9e42aaebe369475bf50f3f3b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.3-SNAPSHOT.jar",
          "url": "runescape-api-1.6.3-20200118.000825-1.jar",
          "size": 55242,
          "sha512": "d8e06ddebd6b7839a66cbeb5a4d0a40e86e82b26c0a41239a1191fc0d03301cf9678c198388ccad628a8beec53ead71bda28fda56200b983d7d7f72584888867",
          "sha256": "33f9490e3c4190372385e2e1c894b5da5e0f2bcd4a08f5d3aa10f707374fe730",
          "sha1": "aa345730114526d0ea2e0f747c8f10940af21bfc",
          "md5": "8985d8ec9e42aaebe369475bf50f3f3b"
        }
      ]
    }
  ]
}
