{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "pwbpa3rx3zb6phpgyvjtmj37hi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.3-SNAPSHOT.jar",
          "url": "runescape-api-1.6.3-20200117.020018-1.jar",
          "size": 55242,
          "sha512": "8b8fa602e17f760d01a0e922600336d8a67e75a497274a9d8d01137d39d44daa41a957a27688d16e8a56c8f5ea38a84edcf68c371b428fd463fc4975d4175f95",
          "sha256": "498a81308e485045a68c049c5f0274399662dbc00a8e7ef04696740ead057af1",
          "sha1": "e9af8dfdb20f42ca8ce4c4782160b0687606a67c",
          "md5": "1b046038db259caa075bfc63db8ffa54"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.3-SNAPSHOT.jar",
          "url": "runescape-api-1.6.3-20200117.020018-1.jar",
          "size": 55242,
          "sha512": "8b8fa602e17f760d01a0e922600336d8a67e75a497274a9d8d01137d39d44daa41a957a27688d16e8a56c8f5ea38a84edcf68c371b428fd463fc4975d4175f95",
          "sha256": "498a81308e485045a68c049c5f0274399662dbc00a8e7ef04696740ead057af1",
          "sha1": "e9af8dfdb20f42ca8ce4c4782160b0687606a67c",
          "md5": "1b046038db259caa075bfc63db8ffa54"
        }
      ]
    }
  ]
}
