{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "2fhut63265gafekzrs4jxj42wa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.3-SNAPSHOT.jar",
          "url": "runescape-api-1.6.3-20200121.051328-1.jar",
          "size": 55242,
          "sha512": "44d30288118e52e198a623e40b6dcd0c4c3e2846655bf6a5605def07d31aa432956ae14013f2a8131c13d852750ae41daeea856d4a5383af45d63e757b7bd858",
          "sha256": "9ed667750dc91fbf593f0f709dfbb0e337dfc532959065811989d57b7711389d",
          "sha1": "8cf6c3a169c10743f501a23c0c1cfaad519ec792",
          "md5": "d37c7bab37fa7a8a688a0ded7115d471"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.3-SNAPSHOT.jar",
          "url": "runescape-api-1.6.3-20200121.051328-1.jar",
          "size": 55242,
          "sha512": "44d30288118e52e198a623e40b6dcd0c4c3e2846655bf6a5605def07d31aa432956ae14013f2a8131c13d852750ae41daeea856d4a5383af45d63e757b7bd858",
          "sha256": "9ed667750dc91fbf593f0f709dfbb0e337dfc532959065811989d57b7711389d",
          "sha1": "8cf6c3a169c10743f501a23c0c1cfaad519ec792",
          "md5": "d37c7bab37fa7a8a688a0ded7115d471"
        }
      ]
    }
  ]
}
