{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "lga66gpwabbedon5gdqb3bsigi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.3-SNAPSHOT.jar",
          "url": "runescape-api-1.6.3-20200123.001038-1.jar",
          "size": 55242,
          "sha512": "d6883c865757e8c57677a57dbed5b20aa329b1a53ce093feef12f631dcbc4aba364e1bb50186ac03d0a20c730669a7a1a1fcfcd7d42ef22264570e121bc971cb",
          "sha256": "f186dd9ab1fede31e3d93f815e965fc2808241e491f7bc636c6519c5d30a1433",
          "sha1": "73beb34d1cb4db65dd5db978bb44e4a280296160",
          "md5": "2a56c4c4b13d643bd0d921f7d8a96dd8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.3-SNAPSHOT.jar",
          "url": "runescape-api-1.6.3-20200123.001038-1.jar",
          "size": 55242,
          "sha512": "d6883c865757e8c57677a57dbed5b20aa329b1a53ce093feef12f631dcbc4aba364e1bb50186ac03d0a20c730669a7a1a1fcfcd7d42ef22264570e121bc971cb",
          "sha256": "f186dd9ab1fede31e3d93f815e965fc2808241e491f7bc636c6519c5d30a1433",
          "sha1": "73beb34d1cb4db65dd5db978bb44e4a280296160",
          "md5": "2a56c4c4b13d643bd0d921f7d8a96dd8"
        }
      ]
    }
  ]
}
