{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "76vxovm35vho3fh3kjzwhlf6g4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.3-SNAPSHOT.jar",
          "url": "runescape-api-1.6.3-20200120.000839-1.jar",
          "size": 55242,
          "sha512": "1260cecb65e725b69a46b55b125278014c578f54b22e5ff91b795b09d5ae35ddaf4f0e0e9ac92ac400bf330a9da81099375b1c0cfa8d2110f989975275c639ab",
          "sha256": "b7ace326db38ad530b100ab235fad0fbf3a05e71ffbbe32348120552a7a01e1c",
          "sha1": "00b1ba14daef08c720e123b03a54254dc08f5575",
          "md5": "7c2025140780f5f4b6c37a35465c76b5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.3-SNAPSHOT.jar",
          "url": "runescape-api-1.6.3-20200120.000839-1.jar",
          "size": 55242,
          "sha512": "1260cecb65e725b69a46b55b125278014c578f54b22e5ff91b795b09d5ae35ddaf4f0e0e9ac92ac400bf330a9da81099375b1c0cfa8d2110f989975275c639ab",
          "sha256": "b7ace326db38ad530b100ab235fad0fbf3a05e71ffbbe32348120552a7a01e1c",
          "sha1": "00b1ba14daef08c720e123b03a54254dc08f5575",
          "md5": "7c2025140780f5f4b6c37a35465c76b5"
        }
      ]
    }
  ]
}
