{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "t5j3pwdnrbdafejetpgfjj6hpi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.3-SNAPSHOT.jar",
          "url": "runescape-api-1.6.3-20200122.000949-1.jar",
          "size": 55242,
          "sha512": "d5913fa02d30fe1e360c8cee8734a6bf8fcdc4f6ee38eda05050345daf23b78f5bd75d44b2843f8ef67c47c5fbc2c46b1a708819c5c5a6f76a1251d4462610d3",
          "sha256": "9d36b387fc46d6843bcd5b02cb0af6e865ca1965cb076928f05c6b44a56f3a17",
          "sha1": "13a786dafa4276558890e4020efaf7f1697a332e",
          "md5": "f5e5f6aef9c7656b2761a2e135b826f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.3-SNAPSHOT.jar",
          "url": "runescape-api-1.6.3-20200122.000949-1.jar",
          "size": 55242,
          "sha512": "d5913fa02d30fe1e360c8cee8734a6bf8fcdc4f6ee38eda05050345daf23b78f5bd75d44b2843f8ef67c47c5fbc2c46b1a708819c5c5a6f76a1251d4462610d3",
          "sha256": "9d36b387fc46d6843bcd5b02cb0af6e865ca1965cb076928f05c6b44a56f3a17",
          "sha1": "13a786dafa4276558890e4020efaf7f1697a332e",
          "md5": "f5e5f6aef9c7656b2761a2e135b826f8"
        }
      ]
    }
  ]
}
