{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "ufew7df6zfbltauic36ac6yszy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.3-SNAPSHOT.jar",
          "url": "runescape-api-1.6.3-20200119.000859-1.jar",
          "size": 55242,
          "sha512": "073ec88edb03410a69366f4fa38e6aff7f602dcf995e2164d8a7dca4d2b2fbdfe13fc73ae04c3e3e468e302cb35044290bd9bb0aec2ef9499f9e40f5c278e721",
          "sha256": "ae628f0be9804b6a36e79d5231d4449fa7981205cee210cc2d984b36ab6cf37c",
          "sha1": "f7e3af0d1497c5c6f0b4a9e9761e00848d96ea7b",
          "md5": "c05e422d86210290513f0929dc442567"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.3-SNAPSHOT.jar",
          "url": "runescape-api-1.6.3-20200119.000859-1.jar",
          "size": 55242,
          "sha512": "073ec88edb03410a69366f4fa38e6aff7f602dcf995e2164d8a7dca4d2b2fbdfe13fc73ae04c3e3e468e302cb35044290bd9bb0aec2ef9499f9e40f5c278e721",
          "sha256": "ae628f0be9804b6a36e79d5231d4449fa7981205cee210cc2d984b36ab6cf37c",
          "sha1": "f7e3af0d1497c5c6f0b4a9e9761e00848d96ea7b",
          "md5": "c05e422d86210290513f0929dc442567"
        }
      ]
    }
  ]
}
