{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "afq7fhtiknhbre6xb7ivkeez4m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.7.jar",
          "url": "runescape-api-3.3.7.jar",
          "size": 103784,
          "sha512": "0527c9d84a2944a07297b892852d63dc5337e4b45b0ef29b302c22ee3d0d4acd824d767cc1817484c85681e3437d73d01189a1f3f6c2406294760b622676db17",
          "sha256": "e43b4d2ee08e8c69ba19d87494dc5d6625b0856628d812611b8c6fa8673ef0be",
          "sha1": "4f2e414b8d59ae1bad51b57ac8fb00bfd54af5d8",
          "md5": "94fd7e937d4612fa23691e9bdc4a5e66"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.7.jar",
          "url": "runescape-api-3.3.7.jar",
          "size": 103784,
          "sha512": "0527c9d84a2944a07297b892852d63dc5337e4b45b0ef29b302c22ee3d0d4acd824d767cc1817484c85681e3437d73d01189a1f3f6c2406294760b622676db17",
          "sha256": "e43b4d2ee08e8c69ba19d87494dc5d6625b0856628d812611b8c6fa8673ef0be",
          "sha1": "4f2e414b8d59ae1bad51b57ac8fb00bfd54af5d8",
          "md5": "94fd7e937d4612fa23691e9bdc4a5e66"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.7-sources.jar",
          "url": "runescape-api-3.3.7-sources.jar",
          "size": 99882,
          "sha512": "3649e3dc53dc83a1c7cd4b98d8838a9dba2ef0399afea5b897e6e2a43a9ae6b82e91204e58d338c8fb222dd01e6ef1fa01776b52548454f9b63342240e41b510",
          "sha256": "b3c78599d29a269ecce29595da31399a66bb3e39929a180482b326e8869ad93a",
          "sha1": "d4658e3b4b6f67015e00cfb1ed4afe4235feb6d7",
          "md5": "fbff87e01cde612946e64e0fb270ba9b"
        }
      ]
    }
  ]
}
