{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "5k3z4g54xfhcpjgt7ikx4ks7le"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.7.jar",
          "url": "runescape-api-3.3.7.jar",
          "size": 103784,
          "sha512": "aae1e86f82e725ac3fa1ad1a520b910a8e7a06e5762800cb41d2d4b6dc705272bf782bc770c4e4386b22fd9a03029a86f8ead3d23f5c74f8c2f4774b0cb1a1be",
          "sha256": "78833a7109d70cfda89a182dfa51508602eb6077a7ae370296968668967e1f7f",
          "sha1": "8cd466dba9483d82e6789e97fb6523b7b7b9a35c",
          "md5": "574e48c2cbf4cf8e928692e67ccbdc3c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.7.jar",
          "url": "runescape-api-3.3.7.jar",
          "size": 103784,
          "sha512": "aae1e86f82e725ac3fa1ad1a520b910a8e7a06e5762800cb41d2d4b6dc705272bf782bc770c4e4386b22fd9a03029a86f8ead3d23f5c74f8c2f4774b0cb1a1be",
          "sha256": "78833a7109d70cfda89a182dfa51508602eb6077a7ae370296968668967e1f7f",
          "sha1": "8cd466dba9483d82e6789e97fb6523b7b7b9a35c",
          "md5": "574e48c2cbf4cf8e928692e67ccbdc3c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.7-sources.jar",
          "url": "runescape-api-3.3.7-sources.jar",
          "size": 99882,
          "sha512": "1f2b7e29d9bbd5c5b1128602ad267e8bfedacb0068cb70943082b078b09e7586d419a7a251b1d97127e6f53e4405a90bc901f4cfc347975a3448167f45e7ed84",
          "sha256": "fcefc0042efa55614cc841ada0f63f5dbcf3d060a47acd34030114738b83aeed",
          "sha1": "adfb45c69687c830a1b4d22b80c6ada58c2abbaf",
          "md5": "6bec5b94793d7e71b56571f8d2ceecbd"
        }
      ]
    }
  ]
}
