{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "taqjrl6iavbcbojhk52alrpupi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.2.jar",
          "url": "injected-client-3.3.2.jar",
          "size": 2253448,
          "sha512": "8296a0202957b22df4b58deaf2d71f10624b50024d3ec0f478a01d7079fee60f2ecf246c5704ed4f9121b626be0b55ef8953c643c94cd77384443a91766abd03",
          "sha256": "8dd494fd826de20df9f4ea7b2b45d50a3ab4cc355ef8e5f94bcf66b98b909c8d",
          "sha1": "6249ed646616b2a686d7c0965ce546046a85b27f",
          "md5": "d899aaeb75e368710d5860cefe93edc6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.2.jar",
          "url": "injected-client-3.3.2.jar",
          "size": 2253448,
          "sha512": "8296a0202957b22df4b58deaf2d71f10624b50024d3ec0f478a01d7079fee60f2ecf246c5704ed4f9121b626be0b55ef8953c643c94cd77384443a91766abd03",
          "sha256": "8dd494fd826de20df9f4ea7b2b45d50a3ab4cc355ef8e5f94bcf66b98b909c8d",
          "sha1": "6249ed646616b2a686d7c0965ce546046a85b27f",
          "md5": "d899aaeb75e368710d5860cefe93edc6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.2-sources.jar",
          "url": "injected-client-3.3.2-sources.jar",
          "size": 261,
          "sha512": "1d49f3f534b7fa6fefac72a9f13a64d153b8bcd1a68da2f6c4d257dc43d86d672f90f50ca297f75667a9fad7f18f91f66a7e3ef49121e8e3229f1e58712f66ca",
          "sha256": "51cfa338f1cb2cca01dcef59e518626e953f3b18b8d2ff87e22647600e50134b",
          "sha1": "7c5bde340fe970047c1819c7c592782064507fd6",
          "md5": "ea1155149f5e9fd121a011cbd9ec3564"
        },
        {
          "name": "injected-client-3.3.2.jar",
          "url": "injected-client-3.3.2.jar",
          "size": 2253448,
          "sha512": "8296a0202957b22df4b58deaf2d71f10624b50024d3ec0f478a01d7079fee60f2ecf246c5704ed4f9121b626be0b55ef8953c643c94cd77384443a91766abd03",
          "sha256": "8dd494fd826de20df9f4ea7b2b45d50a3ab4cc355ef8e5f94bcf66b98b909c8d",
          "sha1": "6249ed646616b2a686d7c0965ce546046a85b27f",
          "md5": "d899aaeb75e368710d5860cefe93edc6"
        }
      ]
    }
  ]
}
