{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "f6xj3y7ut5btjc47nyd7vmrc2e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.2.jar",
          "url": "injected-client-3.3.2.jar",
          "size": 2252612,
          "sha512": "8fb44ec9ff81e8459658805cb9385f69c6eca90f1c842d41625f9a7b8f2a192dbd54c9a20a986a50c79e4d6027347d302fe96465f642956214d705a1ebc01d38",
          "sha256": "1437161d93f4905cbd9528c0c255cda2908b3e1184cfd12b39adeb2f6036a48e",
          "sha1": "18c4abedac8b433a507b268f7ad19e74870cdddc",
          "md5": "63c5bc8f05da640b714ef64e51950dff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.2.jar",
          "url": "injected-client-3.3.2.jar",
          "size": 2252612,
          "sha512": "8fb44ec9ff81e8459658805cb9385f69c6eca90f1c842d41625f9a7b8f2a192dbd54c9a20a986a50c79e4d6027347d302fe96465f642956214d705a1ebc01d38",
          "sha256": "1437161d93f4905cbd9528c0c255cda2908b3e1184cfd12b39adeb2f6036a48e",
          "sha1": "18c4abedac8b433a507b268f7ad19e74870cdddc",
          "md5": "63c5bc8f05da640b714ef64e51950dff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.2-sources.jar",
          "url": "injected-client-3.3.2-sources.jar",
          "size": 261,
          "sha512": "7b175f20095aae152fa58918507a63f5239eb5be421171d48f04db4f1d29d72d8611eb275453a64109fc167b6440551e5e8f1ff287cb1076c36223b93c724ab7",
          "sha256": "b462fb16e7362a7f9eb432346aacccd2096affa22f91188af115decdde0b4713",
          "sha1": "baf1bf114fb2fef3b9d3fe3306fa2b5061fa654b",
          "md5": "3e4a381b7ec968f190b859e9385f491e"
        },
        {
          "name": "injected-client-3.3.2.jar",
          "url": "injected-client-3.3.2.jar",
          "size": 2252612,
          "sha512": "8fb44ec9ff81e8459658805cb9385f69c6eca90f1c842d41625f9a7b8f2a192dbd54c9a20a986a50c79e4d6027347d302fe96465f642956214d705a1ebc01d38",
          "sha256": "1437161d93f4905cbd9528c0c255cda2908b3e1184cfd12b39adeb2f6036a48e",
          "sha1": "18c4abedac8b433a507b268f7ad19e74870cdddc",
          "md5": "63c5bc8f05da640b714ef64e51950dff"
        }
      ]
    }
  ]
}
