{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "fv3xrqpvcfgmllx27r5wuy7p5q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.0.7.jar",
          "url": "runescape-api-3.0.7.jar",
          "size": 55408,
          "sha512": "75ccfb273c1f897b0898480c40543baf6324c1afbb1f8f976bad04c12615e99a1d5cb3833892a7eed1f14052b47d252ba91e7531b199f35075b0a65d23ae9039",
          "sha256": "4e81f262fafbd421e4ce619f50dfeb132cc85510e69337e7213f52681a43c54f",
          "sha1": "1ea324d0111413030da2c0e1214da2e3a25c2677",
          "md5": "fb7052c9daf39fbf115eda3eb5f4ece4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.0.7.jar",
          "url": "runescape-api-3.0.7.jar",
          "size": 55408,
          "sha512": "75ccfb273c1f897b0898480c40543baf6324c1afbb1f8f976bad04c12615e99a1d5cb3833892a7eed1f14052b47d252ba91e7531b199f35075b0a65d23ae9039",
          "sha256": "4e81f262fafbd421e4ce619f50dfeb132cc85510e69337e7213f52681a43c54f",
          "sha1": "1ea324d0111413030da2c0e1214da2e3a25c2677",
          "md5": "fb7052c9daf39fbf115eda3eb5f4ece4"
        }
      ]
    }
  ]
}
