{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "7ukznm4zhfczpkbzlvj6brvxs4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.0.7.jar",
          "url": "runescape-api-3.0.7.jar",
          "size": 55408,
          "sha512": "4002af3102c02fa5e354223ad0845a6452d915777581e12ed9eae8c7ca6b607d84a342cc993e12618acf3976fe8df874f8fc014059c7b13d0801c6be6c9a240d",
          "sha256": "0f0523c243b207e143bc2598b66008896e92db65141215bbec3b8656652becb5",
          "sha1": "1aa91185e5309d3021b614631537c515b0449a4c",
          "md5": "d7c11c9de530c43ae11858c3dfb31313"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.0.7.jar",
          "url": "runescape-api-3.0.7.jar",
          "size": 55408,
          "sha512": "4002af3102c02fa5e354223ad0845a6452d915777581e12ed9eae8c7ca6b607d84a342cc993e12618acf3976fe8df874f8fc014059c7b13d0801c6be6c9a240d",
          "sha256": "0f0523c243b207e143bc2598b66008896e92db65141215bbec3b8656652becb5",
          "sha1": "1aa91185e5309d3021b614631537c515b0449a4c",
          "md5": "d7c11c9de530c43ae11858c3dfb31313"
        }
      ]
    }
  ]
}
