{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "wortqpqmv5dsvnj23qe7swpyyu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.4.jar",
          "url": "injected-client-3.3.4.jar",
          "size": 2252824,
          "sha512": "5f3bbc7656a9a593e4ce72cd009d989f645842dd7dab0519b611fb45c1b0c8019ac3c18470c415f7dfbdcafc5c7dd48900bd2c2c29de73c8c40e88e16f565057",
          "sha256": "ea165b9c82dc155f9af5882ec276506ec07c42225d44a4ec5c3a0afbb6c6cef2",
          "sha1": "ba141c9553a729a8c39e45d7d9d9940c9444d854",
          "md5": "f804ea9adbddd0ec2b5adc6218b55879"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.4.jar",
          "url": "injected-client-3.3.4.jar",
          "size": 2252824,
          "sha512": "5f3bbc7656a9a593e4ce72cd009d989f645842dd7dab0519b611fb45c1b0c8019ac3c18470c415f7dfbdcafc5c7dd48900bd2c2c29de73c8c40e88e16f565057",
          "sha256": "ea165b9c82dc155f9af5882ec276506ec07c42225d44a4ec5c3a0afbb6c6cef2",
          "sha1": "ba141c9553a729a8c39e45d7d9d9940c9444d854",
          "md5": "f804ea9adbddd0ec2b5adc6218b55879"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.4-sources.jar",
          "url": "injected-client-3.3.4-sources.jar",
          "size": 261,
          "sha512": "de95a0a38929b589de19e0de949e653a9708ef071d9ed40fe0b2891690386a0af8369b68f1b5ebbe560e9f434172494a4c6fccd1b43e434aed366e4f9fd8e5b9",
          "sha256": "dedb08f9035071cb176695839a7fd3c2199be365c44e24178a10f0f6fa685259",
          "sha1": "ab92c56cdfa51a234eb1ac93673b8f674c3483d5",
          "md5": "634847ade057a38e0377c7cfb77e3489"
        },
        {
          "name": "injected-client-3.3.4.jar",
          "url": "injected-client-3.3.4.jar",
          "size": 2252824,
          "sha512": "5f3bbc7656a9a593e4ce72cd009d989f645842dd7dab0519b611fb45c1b0c8019ac3c18470c415f7dfbdcafc5c7dd48900bd2c2c29de73c8c40e88e16f565057",
          "sha256": "ea165b9c82dc155f9af5882ec276506ec07c42225d44a4ec5c3a0afbb6c6cef2",
          "sha1": "ba141c9553a729a8c39e45d7d9d9940c9444d854",
          "md5": "f804ea9adbddd0ec2b5adc6218b55879"
        }
      ]
    }
  ]
}
