{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "cqq7nc66dva4patoegzemqvkba"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.4.jar",
          "url": "injected-client-3.3.4.jar",
          "size": 2252824,
          "sha512": "af70717fa000c5f04c0ffce0d24910dc0ab63200dd760af5bc0bc28968e963a2761a1090bd73a70bf658ce4e935089ef273d9941de3f8c9d9452d51460c641f5",
          "sha256": "4448701b0bf0ec40ac06748a597f4cf092bc196608fb6999229cbd7be12fa6c4",
          "sha1": "7eddac79ba6244bb9fa5f32ca726fe6710fda8b0",
          "md5": "39ddbd7723c1c7c3e6260a33d9dd1207"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.4.jar",
          "url": "injected-client-3.3.4.jar",
          "size": 2252824,
          "sha512": "af70717fa000c5f04c0ffce0d24910dc0ab63200dd760af5bc0bc28968e963a2761a1090bd73a70bf658ce4e935089ef273d9941de3f8c9d9452d51460c641f5",
          "sha256": "4448701b0bf0ec40ac06748a597f4cf092bc196608fb6999229cbd7be12fa6c4",
          "sha1": "7eddac79ba6244bb9fa5f32ca726fe6710fda8b0",
          "md5": "39ddbd7723c1c7c3e6260a33d9dd1207"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.4-sources.jar",
          "url": "injected-client-3.3.4-sources.jar",
          "size": 261,
          "sha512": "cab6a05fa5c3b9f2c253758a287321f7e9b920d7a90df8f18c285ab7e8ff1ec9583f2cb42192fd5dcbbd052c73e8b7faf14526a41a6f43fe6258bc0fbf05159e",
          "sha256": "1b575ab74f636cbd712c904421503a24838a28ba6180f60ae14b318c8e59c09d",
          "sha1": "baa75afdf66f5c1cbe1b0ee9a60e219c59e8e69a",
          "md5": "26f6304f4b95670bad396d9a32bbce4a"
        },
        {
          "name": "injected-client-3.3.4.jar",
          "url": "injected-client-3.3.4.jar",
          "size": 2252824,
          "sha512": "af70717fa000c5f04c0ffce0d24910dc0ab63200dd760af5bc0bc28968e963a2761a1090bd73a70bf658ce4e935089ef273d9941de3f8c9d9452d51460c641f5",
          "sha256": "4448701b0bf0ec40ac06748a597f4cf092bc196608fb6999229cbd7be12fa6c4",
          "sha1": "7eddac79ba6244bb9fa5f32ca726fe6710fda8b0",
          "md5": "39ddbd7723c1c7c3e6260a33d9dd1207"
        }
      ]
    }
  ]
}
