{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "blh2zpvljjazvdv4amvku44acu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.4.jar",
          "url": "injected-client-3.3.4.jar",
          "size": 2252824,
          "sha512": "9615e504f11414d8aca86a46d9398c114147662e79d8738254bec4faefec4b301c6e6dcf5e535bd63d0a0e5f2fa7ed8fc6179d2c131c58de0d7d452420327cf5",
          "sha256": "7ab50a5c2d6475ac30cb6281ec9d6c89c39260333cfe930beed9455ba4643cb9",
          "sha1": "8b4c7c62c8dfdc4678f58bc05c2389a04a949a10",
          "md5": "5b3441e6ccfa274d6665c37367caf29a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.4.jar",
          "url": "injected-client-3.3.4.jar",
          "size": 2252824,
          "sha512": "9615e504f11414d8aca86a46d9398c114147662e79d8738254bec4faefec4b301c6e6dcf5e535bd63d0a0e5f2fa7ed8fc6179d2c131c58de0d7d452420327cf5",
          "sha256": "7ab50a5c2d6475ac30cb6281ec9d6c89c39260333cfe930beed9455ba4643cb9",
          "sha1": "8b4c7c62c8dfdc4678f58bc05c2389a04a949a10",
          "md5": "5b3441e6ccfa274d6665c37367caf29a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.4-sources.jar",
          "url": "injected-client-3.3.4-sources.jar",
          "size": 261,
          "sha512": "1117b5be94fb1ac8a37c228e555d382ec06f11ec3255b33453da124254bb8f0a67faaaf1ecf53c8ad2fe40c72a6d342e59d4c56abc28b089293540bff4300c2a",
          "sha256": "66d07e72d4b6154a997fa16193437fd09c535423bfd76a0ace5b81e06f09d988",
          "sha1": "d492b39072e4d86bcd8e5453a1fd40a2201ab387",
          "md5": "82ffad8aa09e16059d62683637c8f106"
        },
        {
          "name": "injected-client-3.3.4.jar",
          "url": "injected-client-3.3.4.jar",
          "size": 2252824,
          "sha512": "9615e504f11414d8aca86a46d9398c114147662e79d8738254bec4faefec4b301c6e6dcf5e535bd63d0a0e5f2fa7ed8fc6179d2c131c58de0d7d452420327cf5",
          "sha256": "7ab50a5c2d6475ac30cb6281ec9d6c89c39260333cfe930beed9455ba4643cb9",
          "sha1": "8b4c7c62c8dfdc4678f58bc05c2389a04a949a10",
          "md5": "5b3441e6ccfa274d6665c37367caf29a"
        }
      ]
    }
  ]
}
