{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "aoj22sqspjeojhy343ufcvh7qu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.8"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.8.jar",
          "url": "runescape-api-3.3.8.jar",
          "size": 103807,
          "sha512": "e5ddc0ab4594fe22eeee7918e105ad938923517a18d7f418315fc1ba32dad6c84e5e725f395e18c0444c1b0d110606beed8b3fa7f30d2352ca80df124789c33d",
          "sha256": "d36c6dc84a3ba506f47dc1ff219129562844ec65de565c100e12c110d8ec91f6",
          "sha1": "4c0951080566cd52e0a95a1d2ed5aed021f82239",
          "md5": "6ea83ea2a48943bef7840d7d681639ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.8"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.8.jar",
          "url": "runescape-api-3.3.8.jar",
          "size": 103807,
          "sha512": "e5ddc0ab4594fe22eeee7918e105ad938923517a18d7f418315fc1ba32dad6c84e5e725f395e18c0444c1b0d110606beed8b3fa7f30d2352ca80df124789c33d",
          "sha256": "d36c6dc84a3ba506f47dc1ff219129562844ec65de565c100e12c110d8ec91f6",
          "sha1": "4c0951080566cd52e0a95a1d2ed5aed021f82239",
          "md5": "6ea83ea2a48943bef7840d7d681639ae"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.8-sources.jar",
          "url": "runescape-api-3.3.8-sources.jar",
          "size": 99891,
          "sha512": "6195b673f44cdb2e6ca5fbb3d5c4854686bb4ba230d75a587be526a238cb864a5f6a23f6b2182c598a727cd9a07b114680c80a209ac5c9a87f01d9b74e3d750e",
          "sha256": "a992a64a12b68bf510656e9b8df0fd816ae49ddf28ea53afcd3b641e43e0a2ea",
          "sha1": "f5909b3f200065bc4922466f9ca9869391381aee",
          "md5": "1b6156d3c77d93a2e37494d4699e53c7"
        }
      ]
    }
  ]
}
