{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "bncfqybm4vcnvmczuittknzmf4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.8"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.8.jar",
          "url": "runescape-api-3.3.8.jar",
          "size": 103807,
          "sha512": "784934760b0cae262f6a03c570b3b1cf45340531ca184045b40c65f46d349f9c238131ec64ab0654efe6285db0991afdb20011adc87e0de0b5adda4a0bb38fc6",
          "sha256": "6f5899a4ad5f416ae82e6ff6f5b6cb72c4aec60c877ac81348a933f40dac0a8f",
          "sha1": "221386208f721f83e3dad5411901c4b67f928ed8",
          "md5": "d1029093e9549a6457150b90fc72c17b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.8"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.8.jar",
          "url": "runescape-api-3.3.8.jar",
          "size": 103807,
          "sha512": "784934760b0cae262f6a03c570b3b1cf45340531ca184045b40c65f46d349f9c238131ec64ab0654efe6285db0991afdb20011adc87e0de0b5adda4a0bb38fc6",
          "sha256": "6f5899a4ad5f416ae82e6ff6f5b6cb72c4aec60c877ac81348a933f40dac0a8f",
          "sha1": "221386208f721f83e3dad5411901c4b67f928ed8",
          "md5": "d1029093e9549a6457150b90fc72c17b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.8-sources.jar",
          "url": "runescape-api-3.3.8-sources.jar",
          "size": 99891,
          "sha512": "a8db1384fe99dd5bfe907a6a181ff7f6c92675d15386e07963d6fe1f8ea087d5aa53feb19826829b1970de75daa42f45ffbe28f7f4bcf7d6b141568a4971d18c",
          "sha256": "0478ab5c1d05e3cf49859b3158655d8922cccc79c669ed593c1becd8d3d189d6",
          "sha1": "cc9f5217fbb3e53f711e08db95cb30af2b426d80",
          "md5": "9855345ac19f13f2407662aef38c426f"
        }
      ]
    }
  ]
}
