{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "w36sdneu2zbexo4kpfqf453564"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.8"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.8.jar",
          "url": "runescape-api-3.3.8.jar",
          "size": 103807,
          "sha512": "6950f87fdf75e1f02af82b436c1c0d0e3d4bb16840576c1b4fde215a4bddfc9642d7b4a0c701432716b976287fe1c9f403288113b2f0836b285aff41d5e8934c",
          "sha256": "1545ebe3d886d66467e327bf9da2fffbc348dede350ad31d1c67f18530d93c72",
          "sha1": "3ad426cda46281a2b7e495e028b4559e2c03c649",
          "md5": "6a7ad906813171d92d704353ee927986"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.8"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.8.jar",
          "url": "runescape-api-3.3.8.jar",
          "size": 103807,
          "sha512": "6950f87fdf75e1f02af82b436c1c0d0e3d4bb16840576c1b4fde215a4bddfc9642d7b4a0c701432716b976287fe1c9f403288113b2f0836b285aff41d5e8934c",
          "sha256": "1545ebe3d886d66467e327bf9da2fffbc348dede350ad31d1c67f18530d93c72",
          "sha1": "3ad426cda46281a2b7e495e028b4559e2c03c649",
          "md5": "6a7ad906813171d92d704353ee927986"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.8-sources.jar",
          "url": "runescape-api-3.3.8-sources.jar",
          "size": 99891,
          "sha512": "6cfa43a70adab27704dc9b9ef90f7f631752087b82e5325f3c5bfc80af37c44e161169ad6c4df72a2990b59fa55897423479cd8d97b3934990449131e1fe3878",
          "sha256": "0512898ad3c1a596eed5d25eb318636cfea70846120da5532acf52e4f1f980e9",
          "sha1": "ec8f0a4eadddfdd6613ec9fde0e8e89ddd8119b2",
          "md5": "3531613142cb83a05650920322be06c0"
        }
      ]
    }
  ]
}
