{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-client",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "otqveiv2azb5rmwjys3mkini5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-client-3.1.0.jar",
          "url": "runelite-client-3.1.0.jar",
          "size": 2616442,
          "sha512": "34c788e048deb2129823e3462fd142223f29c539bdff332a10daf7fdc266c6ecf338991ce3b5002ea4a863fbb9058abfea6726967c927aae3dfcdf37d4641c66",
          "sha256": "cc7569446f8662bb1fb104264350dba1b3fccf6eb41d53227814d46ece14deee",
          "sha1": "b7ad3319c9bbf8e27198dfca4af5833ea1fcfad2",
          "md5": "e2a69d60b040c00cb9d6d11041f417de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "4.2.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "guice",
              "type": "jar",
              "extension": "jar",
              "classifier": "no_aop"
            }
          }
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "1.4.200"
          }
        },
        {
          "group": "com.openosrs.rxrelay3",
          "module": "rxrelay",
          "version": {
            "requires": "3.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "net.runelite",
          "module": "discord",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "org.pushing-pixels",
          "module": "radiance-substance",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "19.0.0"
          }
        },
        {
          "group": "org.jogamp.gluegen",
          "module": "gluegen-rt",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.jogamp.jogl",
          "module": "jogl-all",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq",
          "version": {
            "requires": "3.13.0"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq-codegen",
          "version": {
            "requires": "3.13.0"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq-meta",
          "version": {
            "requires": "3.13.0"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-logback",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.github.zafarkhaja",
          "module": "java-semver",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.pf4j",
          "module": "pf4j",
          "version": {
            "requires": "3.2.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.pf4j",
          "module": "pf4j-update",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "http-api",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.pushing-pixels",
          "module": "radiance-trident",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "org.jogamp.gluegen",
          "module": "gluegen-rt",
          "version": {
            "requires": "2.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gluegen-rt",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux-amd64"
            }
          }
        },
        {
          "group": "org.jogamp.gluegen",
          "module": "gluegen-rt",
          "version": {
            "requires": "2.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gluegen-rt",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux-i586"
            }
          }
        },
        {
          "group": "org.jogamp.gluegen",
          "module": "gluegen-rt",
          "version": {
            "requires": "2.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gluegen-rt",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-amd64"
            }
          }
        },
        {
          "group": "org.jogamp.gluegen",
          "module": "gluegen-rt",
          "version": {
            "requires": "2.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gluegen-rt",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-i586"
            }
          }
        },
        {
          "group": "org.jogamp.jogl",
          "module": "jogl-all",
          "version": {
            "requires": "2.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jogl-all",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux-amd64"
            }
          }
        },
        {
          "group": "org.jogamp.jogl",
          "module": "jogl-all",
          "version": {
            "requires": "2.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jogl-all",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux-i586"
            }
          }
        },
        {
          "group": "org.jogamp.jogl",
          "module": "jogl-all",
          "version": {
            "requires": "2.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jogl-all",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-amd64"
            }
          }
        },
        {
          "group": "org.jogamp.jogl",
          "module": "jogl-all",
          "version": {
            "requires": "2.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jogl-all",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-i586"
            }
          }
        },
        {
          "group": "com.openosrs",
          "module": "injected-client",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.openosrs.rs",
          "module": "runescape-api",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-client-3.1.0.jar",
          "url": "runelite-client-3.1.0.jar",
          "size": 2616442,
          "sha512": "34c788e048deb2129823e3462fd142223f29c539bdff332a10daf7fdc266c6ecf338991ce3b5002ea4a863fbb9058abfea6726967c927aae3dfcdf37d4641c66",
          "sha256": "cc7569446f8662bb1fb104264350dba1b3fccf6eb41d53227814d46ece14deee",
          "sha1": "b7ad3319c9bbf8e27198dfca4af5833ea1fcfad2",
          "md5": "e2a69d60b040c00cb9d6d11041f417de"
        }
      ]
    }
  ]
}
