{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "wearss7mlrhafjozjlmzxt6adm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.4.jar",
          "url": "runelite-api-1.6.4.jar",
          "size": 1149312,
          "sha512": "5ab5baada2bcd0badea2f23a5c4701de3667617fafad12f0f462599acf5b9a9efb14b52baefb7bfdc39ee7acf19a1ff328887f70eb96b83bcdd7d42418320b39",
          "sha256": "4b6a3bf94184327701124a1c024dbec7850161250596feff2b53a2470d67610a",
          "sha1": "d5b46d9d7278937ee3eb87582c6d37a2e91ba109",
          "md5": "d39ef934ee527986ac6c96cb6a15f680"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.4.jar",
          "url": "runelite-api-1.6.4.jar",
          "size": 1149312,
          "sha512": "5ab5baada2bcd0badea2f23a5c4701de3667617fafad12f0f462599acf5b9a9efb14b52baefb7bfdc39ee7acf19a1ff328887f70eb96b83bcdd7d42418320b39",
          "sha256": "4b6a3bf94184327701124a1c024dbec7850161250596feff2b53a2470d67610a",
          "sha1": "d5b46d9d7278937ee3eb87582c6d37a2e91ba109",
          "md5": "d39ef934ee527986ac6c96cb6a15f680"
        }
      ]
    }
  ]
}
