{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "5qd27gdaunec3dmcvscdgx4jgi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.3-SNAPSHOT.jar",
          "url": "runelite-api-1.6.3-20200121.051331-2.jar",
          "size": 1149042,
          "sha512": "e12bfa54ed4920cb5f18a6cec384ddc6a159ef4aa533ac43a6beb87567e7c5d74dcbffc4fe4300a60afe8f5e7437854da96f68152125a4079395f3690950b33d",
          "sha256": "b0212fa4c6b0f7f3fd5debc878d697d992dac6415f500f9801c17ccfcbbb4251",
          "sha1": "0dd9d8139e2169a71b2821478472120a1bd365f5",
          "md5": "d993faa71741612d04b7b687113094d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.3-SNAPSHOT.jar",
          "url": "runelite-api-1.6.3-20200121.051331-2.jar",
          "size": 1149042,
          "sha512": "e12bfa54ed4920cb5f18a6cec384ddc6a159ef4aa533ac43a6beb87567e7c5d74dcbffc4fe4300a60afe8f5e7437854da96f68152125a4079395f3690950b33d",
          "sha256": "b0212fa4c6b0f7f3fd5debc878d697d992dac6415f500f9801c17ccfcbbb4251",
          "sha1": "0dd9d8139e2169a71b2821478472120a1bd365f5",
          "md5": "d993faa71741612d04b7b687113094d1"
        }
      ]
    }
  ]
}
