{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "35o7ugfvczalxmxd53hde2sfpa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.5-SNAPSHOT.jar",
          "url": "http-api-1.6.5-20200126.000916-1.jar",
          "size": 165434,
          "sha512": "ef90c76378d71aca049c73715a6af1ae000ca1852cc18a7907264d468c45d0433b6db9f1062924b9800f26ae40dc0052f6b96bc3922eb40d62640bfb3042fc28",
          "sha256": "6bfd80b981010ce71d548d3a1742ca29035c2d7373b34f0c51227065affcfe7b",
          "sha1": "aa72875938844ad4502f2b9330965bc4ebe37f10",
          "md5": "003c8977f0713e8bb227d06cbd574917"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.5-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.5-SNAPSHOT.jar",
          "url": "http-api-1.6.5-20200126.000916-1.jar",
          "size": 165434,
          "sha512": "ef90c76378d71aca049c73715a6af1ae000ca1852cc18a7907264d468c45d0433b6db9f1062924b9800f26ae40dc0052f6b96bc3922eb40d62640bfb3042fc28",
          "sha256": "6bfd80b981010ce71d548d3a1742ca29035c2d7373b34f0c51227065affcfe7b",
          "sha1": "aa72875938844ad4502f2b9330965bc4ebe37f10",
          "md5": "003c8977f0713e8bb227d06cbd574917"
        }
      ]
    }
  ]
}
