{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "5vbyyaqmcramrbqo7yp7hanwxm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.5-SNAPSHOT.jar",
          "url": "http-api-1.6.5-20200129.000856-1.jar",
          "size": 165434,
          "sha512": "2ef286caf071a25b590348ff533a1be2c378288f1bd2448f175e0212844f698840b7d81b99b3c554f70ea1c567e2d83fcdf1927294249809b3b2f991f363ad85",
          "sha256": "f1b82d7a0aa43bd409a7ea62416c0e8b52ea5095fffcae835f81dd2f3c269696",
          "sha1": "c93d1623fd2cb8bb7511778e4f0f671f670bb1bb",
          "md5": "ef1ac307718df0f141ff947ff5ae1904"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.5-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.5-SNAPSHOT.jar",
          "url": "http-api-1.6.5-20200129.000856-1.jar",
          "size": 165434,
          "sha512": "2ef286caf071a25b590348ff533a1be2c378288f1bd2448f175e0212844f698840b7d81b99b3c554f70ea1c567e2d83fcdf1927294249809b3b2f991f363ad85",
          "sha256": "f1b82d7a0aa43bd409a7ea62416c0e8b52ea5095fffcae835f81dd2f3c269696",
          "sha1": "c93d1623fd2cb8bb7511778e4f0f671f670bb1bb",
          "md5": "ef1ac307718df0f141ff947ff5ae1904"
        }
      ]
    }
  ]
}
