{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "tq6d5fcpuzfolj3t2vk3h7pqcu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.5-SNAPSHOT.jar",
          "url": "http-api-1.6.5-20200123.130318-1.jar",
          "size": 165434,
          "sha512": "ff762d77e7395822bd7b4eee7c07da7b756b5cbb560e67be76137d7187eb05ebc323879c7c1accfa4800696a9da71fd9e3827a28634cb395c589b2dc2d8624ad",
          "sha256": "0d33026ffe16ce4f2d643505c14010c21f8fd43cc02720841541c381954192a0",
          "sha1": "d97ddc726ec00a323d3ca6309e948b5e21bf83c8",
          "md5": "d4e6230f8704ccca226464ac9f9e2113"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.5-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.5-SNAPSHOT.jar",
          "url": "http-api-1.6.5-20200123.130318-1.jar",
          "size": 165434,
          "sha512": "ff762d77e7395822bd7b4eee7c07da7b756b5cbb560e67be76137d7187eb05ebc323879c7c1accfa4800696a9da71fd9e3827a28634cb395c589b2dc2d8624ad",
          "sha256": "0d33026ffe16ce4f2d643505c14010c21f8fd43cc02720841541c381954192a0",
          "sha1": "d97ddc726ec00a323d3ca6309e948b5e21bf83c8",
          "md5": "d4e6230f8704ccca226464ac9f9e2113"
        }
      ]
    }
  ]
}
