{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "bxmcylkl6farbfd3u7e2f7kxku"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.9.jar",
          "url": "runelite-api-3.3.9.jar",
          "size": 1219329,
          "sha512": "14e03fa9beac8bf00a232aa30ebded8bfd58fef42768737b9030aeeb1a92e08159f6e7fb82dca9a8f12da51a5ee4e39657b1896ab7c924d2aa26e8c31c00ef00",
          "sha256": "58d61f58d936e163e6b097a58d85240c1c389de3bac340bc57b29ef41a284535",
          "sha1": "49b010d03fab0639f219ad25fbd24efe44496363",
          "md5": "a39796d89fdcc6d97a4f4e5c2bc4b5a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.9.jar",
          "url": "runelite-api-3.3.9.jar",
          "size": 1219329,
          "sha512": "14e03fa9beac8bf00a232aa30ebded8bfd58fef42768737b9030aeeb1a92e08159f6e7fb82dca9a8f12da51a5ee4e39657b1896ab7c924d2aa26e8c31c00ef00",
          "sha256": "58d61f58d936e163e6b097a58d85240c1c389de3bac340bc57b29ef41a284535",
          "sha1": "49b010d03fab0639f219ad25fbd24efe44496363",
          "md5": "a39796d89fdcc6d97a4f4e5c2bc4b5a3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.9-sources.jar",
          "url": "runelite-api-3.3.9-sources.jar",
          "size": 893202,
          "sha512": "7c5a59122e6ddfd4b1c5867ba5fa4ac40386c593b2e011310031bb66116f7e350fc002e9d8c15dea15e4308cd3f9d503f0d80b7fc6495b8e19ac66b68a0fc912",
          "sha256": "1da9db1e8a1e951105d88dc36209a8e217bb73496441d9f2497b23e10a6cedaf",
          "sha1": "93a6a484c93fd08ac298076c619170e8deba139d",
          "md5": "d2c1ad1758aeae259e3614b731a01086"
        }
      ]
    }
  ]
}
