{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "6sntp6srbfhbhitopmjtqf2rme"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.9.jar",
          "url": "runelite-api-3.3.9.jar",
          "size": 1218932,
          "sha512": "56a38844f421f0074395c9b9507ce0c98c87510a2caacc66d928e1a77b2c5fdd226276b30516b33a391a122b6dd27dc688c8a4a49de42dfc330734f3077d5a97",
          "sha256": "0bce2393dcb354db52ed6c3c1d701698d0d397d5ecad1d997042c1184acb07da",
          "sha1": "68abcd2b2ffc18a2d4776492a43740ef85917776",
          "md5": "0109cfcec33b2aa9af038063f98345f3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.9.jar",
          "url": "runelite-api-3.3.9.jar",
          "size": 1218932,
          "sha512": "56a38844f421f0074395c9b9507ce0c98c87510a2caacc66d928e1a77b2c5fdd226276b30516b33a391a122b6dd27dc688c8a4a49de42dfc330734f3077d5a97",
          "sha256": "0bce2393dcb354db52ed6c3c1d701698d0d397d5ecad1d997042c1184acb07da",
          "sha1": "68abcd2b2ffc18a2d4776492a43740ef85917776",
          "md5": "0109cfcec33b2aa9af038063f98345f3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.9-sources.jar",
          "url": "runelite-api-3.3.9-sources.jar",
          "size": 892214,
          "sha512": "4d315b07204dde1893490f44b01aeb88828f102dad744f8fdd98f5dc3061c75c51decaac50813e3a2bf129f367f57ec4023a963c42f543b05c725832d42d766f",
          "sha256": "0db4b90c345073afb0038643b57f7795026eea8e4ba030acaa97cc58858d89c1",
          "sha1": "1afc2f9841cd03624cc2ef1e8c34b214ff26e1a3",
          "md5": "92eedad919e204580dcab47703885312"
        }
      ]
    }
  ]
}
