{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "ohvik6533vgwjjlgurbourb26y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.7.jar",
          "url": "injected-client-1.6.7.jar",
          "size": 2266350,
          "sha512": "66a3ae9b6c5db4bc2095a64f0178c3b5030bd6d834240b2d9111b804c78531f60d2bce29e46dbfb17e7fd1261ba4250c61f12e6140c7a1a59e03f3f2b82f6c87",
          "sha256": "51fe20423faccf0cff737e1a70d1399d0bbd46f2c6d5da39bcb2fb7046ad981a",
          "sha1": "5a7fd1a0c2d9a6999192f604d62065f950c7b0ca",
          "md5": "f6689f7b550c736d3b7923d8893c1e57"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.7.jar",
          "url": "injected-client-1.6.7.jar",
          "size": 2266350,
          "sha512": "66a3ae9b6c5db4bc2095a64f0178c3b5030bd6d834240b2d9111b804c78531f60d2bce29e46dbfb17e7fd1261ba4250c61f12e6140c7a1a59e03f3f2b82f6c87",
          "sha256": "51fe20423faccf0cff737e1a70d1399d0bbd46f2c6d5da39bcb2fb7046ad981a",
          "sha1": "5a7fd1a0c2d9a6999192f604d62065f950c7b0ca",
          "md5": "f6689f7b550c736d3b7923d8893c1e57"
        }
      ]
    }
  ]
}
