{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "3yeprqic7nhydhhejnplopuewq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.7.jar",
          "url": "injected-client-1.6.7.jar",
          "size": 2265954,
          "sha512": "388953e678616b3b7b6ca6924832205cf1fe03bb6cb64143a55d9d0a52736efa1414484add11922ac58b95fdd76b57ec3e9e965c6f93068bc82dad21f14df429",
          "sha256": "82258ab8b146f90c58c999502840a4b9129bec3191360bb17421467653e26a59",
          "sha1": "7270917e2776456d0e75b611e8df70708c748d82",
          "md5": "1c52bd2235b8da4bcf9154fb6505a7eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.7.jar",
          "url": "injected-client-1.6.7.jar",
          "size": 2265954,
          "sha512": "388953e678616b3b7b6ca6924832205cf1fe03bb6cb64143a55d9d0a52736efa1414484add11922ac58b95fdd76b57ec3e9e965c6f93068bc82dad21f14df429",
          "sha256": "82258ab8b146f90c58c999502840a4b9129bec3191360bb17421467653e26a59",
          "sha1": "7270917e2776456d0e75b611e8df70708c748d82",
          "md5": "1c52bd2235b8da4bcf9154fb6505a7eb"
        }
      ]
    }
  ]
}
