{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "qwkihedazrfibkaaa45s3q2vmu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.7.jar",
          "url": "injected-client-1.6.7.jar",
          "size": 2266350,
          "sha512": "69c5372823a025eea34671f89307eaae9b09f7538408ae243a2f1ada4e69ad8ff5a2608408a182d5767557d131a7d828d5b803ef3b85af3251c171dde7c90968",
          "sha256": "23550c60332c6ad400a019ac1f5f7a4ef6ed19ae7a9d1bcde89a433a1dc4f7b2",
          "sha1": "a0b0e9df2591716096414219c3bbbca81c5054a9",
          "md5": "924252893d4b8bb3046fa9101cb14a81"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.7.jar",
          "url": "injected-client-1.6.7.jar",
          "size": 2266350,
          "sha512": "69c5372823a025eea34671f89307eaae9b09f7538408ae243a2f1ada4e69ad8ff5a2608408a182d5767557d131a7d828d5b803ef3b85af3251c171dde7c90968",
          "sha256": "23550c60332c6ad400a019ac1f5f7a4ef6ed19ae7a9d1bcde89a433a1dc4f7b2",
          "sha1": "a0b0e9df2591716096414219c3bbbca81c5054a9",
          "md5": "924252893d4b8bb3046fa9101cb14a81"
        }
      ]
    }
  ]
}
