{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "nfciutv2ujbjdabtzzanx67oxe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.2.0.jar",
          "url": "runescape-api-3.2.0.jar",
          "size": 55416,
          "sha512": "98f42d02d6ac09d9d4fc4709b561ab9ba8569ce8fa8308ef8bd38d8783f228fa3f37dc45793e7fea260fc75607a825a39438a57ac66b945c037473342cde5512",
          "sha256": "08f9531711be608895bea08437bf993bd9e9176d862512d2ee936127c7c3190a",
          "sha1": "2733596401d0707e5ee6dfafe48440724a1a0803",
          "md5": "e5228db4bc82e0dad34c8b14f705c5a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.2.0.jar",
          "url": "runescape-api-3.2.0.jar",
          "size": 55416,
          "sha512": "98f42d02d6ac09d9d4fc4709b561ab9ba8569ce8fa8308ef8bd38d8783f228fa3f37dc45793e7fea260fc75607a825a39438a57ac66b945c037473342cde5512",
          "sha256": "08f9531711be608895bea08437bf993bd9e9176d862512d2ee936127c7c3190a",
          "sha1": "2733596401d0707e5ee6dfafe48440724a1a0803",
          "md5": "e5228db4bc82e0dad34c8b14f705c5a8"
        }
      ]
    }
  ]
}
