{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "6v4fg4y7fzhu5bfris2fjbgutm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.3.jar",
          "url": "runescape-api-3.3.3.jar",
          "size": 103485,
          "sha512": "3e34842c338a6a69ebac793aaf0fa3249c56cc40e1f91447d98d920ed96573a823d2f955a7af17397dabf175b2e5cc662bb0bec41c30b8918b1c77b1f0e26d86",
          "sha256": "faac4764718b57fbe95e44996667df3802ae6bf22198f7c047202e49545ec7e3",
          "sha1": "bed8121b75df4db97a9115555230884d893106d8",
          "md5": "b67b0fb10fbb7453c3af7965f766398c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.3.jar",
          "url": "runescape-api-3.3.3.jar",
          "size": 103485,
          "sha512": "3e34842c338a6a69ebac793aaf0fa3249c56cc40e1f91447d98d920ed96573a823d2f955a7af17397dabf175b2e5cc662bb0bec41c30b8918b1c77b1f0e26d86",
          "sha256": "faac4764718b57fbe95e44996667df3802ae6bf22198f7c047202e49545ec7e3",
          "sha1": "bed8121b75df4db97a9115555230884d893106d8",
          "md5": "b67b0fb10fbb7453c3af7965f766398c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.3-sources.jar",
          "url": "runescape-api-3.3.3-sources.jar",
          "size": 99587,
          "sha512": "9fae8421d1a2d094a3faf4f29d73cb0be8d730b371fda431a77b161c5e30a27d6006d2766583e3f8e05b13374992b59ba4aaf14fd28179cae56111cda3a42c0f",
          "sha256": "e8e62d04c99b01295ea2fc49096d0af437653349be29f6727b085208ea7ae46b",
          "sha1": "bb5778a165de8b6760bd7e6593838ef6eb0b6123",
          "md5": "25b7380b8fd8b9ce5f07faf0d1a0aff7"
        }
      ]
    }
  ]
}
