{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "66kqjmg7lrg33guig5udmisnmy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.3.jar",
          "url": "runescape-api-3.3.3.jar",
          "size": 103485,
          "sha512": "b0f1ed3ac276bb3e5b9c25ba2f385e145aaa0114e92f41e59edc1e40be1391b00d0e3218031a6a80ebb220b8bc68eb13da0ed5af3445eb9174c8b1e3f32912aa",
          "sha256": "24a3489b09dd485aa04cd87a1f71ae6af2c7b8ca7f40505ac56516edc8a9e7ff",
          "sha1": "7aa7e5bc1f54edb777c14633980eeae6a6fe89b0",
          "md5": "c712aa7fa3b3d86289b112d99f76ea8e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.3.jar",
          "url": "runescape-api-3.3.3.jar",
          "size": 103485,
          "sha512": "b0f1ed3ac276bb3e5b9c25ba2f385e145aaa0114e92f41e59edc1e40be1391b00d0e3218031a6a80ebb220b8bc68eb13da0ed5af3445eb9174c8b1e3f32912aa",
          "sha256": "24a3489b09dd485aa04cd87a1f71ae6af2c7b8ca7f40505ac56516edc8a9e7ff",
          "sha1": "7aa7e5bc1f54edb777c14633980eeae6a6fe89b0",
          "md5": "c712aa7fa3b3d86289b112d99f76ea8e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.3-sources.jar",
          "url": "runescape-api-3.3.3-sources.jar",
          "size": 99587,
          "sha512": "e36a6b292f5ab44af5f6d8f504401cdca0c431247b9dbb3073fdf87440071ade166f11754505ffb3455a08eb9d0ff3f5b5be9ddc3c30b6ee9ed5b1b5df4c1a2d",
          "sha256": "d84c758b6f3a908bbfa7801cc1f051ac6d0b049310d5dea300201b5517ecf332",
          "sha1": "07c2674e6b84b8611fdcd05115881e7eb1e75e0d",
          "md5": "e919f5ada910569b6e70a7e065bb94f4"
        }
      ]
    }
  ]
}
