{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "bclice7o7vgdbg2hmmze3s6kpe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6.jar",
          "url": "runescape-api-1.6.6.jar",
          "size": 55272,
          "sha512": "2f561aad98ba557d8b99771256889e7661d4ad4b103f195bf6338d41868ef61c95168ad1ba5b79647517412e4e659e3301aa8cbdfe87119247cc4b72fe6f9706",
          "sha256": "53fda116faa24b08156cdda956bd6c8b4ec755f9da424cff3b2d4d740942d39a",
          "sha1": "059c1a1bc2b70298ba53dc641c544688ce40dc32",
          "md5": "028d085e0c9664203236a5905828a272"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6.jar",
          "url": "runescape-api-1.6.6.jar",
          "size": 55272,
          "sha512": "2f561aad98ba557d8b99771256889e7661d4ad4b103f195bf6338d41868ef61c95168ad1ba5b79647517412e4e659e3301aa8cbdfe87119247cc4b72fe6f9706",
          "sha256": "53fda116faa24b08156cdda956bd6c8b4ec755f9da424cff3b2d4d740942d39a",
          "sha1": "059c1a1bc2b70298ba53dc641c544688ce40dc32",
          "md5": "028d085e0c9664203236a5905828a272"
        }
      ]
    }
  ]
}
