{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "cache",
    "version": "187.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "fywy2bzk6jbi5jmgbg4fnbm43m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cache-187.0-SNAPSHOT.jar",
          "url": "cache-187.0-20200117.045355-1.jar",
          "size": 375578,
          "sha512": "a2f6585f0fefe9729265d41484876645db6a70a58297bb91daf792ffb1bf64b540260617b0226f53ee6d646d903684bf087dbc92b27ad8cb436953ea8170d835",
          "sha256": "242a0d94de27fb656d820f58c62ac9fe48b7ad1c0edddd60626b337beb5e5eae",
          "sha1": "32e12c5cd4427096a5e54d9d52e1bb4cde2a1cf4",
          "md5": "81a32c4bc005c2f04cfc0cacf9415fb3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.10"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.44.Final"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4-runtime",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.19"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "cache-187.0-SNAPSHOT.jar",
          "url": "cache-187.0-20200117.045355-1.jar",
          "size": 375578,
          "sha512": "a2f6585f0fefe9729265d41484876645db6a70a58297bb91daf792ffb1bf64b540260617b0226f53ee6d646d903684bf087dbc92b27ad8cb436953ea8170d835",
          "sha256": "242a0d94de27fb656d820f58c62ac9fe48b7ad1c0edddd60626b337beb5e5eae",
          "sha1": "32e12c5cd4427096a5e54d9d52e1bb4cde2a1cf4",
          "md5": "81a32c4bc005c2f04cfc0cacf9415fb3"
        }
      ]
    }
  ]
}
