{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "cache",
    "version": "187.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "oq545ombxfg7jgl665kqo3bjpy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cache-187.0-SNAPSHOT.jar",
          "url": "cache-187.0-20200117.032720-1.jar",
          "size": 375578,
          "sha512": "b5e2e98c381ead36a7b50992edf36b250f8b7180fb411d5721dfea66037a92b1ae8215a298be8b7368309b9f2a4ac061315c0b80a8992a224f798ad9ed870d6e",
          "sha256": "7c769d6b12229eff175d0fcb3fc7b8db9cb9f285ac3c814cfea78312884627b8",
          "sha1": "7510adf91d2b6f06d0a3ffcafaf0d2673852cc56",
          "md5": "25be5aba11d5a388dc5398ea8a00296e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.10"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.44.Final"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4-runtime",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.19"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "cache-187.0-SNAPSHOT.jar",
          "url": "cache-187.0-20200117.032720-1.jar",
          "size": 375578,
          "sha512": "b5e2e98c381ead36a7b50992edf36b250f8b7180fb411d5721dfea66037a92b1ae8215a298be8b7368309b9f2a4ac061315c0b80a8992a224f798ad9ed870d6e",
          "sha256": "7c769d6b12229eff175d0fcb3fc7b8db9cb9f285ac3c814cfea78312884627b8",
          "sha1": "7510adf91d2b6f06d0a3ffcafaf0d2673852cc56",
          "md5": "25be5aba11d5a388dc5398ea8a00296e"
        }
      ]
    }
  ]
}
