{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "5jyhhj26ufg2tcbfo6rjpcshbm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.9.jar",
          "url": "runelite-api-1.6.9.jar",
          "size": 1162158,
          "sha512": "77adbbe4162a908fc0ad8c25c0cae5c2b3c0eadd49844d50135e47354ac232d21708a9652a35815e02347f1f8d1b96edce14eceac6d59b21812c0003c96e6ae7",
          "sha256": "b7ce0d6fa64f409b38398be4f97d4cb8f110ac5b801a1a3892c4d37b7b3f4156",
          "sha1": "f0e3e5f1b977b3c1382c6879926a9b220977e5c2",
          "md5": "20e858bd027fc7abbaf258439c04caf9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.9.jar",
          "url": "runelite-api-1.6.9.jar",
          "size": 1162158,
          "sha512": "77adbbe4162a908fc0ad8c25c0cae5c2b3c0eadd49844d50135e47354ac232d21708a9652a35815e02347f1f8d1b96edce14eceac6d59b21812c0003c96e6ae7",
          "sha256": "b7ce0d6fa64f409b38398be4f97d4cb8f110ac5b801a1a3892c4d37b7b3f4156",
          "sha1": "f0e3e5f1b977b3c1382c6879926a9b220977e5c2",
          "md5": "20e858bd027fc7abbaf258439c04caf9"
        }
      ]
    }
  ]
}
