{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "evnul2g6szeq5jpwhsr7qug7li"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.6.jar",
          "url": "injected-client-3.3.6.jar",
          "size": 2253877,
          "sha512": "a4f37b785f8456c8e0e2b8db9440cf2698491cadd59c5ba66eef0bbc1037b6ec4fcb14ca44babdbbcac3fb70b367005cc9a81ff2efb5d9c32a30cf969f0df071",
          "sha256": "7d1abd17eb80922f6efaf1e20b1d020f2b50ee1dd22aef6dd82ddbf9f4a40819",
          "sha1": "013d54e8ecae29cb4a55c70520a6b137de760a2c",
          "md5": "c2e5b7cde2c773130eb648a3746bf88a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.6.jar",
          "url": "injected-client-3.3.6.jar",
          "size": 2253877,
          "sha512": "a4f37b785f8456c8e0e2b8db9440cf2698491cadd59c5ba66eef0bbc1037b6ec4fcb14ca44babdbbcac3fb70b367005cc9a81ff2efb5d9c32a30cf969f0df071",
          "sha256": "7d1abd17eb80922f6efaf1e20b1d020f2b50ee1dd22aef6dd82ddbf9f4a40819",
          "sha1": "013d54e8ecae29cb4a55c70520a6b137de760a2c",
          "md5": "c2e5b7cde2c773130eb648a3746bf88a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.6-sources.jar",
          "url": "injected-client-3.3.6-sources.jar",
          "size": 261,
          "sha512": "a91c0ed9820935c7007c5c6b0a326a8437ad9cde1bcd17fb9353cd7f989723304ef9774e8c393b46df4ad18c12745c2f5a2b6065dfe6981890a2f5d1764d292f",
          "sha256": "09106a551752cc8896cf4e49ba9cdda0e51987300ce12a1a500abfd5f4714459",
          "sha1": "7e4b651c243d8710a369542412ed8ca5983429ce",
          "md5": "ec9d3880fb282c50efca5348ac5b63ca"
        },
        {
          "name": "injected-client-3.3.6.jar",
          "url": "injected-client-3.3.6.jar",
          "size": 2253877,
          "sha512": "a4f37b785f8456c8e0e2b8db9440cf2698491cadd59c5ba66eef0bbc1037b6ec4fcb14ca44babdbbcac3fb70b367005cc9a81ff2efb5d9c32a30cf969f0df071",
          "sha256": "7d1abd17eb80922f6efaf1e20b1d020f2b50ee1dd22aef6dd82ddbf9f4a40819",
          "sha1": "013d54e8ecae29cb4a55c70520a6b137de760a2c",
          "md5": "c2e5b7cde2c773130eb648a3746bf88a"
        }
      ]
    }
  ]
}
