{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "6pdfxs5bcrhepowkvucwbyg6om"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.6.jar",
          "url": "injected-client-3.3.6.jar",
          "size": 2253165,
          "sha512": "cf75a7d15b4de9139b26decb26df22a0ab9c32600efc786ff60a0285e055707174f281fe08f0631e28f952801d4f91ec67f29550e56b398e9d076d9fc55daeda",
          "sha256": "7b8d1dbd3670d1822ed4b3e46efd63e2005d010068a1519df13eef226ce71d16",
          "sha1": "618919edfcaaf7193c5dfe6f20642d24adfae41d",
          "md5": "d9f009ff6d350d97f92b0563dcbdfcc7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.6.jar",
          "url": "injected-client-3.3.6.jar",
          "size": 2253165,
          "sha512": "cf75a7d15b4de9139b26decb26df22a0ab9c32600efc786ff60a0285e055707174f281fe08f0631e28f952801d4f91ec67f29550e56b398e9d076d9fc55daeda",
          "sha256": "7b8d1dbd3670d1822ed4b3e46efd63e2005d010068a1519df13eef226ce71d16",
          "sha1": "618919edfcaaf7193c5dfe6f20642d24adfae41d",
          "md5": "d9f009ff6d350d97f92b0563dcbdfcc7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.6-sources.jar",
          "url": "injected-client-3.3.6-sources.jar",
          "size": 261,
          "sha512": "9af531197f0eb393acd061b4809f06b1365b028876b6519f28275b3b70cc880f0f850727bba9c1120ab753ffe82bb443127c5288c5b59be04e5c61a15701b358",
          "sha256": "f04e10cd7377e692097c2ed65368070f47dd52652a95bbddfa4c2707a443ab2c",
          "sha1": "5abe222d64afbe0f8eb343fffe4f9b013ce47b54",
          "md5": "0a2c44e87c7db84821c0272374166750"
        },
        {
          "name": "injected-client-3.3.6.jar",
          "url": "injected-client-3.3.6.jar",
          "size": 2253165,
          "sha512": "cf75a7d15b4de9139b26decb26df22a0ab9c32600efc786ff60a0285e055707174f281fe08f0631e28f952801d4f91ec67f29550e56b398e9d076d9fc55daeda",
          "sha256": "7b8d1dbd3670d1822ed4b3e46efd63e2005d010068a1519df13eef226ce71d16",
          "sha1": "618919edfcaaf7193c5dfe6f20642d24adfae41d",
          "md5": "d9f009ff6d350d97f92b0563dcbdfcc7"
        }
      ]
    }
  ]
}
