{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "75hjafas2bcyriu3ba6eqlelyi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.0.7.jar",
          "url": "http-api-3.0.7.jar",
          "size": 164353,
          "sha512": "2449dd675a7b742c45d7ed9cb747695f136a9578153aac75ebbe981ecffde0822aa84069ed2f73b514e5fd2220c00bdc25653aae5fed09e173c60da14d043fa2",
          "sha256": "6781115a09dc8455fbba6d41184dbcabffc7657ad73ec91f0433c8843f4d2bce",
          "sha1": "898e4c6d999395e147b837068512549fada808af",
          "md5": "72f3e96484be48abad4886295a6a14cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.18"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.0.7.jar",
          "url": "http-api-3.0.7.jar",
          "size": 164353,
          "sha512": "2449dd675a7b742c45d7ed9cb747695f136a9578153aac75ebbe981ecffde0822aa84069ed2f73b514e5fd2220c00bdc25653aae5fed09e173c60da14d043fa2",
          "sha256": "6781115a09dc8455fbba6d41184dbcabffc7657ad73ec91f0433c8843f4d2bce",
          "sha1": "898e4c6d999395e147b837068512549fada808af",
          "md5": "72f3e96484be48abad4886295a6a14cf"
        }
      ]
    }
  ]
}
