{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "36hbq5herfeilevtvng3rccmvu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.0.7.jar",
          "url": "http-api-3.0.7.jar",
          "size": 164354,
          "sha512": "1c6b39874034d866cca3aa8fa7a431067276d561550e114738dfb7cb482ee5d7125ea9474b4e45bfb2087feb8836778d4a132379bdecc654f19651b6868317b0",
          "sha256": "da8ec5ed3284ead5e455dd23b8d8a5ef838a8f36b78fd86b3297a3bea5a28bce",
          "sha1": "ea8581c905a235c3fc94475e12bc8681b9a8358d",
          "md5": "fb593bc5b877d08888f3d61c76db917e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.18"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.0.7.jar",
          "url": "http-api-3.0.7.jar",
          "size": 164354,
          "sha512": "1c6b39874034d866cca3aa8fa7a431067276d561550e114738dfb7cb482ee5d7125ea9474b4e45bfb2087feb8836778d4a132379bdecc654f19651b6868317b0",
          "sha256": "da8ec5ed3284ead5e455dd23b8d8a5ef838a8f36b78fd86b3297a3bea5a28bce",
          "sha1": "ea8581c905a235c3fc94475e12bc8681b9a8358d",
          "md5": "fb593bc5b877d08888f3d61c76db917e"
        }
      ]
    }
  ]
}
