{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "gge6gokimjauthbbbjofq4r6su"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.6.jar",
          "url": "http-api-1.6.6.jar",
          "size": 165767,
          "sha512": "2eae610f5c769ed95f183d76b99866a536197a156390bd7502e0e8208760a8c33fd6b545e5a04db7a2cc1337f448de35387a606d9391202b05083386f422b455",
          "sha256": "315aa9dcb5020be3748103574310fc123d1e3e55cca61767f06ae38cb03a1b54",
          "sha1": "965adcabea501d3f3ba787d53b81d5f2f5210410",
          "md5": "59ce36feb9ac16332e8b158eaa26e5e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.6.jar",
          "url": "http-api-1.6.6.jar",
          "size": 165767,
          "sha512": "2eae610f5c769ed95f183d76b99866a536197a156390bd7502e0e8208760a8c33fd6b545e5a04db7a2cc1337f448de35387a606d9391202b05083386f422b455",
          "sha256": "315aa9dcb5020be3748103574310fc123d1e3e55cca61767f06ae38cb03a1b54",
          "sha1": "965adcabea501d3f3ba787d53b81d5f2f5210410",
          "md5": "59ce36feb9ac16332e8b158eaa26e5e9"
        }
      ]
    }
  ]
}
