{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "jnxocuj2g5eblo4ooxv4nrjtdm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.6.jar",
          "url": "http-api-1.6.6.jar",
          "size": 165767,
          "sha512": "0529d68353db9d5c9ad5264eec324217828059b34f6f168907b5b815af2e9f825056bfae6a8822d0d7ba8f0f3ebc58b86c5355f04cf732ac744bac5a25c31e8d",
          "sha256": "51fd97220103f3a482a69ac15e7a3e18a960d25bc1c8a87400d93cdcefcc5024",
          "sha1": "dbcb90978f0adb52ea0b1044ddbea4bd57e51df0",
          "md5": "ed981f98acb2c5f8de461ff11436da3c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.6.jar",
          "url": "http-api-1.6.6.jar",
          "size": 165767,
          "sha512": "0529d68353db9d5c9ad5264eec324217828059b34f6f168907b5b815af2e9f825056bfae6a8822d0d7ba8f0f3ebc58b86c5355f04cf732ac744bac5a25c31e8d",
          "sha256": "51fd97220103f3a482a69ac15e7a3e18a960d25bc1c8a87400d93cdcefcc5024",
          "sha1": "dbcb90978f0adb52ea0b1044ddbea4bd57e51df0",
          "md5": "ed981f98acb2c5f8de461ff11436da3c"
        }
      ]
    }
  ]
}
