{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "rb5yuoxqkreankmnlkb74x3pse"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.6.jar",
          "url": "http-api-1.6.6.jar",
          "size": 165768,
          "sha512": "ed4814f21847e7979c532a946e2124ea4151301273f0f07669e8a1a5fc3ff181c98d6942287ddd6c36942bb8b5272aff450af84449572c1fc66a927353296f8f",
          "sha256": "1dba0614ae396126460bb9e85ec1500b1a63377737ec4ebe1a1eb9504603e7aa",
          "sha1": "6ae74ed424554b78507e8c3f41534bf8afa03340",
          "md5": "30da1fd01df55e1744931d82f9ba4a8b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.6.jar",
          "url": "http-api-1.6.6.jar",
          "size": 165768,
          "sha512": "ed4814f21847e7979c532a946e2124ea4151301273f0f07669e8a1a5fc3ff181c98d6942287ddd6c36942bb8b5272aff450af84449572c1fc66a927353296f8f",
          "sha256": "1dba0614ae396126460bb9e85ec1500b1a63377737ec4ebe1a1eb9504603e7aa",
          "sha1": "6ae74ed424554b78507e8c3f41534bf8afa03340",
          "md5": "30da1fd01df55e1744931d82f9ba4a8b"
        }
      ]
    }
  ]
}
