{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "cqq7nc66dva4patoegzemqvkba"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.4"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.4.jar",
          "url": "runescape-api-3.3.4.jar",
          "size": 103527,
          "sha512": "73c02692f6dd589dee16113a10992967f6caf50e974f5e74b847ccfcae33fe464c4c2468ae887dac2c685ad13563e63f90e6fd5832d13b88903d75de2dc9e0af",
          "sha256": "bd8aa24a0aaa03399546e54e8d192d52b2b3af73b1ed23fe6ee0545a5cb12ce8",
          "sha1": "7ff60bbf0065246fae606f2c1af2711750ca1897",
          "md5": "c4870e1886d207606871f8cab9714d04"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.4"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.4.jar",
          "url": "runescape-api-3.3.4.jar",
          "size": 103527,
          "sha512": "73c02692f6dd589dee16113a10992967f6caf50e974f5e74b847ccfcae33fe464c4c2468ae887dac2c685ad13563e63f90e6fd5832d13b88903d75de2dc9e0af",
          "sha256": "bd8aa24a0aaa03399546e54e8d192d52b2b3af73b1ed23fe6ee0545a5cb12ce8",
          "sha1": "7ff60bbf0065246fae606f2c1af2711750ca1897",
          "md5": "c4870e1886d207606871f8cab9714d04"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.4-sources.jar",
          "url": "runescape-api-3.3.4-sources.jar",
          "size": 99648,
          "sha512": "7acd6c3bc7c4f5e1da844fbb29d6fa2220e0ef6a5fa04a2020f0e58bbf26c1a1a458ddb4f93a3e5079d78081cbe08dba5cf43097aefc4c0a6e976d11504823d0",
          "sha256": "1fa8da469a6bd3dd464c9a9922a105b8e328d9732b8f78536c096dcfcb74c47c",
          "sha1": "f81397241f17ebc27584214a86a47018e2b0b103",
          "md5": "4bec0797856a60d25917139d1eee96e0"
        }
      ]
    }
  ]
}
