{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "5pbwxfuunbb6flmlhxndwktfoi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.4"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.4.jar",
          "url": "runescape-api-3.3.4.jar",
          "size": 103527,
          "sha512": "e70be4a4ca4ca6fc647e706f01205f8d11d350ac80600395bee5290ce62fecb8d473ce0f3749a74bef74fe35d872f03efef2e584e6870d9cadabef138d41cf67",
          "sha256": "7578adff7f948927ed663a3e44c117146fac61a0b8164192d7723016ecf22241",
          "sha1": "0981bca86716a624463d88b051033c4634b0f216",
          "md5": "2f7ceb761186ba319bc31b5fadb2e7f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.4"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.4.jar",
          "url": "runescape-api-3.3.4.jar",
          "size": 103527,
          "sha512": "e70be4a4ca4ca6fc647e706f01205f8d11d350ac80600395bee5290ce62fecb8d473ce0f3749a74bef74fe35d872f03efef2e584e6870d9cadabef138d41cf67",
          "sha256": "7578adff7f948927ed663a3e44c117146fac61a0b8164192d7723016ecf22241",
          "sha1": "0981bca86716a624463d88b051033c4634b0f216",
          "md5": "2f7ceb761186ba319bc31b5fadb2e7f2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.4-sources.jar",
          "url": "runescape-api-3.3.4-sources.jar",
          "size": 99648,
          "sha512": "2c59788841cf10863f99664449436dcd210ae4fdfce913fd75c9522080831ed425a74047f1ebc5bb6ad09c811d7e6289381faed21ba10740f73951e20d76cd52",
          "sha256": "7cf2b6e5b4931c619583de6da4ce71c3c61e60774becbe8c7fba9cc4fa0c5e3e",
          "sha1": "18f7ca88a9ca31991c63e915469a5d5eb24b787d",
          "md5": "17593cd61a6985b749a6373064ad18b5"
        }
      ]
    }
  ]
}
