{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "yfkbmcdwgzczna64ihqkt2icd4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.4"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.4.jar",
          "url": "runescape-api-3.3.4.jar",
          "size": 103527,
          "sha512": "e8ec2d20187254dc4d4fb6384f87f1fba79036397390a38336c19fad1beb499e08af490a0db113c873bf1cbd3d9c4b8a727254351c6a526c03cbd0118a71658e",
          "sha256": "02c0573f38dd366201bb26d2245107a743d4f3836852b8416c8b7492e5aedc5e",
          "sha1": "6fdcd177536fce0acdf6dfa73b16ec8fd46ee62a",
          "md5": "6da5f1d8af0568729bc4eb6c194eee4e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.4"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.4.jar",
          "url": "runescape-api-3.3.4.jar",
          "size": 103527,
          "sha512": "e8ec2d20187254dc4d4fb6384f87f1fba79036397390a38336c19fad1beb499e08af490a0db113c873bf1cbd3d9c4b8a727254351c6a526c03cbd0118a71658e",
          "sha256": "02c0573f38dd366201bb26d2245107a743d4f3836852b8416c8b7492e5aedc5e",
          "sha1": "6fdcd177536fce0acdf6dfa73b16ec8fd46ee62a",
          "md5": "6da5f1d8af0568729bc4eb6c194eee4e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.4-sources.jar",
          "url": "runescape-api-3.3.4-sources.jar",
          "size": 99648,
          "sha512": "abb7180983e0954ba1ee9f2b79b9e6c65aebca9e88bb7cc2dfb490444c8ed3f16e5a65ceea53595ca9658cf0074e82afdae08ccc44ddc21dd1cad0f2f53d8047",
          "sha256": "1c0c3a618676576bb21055cc4c8cdbc2ac25047d3125ea1aa70929badf408bd3",
          "sha1": "5226f9a7f97dadae5438f3b7e78bcfe3f78887c5",
          "md5": "b1c0343a55abb30d9e8aac9f37248842"
        }
      ]
    }
  ]
}
