{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "di32qfpgqzhqvkussohihqegoe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.5-SNAPSHOT.jar",
          "url": "runelite-api-1.6.5-20200128.004105-1.jar",
          "size": 1149769,
          "sha512": "58a6193ba9fa64c92d0dcd1b964505548a06efa0d6b94660231c2a39e6f309375f22e4dcbe7dbce428520913d816f3824bf91b06109c543503f588fd0ca8ded6",
          "sha256": "49a248397512cac761cf9566bd60d70add03a54e019c7fefe891f56afdfa4dce",
          "sha1": "0a5e45456b77476f4aa961c5e2582a7a2e871b96",
          "md5": "770788987591fef9651d564bb4ed6431"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.5-SNAPSHOT.jar",
          "url": "runelite-api-1.6.5-20200128.004105-1.jar",
          "size": 1149769,
          "sha512": "58a6193ba9fa64c92d0dcd1b964505548a06efa0d6b94660231c2a39e6f309375f22e4dcbe7dbce428520913d816f3824bf91b06109c543503f588fd0ca8ded6",
          "sha256": "49a248397512cac761cf9566bd60d70add03a54e019c7fefe891f56afdfa4dce",
          "sha1": "0a5e45456b77476f4aa961c5e2582a7a2e871b96",
          "md5": "770788987591fef9651d564bb4ed6431"
        }
      ]
    }
  ]
}
