{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "35o7ugfvczalxmxd53hde2sfpa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.5-SNAPSHOT.jar",
          "url": "runelite-api-1.6.5-20200126.000916-1.jar",
          "size": 1149312,
          "sha512": "cb521c89d5fb3e322bf2e278ae37426a6f4c6047f53b46b693ae529a19d17ace2295caf990d240502bbd66da894c8ac113f386cc35910bdd92fb66c9ed78ac66",
          "sha256": "fa3115178e95deb174f26f0aa79ecdabc2c9da0e46ce96d2b12c10353dc45245",
          "sha1": "e93fdc58e29ec9b3e21ead57805e79389d874d13",
          "md5": "28e4023f05097ae596d1c1fdb11d9a1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.5-SNAPSHOT.jar",
          "url": "runelite-api-1.6.5-20200126.000916-1.jar",
          "size": 1149312,
          "sha512": "cb521c89d5fb3e322bf2e278ae37426a6f4c6047f53b46b693ae529a19d17ace2295caf990d240502bbd66da894c8ac113f386cc35910bdd92fb66c9ed78ac66",
          "sha256": "fa3115178e95deb174f26f0aa79ecdabc2c9da0e46ce96d2b12c10353dc45245",
          "sha1": "e93fdc58e29ec9b3e21ead57805e79389d874d13",
          "md5": "28e4023f05097ae596d1c1fdb11d9a1f"
        }
      ]
    }
  ]
}
