{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "ohxcde6lofempnsnf753wfon7e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.5-SNAPSHOT.jar",
          "url": "runelite-api-1.6.5-20200124.000811-1.jar",
          "size": 1149312,
          "sha512": "4c40db66e5d720f64a761e9c21564e52b31c2023e651f0cc4deec104c59b61d0dab2ee703d2d01f2f4fa2fe5cff2a49ca88203277b95446a5509ccb426605e42",
          "sha256": "4d59acb29198a8532a05019bd2cba3320b3f6299d67b386d6bedce78665f3bc7",
          "sha1": "279056c5acc710d8ea98c63fa287cbbf80475a8c",
          "md5": "978107f7222345b56aff82a6dc8a105a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.5-SNAPSHOT.jar",
          "url": "runelite-api-1.6.5-20200124.000811-1.jar",
          "size": 1149312,
          "sha512": "4c40db66e5d720f64a761e9c21564e52b31c2023e651f0cc4deec104c59b61d0dab2ee703d2d01f2f4fa2fe5cff2a49ca88203277b95446a5509ccb426605e42",
          "sha256": "4d59acb29198a8532a05019bd2cba3320b3f6299d67b386d6bedce78665f3bc7",
          "sha1": "279056c5acc710d8ea98c63fa287cbbf80475a8c",
          "md5": "978107f7222345b56aff82a6dc8a105a"
        }
      ]
    }
  ]
}
