{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "4xf677b2avckpl5ja35dtrbb34"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.5-SNAPSHOT.jar",
          "url": "runelite-api-1.6.5-20200127.000806-1.jar",
          "size": 1149769,
          "sha512": "b99b3788044bd6babd9d897f2e17b33c6005dd7e04285f9a01c99f19f308c77d0212212053c9a263701c81ff5f799dfdab3816f3ae148d6f272bb4cd813cb63b",
          "sha256": "2bd4fb994dae512b57f000472a338c7753287b7b81d223c12e9de284049982ba",
          "sha1": "d1f8a88d457dde4cbe13380717c2e9ae1d11ee05",
          "md5": "bd318f3ec746dd9cc813947f52566389"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.5-SNAPSHOT.jar",
          "url": "runelite-api-1.6.5-20200127.000806-1.jar",
          "size": 1149769,
          "sha512": "b99b3788044bd6babd9d897f2e17b33c6005dd7e04285f9a01c99f19f308c77d0212212053c9a263701c81ff5f799dfdab3816f3ae148d6f272bb4cd813cb63b",
          "sha256": "2bd4fb994dae512b57f000472a338c7753287b7b81d223c12e9de284049982ba",
          "sha1": "d1f8a88d457dde4cbe13380717c2e9ae1d11ee05",
          "md5": "bd318f3ec746dd9cc813947f52566389"
        }
      ]
    }
  ]
}
