{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "m45537v5mbhzxow5r2d2ox6zly"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": []
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.4.1.jar",
          "url": "injected-client-3.4.1.jar",
          "size": 2305281,
          "sha512": "052ee0ead1db4a0ba4d90bf00f13533d4c9c8cf1f005ef7bc12ac8e3233735206d31f5c0685cbc74ece1a2931b88c551dd1932dd0c630c3a11bcf89fd4700190",
          "sha256": "e2c12029db9f71a52da09fed895d9af76f3bea365dff4620610cdd9ea9c325b0",
          "sha1": "142555966aea9d4480773d6e9170124463f8e4e5",
          "md5": "632eb5c34d9263c1d6fed4139f5ea786"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": []
    }
  ]
}
