{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "ki2pqium4zclhiv2tqg3lp7e6i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": []
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.4.1.jar",
          "url": "injected-client-3.4.1.jar",
          "size": 2305281,
          "sha512": "388ecc4d9226673721f3e4ac76e77f4bc650f13a45df85c1652a49f2d68dab84d93a00435baa6b163024af9936e66ff81c1d6846f63dbb92cb98090aea27d112",
          "sha256": "b12b11dd9ac81fd32dd6affb305e3014ee979268ec8949897588d58a997ba067",
          "sha1": "eff673c5bf3f3a766c3f25f832bc19310b74ec82",
          "md5": "ad922515fa10176231302b6b2f7fa75a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": []
    }
  ]
}
