{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ggaw6frbljekpfvvsureab2nea"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.6.jar",
          "url": "runelite-api-3.3.6.jar",
          "size": 1202729,
          "sha512": "4fff3c9052e15bdcb09a4534102b3e1e8345c8d74ff717a4973082543d3a232ee41dd90d1eda6d357154f0df7a04df3952662f74433ccc1d3c509f29c7e16b34",
          "sha256": "14c05cbb8c74cc095a0640aaa21ecd4c7250e42f8a9e3f0fbb0b4947d988fcb0",
          "sha1": "1f88b07b8e7277eda2c97a28c91c3ee93c72687c",
          "md5": "b2839af02d12c9ef5aa4be86b020d88a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.6.jar",
          "url": "runelite-api-3.3.6.jar",
          "size": 1202729,
          "sha512": "4fff3c9052e15bdcb09a4534102b3e1e8345c8d74ff717a4973082543d3a232ee41dd90d1eda6d357154f0df7a04df3952662f74433ccc1d3c509f29c7e16b34",
          "sha256": "14c05cbb8c74cc095a0640aaa21ecd4c7250e42f8a9e3f0fbb0b4947d988fcb0",
          "sha1": "1f88b07b8e7277eda2c97a28c91c3ee93c72687c",
          "md5": "b2839af02d12c9ef5aa4be86b020d88a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.6-sources.jar",
          "url": "runelite-api-3.3.6-sources.jar",
          "size": 881959,
          "sha512": "2ae366440bc15277aa947f9e81fc17a7e3b79a761207d14448bc1837ee600b3252a4e387e4021bd70ee39e09f061d7151ce8bd1a8fd129da0379e26b724bc06c",
          "sha256": "eb5be448d7a5bc70f4e02dd2edc61b286372ed71c33433485ce9cc6d696e015d",
          "sha1": "5d534520720ee492fec28e439f092eb6c3c4e20b",
          "md5": "db3a38c9d08b321b6e536890b5cdebb6"
        }
      ]
    }
  ]
}
