{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "evnul2g6szeq5jpwhsr7qug7li"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.6.jar",
          "url": "runelite-api-3.3.6.jar",
          "size": 1202812,
          "sha512": "7be1aef8dfc0fe8aea0f1441464de9c6118670cf5427d0ccc49599b01efa4e3a762aecff5511e62d18b896efbe422ac48bb29fae2f05271cb00d6fb55b86934a",
          "sha256": "b3668989baa93ef9963f0420343fa8fe6dc89eb67836f52fcadf7ffbcade5a96",
          "sha1": "a53b644f0248467855d92e5944c58f41fa56853d",
          "md5": "dbdf64b05bc5d6bc658eb544d49ce6d3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.6.jar",
          "url": "runelite-api-3.3.6.jar",
          "size": 1202812,
          "sha512": "7be1aef8dfc0fe8aea0f1441464de9c6118670cf5427d0ccc49599b01efa4e3a762aecff5511e62d18b896efbe422ac48bb29fae2f05271cb00d6fb55b86934a",
          "sha256": "b3668989baa93ef9963f0420343fa8fe6dc89eb67836f52fcadf7ffbcade5a96",
          "sha1": "a53b644f0248467855d92e5944c58f41fa56853d",
          "md5": "dbdf64b05bc5d6bc658eb544d49ce6d3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.6-sources.jar",
          "url": "runelite-api-3.3.6-sources.jar",
          "size": 881983,
          "sha512": "ce2cabf2f07f0fcf51ef4c05dc6a493cf24373fdd192e68ed173e49d9abb488acf0ee1761d9c23ba9a2339deb41a7e55ce3630439935fd6ca8faba4bba78abb0",
          "sha256": "f9b4b4775b73b675f381d83bc69005bb48b59f936d25558725dbb2d3caf36fb2",
          "sha1": "7dc848c91a08e55afa2f9f9d6f419de30769d2da",
          "md5": "99fe3611dae9d1b1092c20818db3c24e"
        }
      ]
    }
  ]
}
