{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "giscvrqxazconlvpjcy26uso3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.6.jar",
          "url": "runelite-api-3.3.6.jar",
          "size": 1202812,
          "sha512": "a96a74df0ae483bac610dc4bbef21ffbf76960928ce86cfa9c1e83c6884235df110f5dfa7233e0cf88b5f719913c9de6d5d667861de2c36986eccb5f42b33145",
          "sha256": "648d10bb73e78f0a91c5373d0e6f3ec1764e12ff53c5f98693fb0a80ec710712",
          "sha1": "36dba32ff10bb88029d7957b1234de5e52fff922",
          "md5": "7f0be8876088f27e0bece309718fac11"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.6.jar",
          "url": "runelite-api-3.3.6.jar",
          "size": 1202812,
          "sha512": "a96a74df0ae483bac610dc4bbef21ffbf76960928ce86cfa9c1e83c6884235df110f5dfa7233e0cf88b5f719913c9de6d5d667861de2c36986eccb5f42b33145",
          "sha256": "648d10bb73e78f0a91c5373d0e6f3ec1764e12ff53c5f98693fb0a80ec710712",
          "sha1": "36dba32ff10bb88029d7957b1234de5e52fff922",
          "md5": "7f0be8876088f27e0bece309718fac11"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.6-sources.jar",
          "url": "runelite-api-3.3.6-sources.jar",
          "size": 881983,
          "sha512": "efb221a4ff0a13bfdf299fd9afa0bd460d2275743c0fe8340608872889c069659688859f4f20b11982457fe430a145d592e4631662950f8a66947add084d26c9",
          "sha256": "545fa661b29c6c2fa21401e9248c1ee075b8b507edc1cccfee184783d62504cd",
          "sha1": "01a3a3849b760e425853b45a5704998010501145",
          "md5": "8965bb8178527ec48024ee681c43c6dc"
        }
      ]
    }
  ]
}
