{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "tuigwsl4fvhkndg5oymysyi4jm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.2.2.jar",
          "url": "runelite-api-3.2.2.jar",
          "size": 1177131,
          "sha512": "d983d1038c0d83de4c41607af7332d1935ed603070637b1d21621ed03d605552d80f92cd9c98bbf91b36a9c75d88ce738c80cbcd9d025584a7e1125330f50748",
          "sha256": "6b7d6aefe18b829aac9f7260f77e5efbd5fd7a09adaea212eb8e0d96ee13c873",
          "sha1": "cf2e7b067f14a807b6c4e68da5cbcd6267b40731",
          "md5": "5aee807346392f495b77b36c4f02fe36"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.2.2.jar",
          "url": "runelite-api-3.2.2.jar",
          "size": 1177131,
          "sha512": "d983d1038c0d83de4c41607af7332d1935ed603070637b1d21621ed03d605552d80f92cd9c98bbf91b36a9c75d88ce738c80cbcd9d025584a7e1125330f50748",
          "sha256": "6b7d6aefe18b829aac9f7260f77e5efbd5fd7a09adaea212eb8e0d96ee13c873",
          "sha1": "cf2e7b067f14a807b6c4e68da5cbcd6267b40731",
          "md5": "5aee807346392f495b77b36c4f02fe36"
        }
      ]
    }
  ]
}
