{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "eozc5css2rdz5fb6c4fkiwagdq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.2.2.jar",
          "url": "runelite-api-3.2.2.jar",
          "size": 1177131,
          "sha512": "e1b6c65406574be0d7a3f9fe87924e5e722a695e4a501c29592c0255ef24470c279108886b16c822726241df8d4315554c62259882c9ca2a34d9bf6b4314cce5",
          "sha256": "c280bcde88c0658d791d7f805fe0b7dcaefec20460b55ea2dd1d7692f978b8cc",
          "sha1": "17296c69dc8a9fce8a0d113b02d710a5309d4ce9",
          "md5": "c034ef2859aa0d8842ae16836b663497"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.2.2.jar",
          "url": "runelite-api-3.2.2.jar",
          "size": 1177131,
          "sha512": "e1b6c65406574be0d7a3f9fe87924e5e722a695e4a501c29592c0255ef24470c279108886b16c822726241df8d4315554c62259882c9ca2a34d9bf6b4314cce5",
          "sha256": "c280bcde88c0658d791d7f805fe0b7dcaefec20460b55ea2dd1d7692f978b8cc",
          "sha1": "17296c69dc8a9fce8a0d113b02d710a5309d4ce9",
          "md5": "c034ef2859aa0d8842ae16836b663497"
        }
      ]
    }
  ]
}
