{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "6jsxpgn2gfcqvn64vh3f3v2uzq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.2.2.jar",
          "url": "runelite-api-3.2.2.jar",
          "size": 1177131,
          "sha512": "c8de35f387c026e6c6a29dd863cb2422488ac3f1c980e84750f53305496be4a1af2d29bb1368c5240356f8fe3b4db1451982ab36763b950f6200f7d5b6cf3eb9",
          "sha256": "10789ca19e636f463b1dfbe0c3f10e4c5c8df3a341db35e099604e5cb05d9d36",
          "sha1": "d1b5114e977c73c94ebf7378bd191042f800b336",
          "md5": "2dba7bda24a958f9c3d9266be4f621db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.2.2.jar",
          "url": "runelite-api-3.2.2.jar",
          "size": 1177131,
          "sha512": "c8de35f387c026e6c6a29dd863cb2422488ac3f1c980e84750f53305496be4a1af2d29bb1368c5240356f8fe3b4db1451982ab36763b950f6200f7d5b6cf3eb9",
          "sha256": "10789ca19e636f463b1dfbe0c3f10e4c5c8df3a341db35e099604e5cb05d9d36",
          "sha1": "d1b5114e977c73c94ebf7378bd191042f800b336",
          "md5": "2dba7bda24a958f9c3d9266be4f621db"
        }
      ]
    }
  ]
}
