{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "k5lwdxgx2ne6xofpjqaxgaqsmm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.2.2.jar",
          "url": "injected-client-3.2.2.jar",
          "size": 2252140,
          "sha512": "0b8c68ba6793c409f190e2746e3cfc3f723a3cb6cabb3fdc2411a63116de8529c481f65a84e4eade90faa940e34cd7b81643cbf19d61b94026886fc2781f2943",
          "sha256": "a1fee9de911e4ca7739b432cfe9d7ff19b5288a61d2110aecbe345b85ccb9ebb",
          "sha1": "c7af06a5f2bf13522badc48a97fc9b3e17ae62cc",
          "md5": "ef58c6a37c2c5efac94b5ef2038cb530"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.2.2.jar",
          "url": "injected-client-3.2.2.jar",
          "size": 2252140,
          "sha512": "0b8c68ba6793c409f190e2746e3cfc3f723a3cb6cabb3fdc2411a63116de8529c481f65a84e4eade90faa940e34cd7b81643cbf19d61b94026886fc2781f2943",
          "sha256": "a1fee9de911e4ca7739b432cfe9d7ff19b5288a61d2110aecbe345b85ccb9ebb",
          "sha1": "c7af06a5f2bf13522badc48a97fc9b3e17ae62cc",
          "md5": "ef58c6a37c2c5efac94b5ef2038cb530"
        }
      ]
    }
  ]
}
