{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "iv6li4obfnevhl3zfxj2esjmjm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.2.2.jar",
          "url": "injected-client-3.2.2.jar",
          "size": 2252140,
          "sha512": "a2575cb1baaafaae9a71d4ed28c1108af0d7e20c81bd4b90a72ba6e63c68cf7bd7ad9f2956de1c76904979953645c9951f77f3348f53463790e58f4ba83bb1ee",
          "sha256": "587a68e275ee2e3c07028a70e368cc7f59cada12737057a98fd2f387846f829b",
          "sha1": "f191de1bedf40f62f3a91b8bd8b5f18255bbfc34",
          "md5": "6a4779400c4e402b1b2f7168a09abd54"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.2.2.jar",
          "url": "injected-client-3.2.2.jar",
          "size": 2252140,
          "sha512": "a2575cb1baaafaae9a71d4ed28c1108af0d7e20c81bd4b90a72ba6e63c68cf7bd7ad9f2956de1c76904979953645c9951f77f3348f53463790e58f4ba83bb1ee",
          "sha256": "587a68e275ee2e3c07028a70e368cc7f59cada12737057a98fd2f387846f829b",
          "sha1": "f191de1bedf40f62f3a91b8bd8b5f18255bbfc34",
          "md5": "6a4779400c4e402b1b2f7168a09abd54"
        }
      ]
    }
  ]
}
