{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "evnul2g6szeq5jpwhsr7qug7li"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.6.jar",
          "url": "http-api-3.3.6.jar",
          "size": 154346,
          "sha512": "6f6026d31c8c79b19c3aabad38d783a25400c0a717ef2407bfc1559e30b7583a0919d467c158ff4495ca25e729ce5eb724b6722d2f92ce8d124cf957227664dd",
          "sha256": "31209fdc84165d58956fb78ddf6df05f12aaf2320dc01a99c0fe99fe597c16cf",
          "sha1": "b0e49d03daf9d259b8e78f059451530a11571e8b",
          "md5": "26a3dd96b090c96438f48669c8098c33"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.6"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.6.jar",
          "url": "http-api-3.3.6.jar",
          "size": 154346,
          "sha512": "6f6026d31c8c79b19c3aabad38d783a25400c0a717ef2407bfc1559e30b7583a0919d467c158ff4495ca25e729ce5eb724b6722d2f92ce8d124cf957227664dd",
          "sha256": "31209fdc84165d58956fb78ddf6df05f12aaf2320dc01a99c0fe99fe597c16cf",
          "sha1": "b0e49d03daf9d259b8e78f059451530a11571e8b",
          "md5": "26a3dd96b090c96438f48669c8098c33"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.6-sources.jar",
          "url": "http-api-3.3.6-sources.jar",
          "size": 101951,
          "sha512": "d4368e66602d634826176e20bfb96f3bb6fb21335fedbe3853dfa38e0c94a3bd9f00ce6ce4b0a4d2e305394f2142a5f5d4238013e1db2b199e9852fa03fdd513",
          "sha256": "320ff92a788025df0d6612327dc24868a074634e2fba1c11a28dab7f1731082c",
          "sha1": "8c4ff1873a00b790decb6768dde951a173131ee5",
          "md5": "28ef27f164437e4b990fc1dc723b83ae"
        }
      ]
    }
  ]
}
