{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "6pdfxs5bcrhepowkvucwbyg6om"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.6.jar",
          "url": "http-api-3.3.6.jar",
          "size": 154345,
          "sha512": "7cc447981dffc607da82fe02ae110521b35674ff5164bad5cbf415a9de667f8cd46e1d973db4fc74e172ba15ac7b74f5a54bfe27bdc74f87d0e8069228903c13",
          "sha256": "578ac6b290a8b5acbb37b5949a37b8acd41ee7844bf877acf5cb71ba1539f074",
          "sha1": "34f77ed9b0519d54c3b8a14482feb06a35c752a8",
          "md5": "2c25593c9775350c1fa5e5673ecc71a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.6"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.6.jar",
          "url": "http-api-3.3.6.jar",
          "size": 154345,
          "sha512": "7cc447981dffc607da82fe02ae110521b35674ff5164bad5cbf415a9de667f8cd46e1d973db4fc74e172ba15ac7b74f5a54bfe27bdc74f87d0e8069228903c13",
          "sha256": "578ac6b290a8b5acbb37b5949a37b8acd41ee7844bf877acf5cb71ba1539f074",
          "sha1": "34f77ed9b0519d54c3b8a14482feb06a35c752a8",
          "md5": "2c25593c9775350c1fa5e5673ecc71a8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.6-sources.jar",
          "url": "http-api-3.3.6-sources.jar",
          "size": 101951,
          "sha512": "825b2874a446f4907b7f1915e777852f931f56c52bc2e64027344b0aa6e2dae3b267ede9ff12a70a14c996097a6b098712e6a87b8330b6fe8613d69a2268cd2c",
          "sha256": "5b165afced4a96d70e16c10a7f4b00164bba795712f8c761481f76c232d9917c",
          "sha1": "fe141f0dc55306049a9c5e72746c198f19aab095",
          "md5": "b9ad6070d30e2f1daf69d1a10bfce3f2"
        }
      ]
    }
  ]
}
