{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "cstu7h7ytjhk7c5jq2afpe77xe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.6.jar",
          "url": "http-api-3.3.6.jar",
          "size": 154346,
          "sha512": "547f6e969a25f493ffe16cb530c2ff0d8258c374db78f9838d2939c73ee984ad7d1e6695b48001748565b444b6289f7f04b0d19b0121717f8ad8b4cd2995f3fa",
          "sha256": "4469bb6abc69f7dd397d14649cad1e433f18d5db5316f467cdc65c7d22cb35f9",
          "sha1": "c24d7e94e87fff290ed4fe60ac479790d214aa1e",
          "md5": "974715eda80bd55ec86bdd14a57f999e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.6"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.6.jar",
          "url": "http-api-3.3.6.jar",
          "size": 154346,
          "sha512": "547f6e969a25f493ffe16cb530c2ff0d8258c374db78f9838d2939c73ee984ad7d1e6695b48001748565b444b6289f7f04b0d19b0121717f8ad8b4cd2995f3fa",
          "sha256": "4469bb6abc69f7dd397d14649cad1e433f18d5db5316f467cdc65c7d22cb35f9",
          "sha1": "c24d7e94e87fff290ed4fe60ac479790d214aa1e",
          "md5": "974715eda80bd55ec86bdd14a57f999e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.6-sources.jar",
          "url": "http-api-3.3.6-sources.jar",
          "size": 101951,
          "sha512": "c88a25ee6b2924eb5f275a3ded9b9f42f6f6e548a2954aeefb06b3736018ca535f15480e0332ad0c98af32445d0f020fca60bf72d05a9e323de2e2738014966a",
          "sha256": "1823953e328b6777edd0dedfa4d12c7b2d431c2f3fc27d91508cba582e6b3c5b",
          "sha1": "d3a506a7a65a18267dfc44b6f5ec87f67e342e2b",
          "md5": "025be831d6ebd315c9889e7f67bc4600"
        }
      ]
    }
  ]
}
