{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "n4bz6bwt5zcfbh3sm4ypxrybzi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.1.jar",
          "url": "runelite-api-3.3.1.jar",
          "size": 1181616,
          "sha512": "b3b7916ceb35a4a0b112139ccbb40eaf8566897968e60b1be9c37721b1618745bd2f34e7173fcb16039e9ef3011ccb79ee92ebe8b106c85467814e37c76e29af",
          "sha256": "ae96acf10d136f58ffbfe7b165a7c8523619937f623ed2d32b568260abe3f589",
          "sha1": "25d9aaa2a6704baf7969c1c0f2320317776f438d",
          "md5": "08e7b61105ca7955be706067a379f3eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.1.jar",
          "url": "runelite-api-3.3.1.jar",
          "size": 1181616,
          "sha512": "b3b7916ceb35a4a0b112139ccbb40eaf8566897968e60b1be9c37721b1618745bd2f34e7173fcb16039e9ef3011ccb79ee92ebe8b106c85467814e37c76e29af",
          "sha256": "ae96acf10d136f58ffbfe7b165a7c8523619937f623ed2d32b568260abe3f589",
          "sha1": "25d9aaa2a6704baf7969c1c0f2320317776f438d",
          "md5": "08e7b61105ca7955be706067a379f3eb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.1-sources.jar",
          "url": "runelite-api-3.3.1-sources.jar",
          "size": 866030,
          "sha512": "0f281aa8f3cce6973854bff6334fe9f058f7c9bf169e84823a1387d999d4728605b54e97e54da596432ee8e47c8a2a9c8a74c84c1d7d4c2ac88eda0936f1b436",
          "sha256": "c3331feff63acfb81e7617c4d44b89d6b41d1f7e6da7ae102eff4c8d2c95be28",
          "sha1": "78b0a08b0e83bdff510a150c59a3f6b4e369e8c2",
          "md5": "6e0e78552c0f2b8d24f893d65f92af15"
        }
      ]
    }
  ]
}
