{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "pov7w6lk5bai7fjaqkz3alhnxq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.1.jar",
          "url": "runelite-api-3.3.1.jar",
          "size": 1181335,
          "sha512": "41eb755f08e4f981aa48d14b8b5c19e79b8ee59b132b96b6ca81f0ba6169f1bdaba32096675df54dca97b991d531857bfe5ee8aa1456e44e6b8358815db21cd9",
          "sha256": "0750610d42870bc2586f5273b260a94f447a3975fddd38bb612665034cca46ba",
          "sha1": "e18f3a0dd34d9b96a3c231545fea13c2dcf3195f",
          "md5": "55daad0b0223b54bc6d2c359bd353192"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.1.jar",
          "url": "runelite-api-3.3.1.jar",
          "size": 1181335,
          "sha512": "41eb755f08e4f981aa48d14b8b5c19e79b8ee59b132b96b6ca81f0ba6169f1bdaba32096675df54dca97b991d531857bfe5ee8aa1456e44e6b8358815db21cd9",
          "sha256": "0750610d42870bc2586f5273b260a94f447a3975fddd38bb612665034cca46ba",
          "sha1": "e18f3a0dd34d9b96a3c231545fea13c2dcf3195f",
          "md5": "55daad0b0223b54bc6d2c359bd353192"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.1-sources.jar",
          "url": "runelite-api-3.3.1-sources.jar",
          "size": 865936,
          "sha512": "bb99df18b7cd7be31d2b78ecf06c8bfae3339ecf72555265cecf73dcc01f74e8023397043bb1a193966660b27d90a6ac2e5cd925e5f0e6abe9c6ce7a708167f3",
          "sha256": "52d64f5248b416691ad4fd7dfc9f803067c7fc7164ebaaee8db61cee715cfd79",
          "sha1": "e24d0e8a6be75448b76172c051bce3ec03695ddf",
          "md5": "531fcd14354178c583f525efec2fe6e1"
        }
      ]
    }
  ]
}
