{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "5jobdrexlvgszjyjphdmonnmk4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.1.jar",
          "url": "runelite-api-3.3.1.jar",
          "size": 1181335,
          "sha512": "e2ab270c2bae2e8a55d44197eca11b188a08f0847271c2d31490f778fe88d4311f8d1efb6c915c8e7e600e3442d2008f3dfd5336307e6bfb7a7125408e5e2841",
          "sha256": "47748bdaaa6dd2f254d1a1d0d68c047ba4ba1b68b1774448b167e14454c1832d",
          "sha1": "ffdba00b62a867e1ee6471767878ff025e332f6f",
          "md5": "77e087209c83a21ac116ed68ef019326"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.1.jar",
          "url": "runelite-api-3.3.1.jar",
          "size": 1181335,
          "sha512": "e2ab270c2bae2e8a55d44197eca11b188a08f0847271c2d31490f778fe88d4311f8d1efb6c915c8e7e600e3442d2008f3dfd5336307e6bfb7a7125408e5e2841",
          "sha256": "47748bdaaa6dd2f254d1a1d0d68c047ba4ba1b68b1774448b167e14454c1832d",
          "sha1": "ffdba00b62a867e1ee6471767878ff025e332f6f",
          "md5": "77e087209c83a21ac116ed68ef019326"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.1-sources.jar",
          "url": "runelite-api-3.3.1-sources.jar",
          "size": 865936,
          "sha512": "93a2fac2234333bb5c77bfbdbb2d2f9c250b22fd2c980c674ad0cb99e8eef3d947afd0a20cc1e5631f94bb3d415be256582b0d2ff045f27584cc078b2700d315",
          "sha256": "3376dbfb75197bb936c886ee109f510dee4755086f47ea71c2eac231f2b562d9",
          "sha1": "a8c093de10e9e887368fcb4ae2e8d0d4ea59bf4b",
          "md5": "646426ba45e0d4309f39bfadf82f6d0b"
        }
      ]
    }
  ]
}
