{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "glaztnihezgs5pz2rucs5z6dpy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.2.1.jar",
          "url": "injected-client-3.2.1.jar",
          "size": 2251713,
          "sha512": "df9ebebb46875e593bc9bf72a347c97992877e09b9c77d335f6637d19f7450c865fca4a0a24e9bf107d78121c2fcef64641ceed96c3c75cc0cf1de617c36845a",
          "sha256": "8433e7e91e3c8f636d4b152ced2a202e654a005362a35921fffe21e25b8a01d3",
          "sha1": "86a227d4beb36fdaef37dfefd04fa9de2b1b48ef",
          "md5": "e0f8cfb7560b165327ab23c60fc53fb9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.2.1.jar",
          "url": "injected-client-3.2.1.jar",
          "size": 2251713,
          "sha512": "df9ebebb46875e593bc9bf72a347c97992877e09b9c77d335f6637d19f7450c865fca4a0a24e9bf107d78121c2fcef64641ceed96c3c75cc0cf1de617c36845a",
          "sha256": "8433e7e91e3c8f636d4b152ced2a202e654a005362a35921fffe21e25b8a01d3",
          "sha1": "86a227d4beb36fdaef37dfefd04fa9de2b1b48ef",
          "md5": "e0f8cfb7560b165327ab23c60fc53fb9"
        }
      ]
    }
  ]
}
