{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "6ud2yyqsfrgwvhmxgpopo7wgmy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.2.1.jar",
          "url": "injected-client-3.2.1.jar",
          "size": 2252068,
          "sha512": "7c6f3f302118c49f3ee11d293bcc9cb6b57de589f5668495007384463d402b2eeb4df2ff6d7bbf9d3ff69eec671d7139fbdce1450cc4617735b963e50e926f74",
          "sha256": "a6c9fd9adac1e35a6a6ed5e34d56a593ffc5906800ac50ae04b9a7d0a5ef22fe",
          "sha1": "a4edf34877497175e82c1a03f659051e02a963f7",
          "md5": "62421e07a427e323a0f63b8542fbff6e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.2.1.jar",
          "url": "injected-client-3.2.1.jar",
          "size": 2252068,
          "sha512": "7c6f3f302118c49f3ee11d293bcc9cb6b57de589f5668495007384463d402b2eeb4df2ff6d7bbf9d3ff69eec671d7139fbdce1450cc4617735b963e50e926f74",
          "sha256": "a6c9fd9adac1e35a6a6ed5e34d56a593ffc5906800ac50ae04b9a7d0a5ef22fe",
          "sha1": "a4edf34877497175e82c1a03f659051e02a963f7",
          "md5": "62421e07a427e323a0f63b8542fbff6e"
        }
      ]
    }
  ]
}
