{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "xmot34gfxrf6zkxeilaxrkfpfu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.2.1.jar",
          "url": "injected-client-3.2.1.jar",
          "size": 2245481,
          "sha512": "117de2002db00c3f8578c6a2d3fb0132b20cf5af59ee0a82be773d22c7507f804921df41fcc37cb600d1c803e351acc314617c797f47263d413a39d0157e851c",
          "sha256": "973bf26c492e71106267f96f949b4dc6911aab20ce658bd8b39fcc23dea8cddd",
          "sha1": "40d7ad34c1f867a3abde6e880bb2ab3ebab18e79",
          "md5": "cdde8734aed2ba1298ee42a9b19a99f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.2.1.jar",
          "url": "injected-client-3.2.1.jar",
          "size": 2245481,
          "sha512": "117de2002db00c3f8578c6a2d3fb0132b20cf5af59ee0a82be773d22c7507f804921df41fcc37cb600d1c803e351acc314617c797f47263d413a39d0157e851c",
          "sha256": "973bf26c492e71106267f96f949b4dc6911aab20ce658bd8b39fcc23dea8cddd",
          "sha1": "40d7ad34c1f867a3abde6e880bb2ab3ebab18e79",
          "md5": "cdde8734aed2ba1298ee42a9b19a99f6"
        }
      ]
    }
  ]
}
