{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "fwoqa2c245gs3b7ixtbz7fyn5u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.4.3.jar",
          "url": "http-api-3.4.3.jar",
          "size": 159710,
          "sha512": "477b38292beb153cb254bf3b9b2d90c870fd7397f769ba281a72f67542613b1a54bd3ccae1a10ff0723472ea8a6a5a982003bc4a6309933c79c21aab427cdfec",
          "sha256": "9f4fba24f014d9eacf17d2a43fad31743c81a703aa8b5e9d52b1fbd1480ed51f",
          "sha1": "d44cffb403a62ab6e53c7ae5d279bfdd3cbd3930",
          "md5": "9eb5ad98d9088464e0ba4601b2b8c092"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.4.3.jar",
          "url": "http-api-3.4.3.jar",
          "size": 159710,
          "sha512": "477b38292beb153cb254bf3b9b2d90c870fd7397f769ba281a72f67542613b1a54bd3ccae1a10ff0723472ea8a6a5a982003bc4a6309933c79c21aab427cdfec",
          "sha256": "9f4fba24f014d9eacf17d2a43fad31743c81a703aa8b5e9d52b1fbd1480ed51f",
          "sha1": "d44cffb403a62ab6e53c7ae5d279bfdd3cbd3930",
          "md5": "9eb5ad98d9088464e0ba4601b2b8c092"
        }
      ]
    }
  ]
}
