{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "ctrz4ahidja37awrdv7ex2stvy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.4.3.jar",
          "url": "http-api-3.4.3.jar",
          "size": 159710,
          "sha512": "3ad5781d4035e7270a250fa3f8f1c6f9bada024ac5de2e9cde47ea5e1443d5aa9bf8248d68265528cc240a75c354ed7feeaa6dd374f39d82d27a60e0407f2014",
          "sha256": "ab89bb75ca4f4d8505e1e897035fe045f2e07ade0132d8f60e15f31ca46431c7",
          "sha1": "a065b3bcd5b669ff8a1ef7f13d2254c3462c8ee4",
          "md5": "dadf259a97ffe4514c721322363504d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.4.3.jar",
          "url": "http-api-3.4.3.jar",
          "size": 159710,
          "sha512": "3ad5781d4035e7270a250fa3f8f1c6f9bada024ac5de2e9cde47ea5e1443d5aa9bf8248d68265528cc240a75c354ed7feeaa6dd374f39d82d27a60e0407f2014",
          "sha256": "ab89bb75ca4f4d8505e1e897035fe045f2e07ade0132d8f60e15f31ca46431c7",
          "sha1": "a065b3bcd5b669ff8a1ef7f13d2254c3462c8ee4",
          "md5": "dadf259a97ffe4514c721322363504d0"
        }
      ]
    }
  ]
}
