{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "fydfladsszgijcgklcx6mw76by"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.8.jar",
          "url": "http-api-3.3.8.jar",
          "size": 154403,
          "sha512": "020de2baeed0090b5d7f298d041770a8581587e39acf7b7bf8b730439cb1cf0a0397560efa8f3ffaf5ac7fa68ba27abd34a96cc8d79a59e2dbc5eac2c0b835db",
          "sha256": "ce741478f7b802e93a5f567be44b0c9861ac3efd36e723fadcad2ae7a05ffdb4",
          "sha1": "f681c427bc348ad0c07ed0fdca6eea18f97fca32",
          "md5": "c81036a31db449f63af3b8433e4c03c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.8"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.8.jar",
          "url": "http-api-3.3.8.jar",
          "size": 154403,
          "sha512": "020de2baeed0090b5d7f298d041770a8581587e39acf7b7bf8b730439cb1cf0a0397560efa8f3ffaf5ac7fa68ba27abd34a96cc8d79a59e2dbc5eac2c0b835db",
          "sha256": "ce741478f7b802e93a5f567be44b0c9861ac3efd36e723fadcad2ae7a05ffdb4",
          "sha1": "f681c427bc348ad0c07ed0fdca6eea18f97fca32",
          "md5": "c81036a31db449f63af3b8433e4c03c9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.8-sources.jar",
          "url": "http-api-3.3.8-sources.jar",
          "size": 101953,
          "sha512": "b8e9a031a4edb19d4655f4c8174d480781dd526b0283806fe8a31bc198e5cc2e438ceedced9548c5e0319638214be48623171d2475ff6a19971ddd24de66e681",
          "sha256": "ab2eeba491d4579423b460a3eb9ab0329d92e706055f8d11a90f901b3b5b8127",
          "sha1": "dc2641e2a8e1ecc9f1735b1457aaaa0eb6d64191",
          "md5": "fd67e48cdf53b9abf041b0cd33ce52fb"
        }
      ]
    }
  ]
}
