{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "3pkvvpxbbnctlkzpyhegapxwaa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.8.jar",
          "url": "http-api-3.3.8.jar",
          "size": 154403,
          "sha512": "3914e5e038a5edf54021adccdea15dd06e5f6fdd333be66e29aa4738bb055c4304c1c8bc1bec66069ade52c0d365c1606965883bb88e7aed33b26934f65cc5e1",
          "sha256": "cde7a551b146629c0174bade5827a47b10c428cf79c4239d887410a32147e9d5",
          "sha1": "165b241749572f2446e78f516aebe36e292daaeb",
          "md5": "b5205ec9b13f97e233cc7e728654735d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.8"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.8.jar",
          "url": "http-api-3.3.8.jar",
          "size": 154403,
          "sha512": "3914e5e038a5edf54021adccdea15dd06e5f6fdd333be66e29aa4738bb055c4304c1c8bc1bec66069ade52c0d365c1606965883bb88e7aed33b26934f65cc5e1",
          "sha256": "cde7a551b146629c0174bade5827a47b10c428cf79c4239d887410a32147e9d5",
          "sha1": "165b241749572f2446e78f516aebe36e292daaeb",
          "md5": "b5205ec9b13f97e233cc7e728654735d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.8-sources.jar",
          "url": "http-api-3.3.8-sources.jar",
          "size": 101953,
          "sha512": "998d2bd4e305ac42958ea003a9cdaf7db2214bf4fd862c2024866039f87e7d79fea577c92986a1b6e09ffd184c6b783e95a3c942a99b21f197252cc83f5978a7",
          "sha256": "7d911ceae153d8b04fa6cb05ea74660fea8439c094ab2ddb2493c46de2cfd8c1",
          "sha1": "6d346b2cfa34955f7dd2075b68b19c7fc6029698",
          "md5": "57a2ecd250dc827829cc3024ce6f0139"
        }
      ]
    }
  ]
}
