{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "lbsuan3fjnglbiutzky6dcavye"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.8.jar",
          "url": "runescape-api-1.6.8.jar",
          "size": 55336,
          "sha512": "958000d3eb005ebd2382d9397fe5ac6a2cdf8b8ffc08e8b3d346c3ff3277436adb2b8a9799c7d415d5501975b1d4021e4d02d9a1ccd82f6e887844eba0c92374",
          "sha256": "450dbe7507389fe3033a48faf5bd450982fc6a7dad7a841a2f8d2bc506fb8167",
          "sha1": "86d7db6d67994ae94c9d3b6b21f991fc0b8b047b",
          "md5": "ffb78d8c0e40eb5b7ef6df8605a54811"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.8.jar",
          "url": "runescape-api-1.6.8.jar",
          "size": 55336,
          "sha512": "958000d3eb005ebd2382d9397fe5ac6a2cdf8b8ffc08e8b3d346c3ff3277436adb2b8a9799c7d415d5501975b1d4021e4d02d9a1ccd82f6e887844eba0c92374",
          "sha256": "450dbe7507389fe3033a48faf5bd450982fc6a7dad7a841a2f8d2bc506fb8167",
          "sha1": "86d7db6d67994ae94c9d3b6b21f991fc0b8b047b",
          "md5": "ffb78d8c0e40eb5b7ef6df8605a54811"
        }
      ]
    }
  ]
}
