{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "53glw4cucfa5hpmc54phaujgxm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": []
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.4.1.jar",
          "url": "injected-client-3.4.1.jar",
          "size": 2305281,
          "sha512": "87d48206488fdd53d646861501379fad670d509db8c6e01d8eeb4410c137d7a580255b99504e1f8d05f3ad3a239d244c52f77739202e740957253937f4d3717d",
          "sha256": "d089f0f24ff3c19cf51c6f14664596feb6b70605dda6eab29b3f0f849fe3f3d7",
          "sha1": "9d3261831960a919d54041e5893ac0bfe15d8fc1",
          "md5": "b94e60dc658aab1e6ce7b7de1c0f5ca1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": []
    }
  ]
}
