{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "otnd32ax2razbpxgqn4eqp6y24"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": []
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.4.1.jar",
          "url": "injected-client-3.4.1.jar",
          "size": 2305275,
          "sha512": "55c69c813b24bb65c2b76e68f17bb89c33fa333d0210cc7bbedae602607f6a16bb5607f16eddd3646a2e8aa16709dc864b07ec53781cb2fd3a74f2c686f6ea81",
          "sha256": "e246ca9a89aeb7082fa754e5afad330a2011c003a5bb8bae6eb1bb26e564f9bc",
          "sha1": "f1df797aae7e35cd5ba0274f779eb1c5f4dd8411",
          "md5": "221ea8bb6cd07048a9abde060fdf4628"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": []
    }
  ]
}
