{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "srmi4ril7re6lblttfwnzxsdgm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": []
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.4.1.jar",
          "url": "injected-client-3.4.1.jar",
          "size": 2305275,
          "sha512": "e16c11b9fb8e2af8d64ebe7468ca5cd654130fa3097fe09b33cf523647e8e5c7f3dd6052d94a2bf5810faeeb5b3229e3242073bd5d7be6475da594d709c78ce6",
          "sha256": "9ec7dd902d5a331f191126031c257fc6cfa905be7a5e391e59349dc30b10c293",
          "sha1": "491e238cb0dc14bdcd08ec5afcf27deb935616ee",
          "md5": "a79e28aa2094f37d0518301b1ce3ba26"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": []
    }
  ]
}
