{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "ofjaddfu3fcxnc5gpdvv35gy5e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.0.jar",
          "url": "runescape-api-3.3.0.jar",
          "size": 103468,
          "sha512": "f60213ed6c43e083c1135b24107936e65e3b10e03b1f8df4217f60eed7f414bac88b90f32950b80c8464d0b0627cc1c398529485fcecbb8300487e336b68886e",
          "sha256": "cfd87b78ff81159c4dc6577dbef22ac27bc6783a1eea4c97db27513dccae47cb",
          "sha1": "833a1b079ab39faedffcace256c6b3825710bc42",
          "md5": "87e54a07746b107e9242f2195e92b48d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.0.jar",
          "url": "runescape-api-3.3.0.jar",
          "size": 103468,
          "sha512": "f60213ed6c43e083c1135b24107936e65e3b10e03b1f8df4217f60eed7f414bac88b90f32950b80c8464d0b0627cc1c398529485fcecbb8300487e336b68886e",
          "sha256": "cfd87b78ff81159c4dc6577dbef22ac27bc6783a1eea4c97db27513dccae47cb",
          "sha1": "833a1b079ab39faedffcace256c6b3825710bc42",
          "md5": "87e54a07746b107e9242f2195e92b48d"
        }
      ]
    }
  ]
}
