{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "nfciutv2ujbjdabtzzanx67oxe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.2.0.jar",
          "url": "http-api-3.2.0.jar",
          "size": 165559,
          "sha512": "efd9fa7670687654b656556351b6999ea847bad0fd8ec44b2665d3c2192ec7b0e283e152f23779e89965cd33304013650d9b9ca8146ea6f1fd447af0d3feff1c",
          "sha256": "95604cc83a82319616bec211f23000faaf489dcf1b3a1911e08082c25cddecca",
          "sha1": "c2ef0109c0ac60d6b201ab3abcb24fbb0e2a26a4",
          "md5": "0e9c398243fc760fb99b4ad03974efe3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.2.0.jar",
          "url": "http-api-3.2.0.jar",
          "size": 165559,
          "sha512": "efd9fa7670687654b656556351b6999ea847bad0fd8ec44b2665d3c2192ec7b0e283e152f23779e89965cd33304013650d9b9ca8146ea6f1fd447af0d3feff1c",
          "sha256": "95604cc83a82319616bec211f23000faaf489dcf1b3a1911e08082c25cddecca",
          "sha1": "c2ef0109c0ac60d6b201ab3abcb24fbb0e2a26a4",
          "md5": "0e9c398243fc760fb99b4ad03974efe3"
        }
      ]
    }
  ]
}
