{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "f3upj6lb25f4dm4sitq246cwr4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.2.0.jar",
          "url": "http-api-3.2.0.jar",
          "size": 165559,
          "sha512": "2ec0a89bac9ad27a26590dea8f26aba29f6e473d2ff91162ed6f7f9681842fec734123e50b867bf79d18ae404be37966884b0e58ad2cfeed1ca5a11020c0f3b9",
          "sha256": "ad6845b465ba72905b30a14fcf36f523960c24a3d391089e29b2f7356e057531",
          "sha1": "d47b4880691e42d2ed4aff0a8c008cd19ceeec34",
          "md5": "b23b13aa7e09a5b6a1b947276f66d712"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.2.0.jar",
          "url": "http-api-3.2.0.jar",
          "size": 165559,
          "sha512": "2ec0a89bac9ad27a26590dea8f26aba29f6e473d2ff91162ed6f7f9681842fec734123e50b867bf79d18ae404be37966884b0e58ad2cfeed1ca5a11020c0f3b9",
          "sha256": "ad6845b465ba72905b30a14fcf36f523960c24a3d391089e29b2f7356e057531",
          "sha1": "d47b4880691e42d2ed4aff0a8c008cd19ceeec34",
          "md5": "b23b13aa7e09a5b6a1b947276f66d712"
        }
      ]
    }
  ]
}
