{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "aglepubd6zcztlekeb3y23adoi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.4.0.jar",
          "url": "http-api-3.4.0.jar",
          "size": 157829,
          "sha512": "2c3de92e6b0535a77aca865212b5bd103a922408abecf802445cec8796bcd9eaa7ae5ccd187432b5f38dbd23582fa9ab7d0ef86af829823b4069d5fa7afcf389",
          "sha256": "8c9438d09e767c70fc4397a63980bf71b0d76e755785ebd723e1cb0c4a63a7be",
          "sha1": "8a875fdd61c52a26df225231e0c1e6c534196587",
          "md5": "a3f5ed85ba8153f5769c9fbc8ef26243"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.4.0.jar",
          "url": "http-api-3.4.0.jar",
          "size": 157829,
          "sha512": "2c3de92e6b0535a77aca865212b5bd103a922408abecf802445cec8796bcd9eaa7ae5ccd187432b5f38dbd23582fa9ab7d0ef86af829823b4069d5fa7afcf389",
          "sha256": "8c9438d09e767c70fc4397a63980bf71b0d76e755785ebd723e1cb0c4a63a7be",
          "sha1": "8a875fdd61c52a26df225231e0c1e6c534196587",
          "md5": "a3f5ed85ba8153f5769c9fbc8ef26243"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.4.0-sources.jar",
          "url": "http-api-3.4.0-sources.jar",
          "size": 103699,
          "sha512": "248cb406b98f474ce98861fe307e1a1d042b43be7bc7cd882470d3681f09719942f05495b2e3456da31b1ebe1a45b8248715b8a57deced34c889a38caf1693a4",
          "sha256": "06a4f475419832123f788a09f2ac028e6cf0e079fda89bb26b668f0626fd8ec1",
          "sha1": "8cb8718be69f020ba8817afe9cb984068a98a2e5",
          "md5": "d18f48bfd59929c91393b313289525d7"
        }
      ]
    }
  ]
}
