{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "bmjwgkx5vfd2rjsdkpde7u4nve"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.6.jar",
          "url": "injected-client-1.6.6.jar",
          "size": 2265863,
          "sha512": "0f4e6ed22b017685350fc3cbe87d76db6acbabf7ecbbdcee03be1a91dd65206c02cdd9529fe29a1a1edc5601e1e3562753dc150534a5f83df58a43cc6fdba916",
          "sha256": "4b97f03c887a43f108477474a755e31d5d6ed9a244ed94ed96d05490ea61e02f",
          "sha1": "b33540d804ccf7d0a44b575815251440151ea431",
          "md5": "5a4ab18ed4b5529f0ae1f1278d74be19"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.6.jar",
          "url": "injected-client-1.6.6.jar",
          "size": 2265863,
          "sha512": "0f4e6ed22b017685350fc3cbe87d76db6acbabf7ecbbdcee03be1a91dd65206c02cdd9529fe29a1a1edc5601e1e3562753dc150534a5f83df58a43cc6fdba916",
          "sha256": "4b97f03c887a43f108477474a755e31d5d6ed9a244ed94ed96d05490ea61e02f",
          "sha1": "b33540d804ccf7d0a44b575815251440151ea431",
          "md5": "5a4ab18ed4b5529f0ae1f1278d74be19"
        }
      ]
    }
  ]
}
