{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-client",
    "version": "3.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "yrgrwxt35vgsnfumly2dkrrfcm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-client-3.3.9.jar",
          "url": "runelite-client-3.3.9.jar",
          "size": 2666344,
          "sha512": "1866b6d6972ccd84fc8e836594ac032f59c39ada150ff9bfd77d4a497e6c21017d143effd49d235eee30429b40c87e75ffa0a2c235559628dd6d25cfe37fb126",
          "sha256": "6d3f109b4d036a8f2b116ecde188f89bbcc6f344ce49dd4c47e337246bd512e3",
          "sha1": "492eebeb273f7b74e83d3d878e831aa1d5b71691",
          "md5": "2718b1967b2e77eb7cda69c2c82b641a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "4.2.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "guice",
              "type": "jar",
              "extension": "jar",
              "classifier": "no_aop"
            }
          }
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "1.4.200"
          }
        },
        {
          "group": "com.jakewharton.rxrelay3",
          "module": "rxrelay",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "org.jgroups",
          "module": "jgroups",
          "version": {
            "requires": "4.2.4.Final"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "net.runelite",
          "module": "discord",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.pushing-pixels",
          "module": "radiance-substance",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "19.0.0"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq",
          "version": {
            "requires": "3.13.2"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq-codegen",
          "version": {
            "requires": "3.13.2"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq-meta",
          "version": {
            "requires": "3.13.2"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-logback",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.github.zafarkhaja",
          "module": "java-semver",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.pf4j",
          "module": "pf4j",
          "version": {
            "requires": "3.3.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.pf4j",
          "module": "pf4j-update",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "http-api",
          "version": {
            "requires": "3.3.9"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.9"
          }
        },
        {
          "group": "org.pushing-pixels",
          "module": "radiance-trident",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injected-client",
          "version": {
            "requires": "3.3.9"
          }
        },
        {
          "group": "com.openosrs.rs",
          "module": "runescape-api",
          "version": {
            "requires": "3.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-client-3.3.9.jar",
          "url": "runelite-client-3.3.9.jar",
          "size": 2666344,
          "sha512": "1866b6d6972ccd84fc8e836594ac032f59c39ada150ff9bfd77d4a497e6c21017d143effd49d235eee30429b40c87e75ffa0a2c235559628dd6d25cfe37fb126",
          "sha256": "6d3f109b4d036a8f2b116ecde188f89bbcc6f344ce49dd4c47e337246bd512e3",
          "sha1": "492eebeb273f7b74e83d3d878e831aa1d5b71691",
          "md5": "2718b1967b2e77eb7cda69c2c82b641a"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-client-3.3.9-shaded.jar",
          "url": "runelite-client-3.3.9-shaded.jar",
          "size": 31465482,
          "sha512": "2cf893254c67a82a58b22e673e183013c2959a2e2112cf3391c66bd95ed3a8983e5ab567a83d189e942b8d3ac5e070ac59afa1a64c07c7ecac894cb516ceeea1",
          "sha256": "c1c4ec6967c4df77f924a89bcb0e8e246442e32204f259f564e0c066bb53a81e",
          "sha1": "0bbe3d697b0e7e978ccbaa7bdd3bc40f4addc08e",
          "md5": "c2683c870d8cce21d6ceedfdaf0328ef"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-client-3.3.9-sources.jar",
          "url": "runelite-client-3.3.9-sources.jar",
          "size": 2317760,
          "sha512": "6266f390167af682c928ef7fd94ef0cc4dd210c2d986491bb4a4ff5ed21f297a0a2d595885e188c68bb852a390076a72889f7bc52958e7877225b45e51f89412",
          "sha256": "85ed62b2ee0b6d8890cab1a291434d09f9e862e069ace3938a4865e9e4de2223",
          "sha1": "4896f2170a0c7f85d49ae47c59651986a6e6d745",
          "md5": "b5e7595a51555187047115cd04ccb236"
        }
      ]
    }
  ]
}
