{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "66kqjmg7lrg33guig5udmisnmy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.3.jar",
          "url": "injected-client-3.3.3.jar",
          "size": 2253448,
          "sha512": "9ce27dba33e414af4ea422ea3c90eba73b5cbdfc61762c1bf6014f2cfe7f35b436eeed84010dd0dd6a8e33626f2a89a8902a8cc8ee6130d3c2fec2bb47a7536b",
          "sha256": "b1e9b810b6683959de53a0ee371ff8cc1b0e3bf78b9491dfc1303bc57504399d",
          "sha1": "d632c452d0d1195d53a3500c9eafc8e4d90b7b07",
          "md5": "c5f6c5624b71b652214ee0fd6b8b3a83"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.3.jar",
          "url": "injected-client-3.3.3.jar",
          "size": 2253448,
          "sha512": "9ce27dba33e414af4ea422ea3c90eba73b5cbdfc61762c1bf6014f2cfe7f35b436eeed84010dd0dd6a8e33626f2a89a8902a8cc8ee6130d3c2fec2bb47a7536b",
          "sha256": "b1e9b810b6683959de53a0ee371ff8cc1b0e3bf78b9491dfc1303bc57504399d",
          "sha1": "d632c452d0d1195d53a3500c9eafc8e4d90b7b07",
          "md5": "c5f6c5624b71b652214ee0fd6b8b3a83"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.3-sources.jar",
          "url": "injected-client-3.3.3-sources.jar",
          "size": 261,
          "sha512": "61267381e7dace0f0827b8681ae2011e4ea8c4e1c37980ce3b3a692dc43ac86120b9bf7e487d0edb93d62aadbc05aa4dce8433c7b369d97f6e5faff71dcf6354",
          "sha256": "cae09c2b2e8dd458a01d667680ce03153f85d92f63cb23031afe5d15cabd46eb",
          "sha1": "a0bee16d10f92b6fbeaf69a2a1896ef04e5e402e",
          "md5": "d20581377fcf6318eaebae998ef5df17"
        },
        {
          "name": "injected-client-3.3.3.jar",
          "url": "injected-client-3.3.3.jar",
          "size": 2253448,
          "sha512": "9ce27dba33e414af4ea422ea3c90eba73b5cbdfc61762c1bf6014f2cfe7f35b436eeed84010dd0dd6a8e33626f2a89a8902a8cc8ee6130d3c2fec2bb47a7536b",
          "sha256": "b1e9b810b6683959de53a0ee371ff8cc1b0e3bf78b9491dfc1303bc57504399d",
          "sha1": "d632c452d0d1195d53a3500c9eafc8e4d90b7b07",
          "md5": "c5f6c5624b71b652214ee0fd6b8b3a83"
        }
      ]
    }
  ]
}
