{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "shc3u7sqqrgojhcu6hvk45igky"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.3.jar",
          "url": "injected-client-3.3.3.jar",
          "size": 2253448,
          "sha512": "cbacd606789cdafcd8ff96ab277a7bd00d255874fac0767fb6e975f2885c0c609229a4ffa66f09894cfb50d1d9b023ff2c8fcf86b42f4ffb61db9d151bbab287",
          "sha256": "04449c42a4107934256487996fd067122bf8b1db7541a643338cdf1eecf4ba00",
          "sha1": "6bdb174729a376b8983352e0d0d0c72d196e01cb",
          "md5": "5b1814eb97435eaa3cccfd30795b3b93"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.3.jar",
          "url": "injected-client-3.3.3.jar",
          "size": 2253448,
          "sha512": "cbacd606789cdafcd8ff96ab277a7bd00d255874fac0767fb6e975f2885c0c609229a4ffa66f09894cfb50d1d9b023ff2c8fcf86b42f4ffb61db9d151bbab287",
          "sha256": "04449c42a4107934256487996fd067122bf8b1db7541a643338cdf1eecf4ba00",
          "sha1": "6bdb174729a376b8983352e0d0d0c72d196e01cb",
          "md5": "5b1814eb97435eaa3cccfd30795b3b93"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.3-sources.jar",
          "url": "injected-client-3.3.3-sources.jar",
          "size": 261,
          "sha512": "1eb6fb20a709c94e92d8e99f69448ee109f19dbb7e321a15ff517823434cb201905aba9c492322842d523708b9275eac7590264766207b7d8ba36ff357d4a249",
          "sha256": "63a7a6aa88d9cce66bbd420da4b8d70a9f260e678d660918d5ebe8a1f7fadc7a",
          "sha1": "1afaa8d45cf2aec71cc08471c7b9728871576c4d",
          "md5": "e3bfebd4441bb67662b9a344fea0c1f5"
        },
        {
          "name": "injected-client-3.3.3.jar",
          "url": "injected-client-3.3.3.jar",
          "size": 2253448,
          "sha512": "cbacd606789cdafcd8ff96ab277a7bd00d255874fac0767fb6e975f2885c0c609229a4ffa66f09894cfb50d1d9b023ff2c8fcf86b42f4ffb61db9d151bbab287",
          "sha256": "04449c42a4107934256487996fd067122bf8b1db7541a643338cdf1eecf4ba00",
          "sha1": "6bdb174729a376b8983352e0d0d0c72d196e01cb",
          "md5": "5b1814eb97435eaa3cccfd30795b3b93"
        }
      ]
    }
  ]
}
