{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "mghvnqxm2ze23ctdnh7iwkbl4e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.3.jar",
          "url": "injected-client-3.3.3.jar",
          "size": 2253448,
          "sha512": "e6f43eb85ca8afe7bae4a6d7d973832a3c061ca1240e03b23d2d24a8ebb9c9fb094e2d872e1ceca782407e61cd301b5664aea8d85fb5bedb21b6f9f75edb7440",
          "sha256": "64033f394344f132a3a437c6b9d422d7a4a58e7be7927bdefc3d65e4b93c4004",
          "sha1": "1caa0da6afd8e6a44bf3ec4beae57bdf2c50993d",
          "md5": "175c3bac6d976b9baf149a156f1bd156"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.3.jar",
          "url": "injected-client-3.3.3.jar",
          "size": 2253448,
          "sha512": "e6f43eb85ca8afe7bae4a6d7d973832a3c061ca1240e03b23d2d24a8ebb9c9fb094e2d872e1ceca782407e61cd301b5664aea8d85fb5bedb21b6f9f75edb7440",
          "sha256": "64033f394344f132a3a437c6b9d422d7a4a58e7be7927bdefc3d65e4b93c4004",
          "sha1": "1caa0da6afd8e6a44bf3ec4beae57bdf2c50993d",
          "md5": "175c3bac6d976b9baf149a156f1bd156"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.3-sources.jar",
          "url": "injected-client-3.3.3-sources.jar",
          "size": 261,
          "sha512": "4f852fc071e550c2c96b3ba7ceb94338dbb57e0e89eabf1f22bf1cc609f8e6e710ac84c56d5ddff3c77a46a7147704071d2168a8cafc92009d24ecd0304868c3",
          "sha256": "81692be33d9b256e3d1dda58e23fa53920db96c65e733a58d58c3df0c221a302",
          "sha1": "8f3fb63e7c3dbf9e1a849e9a61a95aec5cef151f",
          "md5": "8412293fc0dc9e524c4c2739d7fa4350"
        },
        {
          "name": "injected-client-3.3.3.jar",
          "url": "injected-client-3.3.3.jar",
          "size": 2253448,
          "sha512": "e6f43eb85ca8afe7bae4a6d7d973832a3c061ca1240e03b23d2d24a8ebb9c9fb094e2d872e1ceca782407e61cd301b5664aea8d85fb5bedb21b6f9f75edb7440",
          "sha256": "64033f394344f132a3a437c6b9d422d7a4a58e7be7927bdefc3d65e4b93c4004",
          "sha1": "1caa0da6afd8e6a44bf3ec4beae57bdf2c50993d",
          "md5": "175c3bac6d976b9baf149a156f1bd156"
        }
      ]
    }
  ]
}
