{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "blh2zpvljjazvdv4amvku44acu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.4.jar",
          "url": "http-api-3.3.4.jar",
          "size": 164096,
          "sha512": "239860b14073924ee0b232e0d850da19c512dc4bfb3d4caadd0d393e50ca5559f700e188ac35297ca5af3f8ab757e29d524d2cecadfd262bfff6ae0e5185a38f",
          "sha256": "126e4bfa949b59b690002ad7adc593939d3f50ddf27979a50232d20b67713340",
          "sha1": "9bafcba55ae02cc027e9604a21b8df36414e7bce",
          "md5": "677712bac14578c338043878676b4686"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.4.jar",
          "url": "http-api-3.3.4.jar",
          "size": 164096,
          "sha512": "239860b14073924ee0b232e0d850da19c512dc4bfb3d4caadd0d393e50ca5559f700e188ac35297ca5af3f8ab757e29d524d2cecadfd262bfff6ae0e5185a38f",
          "sha256": "126e4bfa949b59b690002ad7adc593939d3f50ddf27979a50232d20b67713340",
          "sha1": "9bafcba55ae02cc027e9604a21b8df36414e7bce",
          "md5": "677712bac14578c338043878676b4686"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.4-sources.jar",
          "url": "http-api-3.3.4-sources.jar",
          "size": 107156,
          "sha512": "faa40e892969a9c6d62b046566f7b13f68835acf23b900b2fdfb3694788ebad8fd1816453c6b15ffb9c595072fa3522f1c8536a2ad5b8a30adcb640555dab029",
          "sha256": "62f28320d542f8572030ebecbc5298ba1bce7569a79bb9a11fc582f7d0e2528a",
          "sha1": "89b0545c4a339de170431e886b4d793ee9aa8da2",
          "md5": "bea9df0f4f94590dc86011f38f2a1b3d"
        }
      ]
    }
  ]
}
