{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "wortqpqmv5dsvnj23qe7swpyyu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.4.jar",
          "url": "http-api-3.3.4.jar",
          "size": 164096,
          "sha512": "36cf25923ee5fcf6398752b595c98372b4b50038d868a20dc1e8eccfea2b52cab6e861302918151cee578981e8b154106422f1433c0b079b866dc850213d9047",
          "sha256": "8deaf68f2e24e580c6ce1216989aa7078123e3a9174af20d099947ac5855864b",
          "sha1": "49acb3d653348df2ef2be7022ed3e7301e0f5291",
          "md5": "519703b7d8374de5c29a8202b233abea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.4.jar",
          "url": "http-api-3.3.4.jar",
          "size": 164096,
          "sha512": "36cf25923ee5fcf6398752b595c98372b4b50038d868a20dc1e8eccfea2b52cab6e861302918151cee578981e8b154106422f1433c0b079b866dc850213d9047",
          "sha256": "8deaf68f2e24e580c6ce1216989aa7078123e3a9174af20d099947ac5855864b",
          "sha1": "49acb3d653348df2ef2be7022ed3e7301e0f5291",
          "md5": "519703b7d8374de5c29a8202b233abea"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.4-sources.jar",
          "url": "http-api-3.3.4-sources.jar",
          "size": 107156,
          "sha512": "95a822a541104970cde3dc0c2f8489c14ca1c9b0b3faa3aec2698de7fc4d6745163db97fded780261fb20f22651c6b489958165fdbcd47d065ed84d004f57882",
          "sha256": "3fb37e28bc9ae9538229a8350d4b9fb7e2f7019d112fe591a2e703696038554c",
          "sha1": "b4af6be0191e7d4ecca6499ad5e78bc6944d6dca",
          "md5": "9e0e80f6df62150b57e5003dd15853b3"
        }
      ]
    }
  ]
}
