{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "ebnwgogc3jdxraawr35khizyxi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.4.jar",
          "url": "http-api-3.3.4.jar",
          "size": 164096,
          "sha512": "9c42566818d32fc865c089f65447c74604621ad73733639bd2455ee68171ee0a73bdff91e10a567e6c9a9a15c4b0d79f54824d31b45d4bc293b8f496985af822",
          "sha256": "a966db087b2bf437ec2430a9d7826d6bd634972977f4c5d2c1fedfe19346c05d",
          "sha1": "8f9b67bbd4ce23a4a0e53f903684a473d2d5881c",
          "md5": "56bf1383c1ac95bc45367311ecc49ea3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.4.jar",
          "url": "http-api-3.3.4.jar",
          "size": 164096,
          "sha512": "9c42566818d32fc865c089f65447c74604621ad73733639bd2455ee68171ee0a73bdff91e10a567e6c9a9a15c4b0d79f54824d31b45d4bc293b8f496985af822",
          "sha256": "a966db087b2bf437ec2430a9d7826d6bd634972977f4c5d2c1fedfe19346c05d",
          "sha1": "8f9b67bbd4ce23a4a0e53f903684a473d2d5881c",
          "md5": "56bf1383c1ac95bc45367311ecc49ea3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.4-sources.jar",
          "url": "http-api-3.3.4-sources.jar",
          "size": 107156,
          "sha512": "e66d3beadf6f64237038b34a5606050182cbd26cb97625d63e708943a53fc88d4efeb71878a0e45631dfa48d5f33eaf6ec8935b1202526278b14b0df945558f5",
          "sha256": "a9f4b35febd81611976a54a45555f311575017820bde22e9a046816a146d7d66",
          "sha1": "82bd022a2379a2b434c2ced0c35eef77a3edefcc",
          "md5": "96b4949ab348634f754cc7802e59d4cc"
        }
      ]
    }
  ]
}
