{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "okixqif5jraclolqnbcy2mxehu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.8.jar",
          "url": "http-api-1.6.8.jar",
          "size": 164353,
          "sha512": "9546a41640a5286060f67166f8b68d31a8a2a6ee6fdf1d44964ac4e2e847573f2a3fb9c53defc9dd9d74c7c9aeae10af5589c77b18c44ed50e22439bb45eb304",
          "sha256": "e8176a9dcad564034bf8e1aec2e3dda01d619b48ec4e1f9c032ccb1446d06eaf",
          "sha1": "45f8d11d3f79913f3254ed7ece3a066b42ddef12",
          "md5": "9c2964f70db268be6445e00fb3422404"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.8"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.8.jar",
          "url": "http-api-1.6.8.jar",
          "size": 164353,
          "sha512": "9546a41640a5286060f67166f8b68d31a8a2a6ee6fdf1d44964ac4e2e847573f2a3fb9c53defc9dd9d74c7c9aeae10af5589c77b18c44ed50e22439bb45eb304",
          "sha256": "e8176a9dcad564034bf8e1aec2e3dda01d619b48ec4e1f9c032ccb1446d06eaf",
          "sha1": "45f8d11d3f79913f3254ed7ece3a066b42ddef12",
          "md5": "9c2964f70db268be6445e00fb3422404"
        }
      ]
    }
  ]
}
