{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "qzmbipda5jfznlm2sxelz6imfy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.1.0.jar",
          "url": "runelite-api-3.1.0.jar",
          "size": 1167334,
          "sha512": "c6cc2304f6fab971a4a59038b01154da8d1ec720b38ad94e2f242ea3b4c0f433fcbb36cc38bb637faccbe4072be2fba759412f62310023c518fe508d62747218",
          "sha256": "e2c3f5b9c72927038d18627373d07a13f3802eb4206b8d3521e56b20d9005ddb",
          "sha1": "e9d0184be4d84d3c37abbe2045f70cdecf0f304e",
          "md5": "0e96ae161d2a9e206d83cf3a7198911c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.1.0.jar",
          "url": "runelite-api-3.1.0.jar",
          "size": 1167334,
          "sha512": "c6cc2304f6fab971a4a59038b01154da8d1ec720b38ad94e2f242ea3b4c0f433fcbb36cc38bb637faccbe4072be2fba759412f62310023c518fe508d62747218",
          "sha256": "e2c3f5b9c72927038d18627373d07a13f3802eb4206b8d3521e56b20d9005ddb",
          "sha1": "e9d0184be4d84d3c37abbe2045f70cdecf0f304e",
          "md5": "0e96ae161d2a9e206d83cf3a7198911c"
        }
      ]
    }
  ]
}
