{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "otqveiv2azb5rmwjys3mkini5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.1.0.jar",
          "url": "runelite-api-3.1.0.jar",
          "size": 1175057,
          "sha512": "b89143fd5899eb068476e1e4a6e9ce7b19ca9af41c3c6543d989411671a827ceef106fb981890415bfcc8945b439b7121f41c37bdbcca498d3140f1b12c5765e",
          "sha256": "2fde47bc04a785a5f90cdef47a3a6d17aea2041b02f616d874843258841b292e",
          "sha1": "38f63180c186bd823db1ed60c0f9a373a7ef7c0d",
          "md5": "123c47f899e6afcac6840ee8fe2c5319"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.1.0.jar",
          "url": "runelite-api-3.1.0.jar",
          "size": 1175057,
          "sha512": "b89143fd5899eb068476e1e4a6e9ce7b19ca9af41c3c6543d989411671a827ceef106fb981890415bfcc8945b439b7121f41c37bdbcca498d3140f1b12c5765e",
          "sha256": "2fde47bc04a785a5f90cdef47a3a6d17aea2041b02f616d874843258841b292e",
          "sha1": "38f63180c186bd823db1ed60c0f9a373a7ef7c0d",
          "md5": "123c47f899e6afcac6840ee8fe2c5319"
        }
      ]
    }
  ]
}
