{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "yw2aotbcangcbbfrh4cicjtxcq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.4.1.jar",
          "url": "http-api-3.4.1.jar",
          "size": 158053,
          "sha512": "87ed50a19748a377912357f57876ed96edac77ab14970fc68b67db965907d4600f9726dd9fc57f82e6bc2d0c3afae3861cc891d6e7f401ca2b06d4065abcb11c",
          "sha256": "db63ba8fd4704a9533337f285d1626094775ee95a2715d1bbd2c146bb0ac3244",
          "sha1": "93cc18d207509fbb046c2209dc6431ec4829f0db",
          "md5": "913f6af9b4a4595b875d9ed518335eff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.4.1.jar",
          "url": "http-api-3.4.1.jar",
          "size": 158053,
          "sha512": "87ed50a19748a377912357f57876ed96edac77ab14970fc68b67db965907d4600f9726dd9fc57f82e6bc2d0c3afae3861cc891d6e7f401ca2b06d4065abcb11c",
          "sha256": "db63ba8fd4704a9533337f285d1626094775ee95a2715d1bbd2c146bb0ac3244",
          "sha1": "93cc18d207509fbb046c2209dc6431ec4829f0db",
          "md5": "913f6af9b4a4595b875d9ed518335eff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.4.1-sources.jar",
          "url": "http-api-3.4.1-sources.jar",
          "size": 103755,
          "sha512": "d85ebf12d82680047a98dd6dc7cf0fb6a0190783e7b995af30c8b46a01b5c07b68f80d1d36281327492306cfedbecd74b297afd67cbe887b9bae2a834f8ca465",
          "sha256": "761e54ce0484ac6e336c74850251a68da827738a087150f3336d899a6d34232f",
          "sha1": "0f57c2fdf40395f04bdcd15200e15d003649cb6b",
          "md5": "bd93fd000353becffe136fe942b9d9cd"
        }
      ]
    }
  ]
}
