{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "hpvf4eeohbeytetqsr23iyfmm4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.4.1.jar",
          "url": "http-api-3.4.1.jar",
          "size": 158053,
          "sha512": "a4125e0375ba50055da46ca59ffb48782e59a0c32baf92359fe35dbc30d514a811ac7f6e1552098852a11ce24df38a8919541ee133751e55782dfa694ad46b7a",
          "sha256": "c2944bde3afb32b9f03b95b3d1cd3b3ec81c3f45c03c42b0b7e8eaa1bc829395",
          "sha1": "2fdf3c927c40a6af409348d85f6ce28a186cc69e",
          "md5": "d287250a49bf20f4ff235bd954e404e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.4.1.jar",
          "url": "http-api-3.4.1.jar",
          "size": 158053,
          "sha512": "a4125e0375ba50055da46ca59ffb48782e59a0c32baf92359fe35dbc30d514a811ac7f6e1552098852a11ce24df38a8919541ee133751e55782dfa694ad46b7a",
          "sha256": "c2944bde3afb32b9f03b95b3d1cd3b3ec81c3f45c03c42b0b7e8eaa1bc829395",
          "sha1": "2fdf3c927c40a6af409348d85f6ce28a186cc69e",
          "md5": "d287250a49bf20f4ff235bd954e404e9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.4.1-sources.jar",
          "url": "http-api-3.4.1-sources.jar",
          "size": 103755,
          "sha512": "d85ebf12d82680047a98dd6dc7cf0fb6a0190783e7b995af30c8b46a01b5c07b68f80d1d36281327492306cfedbecd74b297afd67cbe887b9bae2a834f8ca465",
          "sha256": "761e54ce0484ac6e336c74850251a68da827738a087150f3336d899a6d34232f",
          "sha1": "0f57c2fdf40395f04bdcd15200e15d003649cb6b",
          "md5": "bd93fd000353becffe136fe942b9d9cd"
        }
      ]
    }
  ]
}
