{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "bmjwgkx5vfd2rjsdkpde7u4nve"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.6.jar",
          "url": "runelite-api-1.6.6.jar",
          "size": 1158718,
          "sha512": "9589271d7f761288988741d60b35a6730021a981f27605cd58bf11ab6df8eae386557613966c561fc01dcfa524a8d21146a63c0fc317941271df3ff83d56e6d7",
          "sha256": "ccf3bb90471fdc82fa73bfe27776542342ddeebcfbae8927755b16b20631a5e0",
          "sha1": "f7cac3339df86fa79cc617a25ba3b1dffea1618d",
          "md5": "27ac0a6ac484bbb81c245b0c327151cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.6.jar",
          "url": "runelite-api-1.6.6.jar",
          "size": 1158718,
          "sha512": "9589271d7f761288988741d60b35a6730021a981f27605cd58bf11ab6df8eae386557613966c561fc01dcfa524a8d21146a63c0fc317941271df3ff83d56e6d7",
          "sha256": "ccf3bb90471fdc82fa73bfe27776542342ddeebcfbae8927755b16b20631a5e0",
          "sha1": "f7cac3339df86fa79cc617a25ba3b1dffea1618d",
          "md5": "27ac0a6ac484bbb81c245b0c327151cf"
        }
      ]
    }
  ]
}
