{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "ytdarnbaczd3fiajnqxt2gaqoi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.4.3.jar",
          "url": "runescape-api-3.4.3.jar",
          "size": 104534,
          "sha512": "5ef31197cfe56936701345f1da97c2f795ffc6c877d7f8dd96cf3465af7c9c6a65e212dde8543cb54f2e78696d203b9c24888c2105e1f90f305efbe8d0e2c371",
          "sha256": "57287299683ab0fa27a1c5d7bcf1b846816d5a8bc9038b455404208d35cc7160",
          "sha1": "4abc674751e7072d05cfb49f037f0d3d5d931770",
          "md5": "8d232fc259f084e8ce143d9242e4dda3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.4.3.jar",
          "url": "runescape-api-3.4.3.jar",
          "size": 104534,
          "sha512": "5ef31197cfe56936701345f1da97c2f795ffc6c877d7f8dd96cf3465af7c9c6a65e212dde8543cb54f2e78696d203b9c24888c2105e1f90f305efbe8d0e2c371",
          "sha256": "57287299683ab0fa27a1c5d7bcf1b846816d5a8bc9038b455404208d35cc7160",
          "sha1": "4abc674751e7072d05cfb49f037f0d3d5d931770",
          "md5": "8d232fc259f084e8ce143d9242e4dda3"
        }
      ]
    }
  ]
}
