{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "f3upj6lb25f4dm4sitq246cwr4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.2.0.jar",
          "url": "runelite-api-3.2.0.jar",
          "size": 1175057,
          "sha512": "6db259d78dd73110eb15d4b10baac4f3831652f26a81cc05a9d800b4de8f353b09636f522be98515484bc06db33e39d3e904ec4534a7aa789b98205ac17b8eb2",
          "sha256": "f2dd7dcb6e84d432dd65e1b686ae67960c1f7448fa045fba2ca3a99fc3ef362b",
          "sha1": "00c600889937158d084b0adf2a3e9d07d85fccf6",
          "md5": "7bc050c948551f506a800253849a0e72"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.2.0.jar",
          "url": "runelite-api-3.2.0.jar",
          "size": 1175057,
          "sha512": "6db259d78dd73110eb15d4b10baac4f3831652f26a81cc05a9d800b4de8f353b09636f522be98515484bc06db33e39d3e904ec4534a7aa789b98205ac17b8eb2",
          "sha256": "f2dd7dcb6e84d432dd65e1b686ae67960c1f7448fa045fba2ca3a99fc3ef362b",
          "sha1": "00c600889937158d084b0adf2a3e9d07d85fccf6",
          "md5": "7bc050c948551f506a800253849a0e72"
        }
      ]
    }
  ]
}
