{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "nfciutv2ujbjdabtzzanx67oxe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.2.0.jar",
          "url": "runelite-api-3.2.0.jar",
          "size": 1175057,
          "sha512": "87fca7bb3e01d38d620d2a0901bf351ad3fb3f8c4c665eb26828128f3d925bb534d348f70a28336b867b353a7a42c20b88003d074bd274d7f40d0de9a4909daf",
          "sha256": "542620ed9bfb728f56f27b9706a076e3fec7b59e2b54f9ee4718ae9862c48563",
          "sha1": "ff85b2846f5a054c56a8ce194b199b468aaa1a43",
          "md5": "652ad1b4cda8218faddf328763b2e399"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.2.0.jar",
          "url": "runelite-api-3.2.0.jar",
          "size": 1175057,
          "sha512": "87fca7bb3e01d38d620d2a0901bf351ad3fb3f8c4c665eb26828128f3d925bb534d348f70a28336b867b353a7a42c20b88003d074bd274d7f40d0de9a4909daf",
          "sha256": "542620ed9bfb728f56f27b9706a076e3fec7b59e2b54f9ee4718ae9862c48563",
          "sha1": "ff85b2846f5a054c56a8ce194b199b468aaa1a43",
          "md5": "652ad1b4cda8218faddf328763b2e399"
        }
      ]
    }
  ]
}
