{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "qgjqkhrpkvchjjh2hyut7go6dy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.0.jar",
          "url": "runescape-api-3.3.0.jar",
          "size": 103468,
          "sha512": "7c7131bd0f2ce08de926266cfc7c170979c1499e59ccf4978787fcfb1b9ddee07fe3a4e25ded2ee5bb6d7ac9cb5281ad1378acc967c6e47a52edcd50a0e15f57",
          "sha256": "971bf1ea51e66c0f0767224a673b90cc128eec82ac110679308567bf7bd9f317",
          "sha1": "14815d6f39a4e4ea151b67d7dc6c926547fb5244",
          "md5": "1f7eecc6bd9e4054cce3c39838320a6c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.0.jar",
          "url": "runescape-api-3.3.0.jar",
          "size": 103468,
          "sha512": "7c7131bd0f2ce08de926266cfc7c170979c1499e59ccf4978787fcfb1b9ddee07fe3a4e25ded2ee5bb6d7ac9cb5281ad1378acc967c6e47a52edcd50a0e15f57",
          "sha256": "971bf1ea51e66c0f0767224a673b90cc128eec82ac110679308567bf7bd9f317",
          "sha1": "14815d6f39a4e4ea151b67d7dc6c926547fb5244",
          "md5": "1f7eecc6bd9e4054cce3c39838320a6c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.0-sources.jar",
          "url": "runescape-api-3.3.0-sources.jar",
          "size": 99524,
          "sha512": "62769b3d5cb9fc3366a31486413ac41e7c5d71e09a33091c69622ada0e03e411918b1a7b67189b16318f776e0a74a5caa8f823885cda514cdb03c3328f0097f7",
          "sha256": "06b645759ad6f4e0556ce5d3a10f39c608a7f52e4e6459250a110b814ee84797",
          "sha1": "015a30aef0bedd67c59f67e092c1dad4625d4282",
          "md5": "4506030a6de81f1c1b37a927bf390477"
        }
      ]
    }
  ]
}
