{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "dfcn57zhnfalhjjql6gnginsje"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.0.jar",
          "url": "runescape-api-3.3.0.jar",
          "size": 103468,
          "sha512": "eed8328c4910b313653a9da7948e95d178044eca6f7a2d27075fc47e66872388ea02a64b3b01f482cb15a72bf62df4bdebed116345be8ccb12e1ff7abb65c748",
          "sha256": "ab949044970313bbaa6c76fceefd67a5d1bf7d4c6d491080bab4785660252b44",
          "sha1": "930156f9f20b5a86d97bceae76a1db7d5574a8fe",
          "md5": "e626bade5a58bfa159ffdde5c33d5ac7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.0.jar",
          "url": "runescape-api-3.3.0.jar",
          "size": 103468,
          "sha512": "eed8328c4910b313653a9da7948e95d178044eca6f7a2d27075fc47e66872388ea02a64b3b01f482cb15a72bf62df4bdebed116345be8ccb12e1ff7abb65c748",
          "sha256": "ab949044970313bbaa6c76fceefd67a5d1bf7d4c6d491080bab4785660252b44",
          "sha1": "930156f9f20b5a86d97bceae76a1db7d5574a8fe",
          "md5": "e626bade5a58bfa159ffdde5c33d5ac7"
        }
      ]
    }
  ]
}
