{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "lc2dwjz7hjbxxka5u6clqnrssq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.0.jar",
          "url": "runescape-api-3.3.0.jar",
          "size": 103468,
          "sha512": "d6c4d249c8c11c5d1fa26efaaabe3c38bbffcbb0d0092e558790dd2f28ad177f6727dd3ea1f3eeeb8834f797730fdd7875a25740fba726b0ab67925da800d442",
          "sha256": "baad64efd674ef7804e280c718782979d75fab0b17e4bc67d043cb977ef13b95",
          "sha1": "684a7ef1086104ad9eb9f5bd2c7a3c3bc34771ea",
          "md5": "12897d6e6072cfce91ad0b073bcc7f49"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.0.jar",
          "url": "runescape-api-3.3.0.jar",
          "size": 103468,
          "sha512": "d6c4d249c8c11c5d1fa26efaaabe3c38bbffcbb0d0092e558790dd2f28ad177f6727dd3ea1f3eeeb8834f797730fdd7875a25740fba726b0ab67925da800d442",
          "sha256": "baad64efd674ef7804e280c718782979d75fab0b17e4bc67d043cb977ef13b95",
          "sha1": "684a7ef1086104ad9eb9f5bd2c7a3c3bc34771ea",
          "md5": "12897d6e6072cfce91ad0b073bcc7f49"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.0-sources.jar",
          "url": "runescape-api-3.3.0-sources.jar",
          "size": 99524,
          "sha512": "39d9556f49be50920b356594f289c2031dc891adbe369bac6ae3cd4a5e1cf0a25b0b18d967549a6c0517faedebb8931aadac56cea5eb67fe423937391a73523c",
          "sha256": "8685bc0275ba185ab2edf00ff38e5ccf3f4febc4fdd62b4f8ee3ebb395d09c9d",
          "sha1": "5a81bc687cf447281723b352f0b5bf1cc7c17b83",
          "md5": "49f5ed46b2bcde38719225de1e3172bd"
        }
      ]
    }
  ]
}
