{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "6wnuhmf4lnh2hkpdlgbiddxdcm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.1.0.jar",
          "url": "http-api-3.1.0.jar",
          "size": 164402,
          "sha512": "9908556b2004e87287ab2371c8f0afb855d4eb7fcde5193f3757c89fe8b9e0055ffb2e40c49cf13b2483296971afca58f40384de7896e9fe12d886a691ce7228",
          "sha256": "6a56fca6400ad5ddaf03edc6b78b707f83c8f5ee5d0fb101bd6e69c57b2e9512",
          "sha1": "dd7d25ec614f6e384e6faf2454c426331b8fe8ef",
          "md5": "cd2f0e05c95232f3f8bf2a0e3252357a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.1.0.jar",
          "url": "http-api-3.1.0.jar",
          "size": 164402,
          "sha512": "9908556b2004e87287ab2371c8f0afb855d4eb7fcde5193f3757c89fe8b9e0055ffb2e40c49cf13b2483296971afca58f40384de7896e9fe12d886a691ce7228",
          "sha256": "6a56fca6400ad5ddaf03edc6b78b707f83c8f5ee5d0fb101bd6e69c57b2e9512",
          "sha1": "dd7d25ec614f6e384e6faf2454c426331b8fe8ef",
          "md5": "cd2f0e05c95232f3f8bf2a0e3252357a"
        }
      ]
    }
  ]
}
