{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "wukzqye25fb5jkktkx65njupdm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.1.0.jar",
          "url": "http-api-3.1.0.jar",
          "size": 164403,
          "sha512": "6b958353a7c67b1f11c21d124be134028931075f167c949f32e5dc593101a66e66659bde23344413aaeadcb32c5d6220bb56292cfa9616f391c4be3e00117021",
          "sha256": "4aa87dbb1d5867750ae5188adf6db59b65772644aeb1f1efeacdba20e4ea9868",
          "sha1": "6930a734dee68deb4b421ebe9f4735c23f3b0181",
          "md5": "e1f4bda5673a082853ffe487e40ae060"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.1.0.jar",
          "url": "http-api-3.1.0.jar",
          "size": 164403,
          "sha512": "6b958353a7c67b1f11c21d124be134028931075f167c949f32e5dc593101a66e66659bde23344413aaeadcb32c5d6220bb56292cfa9616f391c4be3e00117021",
          "sha256": "4aa87dbb1d5867750ae5188adf6db59b65772644aeb1f1efeacdba20e4ea9868",
          "sha1": "6930a734dee68deb4b421ebe9f4735c23f3b0181",
          "md5": "e1f4bda5673a082853ffe487e40ae060"
        }
      ]
    }
  ]
}
