{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "hn36xoe3rzgv7dxswhm7euhej4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.1.0.jar",
          "url": "http-api-3.1.0.jar",
          "size": 164403,
          "sha512": "5d26fde11b572ce7da58a7d54380e471f1c2e867ae64d15da6bb1acea6564e3f999437433731a56d5907b5863caa4700c261c0001c10e18c0b05116fa6f8d8fc",
          "sha256": "d5c2b87cbe52902fc2266d834dcc119100116daee6921fac8ad3365e709f271d",
          "sha1": "402b6452bcf08b3b4e62731689efb9d633b884ee",
          "md5": "e86231de8eead392dc9817b5851f8499"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.1.0.jar",
          "url": "http-api-3.1.0.jar",
          "size": 164403,
          "sha512": "5d26fde11b572ce7da58a7d54380e471f1c2e867ae64d15da6bb1acea6564e3f999437433731a56d5907b5863caa4700c261c0001c10e18c0b05116fa6f8d8fc",
          "sha256": "d5c2b87cbe52902fc2266d834dcc119100116daee6921fac8ad3365e709f271d",
          "sha1": "402b6452bcf08b3b4e62731689efb9d633b884ee",
          "md5": "e86231de8eead392dc9817b5851f8499"
        }
      ]
    }
  ]
}
