{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "jngamcpxfzgoves7ilesk3hvq4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.7.jar",
          "url": "http-api-3.3.7.jar",
          "size": 154402,
          "sha512": "8efb5c19c41470afc507a04e8fc7521b65b158c9079e90610375fa5b0967ce7fb0bec0d0a162d1343ed18ed2583f1097195f3bfd901a7ef9967a52a3a338dcc2",
          "sha256": "6c5cb9894b18f6f0ea8015e250ebeb6f958b90b0335293282978d32e7602c7be",
          "sha1": "1c35763f6b420cb4bd8ff49fc413c6b4347a02f3",
          "md5": "b0c00b9261c5b55963ca5d367b97ee85"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.7.jar",
          "url": "http-api-3.3.7.jar",
          "size": 154402,
          "sha512": "8efb5c19c41470afc507a04e8fc7521b65b158c9079e90610375fa5b0967ce7fb0bec0d0a162d1343ed18ed2583f1097195f3bfd901a7ef9967a52a3a338dcc2",
          "sha256": "6c5cb9894b18f6f0ea8015e250ebeb6f958b90b0335293282978d32e7602c7be",
          "sha1": "1c35763f6b420cb4bd8ff49fc413c6b4347a02f3",
          "md5": "b0c00b9261c5b55963ca5d367b97ee85"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.7-sources.jar",
          "url": "http-api-3.3.7-sources.jar",
          "size": 101953,
          "sha512": "610c9455070c5e3f4d142c5e38d21fd74ab4e960e24d699a0fb0b4e4e86ec44e76d340b0bfac60cdcd84c00550b9c4393d7e2f898e0558426d5d8e4b2d7d356a",
          "sha256": "6aee9231311a770ce9c2ddb1b3728479208957c17cdd0f8bfbd87a2efb25f042",
          "sha1": "b52399da82469237adb120c416f71c4fbc1e13be",
          "md5": "bc95e0905a9a6599e93615c97e3a3020"
        }
      ]
    }
  ]
}
