{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "ne5zmxz7tnatlfcsu5aq2mdj6y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.1.jar",
          "url": "injected-client-3.3.1.jar",
          "size": 2252631,
          "sha512": "41d4ecb0ab0de39a89ab7c08ed1624bf259f77aa4c8399efbff14336c2d062223a180c6abf37f85f281971ec6f3747aa1d2adca3aac4c2359dde88ddbc89595a",
          "sha256": "676f53f529ce7bfdc3e2e8c3d0efbe58cff96f35bcb02a089441b0633e703875",
          "sha1": "f7e1dc1e9b9b863b7171644a3d37bb450c5cd993",
          "md5": "dd9ace744f12eecd85b8c6ced3bd8c96"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.1.jar",
          "url": "injected-client-3.3.1.jar",
          "size": 2252631,
          "sha512": "41d4ecb0ab0de39a89ab7c08ed1624bf259f77aa4c8399efbff14336c2d062223a180c6abf37f85f281971ec6f3747aa1d2adca3aac4c2359dde88ddbc89595a",
          "sha256": "676f53f529ce7bfdc3e2e8c3d0efbe58cff96f35bcb02a089441b0633e703875",
          "sha1": "f7e1dc1e9b9b863b7171644a3d37bb450c5cd993",
          "md5": "dd9ace744f12eecd85b8c6ced3bd8c96"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.1-sources.jar",
          "url": "injected-client-3.3.1-sources.jar",
          "size": 261,
          "sha512": "0b0c2ae3c38b0be1bfe563dfcb112c824b9407bf60a1165fcdbb9f753e04b8ded6712a720be91a0965b1aa9e447d17d4ac634520d2090bc993567205b9385f92",
          "sha256": "d84463c0dd84ffc9bc44606e2834828b4bd18b05233f0edb97be2d2542807d4c",
          "sha1": "e28772fcf427695b8c4257545267b8ab273ca1df",
          "md5": "e141a898207be35b4fd362c63f14fe96"
        },
        {
          "name": "injected-client-3.3.1.jar",
          "url": "injected-client-3.3.1.jar",
          "size": 2252631,
          "sha512": "41d4ecb0ab0de39a89ab7c08ed1624bf259f77aa4c8399efbff14336c2d062223a180c6abf37f85f281971ec6f3747aa1d2adca3aac4c2359dde88ddbc89595a",
          "sha256": "676f53f529ce7bfdc3e2e8c3d0efbe58cff96f35bcb02a089441b0633e703875",
          "sha1": "f7e1dc1e9b9b863b7171644a3d37bb450c5cd993",
          "md5": "dd9ace744f12eecd85b8c6ced3bd8c96"
        }
      ]
    }
  ]
}
