{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "winqrhre6nfgjeptp7pgrdfupm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.1.jar",
          "url": "injected-client-3.3.1.jar",
          "size": 2251550,
          "sha512": "157962eba3d9481092964fa2c368e96b5203beef75e7b417ed4ef19b01dc75444233cc693a7e883bad3bc9abc10c62497a557c10bec46c0c1220cb70edc6e973",
          "sha256": "f96c30db9f75c04706c2e488f239a9bc3f3c99895c2d2d473fbb676503321667",
          "sha1": "7ba6361ca9e27e62683a96cc050f190752799826",
          "md5": "9dd8b3eebb1c96479d77251cd8007bbc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.1.jar",
          "url": "injected-client-3.3.1.jar",
          "size": 2251550,
          "sha512": "157962eba3d9481092964fa2c368e96b5203beef75e7b417ed4ef19b01dc75444233cc693a7e883bad3bc9abc10c62497a557c10bec46c0c1220cb70edc6e973",
          "sha256": "f96c30db9f75c04706c2e488f239a9bc3f3c99895c2d2d473fbb676503321667",
          "sha1": "7ba6361ca9e27e62683a96cc050f190752799826",
          "md5": "9dd8b3eebb1c96479d77251cd8007bbc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.1-sources.jar",
          "url": "injected-client-3.3.1-sources.jar",
          "size": 261,
          "sha512": "1bb9b8d97cb0650cf00530b1ad10a6c876a1a6d0b36488e57ba65e2818c4593f8c2bfee4b2f3d84b77dd4877e2a813b0ddc898486f3e970d7696e43c333b4c4a",
          "sha256": "a46a6b5bb909854add6aba316cceb450bee3ab5160cb2c79974614a3826287f0",
          "sha1": "9f63613b833486163c54691cc7a0d271dc9b4338",
          "md5": "78e4d7a9df6ec35dca0f06bcd4cf62c3"
        },
        {
          "name": "injected-client-3.3.1.jar",
          "url": "injected-client-3.3.1.jar",
          "size": 2251550,
          "sha512": "157962eba3d9481092964fa2c368e96b5203beef75e7b417ed4ef19b01dc75444233cc693a7e883bad3bc9abc10c62497a557c10bec46c0c1220cb70edc6e973",
          "sha256": "f96c30db9f75c04706c2e488f239a9bc3f3c99895c2d2d473fbb676503321667",
          "sha1": "7ba6361ca9e27e62683a96cc050f190752799826",
          "md5": "9dd8b3eebb1c96479d77251cd8007bbc"
        }
      ]
    }
  ]
}
