{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "malatzhpafhqfdfe7wxbgsu66q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.1.jar",
          "url": "injected-client-3.3.1.jar",
          "size": 2252599,
          "sha512": "61a548c4ff8c1714a055f5e18e014c5d734e83497c71b8dbbf9bc0e250816d869e5017fb6cea9339e2b08423b4e9f41b5df827bdfbf71e40f3e66fd0ecbc1b78",
          "sha256": "9e929f38c73266858bb7ee98643f154e9f94111907b22b8d6ba3302bf688e123",
          "sha1": "be5b2552d6a64a9827d918dd603fa2c1b9ee1874",
          "md5": "879471c082e600f8e4050c1c48c89b03"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.1.jar",
          "url": "injected-client-3.3.1.jar",
          "size": 2252599,
          "sha512": "61a548c4ff8c1714a055f5e18e014c5d734e83497c71b8dbbf9bc0e250816d869e5017fb6cea9339e2b08423b4e9f41b5df827bdfbf71e40f3e66fd0ecbc1b78",
          "sha256": "9e929f38c73266858bb7ee98643f154e9f94111907b22b8d6ba3302bf688e123",
          "sha1": "be5b2552d6a64a9827d918dd603fa2c1b9ee1874",
          "md5": "879471c082e600f8e4050c1c48c89b03"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.1-sources.jar",
          "url": "injected-client-3.3.1-sources.jar",
          "size": 261,
          "sha512": "15b704532be6e26264249c16ce07f7743e590f03eb8de907cba8d0b098ea427a57381cccdeaf1fdb82a3b1fcfaba27086a170b7a756e2cd4974ed48eee1a50e1",
          "sha256": "14c5d4c3946642402a19284ea31a8ef42cb27f129f77fbee9e36b28dd29b4e9e",
          "sha1": "1478dae52c9f63bf678b805da8ffb98a50402333",
          "md5": "09d65831fc165bcde517904ee8f964a6"
        },
        {
          "name": "injected-client-3.3.1.jar",
          "url": "injected-client-3.3.1.jar",
          "size": 2252599,
          "sha512": "61a548c4ff8c1714a055f5e18e014c5d734e83497c71b8dbbf9bc0e250816d869e5017fb6cea9339e2b08423b4e9f41b5df827bdfbf71e40f3e66fd0ecbc1b78",
          "sha256": "9e929f38c73266858bb7ee98643f154e9f94111907b22b8d6ba3302bf688e123",
          "sha1": "be5b2552d6a64a9827d918dd603fa2c1b9ee1874",
          "md5": "879471c082e600f8e4050c1c48c89b03"
        }
      ]
    }
  ]
}
