{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "taqjrl6iavbcbojhk52alrpupi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.2.jar",
          "url": "runelite-api-3.3.2.jar",
          "size": 1182686,
          "sha512": "57a3f3f032493f59a58d07bf2f126e6a4884bcdaa720b09d4a7788c37405c128c018106d64eed013710c18b92672cc157b8d6f5a9fc691b9cdb79c491ce98d76",
          "sha256": "728864e2b06acbcf6c321d02e065b036cb87c23ed69e3578482c7deb2c4a99be",
          "sha1": "e1296b0ef26446a6130f7adf8071ae95293fff17",
          "md5": "0e7702985d7222c3af104de11fb31dbf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.2.jar",
          "url": "runelite-api-3.3.2.jar",
          "size": 1182686,
          "sha512": "57a3f3f032493f59a58d07bf2f126e6a4884bcdaa720b09d4a7788c37405c128c018106d64eed013710c18b92672cc157b8d6f5a9fc691b9cdb79c491ce98d76",
          "sha256": "728864e2b06acbcf6c321d02e065b036cb87c23ed69e3578482c7deb2c4a99be",
          "sha1": "e1296b0ef26446a6130f7adf8071ae95293fff17",
          "md5": "0e7702985d7222c3af104de11fb31dbf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.2-sources.jar",
          "url": "runelite-api-3.3.2-sources.jar",
          "size": 866814,
          "sha512": "213b63d4ae4430a09adcde56e9f950df536ab660ce8d931caf72ebdbbb1a79617a0810712f4c93c5ec8c6a4720c63a0a90b19fe529b99683ce8668066bc2b9c9",
          "sha256": "2f0fb5d009e476b0b66f97a4c4974a6811e9bac4a2729732ecd5c1d9eacd8036",
          "sha1": "19aec6edc1bdeccaed473ccbb5368c7f145b72c4",
          "md5": "c68eb7b3b977695e49f025838a333ecc"
        }
      ]
    }
  ]
}
