{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "f6xj3y7ut5btjc47nyd7vmrc2e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.2.jar",
          "url": "runelite-api-3.3.2.jar",
          "size": 1181672,
          "sha512": "70b849ef10a0a353520801293a50393a19f053151b92f1a1facac1b7fd4e4e017b12529e78e0c195ece3cf5e46706e09d8756e23ee455981c542d025747e2c39",
          "sha256": "5521bb57094cf5bb1bd46475644ac4f21345dd8dbcab278b203e27a248aff95b",
          "sha1": "6e793a8b47e1a0364f007a89e48336be3d44a3ea",
          "md5": "b6e1bee6b8e499ce27b430a13e08a018"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.2.jar",
          "url": "runelite-api-3.3.2.jar",
          "size": 1181672,
          "sha512": "70b849ef10a0a353520801293a50393a19f053151b92f1a1facac1b7fd4e4e017b12529e78e0c195ece3cf5e46706e09d8756e23ee455981c542d025747e2c39",
          "sha256": "5521bb57094cf5bb1bd46475644ac4f21345dd8dbcab278b203e27a248aff95b",
          "sha1": "6e793a8b47e1a0364f007a89e48336be3d44a3ea",
          "md5": "b6e1bee6b8e499ce27b430a13e08a018"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.2-sources.jar",
          "url": "runelite-api-3.3.2-sources.jar",
          "size": 866090,
          "sha512": "d9cd6291eea6c6eac989b7027727bfd12f0fed8634bc9b026633a8a961eab320405c663b53e57947a71186ca630730a4aad32a2f1a2ece50cb03066328e28b06",
          "sha256": "2a5a409c291b7ea69f5ddd196ba99cbe60e94313ae73913374c1f62da87d69f9",
          "sha1": "7ac47d7a9d7a63af790877faa23df55d89bf7fcf",
          "md5": "b7cf6730ce633cb22146c13675d936ea"
        }
      ]
    }
  ]
}
