{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "cxjd6axyubarpjvg5yipkt64ba"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.0.jar",
          "url": "injected-client-3.3.0.jar",
          "size": 2252595,
          "sha512": "03b1b41fae88eebe2d7b2129dded2e04ba85c165bb70e1f239a7addf40813971dc0fa3ddce96448af8cbc0e2e97733d309850e81687d441ac80276ce9bad00f1",
          "sha256": "76a6d6f740716a5f97c7b3b4ea0cabcc08cb1b01e2730470ce163bb9bbe8d2f1",
          "sha1": "33ae7551d8bfabafa30482fb4d59e0bf46339876",
          "md5": "319bba04e8932645b630b2085feb92bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.0.jar",
          "url": "injected-client-3.3.0.jar",
          "size": 2252595,
          "sha512": "03b1b41fae88eebe2d7b2129dded2e04ba85c165bb70e1f239a7addf40813971dc0fa3ddce96448af8cbc0e2e97733d309850e81687d441ac80276ce9bad00f1",
          "sha256": "76a6d6f740716a5f97c7b3b4ea0cabcc08cb1b01e2730470ce163bb9bbe8d2f1",
          "sha1": "33ae7551d8bfabafa30482fb4d59e0bf46339876",
          "md5": "319bba04e8932645b630b2085feb92bf"
        }
      ]
    }
  ]
}
