{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "dfcn57zhnfalhjjql6gnginsje"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.0.jar",
          "url": "injected-client-3.3.0.jar",
          "size": 2252595,
          "sha512": "6ab413865755587325c088e3e7d42d9fce220fe1c60af066cafce30e96ff96ffebd3e875dda62f1d728ea088cfa41e33d378992e9ba3b8cd675e5bf8c42f8415",
          "sha256": "c45648b4afd7f48685f24d41e76da79fde5a78cd51ccaf7255e3f87e415a85d8",
          "sha1": "addc4478c8a51fbe307b73805f2e5d91be4412cf",
          "md5": "2c78c268082adde52c7ad9db959c2e5c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.0.jar",
          "url": "injected-client-3.3.0.jar",
          "size": 2252595,
          "sha512": "6ab413865755587325c088e3e7d42d9fce220fe1c60af066cafce30e96ff96ffebd3e875dda62f1d728ea088cfa41e33d378992e9ba3b8cd675e5bf8c42f8415",
          "sha256": "c45648b4afd7f48685f24d41e76da79fde5a78cd51ccaf7255e3f87e415a85d8",
          "sha1": "addc4478c8a51fbe307b73805f2e5d91be4412cf",
          "md5": "2c78c268082adde52c7ad9db959c2e5c"
        }
      ]
    }
  ]
}
