{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "qgjqkhrpkvchjjh2hyut7go6dy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.0.jar",
          "url": "injected-client-3.3.0.jar",
          "size": 2252595,
          "sha512": "adf30ced8a59c39c9f99ef9199c7b9bc9e6e2fb827f099c6cef1c444220afa8db07cd8bd6c10644ba7ced607386204878729ed3b6ff18f1ae2e00f493b03462e",
          "sha256": "c1ff6a3a8bce5ef5fdb68a87416baf6e919fb43c9f72fe67a05b504dc444c373",
          "sha1": "fc1302e406f9fda0ffeab5ccc03b13b99183c339",
          "md5": "d97fca81f32e03b2aceb12b9dc1f874e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.0.jar",
          "url": "injected-client-3.3.0.jar",
          "size": 2252595,
          "sha512": "adf30ced8a59c39c9f99ef9199c7b9bc9e6e2fb827f099c6cef1c444220afa8db07cd8bd6c10644ba7ced607386204878729ed3b6ff18f1ae2e00f493b03462e",
          "sha256": "c1ff6a3a8bce5ef5fdb68a87416baf6e919fb43c9f72fe67a05b504dc444c373",
          "sha1": "fc1302e406f9fda0ffeab5ccc03b13b99183c339",
          "md5": "d97fca81f32e03b2aceb12b9dc1f874e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.0-sources.jar",
          "url": "injected-client-3.3.0-sources.jar",
          "size": 261,
          "sha512": "5344105d3acffe07a14195277ee5c561542a83bedc1b6af75a1aebba8108b7e314d9ba83221d32c24ad721529c025000ff234321fdafb9dae1205b54a1a0126e",
          "sha256": "5a6eb46850926c94b9438c86601706d7287240216de372c7c172afa73abf1c4d",
          "sha1": "58f33883c3240660ad941e96de90976990e4e70c",
          "md5": "460661e28c421582edefab02f1fe1bc1"
        },
        {
          "name": "injected-client-3.3.0.jar",
          "url": "injected-client-3.3.0.jar",
          "size": 2252595,
          "sha512": "adf30ced8a59c39c9f99ef9199c7b9bc9e6e2fb827f099c6cef1c444220afa8db07cd8bd6c10644ba7ced607386204878729ed3b6ff18f1ae2e00f493b03462e",
          "sha256": "c1ff6a3a8bce5ef5fdb68a87416baf6e919fb43c9f72fe67a05b504dc444c373",
          "sha1": "fc1302e406f9fda0ffeab5ccc03b13b99183c339",
          "md5": "d97fca81f32e03b2aceb12b9dc1f874e"
        }
      ]
    }
  ]
}
