{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "taqjrl6iavbcbojhk52alrpupi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.2.jar",
          "url": "http-api-3.3.2.jar",
          "size": 164097,
          "sha512": "d8ad6c4da0bd2332aa19d331b3760cf1fa189f4b3212882459b31eb2edab6367f9d7617bbf9167b7c0513792c2e303ae0562ca6939a3b88b5987bdf6288c1a96",
          "sha256": "f33386f3653ab9e2cf6b8f709d078e8cbeced4176df1a39a286ae0f123ac2530",
          "sha1": "3833696d2a17a37c8262d7577004b2df3e7c0169",
          "md5": "ef2e259561349a6e0cd9d5cb9bcc0c20"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.2.jar",
          "url": "http-api-3.3.2.jar",
          "size": 164097,
          "sha512": "d8ad6c4da0bd2332aa19d331b3760cf1fa189f4b3212882459b31eb2edab6367f9d7617bbf9167b7c0513792c2e303ae0562ca6939a3b88b5987bdf6288c1a96",
          "sha256": "f33386f3653ab9e2cf6b8f709d078e8cbeced4176df1a39a286ae0f123ac2530",
          "sha1": "3833696d2a17a37c8262d7577004b2df3e7c0169",
          "md5": "ef2e259561349a6e0cd9d5cb9bcc0c20"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.2-sources.jar",
          "url": "http-api-3.3.2-sources.jar",
          "size": 107156,
          "sha512": "334eb52560f7503e29f75711c8412f114be74ece60b678e4ead02e98af515a2979984bde2f4d6ba8f9e0c9384a28571f4cd2c60cb754de820878894d2e54d936",
          "sha256": "f2addbac8fa6273ee1b937f8a3a732bda387ca4ae97da744a7d6285b971c70ef",
          "sha1": "b3d598cfcbcf1841cb26922efef68c03cf8d6cbb",
          "md5": "ef5e85a0abcfa6bdc1a3f9c18e6f0700"
        }
      ]
    }
  ]
}
