{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "tiztyuvfznfixlzvedzgio4hpu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200208.000922-1.jar",
          "size": 1154972,
          "sha512": "cf0aa40d0156b4c5c21981252c881a998f89407517d262153cbcfa7d95ea48e7b186de2d228e50aaf633c1a4856db4e90a4ae42f483cd150089b360834690516",
          "sha256": "626c3c2178f16bbdccab3fbfe4e0a6685df4cafbe8ebdd2ab139893163634ca0",
          "sha1": "98018e71bb295a0159baccfb3587b5d79e297514",
          "md5": "0d8286e7a4fd1c372a0cf661b7a92bde"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200208.000922-1.jar",
          "size": 1154972,
          "sha512": "cf0aa40d0156b4c5c21981252c881a998f89407517d262153cbcfa7d95ea48e7b186de2d228e50aaf633c1a4856db4e90a4ae42f483cd150089b360834690516",
          "sha256": "626c3c2178f16bbdccab3fbfe4e0a6685df4cafbe8ebdd2ab139893163634ca0",
          "sha1": "98018e71bb295a0159baccfb3587b5d79e297514",
          "md5": "0d8286e7a4fd1c372a0cf661b7a92bde"
        }
      ]
    }
  ]
}
