{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "ryrj5ynzmvd4hnzdtpuifkq3hu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200131.203926-1.jar",
          "size": 1150995,
          "sha512": "a5ae276b9e25bec45ac292946c69e41101dcccb53c0bb308882b36a016aa701df980eac474ba26136852667041d20ee73e6873a1c25e6321d62c822e4c52574e",
          "sha256": "d61f310ef4c0d7ca79ec23740533ce7ef75ab4ccef91d155e12e2d7eaf2d5705",
          "sha1": "e9b177c821f8c6a27ea47cc2981696447e655cc9",
          "md5": "634612c52ff734a02840a4b89be11fe7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200131.203926-1.jar",
          "size": 1150995,
          "sha512": "a5ae276b9e25bec45ac292946c69e41101dcccb53c0bb308882b36a016aa701df980eac474ba26136852667041d20ee73e6873a1c25e6321d62c822e4c52574e",
          "sha256": "d61f310ef4c0d7ca79ec23740533ce7ef75ab4ccef91d155e12e2d7eaf2d5705",
          "sha1": "e9b177c821f8c6a27ea47cc2981696447e655cc9",
          "md5": "634612c52ff734a02840a4b89be11fe7"
        }
      ]
    }
  ]
}
