{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "pelk7vwaojfclombmt7ouwfsry"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200215.001224-1.jar",
          "size": 1158141,
          "sha512": "c226fba8b3d4b5e3fce9f33a6b4d760fc3676084991bea8cf32b51f49798342dadd52ce47b0c2f7d7a6e04daddcb71c96acb1f259f5bff0a455e4cae423f5d89",
          "sha256": "95ea1af0257273562647671dfb9d0fe4c5ede0d0c3d5dba1b10bb5ed1481d7d9",
          "sha1": "d06f3b04f41a34ac8be636182f98b0e8172284a7",
          "md5": "dd505c5bb100c5b5d80637b2431a5c60"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200215.001224-1.jar",
          "size": 1158141,
          "sha512": "c226fba8b3d4b5e3fce9f33a6b4d760fc3676084991bea8cf32b51f49798342dadd52ce47b0c2f7d7a6e04daddcb71c96acb1f259f5bff0a455e4cae423f5d89",
          "sha256": "95ea1af0257273562647671dfb9d0fe4c5ede0d0c3d5dba1b10bb5ed1481d7d9",
          "sha1": "d06f3b04f41a34ac8be636182f98b0e8172284a7",
          "md5": "dd505c5bb100c5b5d80637b2431a5c60"
        }
      ]
    }
  ]
}
