{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "nks3juklb5eunefxms6kyelpry"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200131.175257-1.jar",
          "size": 1150995,
          "sha512": "6cf1ff8f5ed52a809a5a08666c27b8faa653ab156e95b724233bff5ceb0593a6678e4bc89839703b28bb1fa40f915f0cfda255a17f7ec15a9cc952eecbde9435",
          "sha256": "d050b9963617f7d8c3d6bf10a03cee5ef114986f4d8165d908e062cec4c87ebb",
          "sha1": "8c1c313178337fcb0933485f06093d9e6202c65b",
          "md5": "96405841f73b9a9c798beeb4e78daa4c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200131.175257-1.jar",
          "size": 1150995,
          "sha512": "6cf1ff8f5ed52a809a5a08666c27b8faa653ab156e95b724233bff5ceb0593a6678e4bc89839703b28bb1fa40f915f0cfda255a17f7ec15a9cc952eecbde9435",
          "sha256": "d050b9963617f7d8c3d6bf10a03cee5ef114986f4d8165d908e062cec4c87ebb",
          "sha1": "8c1c313178337fcb0933485f06093d9e6202c65b",
          "md5": "96405841f73b9a9c798beeb4e78daa4c"
        }
      ]
    }
  ]
}
