{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "n5ytgqpd4vcmzlxxlmf3hpe33e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200206.153516-1.jar",
          "size": 1150996,
          "sha512": "0cebc5424f122f7e034b86b19511f893ed2a4e09d4cad628752b43488c31f6988891d5b5d893910c5894c336af0c13d4cfce7bd18cee3c046f92594a40081afa",
          "sha256": "7b62ae174652ed17cc003167638f11f2cf0ff2e34e64624c96ff76b0efecc795",
          "sha1": "22e136d72bcd212b2118d2e841e33b7902008c01",
          "md5": "61f1a7a3b9ac95b2c7e8075648ec41a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200206.153516-1.jar",
          "size": 1150996,
          "sha512": "0cebc5424f122f7e034b86b19511f893ed2a4e09d4cad628752b43488c31f6988891d5b5d893910c5894c336af0c13d4cfce7bd18cee3c046f92594a40081afa",
          "sha256": "7b62ae174652ed17cc003167638f11f2cf0ff2e34e64624c96ff76b0efecc795",
          "sha1": "22e136d72bcd212b2118d2e841e33b7902008c01",
          "md5": "61f1a7a3b9ac95b2c7e8075648ec41a1"
        }
      ]
    }
  ]
}
