{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "izq2qevp6ng6tmqpsmwfj2gwf4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200129.173414-1.jar",
          "size": 1150995,
          "sha512": "d30b65f72f472e32fc653301c5cda070b4357b418c761f697589223004aa1fbf2728a0de8ae3b003b10bb7b35de6cda19827ac82ad59225964071bbed837a0f9",
          "sha256": "6cb303657ea757661502298751af487983b2fdddfddf9ddd32f4f94ce7f49f25",
          "sha1": "7ecf0fbfce67ce27cfc21b54deceb766d6b171af",
          "md5": "7a8640fb0a3c98dbe6b8ab925ad26125"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200129.173414-1.jar",
          "size": 1150995,
          "sha512": "d30b65f72f472e32fc653301c5cda070b4357b418c761f697589223004aa1fbf2728a0de8ae3b003b10bb7b35de6cda19827ac82ad59225964071bbed837a0f9",
          "sha256": "6cb303657ea757661502298751af487983b2fdddfddf9ddd32f4f94ce7f49f25",
          "sha1": "7ecf0fbfce67ce27cfc21b54deceb766d6b171af",
          "md5": "7a8640fb0a3c98dbe6b8ab925ad26125"
        }
      ]
    }
  ]
}
