{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "f4uoenkc5bdpvjswckxlmyq7le"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200201.000847-1.jar",
          "size": 1150995,
          "sha512": "7a8ca8cadab165918c9e6e24bfd5f700bcb7aea7259d56fe28b30e6f252a73e8fc20427d2ed1797a7b755aa0256c3b132fda384649ce78879fbf17a0bad7a7d0",
          "sha256": "dd97147f5a6e5fdf03783b3639c7705c62ee09de78564999ef0f4bbde31606da",
          "sha1": "56670a3906fdd5579c373caf7947190051868847",
          "md5": "571b89cd1c113b31cb60b4323ffb5d7b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200201.000847-1.jar",
          "size": 1150995,
          "sha512": "7a8ca8cadab165918c9e6e24bfd5f700bcb7aea7259d56fe28b30e6f252a73e8fc20427d2ed1797a7b755aa0256c3b132fda384649ce78879fbf17a0bad7a7d0",
          "sha256": "dd97147f5a6e5fdf03783b3639c7705c62ee09de78564999ef0f4bbde31606da",
          "sha1": "56670a3906fdd5579c373caf7947190051868847",
          "md5": "571b89cd1c113b31cb60b4323ffb5d7b"
        }
      ]
    }
  ]
}
