{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "ltsdzirxwbdgtlo4qddimrbscq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200206.000857-1.jar",
          "size": 1150995,
          "sha512": "2aa8115199f03fdf4935cd78413d363e1e9f1f3ce736c501a2ce6166caae8a279e8732e62c6c6949897163e2bc36ef9f0f79ceebdf65b9bdab145273835aff5e",
          "sha256": "2141dc583e9fb0a6d0d73b0ef83b89a61a40eee072c3b4941619fd5598a5c23d",
          "sha1": "b39a4f9d1ae9b93c60d3e0c376e155a902455653",
          "md5": "ef8385aac07fc13774986739cd7a6598"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200206.000857-1.jar",
          "size": 1150995,
          "sha512": "2aa8115199f03fdf4935cd78413d363e1e9f1f3ce736c501a2ce6166caae8a279e8732e62c6c6949897163e2bc36ef9f0f79ceebdf65b9bdab145273835aff5e",
          "sha256": "2141dc583e9fb0a6d0d73b0ef83b89a61a40eee072c3b4941619fd5598a5c23d",
          "sha1": "b39a4f9d1ae9b93c60d3e0c376e155a902455653",
          "md5": "ef8385aac07fc13774986739cd7a6598"
        }
      ]
    }
  ]
}
