{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "6fkt64kyjfg57fb6jqmpgcldwe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200211.001142-1.jar",
          "size": 1156085,
          "sha512": "d0b98f7a0cfbc1fe7623c013e61bfcd61fd3192c75fc54228194ce1e87c9abe2d7a35d8d668d316636853c17fe7634c35ea53d0b30e77d3f119b5b4402e6ee4b",
          "sha256": "43c7827f6be5a2c728fa979851efa7baee0a58e4a1f6b0a7719f3d3e34014d76",
          "sha1": "debf19860d378bb26d8e346f2bb5e60d351780ac",
          "md5": "86894d24a5533d0877184f11aa0970ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200211.001142-1.jar",
          "size": 1156085,
          "sha512": "d0b98f7a0cfbc1fe7623c013e61bfcd61fd3192c75fc54228194ce1e87c9abe2d7a35d8d668d316636853c17fe7634c35ea53d0b30e77d3f119b5b4402e6ee4b",
          "sha256": "43c7827f6be5a2c728fa979851efa7baee0a58e4a1f6b0a7719f3d3e34014d76",
          "sha1": "debf19860d378bb26d8e346f2bb5e60d351780ac",
          "md5": "86894d24a5533d0877184f11aa0970ca"
        }
      ]
    }
  ]
}
