{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "hd2x4jqv4vcatk3rjnrmy3xgta"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200129.140204-1.jar",
          "size": 1150995,
          "sha512": "cb654dd5a48340c34a8abf65fdf84efdacd26690b041c97ffffaf6bef315910bf772de612812c7137231932ab34eadc4233537c27b1fe4f43169fa0d87289452",
          "sha256": "9d2406374d350c76b2b358fa4e744f2c8e17fb9a2ebbc0b926259baccac67896",
          "sha1": "ce8d7b43c49716296bccb938741f1846ce92fad7",
          "md5": "0533147be417825b64a7ca87b4542da5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200129.140204-1.jar",
          "size": 1150995,
          "sha512": "cb654dd5a48340c34a8abf65fdf84efdacd26690b041c97ffffaf6bef315910bf772de612812c7137231932ab34eadc4233537c27b1fe4f43169fa0d87289452",
          "sha256": "9d2406374d350c76b2b358fa4e744f2c8e17fb9a2ebbc0b926259baccac67896",
          "sha1": "ce8d7b43c49716296bccb938741f1846ce92fad7",
          "md5": "0533147be417825b64a7ca87b4542da5"
        }
      ]
    }
  ]
}
