{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "6garymirazahvbgjp3g6xxwspu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200207.000935-1.jar",
          "size": 1150996,
          "sha512": "87d2a8a1209a9298f9a1ce3eead245a8c87499b8dfd66ed430df77f8b4f44a5b3f29dfd504db267b7feae451c3c692467ce3c4c40607b18c89abfe796e6d8eb7",
          "sha256": "053aa7db416c497aae0323301188b742cd986e7a1ee0f5856d36556cc69678a4",
          "sha1": "2880729b81be1cd610781b1acaafe5e2065db153",
          "md5": "0d5656a33f78e2eb824e5e6ec9a7ca26"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200207.000935-1.jar",
          "size": 1150996,
          "sha512": "87d2a8a1209a9298f9a1ce3eead245a8c87499b8dfd66ed430df77f8b4f44a5b3f29dfd504db267b7feae451c3c692467ce3c4c40607b18c89abfe796e6d8eb7",
          "sha256": "053aa7db416c497aae0323301188b742cd986e7a1ee0f5856d36556cc69678a4",
          "sha1": "2880729b81be1cd610781b1acaafe5e2065db153",
          "md5": "0d5656a33f78e2eb824e5e6ec9a7ca26"
        }
      ]
    }
  ]
}
