{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "x5na3rh3jvcb5g2x2nwm5bocru"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200214.001210-1.jar",
          "size": 1158141,
          "sha512": "8a8b172a207100bd83b00dec084c1acb419c3aac8e4b11a59ce9eb444fff6028bed1f442094d901b1148ba5f5250be31e5e8443785439b4252ac19342706cb77",
          "sha256": "8b6328b4624e5b87e5ab2123439f37cc4f7ade07f5091fd530929d32803a7721",
          "sha1": "6ace8859ff8758303b5661e4f9c161d8545acd93",
          "md5": "356c1af8c68b9236bd5c118572c0001d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200214.001210-1.jar",
          "size": 1158141,
          "sha512": "8a8b172a207100bd83b00dec084c1acb419c3aac8e4b11a59ce9eb444fff6028bed1f442094d901b1148ba5f5250be31e5e8443785439b4252ac19342706cb77",
          "sha256": "8b6328b4624e5b87e5ab2123439f37cc4f7ade07f5091fd530929d32803a7721",
          "sha1": "6ace8859ff8758303b5661e4f9c161d8545acd93",
          "md5": "356c1af8c68b9236bd5c118572c0001d"
        }
      ]
    }
  ]
}
