{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "ac6pd77vwnduxh5v2pbsddkgfi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200213.001218-1.jar",
          "size": 1158141,
          "sha512": "106e416a6c034cf881263955c71aecef2eaca84eb025046d95e8824059272271ebf7f0774bc3f26e29258b23a336887d4c0698ad9d54ba5a1cfb0e795c156c02",
          "sha256": "01fc5bcc1e1c45d549848b29675942c3e90bc41002cc1f1096edbb5accc96f67",
          "sha1": "a70a9e702210c03b913cefdbd6b8f89203161382",
          "md5": "4f7d2d6c3d49ea12dd150ae160e31396"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200213.001218-1.jar",
          "size": 1158141,
          "sha512": "106e416a6c034cf881263955c71aecef2eaca84eb025046d95e8824059272271ebf7f0774bc3f26e29258b23a336887d4c0698ad9d54ba5a1cfb0e795c156c02",
          "sha256": "01fc5bcc1e1c45d549848b29675942c3e90bc41002cc1f1096edbb5accc96f67",
          "sha1": "a70a9e702210c03b913cefdbd6b8f89203161382",
          "md5": "4f7d2d6c3d49ea12dd150ae160e31396"
        }
      ]
    }
  ]
}
