{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "7rrh2oeceremxmn6hdow7wjqwi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200131.000935-1.jar",
          "size": 1150995,
          "sha512": "0ad515a0643255c92f185e2cffa63e84768158295773e3bd8c16f0ecf54da440250f221771cdd27a480f4fc76a4acace120b5eda6022b6a18168f5f9443f2aed",
          "sha256": "64a52a85bfd7949359d24d787cbb3394def88b67462d5920487be80fc0eec957",
          "sha1": "5c2fa9b149b1bf4215a3c01b787f0219e783b607",
          "md5": "2573b369885a2e53a8c967e49a5e51b5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200131.000935-1.jar",
          "size": 1150995,
          "sha512": "0ad515a0643255c92f185e2cffa63e84768158295773e3bd8c16f0ecf54da440250f221771cdd27a480f4fc76a4acace120b5eda6022b6a18168f5f9443f2aed",
          "sha256": "64a52a85bfd7949359d24d787cbb3394def88b67462d5920487be80fc0eec957",
          "sha1": "5c2fa9b149b1bf4215a3c01b787f0219e783b607",
          "md5": "2573b369885a2e53a8c967e49a5e51b5"
        }
      ]
    }
  ]
}
