{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "2rfhatrcbvgzjmlhghyvxvfy2a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200205.000903-1.jar",
          "size": 1150995,
          "sha512": "d4122daacc80d6399a6051a152026706c584642af6573e04b7b108e23bce8f849e387aa69f12dd33614179717cf4eaad7dd3d3efc1d54e81690c89789a33e738",
          "sha256": "37a34ad3cc476aa99bd52311b3ad614775e00931dafff734f9831872f3356421",
          "sha1": "8fe6d369949149150d5159c6c048d1855eed7230",
          "md5": "f9d6512a01c9758d2d7d1902dd2b7660"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200205.000903-1.jar",
          "size": 1150995,
          "sha512": "d4122daacc80d6399a6051a152026706c584642af6573e04b7b108e23bce8f849e387aa69f12dd33614179717cf4eaad7dd3d3efc1d54e81690c89789a33e738",
          "sha256": "37a34ad3cc476aa99bd52311b3ad614775e00931dafff734f9831872f3356421",
          "sha1": "8fe6d369949149150d5159c6c048d1855eed7230",
          "md5": "f9d6512a01c9758d2d7d1902dd2b7660"
        }
      ]
    }
  ]
}
