{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "dvgrgv5jv5fpvhst277gs744wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.7.jar",
          "url": "runelite-api-1.6.7.jar",
          "size": 1160683,
          "sha512": "f11b01351a08eb3c6f3264c110ad56bd1f2dab5cade19187dd48a29377ddf3b7c0453159004301600da0c695252755a5a7a05b84a8a8acab27521aa314f2e3ff",
          "sha256": "cef46e1c0a71faf3274b5564e2338d23ff9fbe523db4f007463cad149ba1229c",
          "sha1": "5d625f4af89490b9476fa8aaebda81b3dec43758",
          "md5": "5a21865c1c2546370a1b8ad08136467a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.7.jar",
          "url": "runelite-api-1.6.7.jar",
          "size": 1160683,
          "sha512": "f11b01351a08eb3c6f3264c110ad56bd1f2dab5cade19187dd48a29377ddf3b7c0453159004301600da0c695252755a5a7a05b84a8a8acab27521aa314f2e3ff",
          "sha256": "cef46e1c0a71faf3274b5564e2338d23ff9fbe523db4f007463cad149ba1229c",
          "sha1": "5d625f4af89490b9476fa8aaebda81b3dec43758",
          "md5": "5a21865c1c2546370a1b8ad08136467a"
        }
      ]
    }
  ]
}
