{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "odg5knamwbaehhc5e3ideqdcju"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.7.jar",
          "url": "runelite-api-1.6.7.jar",
          "size": 1160683,
          "sha512": "ae695f3542b44c4cb945b7da6bac453d5c945b2312d664ef55ac34689f1259e5ac0d4f326d4256d2a7852c2245e0a545b864af93e574a767823e524a9299b734",
          "sha256": "63f7ffac30e3173b69aefa4ca74a09b9cd0eb2da3b4eef7a2f6f1665fefa7293",
          "sha1": "bc81367c8b30a39c900d60bcc761d9b5a1d0b5cc",
          "md5": "0325ce4a05caecdb1c6bfa28834c28a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.7.jar",
          "url": "runelite-api-1.6.7.jar",
          "size": 1160683,
          "sha512": "ae695f3542b44c4cb945b7da6bac453d5c945b2312d664ef55ac34689f1259e5ac0d4f326d4256d2a7852c2245e0a545b864af93e574a767823e524a9299b734",
          "sha256": "63f7ffac30e3173b69aefa4ca74a09b9cd0eb2da3b4eef7a2f6f1665fefa7293",
          "sha1": "bc81367c8b30a39c900d60bcc761d9b5a1d0b5cc",
          "md5": "0325ce4a05caecdb1c6bfa28834c28a4"
        }
      ]
    }
  ]
}
