{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "76vxovm35vho3fh3kjzwhlf6g4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.3-SNAPSHOT.jar",
          "url": "http-api-1.6.3-20200120.000839-1.jar",
          "size": 157779,
          "sha512": "dee386faa7084853672632bdd08a2c47429008494be0591db481c6fbfac3a4f6f951f3e991d9d83ac884915b3b625b58c06d490f8402b1b069e0ee1c9fa85ac6",
          "sha256": "76bdad104660cfba0e85ff0b48c8add659a5e949907638f38d0deafe05e5a1cd",
          "sha1": "214316ce7cfced61ae693a3e5aa4a9fba225ee2b",
          "md5": "c19788c7665c931f206ef49d3899d493"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.3-SNAPSHOT.jar",
          "url": "http-api-1.6.3-20200120.000839-1.jar",
          "size": 157779,
          "sha512": "dee386faa7084853672632bdd08a2c47429008494be0591db481c6fbfac3a4f6f951f3e991d9d83ac884915b3b625b58c06d490f8402b1b069e0ee1c9fa85ac6",
          "sha256": "76bdad104660cfba0e85ff0b48c8add659a5e949907638f38d0deafe05e5a1cd",
          "sha1": "214316ce7cfced61ae693a3e5aa4a9fba225ee2b",
          "md5": "c19788c7665c931f206ef49d3899d493"
        }
      ]
    }
  ]
}
