{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "t5j3pwdnrbdafejetpgfjj6hpi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.3-SNAPSHOT.jar",
          "url": "http-api-1.6.3-20200122.000949-1.jar",
          "size": 161221,
          "sha512": "233647f0b48a71951e61b6ac02e3bf2a896db3d694dbe2945d8bfdea45659d376c34138c717ff72c4f6bfbaa08b9a4912e4ab738af89a06dc5e27724f6bb0400",
          "sha256": "f327fdaa96d00d07073aec6bf6c2ebd3550f07283a3a24a74f2e2e496cfa09c4",
          "sha1": "7f71e9e17c196c70b8f6c5b86412667bc3b735d1",
          "md5": "475ba44c7b86c11c541ebfead26aa7be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.3-SNAPSHOT.jar",
          "url": "http-api-1.6.3-20200122.000949-1.jar",
          "size": 161221,
          "sha512": "233647f0b48a71951e61b6ac02e3bf2a896db3d694dbe2945d8bfdea45659d376c34138c717ff72c4f6bfbaa08b9a4912e4ab738af89a06dc5e27724f6bb0400",
          "sha256": "f327fdaa96d00d07073aec6bf6c2ebd3550f07283a3a24a74f2e2e496cfa09c4",
          "sha1": "7f71e9e17c196c70b8f6c5b86412667bc3b735d1",
          "md5": "475ba44c7b86c11c541ebfead26aa7be"
        }
      ]
    }
  ]
}
