{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "kwndnbmqzvg7roez2rv3mhfbna"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.3-SNAPSHOT.jar",
          "url": "http-api-1.6.3-20200118.222052-1.jar",
          "size": 159918,
          "sha512": "79c62eb9a3220f709fa31c6d9b7440c7e746bcc4b3cb64530b35140b0af2a67a6aae916b012ca2777e0f8170b91dd10ec4d9eda51b67afc51f1c4c5784f6f966",
          "sha256": "7500ec6bbb92eca05f218708f50d3057287adaa8943006358cc435d4af9f45c4",
          "sha1": "3657539e0cd88a94924952d6cd05ab05ad286a1d",
          "md5": "459e1b917e501a25979380a9f882eef5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.3-SNAPSHOT.jar",
          "url": "http-api-1.6.3-20200118.222052-1.jar",
          "size": 159918,
          "sha512": "79c62eb9a3220f709fa31c6d9b7440c7e746bcc4b3cb64530b35140b0af2a67a6aae916b012ca2777e0f8170b91dd10ec4d9eda51b67afc51f1c4c5784f6f966",
          "sha256": "7500ec6bbb92eca05f218708f50d3057287adaa8943006358cc435d4af9f45c4",
          "sha1": "3657539e0cd88a94924952d6cd05ab05ad286a1d",
          "md5": "459e1b917e501a25979380a9f882eef5"
        }
      ]
    }
  ]
}
