{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "ufew7df6zfbltauic36ac6yszy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.3-SNAPSHOT.jar",
          "url": "http-api-1.6.3-20200119.000859-1.jar",
          "size": 159919,
          "sha512": "fa75113384f350dd6465f3956c8d2b322eec3e9bfcba0175f3ded52f594ae5e8c692e679e7b1ca215b2f083a10d9d3e608b57b0da216dc901b6e44091f92c931",
          "sha256": "09a20b67e615431960efefd7113ff8e78b28782ecea350d443bed675d3a1157f",
          "sha1": "7311a39b5b3adb733bc29d39e8fa777cfaefd86f",
          "md5": "8a01f233862dec8a0c2f9f4f2259fb7f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.3-SNAPSHOT.jar",
          "url": "http-api-1.6.3-20200119.000859-1.jar",
          "size": 159919,
          "sha512": "fa75113384f350dd6465f3956c8d2b322eec3e9bfcba0175f3ded52f594ae5e8c692e679e7b1ca215b2f083a10d9d3e608b57b0da216dc901b6e44091f92c931",
          "sha256": "09a20b67e615431960efefd7113ff8e78b28782ecea350d443bed675d3a1157f",
          "sha1": "7311a39b5b3adb733bc29d39e8fa777cfaefd86f",
          "md5": "8a01f233862dec8a0c2f9f4f2259fb7f"
        }
      ]
    }
  ]
}
