{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "lga66gpwabbedon5gdqb3bsigi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.3-SNAPSHOT.jar",
          "url": "http-api-1.6.3-20200123.001038-1.jar",
          "size": 161220,
          "sha512": "b65067fa446d0cb0e7ac2df7c6d2b953bbd0e21247084b11c1dfb86331f3f06b70a54c8039404b840d3d9e8aaaf9f4e43ed88be174285212b539b6d471727f48",
          "sha256": "129b24da2ba5b93c82e60bdbbebef5815a51ac476861f1a08b378f92606b7f11",
          "sha1": "5c943440897ebb74b6165ba127f1c7caad13ffbd",
          "md5": "38e2469e83608eeff77dd044e786e087"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.3-SNAPSHOT.jar",
          "url": "http-api-1.6.3-20200123.001038-1.jar",
          "size": 161220,
          "sha512": "b65067fa446d0cb0e7ac2df7c6d2b953bbd0e21247084b11c1dfb86331f3f06b70a54c8039404b840d3d9e8aaaf9f4e43ed88be174285212b539b6d471727f48",
          "sha256": "129b24da2ba5b93c82e60bdbbebef5815a51ac476861f1a08b378f92606b7f11",
          "sha1": "5c943440897ebb74b6165ba127f1c7caad13ffbd",
          "md5": "38e2469e83608eeff77dd044e786e087"
        }
      ]
    }
  ]
}
