{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "2yty7ku6y5hslg3tf45hxegi6m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.3-SNAPSHOT.jar",
          "url": "http-api-1.6.3-20200121.000800-1.jar",
          "size": 157779,
          "sha512": "5d542e2dede2367ce815c02cbf0834a4bf01c14a9b696e62021650867f92131b60d56df1181d098a4b537a702b8dff6fe403a0b9fec0d63c5e7dd0054c0549a2",
          "sha256": "034cbd3211d2fbdd7831977e14da7a0574a030c35776ada45f1099f452f5fd58",
          "sha1": "c0da1e74d1f773284d017d41411d4707ba025550",
          "md5": "1518fbd8023c88b1bfcb5cc527570b84"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.3-SNAPSHOT.jar",
          "url": "http-api-1.6.3-20200121.000800-1.jar",
          "size": 157779,
          "sha512": "5d542e2dede2367ce815c02cbf0834a4bf01c14a9b696e62021650867f92131b60d56df1181d098a4b537a702b8dff6fe403a0b9fec0d63c5e7dd0054c0549a2",
          "sha256": "034cbd3211d2fbdd7831977e14da7a0574a030c35776ada45f1099f452f5fd58",
          "sha1": "c0da1e74d1f773284d017d41411d4707ba025550",
          "md5": "1518fbd8023c88b1bfcb5cc527570b84"
        }
      ]
    }
  ]
}
