{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "ettx7xwp5rf2tfabpq4mlbblhm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.4.0.jar",
          "url": "runescape-api-3.4.0.jar",
          "size": 103971,
          "sha512": "392165f49faa99ade47b5ef3b7f51a520261811c6a1c1af2c398f1539ae0a2901502d169735462a2280c9630526a57802ea43f10aed8e5e6237b6845f32e2bd1",
          "sha256": "323f1ae9f58c143696f3e12bb3d6bbd0efcaef1034ce3d441a74d3ddbb5933ba",
          "sha1": "ba7c49773ac3419fabaecb4af9af7ec7406a336f",
          "md5": "0792d5a315bb9f500044dd52f25765a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.4.0.jar",
          "url": "runescape-api-3.4.0.jar",
          "size": 103971,
          "sha512": "392165f49faa99ade47b5ef3b7f51a520261811c6a1c1af2c398f1539ae0a2901502d169735462a2280c9630526a57802ea43f10aed8e5e6237b6845f32e2bd1",
          "sha256": "323f1ae9f58c143696f3e12bb3d6bbd0efcaef1034ce3d441a74d3ddbb5933ba",
          "sha1": "ba7c49773ac3419fabaecb4af9af7ec7406a336f",
          "md5": "0792d5a315bb9f500044dd52f25765a8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.4.0-sources.jar",
          "url": "runescape-api-3.4.0-sources.jar",
          "size": 100742,
          "sha512": "15f5696a66d1b507eacba02eeef12b17ef4fc4cf1b867101557e79f643ba9b4052bcc8efcbf7781ea05d5e7cf92b1f025225d3b280d31cda848af3a682423aec",
          "sha256": "554758b65b2da21b7559fd94d05ae2e4bb1e293902c6a7b33c5fc1ea652fb4cb",
          "sha1": "c8a617d9da8e72df92a5e7d5e35492f599815164",
          "md5": "19524ab67e211675fc317620f69925f6"
        }
      ]
    }
  ]
}
