{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "5ssghafjsjbf3lvumjhizic7e4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.2.1.jar",
          "url": "runelite-api-3.2.1.jar",
          "size": 1177444,
          "sha512": "7ae1f94a5470f3e3613506b1cb3121eeec8dee9fac5a568d0920b1cb357c93867090b82dd8ec79c2aff781382379cca0f4641fea0c9830371fb00bbe4e64c449",
          "sha256": "68853d02253453e6114b14b2f563c27e19b8a88b9acc020c4eca36bb8c7ddabd",
          "sha1": "6ebac610ceea6b6e4af153cdfe351f94446b471f",
          "md5": "fc2d45bbbe68cfb677b5f7ae3995fb0c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.2.1.jar",
          "url": "runelite-api-3.2.1.jar",
          "size": 1177444,
          "sha512": "7ae1f94a5470f3e3613506b1cb3121eeec8dee9fac5a568d0920b1cb357c93867090b82dd8ec79c2aff781382379cca0f4641fea0c9830371fb00bbe4e64c449",
          "sha256": "68853d02253453e6114b14b2f563c27e19b8a88b9acc020c4eca36bb8c7ddabd",
          "sha1": "6ebac610ceea6b6e4af153cdfe351f94446b471f",
          "md5": "fc2d45bbbe68cfb677b5f7ae3995fb0c"
        }
      ]
    }
  ]
}
