{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "ayqukufk5rd7fgqq3pqi3qjtji"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.2.1.jar",
          "url": "runelite-api-3.2.1.jar",
          "size": 1177469,
          "sha512": "e9fae5aa3eff9cb4998994da3cd4e4b581523eb5fb3f4f09c53daa45d4069bcaf49084aeaa37270c56736513d233b2b3eeef0808ff2de4b934659b97ac83758a",
          "sha256": "b0940c03c4b954d04b3909e114fc3f54a102db415471c244a2cd108360364dcd",
          "sha1": "d2367549b965633350ca6f2a8c194fad170d0545",
          "md5": "f6daca36ab84dad686dd90394422ddd2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.2.1.jar",
          "url": "runelite-api-3.2.1.jar",
          "size": 1177469,
          "sha512": "e9fae5aa3eff9cb4998994da3cd4e4b581523eb5fb3f4f09c53daa45d4069bcaf49084aeaa37270c56736513d233b2b3eeef0808ff2de4b934659b97ac83758a",
          "sha256": "b0940c03c4b954d04b3909e114fc3f54a102db415471c244a2cd108360364dcd",
          "sha1": "d2367549b965633350ca6f2a8c194fad170d0545",
          "md5": "f6daca36ab84dad686dd90394422ddd2"
        }
      ]
    }
  ]
}
