{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "cxhso3hhi5gmvbdpof67rgfccu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.2.1.jar",
          "url": "runelite-api-3.2.1.jar",
          "size": 1176466,
          "sha512": "2101b45fd5cf6decd57e77fdf13c6bd1254c4740bbd1f8e9df3feefeda0125cc53c1bc01dbf36983941547db9e8c02566a8eaa0604bee90d36126d467c1ba47b",
          "sha256": "f79c4ad2c58863d3100056d4a396fb824af4660c6eed416965efdb99e9d13861",
          "sha1": "85abb483dd08d4e2ca562f7757d74ba01601b0b6",
          "md5": "1e59340084a11b289c2447f1c4131cff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.2.1.jar",
          "url": "runelite-api-3.2.1.jar",
          "size": 1176466,
          "sha512": "2101b45fd5cf6decd57e77fdf13c6bd1254c4740bbd1f8e9df3feefeda0125cc53c1bc01dbf36983941547db9e8c02566a8eaa0604bee90d36126d467c1ba47b",
          "sha256": "f79c4ad2c58863d3100056d4a396fb824af4660c6eed416965efdb99e9d13861",
          "sha1": "85abb483dd08d4e2ca562f7757d74ba01601b0b6",
          "md5": "1e59340084a11b289c2447f1c4131cff"
        }
      ]
    }
  ]
}
