{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "ofjaddfu3fcxnc5gpdvv35gy5e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.0.jar",
          "url": "injected-client-3.3.0.jar",
          "size": 2252595,
          "sha512": "b5935cf9d9461ecc369b75a6a3da9385c7e7e89e6c1bd8a00a86312821ca4f5205fe3dc1614293f961e12d5ad5931f5268e0182184a57a2d8c528cf3054b8aab",
          "sha256": "bba137213179ea20e9c5590871fa3be63685ff2152fce63e9d82dd343f1cd4c2",
          "sha1": "205b76522921fe988859ebf19459e5798620389f",
          "md5": "99ebf7db821849452f9afc9cd33f6ab6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.0.jar",
          "url": "injected-client-3.3.0.jar",
          "size": 2252595,
          "sha512": "b5935cf9d9461ecc369b75a6a3da9385c7e7e89e6c1bd8a00a86312821ca4f5205fe3dc1614293f961e12d5ad5931f5268e0182184a57a2d8c528cf3054b8aab",
          "sha256": "bba137213179ea20e9c5590871fa3be63685ff2152fce63e9d82dd343f1cd4c2",
          "sha1": "205b76522921fe988859ebf19459e5798620389f",
          "md5": "99ebf7db821849452f9afc9cd33f6ab6"
        }
      ]
    }
  ]
}
