{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "mzfay7dm35dihouqd2djvy2ukq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.5.2.jar",
          "url": "runelite-api-3.5.2.jar",
          "size": 1236425,
          "sha512": "2591a2acdbe587bf9c3c791ddca5dc185aca56f0fbdb1d2a57319b7d51c8054638caedee62ea1ef37ac1384d36ca33d22fe500e9fefe5df881d76c2923f7d2a3",
          "sha256": "1d16091b7c4a7e9f54b94dd17cb4156ed98e1295a400acb83c9ef6bc9cd40995",
          "sha1": "9123fcb381c26add5ab7b26dd43b675db914567c",
          "md5": "4e75aed38c1faf58e59398299a29d97a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.5.2.jar",
          "url": "runelite-api-3.5.2.jar",
          "size": 1236425,
          "sha512": "2591a2acdbe587bf9c3c791ddca5dc185aca56f0fbdb1d2a57319b7d51c8054638caedee62ea1ef37ac1384d36ca33d22fe500e9fefe5df881d76c2923f7d2a3",
          "sha256": "1d16091b7c4a7e9f54b94dd17cb4156ed98e1295a400acb83c9ef6bc9cd40995",
          "sha1": "9123fcb381c26add5ab7b26dd43b675db914567c",
          "md5": "4e75aed38c1faf58e59398299a29d97a"
        }
      ]
    }
  ]
}
