{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "3cumxpvzszckfde5iljmtuhxmm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.2.jar",
          "url": "runelite-api-3.3.2.jar",
          "size": 1181672,
          "sha512": "9d62c2e873fe28a5fdfb56f74ba5fa92004d6e53fb10197b57a0a63bf22c73e67e47ca9a69576892ff08de0d1f449221e246a96de61d872f5b1438e08fc1b0e1",
          "sha256": "4228ebb3c91a8f28e03c52279353e066ee396e74fdf0ad0fef70ec0964fb947d",
          "sha1": "c6e101270e84d5eee735ba11d3f57c919285b2d2",
          "md5": "faa38ed2f836109f53db694ee2eb1e41"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.2.jar",
          "url": "runelite-api-3.3.2.jar",
          "size": 1181672,
          "sha512": "9d62c2e873fe28a5fdfb56f74ba5fa92004d6e53fb10197b57a0a63bf22c73e67e47ca9a69576892ff08de0d1f449221e246a96de61d872f5b1438e08fc1b0e1",
          "sha256": "4228ebb3c91a8f28e03c52279353e066ee396e74fdf0ad0fef70ec0964fb947d",
          "sha1": "c6e101270e84d5eee735ba11d3f57c919285b2d2",
          "md5": "faa38ed2f836109f53db694ee2eb1e41"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.2-sources.jar",
          "url": "runelite-api-3.3.2-sources.jar",
          "size": 866090,
          "sha512": "94c9c5e8474cf8c8150ea3d9fd05d1fe5cfebe8abdcb352d71f87e903dbf09e1c702244643f4d6384623af772a75db69947525ca7a68bfc504c00c1592744612",
          "sha256": "e8919c97793fd3fc14fb893fd65a38a1aeb0cae13ce2c938052a2629b8388568",
          "sha1": "1d9a7fa578f64428b8b83a58ea4acb658009fe82",
          "md5": "bda508f2c014ebccee50d74693a07460"
        }
      ]
    }
  ]
}
