{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "rgsjahkotbax3llwkocflj34qy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.2.jar",
          "url": "runelite-api-3.3.2.jar",
          "size": 1182644,
          "sha512": "b7ccda10dfd9fa1739f99934db3684a76fbc3cd0dac4ad65a124b8283b96a0e82c9836a385c6fcfef503ec14a4e4ebd2ac6ef663a9d4a00c5e674bc779eef4b9",
          "sha256": "07e8c74afafb62c4d0dc7dec88498d29e83c630247b9508c7a01f7669424f44e",
          "sha1": "3c12df1075b6824bede80a73ac5629f72aad9c6d",
          "md5": "0b99784dede6d84e7bfa270f28b640d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.2.jar",
          "url": "runelite-api-3.3.2.jar",
          "size": 1182644,
          "sha512": "b7ccda10dfd9fa1739f99934db3684a76fbc3cd0dac4ad65a124b8283b96a0e82c9836a385c6fcfef503ec14a4e4ebd2ac6ef663a9d4a00c5e674bc779eef4b9",
          "sha256": "07e8c74afafb62c4d0dc7dec88498d29e83c630247b9508c7a01f7669424f44e",
          "sha1": "3c12df1075b6824bede80a73ac5629f72aad9c6d",
          "md5": "0b99784dede6d84e7bfa270f28b640d6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.2-sources.jar",
          "url": "runelite-api-3.3.2-sources.jar",
          "size": 866709,
          "sha512": "5be5ae0921d181cc7a574ac3ef686b5c599d9ed10f09666bbbe46d1a34d8ad96b33a26a00a2711cd306b629241d7d1a7716b56bbb965a584f3f952774dc4115c",
          "sha256": "e2a9f31ae038ec272aa1938c8a2f16b6fa32db7fa5124d1924ce84e6b97e7b20",
          "sha1": "2bf2430040348aec46728846d44cbbb2e631e42a",
          "md5": "e105f8d32a82d87c97850d5f7ed2ccec"
        }
      ]
    }
  ]
}
