{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "kwxhedpo4zgwvfvzlx6kunma3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.2.jar",
          "url": "runelite-api-3.3.2.jar",
          "size": 1182655,
          "sha512": "b1179e165d0dbf52d398e86ef46f8b0f7e0f5ff2a10b2c7cd215c586659604ed75350704de608f02c5e9483d1d896e5876d725edf9d867f370d92e36e09f519b",
          "sha256": "17aaec01d9be8b6d20c6bd8e0aa4f7b927a07e7f137cf6e2c8af36b5891ddb1b",
          "sha1": "d4a32e2c2ba8ad65742c130bf88ca04df3d7d430",
          "md5": "2c569b61024120726cdd408ccf3c11e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.2.jar",
          "url": "runelite-api-3.3.2.jar",
          "size": 1182655,
          "sha512": "b1179e165d0dbf52d398e86ef46f8b0f7e0f5ff2a10b2c7cd215c586659604ed75350704de608f02c5e9483d1d896e5876d725edf9d867f370d92e36e09f519b",
          "sha256": "17aaec01d9be8b6d20c6bd8e0aa4f7b927a07e7f137cf6e2c8af36b5891ddb1b",
          "sha1": "d4a32e2c2ba8ad65742c130bf88ca04df3d7d430",
          "md5": "2c569b61024120726cdd408ccf3c11e5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.2-sources.jar",
          "url": "runelite-api-3.3.2-sources.jar",
          "size": 866769,
          "sha512": "60ef402cb6e1ee3ecc881595f3341f416c0c814adf87b5014349cba1c881dcdeb851705d997d2adfb83681f4e8ae403dc4f454bb91e8533f46ae3ec2daea2d57",
          "sha256": "1782f9c699ccf93794161e68bb79464c096cb6b8371d8603d4a399d36125ba46",
          "sha1": "d78b052ea6b1118e5ee35726edf07fd751f931aa",
          "md5": "d3ec0decd86f15a9222e86dffc483692"
        }
      ]
    }
  ]
}
