{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "atbknxixjbgaljjpvkhkmpgxrq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.0.jar",
          "url": "injected-client-3.3.0.jar",
          "size": 2252595,
          "sha512": "6d944b1088662c682bc8be603fbee4d8ee44a43349ac6d14a3070eb5ac447eaf315b88d288a7f6fc9ed18f0ce6f0f4915af5bca4f7e1856d7d08be08aa0d9361",
          "sha256": "08c84f826c7c806c1ae07d738a8d6e889c83d48f2bffde9a9de3e899ebb4fa42",
          "sha1": "ebbb579a5a7b3f6ebc45260bcc02acaa762742a1",
          "md5": "76e26828148787510ab63c322664bcd8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.0.jar",
          "url": "injected-client-3.3.0.jar",
          "size": 2252595,
          "sha512": "6d944b1088662c682bc8be603fbee4d8ee44a43349ac6d14a3070eb5ac447eaf315b88d288a7f6fc9ed18f0ce6f0f4915af5bca4f7e1856d7d08be08aa0d9361",
          "sha256": "08c84f826c7c806c1ae07d738a8d6e889c83d48f2bffde9a9de3e899ebb4fa42",
          "sha1": "ebbb579a5a7b3f6ebc45260bcc02acaa762742a1",
          "md5": "76e26828148787510ab63c322664bcd8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.0-sources.jar",
          "url": "injected-client-3.3.0-sources.jar",
          "size": 261,
          "sha512": "424058285d97dd9067ecce2c152d5dae00fcf948865236a4c0e365e8248bfeb1a16f331688725315a5ec6b95d4b7816eee66a3aec74d1018e6c2c121f4f2fb01",
          "sha256": "66bc151b0f60f48de5f4a9e96796563bd10c042277af17b9f4c604c67f151633",
          "sha1": "553713f64faf89bb2cff27b4a90f9b7ef5ec3d79",
          "md5": "a9fa21a5092fbff9d6bb63891713c8d2"
        },
        {
          "name": "injected-client-3.3.0.jar",
          "url": "injected-client-3.3.0.jar",
          "size": 2252595,
          "sha512": "6d944b1088662c682bc8be603fbee4d8ee44a43349ac6d14a3070eb5ac447eaf315b88d288a7f6fc9ed18f0ce6f0f4915af5bca4f7e1856d7d08be08aa0d9361",
          "sha256": "08c84f826c7c806c1ae07d738a8d6e889c83d48f2bffde9a9de3e899ebb4fa42",
          "sha1": "ebbb579a5a7b3f6ebc45260bcc02acaa762742a1",
          "md5": "76e26828148787510ab63c322664bcd8"
        }
      ]
    }
  ]
}
