{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "bxmcylkl6farbfd3u7e2f7kxku"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.9"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.9.jar",
          "url": "runescape-api-3.3.9.jar",
          "size": 103804,
          "sha512": "84d6cec29cad4dcaff7837e56096629bf2a25af7938d2b66210447fe02ed8003af4c9a0fd1d83cfa10b80a3cd5ccbea6815ac8ddc21983e8be9d2465791bcfd4",
          "sha256": "c7d8b876add06624e5f649be082cc593c4e12705eb4f22b45ab93464bee9d4d4",
          "sha1": "b17eedf92c8ecce4a77ab0089e548004a4b283b4",
          "md5": "945f1d1875176755a8179cebd44af29e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.9"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.9.jar",
          "url": "runescape-api-3.3.9.jar",
          "size": 103804,
          "sha512": "84d6cec29cad4dcaff7837e56096629bf2a25af7938d2b66210447fe02ed8003af4c9a0fd1d83cfa10b80a3cd5ccbea6815ac8ddc21983e8be9d2465791bcfd4",
          "sha256": "c7d8b876add06624e5f649be082cc593c4e12705eb4f22b45ab93464bee9d4d4",
          "sha1": "b17eedf92c8ecce4a77ab0089e548004a4b283b4",
          "md5": "945f1d1875176755a8179cebd44af29e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.9-sources.jar",
          "url": "runescape-api-3.3.9-sources.jar",
          "size": 99887,
          "sha512": "45ad82e52c626928e4bc6d4ef46e9c1533a68530d69029a11d687ef3fc62a242799f4010dc2de9d8091033d9cc2721ee875304208db4b0f9592a272b66bed874",
          "sha256": "ee26b8cd8ea5fe162678c0264261a1c86e180f66fddf6e064aa32880ae928b7b",
          "sha1": "2015dd1bd381422f54f4862f7fe7345af979ffde",
          "md5": "09323d55a4b6e324ed69eb403424086d"
        }
      ]
    }
  ]
}
