{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "b54trkceujcplpatavyavejajq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.8.jar",
          "url": "runescape-api-1.6.8.jar",
          "size": 55336,
          "sha512": "85a56592bd59bd0fe62647865f4ad1681f258dc9256a96365f3379f20cd6c148a2dc76fe5518782114c8aaf4c17eac5506491c8b0c487b345f0ef23cf9607049",
          "sha256": "c556b6c5dc94245fbed5167a2adbb585950c8f0661a7491a57ee17de2cd14c8d",
          "sha1": "61a7e41f5ff8954744c7e78851aeaf4ebdf8a545",
          "md5": "1d82162d2a8dbbee6cfda655e8ce6572"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.8.jar",
          "url": "runescape-api-1.6.8.jar",
          "size": 55336,
          "sha512": "85a56592bd59bd0fe62647865f4ad1681f258dc9256a96365f3379f20cd6c148a2dc76fe5518782114c8aaf4c17eac5506491c8b0c487b345f0ef23cf9607049",
          "sha256": "c556b6c5dc94245fbed5167a2adbb585950c8f0661a7491a57ee17de2cd14c8d",
          "sha1": "61a7e41f5ff8954744c7e78851aeaf4ebdf8a545",
          "md5": "1d82162d2a8dbbee6cfda655e8ce6572"
        }
      ]
    }
  ]
}
