{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "2ua3o4f2sbf7dg4uwufk6ekduu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.8.jar",
          "url": "runescape-api-1.6.8.jar",
          "size": 55336,
          "sha512": "af7d9d08f7278ec0aa037d5d3f11866bf2a14e0ad665776b3216e8b4288e715581809f06ec12c98ab3630da475dba6b5a096c6a21fec1a4b89faf8b1c0b6ce61",
          "sha256": "5ca832a25f4a7909b6166fe8d59cd4519f74db14956de1c03ca37949ed9ce4bd",
          "sha1": "b3d17d428a73c96ce0c1f2aae742c926c056aff1",
          "md5": "6efd378c7d454f30f49824c3245c8896"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.8.jar",
          "url": "runescape-api-1.6.8.jar",
          "size": 55336,
          "sha512": "af7d9d08f7278ec0aa037d5d3f11866bf2a14e0ad665776b3216e8b4288e715581809f06ec12c98ab3630da475dba6b5a096c6a21fec1a4b89faf8b1c0b6ce61",
          "sha256": "5ca832a25f4a7909b6166fe8d59cd4519f74db14956de1c03ca37949ed9ce4bd",
          "sha1": "b3d17d428a73c96ce0c1f2aae742c926c056aff1",
          "md5": "6efd378c7d454f30f49824c3245c8896"
        }
      ]
    }
  ]
}
