{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "nuncon336zeubambeenhobop2m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.8.jar",
          "url": "runelite-api-3.3.8.jar",
          "size": 1214462,
          "sha512": "acda36c24c89c1107d0ee69d369faf9d0ca2f4b482ecaf277925de82b75ce145506eee306186ff13e5c80f03a37a0077bea13e90c72fc22eb378ed5daa3aa7a4",
          "sha256": "861f9d2edbc451fbd1c1551efba9a19ced6001f956f3c8ae4a7a60d952e7e89a",
          "sha1": "6163996ba25f70dec8b317fef1d21a597780d0ce",
          "md5": "136db69469b959a47a8610f3671d8919"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.8.jar",
          "url": "runelite-api-3.3.8.jar",
          "size": 1214462,
          "sha512": "acda36c24c89c1107d0ee69d369faf9d0ca2f4b482ecaf277925de82b75ce145506eee306186ff13e5c80f03a37a0077bea13e90c72fc22eb378ed5daa3aa7a4",
          "sha256": "861f9d2edbc451fbd1c1551efba9a19ced6001f956f3c8ae4a7a60d952e7e89a",
          "sha1": "6163996ba25f70dec8b317fef1d21a597780d0ce",
          "md5": "136db69469b959a47a8610f3671d8919"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.8-sources.jar",
          "url": "runelite-api-3.3.8-sources.jar",
          "size": 888797,
          "sha512": "ed589c65be7d9cb052cc0bee72243e26665ad18be53d80f741b1ec610ec1e35b8833366eca5c661b5056498e5594af5cf822933faf55df4f0e3cdba7f2057809",
          "sha256": "e152d8c311dc9105e5f722a9aec62e4112b03b92ca88f95e0bff077c928f2d4e",
          "sha1": "0b8cdce18f1f73377203aa25d57edfed9d89c91f",
          "md5": "435105a700d82dc1603aa44d5dcb168d"
        }
      ]
    }
  ]
}
