{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "wwzawqbmqvgknlpoyhrokjmaaa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.8.jar",
          "url": "runelite-api-3.3.8.jar",
          "size": 1214215,
          "sha512": "c1f556d92c16de95def6cd94416af0abce2cf67eb10fdea1b86c44d148aa79cb5daa02f3bef8dcb9f8140d0a249d0c1a0092fcf51bd8f990e35e397b1f1207ab",
          "sha256": "fdd18f47872c03ca457b8a2fadc1ccf59c86879b84a514b946612e6b7221c2ed",
          "sha1": "7c563eb655679fc79c41e3ec075bc86153fc24cf",
          "md5": "5d251532ce6b983325782558a0f7a6aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.8.jar",
          "url": "runelite-api-3.3.8.jar",
          "size": 1214215,
          "sha512": "c1f556d92c16de95def6cd94416af0abce2cf67eb10fdea1b86c44d148aa79cb5daa02f3bef8dcb9f8140d0a249d0c1a0092fcf51bd8f990e35e397b1f1207ab",
          "sha256": "fdd18f47872c03ca457b8a2fadc1ccf59c86879b84a514b946612e6b7221c2ed",
          "sha1": "7c563eb655679fc79c41e3ec075bc86153fc24cf",
          "md5": "5d251532ce6b983325782558a0f7a6aa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.8-sources.jar",
          "url": "runelite-api-3.3.8-sources.jar",
          "size": 888647,
          "sha512": "bb2483d3a9df8d6eaa481a2edb64f539eb784381155f2ded767ddac6ea69675559d90e79a1459b1b01f00c3053bd96e09fa35469eb01e611236ce0acc302b835",
          "sha256": "8deb6638a25156fe9ab8faf88a455a8849398aad2e718d5ae447eda791719d05",
          "sha1": "87eafff37b6e442dbac29c3ec97181e96689c2e3",
          "md5": "9a1f838088a1c52fdf83adceaee33707"
        }
      ]
    }
  ]
}
