{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "ag7kba57wnhh3fmqilynicfq5m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.4.jar",
          "url": "runelite-api-3.3.4.jar",
          "size": 1183603,
          "sha512": "d55b0961da7b28311720a71cf3acb4fca0cb74932d2556817c69226aa7d8e6304ed0ca5b61b996b55955e8ee0be93f2a8efe1807f954ca840eb19dd48862146c",
          "sha256": "5bbb5117167b69834ca2c8ffb84e23f9ba92f21dcb869f7de00f698d35e1c7ae",
          "sha1": "0242af5a73b56e2782ac08993e1ff81ea273dddb",
          "md5": "3681c46f2317965c14723610f154fa8c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.4.jar",
          "url": "runelite-api-3.3.4.jar",
          "size": 1183603,
          "sha512": "d55b0961da7b28311720a71cf3acb4fca0cb74932d2556817c69226aa7d8e6304ed0ca5b61b996b55955e8ee0be93f2a8efe1807f954ca840eb19dd48862146c",
          "sha256": "5bbb5117167b69834ca2c8ffb84e23f9ba92f21dcb869f7de00f698d35e1c7ae",
          "sha1": "0242af5a73b56e2782ac08993e1ff81ea273dddb",
          "md5": "3681c46f2317965c14723610f154fa8c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.4-sources.jar",
          "url": "runelite-api-3.3.4-sources.jar",
          "size": 868075,
          "sha512": "19aa7e5af19428f2b0cf1fed09a9f43a9163e0fff5eccf4bd3f3522fb4faf9c25b3032d14a95d74a415d5f98f5252e25f10a9c5d2e1855092a9b04982769ded7",
          "sha256": "3578cbc60103e75fcf2bb7596a6f095c2a45a4518bf4309a79a64d3f98e1265f",
          "sha1": "94e7df21e9cd42a22aed7b3b9f447e5e4fae8976",
          "md5": "8e0667d40abe8594e9cedb1ea1efc0d4"
        }
      ]
    }
  ]
}
