{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "3xcuqhh27fbdpmcyy5i5cb3ivm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.4.jar",
          "url": "runelite-api-3.3.4.jar",
          "size": 1183668,
          "sha512": "313286f7c08e9e50bf1cbf43b0ce4c360de13db3eca549f5f0fbbc9d62afe858761c8ff7c1c897762d4e8d9121d5c7e3178618443fe49c06a83818a602b548a2",
          "sha256": "41b336a7109bebf265379e87550b0fc21c4057dfcd417b3e62e02423db4f0b73",
          "sha1": "de9aee36f861cd0a4826be9cfd8df6cd89561874",
          "md5": "cff3064f744ffcfa0230a843300a1e22"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.4.jar",
          "url": "runelite-api-3.3.4.jar",
          "size": 1183668,
          "sha512": "313286f7c08e9e50bf1cbf43b0ce4c360de13db3eca549f5f0fbbc9d62afe858761c8ff7c1c897762d4e8d9121d5c7e3178618443fe49c06a83818a602b548a2",
          "sha256": "41b336a7109bebf265379e87550b0fc21c4057dfcd417b3e62e02423db4f0b73",
          "sha1": "de9aee36f861cd0a4826be9cfd8df6cd89561874",
          "md5": "cff3064f744ffcfa0230a843300a1e22"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.4-sources.jar",
          "url": "runelite-api-3.3.4-sources.jar",
          "size": 868493,
          "sha512": "306504f52c3e54342ef63f9f44bb762f2b0f45343ee70af7b0fb70e2bc50c1aa6a66af6810f1876ecc7c5dd03a97342a94f531ffb5683c11a0e8b97e029adac7",
          "sha256": "bce4f33d5d6b296655b095404cf4f2614c0027313512dc107a7217b5631ceb0d",
          "sha1": "0857b46413e6742de8153c56cd3b3d2edd0abfc4",
          "md5": "256d416471505211df449bb2e2d2c1d3"
        }
      ]
    }
  ]
}
