{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "irwk6tfda5ggthdjh4gmblg62q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.4.jar",
          "url": "runelite-api-3.3.4.jar",
          "size": 1183603,
          "sha512": "14b63daef787640988637ecf89a7eaeae78c7266a4663cd81fe761e862f7098fbbf1dd3f1fe45349506d2e34717fffafc2bcbf767d30ceeb26932cd07e5a8830",
          "sha256": "1aa53b2b363a8fd7344a3395b6c8af7e0328a545ab3c15411074bf5b94147ead",
          "sha1": "f33e62f901b5d580d2121f7a6e444d5997233e8b",
          "md5": "b88a271c2b87c58e0ca76a6b407069b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.4.jar",
          "url": "runelite-api-3.3.4.jar",
          "size": 1183603,
          "sha512": "14b63daef787640988637ecf89a7eaeae78c7266a4663cd81fe761e862f7098fbbf1dd3f1fe45349506d2e34717fffafc2bcbf767d30ceeb26932cd07e5a8830",
          "sha256": "1aa53b2b363a8fd7344a3395b6c8af7e0328a545ab3c15411074bf5b94147ead",
          "sha1": "f33e62f901b5d580d2121f7a6e444d5997233e8b",
          "md5": "b88a271c2b87c58e0ca76a6b407069b1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.4-sources.jar",
          "url": "runelite-api-3.3.4-sources.jar",
          "size": 868075,
          "sha512": "740253bf7be5e97c77528a8df167a13c6f24f549de9163032e2a20fa2213e7f715b09643e3a75e0df7e9f3c4442e6ec530df1b3d956dae5d435ca2958dd7a0de",
          "sha256": "36f28b705722cf2f7acdfbc2dd33abb030626253c4720476edf307e2a1315066",
          "sha1": "2df08aff4adb7d181c86ba443ba5da61a114f06c",
          "md5": "2758d9441f9dfc637f15d6cf5e1a3cc2"
        }
      ]
    }
  ]
}
