{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "2c3ukkycprglrc6ddokf4panqa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.9"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.9.jar",
          "url": "runescape-api-1.6.9.jar",
          "size": 55336,
          "sha512": "43dfee530fffe850b4773fbdd1125194f5a071329f3e274bde9aa0e5c91688851b65437c4221340bb2505ba007ce122b54c418a40dcdad8a7174ee21f732f3b9",
          "sha256": "9d492fbaef1ff38cf865698660b558563b023d016c993b83ca2db9a5b153f0c7",
          "sha1": "c33decb35c922c921007646ff4eaec86892b1f6d",
          "md5": "ce30322d9041ce92fa54fc32e63d0167"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.9"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.9.jar",
          "url": "runescape-api-1.6.9.jar",
          "size": 55336,
          "sha512": "43dfee530fffe850b4773fbdd1125194f5a071329f3e274bde9aa0e5c91688851b65437c4221340bb2505ba007ce122b54c418a40dcdad8a7174ee21f732f3b9",
          "sha256": "9d492fbaef1ff38cf865698660b558563b023d016c993b83ca2db9a5b153f0c7",
          "sha1": "c33decb35c922c921007646ff4eaec86892b1f6d",
          "md5": "ce30322d9041ce92fa54fc32e63d0167"
        }
      ]
    }
  ]
}
