{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "sgsnhkex2nct5gfzg5oz63fg7u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.9"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.9.jar",
          "url": "runescape-api-1.6.9.jar",
          "size": 55336,
          "sha512": "919eedb9cf6a667926b76619b0c068b69fd4be468af682996a9381620604f68125a035577cfc432d03637774e2085fe5a9643d9b5a32038de92602fd85b060b6",
          "sha256": "93aecdfa06d9dc9c1538cfd1ba32260f44553218e55f2a6ea361e2236f2c391f",
          "sha1": "76d94865684526ee5ac0e809cc7603b4b47c6ede",
          "md5": "ef79e0819e75501553237ec69d5e613e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.9"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.9.jar",
          "url": "runescape-api-1.6.9.jar",
          "size": 55336,
          "sha512": "919eedb9cf6a667926b76619b0c068b69fd4be468af682996a9381620604f68125a035577cfc432d03637774e2085fe5a9643d9b5a32038de92602fd85b060b6",
          "sha256": "93aecdfa06d9dc9c1538cfd1ba32260f44553218e55f2a6ea361e2236f2c391f",
          "sha1": "76d94865684526ee5ac0e809cc7603b4b47c6ede",
          "md5": "ef79e0819e75501553237ec69d5e613e"
        }
      ]
    }
  ]
}
