{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "bclice7o7vgdbg2hmmze3s6kpe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.6.jar",
          "url": "http-api-1.6.6.jar",
          "size": 165766,
          "sha512": "52cd2f9ae684e3e97b7cd85b4444bf676963b82b37c3b78de9e7fa2303437ace0c1b097b1ae0b9c5d5f1389f5df7f34eca5d56291cb9a9c53d21c128c892a385",
          "sha256": "e468b8a43c5a28a4db62e5b5f365d2d29aff3240298e69bf1024a7c29f613df6",
          "sha1": "1e9038a15514bd6cf61653747f5fa41055490795",
          "md5": "f7d282fae665fc8265f9bf87d782ea06"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.6.jar",
          "url": "http-api-1.6.6.jar",
          "size": 165766,
          "sha512": "52cd2f9ae684e3e97b7cd85b4444bf676963b82b37c3b78de9e7fa2303437ace0c1b097b1ae0b9c5d5f1389f5df7f34eca5d56291cb9a9c53d21c128c892a385",
          "sha256": "e468b8a43c5a28a4db62e5b5f365d2d29aff3240298e69bf1024a7c29f613df6",
          "sha1": "1e9038a15514bd6cf61653747f5fa41055490795",
          "md5": "f7d282fae665fc8265f9bf87d782ea06"
        }
      ]
    }
  ]
}
