{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-client",
    "version": "3.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "3pkvvpxbbnctlkzpyhegapxwaa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.8"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-client-3.3.8.jar",
          "url": "runelite-client-3.3.8.jar",
          "size": 2666187,
          "sha512": "7a7a0e01f079702f34d9254dc4dbdaecf2c975cf13f275d4eeb805720960c9dd32ddd191b3808132b72dfdf9dc02e0227804837fe3a8eae29a3e339ba8427079",
          "sha256": "0fa2dbc668dffab07eb106fe0f7f44348b964e4104f23ce21e730dd03030ed4a",
          "sha1": "5f44127e5b04ecf66dbfc5047abbc6e6f9c82c96",
          "md5": "3106ebebd95007d5cc188287c26c8bbb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "4.2.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "guice",
              "type": "jar",
              "extension": "jar",
              "classifier": "no_aop"
            }
          }
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "1.4.200"
          }
        },
        {
          "group": "com.jakewharton.rxrelay3",
          "module": "rxrelay",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "org.jgroups",
          "module": "jgroups",
          "version": {
            "requires": "4.2.4.Final"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "net.runelite",
          "module": "discord",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.pushing-pixels",
          "module": "radiance-substance",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "19.0.0"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq",
          "version": {
            "requires": "3.13.2"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq-codegen",
          "version": {
            "requires": "3.13.2"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq-meta",
          "version": {
            "requires": "3.13.2"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-logback",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.github.zafarkhaja",
          "module": "java-semver",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.pf4j",
          "module": "pf4j",
          "version": {
            "requires": "3.3.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.pf4j",
          "module": "pf4j-update",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "http-api",
          "version": {
            "requires": "3.3.8"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.8"
          }
        },
        {
          "group": "org.pushing-pixels",
          "module": "radiance-trident",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injected-client",
          "version": {
            "requires": "3.3.8"
          }
        },
        {
          "group": "com.openosrs.rs",
          "module": "runescape-api",
          "version": {
            "requires": "3.3.8"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-client-3.3.8.jar",
          "url": "runelite-client-3.3.8.jar",
          "size": 2666187,
          "sha512": "7a7a0e01f079702f34d9254dc4dbdaecf2c975cf13f275d4eeb805720960c9dd32ddd191b3808132b72dfdf9dc02e0227804837fe3a8eae29a3e339ba8427079",
          "sha256": "0fa2dbc668dffab07eb106fe0f7f44348b964e4104f23ce21e730dd03030ed4a",
          "sha1": "5f44127e5b04ecf66dbfc5047abbc6e6f9c82c96",
          "md5": "3106ebebd95007d5cc188287c26c8bbb"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-client-3.3.8-shaded.jar",
          "url": "runelite-client-3.3.8-shaded.jar",
          "size": 31459590,
          "sha512": "a5254b802b6961022ec60b8fc1db694fe8c31c362312b3fcb35e3675aa10cbb948e5198dd1d6c9fe89a23fb7bfc9bc2af1d5eb13196dcd7412fa61f030713567",
          "sha256": "31414d9df19ca78e0ef739972e87a2b5370e576f1f8e1abfd2a947fa3af51c3d",
          "sha1": "af715436599fd47235b38e3e69e50a158e57bbef",
          "md5": "ed7568661db1343fb4a1d8cd2c27eb79"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-client-3.3.8-sources.jar",
          "url": "runelite-client-3.3.8-sources.jar",
          "size": 2317503,
          "sha512": "bfbac5b26b8ae447be615e742e0b86824b933f3745d68ca4737c8287c9074010d397ab9ed7ad8bdfa0278e67614acf2de40826ebedc3e7d526b3b1f58f97dfc4",
          "sha256": "1666e9fd125ce96ab51c345bde5e2a81cb4f60a4ec3abfcc9778b2e211557481",
          "sha1": "6f543cbb8854da5c1d96c7a274f69bd98008648b",
          "md5": "8f2ca12dd3c613f9b9066641e9264608"
        }
      ]
    }
  ]
}
