{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "k4b3uicimzhprkhxnr6zuyyyf4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.6-SNAPSHOT.jar",
          "url": "http-api-1.6.6-20200209.222511-2.jar",
          "size": 165513,
          "sha512": "e807d7d7c4fff1bd1a4e985c379d32fb55e24cdf95d75484bcef11807c74050084b7c910ddc00c889a75ebf9acf44831fe062047f7f3a0e4de68c69e1efcaed1",
          "sha256": "84ea975c5b0335ded8e3b86a88ec648d6f76c1d34066533bb15376683748581a",
          "sha1": "d90e1e60833cb4c5763e3a60e724d3890e87bf3a",
          "md5": "8ec9085dda2645247d74016aa53f2988"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.6-SNAPSHOT.jar",
          "url": "http-api-1.6.6-20200209.222511-2.jar",
          "size": 165513,
          "sha512": "e807d7d7c4fff1bd1a4e985c379d32fb55e24cdf95d75484bcef11807c74050084b7c910ddc00c889a75ebf9acf44831fe062047f7f3a0e4de68c69e1efcaed1",
          "sha256": "84ea975c5b0335ded8e3b86a88ec648d6f76c1d34066533bb15376683748581a",
          "sha1": "d90e1e60833cb4c5763e3a60e724d3890e87bf3a",
          "md5": "8ec9085dda2645247d74016aa53f2988"
        }
      ]
    }
  ]
}
