{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "ffjqypbsxneapilie7isekxg5q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.6-SNAPSHOT.jar",
          "url": "http-api-1.6.6-20200211.034535-2.jar",
          "size": 165512,
          "sha512": "3ca367603e506ac76ca94156d68ffadc069710027cec3b88a1e99a8b4683608f8c1394caca1591c8cdd212308f64505e4416b5e19a3313309b9851a7f975f4c8",
          "sha256": "836e103f7543b7849b5795b3e3aad3c8b86d79fc8ed4df118dd31ab06524a1fa",
          "sha1": "91e1e0216cb7aaf962b1aad103d839d5e46cd54c",
          "md5": "a40113940dfcc6fd89c838fc275bb302"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.6-SNAPSHOT.jar",
          "url": "http-api-1.6.6-20200211.034535-2.jar",
          "size": 165512,
          "sha512": "3ca367603e506ac76ca94156d68ffadc069710027cec3b88a1e99a8b4683608f8c1394caca1591c8cdd212308f64505e4416b5e19a3313309b9851a7f975f4c8",
          "sha256": "836e103f7543b7849b5795b3e3aad3c8b86d79fc8ed4df118dd31ab06524a1fa",
          "sha1": "91e1e0216cb7aaf962b1aad103d839d5e46cd54c",
          "md5": "a40113940dfcc6fd89c838fc275bb302"
        }
      ]
    }
  ]
}
