{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "2bwjmg2h6vawzgurtvjtf3oahm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.6-SNAPSHOT.jar",
          "url": "http-api-1.6.6-20200209.161917-1.jar",
          "size": 165512,
          "sha512": "c116c1542195b6e40982ee8f436550fd4550d5f23801a1c15061b226a61146b1b7be9fc9fa4c2f081ef446cbe27b48d82dbe074104a0daa6e9a3c5c3f381bef6",
          "sha256": "8f0f92a22de6314d23d841ea9616e364bdd0ee25e6432177e8f6517c948bbbc4",
          "sha1": "ab960f1de36f03f2e231ed2d1471b9ad9e289d00",
          "md5": "e967c313e575e6bc72a91acac3c0d88d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.6-SNAPSHOT.jar",
          "url": "http-api-1.6.6-20200209.161917-1.jar",
          "size": 165512,
          "sha512": "c116c1542195b6e40982ee8f436550fd4550d5f23801a1c15061b226a61146b1b7be9fc9fa4c2f081ef446cbe27b48d82dbe074104a0daa6e9a3c5c3f381bef6",
          "sha256": "8f0f92a22de6314d23d841ea9616e364bdd0ee25e6432177e8f6517c948bbbc4",
          "sha1": "ab960f1de36f03f2e231ed2d1471b9ad9e289d00",
          "md5": "e967c313e575e6bc72a91acac3c0d88d"
        }
      ]
    }
  ]
}
