{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "oz3lwfovprdh7luxs6u2rzfbu4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.6-SNAPSHOT.jar",
          "url": "http-api-1.6.6-20200206.153326-1.jar",
          "size": 165513,
          "sha512": "056cd5d2d2a3605fd8641705757ea920856c136c42821090136517a9ccb5926b0fd907f63181b6d7e60d5b80a7798f8068f21ce3f15aaf2595cf08461e6014a5",
          "sha256": "b22926fadd0f3c9596a2c509d499660067e93f2f2544736d7dd6afcf196ae2d4",
          "sha1": "38252a4c244e995f9bc6830bea48987c469facce",
          "md5": "6b83c37360314929de545ef21ca49038"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.6-SNAPSHOT.jar",
          "url": "http-api-1.6.6-20200206.153326-1.jar",
          "size": 165513,
          "sha512": "056cd5d2d2a3605fd8641705757ea920856c136c42821090136517a9ccb5926b0fd907f63181b6d7e60d5b80a7798f8068f21ce3f15aaf2595cf08461e6014a5",
          "sha256": "b22926fadd0f3c9596a2c509d499660067e93f2f2544736d7dd6afcf196ae2d4",
          "sha1": "38252a4c244e995f9bc6830bea48987c469facce",
          "md5": "6b83c37360314929de545ef21ca49038"
        }
      ]
    }
  ]
}
