{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "rdlz2kyko5e3nkzkleidj6ig7y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.6-SNAPSHOT.jar",
          "url": "http-api-1.6.6-20200130.005030-2.jar",
          "size": 165430,
          "sha512": "541559f0d8dcf3e106a352528a74086be377a679c741734283fec69d0ab09d64448ba3dc1269770b8c9ce7888202ff7906ed91835e059942e39808e466e7b641",
          "sha256": "30546bf2b0e1dcde837f79c905c12655d89e590cc25d247fad31d93ccc07c398",
          "sha1": "b7e5a371b128f9bb2787d03e7c9c63d4c6087865",
          "md5": "641b12502b6a842268f143ba4567ca1d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.6-SNAPSHOT.jar",
          "url": "http-api-1.6.6-20200130.005030-2.jar",
          "size": 165430,
          "sha512": "541559f0d8dcf3e106a352528a74086be377a679c741734283fec69d0ab09d64448ba3dc1269770b8c9ce7888202ff7906ed91835e059942e39808e466e7b641",
          "sha256": "30546bf2b0e1dcde837f79c905c12655d89e590cc25d247fad31d93ccc07c398",
          "sha1": "b7e5a371b128f9bb2787d03e7c9c63d4c6087865",
          "md5": "641b12502b6a842268f143ba4567ca1d"
        }
      ]
    }
  ]
}
