{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "7ery2omxijfmhd3z7dftf2faee"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.5.jar",
          "url": "runelite-api-3.3.5.jar",
          "size": 1183687,
          "sha512": "0a31a021ea707e69cf94020244d9033358b4388a8ffcd3c045b7d4aae27f1198650beef422afbd8f59b2f8c15396531f6c226a8260a5b3fbbb6b48f50746c2e1",
          "sha256": "3e1688a3a47f72920405c6f890ab1b1d4906c08e8ee278dfc6567806b11896f1",
          "sha1": "6eda4f4aecf02b1b1b2938691933845e92e75e3b",
          "md5": "f61c54a5f5d2223bd43254deed3953ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.5.jar",
          "url": "runelite-api-3.3.5.jar",
          "size": 1183687,
          "sha512": "0a31a021ea707e69cf94020244d9033358b4388a8ffcd3c045b7d4aae27f1198650beef422afbd8f59b2f8c15396531f6c226a8260a5b3fbbb6b48f50746c2e1",
          "sha256": "3e1688a3a47f72920405c6f890ab1b1d4906c08e8ee278dfc6567806b11896f1",
          "sha1": "6eda4f4aecf02b1b1b2938691933845e92e75e3b",
          "md5": "f61c54a5f5d2223bd43254deed3953ff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.5-sources.jar",
          "url": "runelite-api-3.3.5-sources.jar",
          "size": 868536,
          "sha512": "eaff6f994abbb55feeaa063cd96624a2ba1291456ec60c5a80cec76c554269f85d20a615a77f1f3a73eede98810d5a770858f5cee66910c1839ca868426a42de",
          "sha256": "2ee8257908722020ddf0066298fd7007f729fc6ab60fdea5f7fc0b3af21a2b31",
          "sha1": "935092a0305234e3be60a5c25593909562bb6788",
          "md5": "c47fbdc23604c3d99e7ba14491934e9d"
        }
      ]
    }
  ]
}
