{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "o6zngoutazcp5ij7sb6whi2v3e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.5.jar",
          "url": "runelite-api-3.3.5.jar",
          "size": 1184209,
          "sha512": "a086c1e69051eec014a82331cb4918a58c6866ddbd561bc87432d351a47e94a3669db71363d9f3c1f6357aaa8fa7d63fc21fcbdf26b9e3666429e0bd00ff6abc",
          "sha256": "24af8d2880da41a548313951d3a5e8ef585a000e2ce812e4c63d4aa0b360d9e7",
          "sha1": "7ca23970bb4cbcc90814c4236e901ae78959ea30",
          "md5": "0a286cad0b0d1a296473ea480d852250"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.5.jar",
          "url": "runelite-api-3.3.5.jar",
          "size": 1184209,
          "sha512": "a086c1e69051eec014a82331cb4918a58c6866ddbd561bc87432d351a47e94a3669db71363d9f3c1f6357aaa8fa7d63fc21fcbdf26b9e3666429e0bd00ff6abc",
          "sha256": "24af8d2880da41a548313951d3a5e8ef585a000e2ce812e4c63d4aa0b360d9e7",
          "sha1": "7ca23970bb4cbcc90814c4236e901ae78959ea30",
          "md5": "0a286cad0b0d1a296473ea480d852250"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.5-sources.jar",
          "url": "runelite-api-3.3.5-sources.jar",
          "size": 869009,
          "sha512": "2f06f1e81f18e0b33242054d179c1946bf93576a847fa7361f605d8b555ba56146f96d5c6a665e2a661c2d7777910702c92502805932eb1f013e740a1620f09d",
          "sha256": "7fbe78ea240053e49be096bffb0d258db2277e168a55bc7d59f6755fdd414293",
          "sha1": "78b97ea98098a0e5d079ac922f70e8e6224b6d79",
          "md5": "12c93a38d850b056581bdda3c621be04"
        }
      ]
    }
  ]
}
