{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "fj5ipvm2g5hljagfnguvn7yqly"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.5.jar",
          "url": "runelite-api-3.3.5.jar",
          "size": 1184063,
          "sha512": "34754ff3f72dd976ab33241aa9c34a183482679a5bcc1838e2d92060245dd43818f98b0c821ae386785c5617d57bebb4d5d2edbea6c7bf782cb635be206a5bad",
          "sha256": "260b7732051c2894fa12694b4cc127e2e5f839fc498c805c2435aea0989c893a",
          "sha1": "47a40a6a29a00bf5be49cfbf2f1a78060e3be7e2",
          "md5": "5ce62097c6d2f7c1823a9a6355fbd020"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.5.jar",
          "url": "runelite-api-3.3.5.jar",
          "size": 1184063,
          "sha512": "34754ff3f72dd976ab33241aa9c34a183482679a5bcc1838e2d92060245dd43818f98b0c821ae386785c5617d57bebb4d5d2edbea6c7bf782cb635be206a5bad",
          "sha256": "260b7732051c2894fa12694b4cc127e2e5f839fc498c805c2435aea0989c893a",
          "sha1": "47a40a6a29a00bf5be49cfbf2f1a78060e3be7e2",
          "md5": "5ce62097c6d2f7c1823a9a6355fbd020"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.5-sources.jar",
          "url": "runelite-api-3.3.5-sources.jar",
          "size": 868748,
          "sha512": "9fb0a9eb2c1d71811a1680cf0bcf4f98282f05f4d4654113ebb3e03bd172f965a754ca36d3bbf34bca0b31fe22e9c2a5d7b9bb17d82b3e1a255bdc5dbf9c2886",
          "sha256": "e262167e7e05950d90668ec22d711379e266750f364cb635b97d7cc3d557d220",
          "sha1": "19e26fbc9cae836075eaaf33a00f71167a9266e9",
          "md5": "176001cb0dc09a72f7c05f357de44153"
        }
      ]
    }
  ]
}
