{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "k5lwdxgx2ne6xofpjqaxgaqsmm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.2.2.jar",
          "url": "runescape-api-3.2.2.jar",
          "size": 103418,
          "sha512": "ff0bbcfdbaa6b9c4b885956a52a34b699b20a3e404b2a37dbd51c51f01e3b2c299374dee88eef657948a7aead092889399f65ce148753b392594adae47501719",
          "sha256": "051a436d840ce2482990ab477cfeca26c3e4a70ab27037d8b12b62728c0dc1ba",
          "sha1": "036d9c679c4bd1310179370cf263f150316ba9eb",
          "md5": "e6c00451e4fbfbec61c5c2bf748150d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.2.2.jar",
          "url": "runescape-api-3.2.2.jar",
          "size": 103418,
          "sha512": "ff0bbcfdbaa6b9c4b885956a52a34b699b20a3e404b2a37dbd51c51f01e3b2c299374dee88eef657948a7aead092889399f65ce148753b392594adae47501719",
          "sha256": "051a436d840ce2482990ab477cfeca26c3e4a70ab27037d8b12b62728c0dc1ba",
          "sha1": "036d9c679c4bd1310179370cf263f150316ba9eb",
          "md5": "e6c00451e4fbfbec61c5c2bf748150d8"
        }
      ]
    }
  ]
}
