{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "da4xdde4szdydcjqpr3r7otnky"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.2.2.jar",
          "url": "http-api-3.2.2.jar",
          "size": 164003,
          "sha512": "38ceaa0676a2a8de8d93226b8f53c37b14a1a67a607926f7dc519fef5f18fb4d945a8f14cc68d018fc7f1f956e36c78b641fa1dd743698d46f11e8fc041331e3",
          "sha256": "3923d411ca5dda6db434d145be2058c91dd64bb06c46d75899806dfe2a23d2a8",
          "sha1": "11b1f4a8f2297d0d2a0f5a7cef0f4d916095eabb",
          "md5": "8fc64d31611e7ee1e1336420ced76739"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.2.2.jar",
          "url": "http-api-3.2.2.jar",
          "size": 164003,
          "sha512": "38ceaa0676a2a8de8d93226b8f53c37b14a1a67a607926f7dc519fef5f18fb4d945a8f14cc68d018fc7f1f956e36c78b641fa1dd743698d46f11e8fc041331e3",
          "sha256": "3923d411ca5dda6db434d145be2058c91dd64bb06c46d75899806dfe2a23d2a8",
          "sha1": "11b1f4a8f2297d0d2a0f5a7cef0f4d916095eabb",
          "md5": "8fc64d31611e7ee1e1336420ced76739"
        }
      ]
    }
  ]
}
