{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "eozc5css2rdz5fb6c4fkiwagdq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.2.2.jar",
          "url": "http-api-3.2.2.jar",
          "size": 164003,
          "sha512": "e05c7a25cfae8e54a46db6b50406645ee34c4207e4374976026ddbdb96f05e5c84794bf8f3bcacd060ae058edeb5f4545aeaed36982b7fdaecdea3a132282450",
          "sha256": "470f5f8a9d43b6f498159d7781c56e07737354adb412620da232aca1245b1dfe",
          "sha1": "a1d85e923ad80e4ac235e7ccb60d48ecc455116b",
          "md5": "0e0aded8137fce4be0b2aeffc793bb7f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.2.2.jar",
          "url": "http-api-3.2.2.jar",
          "size": 164003,
          "sha512": "e05c7a25cfae8e54a46db6b50406645ee34c4207e4374976026ddbdb96f05e5c84794bf8f3bcacd060ae058edeb5f4545aeaed36982b7fdaecdea3a132282450",
          "sha256": "470f5f8a9d43b6f498159d7781c56e07737354adb412620da232aca1245b1dfe",
          "sha1": "a1d85e923ad80e4ac235e7ccb60d48ecc455116b",
          "md5": "0e0aded8137fce4be0b2aeffc793bb7f"
        }
      ]
    }
  ]
}
