{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "zwbdy6ivf5ampkvubyr2ohfu4y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.2.2.jar",
          "url": "http-api-3.2.2.jar",
          "size": 164004,
          "sha512": "9046f5ee8f1d28e4ee41e57b180b967ddbcf2b89841fa2301233fd6017feabca4853c50bb8b9d0ad704d47fb71bffa0f85d468f8fefee69c04aa1dd62eba52b0",
          "sha256": "b72ab54a3803f49bd97c6f2cf65f63faea20251353b2238ff29cfcf90f48e610",
          "sha1": "9723b4622eaa06671253b7accff5072e607a054f",
          "md5": "d7091ac699ca838af0c016c26755eb89"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.2.2.jar",
          "url": "http-api-3.2.2.jar",
          "size": 164004,
          "sha512": "9046f5ee8f1d28e4ee41e57b180b967ddbcf2b89841fa2301233fd6017feabca4853c50bb8b9d0ad704d47fb71bffa0f85d468f8fefee69c04aa1dd62eba52b0",
          "sha256": "b72ab54a3803f49bd97c6f2cf65f63faea20251353b2238ff29cfcf90f48e610",
          "sha1": "9723b4622eaa06671253b7accff5072e607a054f",
          "md5": "d7091ac699ca838af0c016c26755eb89"
        }
      ]
    }
  ]
}
