{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-client",
    "version": "3.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "i6hnybq5v5av3ljxmgzjnpzo2q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-client-3.3.1.jar",
          "url": "runelite-client-3.3.1.jar",
          "size": 2634811,
          "sha512": "8767102d614662c312d704086d65cb5389198e4742fd362f2205ded01f7ddab53878c01159ff9524ed4c1172989a918a90b0e810beff757e24dec777451638f4",
          "sha256": "101ad6aa4bb30677ef5cdacd3d8a40f7e1fc8a8bbceac6f276210d87c10908c2",
          "sha1": "54bde2bdf020703135a637f44181e197dedb7f8f",
          "md5": "fd619c3d415c662c59242b708240c4f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "4.2.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "guice",
              "type": "jar",
              "extension": "jar",
              "classifier": "no_aop"
            }
          }
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "1.4.200"
          }
        },
        {
          "group": "com.openosrs.rxrelay3",
          "module": "rxrelay",
          "version": {
            "requires": "3.0.1-SNAPSHOT"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "org.jgroups",
          "module": "jgroups",
          "version": {
            "requires": "4.2.3.Final"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "net.runelite",
          "module": "discord",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "org.pushing-pixels",
          "module": "radiance-substance",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "19.0.0"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq",
          "version": {
            "requires": "3.13.2"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq-codegen",
          "version": {
            "requires": "3.13.2"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq-meta",
          "version": {
            "requires": "3.13.2"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-logback",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.github.zafarkhaja",
          "module": "java-semver",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.pf4j",
          "module": "pf4j",
          "version": {
            "requires": "3.3.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.pf4j",
          "module": "pf4j-update",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "http-api",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.pushing-pixels",
          "module": "radiance-trident",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injected-client",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.openosrs.rs",
          "module": "runescape-api",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-client-3.3.1.jar",
          "url": "runelite-client-3.3.1.jar",
          "size": 2634811,
          "sha512": "8767102d614662c312d704086d65cb5389198e4742fd362f2205ded01f7ddab53878c01159ff9524ed4c1172989a918a90b0e810beff757e24dec777451638f4",
          "sha256": "101ad6aa4bb30677ef5cdacd3d8a40f7e1fc8a8bbceac6f276210d87c10908c2",
          "sha1": "54bde2bdf020703135a637f44181e197dedb7f8f",
          "md5": "fd619c3d415c662c59242b708240c4f5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-client-3.3.1-sources.jar",
          "url": "runelite-client-3.3.1-sources.jar",
          "size": 2325912,
          "sha512": "8cf3ba12ff7a479b42696d3e9276e381f2740bb42e95b5923bf72a7abd85774053e084ad15f1ea4a94b0f999363775df71f297a21c3c5734f23c1ab7b3957850",
          "sha256": "d9c977c9519e88a7003c5b9b0913642d63c4eebc505f3cce1a8d5710138af686",
          "sha1": "2c39a174b06116ee2bd274b61047a6afcdeb01ce",
          "md5": "24f9b8a84b4c2948ab73a3335642e5d9"
        }
      ]
    }
  ]
}
