{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "kuvdw6ukbvbxjngugizkemcx4a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.4.3.jar",
          "url": "http-api-3.4.3.jar",
          "size": 159709,
          "sha512": "d7d4d7ffe4fb331dd36c0949cf32ef8e78725cb267ff1dc45b78a25af91f39f2879d7fc019e4068bc5f6728352b999926197294a657163855da8f4e9ec98b8b0",
          "sha256": "784ed837effefec4dbc57d3eb230634bca891f692f6d9f67925e82ac2728bd44",
          "sha1": "ef3fe1b33fc84dd4ecdfc2399fdde738abec8c50",
          "md5": "81707349bf2d19c1505ad3d028d5fd9a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.4.3.jar",
          "url": "http-api-3.4.3.jar",
          "size": 159709,
          "sha512": "d7d4d7ffe4fb331dd36c0949cf32ef8e78725cb267ff1dc45b78a25af91f39f2879d7fc019e4068bc5f6728352b999926197294a657163855da8f4e9ec98b8b0",
          "sha256": "784ed837effefec4dbc57d3eb230634bca891f692f6d9f67925e82ac2728bd44",
          "sha1": "ef3fe1b33fc84dd4ecdfc2399fdde738abec8c50",
          "md5": "81707349bf2d19c1505ad3d028d5fd9a"
        }
      ]
    }
  ]
}
