{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "wvcsc4ycvfb6tglj4tbstv6r7y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.4.3.jar",
          "url": "http-api-3.4.3.jar",
          "size": 158219,
          "sha512": "89e790066b16687153cde71fcb8dc16a28fa121799320d6555ff8a314e7a753690a29ff89d3933ea7dc181780c89e2ac62fa654f989ea3a7a48b9b0276f3495e",
          "sha256": "796a5c5f21e3b0c3efbb9df7880af7808d21c52699a672c712221ec69564e32b",
          "sha1": "57fd1823c7ce48f7ee224c65ea52d05694fee852",
          "md5": "3780eeea25541c0771e2db4cc0e258e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.4.3.jar",
          "url": "http-api-3.4.3.jar",
          "size": 158219,
          "sha512": "89e790066b16687153cde71fcb8dc16a28fa121799320d6555ff8a314e7a753690a29ff89d3933ea7dc181780c89e2ac62fa654f989ea3a7a48b9b0276f3495e",
          "sha256": "796a5c5f21e3b0c3efbb9df7880af7808d21c52699a672c712221ec69564e32b",
          "sha1": "57fd1823c7ce48f7ee224c65ea52d05694fee852",
          "md5": "3780eeea25541c0771e2db4cc0e258e1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.4.3-sources.jar",
          "url": "http-api-3.4.3-sources.jar",
          "size": 103767,
          "sha512": "92a3c1b8411af29ca60f413f890a089018d8e79ec1d192e738b0b5584bca9c4728c547dbbb0435d33a52ce020d8a8e222af1d9f0b36b414e2f4c5087aa96ba19",
          "sha256": "a527fb414e2ec8f6a4f2f8d4609cb620c25e0ce0d36a8780769d92d5e28a10c2",
          "sha1": "66f2088304149c0d8ed69d4a60ff04fc69fcb532",
          "md5": "d54cd3f5ee5ba8780ff00384b6718aa0"
        }
      ]
    }
  ]
}
