{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "5suaout5bjctnlghojbrq4b5ai"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.2.1.jar",
          "url": "runescape-api-3.2.1.jar",
          "size": 55416,
          "sha512": "a543aef36798d92c1e009b505eaa2181812fc91e597dcd25dc574cedca373ed901192538649b04a81be873eec9162235d7719217ef579d51ed783f3dff9abc68",
          "sha256": "ad37798033e51247bfd849ef8b0a61caae939c76e616833fafa2972978372114",
          "sha1": "a581d7848bd0266aa8cc15e0d8fa4dae5843403e",
          "md5": "8eb3ee7e201c0610ec05c626329b5a2f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.2.1.jar",
          "url": "runescape-api-3.2.1.jar",
          "size": 55416,
          "sha512": "a543aef36798d92c1e009b505eaa2181812fc91e597dcd25dc574cedca373ed901192538649b04a81be873eec9162235d7719217ef579d51ed783f3dff9abc68",
          "sha256": "ad37798033e51247bfd849ef8b0a61caae939c76e616833fafa2972978372114",
          "sha1": "a581d7848bd0266aa8cc15e0d8fa4dae5843403e",
          "md5": "8eb3ee7e201c0610ec05c626329b5a2f"
        }
      ]
    }
  ]
}
