{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "k2zvkynkujgtjivzlpsd6on34u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.2.1.jar",
          "url": "runescape-api-3.2.1.jar",
          "size": 55416,
          "sha512": "6840ddcbc29f8ef0ef0bf36f7c06eee6fe05e80c7b0f9e9a5a476d4b1ce52108c52f2c271b9f9d1e87a07e23497e806e6918493e7416977a49654cb59dfce61e",
          "sha256": "542c9b937a8958c8c2b414ae0aeb0ff3b1d484b2ac7a348a58088c9008e6578a",
          "sha1": "cbae47cb602fc90d39d85fa6f3c17712b921d954",
          "md5": "7460128bb168adbb8ae1ad52f02ca1ee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.2.1.jar",
          "url": "runescape-api-3.2.1.jar",
          "size": 55416,
          "sha512": "6840ddcbc29f8ef0ef0bf36f7c06eee6fe05e80c7b0f9e9a5a476d4b1ce52108c52f2c271b9f9d1e87a07e23497e806e6918493e7416977a49654cb59dfce61e",
          "sha256": "542c9b937a8958c8c2b414ae0aeb0ff3b1d484b2ac7a348a58088c9008e6578a",
          "sha1": "cbae47cb602fc90d39d85fa6f3c17712b921d954",
          "md5": "7460128bb168adbb8ae1ad52f02ca1ee"
        }
      ]
    }
  ]
}
