{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "6ud2yyqsfrgwvhmxgpopo7wgmy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.2.1.jar",
          "url": "runescape-api-3.2.1.jar",
          "size": 103399,
          "sha512": "06ad7bb310f4364f4de888ff52887750814082874327dab298d4c5337cc86a23244b58d7da160dcf18b26cc24c3ee6f1d72f63f9b047a35c0d5cd31ad9ad0be1",
          "sha256": "ef11402eefba08cb43c0a3f908e5794eb848dee9f635e246f36d05d7492ead10",
          "sha1": "ee758f33440de925eeeb27e782a8863cec012c34",
          "md5": "3085ae0aacbba4c2f48c5cfb0f3a6dae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.2.1.jar",
          "url": "runescape-api-3.2.1.jar",
          "size": 103399,
          "sha512": "06ad7bb310f4364f4de888ff52887750814082874327dab298d4c5337cc86a23244b58d7da160dcf18b26cc24c3ee6f1d72f63f9b047a35c0d5cd31ad9ad0be1",
          "sha256": "ef11402eefba08cb43c0a3f908e5794eb848dee9f635e246f36d05d7492ead10",
          "sha1": "ee758f33440de925eeeb27e782a8863cec012c34",
          "md5": "3085ae0aacbba4c2f48c5cfb0f3a6dae"
        }
      ]
    }
  ]
}
