{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "dfcn57zhnfalhjjql6gnginsje"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.0.jar",
          "url": "http-api-3.3.0.jar",
          "size": 164003,
          "sha512": "ce06b46991432d36bcb7ccda9db3b25d22953bd3fef585a3ed47011901fb7cdfaa21d7346d530577f849012b10ddd3fa35d174e3afd01ec140315115a7b53e46",
          "sha256": "ac0efc3ef43056c86f8416916f658ebf6cf056a7da34e493bafc447d76ff309a",
          "sha1": "f49514474107201711fa1c4842be018bd3acb131",
          "md5": "7b0987761a7ffdc89d8b90d56dba2631"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.0.jar",
          "url": "http-api-3.3.0.jar",
          "size": 164003,
          "sha512": "ce06b46991432d36bcb7ccda9db3b25d22953bd3fef585a3ed47011901fb7cdfaa21d7346d530577f849012b10ddd3fa35d174e3afd01ec140315115a7b53e46",
          "sha256": "ac0efc3ef43056c86f8416916f658ebf6cf056a7da34e493bafc447d76ff309a",
          "sha1": "f49514474107201711fa1c4842be018bd3acb131",
          "md5": "7b0987761a7ffdc89d8b90d56dba2631"
        }
      ]
    }
  ]
}
