{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "qgjqkhrpkvchjjh2hyut7go6dy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.0.jar",
          "url": "http-api-3.3.0.jar",
          "size": 164002,
          "sha512": "079e29fba882c373b94ea4700077b888b7c2df9088774dedc8e4cb99ccfdb49db90870a1486074287d3cfdc9a1b35398a57bae8b69a0266e70e7b4557c2a9f20",
          "sha256": "fd0b8b15457d3753ecabef3d12a7d99a35fb132b12b1fa6225f2a798f6d70177",
          "sha1": "b4873bfbf1c63305ad147a75c28eb25c687fb606",
          "md5": "4164331b35326b4fdebe5659b9b73c0a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.0.jar",
          "url": "http-api-3.3.0.jar",
          "size": 164002,
          "sha512": "079e29fba882c373b94ea4700077b888b7c2df9088774dedc8e4cb99ccfdb49db90870a1486074287d3cfdc9a1b35398a57bae8b69a0266e70e7b4557c2a9f20",
          "sha256": "fd0b8b15457d3753ecabef3d12a7d99a35fb132b12b1fa6225f2a798f6d70177",
          "sha1": "b4873bfbf1c63305ad147a75c28eb25c687fb606",
          "md5": "4164331b35326b4fdebe5659b9b73c0a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.0-sources.jar",
          "url": "http-api-3.3.0-sources.jar",
          "size": 107148,
          "sha512": "6b385e7466e98dec5eb7ded25b5d07573eb4e797e390af152c75f7097eb3f5655fba0364aafe86a02399d8bab1f9191701e96fb2827c16754b3c0f6a3a56194b",
          "sha256": "cd1cf9357ce5fab80619d209d1cd7010a106047b1189e79c6e52d3cc452dceb5",
          "sha1": "e697d709d2eee9dd2ac438220c6b7591b2ee44ac",
          "md5": "8f46f4fe39de6a680c907a45f3eff95a"
        }
      ]
    }
  ]
}
