{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "2yty7ku6y5hslg3tf45hxegi6m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.3-SNAPSHOT.jar",
          "url": "runelite-api-1.6.3-20200121.000800-1.jar",
          "size": 1148985,
          "sha512": "f9b0a51c046cc926f3924086e9e478b1d578261a3a47ef07ebbe3d1179660258bdc782d7029d0291222165709066db98e44c79bd0261b4e35a7d9787c731da1a",
          "sha256": "d638867fe7e49013fe3769b44ea577d587d20a17b0fffaf5e55c84c03da2707c",
          "sha1": "e28a61e696f585cafd65ae7e445c62733123d3e3",
          "md5": "a4981dcd851347ba13caab9739dfd815"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.3-SNAPSHOT.jar",
          "url": "runelite-api-1.6.3-20200121.000800-1.jar",
          "size": 1148985,
          "sha512": "f9b0a51c046cc926f3924086e9e478b1d578261a3a47ef07ebbe3d1179660258bdc782d7029d0291222165709066db98e44c79bd0261b4e35a7d9787c731da1a",
          "sha256": "d638867fe7e49013fe3769b44ea577d587d20a17b0fffaf5e55c84c03da2707c",
          "sha1": "e28a61e696f585cafd65ae7e445c62733123d3e3",
          "md5": "a4981dcd851347ba13caab9739dfd815"
        }
      ]
    }
  ]
}
