{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "lga66gpwabbedon5gdqb3bsigi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.3-SNAPSHOT.jar",
          "url": "runelite-api-1.6.3-20200123.001038-1.jar",
          "size": 1149042,
          "sha512": "de5e19f2037e21194299d9621da5337b84a93ebe9067d4a630a051387ac549e765bfec9fb1ef3b82303d1d4f53c0d90737b61dd6bb384a98336adb913f489fc4",
          "sha256": "a6e5b31d3b5aa3b1b2d5a9e3fd127630c8688a042fe48624861089ff37f1d86c",
          "sha1": "d2fe9d555a2143ce3dc3d914d27868f354e0761b",
          "md5": "66563121b7b26f1a5adde3d61b8d4be1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.3-SNAPSHOT.jar",
          "url": "runelite-api-1.6.3-20200123.001038-1.jar",
          "size": 1149042,
          "sha512": "de5e19f2037e21194299d9621da5337b84a93ebe9067d4a630a051387ac549e765bfec9fb1ef3b82303d1d4f53c0d90737b61dd6bb384a98336adb913f489fc4",
          "sha256": "a6e5b31d3b5aa3b1b2d5a9e3fd127630c8688a042fe48624861089ff37f1d86c",
          "sha1": "d2fe9d555a2143ce3dc3d914d27868f354e0761b",
          "md5": "66563121b7b26f1a5adde3d61b8d4be1"
        }
      ]
    }
  ]
}
