{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "76vxovm35vho3fh3kjzwhlf6g4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.3-SNAPSHOT.jar",
          "url": "runelite-api-1.6.3-20200120.000839-1.jar",
          "size": 1148985,
          "sha512": "7e53f85386b6a773492bc6d752d807a1a39d113b1b8db37ed2f5d12af7de095174d44ffaf0314a3d5bc63ab4d2613d04cebfa87ffddf1ed19af16be304703f3c",
          "sha256": "1e2f60d2897c79fe4764a4e8a44b86ee4c790275ada790a28214861c456fb492",
          "sha1": "c272c8a9d3452413222f298bbdd4a39fb53e56f2",
          "md5": "f3276aea8bc798aac53a71d0add87fb2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.3-SNAPSHOT.jar",
          "url": "runelite-api-1.6.3-20200120.000839-1.jar",
          "size": 1148985,
          "sha512": "7e53f85386b6a773492bc6d752d807a1a39d113b1b8db37ed2f5d12af7de095174d44ffaf0314a3d5bc63ab4d2613d04cebfa87ffddf1ed19af16be304703f3c",
          "sha256": "1e2f60d2897c79fe4764a4e8a44b86ee4c790275ada790a28214861c456fb492",
          "sha1": "c272c8a9d3452413222f298bbdd4a39fb53e56f2",
          "md5": "f3276aea8bc798aac53a71d0add87fb2"
        }
      ]
    }
  ]
}
