{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "kwndnbmqzvg7roez2rv3mhfbna"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.3-SNAPSHOT.jar",
          "url": "runelite-api-1.6.3-20200118.222052-1.jar",
          "size": 1148985,
          "sha512": "3049b63db425f542798632bfd2134247e6a2f37273d86e14faf4b2d12dd03e3ea8cc85b062c01ef8e5ef019e8909204a2ef54480ed0b6788607aba9d9242a23a",
          "sha256": "f73b9bba08bd01801f55c7634640d7a7f52f6f76bae0d62f9be1302b0f366939",
          "sha1": "2d7447c969d38ad00af2a6ff3402d6629b6c1c11",
          "md5": "8d0c2df5a1af05d7a3afb15cac2321a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.3-SNAPSHOT.jar",
          "url": "runelite-api-1.6.3-20200118.222052-1.jar",
          "size": 1148985,
          "sha512": "3049b63db425f542798632bfd2134247e6a2f37273d86e14faf4b2d12dd03e3ea8cc85b062c01ef8e5ef019e8909204a2ef54480ed0b6788607aba9d9242a23a",
          "sha256": "f73b9bba08bd01801f55c7634640d7a7f52f6f76bae0d62f9be1302b0f366939",
          "sha1": "2d7447c969d38ad00af2a6ff3402d6629b6c1c11",
          "md5": "8d0c2df5a1af05d7a3afb15cac2321a7"
        }
      ]
    }
  ]
}
