{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "mpju6w4wqbglxk2kh4vkfved24"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.3-SNAPSHOT.jar",
          "url": "runelite-api-1.6.3-20200119.093458-1.jar",
          "size": 1148985,
          "sha512": "a2876065a3e2ebf8ae7a19766ee447058c141494e9b2a8caf9ad72d7d64fe0e70dc0de07bf85fc3da6631cce7d7b487981ab4466a4e8f5a4a1a83c4f74f2e0f5",
          "sha256": "44773da37f0a93248107962a157ed71aaf15764940d1eba2788328197eb8445f",
          "sha1": "9346294e99f5849f145e9414d78ed079d23fe23d",
          "md5": "ac505ccdde91fe5ac7c34654338f3459"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.3-SNAPSHOT.jar",
          "url": "runelite-api-1.6.3-20200119.093458-1.jar",
          "size": 1148985,
          "sha512": "a2876065a3e2ebf8ae7a19766ee447058c141494e9b2a8caf9ad72d7d64fe0e70dc0de07bf85fc3da6631cce7d7b487981ab4466a4e8f5a4a1a83c4f74f2e0f5",
          "sha256": "44773da37f0a93248107962a157ed71aaf15764940d1eba2788328197eb8445f",
          "sha1": "9346294e99f5849f145e9414d78ed079d23fe23d",
          "md5": "ac505ccdde91fe5ac7c34654338f3459"
        }
      ]
    }
  ]
}
