{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "hwgfzvbmurfdbnzhvtll5bi37i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.3-SNAPSHOT.jar",
          "url": "runelite-api-1.6.3-20200118.223013-1.jar",
          "size": 1148985,
          "sha512": "dcf8397c7f6960c3456de6ecec401216b1e988399feab247c853ee448406f7a4bbb3ce9aba308b892d4bd5eb89fad7fa88df2978f3f9d9271dd00465eef4b10d",
          "sha256": "3f7aaa9498a3ba5d884d18df520d4c57c37ab4048ae17277479f6e7a54a4b830",
          "sha1": "51b456a9ed9328830d1ba0883755eadcaee02d59",
          "md5": "6a224070bb94d9383a1deb79f2ae4fea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.3-SNAPSHOT.jar",
          "url": "runelite-api-1.6.3-20200118.223013-1.jar",
          "size": 1148985,
          "sha512": "dcf8397c7f6960c3456de6ecec401216b1e988399feab247c853ee448406f7a4bbb3ce9aba308b892d4bd5eb89fad7fa88df2978f3f9d9271dd00465eef4b10d",
          "sha256": "3f7aaa9498a3ba5d884d18df520d4c57c37ab4048ae17277479f6e7a54a4b830",
          "sha1": "51b456a9ed9328830d1ba0883755eadcaee02d59",
          "md5": "6a224070bb94d9383a1deb79f2ae4fea"
        }
      ]
    }
  ]
}
