{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "t5j3pwdnrbdafejetpgfjj6hpi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.3-SNAPSHOT.jar",
          "url": "runelite-api-1.6.3-20200122.000949-1.jar",
          "size": 1149042,
          "sha512": "9d6f8b07f7cfbd58d1bcb4bd737f0f5e5156c43735b407321b012bdb91a84872ca4e58e682bf46676b727375e4bb221f82e404d7be98f74989f16820cf3a117c",
          "sha256": "a12ecbff918edc3137535729b5af7d45fd57baa0cc4501e824c442ad642fe3d0",
          "sha1": "a38df6b73b23d7c67d9e5f9e6deee56f22c5dc3f",
          "md5": "01770db9a1413c084f270b914027f418"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.3-SNAPSHOT.jar",
          "url": "runelite-api-1.6.3-20200122.000949-1.jar",
          "size": 1149042,
          "sha512": "9d6f8b07f7cfbd58d1bcb4bd737f0f5e5156c43735b407321b012bdb91a84872ca4e58e682bf46676b727375e4bb221f82e404d7be98f74989f16820cf3a117c",
          "sha256": "a12ecbff918edc3137535729b5af7d45fd57baa0cc4501e824c442ad642fe3d0",
          "sha1": "a38df6b73b23d7c67d9e5f9e6deee56f22c5dc3f",
          "md5": "01770db9a1413c084f270b914027f418"
        }
      ]
    }
  ]
}
