{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "w6bxz5lg6ne2jcow2buh2cbpta"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.7.jar",
          "url": "injected-client-1.6.7.jar",
          "size": 2266350,
          "sha512": "900b94ddff13b8be398ba5304a6dda576566f440e70c7d42af89b57581b38971fe9d90b2b92bcd0577a267f33669b4344a0f447ffec52d4afce2961109a62118",
          "sha256": "5319ed6679ceaa193cc5948d33213d8fb5f3e07e33d65db71a55affbad8c53ed",
          "sha1": "fb5acadaaefc459664e2e97fe0d4dfa8c951a4ec",
          "md5": "16a0647c3865e28266295fff2955c14f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.7.jar",
          "url": "injected-client-1.6.7.jar",
          "size": 2266350,
          "sha512": "900b94ddff13b8be398ba5304a6dda576566f440e70c7d42af89b57581b38971fe9d90b2b92bcd0577a267f33669b4344a0f447ffec52d4afce2961109a62118",
          "sha256": "5319ed6679ceaa193cc5948d33213d8fb5f3e07e33d65db71a55affbad8c53ed",
          "sha1": "fb5acadaaefc459664e2e97fe0d4dfa8c951a4ec",
          "md5": "16a0647c3865e28266295fff2955c14f"
        }
      ]
    }
  ]
}
