{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "dvgrgv5jv5fpvhst277gs744wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.7.jar",
          "url": "injected-client-1.6.7.jar",
          "size": 2266350,
          "sha512": "4b11cf6c560e69c337d49f784c9920ecd01718bbf5d75cb602785538e7aa8cedb634080cfc77a74701e19bb5ab036e4a25fb64919a97be3a59ab26af4c794210",
          "sha256": "4dee7a6b9633d615e7e0fcab9a6557f4a867a59eccdf9b74e2a1503f50d4b605",
          "sha1": "ecf1670e3ca52809db9454b9ceeb6ca71cb22781",
          "md5": "f5eefc82ed2296655f8802c181edea2c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.7.jar",
          "url": "injected-client-1.6.7.jar",
          "size": 2266350,
          "sha512": "4b11cf6c560e69c337d49f784c9920ecd01718bbf5d75cb602785538e7aa8cedb634080cfc77a74701e19bb5ab036e4a25fb64919a97be3a59ab26af4c794210",
          "sha256": "4dee7a6b9633d615e7e0fcab9a6557f4a867a59eccdf9b74e2a1503f50d4b605",
          "sha1": "ecf1670e3ca52809db9454b9ceeb6ca71cb22781",
          "md5": "f5eefc82ed2296655f8802c181edea2c"
        }
      ]
    }
  ]
}
