{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "f6hkzu546fcazeq5qs7zy5fjv4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.7.jar",
          "url": "injected-client-1.6.7.jar",
          "size": 2265954,
          "sha512": "06eeffe8abf39c829d45b23575aa7b8ebcd41436b43c969bbd0305a01356b28ce3cda697041b39e3886ca6be0d8582365b7bd7ad56ff8deeaa1b334f62317643",
          "sha256": "b8899eee2faea9e522e80a16497578c88735f32f845d79cf95e1564e6f6ddc8e",
          "sha1": "a6e27e77b8174291b6a492eff4db7a15a6cad180",
          "md5": "37c74652f148ec436c00ffeb53324808"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.7.jar",
          "url": "injected-client-1.6.7.jar",
          "size": 2265954,
          "sha512": "06eeffe8abf39c829d45b23575aa7b8ebcd41436b43c969bbd0305a01356b28ce3cda697041b39e3886ca6be0d8582365b7bd7ad56ff8deeaa1b334f62317643",
          "sha256": "b8899eee2faea9e522e80a16497578c88735f32f845d79cf95e1564e6f6ddc8e",
          "sha1": "a6e27e77b8174291b6a492eff4db7a15a6cad180",
          "md5": "37c74652f148ec436c00ffeb53324808"
        }
      ]
    }
  ]
}
