{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "7a6kzebvnjhcxbagy7cskuh2gy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.2.1.jar",
          "url": "runescape-api-3.2.1.jar",
          "size": 55416,
          "sha512": "89e8345173603ec0253aa3721802237ef6c76b314c91c7ddd413d82e008637bef71a8409f5dd2ea84bde581b7c70d9f6e37742f48540bfada79e1dce866fa443",
          "sha256": "77e166ae5a8e51aff892c5c58c4c45f7109c2ab8bbfb946d8e9be559b74bf785",
          "sha1": "01c277218e1b3612451fc1752b067b8721a764a5",
          "md5": "f647def0805c75d5ad2bff9b9ad4f233"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.2.1.jar",
          "url": "runescape-api-3.2.1.jar",
          "size": 55416,
          "sha512": "89e8345173603ec0253aa3721802237ef6c76b314c91c7ddd413d82e008637bef71a8409f5dd2ea84bde581b7c70d9f6e37742f48540bfada79e1dce866fa443",
          "sha256": "77e166ae5a8e51aff892c5c58c4c45f7109c2ab8bbfb946d8e9be559b74bf785",
          "sha1": "01c277218e1b3612451fc1752b067b8721a764a5",
          "md5": "f647def0805c75d5ad2bff9b9ad4f233"
        }
      ]
    }
  ]
}
