{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "bszlxxsiojfmxjrpuivynkz6e4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.9.jar",
          "url": "http-api-3.3.9.jar",
          "size": 157761,
          "sha512": "dd47576fc855b858f3fb23d6186f01969353035df10d656f55ae796a9339e120b29ae487fd2021cbcd5be73877d32c33e8a7c6758b73bcf268e4452ea281b1e9",
          "sha256": "33f7fd122eef3d8e58491d6f7b4b338c468ebe333e80e3174b337bee9bf2a621",
          "sha1": "2dccb141c741414213219a69098b717d191d8bc5",
          "md5": "33aaf606153d5415fdbc3401252e1abb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.9.jar",
          "url": "http-api-3.3.9.jar",
          "size": 157761,
          "sha512": "dd47576fc855b858f3fb23d6186f01969353035df10d656f55ae796a9339e120b29ae487fd2021cbcd5be73877d32c33e8a7c6758b73bcf268e4452ea281b1e9",
          "sha256": "33f7fd122eef3d8e58491d6f7b4b338c468ebe333e80e3174b337bee9bf2a621",
          "sha1": "2dccb141c741414213219a69098b717d191d8bc5",
          "md5": "33aaf606153d5415fdbc3401252e1abb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.9-sources.jar",
          "url": "http-api-3.3.9-sources.jar",
          "size": 103637,
          "sha512": "a736f46db0bfa5d09953615fb89c04bfc3905fda45a8a1861e23e95f004311a144a5ebf4784dde7167261541a737047efbbc3ed8cd8a86340bb27960a108acc7",
          "sha256": "cc8162c2d8d8a6ecbf96fe060f3bb047bb7e6ab8ac308aa52e4d64299a7279ae",
          "sha1": "9523f1ff46e54b71289d0ca6bdf8b239474bd96b",
          "md5": "c29aac92bd900f32941f0e1f36044d37"
        }
      ]
    }
  ]
}
