{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "nr6s34ue35fkpfyu2xbw5soeuq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.9.jar",
          "url": "http-api-3.3.9.jar",
          "size": 154401,
          "sha512": "19fea10490577f01d54457c446668c22f8c5826adc4e0773d2ff195aa34f4eceb7bf1a9fa4d3df4c80e3dec3c387da4da1b2462349fc01b12aedca21a98544dd",
          "sha256": "762f2e677ea73533789f82bdbb93d02f7e51cfa8f1fea62b8310e7f5a2154e8b",
          "sha1": "37d236336c60e2225e9a543812c0ea984d8551ed",
          "md5": "e04ebb027fb50eb5a5af1364541e57f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.9.jar",
          "url": "http-api-3.3.9.jar",
          "size": 154401,
          "sha512": "19fea10490577f01d54457c446668c22f8c5826adc4e0773d2ff195aa34f4eceb7bf1a9fa4d3df4c80e3dec3c387da4da1b2462349fc01b12aedca21a98544dd",
          "sha256": "762f2e677ea73533789f82bdbb93d02f7e51cfa8f1fea62b8310e7f5a2154e8b",
          "sha1": "37d236336c60e2225e9a543812c0ea984d8551ed",
          "md5": "e04ebb027fb50eb5a5af1364541e57f4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.9-sources.jar",
          "url": "http-api-3.3.9-sources.jar",
          "size": 101953,
          "sha512": "50ce99cc02325b283354840dc58b5dcf32484b2e7a1b9b8398007b6635307ae4087c107cabc81d8b5c25b0037df0abcf238bf1fdfe69538407fe91fd57f038f5",
          "sha256": "d8b19bdc7d3b5b5d419e9e55f46ba09a39b0e985bf6926c6b996a1d5aa6383ba",
          "sha1": "9828e806c82e2540b729d0b0a387a3654bed7acc",
          "md5": "66dc61cb446775ec7c6d508c8a5efaa9"
        }
      ]
    }
  ]
}
