{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "57mxt7rgjvembirf2ghn267kou"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.9.jar",
          "url": "http-api-3.3.9.jar",
          "size": 154402,
          "sha512": "40052a93650ce2f7a4b3ebc82b3f140b593f932aafe96cad3337f4df1adc059b62c62f438ccceabe230e80fab0369f308399b46105fafe063f6d9d5e35a8785e",
          "sha256": "ac5352e5d9089f3b640e6ee32c14a25b72543fbacb51f267e9d1739342fa9686",
          "sha1": "08512338b852601172cb984b75919fca19c022fd",
          "md5": "ebeaabecf0979ad4c19914c7053945ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.9.jar",
          "url": "http-api-3.3.9.jar",
          "size": 154402,
          "sha512": "40052a93650ce2f7a4b3ebc82b3f140b593f932aafe96cad3337f4df1adc059b62c62f438ccceabe230e80fab0369f308399b46105fafe063f6d9d5e35a8785e",
          "sha256": "ac5352e5d9089f3b640e6ee32c14a25b72543fbacb51f267e9d1739342fa9686",
          "sha1": "08512338b852601172cb984b75919fca19c022fd",
          "md5": "ebeaabecf0979ad4c19914c7053945ab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.9-sources.jar",
          "url": "http-api-3.3.9-sources.jar",
          "size": 101953,
          "sha512": "2d6f1ab00b045aa537ac242e3c1d9f584b7bfc05850c78838b0e13dd4f5953afd8425b334ebdbaa8cc9ae124520c42711eb103164cf9637082a41d2d481b88cb",
          "sha256": "2f6671da9744b476ad3328e24a3f2af7e1e1b26ba63c68a63304337a86299bf8",
          "sha1": "eeda0cd26bf46aebe7a22ba7e88e391ba331c604",
          "md5": "f43f7071d97f726d7f4a0c434fc42331"
        }
      ]
    }
  ]
}
