{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "66kqjmg7lrg33guig5udmisnmy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.3.jar",
          "url": "runelite-api-3.3.3.jar",
          "size": 1182890,
          "sha512": "7fe9e061f43fcc8e8ddc20ca2bcc380324d17cd879e125e3f5e6ec0c044855457d12a8eef1d5827b31fde0a2deba7faa14f24a0d5e129905535e1f2c0f8cc057",
          "sha256": "32531917fa8e016e2ed45541e2b554a79fa1d40cc995c7362bb3f7ca5ca35014",
          "sha1": "c2d9a1acd9f6c7189869ea2e5146984b9691d0e6",
          "md5": "40e0ef3b2e2d64a9f0e07b69c5b0d26c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.3.jar",
          "url": "runelite-api-3.3.3.jar",
          "size": 1182890,
          "sha512": "7fe9e061f43fcc8e8ddc20ca2bcc380324d17cd879e125e3f5e6ec0c044855457d12a8eef1d5827b31fde0a2deba7faa14f24a0d5e129905535e1f2c0f8cc057",
          "sha256": "32531917fa8e016e2ed45541e2b554a79fa1d40cc995c7362bb3f7ca5ca35014",
          "sha1": "c2d9a1acd9f6c7189869ea2e5146984b9691d0e6",
          "md5": "40e0ef3b2e2d64a9f0e07b69c5b0d26c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.3-sources.jar",
          "url": "runelite-api-3.3.3-sources.jar",
          "size": 866930,
          "sha512": "1a3ede6c2e1db8d826162ffb7f81b64675225eb0c39d33d942d4b1c34f7e07e31f41856e8f54e1586fd98e3a47be68fdebe57dab1428604e0212d16cc4debd72",
          "sha256": "884d50ecd61743719481958c7a9220feb96c8917da55e4a5b79aac1e6c96ad6f",
          "sha1": "ba4c2fb23f09397b780d259b5d90977742f11e61",
          "md5": "89911b75584afaa6813f7e07e579e6dc"
        }
      ]
    }
  ]
}
