{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "6v4fg4y7fzhu5bfris2fjbgutm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.3.jar",
          "url": "runelite-api-3.3.3.jar",
          "size": 1182890,
          "sha512": "60dfe3441101dd5e2167054ee80ba871024cae86074a45a174968463d1bdd8d4d885bbebc3680498bfcfaeb27c3e17157ecd5303bdf8322d15c959d2760f0a14",
          "sha256": "b8321e64ec872a48cfdf82d5327a7eb5455fb528f901b781557301f724566873",
          "sha1": "5a17cced74fb30a4da336a83ecbca2dfa3cec042",
          "md5": "99757579b8b82a89f4f7211bfa20af84"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.3.jar",
          "url": "runelite-api-3.3.3.jar",
          "size": 1182890,
          "sha512": "60dfe3441101dd5e2167054ee80ba871024cae86074a45a174968463d1bdd8d4d885bbebc3680498bfcfaeb27c3e17157ecd5303bdf8322d15c959d2760f0a14",
          "sha256": "b8321e64ec872a48cfdf82d5327a7eb5455fb528f901b781557301f724566873",
          "sha1": "5a17cced74fb30a4da336a83ecbca2dfa3cec042",
          "md5": "99757579b8b82a89f4f7211bfa20af84"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.3-sources.jar",
          "url": "runelite-api-3.3.3-sources.jar",
          "size": 866930,
          "sha512": "5d42bb705c62fd6014caced1604104caf7072806048c193f7b69bbe6f698bd77e7bdab44f795ef055213afe5023b93a60096dbc03d1fd8c8018c034344a8d35e",
          "sha256": "ca8ad5bea6a70fb6fec5014b2bb7baf1c82d04b643f1496dde9d4feb8c7b47f6",
          "sha1": "f96225c94f00dfd93050afca61c53635c3cb3b7e",
          "md5": "a8ef2bc88fb23ff6b099d9e5e2b97dc1"
        }
      ]
    }
  ]
}
