{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "5jyhhj26ufg2tcbfo6rjpcshbm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.9"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.9.jar",
          "url": "runescape-api-1.6.9.jar",
          "size": 55336,
          "sha512": "7527dcb82ed362b50fd3f8033cd0f9ca297dad868ea843bd8a13dbc36df0d395e9d87d8bda0c4b34d760cdc55c0e94d185fd535d4428523768b490300d246b0c",
          "sha256": "99e1338f911e34d0821f35eaa4159e106ac2e423f989f99eaa531af2101f66ec",
          "sha1": "2d6836a76a1d094d0ffe9f8db5f5154a14d97850",
          "md5": "d1f5198323b7b33dc4a0a37c15fa56b8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.9"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.9.jar",
          "url": "runescape-api-1.6.9.jar",
          "size": 55336,
          "sha512": "7527dcb82ed362b50fd3f8033cd0f9ca297dad868ea843bd8a13dbc36df0d395e9d87d8bda0c4b34d760cdc55c0e94d185fd535d4428523768b490300d246b0c",
          "sha256": "99e1338f911e34d0821f35eaa4159e106ac2e423f989f99eaa531af2101f66ec",
          "sha1": "2d6836a76a1d094d0ffe9f8db5f5154a14d97850",
          "md5": "d1f5198323b7b33dc4a0a37c15fa56b8"
        }
      ]
    }
  ]
}
