{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-client",
    "version": "3.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "hvqhzrsf6fg4vpeme5kjss6agi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-client-3.3.9.jar",
          "url": "runelite-client-3.3.9.jar",
          "size": 2666290,
          "sha512": "b09d5b1cc812eb6f4fd7434c918f8521b5ba91d6dab6a35dc570356b0c192dc11c92acedaad60aad64818ca10c68bfc08edb6cd9a1fe1a179cd670c19e49e626",
          "sha256": "415d8732df3ac610afb383b09ee69e4c2a3c1fd33b8e9b0ddde0691b6df1edd1",
          "sha1": "d9576106ddada0cee938ebe49a8af2e15a85de88",
          "md5": "bdca0b4ecb723e35bba84515ebcb6cef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "4.2.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "guice",
              "type": "jar",
              "extension": "jar",
              "classifier": "no_aop"
            }
          }
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "1.4.200"
          }
        },
        {
          "group": "com.jakewharton.rxrelay3",
          "module": "rxrelay",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "org.jgroups",
          "module": "jgroups",
          "version": {
            "requires": "4.2.4.Final"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "net.runelite",
          "module": "discord",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.pushing-pixels",
          "module": "radiance-substance",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "19.0.0"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq",
          "version": {
            "requires": "3.13.2"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq-codegen",
          "version": {
            "requires": "3.13.2"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq-meta",
          "version": {
            "requires": "3.13.2"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-logback",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.github.zafarkhaja",
          "module": "java-semver",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.pf4j",
          "module": "pf4j",
          "version": {
            "requires": "3.3.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.pf4j",
          "module": "pf4j-update",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "http-api",
          "version": {
            "requires": "3.3.9"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.9"
          }
        },
        {
          "group": "org.pushing-pixels",
          "module": "radiance-trident",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injected-client",
          "version": {
            "requires": "3.3.9"
          }
        },
        {
          "group": "com.openosrs.rs",
          "module": "runescape-api",
          "version": {
            "requires": "3.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-client-3.3.9.jar",
          "url": "runelite-client-3.3.9.jar",
          "size": 2666290,
          "sha512": "b09d5b1cc812eb6f4fd7434c918f8521b5ba91d6dab6a35dc570356b0c192dc11c92acedaad60aad64818ca10c68bfc08edb6cd9a1fe1a179cd670c19e49e626",
          "sha256": "415d8732df3ac610afb383b09ee69e4c2a3c1fd33b8e9b0ddde0691b6df1edd1",
          "sha1": "d9576106ddada0cee938ebe49a8af2e15a85de88",
          "md5": "bdca0b4ecb723e35bba84515ebcb6cef"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-client-3.3.9-shaded.jar",
          "url": "runelite-client-3.3.9-shaded.jar",
          "size": 31466674,
          "sha512": "ce6b119e841476728b94932a143543488dfaf648456bfbc6215cd419c213cc00da79b1df436d8faeaa2cb256ff436cf0d111f77642f6eb3fc78466ee17fb3d63",
          "sha256": "c0e3cce7255758bef91d3468cec6ce9f372a0b7571d190499b79ce9d657b13f6",
          "sha1": "40a5ac55181aa473e6255af1804d0293e44d3700",
          "md5": "25444f50eb2ff562744b35249dee56dc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-client-3.3.9-sources.jar",
          "url": "runelite-client-3.3.9-sources.jar",
          "size": 2317707,
          "sha512": "55e35338f3f4fbe3ba63979cb29dcad2545f85804df12017d081cbe49afb1b7d92aece4e565d5649ca1ab862833d0fab8293ff1cc900b534cb57c18bd0ba721d",
          "sha256": "557b60879778975d0a5bc6f52019b78a88d591c679711d290e86d7ccfa35ba32",
          "sha1": "8c3424774d6c3f56885815a08d00986b0aae25f1",
          "md5": "5182e1b5b4b3334c4c2868bf56bd89bb"
        }
      ]
    }
  ]
}
