{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-client",
    "version": "3.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "nkjidasifvep7jumf6tquswwy4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-client-3.3.9.jar",
          "url": "runelite-client-3.3.9.jar",
          "size": 2666416,
          "sha512": "51f84f5a95aa2ed60c3696620f41901f9c6c0208223120661f9ceee99ca198edc0961511fe1021c237901a8b3062b734594957705e94342a0a8ad90cd53a22e5",
          "sha256": "d8b542a7d95d630c732d472e9d01a585ae08e67b192d2c079dbb2e2c70b6277a",
          "sha1": "6012af4edb0706a3ebff888c6fb2ff5840e81d0a",
          "md5": "332db8a6da038b2a723bd9bf3658784d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "4.2.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "guice",
              "type": "jar",
              "extension": "jar",
              "classifier": "no_aop"
            }
          }
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "1.4.200"
          }
        },
        {
          "group": "com.jakewharton.rxrelay3",
          "module": "rxrelay",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "org.jgroups",
          "module": "jgroups",
          "version": {
            "requires": "4.2.4.Final"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "net.runelite",
          "module": "discord",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.pushing-pixels",
          "module": "radiance-substance",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "19.0.0"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq",
          "version": {
            "requires": "3.13.2"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq-codegen",
          "version": {
            "requires": "3.13.2"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq-meta",
          "version": {
            "requires": "3.13.2"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-logback",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.github.zafarkhaja",
          "module": "java-semver",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.pf4j",
          "module": "pf4j",
          "version": {
            "requires": "3.3.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.pf4j",
          "module": "pf4j-update",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "http-api",
          "version": {
            "requires": "3.3.9"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.9"
          }
        },
        {
          "group": "org.pushing-pixels",
          "module": "radiance-trident",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injected-client",
          "version": {
            "requires": "3.3.9"
          }
        },
        {
          "group": "com.openosrs.rs",
          "module": "runescape-api",
          "version": {
            "requires": "3.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-client-3.3.9.jar",
          "url": "runelite-client-3.3.9.jar",
          "size": 2666416,
          "sha512": "51f84f5a95aa2ed60c3696620f41901f9c6c0208223120661f9ceee99ca198edc0961511fe1021c237901a8b3062b734594957705e94342a0a8ad90cd53a22e5",
          "sha256": "d8b542a7d95d630c732d472e9d01a585ae08e67b192d2c079dbb2e2c70b6277a",
          "sha1": "6012af4edb0706a3ebff888c6fb2ff5840e81d0a",
          "md5": "332db8a6da038b2a723bd9bf3658784d"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-client-3.3.9-shaded.jar",
          "url": "runelite-client-3.3.9-shaded.jar",
          "size": 31466749,
          "sha512": "023fd69a8d81cacc18004fd029453293b2d407f9e3c594951c965d197bd690bd061ccb1bf0206f6d35dbdee40f5ed667d47425d82500cd6f2aa942183fe0b1bf",
          "sha256": "67c537e1344d207c76928b9c8441ad8d6894f48fbea908d1d0445ef3a94b4310",
          "sha1": "3274055f8da04e1ab4d3504a9d2d524445adf9df",
          "md5": "a11ec3b9f306db260853eb6976c93a35"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-client-3.3.9-sources.jar",
          "url": "runelite-client-3.3.9-sources.jar",
          "size": 2317829,
          "sha512": "d929f914e58bee1e87d2ee91eebfa5c1d76bfb64f84c2b541a04c7f3fb65e83511004057dc41453979d0ac7c95eb7b13a5b83a514c89d802053eac8b2c1a7d29",
          "sha256": "4eacd599336efd49f0ba530a1d33b20a04aaa7aed754119133018688e252f8f5",
          "sha1": "368b43bb289e9f1af57789875ba3e96f3e85aac1",
          "md5": "9e161d4d1f9a9722d80ad553920306c8"
        }
      ]
    }
  ]
}
