{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "5kw5yywz5be3xgfu3yi64baf2e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.2.1.jar",
          "url": "http-api-3.2.1.jar",
          "size": 165561,
          "sha512": "a85efb0b4911e8d35baff5d29fd3a85d553c57daa20c445febee846e0bcd66ca178107d1251702fafeb3a9afea603dd00584b6082d421c4efe802b3fda3572ed",
          "sha256": "8b30357866135f4ceae5ec4e7036e3e569f5fe4c5e21f944e859492f2e252dc0",
          "sha1": "da5fdceefd0e29fe7deb3e41193c6ea1de15dfa8",
          "md5": "bbf61b6d208d8bac8a5c9a7b89ef224c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.2.1.jar",
          "url": "http-api-3.2.1.jar",
          "size": 165561,
          "sha512": "a85efb0b4911e8d35baff5d29fd3a85d553c57daa20c445febee846e0bcd66ca178107d1251702fafeb3a9afea603dd00584b6082d421c4efe802b3fda3572ed",
          "sha256": "8b30357866135f4ceae5ec4e7036e3e569f5fe4c5e21f944e859492f2e252dc0",
          "sha1": "da5fdceefd0e29fe7deb3e41193c6ea1de15dfa8",
          "md5": "bbf61b6d208d8bac8a5c9a7b89ef224c"
        }
      ]
    }
  ]
}
