{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "jrf73pb77va5jdzg4hguqgamem"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.2.1.jar",
          "url": "http-api-3.2.1.jar",
          "size": 165562,
          "sha512": "7932e4ab6ee7c2caf14c92468a4ff3d80ec457886b92afd0598c8540400209480b7bc98a20a90a1c5e8c26db1ff4d198fff29402bc32bc6f927fc81b6c7a123a",
          "sha256": "7aef49e5d1914ed7430b0239e961e1e977b37bbecdc483c3c771853ed92211cb",
          "sha1": "220d87c7e30d3d4bff8daa0b397c2f1e0705f10d",
          "md5": "7869a48921d52f8ec9ae3a2b8f062ddd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.2.1.jar",
          "url": "http-api-3.2.1.jar",
          "size": 165562,
          "sha512": "7932e4ab6ee7c2caf14c92468a4ff3d80ec457886b92afd0598c8540400209480b7bc98a20a90a1c5e8c26db1ff4d198fff29402bc32bc6f927fc81b6c7a123a",
          "sha256": "7aef49e5d1914ed7430b0239e961e1e977b37bbecdc483c3c771853ed92211cb",
          "sha1": "220d87c7e30d3d4bff8daa0b397c2f1e0705f10d",
          "md5": "7869a48921d52f8ec9ae3a2b8f062ddd"
        }
      ]
    }
  ]
}
