{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "vynbebrvhvhfzhix6l6yy36cuy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.2.1.jar",
          "url": "http-api-3.2.1.jar",
          "size": 165559,
          "sha512": "5e231b5513c3c75df1a3539384f3b1389b09f8240ec83b4b4b2acaad2281fc8df7289108703dd849d44ad2b3d025433ad1990fa84c8f0a4d4afad805faad9f98",
          "sha256": "bb8dd363bebeb7ad3e5a67e95a0c2b88abec0da3e02670ecc3f18594d99edf9e",
          "sha1": "ca06fb7e54cf13728cacf3b7a043431b4fba7372",
          "md5": "695370256a4afbaa7d3b90f6a0615ee9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.2.1.jar",
          "url": "http-api-3.2.1.jar",
          "size": 165559,
          "sha512": "5e231b5513c3c75df1a3539384f3b1389b09f8240ec83b4b4b2acaad2281fc8df7289108703dd849d44ad2b3d025433ad1990fa84c8f0a4d4afad805faad9f98",
          "sha256": "bb8dd363bebeb7ad3e5a67e95a0c2b88abec0da3e02670ecc3f18594d99edf9e",
          "sha1": "ca06fb7e54cf13728cacf3b7a043431b4fba7372",
          "md5": "695370256a4afbaa7d3b90f6a0615ee9"
        }
      ]
    }
  ]
}
