{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "eozc5css2rdz5fb6c4fkiwagdq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.2.2.jar",
          "url": "injected-client-3.2.2.jar",
          "size": 2252140,
          "sha512": "497d8e0c45fc4c9275147a68632a3388ccafc477a4d04840cec8fc7d30baf8749d6001398a9074b3467c0c8f7732537b18954df5300b94cdcc067083a96c045f",
          "sha256": "4166c891ac18e62c96085f940dc5a0cb5fbc891387c90deaa2fd24955c61f251",
          "sha1": "a0cded861c9eea951d3ef57cc08c7dd1a6238f2e",
          "md5": "9cc2d7f91dd1acf1b1ad5d41af3ebd71"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.2.2.jar",
          "url": "injected-client-3.2.2.jar",
          "size": 2252140,
          "sha512": "497d8e0c45fc4c9275147a68632a3388ccafc477a4d04840cec8fc7d30baf8749d6001398a9074b3467c0c8f7732537b18954df5300b94cdcc067083a96c045f",
          "sha256": "4166c891ac18e62c96085f940dc5a0cb5fbc891387c90deaa2fd24955c61f251",
          "sha1": "a0cded861c9eea951d3ef57cc08c7dd1a6238f2e",
          "md5": "9cc2d7f91dd1acf1b1ad5d41af3ebd71"
        }
      ]
    }
  ]
}
