{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "zubdortb4nfvfg2djchzs4s4va"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.2.2.jar",
          "url": "injected-client-3.2.2.jar",
          "size": 2252140,
          "sha512": "695c1ada8d83babf46fb9326ec2c09a005a4cbda03124e1d8172fa98839de7af236f89415ff1201ea68322391b4df7f84fe79df9b85ea2c0b4340b6fe3c3ed24",
          "sha256": "4caddf10af0b4a2cad1dfb24b10fa65ad976754baa1bdefacb24cf0f257702f2",
          "sha1": "ea9e79e39fbf36a4d7769378528b2e5f8d0e4571",
          "md5": "ebe33286da21a3b6ece1cd97122d180e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.2.2.jar",
          "url": "injected-client-3.2.2.jar",
          "size": 2252140,
          "sha512": "695c1ada8d83babf46fb9326ec2c09a005a4cbda03124e1d8172fa98839de7af236f89415ff1201ea68322391b4df7f84fe79df9b85ea2c0b4340b6fe3c3ed24",
          "sha256": "4caddf10af0b4a2cad1dfb24b10fa65ad976754baa1bdefacb24cf0f257702f2",
          "sha1": "ea9e79e39fbf36a4d7769378528b2e5f8d0e4571",
          "md5": "ebe33286da21a3b6ece1cd97122d180e"
        }
      ]
    }
  ]
}
