{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "zwbdy6ivf5ampkvubyr2ohfu4y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.2.2.jar",
          "url": "injected-client-3.2.2.jar",
          "size": 2252140,
          "sha512": "4ba7b452fd3d4a712f39f410347c7f975f2297b2d1b192fb2d4a9d2e5f6aa66391fca517c1a7f41f651c86b47b5f91f3b41421da232419b38b809a58e304466f",
          "sha256": "8ce3f0b98be0277534a754b6e82f0e975b9dcc491d28ffb3a94084de7d644bd4",
          "sha1": "4dd2815a36fd19de1450d60ff7a17c7604ac9f85",
          "md5": "fbb97d37a84170647810289b15a60f5b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.2.2.jar",
          "url": "injected-client-3.2.2.jar",
          "size": 2252140,
          "sha512": "4ba7b452fd3d4a712f39f410347c7f975f2297b2d1b192fb2d4a9d2e5f6aa66391fca517c1a7f41f651c86b47b5f91f3b41421da232419b38b809a58e304466f",
          "sha256": "8ce3f0b98be0277534a754b6e82f0e975b9dcc491d28ffb3a94084de7d644bd4",
          "sha1": "4dd2815a36fd19de1450d60ff7a17c7604ac9f85",
          "md5": "fbb97d37a84170647810289b15a60f5b"
        }
      ]
    }
  ]
}
