{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "nks3juklb5eunefxms6kyelpry"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6-SNAPSHOT.jar",
          "url": "runescape-api-1.6.6-20200131.175257-1.jar",
          "size": 55272,
          "sha512": "8642f150c7cf5ca293069ea590ccdc28a59a3c7e2bcc03d3254d44127a227ea2a522be6096604237dc8e2c179485e6e0d98c9dfa21bd02c4f08da9e0ded95e31",
          "sha256": "430a51f1cb35144d9aaca64cc9cf71cc57a37f72fb4b748b04e91bdad1bf2b37",
          "sha1": "9be8d8792117f1f231e26fc8fe30f23e1d6670d0",
          "md5": "fa33d9533b053bd46380c6e027ef41a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6-SNAPSHOT.jar",
          "url": "runescape-api-1.6.6-20200131.175257-1.jar",
          "size": 55272,
          "sha512": "8642f150c7cf5ca293069ea590ccdc28a59a3c7e2bcc03d3254d44127a227ea2a522be6096604237dc8e2c179485e6e0d98c9dfa21bd02c4f08da9e0ded95e31",
          "sha256": "430a51f1cb35144d9aaca64cc9cf71cc57a37f72fb4b748b04e91bdad1bf2b37",
          "sha1": "9be8d8792117f1f231e26fc8fe30f23e1d6670d0",
          "md5": "fa33d9533b053bd46380c6e027ef41a0"
        }
      ]
    }
  ]
}
