{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "x5na3rh3jvcb5g2x2nwm5bocru"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6-SNAPSHOT.jar",
          "url": "runescape-api-1.6.6-20200214.001210-1.jar",
          "size": 55272,
          "sha512": "b3d9a14726985a867af4aa92c58debf51a8a3364f82649df98d185bbddbf2229ea56af48a0dbd2d3abb2c643a5f82eb9d691bbcce38eab2c8ecd817e89a5af4a",
          "sha256": "a5f8c81d0a403b5de859424877455ac43b53f1471016a97b0c77acceaad94f7b",
          "sha1": "86568f5c7af5271d1cb4267059990402152b5b48",
          "md5": "d184eebdb8f2bf1956c129f549c9b571"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6-SNAPSHOT.jar",
          "url": "runescape-api-1.6.6-20200214.001210-1.jar",
          "size": 55272,
          "sha512": "b3d9a14726985a867af4aa92c58debf51a8a3364f82649df98d185bbddbf2229ea56af48a0dbd2d3abb2c643a5f82eb9d691bbcce38eab2c8ecd817e89a5af4a",
          "sha256": "a5f8c81d0a403b5de859424877455ac43b53f1471016a97b0c77acceaad94f7b",
          "sha1": "86568f5c7af5271d1cb4267059990402152b5b48",
          "md5": "d184eebdb8f2bf1956c129f549c9b571"
        }
      ]
    }
  ]
}
