{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "3h3babsauzdcnjcduoss5gpsie"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6-SNAPSHOT.jar",
          "url": "runescape-api-1.6.6-20200212.001207-1.jar",
          "size": 55272,
          "sha512": "d9e97b721fbdb95697e1cdbc0e25dfe68c8ba4d075825e8e1cc2625c6898230abf96e32e8eafbe39efc61431db6e155854185a93f75d7c6a0ce3033839555edb",
          "sha256": "50403b792638a97b739ea6b58009b38e9b1629a38b89f17383719aef79068519",
          "sha1": "3a5b2f42304512ed413d3f5c8e84989132d856ef",
          "md5": "33c6770034423bab6f1a87682ec56ed5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6-SNAPSHOT.jar",
          "url": "runescape-api-1.6.6-20200212.001207-1.jar",
          "size": 55272,
          "sha512": "d9e97b721fbdb95697e1cdbc0e25dfe68c8ba4d075825e8e1cc2625c6898230abf96e32e8eafbe39efc61431db6e155854185a93f75d7c6a0ce3033839555edb",
          "sha256": "50403b792638a97b739ea6b58009b38e9b1629a38b89f17383719aef79068519",
          "sha1": "3a5b2f42304512ed413d3f5c8e84989132d856ef",
          "md5": "33c6770034423bab6f1a87682ec56ed5"
        }
      ]
    }
  ]
}
