{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "izq2qevp6ng6tmqpsmwfj2gwf4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6-SNAPSHOT.jar",
          "url": "runescape-api-1.6.6-20200129.173414-1.jar",
          "size": 55272,
          "sha512": "e57b521e5a91b34616427538a72a6b9177a454886a1de61259844e6cc9f80d5c857ead523a46d023fc7c499d15b1bd9d05c3ee398a3f19e55205010ba246828f",
          "sha256": "808d2fe90f7d6e1330cc4d6ac4fddcaf8949d60d8b602eb7c94da6c4189dcaa8",
          "sha1": "f52eb374ca16bcdc2b566e0a101bda2ef3ea9e19",
          "md5": "9e3d9eef49d0902fa7403c5cc89205b8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6-SNAPSHOT.jar",
          "url": "runescape-api-1.6.6-20200129.173414-1.jar",
          "size": 55272,
          "sha512": "e57b521e5a91b34616427538a72a6b9177a454886a1de61259844e6cc9f80d5c857ead523a46d023fc7c499d15b1bd9d05c3ee398a3f19e55205010ba246828f",
          "sha256": "808d2fe90f7d6e1330cc4d6ac4fddcaf8949d60d8b602eb7c94da6c4189dcaa8",
          "sha1": "f52eb374ca16bcdc2b566e0a101bda2ef3ea9e19",
          "md5": "9e3d9eef49d0902fa7403c5cc89205b8"
        }
      ]
    }
  ]
}
