{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "f4uoenkc5bdpvjswckxlmyq7le"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6-SNAPSHOT.jar",
          "url": "runescape-api-1.6.6-20200201.000847-1.jar",
          "size": 55272,
          "sha512": "fd0ba169b961537f2f04fd5365dda34c30637151ea452dbc3cd00f65bae7820a4b7f40027865d7ca36ef59c7a6f913860d5eabcc1e2d2360a771c28d58107e87",
          "sha256": "faec2ae2aafcbfa91db2cad4dc148f222f28b712d169b6dc1c10a88fe6a422d1",
          "sha1": "3f26fc2fdef516761c3c4c5d455f8ff4019a2ce8",
          "md5": "69db9f98b94f8a38449ead1eb14597c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6-SNAPSHOT.jar",
          "url": "runescape-api-1.6.6-20200201.000847-1.jar",
          "size": 55272,
          "sha512": "fd0ba169b961537f2f04fd5365dda34c30637151ea452dbc3cd00f65bae7820a4b7f40027865d7ca36ef59c7a6f913860d5eabcc1e2d2360a771c28d58107e87",
          "sha256": "faec2ae2aafcbfa91db2cad4dc148f222f28b712d169b6dc1c10a88fe6a422d1",
          "sha1": "3f26fc2fdef516761c3c4c5d455f8ff4019a2ce8",
          "md5": "69db9f98b94f8a38449ead1eb14597c3"
        }
      ]
    }
  ]
}
