{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "n7ajluuqdrhsjnxl5l73bbwfra"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6-SNAPSHOT.jar",
          "url": "runescape-api-1.6.6-20200204.000941-1.jar",
          "size": 55272,
          "sha512": "a5184a3a52be7cad740570f70867d16b79a4a2caaa0b9ed4c8270863f2769b812219f829ea6a8cf12710fc698fa5454098c2a4b20b8766f350a93f5dde0bdc54",
          "sha256": "fcc31e2dd4b23ded600722232864c3285d2bbf3af0de6a022e8b07a68b9d99e8",
          "sha1": "08b467026b0cd0653e9b4fe7aed893a06f58a11c",
          "md5": "750aa3c10d291c14b7720039485a185d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6-SNAPSHOT.jar",
          "url": "runescape-api-1.6.6-20200204.000941-1.jar",
          "size": 55272,
          "sha512": "a5184a3a52be7cad740570f70867d16b79a4a2caaa0b9ed4c8270863f2769b812219f829ea6a8cf12710fc698fa5454098c2a4b20b8766f350a93f5dde0bdc54",
          "sha256": "fcc31e2dd4b23ded600722232864c3285d2bbf3af0de6a022e8b07a68b9d99e8",
          "sha1": "08b467026b0cd0653e9b4fe7aed893a06f58a11c",
          "md5": "750aa3c10d291c14b7720039485a185d"
        }
      ]
    }
  ]
}
