{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "efrsqpvncbgtdnwjzuxejex6je"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6-SNAPSHOT.jar",
          "url": "runescape-api-1.6.6-20200211.223543-1.jar",
          "size": 55272,
          "sha512": "ed47a7f96b36eec5803258a5efcb1574d37e813b2c41d6788b04aade56da9ccd7fcba8436bf94e2933aae6ece32044249a5f17fd167d96b65bb1baf993d56269",
          "sha256": "958d8b101b13d9fb795f9f011d977fb424c1c0ccac1414837a62e5f832247ecf",
          "sha1": "556dba93b384dd87143e50f01d8b82b9383d4c90",
          "md5": "df297e1232eb87a367e8a2d2166f859e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6-SNAPSHOT.jar",
          "url": "runescape-api-1.6.6-20200211.223543-1.jar",
          "size": 55272,
          "sha512": "ed47a7f96b36eec5803258a5efcb1574d37e813b2c41d6788b04aade56da9ccd7fcba8436bf94e2933aae6ece32044249a5f17fd167d96b65bb1baf993d56269",
          "sha256": "958d8b101b13d9fb795f9f011d977fb424c1c0ccac1414837a62e5f832247ecf",
          "sha1": "556dba93b384dd87143e50f01d8b82b9383d4c90",
          "md5": "df297e1232eb87a367e8a2d2166f859e"
        }
      ]
    }
  ]
}
