{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "ac6pd77vwnduxh5v2pbsddkgfi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6-SNAPSHOT.jar",
          "url": "runescape-api-1.6.6-20200213.001218-1.jar",
          "size": 55272,
          "sha512": "5c99e736c44b90ad9b89357b6b6619be869cc339f902288521a4fa2916c354dc648ed3120b2450da5a2559dba0f6673bfc63caacdcf840d71d59637bb7386490",
          "sha256": "010f4df9378498fba2fc7ae955c45f98789b6248e71a1f2bf6e1398b6d1fa807",
          "sha1": "a1eda56d83711b69f39fa5872885eb044943e40a",
          "md5": "704778f6e253fe2aff4c4bc8f42c747e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6-SNAPSHOT.jar",
          "url": "runescape-api-1.6.6-20200213.001218-1.jar",
          "size": 55272,
          "sha512": "5c99e736c44b90ad9b89357b6b6619be869cc339f902288521a4fa2916c354dc648ed3120b2450da5a2559dba0f6673bfc63caacdcf840d71d59637bb7386490",
          "sha256": "010f4df9378498fba2fc7ae955c45f98789b6248e71a1f2bf6e1398b6d1fa807",
          "sha1": "a1eda56d83711b69f39fa5872885eb044943e40a",
          "md5": "704778f6e253fe2aff4c4bc8f42c747e"
        }
      ]
    }
  ]
}
