{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "6fkt64kyjfg57fb6jqmpgcldwe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6-SNAPSHOT.jar",
          "url": "runescape-api-1.6.6-20200211.001142-1.jar",
          "size": 55272,
          "sha512": "fb1a53f0b06ca2f4386de67f5bfce66fa66f1815abe80b606b1cc88c9412fd48948de7d8494f83c168083c44cd9767b4ade3852754bf3b3c8d554845f68dfbb3",
          "sha256": "bb5212d25568b5dd11331af0469d19f1aafaa34fcbdafcf78aedb748b7b2acc6",
          "sha1": "58d7be89e5e84d5a4e9f7b6c59d61ccdcce6ca67",
          "md5": "dfb68517c7dd276ea649a5fbc5d74d20"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6-SNAPSHOT.jar",
          "url": "runescape-api-1.6.6-20200211.001142-1.jar",
          "size": 55272,
          "sha512": "fb1a53f0b06ca2f4386de67f5bfce66fa66f1815abe80b606b1cc88c9412fd48948de7d8494f83c168083c44cd9767b4ade3852754bf3b3c8d554845f68dfbb3",
          "sha256": "bb5212d25568b5dd11331af0469d19f1aafaa34fcbdafcf78aedb748b7b2acc6",
          "sha1": "58d7be89e5e84d5a4e9f7b6c59d61ccdcce6ca67",
          "md5": "dfb68517c7dd276ea649a5fbc5d74d20"
        }
      ]
    }
  ]
}
