{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "42df6ild3ndbvawwmbvzhjzodi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6-SNAPSHOT.jar",
          "url": "runescape-api-1.6.6-20200209.222509-1.jar",
          "size": 55272,
          "sha512": "f1efef5275f9cb80183fc9eb7c97f3a9afd11ffb51c2da7b540d16c26fb20cbe74c0b63dde15ad2caff8d8704f9e81e3518afa249ff5bdf7fbb990dbf489e748",
          "sha256": "3caa883589f70c1b23df38fb17058405004119d2b620f937c51895af4995f324",
          "sha1": "0a45d8905e0b11141a7e4e904a3294304283a347",
          "md5": "1ee8ebc7eb3b488332c58d9928909f2b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6-SNAPSHOT.jar",
          "url": "runescape-api-1.6.6-20200209.222509-1.jar",
          "size": 55272,
          "sha512": "f1efef5275f9cb80183fc9eb7c97f3a9afd11ffb51c2da7b540d16c26fb20cbe74c0b63dde15ad2caff8d8704f9e81e3518afa249ff5bdf7fbb990dbf489e748",
          "sha256": "3caa883589f70c1b23df38fb17058405004119d2b620f937c51895af4995f324",
          "sha1": "0a45d8905e0b11141a7e4e904a3294304283a347",
          "md5": "1ee8ebc7eb3b488332c58d9928909f2b"
        }
      ]
    }
  ]
}
