{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "2fhdwpc6yvhqjmw3p4di3i632q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6-SNAPSHOT.jar",
          "url": "runescape-api-1.6.6-20200210.001228-1.jar",
          "size": 55272,
          "sha512": "85ae032bb7d17c169bb8b570fcab62b48983434f0ca932c21f8615359809d74e5d2433d263d7426eb3237782ee2e5028df642acfb7277452eac0fffb7f975459",
          "sha256": "56ff54d31faef07754e60595f3c852b63c3bf1a66bde00da19f0224ce5f5ea16",
          "sha1": "14407211345deb54ba0e18afb8cef6dcf41c8a0b",
          "md5": "6b5c083cfcec96731d5e0c2ce57e1143"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6-SNAPSHOT.jar",
          "url": "runescape-api-1.6.6-20200210.001228-1.jar",
          "size": 55272,
          "sha512": "85ae032bb7d17c169bb8b570fcab62b48983434f0ca932c21f8615359809d74e5d2433d263d7426eb3237782ee2e5028df642acfb7277452eac0fffb7f975459",
          "sha256": "56ff54d31faef07754e60595f3c852b63c3bf1a66bde00da19f0224ce5f5ea16",
          "sha1": "14407211345deb54ba0e18afb8cef6dcf41c8a0b",
          "md5": "6b5c083cfcec96731d5e0c2ce57e1143"
        }
      ]
    }
  ]
}
