{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "ltsdzirxwbdgtlo4qddimrbscq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6-SNAPSHOT.jar",
          "url": "runescape-api-1.6.6-20200206.000857-1.jar",
          "size": 55272,
          "sha512": "85631aa02d30e02becff63d89fb066a997a6717580adf97a0e6c3cf047868e22cf9c5e41de61e3d58939c1a1520d79cc9c8978f33971c16fab79ea4c0b4bd653",
          "sha256": "15922f696896bbf10f84084358ffccb94fc0965df9b3da57a8c48c2eb9792c5f",
          "sha1": "78db2cc2ebf8abdcc7b43f754ecb3e76a558ffc0",
          "md5": "01108a0d17a2bdb11a7a5be0c96d6eb0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6-SNAPSHOT.jar",
          "url": "runescape-api-1.6.6-20200206.000857-1.jar",
          "size": 55272,
          "sha512": "85631aa02d30e02becff63d89fb066a997a6717580adf97a0e6c3cf047868e22cf9c5e41de61e3d58939c1a1520d79cc9c8978f33971c16fab79ea4c0b4bd653",
          "sha256": "15922f696896bbf10f84084358ffccb94fc0965df9b3da57a8c48c2eb9792c5f",
          "sha1": "78db2cc2ebf8abdcc7b43f754ecb3e76a558ffc0",
          "md5": "01108a0d17a2bdb11a7a5be0c96d6eb0"
        }
      ]
    }
  ]
}
