{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "6garymirazahvbgjp3g6xxwspu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6-SNAPSHOT.jar",
          "url": "runescape-api-1.6.6-20200207.000935-1.jar",
          "size": 55272,
          "sha512": "173f5dc1572616fca3c4f7fbad5c41a54156b0abedbd64aadaa73f01eff0c9372ec42c8fa632961ff11e463d14e3a4ba24441c65a9ffddfaf4aa3eb54ab38cfa",
          "sha256": "a593f924106921de48cc294b7f08f4ba1fe9d75482fde3a3a105f7ec1d747256",
          "sha1": "f45cede642f1175e1180a713f284af9af9912ae8",
          "md5": "ae220dfd6d0517df1186308c7f7c2dfa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6-SNAPSHOT.jar",
          "url": "runescape-api-1.6.6-20200207.000935-1.jar",
          "size": 55272,
          "sha512": "173f5dc1572616fca3c4f7fbad5c41a54156b0abedbd64aadaa73f01eff0c9372ec42c8fa632961ff11e463d14e3a4ba24441c65a9ffddfaf4aa3eb54ab38cfa",
          "sha256": "a593f924106921de48cc294b7f08f4ba1fe9d75482fde3a3a105f7ec1d747256",
          "sha1": "f45cede642f1175e1180a713f284af9af9912ae8",
          "md5": "ae220dfd6d0517df1186308c7f7c2dfa"
        }
      ]
    }
  ]
}
