{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "hd2x4jqv4vcatk3rjnrmy3xgta"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6-SNAPSHOT.jar",
          "url": "runescape-api-1.6.6-20200129.140204-1.jar",
          "size": 55272,
          "sha512": "6d0e87e833d0852b3aa58ff7958a475b7c616ab2957388233bfe70481703c520eaf2aa439b91832e538db1c2b56ba2c9e40e9e2cbb949ebd7f76226ea7cd92cf",
          "sha256": "b86048ac09c1206da5a460b67bf3fa68be236101ea3eb50159ec4954ad638537",
          "sha1": "461b01c9d0544f8c5dcbc6940eb5fce2f64e717b",
          "md5": "385eda10c6afc0a2e73129032a1750a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6-SNAPSHOT.jar",
          "url": "runescape-api-1.6.6-20200129.140204-1.jar",
          "size": 55272,
          "sha512": "6d0e87e833d0852b3aa58ff7958a475b7c616ab2957388233bfe70481703c520eaf2aa439b91832e538db1c2b56ba2c9e40e9e2cbb949ebd7f76226ea7cd92cf",
          "sha256": "b86048ac09c1206da5a460b67bf3fa68be236101ea3eb50159ec4954ad638537",
          "sha1": "461b01c9d0544f8c5dcbc6940eb5fce2f64e717b",
          "md5": "385eda10c6afc0a2e73129032a1750a9"
        }
      ]
    }
  ]
}
