{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "w6bxz5lg6ne2jcow2buh2cbpta"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.7.jar",
          "url": "runescape-api-1.6.7.jar",
          "size": 55336,
          "sha512": "c3fce0d9d5fba9fc88d4d9f938b424b189f88664d9ad0b947c7aef2de2c191d96ef952840e68aeac9b3b322a0785e1f5851993146c80b3835e439c61f7d3cced",
          "sha256": "5ea4b607e2dbc9ab6b4faa935282411777e55d5fcbecd6f93854951ebe536eaa",
          "sha1": "34b604ea03b8839d6bac88338bb459bb6a946efa",
          "md5": "6b6c5b6a8a1975c9773213b15ab8ae02"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.7.jar",
          "url": "runescape-api-1.6.7.jar",
          "size": 55336,
          "sha512": "c3fce0d9d5fba9fc88d4d9f938b424b189f88664d9ad0b947c7aef2de2c191d96ef952840e68aeac9b3b322a0785e1f5851993146c80b3835e439c61f7d3cced",
          "sha256": "5ea4b607e2dbc9ab6b4faa935282411777e55d5fcbecd6f93854951ebe536eaa",
          "sha1": "34b604ea03b8839d6bac88338bb459bb6a946efa",
          "md5": "6b6c5b6a8a1975c9773213b15ab8ae02"
        }
      ]
    }
  ]
}
