{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "dvgrgv5jv5fpvhst277gs744wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.7.jar",
          "url": "runescape-api-1.6.7.jar",
          "size": 55336,
          "sha512": "8f01b8f4f3d777c56eede58da5dbab7313f8c3671c9058df6de933f2be3b7ef202582326b4cd4cf35c31daac33e0e18160b6d01ab828e406c77227b53c61fafd",
          "sha256": "c3461fb075a90f5704ac6568562fc203ce8b7ec6f653fac3e6dbc75ee1a2e2f6",
          "sha1": "0e53d7ed6c3690dfe026235a19aa5f719c895155",
          "md5": "00c977547b680b86da480d6da3ec59f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.7.jar",
          "url": "runescape-api-1.6.7.jar",
          "size": 55336,
          "sha512": "8f01b8f4f3d777c56eede58da5dbab7313f8c3671c9058df6de933f2be3b7ef202582326b4cd4cf35c31daac33e0e18160b6d01ab828e406c77227b53c61fafd",
          "sha256": "c3461fb075a90f5704ac6568562fc203ce8b7ec6f653fac3e6dbc75ee1a2e2f6",
          "sha1": "0e53d7ed6c3690dfe026235a19aa5f719c895155",
          "md5": "00c977547b680b86da480d6da3ec59f6"
        }
      ]
    }
  ]
}
