{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "skpysh7pgfdrzevma54h74dx7i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.7.jar",
          "url": "runescape-api-1.6.7.jar",
          "size": 55336,
          "sha512": "6c0b7686d1fef941af8ae984ffcbb289e2557ccfca1d401eb2bef8c712ead70551cdea31c5e5fb522481b64d221e06360c66a9ef3e8e9f54442ffbf6fbcc0a24",
          "sha256": "223e6ee9f7dfcc44292f2ab6f521df5ed5d0bd267ef25896368bc8ce252baa41",
          "sha1": "095244ee1bb049a1b64ece7161c581bc09996551",
          "md5": "2235dda2b4d6da3942ec4cd0f49cc3a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.7.jar",
          "url": "runescape-api-1.6.7.jar",
          "size": 55336,
          "sha512": "6c0b7686d1fef941af8ae984ffcbb289e2557ccfca1d401eb2bef8c712ead70551cdea31c5e5fb522481b64d221e06360c66a9ef3e8e9f54442ffbf6fbcc0a24",
          "sha256": "223e6ee9f7dfcc44292f2ab6f521df5ed5d0bd267ef25896368bc8ce252baa41",
          "sha1": "095244ee1bb049a1b64ece7161c581bc09996551",
          "md5": "2235dda2b4d6da3942ec4cd0f49cc3a0"
        }
      ]
    }
  ]
}
