{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-client",
    "version": "3.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6",
      "buildId": "tqlvau6cqnbqnhrlx6obdna2gq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-client-3.4.2.jar",
          "url": "runelite-client-3.4.2.jar",
          "size": 2671139,
          "sha512": "63f677def180141093c6809c55a2692fd5998e57f18e4a17328978fa9b12c3527db6416d27aed66ee24f169d96b746d0d408d4980925ffc0a90635e919a26ba3",
          "sha256": "32c81ba75ba01119684826cbd79f35681b5e9343671b101f28bc0e4de41bb68a",
          "sha1": "e280e71a867e6ed7f1ed6cc29a9f75ab587c3b1a",
          "md5": "87025bb5896eaf637d454168a69c46c6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "4.2.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "guice",
              "type": "jar",
              "extension": "jar",
              "classifier": "no_aop"
            }
          }
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "1.4.200"
          }
        },
        {
          "group": "com.jakewharton.rxrelay3",
          "module": "rxrelay",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.5"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.6.0"
          }
        },
        {
          "group": "org.jgroups",
          "module": "jgroups",
          "version": {
            "requires": "4.2.4.Final"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.6.0"
          }
        },
        {
          "group": "net.runelite",
          "module": "discord",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.pushing-pixels",
          "module": "radiance-substance",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "20.0.0"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq",
          "version": {
            "requires": "3.13.3"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq-codegen",
          "version": {
            "requires": "3.13.3"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq-meta",
          "version": {
            "requires": "3.13.3"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-logback",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.github.zafarkhaja",
          "module": "java-semver",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.pf4j",
          "module": "pf4j",
          "version": {
            "requires": "3.3.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.pf4j",
          "module": "pf4j-update",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "http-api",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "org.pushing-pixels",
          "module": "radiance-trident",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injected-client",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "com.openosrs.rs",
          "module": "runescape-api",
          "version": {
            "requires": "3.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-client-3.4.2.jar",
          "url": "runelite-client-3.4.2.jar",
          "size": 2671139,
          "sha512": "63f677def180141093c6809c55a2692fd5998e57f18e4a17328978fa9b12c3527db6416d27aed66ee24f169d96b746d0d408d4980925ffc0a90635e919a26ba3",
          "sha256": "32c81ba75ba01119684826cbd79f35681b5e9343671b101f28bc0e4de41bb68a",
          "sha1": "e280e71a867e6ed7f1ed6cc29a9f75ab587c3b1a",
          "md5": "87025bb5896eaf637d454168a69c46c6"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-client-3.4.2-shaded.jar",
          "url": "runelite-client-3.4.2-shaded.jar",
          "size": 31519553,
          "sha512": "8e6ef11252c155b84bf3c450e4c6bddbb0ec6e91622748f9f2369013d16abaf8c62136891f8e84acfc58e0e0fc1002ae8c9873c1f1c30f3ce468ac5120f51a6c",
          "sha256": "2ea11e245ee64f194607174819c5f2bd61e29b845ce28b75c57611373672cab4",
          "sha1": "f9ab26c0ef4cdcadc1defcbba0e784180e2d3503",
          "md5": "8864d8ff327233dd3cf12ae7ca0df04e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-client-3.4.2-sources.jar",
          "url": "runelite-client-3.4.2-sources.jar",
          "size": 2321374,
          "sha512": "0e714005150add4ede2ea202fc85306c23fb9264b739860049691aa220ae040517386856fb368a4897015d18b5ca0ee94e316604a1a5dcec9b1f20a712c277a4",
          "sha256": "1e3ce7be5b68e278f71aefb579bc83589a775ef157762b2f2dc011b604844304",
          "sha1": "a8e7e1e7e2c6e80b6a7869cbf6856cc30758e287",
          "md5": "18c098e34021502bbc6c6d85bc79e741"
        }
      ]
    }
  ]
}
