{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "6sntp6srbfhbhitopmjtqf2rme"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.9.jar",
          "url": "http-api-3.3.9.jar",
          "size": 154402,
          "sha512": "4e52f25158599bd7a66fca71121ff353df61ab70667d498c4e1987414c542efad74ce42e85c2ac3dbbefc01aeeabb9cee8ac3690b2e886cdfbb9adc6a8d52c04",
          "sha256": "9c437aa86a341eb95cc86d8ab65c8d65054b17fcccfd0a57266d055125af182e",
          "sha1": "e281638ee3b17dd16cf9899d2caa4d6031cde4ba",
          "md5": "19c787026d447cda7fd78bf54b0d97c6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.9.jar",
          "url": "http-api-3.3.9.jar",
          "size": 154402,
          "sha512": "4e52f25158599bd7a66fca71121ff353df61ab70667d498c4e1987414c542efad74ce42e85c2ac3dbbefc01aeeabb9cee8ac3690b2e886cdfbb9adc6a8d52c04",
          "sha256": "9c437aa86a341eb95cc86d8ab65c8d65054b17fcccfd0a57266d055125af182e",
          "sha1": "e281638ee3b17dd16cf9899d2caa4d6031cde4ba",
          "md5": "19c787026d447cda7fd78bf54b0d97c6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.9-sources.jar",
          "url": "http-api-3.3.9-sources.jar",
          "size": 101953,
          "sha512": "4c68c3ab9ce96f004f25b2d2db450287db8111414422c73b1a7851ddbc827c221f989d3db7cb3567e2729f11b5964c2bb5454510fc4a2bbd12553663ef0ebe72",
          "sha256": "88b4ae64d9f02faa0a7791abf863874551ee235555114c85c13b82056779a667",
          "sha1": "1572482049a45fcaf2a975a333191630303b9007",
          "md5": "aa76d68db45754e347cf5479ea6ef127"
        }
      ]
    }
  ]
}
