{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-client",
    "version": "3.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "srmi4ril7re6lblttfwnzxsdgm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-client-3.4.1.jar",
          "url": "runelite-client-3.4.1.jar",
          "size": 2670833,
          "sha512": "794c1bbde9ec9889ef4c743fc2900a3d5c9e91574bead9235bad8cdb697ff61bd10f243b6051e85e2fdbcd3987ba61d5d82d7e75a5bf8735639722160f649aae",
          "sha256": "61c94e5ef59bb8a59ac34cbf1edb8591a32c915a56090a58bcd4d870959ab671",
          "sha1": "45f082facabd90c20d83ea4c5a0c7f5e841ab4c7",
          "md5": "648fc6e306f31c0fb230c74a142b7c68"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "4.2.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "guice",
              "type": "jar",
              "extension": "jar",
              "classifier": "no_aop"
            }
          }
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "1.4.200"
          }
        },
        {
          "group": "com.jakewharton.rxrelay3",
          "module": "rxrelay",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.6.0"
          }
        },
        {
          "group": "org.jgroups",
          "module": "jgroups",
          "version": {
            "requires": "4.2.4.Final"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.6.0"
          }
        },
        {
          "group": "net.runelite",
          "module": "discord",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.pushing-pixels",
          "module": "radiance-substance",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "19.0.0"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq",
          "version": {
            "requires": "3.13.3"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq-codegen",
          "version": {
            "requires": "3.13.3"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq-meta",
          "version": {
            "requires": "3.13.3"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-logback",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.github.zafarkhaja",
          "module": "java-semver",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.pf4j",
          "module": "pf4j",
          "version": {
            "requires": "3.3.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.pf4j",
          "module": "pf4j-update",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "http-api",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.pushing-pixels",
          "module": "radiance-trident",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injected-client",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "com.openosrs.rs",
          "module": "runescape-api",
          "version": {
            "requires": "3.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-client-3.4.1.jar",
          "url": "runelite-client-3.4.1.jar",
          "size": 2670833,
          "sha512": "794c1bbde9ec9889ef4c743fc2900a3d5c9e91574bead9235bad8cdb697ff61bd10f243b6051e85e2fdbcd3987ba61d5d82d7e75a5bf8735639722160f649aae",
          "sha256": "61c94e5ef59bb8a59ac34cbf1edb8591a32c915a56090a58bcd4d870959ab671",
          "sha1": "45f082facabd90c20d83ea4c5a0c7f5e841ab4c7",
          "md5": "648fc6e306f31c0fb230c74a142b7c68"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-client-3.4.1-shaded.jar",
          "url": "runelite-client-3.4.1-shaded.jar",
          "size": 31516508,
          "sha512": "1d9178a83817ff45f4675d92122d55b918db23d1880e7d6dcaaede3bcff5090c6f7d96a1bbd2003e50ac26a58857dee7f9570ee28277d4e6d124b38258d077e0",
          "sha256": "2cb1ca9f647e134a86cc6d41e4261dcd4866475da823e88c652730543e45e811",
          "sha1": "279bbc2d2ab4508b1bb53f0d9fe4279ee68e4d3e",
          "md5": "9173d7172525e29a17af7dd063f49664"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-client-3.4.1-sources.jar",
          "url": "runelite-client-3.4.1-sources.jar",
          "size": 2321079,
          "sha512": "909ffb1b07ef9c8d2a83b77a8d44e0b98544bc896316207741a1c35ccd3069c262202d27ce9b57674d6b9bb4420aa00f3be765918477d61c4fd0adf8ba5083c8",
          "sha256": "afb6130ddb00a0e5689096491fab8de1f196b07e5c6981397acd02b968df63ec",
          "sha1": "440a85bc1dd765d4a4a47abb8b38d9eb3a6f9054",
          "md5": "89e67b15efe6ae977ce53f8fc80f9f50"
        }
      ]
    }
  ]
}
