{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "bryaik4yyfaszg4kbqwnhgbrfq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.4.5.jar",
          "url": "http-api-3.4.5.jar",
          "size": 160252,
          "sha512": "9fa0c966bf7617ba506486e4a4955aacb8141b7347e855e4943572921bdbb1f5814a866623db527aca3ac0ea93df749d3a70f2c08d8442aeb9202b46c1d70659",
          "sha256": "c0f8690a8a7b8fa2dbdd5eec4bda96c93bb137f028907bf7e25aba50187843c2",
          "sha1": "1ad7bda3ff9ab136cdc8f4c05660c1af5d9931c1",
          "md5": "a4497a182ef9d91ffa424ba7001fa4f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.4.5"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.4.5.jar",
          "url": "http-api-3.4.5.jar",
          "size": 160252,
          "sha512": "9fa0c966bf7617ba506486e4a4955aacb8141b7347e855e4943572921bdbb1f5814a866623db527aca3ac0ea93df749d3a70f2c08d8442aeb9202b46c1d70659",
          "sha256": "c0f8690a8a7b8fa2dbdd5eec4bda96c93bb137f028907bf7e25aba50187843c2",
          "sha1": "1ad7bda3ff9ab136cdc8f4c05660c1af5d9931c1",
          "md5": "a4497a182ef9d91ffa424ba7001fa4f7"
        }
      ]
    }
  ]
}
