{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "k3ejfhuw5bhy7i3zvx6vcjtzey"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.4.5.jar",
          "url": "http-api-3.4.5.jar",
          "size": 160252,
          "sha512": "f8dd975b3325c6895f34302b5b4ec2aaf59d422e69c4385ee9d0f69d74c9309246b008cc8fe50228481099182515606d121804029f28e64ac3bec30fce3c5ec4",
          "sha256": "78f911a9b8cba04d310ffefa9dbe92128497ecf0e03cc2ada7efab31e8f80759",
          "sha1": "60860e35e10e7d801a2d86e1f9b7539046613789",
          "md5": "a4392a58b29e4ee8b6b37397e3da4235"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.4.5"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.4.5.jar",
          "url": "http-api-3.4.5.jar",
          "size": 160252,
          "sha512": "f8dd975b3325c6895f34302b5b4ec2aaf59d422e69c4385ee9d0f69d74c9309246b008cc8fe50228481099182515606d121804029f28e64ac3bec30fce3c5ec4",
          "sha256": "78f911a9b8cba04d310ffefa9dbe92128497ecf0e03cc2ada7efab31e8f80759",
          "sha1": "60860e35e10e7d801a2d86e1f9b7539046613789",
          "md5": "a4392a58b29e4ee8b6b37397e3da4235"
        }
      ]
    }
  ]
}
