{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "q7hpyrplojh25gkhin3h4p7yyq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.4.5.jar",
          "url": "http-api-3.4.5.jar",
          "size": 160251,
          "sha512": "fd89bf901b166dd05faa5d3228e505750931b4fa979975973b323f9a2ea72e5905e1a5ab7fe9090a3ea93cf0fc5dc5ddbd16b480c227d143d9148fcc4904d9b8",
          "sha256": "73553673dc21623f292032589347d8fae6748f12b91d89ee0ec5b1517d773433",
          "sha1": "f53570b749b0f34ee320be9070ecbeb34433e094",
          "md5": "acd41bf8ed83f7f14ae20baeed181c65"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.4.5"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.4.5.jar",
          "url": "http-api-3.4.5.jar",
          "size": 160251,
          "sha512": "fd89bf901b166dd05faa5d3228e505750931b4fa979975973b323f9a2ea72e5905e1a5ab7fe9090a3ea93cf0fc5dc5ddbd16b480c227d143d9148fcc4904d9b8",
          "sha256": "73553673dc21623f292032589347d8fae6748f12b91d89ee0ec5b1517d773433",
          "sha1": "f53570b749b0f34ee320be9070ecbeb34433e094",
          "md5": "acd41bf8ed83f7f14ae20baeed181c65"
        }
      ]
    }
  ]
}
