{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "f75twmv45zbnnnk6kd3v53kpem"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.5"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.5.jar",
          "url": "runescape-api-3.3.5.jar",
          "size": 103599,
          "sha512": "911c81d998b4393c34b2b2a9c95a54c6516f3829839007fb6bcdb9994236d12adb0b96f3a81fca161a44835df2ff5ed55056024d4bf10474ea97a0a804642a56",
          "sha256": "46a373d5ac27b62583895e0b8836be87f56491fead7a830534d341ed6ba2cd3c",
          "sha1": "60cc17e54cb65f3dd804017ea21c62a2eddc31f9",
          "md5": "0b1fd1cb78397bdd5f8c7f3db4fd45a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.5"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.5.jar",
          "url": "runescape-api-3.3.5.jar",
          "size": 103599,
          "sha512": "911c81d998b4393c34b2b2a9c95a54c6516f3829839007fb6bcdb9994236d12adb0b96f3a81fca161a44835df2ff5ed55056024d4bf10474ea97a0a804642a56",
          "sha256": "46a373d5ac27b62583895e0b8836be87f56491fead7a830534d341ed6ba2cd3c",
          "sha1": "60cc17e54cb65f3dd804017ea21c62a2eddc31f9",
          "md5": "0b1fd1cb78397bdd5f8c7f3db4fd45a9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.5-sources.jar",
          "url": "runescape-api-3.3.5-sources.jar",
          "size": 99711,
          "sha512": "bc3ec82d6c7c7117e4f20d96de059ff8e43ed839ccc1c24acb6e37d1b7a396950fe369a96d023fa062aadfc8c3a26256e26bbffb9205a50fff8f6bdcce0d70a4",
          "sha256": "262e98b870b3d4b3faee2ec19331227345755d83c3d6f076ec30c7650dd95b41",
          "sha1": "a690cc1ecbf235f0835e68a778f23722aa15786c",
          "md5": "8d3a7206da1e2ed6d5d3ac0f71704e83"
        }
      ]
    }
  ]
}
