{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "mrii4sqkqvf4znlodbpmkkl2ce"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.5"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.5.jar",
          "url": "runescape-api-3.3.5.jar",
          "size": 103599,
          "sha512": "888cad14b716ec2a3c484c45331e0d1f8235fa4bd8a5fed82627be1007bc0656dfdda10d3e3bf7853e74d2754c13a422435022913f9bd8796662aa186f8cf0d0",
          "sha256": "d3156edd85d9fd04ecd0d410e3da98f8c902118603bd222031b494abd6bc9b0f",
          "sha1": "4fee23819ddd89db84a680d47ebb1743799c0008",
          "md5": "ac7a2eb6a0b0fa55bbe5fd88389bc627"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.5"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.5.jar",
          "url": "runescape-api-3.3.5.jar",
          "size": 103599,
          "sha512": "888cad14b716ec2a3c484c45331e0d1f8235fa4bd8a5fed82627be1007bc0656dfdda10d3e3bf7853e74d2754c13a422435022913f9bd8796662aa186f8cf0d0",
          "sha256": "d3156edd85d9fd04ecd0d410e3da98f8c902118603bd222031b494abd6bc9b0f",
          "sha1": "4fee23819ddd89db84a680d47ebb1743799c0008",
          "md5": "ac7a2eb6a0b0fa55bbe5fd88389bc627"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.5-sources.jar",
          "url": "runescape-api-3.3.5-sources.jar",
          "size": 99711,
          "sha512": "f9ee98c24174c51aabc7575335e4e41f1eaf1196d1d0090b88fa71bfe12dca124e9cc5a6ebfaf82cda49a83af374d571f27a94c8ea33d575f6fb4ce5f4b0891e",
          "sha256": "d8854e1fd3ff314e0ead0aa2e8bb2c84a44d47ecf22975872506e7b13566a0ce",
          "sha1": "020234dbdea2b532fcbd6df5ca1c2361715c62fc",
          "md5": "1f0a414e66da5853328123aed7a7285c"
        }
      ]
    }
  ]
}
