{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "4swnroq4ujh2ddizhdj4eyybuq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.5"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.5.jar",
          "url": "runescape-api-3.3.5.jar",
          "size": 103599,
          "sha512": "341102ac9fbeea9347812e48b1ed2e9f291062e051b06543935be955cb5829a66abd45e2a23f0095063992400337d273fa5c1a0e20be078fc615fb5b70ad9be2",
          "sha256": "24c923378accd9adfc730a2e4b93f011b96a4084dd33e05b9b4738d3da7ae9d7",
          "sha1": "cf2e07b026786915e184ed3379ea17945d5bef5e",
          "md5": "af809136856991a20dd306cab86fb322"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.5"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.5.jar",
          "url": "runescape-api-3.3.5.jar",
          "size": 103599,
          "sha512": "341102ac9fbeea9347812e48b1ed2e9f291062e051b06543935be955cb5829a66abd45e2a23f0095063992400337d273fa5c1a0e20be078fc615fb5b70ad9be2",
          "sha256": "24c923378accd9adfc730a2e4b93f011b96a4084dd33e05b9b4738d3da7ae9d7",
          "sha1": "cf2e07b026786915e184ed3379ea17945d5bef5e",
          "md5": "af809136856991a20dd306cab86fb322"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.5-sources.jar",
          "url": "runescape-api-3.3.5-sources.jar",
          "size": 99711,
          "sha512": "7af17e33431196439233cb1b9b98ff52a03012e50828343be92112d4daf251c4d89baee3383c02a7e7eb5af299fad966570dee4cfdbd80e01fa2e6d97089520a",
          "sha256": "f1f34d7aec17d31c2b9825f7af2dfaa67428f569c11b7a615a8a0e3689e03ff4",
          "sha1": "01adddb937a7e682ce84b75b2fe546bd872659e6",
          "md5": "4b411e59be855066354238356e3def5f"
        }
      ]
    }
  ]
}
