{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "55edipcdszhopbkbxnururrbca"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.3.jar",
          "url": "injected-client-3.3.3.jar",
          "size": 2253448,
          "sha512": "9c73f26b25bc8e5d003feae3ba1ce8262cecdf9c5b4a8a650f51c64336e9f842cfcb244d517aa80e1224ab17474a1aee977adcb105bd1481ed1b5710ab53ce47",
          "sha256": "1e0a719f979c76da1b6e77e45c61b3749c9d6ada3bd91bdf917a0651c925ead7",
          "sha1": "3e2cea0c06993a0f0a0ca492eb3e6f52882d76b2",
          "md5": "d6a7c5b63d6012201e9981d7010afefc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.3.jar",
          "url": "injected-client-3.3.3.jar",
          "size": 2253448,
          "sha512": "9c73f26b25bc8e5d003feae3ba1ce8262cecdf9c5b4a8a650f51c64336e9f842cfcb244d517aa80e1224ab17474a1aee977adcb105bd1481ed1b5710ab53ce47",
          "sha256": "1e0a719f979c76da1b6e77e45c61b3749c9d6ada3bd91bdf917a0651c925ead7",
          "sha1": "3e2cea0c06993a0f0a0ca492eb3e6f52882d76b2",
          "md5": "d6a7c5b63d6012201e9981d7010afefc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.3-sources.jar",
          "url": "injected-client-3.3.3-sources.jar",
          "size": 261,
          "sha512": "f47725ec8bac0cbccabb9bac6bbfb85b139ece45f4157dca0d70a1fcd436253671ffe8538f3861a6656dd07a021aa10afe21af18107909f5d10bedbacba4ab85",
          "sha256": "5d0f8d7c92ea3129d814fcdeab505aedf137e086f90a3e964b5f6e102a8e17a6",
          "sha1": "fefc7020c643dbf8e0bdfd4b643c22bf1fc76a4a",
          "md5": "fd6aa28ba74836d66c737dbe3ecbb26a"
        },
        {
          "name": "injected-client-3.3.3.jar",
          "url": "injected-client-3.3.3.jar",
          "size": 2253448,
          "sha512": "9c73f26b25bc8e5d003feae3ba1ce8262cecdf9c5b4a8a650f51c64336e9f842cfcb244d517aa80e1224ab17474a1aee977adcb105bd1481ed1b5710ab53ce47",
          "sha256": "1e0a719f979c76da1b6e77e45c61b3749c9d6ada3bd91bdf917a0651c925ead7",
          "sha1": "3e2cea0c06993a0f0a0ca492eb3e6f52882d76b2",
          "md5": "d6a7c5b63d6012201e9981d7010afefc"
        }
      ]
    }
  ]
}
