{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "mfk5xstvi5a55d5dgo4g6qvpvu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.3.jar",
          "url": "injected-client-3.3.3.jar",
          "size": 2253448,
          "sha512": "90c1fcad985b8e63ff8ee9a3cb8260868a38a7d23f3caabb4d24ecceaee1fdfe065d696604acb359ebbcc376e4abfa69d2392226b92b1326d5a981b1604723fe",
          "sha256": "e48ae72c8cffe99ec968d18ac009faca01ebc84efa8fe4d8c2ff13f2afb14e1b",
          "sha1": "c47a7d61f0fcc0a05925010d8dc62157f67f3c07",
          "md5": "fcfd8081a18da74433a8072cf0b64dab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.3.jar",
          "url": "injected-client-3.3.3.jar",
          "size": 2253448,
          "sha512": "90c1fcad985b8e63ff8ee9a3cb8260868a38a7d23f3caabb4d24ecceaee1fdfe065d696604acb359ebbcc376e4abfa69d2392226b92b1326d5a981b1604723fe",
          "sha256": "e48ae72c8cffe99ec968d18ac009faca01ebc84efa8fe4d8c2ff13f2afb14e1b",
          "sha1": "c47a7d61f0fcc0a05925010d8dc62157f67f3c07",
          "md5": "fcfd8081a18da74433a8072cf0b64dab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.3-sources.jar",
          "url": "injected-client-3.3.3-sources.jar",
          "size": 261,
          "sha512": "fcc4c36ca925985ba90acd05c44c11cec413e078ce60b09ab041673b3e28ee335cd74b124e37fdee09c316943cd59acd117ea75ceceb15a903e50aa4c6513a72",
          "sha256": "02094e5d3e567ce83c948f735c3f487086ed41fdb7c66455dfd21df14c529d4a",
          "sha1": "033a99c83337ddbe6488a21249926e852b988ec3",
          "md5": "a37eecf6771c913fa4c29e5ae5e35076"
        },
        {
          "name": "injected-client-3.3.3.jar",
          "url": "injected-client-3.3.3.jar",
          "size": 2253448,
          "sha512": "90c1fcad985b8e63ff8ee9a3cb8260868a38a7d23f3caabb4d24ecceaee1fdfe065d696604acb359ebbcc376e4abfa69d2392226b92b1326d5a981b1604723fe",
          "sha256": "e48ae72c8cffe99ec968d18ac009faca01ebc84efa8fe4d8c2ff13f2afb14e1b",
          "sha1": "c47a7d61f0fcc0a05925010d8dc62157f67f3c07",
          "md5": "fcfd8081a18da74433a8072cf0b64dab"
        }
      ]
    }
  ]
}
