{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "aloehfunujhqdkgjobesvmrgci"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.3.jar",
          "url": "injected-client-3.3.3.jar",
          "size": 2253448,
          "sha512": "e1e5ee5345a866eeec481d28428fb058314e2db175ca905b0eb90e0b90cb0df4f3302e452941eb2f7f01bc0ab75b0b84a5fd648535758bd51774ff214b01e935",
          "sha256": "e34ca250a538483dd5026e8a639bf56774e372e1fd4eb577a6fa703d1fe3c881",
          "sha1": "311ab58ada0d99b29b275430e1b9ab2ebb37e3fc",
          "md5": "5f77f4a9205a66bfe510313e5af6b397"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.3.jar",
          "url": "injected-client-3.3.3.jar",
          "size": 2253448,
          "sha512": "e1e5ee5345a866eeec481d28428fb058314e2db175ca905b0eb90e0b90cb0df4f3302e452941eb2f7f01bc0ab75b0b84a5fd648535758bd51774ff214b01e935",
          "sha256": "e34ca250a538483dd5026e8a639bf56774e372e1fd4eb577a6fa703d1fe3c881",
          "sha1": "311ab58ada0d99b29b275430e1b9ab2ebb37e3fc",
          "md5": "5f77f4a9205a66bfe510313e5af6b397"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.3-sources.jar",
          "url": "injected-client-3.3.3-sources.jar",
          "size": 261,
          "sha512": "2bbbfff619c7dee3995f899acc5dc67f3e27a1c5714bc4dd027de7da44455a017bed9dadb662d90a2015167d19cd9d93b51ae5a7b7c92d4007176ce703d7e1d0",
          "sha256": "bbff9945105a9db50cce09aba14933d91b7538b810bba2f79a393d6e8799b9b2",
          "sha1": "9add5ba41a5352bd75d7922b1a807fc737da6480",
          "md5": "b88960f5390b5d4838b7f5b33407fbd1"
        },
        {
          "name": "injected-client-3.3.3.jar",
          "url": "injected-client-3.3.3.jar",
          "size": 2253448,
          "sha512": "e1e5ee5345a866eeec481d28428fb058314e2db175ca905b0eb90e0b90cb0df4f3302e452941eb2f7f01bc0ab75b0b84a5fd648535758bd51774ff214b01e935",
          "sha256": "e34ca250a538483dd5026e8a639bf56774e372e1fd4eb577a6fa703d1fe3c881",
          "sha1": "311ab58ada0d99b29b275430e1b9ab2ebb37e3fc",
          "md5": "5f77f4a9205a66bfe510313e5af6b397"
        }
      ]
    }
  ]
}
