{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "fv3xrqpvcfgmllx27r5wuy7p5q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.0.7.jar",
          "url": "http-api-3.0.7.jar",
          "size": 164353,
          "sha512": "6d961735acbb87ce6190b557eff1f65efee876dee5a097c9f473a988dce70c0e4ea3fbf374a1eb85148f39513bbb08d16cdd7a4a7b1732fa3558bfd0c3bbecdf",
          "sha256": "3253b2a087c7ee8d97d7db14c928bb882e8e40d4fe4a43a1953ddfc1397069cc",
          "sha1": "7c78476f130ce8df6494c3962340a126a2b456d1",
          "md5": "415745e88150b3345ab04d45fc282ec0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.18"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.0.7.jar",
          "url": "http-api-3.0.7.jar",
          "size": 164353,
          "sha512": "6d961735acbb87ce6190b557eff1f65efee876dee5a097c9f473a988dce70c0e4ea3fbf374a1eb85148f39513bbb08d16cdd7a4a7b1732fa3558bfd0c3bbecdf",
          "sha256": "3253b2a087c7ee8d97d7db14c928bb882e8e40d4fe4a43a1953ddfc1397069cc",
          "sha1": "7c78476f130ce8df6494c3962340a126a2b456d1",
          "md5": "415745e88150b3345ab04d45fc282ec0"
        }
      ]
    }
  ]
}
