{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "7ukznm4zhfczpkbzlvj6brvxs4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.0.7.jar",
          "url": "http-api-3.0.7.jar",
          "size": 164353,
          "sha512": "cc00584d92dd7e08e65bc70326d53c5fc56d3ccbbec29b4b00daf38ecb311f5f7ab94f6c0dfd8dcf9db739dd8eaad5a9bb5256ea73ba4bd70cccec15eaa8cf6b",
          "sha256": "fbf3f0960eaf396f9014ea7ae51382328a2e59f5f0cfb0501f2a6759c837f63c",
          "sha1": "6e55d8329ffe1fb92bb9c4798761c0ed7ea6334b",
          "md5": "04848471db9cf63245aaab06f238ad9e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.0.7.jar",
          "url": "http-api-3.0.7.jar",
          "size": 164353,
          "sha512": "cc00584d92dd7e08e65bc70326d53c5fc56d3ccbbec29b4b00daf38ecb311f5f7ab94f6c0dfd8dcf9db739dd8eaad5a9bb5256ea73ba4bd70cccec15eaa8cf6b",
          "sha256": "fbf3f0960eaf396f9014ea7ae51382328a2e59f5f0cfb0501f2a6759c837f63c",
          "sha1": "6e55d8329ffe1fb92bb9c4798761c0ed7ea6334b",
          "md5": "04848471db9cf63245aaab06f238ad9e"
        }
      ]
    }
  ]
}
