{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "pp3k6m3ejndbdak4aapjia65cm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200211.223545-2.jar",
          "size": 1158141,
          "sha512": "87321c8f1d734985cd481c86ae3f3ff7b30d9948cc88adbf3e643cd409bc20cc8cc27008091d7eaf7bb90982b2f1942222553c6bd3b0f5844a93f987f9c4ade8",
          "sha256": "4e1ba3a56d30ad01050642f7cddf21b1c7c45dce44fa4ba51280b20c73981359",
          "sha1": "02e01c5307ab5fcc7f0ac8b6d478b08f32c072d6",
          "md5": "a3e814156cc08270e96c6290e514dc36"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200211.223545-2.jar",
          "size": 1158141,
          "sha512": "87321c8f1d734985cd481c86ae3f3ff7b30d9948cc88adbf3e643cd409bc20cc8cc27008091d7eaf7bb90982b2f1942222553c6bd3b0f5844a93f987f9c4ade8",
          "sha256": "4e1ba3a56d30ad01050642f7cddf21b1c7c45dce44fa4ba51280b20c73981359",
          "sha1": "02e01c5307ab5fcc7f0ac8b6d478b08f32c072d6",
          "md5": "a3e814156cc08270e96c6290e514dc36"
        }
      ]
    }
  ]
}
