{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "oz3lwfovprdh7luxs6u2rzfbu4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200206.153326-1.jar",
          "size": 1150996,
          "sha512": "cbd44a3d80324d5723d8bfb96b0a6a5208f0ed794dbd5fd9093f04b292baeee80db7f73e5aba1924153f6ea70848861da154706d19132344cce1496b10073d5c",
          "sha256": "86795d1f34cac2666b4aebe201a33b76db3eef3f5bca8aa3b2bca0bb1436df8f",
          "sha1": "70b9e1299787f4b019ecdb06e6e6e83d921982b6",
          "md5": "9bd0bd85ce6d3a23274d2d3ecc37f37f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200206.153326-1.jar",
          "size": 1150996,
          "sha512": "cbd44a3d80324d5723d8bfb96b0a6a5208f0ed794dbd5fd9093f04b292baeee80db7f73e5aba1924153f6ea70848861da154706d19132344cce1496b10073d5c",
          "sha256": "86795d1f34cac2666b4aebe201a33b76db3eef3f5bca8aa3b2bca0bb1436df8f",
          "sha1": "70b9e1299787f4b019ecdb06e6e6e83d921982b6",
          "md5": "9bd0bd85ce6d3a23274d2d3ecc37f37f"
        }
      ]
    }
  ]
}
