{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "3qpvhxgiundehbuaqfk6rluivi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200129.160401-2.jar",
          "size": 1150995,
          "sha512": "c0658f57e7586420a0eb5ff6840930058a40f2ec4c2ec9de7fc3cbfad423dba26edfb731abe52c2facc6927114ce94bf4d803a4be23337b21769074b3f1f522d",
          "sha256": "5960906128b17e13a3e683b7607cda5e8c44d208b2dce1b81a3ced34a4ecd4bb",
          "sha1": "5aa88fec10a008c1e7416e00037023b1d9cd30fe",
          "md5": "1818c7c0c87e7fd945d5b76380b46ce8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200129.160401-2.jar",
          "size": 1150995,
          "sha512": "c0658f57e7586420a0eb5ff6840930058a40f2ec4c2ec9de7fc3cbfad423dba26edfb731abe52c2facc6927114ce94bf4d803a4be23337b21769074b3f1f522d",
          "sha256": "5960906128b17e13a3e683b7607cda5e8c44d208b2dce1b81a3ced34a4ecd4bb",
          "sha1": "5aa88fec10a008c1e7416e00037023b1d9cd30fe",
          "md5": "1818c7c0c87e7fd945d5b76380b46ce8"
        }
      ]
    }
  ]
}
