{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "js2kzdyeknhqjf3rb7kpu63z4m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200211.195718-2.jar",
          "size": 1158141,
          "sha512": "a3581e598878e7691356fba4d5ad880ad2575738790bd97b14c715b4bcbfd14dc174da6a2fa190a929fecc0f6d5172c49d4e8e7b15046036cfb12455a1d0c2a3",
          "sha256": "5fcd3981f4ca4adee3a14cff285ef22ee040203ab051a4eabb0ccb1c8510da3f",
          "sha1": "5f8ab31d1c2bbc71fab02378eef37ce34121d2d9",
          "md5": "299a08922f38361de02cea7925778ddb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200211.195718-2.jar",
          "size": 1158141,
          "sha512": "a3581e598878e7691356fba4d5ad880ad2575738790bd97b14c715b4bcbfd14dc174da6a2fa190a929fecc0f6d5172c49d4e8e7b15046036cfb12455a1d0c2a3",
          "sha256": "5fcd3981f4ca4adee3a14cff285ef22ee040203ab051a4eabb0ccb1c8510da3f",
          "sha1": "5f8ab31d1c2bbc71fab02378eef37ce34121d2d9",
          "md5": "299a08922f38361de02cea7925778ddb"
        }
      ]
    }
  ]
}
