{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "itp6lcfjerbo3iypov5gknjsz4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200209.132813-2.jar",
          "size": 1156074,
          "sha512": "33e94a90d89807720a76682b8c63529c661f4d3209b71e30827a6bafedda954dc8e5a82ffc73652e22b7bb94fd7e690bbc4a7ad4e78873b70d8e5a88f4f90eff",
          "sha256": "7c1f3105fcda6819301385be15401da3f6c66387acff1d1d734be323f730fee4",
          "sha1": "f24a0a68d873a8799a12e408242480924d763006",
          "md5": "55050f9ae431253277c77aad1f156490"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200209.132813-2.jar",
          "size": 1156074,
          "sha512": "33e94a90d89807720a76682b8c63529c661f4d3209b71e30827a6bafedda954dc8e5a82ffc73652e22b7bb94fd7e690bbc4a7ad4e78873b70d8e5a88f4f90eff",
          "sha256": "7c1f3105fcda6819301385be15401da3f6c66387acff1d1d734be323f730fee4",
          "sha1": "f24a0a68d873a8799a12e408242480924d763006",
          "md5": "55050f9ae431253277c77aad1f156490"
        }
      ]
    }
  ]
}
