{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "2srzxppmvjc5vd43bqta6w4bpi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200209.161919-2.jar",
          "size": 1156074,
          "sha512": "5a2ffe38a342861aeb2b27579a347802060b10b5c5d820c2ec98dddf4958b2447bf4859c6ca01900175373f4982abf06b07aba04d2c348d6aa9d2acbad29f8e1",
          "sha256": "66682d5ed37158e4ee3b6bc6a6dc56220d1001898f616160c50cca5dec94a02f",
          "sha1": "28b968832ca49744a35e90d2a35b139c927e18f8",
          "md5": "cad59586755cb98c5ee015cb965633e0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.6-SNAPSHOT.jar",
          "url": "runelite-api-1.6.6-20200209.161919-2.jar",
          "size": 1156074,
          "sha512": "5a2ffe38a342861aeb2b27579a347802060b10b5c5d820c2ec98dddf4958b2447bf4859c6ca01900175373f4982abf06b07aba04d2c348d6aa9d2acbad29f8e1",
          "sha256": "66682d5ed37158e4ee3b6bc6a6dc56220d1001898f616160c50cca5dec94a02f",
          "sha1": "28b968832ca49744a35e90d2a35b139c927e18f8",
          "md5": "cad59586755cb98c5ee015cb965633e0"
        }
      ]
    }
  ]
}
