{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "rb5yuoxqkreankmnlkb74x3pse"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6.jar",
          "url": "runescape-api-1.6.6.jar",
          "size": 55272,
          "sha512": "a72b4f5b990d9f4e0bb84073ba02780db016aeb1897cbe83e87fb78503c381d60a2c8caed64016c9b82470985dfc9394f8343dcdd85e5324dfdad4103c7a246d",
          "sha256": "2b36c06b2cab102493b50eaf8594b4e1100241192ed200434342bbf93a467062",
          "sha1": "f55916216c9150524af3b94beb12814bf88200db",
          "md5": "b6943062a92fab3bc26fcdbc6309083c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6.jar",
          "url": "runescape-api-1.6.6.jar",
          "size": 55272,
          "sha512": "a72b4f5b990d9f4e0bb84073ba02780db016aeb1897cbe83e87fb78503c381d60a2c8caed64016c9b82470985dfc9394f8343dcdd85e5324dfdad4103c7a246d",
          "sha256": "2b36c06b2cab102493b50eaf8594b4e1100241192ed200434342bbf93a467062",
          "sha1": "f55916216c9150524af3b94beb12814bf88200db",
          "md5": "b6943062a92fab3bc26fcdbc6309083c"
        }
      ]
    }
  ]
}
