{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "ppkx2vnvobgtpgb7auzjikr6sa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6.jar",
          "url": "runescape-api-1.6.6.jar",
          "size": 55272,
          "sha512": "4800f5b59b22282b53785e41ee1e6fadc2041ef9ba79d191fb337add149ad886e9a26fb2e283a7abac08405646ae97b36278913f9dafe6c3c6d79fb5fbdc692f",
          "sha256": "aec6d655152224f5de4d6602d8fba95a1b4d141734348d554ab8acf18354a8a1",
          "sha1": "a72f6db4563afa6e45a73b82fea5f1387fa8f3ac",
          "md5": "d0f83af8d71e597c6f45bb44ae550a11"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6.jar",
          "url": "runescape-api-1.6.6.jar",
          "size": 55272,
          "sha512": "4800f5b59b22282b53785e41ee1e6fadc2041ef9ba79d191fb337add149ad886e9a26fb2e283a7abac08405646ae97b36278913f9dafe6c3c6d79fb5fbdc692f",
          "sha256": "aec6d655152224f5de4d6602d8fba95a1b4d141734348d554ab8acf18354a8a1",
          "sha1": "a72f6db4563afa6e45a73b82fea5f1387fa8f3ac",
          "md5": "d0f83af8d71e597c6f45bb44ae550a11"
        }
      ]
    }
  ]
}
