{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "mxqmrkkdnbgnfb6zeqgj7nbolm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.3-SNAPSHOT.jar",
          "url": "injected-client-1.6.3-20200118.234138-1.jar",
          "size": 2224272,
          "sha512": "ff883abbc2cbbda8cad10ba5792c7ce5bd997392a25ddb60b35239d9d7a4a510ec5dd03db26ead9289cb6f4ad61aa3b56cf8a77cbab74b963cf9ffa0930568f6",
          "sha256": "9fe3a542bb7993036d45326d7d9b8650da25f5aa86a78c7d9c080a1a805f361e",
          "sha1": "67ef9e61b8a58161a0481b175e104644e1f08335",
          "md5": "d092d5984cffb6d142c62bbe4a5ad98f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.3-SNAPSHOT.jar",
          "url": "injected-client-1.6.3-20200118.234138-1.jar",
          "size": 2224272,
          "sha512": "ff883abbc2cbbda8cad10ba5792c7ce5bd997392a25ddb60b35239d9d7a4a510ec5dd03db26ead9289cb6f4ad61aa3b56cf8a77cbab74b963cf9ffa0930568f6",
          "sha256": "9fe3a542bb7993036d45326d7d9b8650da25f5aa86a78c7d9c080a1a805f361e",
          "sha1": "67ef9e61b8a58161a0481b175e104644e1f08335",
          "md5": "d092d5984cffb6d142c62bbe4a5ad98f"
        }
      ]
    }
  ]
}
