{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "ufew7df6zfbltauic36ac6yszy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.3-SNAPSHOT.jar",
          "url": "injected-client-1.6.3-20200119.000859-1.jar",
          "size": 2224272,
          "sha512": "8cb577e990d7ed7f32be76f82712c4b3593fd43a107449a557607a61ebb972803e78fd281b6d85f757dac225fffcfb79fffbbcd84f0458c972a69ef329228f9f",
          "sha256": "531b966a36ad11c7c75190585d67d3ddb4ecf4b040c9e6c3e754e1cf20029f2b",
          "sha1": "b6a81675a2866270081dc20b3ee949378f446430",
          "md5": "7938166a1bc5720b1aabf78be4071d6f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.3-SNAPSHOT.jar",
          "url": "injected-client-1.6.3-20200119.000859-1.jar",
          "size": 2224272,
          "sha512": "8cb577e990d7ed7f32be76f82712c4b3593fd43a107449a557607a61ebb972803e78fd281b6d85f757dac225fffcfb79fffbbcd84f0458c972a69ef329228f9f",
          "sha256": "531b966a36ad11c7c75190585d67d3ddb4ecf4b040c9e6c3e754e1cf20029f2b",
          "sha1": "b6a81675a2866270081dc20b3ee949378f446430",
          "md5": "7938166a1bc5720b1aabf78be4071d6f"
        }
      ]
    }
  ]
}
