{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "lga66gpwabbedon5gdqb3bsigi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.3-SNAPSHOT.jar",
          "url": "injected-client-1.6.3-20200123.001038-1.jar",
          "size": 2224423,
          "sha512": "268e812b7f6e53d4fc0df049f7236b2198fb02ba12e9c5ce74887ac9950f8f033e9ecf0995238cab0d8a8a030c5acbfbf778375e515f97e74502332f35c9edb9",
          "sha256": "f6d15eb5a59666d711167f31f50e7b750c3751aac36a4d46b12e1745482c5063",
          "sha1": "e0bada28ec1365457b78ea22e1b6f9c447570527",
          "md5": "e92033ab3a5b369dde9d72a1284c7256"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.3-SNAPSHOT.jar",
          "url": "injected-client-1.6.3-20200123.001038-1.jar",
          "size": 2224423,
          "sha512": "268e812b7f6e53d4fc0df049f7236b2198fb02ba12e9c5ce74887ac9950f8f033e9ecf0995238cab0d8a8a030c5acbfbf778375e515f97e74502332f35c9edb9",
          "sha256": "f6d15eb5a59666d711167f31f50e7b750c3751aac36a4d46b12e1745482c5063",
          "sha1": "e0bada28ec1365457b78ea22e1b6f9c447570527",
          "md5": "e92033ab3a5b369dde9d72a1284c7256"
        }
      ]
    }
  ]
}
