{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "2yty7ku6y5hslg3tf45hxegi6m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.3-SNAPSHOT.jar",
          "url": "injected-client-1.6.3-20200121.000800-1.jar",
          "size": 2224272,
          "sha512": "25ab0b9d72cfa8f2a98fc3fb29f3e55afbec2ff4c150f8a851363256ba36c59b2e48de4dce38ff476a5388b3a521077a542b9557524312005f411825d06afe5d",
          "sha256": "a8559d46a63fc3c10cd06516b865a360f3f25d2c5ec8245733d5eb7b01c2a02d",
          "sha1": "aa6ab24d261a73032655891ee003141d9e1a64da",
          "md5": "0c074f01434f337020b14832e011bfec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.3-SNAPSHOT.jar",
          "url": "injected-client-1.6.3-20200121.000800-1.jar",
          "size": 2224272,
          "sha512": "25ab0b9d72cfa8f2a98fc3fb29f3e55afbec2ff4c150f8a851363256ba36c59b2e48de4dce38ff476a5388b3a521077a542b9557524312005f411825d06afe5d",
          "sha256": "a8559d46a63fc3c10cd06516b865a360f3f25d2c5ec8245733d5eb7b01c2a02d",
          "sha1": "aa6ab24d261a73032655891ee003141d9e1a64da",
          "md5": "0c074f01434f337020b14832e011bfec"
        }
      ]
    }
  ]
}
