{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "2fhut63265gafekzrs4jxj42wa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.3-SNAPSHOT.jar",
          "url": "injected-client-1.6.3-20200121.051328-1.jar",
          "size": 2224423,
          "sha512": "8f0ca9278253f0a298a5f32167623b84c8526417c74e80511b4c446f5eebd0975252829c7e196e4496caff3c0595397599bb62537fb536d00867b50dcbaa53bf",
          "sha256": "e4643376b1a7599d6227e05aa192e38841e1de46d81e734337eaf390089e05b5",
          "sha1": "94b2a309134de9bf11a0b901b439305f7f7ece68",
          "md5": "47afd1c80e646704f4d00f0dfa7d2719"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.3-SNAPSHOT.jar",
          "url": "injected-client-1.6.3-20200121.051328-1.jar",
          "size": 2224423,
          "sha512": "8f0ca9278253f0a298a5f32167623b84c8526417c74e80511b4c446f5eebd0975252829c7e196e4496caff3c0595397599bb62537fb536d00867b50dcbaa53bf",
          "sha256": "e4643376b1a7599d6227e05aa192e38841e1de46d81e734337eaf390089e05b5",
          "sha1": "94b2a309134de9bf11a0b901b439305f7f7ece68",
          "md5": "47afd1c80e646704f4d00f0dfa7d2719"
        }
      ]
    }
  ]
}
