{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "t5j3pwdnrbdafejetpgfjj6hpi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.3-SNAPSHOT.jar",
          "url": "injected-client-1.6.3-20200122.000949-1.jar",
          "size": 2224423,
          "sha512": "02377985f2f87709f8d405264f06338265a49ac2cca270e793e989645d4f78f424a3887fbd8fbc2949d2c093f98cf490643d28890660e19fd43f0f2cf999af52",
          "sha256": "5357e48b1dda5b6490d57bfe04791247deab4966875d707f4d10e62d6b26ab2c",
          "sha1": "b8e73c25dbec5534ceaa77c96ac87a0b40305337",
          "md5": "8217a42ba180d2882cdb2b49f1f0b155"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.3-SNAPSHOT.jar",
          "url": "injected-client-1.6.3-20200122.000949-1.jar",
          "size": 2224423,
          "sha512": "02377985f2f87709f8d405264f06338265a49ac2cca270e793e989645d4f78f424a3887fbd8fbc2949d2c093f98cf490643d28890660e19fd43f0f2cf999af52",
          "sha256": "5357e48b1dda5b6490d57bfe04791247deab4966875d707f4d10e62d6b26ab2c",
          "sha1": "b8e73c25dbec5534ceaa77c96ac87a0b40305337",
          "md5": "8217a42ba180d2882cdb2b49f1f0b155"
        }
      ]
    }
  ]
}
