{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "wmngsrqetvec7fu4qokwhdtmta"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.2.0.jar",
          "url": "runescape-api-3.2.0.jar",
          "size": 55416,
          "sha512": "62b199d5096cbb507da262a7bcdd0b13136a57edcaebf5e641f34e52fcc78d6010d1865ba86073770b4e1325fd7dbc2972faa9bac893289693b841fab78fe6f2",
          "sha256": "69f6332a7e75feaa57bae1f0701a991b9fb392bbf70bc4303d4a084c927d0b4b",
          "sha1": "738022844195731b22849f9f29349cdab1c25d13",
          "md5": "51e31641062b5d51505e525736fcbfdc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.2.0.jar",
          "url": "runescape-api-3.2.0.jar",
          "size": 55416,
          "sha512": "62b199d5096cbb507da262a7bcdd0b13136a57edcaebf5e641f34e52fcc78d6010d1865ba86073770b4e1325fd7dbc2972faa9bac893289693b841fab78fe6f2",
          "sha256": "69f6332a7e75feaa57bae1f0701a991b9fb392bbf70bc4303d4a084c927d0b4b",
          "sha1": "738022844195731b22849f9f29349cdab1c25d13",
          "md5": "51e31641062b5d51505e525736fcbfdc"
        }
      ]
    }
  ]
}
