{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-client",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "hhq4bwszdzgufg5vd4wehrymiy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-client-1.6.3-SNAPSHOT.jar",
          "url": "runelite-client-1.6.3-20200118.223016-2.jar",
          "size": 9488489,
          "sha512": "332eda27ff209c0802b54993a06649c8c747438234a6cfe79c9de0c28cd1e52f4313ce3648568db2de879d29bd293baa02ecdec9b2f457cad95200e6788c9b57",
          "sha256": "9539ab3f945d2870ddb615c8355b7abd723705338edab92234f5bdd6f16f7fc7",
          "sha1": "cee2ad3140b77d4fa9213bcd432add7b618a0766",
          "md5": "a6577659258d6537acc4a86afd12471e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "4.2.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "guice",
              "type": "jar",
              "extension": "jar",
              "classifier": "no_aop"
            }
          }
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "1.4.200"
          }
        },
        {
          "group": "com.jakewharton.rxrelay2",
          "module": "rxrelay",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "net.runelite",
          "module": "discord",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "org.pushing-pixels",
          "module": "radiance-substance",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.codehaus.plexus",
          "module": "plexus-utils",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "18.0.0"
          }
        },
        {
          "group": "org.jogamp.gluegen",
          "module": "gluegen-rt",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.jogamp.jogl",
          "module": "jogl-all",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq",
          "version": {
            "requires": "3.12.3"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq-codegen",
          "version": {
            "requires": "3.12.3"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq-meta",
          "version": {
            "requires": "3.12.3"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry",
          "version": {
            "requires": "1.7.29"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "http-api",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "com.github.joonasvali.naturalmouse",
          "module": "naturalmouse",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "org.pushing-pixels",
          "module": "radiance-trident",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "org.jogamp.gluegen",
          "module": "gluegen-rt",
          "version": {
            "requires": "2.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gluegen-rt",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux-amd64"
            }
          }
        },
        {
          "group": "org.jogamp.gluegen",
          "module": "gluegen-rt",
          "version": {
            "requires": "2.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gluegen-rt",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux-i586"
            }
          }
        },
        {
          "group": "org.jogamp.gluegen",
          "module": "gluegen-rt",
          "version": {
            "requires": "2.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gluegen-rt",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-amd64"
            }
          }
        },
        {
          "group": "org.jogamp.gluegen",
          "module": "gluegen-rt",
          "version": {
            "requires": "2.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gluegen-rt",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-i586"
            }
          }
        },
        {
          "group": "org.jogamp.jogl",
          "module": "jogl-all",
          "version": {
            "requires": "2.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jogl-all",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux-amd64"
            }
          }
        },
        {
          "group": "org.jogamp.jogl",
          "module": "jogl-all",
          "version": {
            "requires": "2.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jogl-all",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux-i586"
            }
          }
        },
        {
          "group": "org.jogamp.jogl",
          "module": "jogl-all",
          "version": {
            "requires": "2.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jogl-all",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-amd64"
            }
          }
        },
        {
          "group": "org.jogamp.jogl",
          "module": "jogl-all",
          "version": {
            "requires": "2.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jogl-all",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-i586"
            }
          }
        },
        {
          "group": "com.openosrs",
          "module": "injected-client",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs.rs",
          "module": "runescape-api",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-client-1.6.3-SNAPSHOT.jar",
          "url": "runelite-client-1.6.3-20200118.223016-2.jar",
          "size": 9488489,
          "sha512": "332eda27ff209c0802b54993a06649c8c747438234a6cfe79c9de0c28cd1e52f4313ce3648568db2de879d29bd293baa02ecdec9b2f457cad95200e6788c9b57",
          "sha256": "9539ab3f945d2870ddb615c8355b7abd723705338edab92234f5bdd6f16f7fc7",
          "sha1": "cee2ad3140b77d4fa9213bcd432add7b618a0766",
          "md5": "a6577659258d6537acc4a86afd12471e"
        }
      ]
    }
  ]
}
