{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "b54trkceujcplpatavyavejajq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.8.jar",
          "url": "http-api-1.6.8.jar",
          "size": 165949,
          "sha512": "0768d69afeeca144d79da13017e5153a8b28350db5391fbd47f270747025759c2d2f313c0377680ee319599eff629759b73c6e5ce2babd6f95cf38765db2052b",
          "sha256": "870e56d378bc3dc8a409e34b067fc903888fc165f2e98ffaacb55ab34734b2fb",
          "sha1": "a4db846ccef6e4019030c3550381158c6dfe6d11",
          "md5": "0d2a844df1df08610ada7fc547b2ce4b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.8"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.8.jar",
          "url": "http-api-1.6.8.jar",
          "size": 165949,
          "sha512": "0768d69afeeca144d79da13017e5153a8b28350db5391fbd47f270747025759c2d2f313c0377680ee319599eff629759b73c6e5ce2babd6f95cf38765db2052b",
          "sha256": "870e56d378bc3dc8a409e34b067fc903888fc165f2e98ffaacb55ab34734b2fb",
          "sha1": "a4db846ccef6e4019030c3550381158c6dfe6d11",
          "md5": "0d2a844df1df08610ada7fc547b2ce4b"
        }
      ]
    }
  ]
}
