{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "eaynwhnouvaevdq6mvhcf54z3q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.8.jar",
          "url": "http-api-1.6.8.jar",
          "size": 164353,
          "sha512": "5c1a1be66399d317dc45b422218856769d8dab726becb129d2ac02065bc418afe303e61e675ca331fba49b12c4da21c6dc03b7de92e569a44b54c2adfad8462d",
          "sha256": "1bf5d59b2f34bfb49b941d65b385cf61547debefcedf28df180052de6ecd9bf8",
          "sha1": "29d3b764ff919840ab160a05b83b4946658a0164",
          "md5": "449ba5b67bcc26b29024df0ae9df23c6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.8"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.8.jar",
          "url": "http-api-1.6.8.jar",
          "size": 164353,
          "sha512": "5c1a1be66399d317dc45b422218856769d8dab726becb129d2ac02065bc418afe303e61e675ca331fba49b12c4da21c6dc03b7de92e569a44b54c2adfad8462d",
          "sha256": "1bf5d59b2f34bfb49b941d65b385cf61547debefcedf28df180052de6ecd9bf8",
          "sha1": "29d3b764ff919840ab160a05b83b4946658a0164",
          "md5": "449ba5b67bcc26b29024df0ae9df23c6"
        }
      ]
    }
  ]
}
