{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "nwxp4meh3rdphjhygrzpkfs7wq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.8.jar",
          "url": "http-api-1.6.8.jar",
          "size": 165947,
          "sha512": "e0b6a0c0f699a5d44a80aec618efcbce9491f2fe5a921387e000490dd847126fb8e72685f32870aa5dc61aff730571d4d13b7d0c8594944941ea3fc113a92512",
          "sha256": "2b71e80aa10221ec7eebc28d0215fc8a2bd80585ba9f03938ad5fc3f262baa6d",
          "sha1": "46bbdf8188538ca3e880d086364474d7832ea918",
          "md5": "14660f1e6445dc5b1775b9ee969bd506"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.8"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.8.jar",
          "url": "http-api-1.6.8.jar",
          "size": 165947,
          "sha512": "e0b6a0c0f699a5d44a80aec618efcbce9491f2fe5a921387e000490dd847126fb8e72685f32870aa5dc61aff730571d4d13b7d0c8594944941ea3fc113a92512",
          "sha256": "2b71e80aa10221ec7eebc28d0215fc8a2bd80585ba9f03938ad5fc3f262baa6d",
          "sha1": "46bbdf8188538ca3e880d086364474d7832ea918",
          "md5": "14660f1e6445dc5b1775b9ee969bd506"
        }
      ]
    }
  ]
}
