{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "buamwedoajf75nbo7b7edzci3y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.4.4.jar",
          "url": "runelite-api-3.4.4.jar",
          "size": 1231029,
          "sha512": "c328235be77e65a383f55c7294293083e243bf4976862d47412909206a0b2060ea3fc501566fbeb0e982d6fba30a46fc208d9020b94b469795581394bdc6b202",
          "sha256": "68cb296837dabc55e8b055fc7970d6331e1e0940b47205cf79d08afd23d66432",
          "sha1": "d56580b509a238e0557f80d4cb9990cce25c186d",
          "md5": "4a2acf444aab8bc9f220f45cbb08b309"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.4.4.jar",
          "url": "runelite-api-3.4.4.jar",
          "size": 1231029,
          "sha512": "c328235be77e65a383f55c7294293083e243bf4976862d47412909206a0b2060ea3fc501566fbeb0e982d6fba30a46fc208d9020b94b469795581394bdc6b202",
          "sha256": "68cb296837dabc55e8b055fc7970d6331e1e0940b47205cf79d08afd23d66432",
          "sha1": "d56580b509a238e0557f80d4cb9990cce25c186d",
          "md5": "4a2acf444aab8bc9f220f45cbb08b309"
        }
      ]
    }
  ]
}
