{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "w4x3dpanbvfoxnwiwpx244sqz4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.4.4.jar",
          "url": "runelite-api-3.4.4.jar",
          "size": 1230925,
          "sha512": "98e685b598fd066187c502644f0e1ae0a726adf99b8665c56a357dbe33fbb48685540f06d055786c2fd12ec2aee98da8f1d4efeae1a2217b30af3b48ab43be98",
          "sha256": "09243bac3380a881018125ee68d6174f04775f6a9ff437f79c88772737167ead",
          "sha1": "eee84729f68986849f8e9ba9213947312c0af2a2",
          "md5": "00b522b0ba7f5752fdb63b6a803c5077"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.4.4.jar",
          "url": "runelite-api-3.4.4.jar",
          "size": 1230925,
          "sha512": "98e685b598fd066187c502644f0e1ae0a726adf99b8665c56a357dbe33fbb48685540f06d055786c2fd12ec2aee98da8f1d4efeae1a2217b30af3b48ab43be98",
          "sha256": "09243bac3380a881018125ee68d6174f04775f6a9ff437f79c88772737167ead",
          "sha1": "eee84729f68986849f8e9ba9213947312c0af2a2",
          "md5": "00b522b0ba7f5752fdb63b6a803c5077"
        }
      ]
    }
  ]
}
