{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "u6wfpfh6wvhx7dap7ixr34i6ti"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.4.4.jar",
          "url": "runelite-api-3.4.4.jar",
          "size": 1231187,
          "sha512": "a3f4f9ff7721f0005edd55a1ce1ae21dd7990de42daf303dbcd4b3e6e80ea53467e4c7c6aba46c42cb43742471fbf1acdbd626fbd77fc2d2fe7515be7fb9618d",
          "sha256": "8dc8f337d149bba86545ff2dc5229802a248a183267f7b0ea887996657fb1e82",
          "sha1": "ff1235dadc987c2a107d16931bd40a33b306b1c5",
          "md5": "329f1a4aebf2cb8b75120b6415b5ee5d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.4.4.jar",
          "url": "runelite-api-3.4.4.jar",
          "size": 1231187,
          "sha512": "a3f4f9ff7721f0005edd55a1ce1ae21dd7990de42daf303dbcd4b3e6e80ea53467e4c7c6aba46c42cb43742471fbf1acdbd626fbd77fc2d2fe7515be7fb9618d",
          "sha256": "8dc8f337d149bba86545ff2dc5229802a248a183267f7b0ea887996657fb1e82",
          "sha1": "ff1235dadc987c2a107d16931bd40a33b306b1c5",
          "md5": "329f1a4aebf2cb8b75120b6415b5ee5d"
        }
      ]
    }
  ]
}
