{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "wearss7mlrhafjozjlmzxt6adm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.4.jar",
          "url": "runescape-api-1.6.4.jar",
          "size": 55242,
          "sha512": "8f46ece2ed3d7151df0c7d0260b9b00331f8335c8b3af4b8a5eb47890b18b100cfe3fe19a2db60dc5536bdab8a97540fd7e576b1f4175f4a5833acae8a1b295b",
          "sha256": "da67cfbe3859e4d5034d425d4aaff308e49cfbb90e4369fd86a3013edb23fac0",
          "sha1": "b8e3d9406a7b31bf8b6a256fee82faf96a9e1e7e",
          "md5": "94d4d6ba19ddaf2d45718aa9d8d2f577"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.4.jar",
          "url": "runescape-api-1.6.4.jar",
          "size": 55242,
          "sha512": "8f46ece2ed3d7151df0c7d0260b9b00331f8335c8b3af4b8a5eb47890b18b100cfe3fe19a2db60dc5536bdab8a97540fd7e576b1f4175f4a5833acae8a1b295b",
          "sha256": "da67cfbe3859e4d5034d425d4aaff308e49cfbb90e4369fd86a3013edb23fac0",
          "sha1": "b8e3d9406a7b31bf8b6a256fee82faf96a9e1e7e",
          "md5": "94d4d6ba19ddaf2d45718aa9d8d2f577"
        }
      ]
    }
  ]
}
