{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "zwbdy6ivf5ampkvubyr2ohfu4y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.2.2.jar",
          "url": "runescape-api-3.2.2.jar",
          "size": 103418,
          "sha512": "9afb37e2801d9bf1ba7b9651ea1b947c336d881413b870a21331c14427dd4565ca3bdfb062051294b5a793d98058a8129dd8a7e257b60145777808517ba4c47c",
          "sha256": "f73226183908f900de4fa365e6ff9a223f760fdf29d10f45f4d53a188c8991ff",
          "sha1": "23480313ab1a9792b11f0e9350fe452ae6cfa2ed",
          "md5": "e8dc17b561086a19fbc16742d3f0fab0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.2.2.jar",
          "url": "runescape-api-3.2.2.jar",
          "size": 103418,
          "sha512": "9afb37e2801d9bf1ba7b9651ea1b947c336d881413b870a21331c14427dd4565ca3bdfb062051294b5a793d98058a8129dd8a7e257b60145777808517ba4c47c",
          "sha256": "f73226183908f900de4fa365e6ff9a223f760fdf29d10f45f4d53a188c8991ff",
          "sha1": "23480313ab1a9792b11f0e9350fe452ae6cfa2ed",
          "md5": "e8dc17b561086a19fbc16742d3f0fab0"
        }
      ]
    }
  ]
}
