{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "eozc5css2rdz5fb6c4fkiwagdq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.2.2.jar",
          "url": "runescape-api-3.2.2.jar",
          "size": 103418,
          "sha512": "4ef24f215f4eb71f356d054d05037cba1c7ca60a7691b913493e52539cf90f8709b40e56e0e507c5d1c379ea7f5002684b8066fd2b5b681098af7f1b474ad62a",
          "sha256": "2ccf56e8cbe77d3e5a76a2a9ce1e4fd71424d2e8cc9037126f077ce9090f6f2b",
          "sha1": "11d9e033a21f817d5aa3a2f9631ca3035e855e84",
          "md5": "85a2d0d62bb8215aef37dcef548798ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.2.2.jar",
          "url": "runescape-api-3.2.2.jar",
          "size": 103418,
          "sha512": "4ef24f215f4eb71f356d054d05037cba1c7ca60a7691b913493e52539cf90f8709b40e56e0e507c5d1c379ea7f5002684b8066fd2b5b681098af7f1b474ad62a",
          "sha256": "2ccf56e8cbe77d3e5a76a2a9ce1e4fd71424d2e8cc9037126f077ce9090f6f2b",
          "sha1": "11d9e033a21f817d5aa3a2f9631ca3035e855e84",
          "md5": "85a2d0d62bb8215aef37dcef548798ca"
        }
      ]
    }
  ]
}
