{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "da4xdde4szdydcjqpr3r7otnky"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.2.2.jar",
          "url": "runescape-api-3.2.2.jar",
          "size": 103418,
          "sha512": "4be8a91c870ce782c49a492daa01bef072f94a0bcd13cd7eb65776f3c08e8b008ec4d32b77a0a4cc0d8167525d03fe2ff55fe6c6400b3a7a545183d47f25e841",
          "sha256": "8b1fddb47515674c48f6537254d961a362371cc76abb0625c5b1035c9dedf947",
          "sha1": "2a787f8bd58728d6d4934dc1f461432b7151b972",
          "md5": "c9645957a7123d5d72556a954fae7264"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.2.2.jar",
          "url": "runescape-api-3.2.2.jar",
          "size": 103418,
          "sha512": "4be8a91c870ce782c49a492daa01bef072f94a0bcd13cd7eb65776f3c08e8b008ec4d32b77a0a4cc0d8167525d03fe2ff55fe6c6400b3a7a545183d47f25e841",
          "sha256": "8b1fddb47515674c48f6537254d961a362371cc76abb0625c5b1035c9dedf947",
          "sha1": "2a787f8bd58728d6d4934dc1f461432b7151b972",
          "md5": "c9645957a7123d5d72556a954fae7264"
        }
      ]
    }
  ]
}
