{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "saelj43s6fcoxplalp5fo6j5xa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.7.jar",
          "url": "runelite-api-1.6.7.jar",
          "size": 1160630,
          "sha512": "824bf268f009ae6837ee6c4dbc63e6a940f3411317fc0fd4d1bfa82ea040cecde55ffa69519fcdf041b9d52fe43a3a96e08df33a3a6a5b1b61d2f22e3a27c210",
          "sha256": "f234cc53eb518e3b126489f4f68ddf1eeff75689355ae8143294cc5e27a92db2",
          "sha1": "a71dcc05df23e30475ad32de5035d1d79a71ddb7",
          "md5": "e7e46017409d652c9ad3efbe2cf8507e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.7.jar",
          "url": "runelite-api-1.6.7.jar",
          "size": 1160630,
          "sha512": "824bf268f009ae6837ee6c4dbc63e6a940f3411317fc0fd4d1bfa82ea040cecde55ffa69519fcdf041b9d52fe43a3a96e08df33a3a6a5b1b61d2f22e3a27c210",
          "sha256": "f234cc53eb518e3b126489f4f68ddf1eeff75689355ae8143294cc5e27a92db2",
          "sha1": "a71dcc05df23e30475ad32de5035d1d79a71ddb7",
          "md5": "e7e46017409d652c9ad3efbe2cf8507e"
        }
      ]
    }
  ]
}
