{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "6asfazep7rf27dfbgyjwvodori"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.7.jar",
          "url": "runelite-api-1.6.7.jar",
          "size": 1160683,
          "sha512": "98ebb957d8710196a31cbbb122ca5742cefd45ba28dd54a43845316fa97074ca0edf25ea47e4548aee56dbebbbb6d718395758354e3302f8afec9c954caba3c5",
          "sha256": "dba70de36cfcf9572b87afb09ac1c5cade63fcff9e561e256cd87968eff5abdb",
          "sha1": "c0123cb150cf139cc14c34f9402ebd61fa66afc4",
          "md5": "a084737539124021171510e52d492b1c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.7.jar",
          "url": "runelite-api-1.6.7.jar",
          "size": 1160683,
          "sha512": "98ebb957d8710196a31cbbb122ca5742cefd45ba28dd54a43845316fa97074ca0edf25ea47e4548aee56dbebbbb6d718395758354e3302f8afec9c954caba3c5",
          "sha256": "dba70de36cfcf9572b87afb09ac1c5cade63fcff9e561e256cd87968eff5abdb",
          "sha1": "c0123cb150cf139cc14c34f9402ebd61fa66afc4",
          "md5": "a084737539124021171510e52d492b1c"
        }
      ]
    }
  ]
}
