{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "3yeprqic7nhydhhejnplopuewq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.7.jar",
          "url": "runelite-api-1.6.7.jar",
          "size": 1160630,
          "sha512": "3885531679e49aac6211fe09431b1c832ea4b241ea5056b94792bbd7f0c9aa6a8a35e09107b7eef715139e46c67b92112deebd662b2b78f6f177037f73506327",
          "sha256": "20560261cca3524e810fbaa0ee9c6415e1d61d273f94d35c91ed355739f9eee7",
          "sha1": "8e5b1698f66ba74a25862fdf71a90c1834938ddf",
          "md5": "a3885dc8b88dbfc792ffa528b98ece32"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.7.jar",
          "url": "runelite-api-1.6.7.jar",
          "size": 1160630,
          "sha512": "3885531679e49aac6211fe09431b1c832ea4b241ea5056b94792bbd7f0c9aa6a8a35e09107b7eef715139e46c67b92112deebd662b2b78f6f177037f73506327",
          "sha256": "20560261cca3524e810fbaa0ee9c6415e1d61d273f94d35c91ed355739f9eee7",
          "sha1": "8e5b1698f66ba74a25862fdf71a90c1834938ddf",
          "md5": "a3885dc8b88dbfc792ffa528b98ece32"
        }
      ]
    }
  ]
}
