{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "5jyhhj26ufg2tcbfo6rjpcshbm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.9.jar",
          "url": "http-api-1.6.9.jar",
          "size": 164353,
          "sha512": "76a2e6e69ac437bb70bd48625f12d0ce5d8aaf0c08e62efbdebc6d7593246e2d53d9d7d44309eebdb9eecd88bfe293b5d84baf59c601b596c5d3dc1abf436b3e",
          "sha256": "51d6230329ea5d1aedf333ed4649d0b7d1be78ff83e3be7d35e0a04071d0e9b6",
          "sha1": "a3212b39247bb18d102906eefaacfaf0f387d398",
          "md5": "71b4022460a8bf719f0fb5bd4c19f7a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.9"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.9.jar",
          "url": "http-api-1.6.9.jar",
          "size": 164353,
          "sha512": "76a2e6e69ac437bb70bd48625f12d0ce5d8aaf0c08e62efbdebc6d7593246e2d53d9d7d44309eebdb9eecd88bfe293b5d84baf59c601b596c5d3dc1abf436b3e",
          "sha256": "51d6230329ea5d1aedf333ed4649d0b7d1be78ff83e3be7d35e0a04071d0e9b6",
          "sha1": "a3212b39247bb18d102906eefaacfaf0f387d398",
          "md5": "71b4022460a8bf719f0fb5bd4c19f7a7"
        }
      ]
    }
  ]
}
