{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "winqrhre6nfgjeptp7pgrdfupm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.1.jar",
          "url": "runelite-api-3.3.1.jar",
          "size": 1181237,
          "sha512": "051aa2987834e6f045e456611b552439a0659b032550407fb757c0ffb26b82f773616cf6cb5bbe612b7e3874413086c67120e84e5efc8f4c2020af95f1fd9744",
          "sha256": "d7571ba2d20086517a365748b737f510a46bcd94d51f401b6155204aad4fb205",
          "sha1": "f470c53b71ec57c13bcfec3f01a7c0b16bc310ae",
          "md5": "ce74fa512c55070899e534168a3c53a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.1.jar",
          "url": "runelite-api-3.3.1.jar",
          "size": 1181237,
          "sha512": "051aa2987834e6f045e456611b552439a0659b032550407fb757c0ffb26b82f773616cf6cb5bbe612b7e3874413086c67120e84e5efc8f4c2020af95f1fd9744",
          "sha256": "d7571ba2d20086517a365748b737f510a46bcd94d51f401b6155204aad4fb205",
          "sha1": "f470c53b71ec57c13bcfec3f01a7c0b16bc310ae",
          "md5": "ce74fa512c55070899e534168a3c53a7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.1-sources.jar",
          "url": "runelite-api-3.3.1-sources.jar",
          "size": 865901,
          "sha512": "e390200cec1eb2cb16d2717a33b7acfdbd7470929644a48d47ee359d40ea115def0302f1d1bcf219780c18bfa92a305bdacd0b0c0dbe170c2aa6b10a75a6c9ff",
          "sha256": "078b814a04d901196967365bf3b56a2343523103c8a7aed862ab5f40e95e1ab6",
          "sha1": "fe0030694344e1b46178deb29ee3c341f4ec71ed",
          "md5": "30b0d5e4629af39e76637e17e4459be4"
        }
      ]
    }
  ]
}
