{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "5gdhgir77bg4pnogfggwpxyraq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.1.jar",
          "url": "runelite-api-3.3.1.jar",
          "size": 1181205,
          "sha512": "49533ceb7aead00ddc40ef84285ec79c4ddd0c49eb47967eef0d77fe654317fcddb5fa96f42c1ef51ba7cf2239dff91be9b05a84916ce6fbeb2e7ea3d9f48f96",
          "sha256": "7fc4ce4a1a6883202b80f8b2b1b70a4a7223d4bae89d86dcfad0ba1721509972",
          "sha1": "de947c45059443177ec7b32746c990b82bb19d8c",
          "md5": "633f25707d3269558030697abfe36014"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.1.jar",
          "url": "runelite-api-3.3.1.jar",
          "size": 1181205,
          "sha512": "49533ceb7aead00ddc40ef84285ec79c4ddd0c49eb47967eef0d77fe654317fcddb5fa96f42c1ef51ba7cf2239dff91be9b05a84916ce6fbeb2e7ea3d9f48f96",
          "sha256": "7fc4ce4a1a6883202b80f8b2b1b70a4a7223d4bae89d86dcfad0ba1721509972",
          "sha1": "de947c45059443177ec7b32746c990b82bb19d8c",
          "md5": "633f25707d3269558030697abfe36014"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.1-sources.jar",
          "url": "runelite-api-3.3.1-sources.jar",
          "size": 865870,
          "sha512": "f5844f0aee5e0d21830346470208101944bf1bb31cc2fb5d1bc1e3440f88fd2602102b03d1b2079f758db4c2def196368d5a2a18d5ad55e606e5350334e02e45",
          "sha256": "bc26c215c17c180121383b4c97a3d694ac6412063e3c85085d44b60b91a901ff",
          "sha1": "5b9d57bd8bf876586ad6e64ec8d312164099d290",
          "md5": "2d75ba62eec12dace51cf3556fdb3843"
        }
      ]
    }
  ]
}
