{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "hcdrecwsnzgpvnjzmulx5rnnpu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.1.jar",
          "url": "runelite-api-3.3.1.jar",
          "size": 1181616,
          "sha512": "1a5ae7da085164146c3d9c21229114bb8755745e085ace02e02c7b326697b9b8b7ecedd322d3d4a78e1a6f30441d8ece05bbec22f861ba5b2fdb8b8605de0045",
          "sha256": "de25f90af1594470bd2877838890b9cca088d5dc72836de262a1cb58b11d5e14",
          "sha1": "878c445650afffe0e21f5a9b47b5a109138ab9d5",
          "md5": "2cf885576341edfcb3990b7d631a7e0e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.1.jar",
          "url": "runelite-api-3.3.1.jar",
          "size": 1181616,
          "sha512": "1a5ae7da085164146c3d9c21229114bb8755745e085ace02e02c7b326697b9b8b7ecedd322d3d4a78e1a6f30441d8ece05bbec22f861ba5b2fdb8b8605de0045",
          "sha256": "de25f90af1594470bd2877838890b9cca088d5dc72836de262a1cb58b11d5e14",
          "sha1": "878c445650afffe0e21f5a9b47b5a109138ab9d5",
          "md5": "2cf885576341edfcb3990b7d631a7e0e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.1-sources.jar",
          "url": "runelite-api-3.3.1-sources.jar",
          "size": 866030,
          "sha512": "e283de36a19131a9073c66429fd52ac2b64ff87de9c0a5b5fe38b3c830b20d45b5b8d34fd57557c1b75938b6f5c869aa861a8aa653ecb21027e1cde4dcc20082",
          "sha256": "32d3a453aefa2526650ab27f4cdb649c7c8c2cd1d347bf907d7b62b857c1d8f7",
          "sha1": "b7218f58d36d3c62842195518de7d1d178fa12db",
          "md5": "7803fafe966e1f7a4dfc310c6ef31fc1"
        }
      ]
    }
  ]
}
