{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "tq6d5fcpuzfolj3t2vk3h7pqcu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.5-SNAPSHOT.jar",
          "url": "injected-client-1.6.5-20200123.130318-1.jar",
          "size": 2224423,
          "sha512": "5d96f644adea73854859d1505bef38fdbd1b0a81fd7c8f11e38d9983547dbbb7e76a16045e840314492170ac5f067a6948b26e2b5380790155e758005d48c084",
          "sha256": "48179af28644a4e96c9178c1096f1fc69b63572975806fd430155929475d943c",
          "sha1": "8bd885d82de1fefc28c7ef9fa31ed4abd46ab95b",
          "md5": "57abccc79cd21555566e95c980898a8d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.5-SNAPSHOT.jar",
          "url": "injected-client-1.6.5-20200123.130318-1.jar",
          "size": 2224423,
          "sha512": "5d96f644adea73854859d1505bef38fdbd1b0a81fd7c8f11e38d9983547dbbb7e76a16045e840314492170ac5f067a6948b26e2b5380790155e758005d48c084",
          "sha256": "48179af28644a4e96c9178c1096f1fc69b63572975806fd430155929475d943c",
          "sha1": "8bd885d82de1fefc28c7ef9fa31ed4abd46ab95b",
          "md5": "57abccc79cd21555566e95c980898a8d"
        }
      ]
    }
  ]
}
