{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "di32qfpgqzhqvkussohihqegoe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.5-SNAPSHOT.jar",
          "url": "injected-client-1.6.5-20200128.004105-1.jar",
          "size": 2224503,
          "sha512": "a5ecae600276dd1cfd1dc9e6e02186e4ca2cf9f8b3d22f177f91ca829626c146e1352149c7743618df7697f98229a771a895459fe7ed6322aeafc1b8c6f61ac8",
          "sha256": "9783cd788b388462f51237c591f75fba64dcf9a4df6c1c8aa48b650367dc03bd",
          "sha1": "5dd6a626c0486f30620a8e47984b7da0cf99618d",
          "md5": "bc36ba34fd62911cf4971783bfa17774"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.5-SNAPSHOT.jar",
          "url": "injected-client-1.6.5-20200128.004105-1.jar",
          "size": 2224503,
          "sha512": "a5ecae600276dd1cfd1dc9e6e02186e4ca2cf9f8b3d22f177f91ca829626c146e1352149c7743618df7697f98229a771a895459fe7ed6322aeafc1b8c6f61ac8",
          "sha256": "9783cd788b388462f51237c591f75fba64dcf9a4df6c1c8aa48b650367dc03bd",
          "sha1": "5dd6a626c0486f30620a8e47984b7da0cf99618d",
          "md5": "bc36ba34fd62911cf4971783bfa17774"
        }
      ]
    }
  ]
}
