{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "ohxcde6lofempnsnf753wfon7e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.5-SNAPSHOT.jar",
          "url": "injected-client-1.6.5-20200124.000811-1.jar",
          "size": 2224423,
          "sha512": "564f4c65701473eaccf65f1582aaccce04f436b2802179ad2b899b7b8215d4fb15cb69586b804a4589d17228c0257cd97ce8aff5add471f8dc2bf0e207b68083",
          "sha256": "43bf87c92ead9dc011cac0f7db2126e9f59c7ec6005885142e781d6376bc06c2",
          "sha1": "2b144b350d8204a51670b1ece94c33fe02b89ede",
          "md5": "6d4e0a03ebb30561008240b692ad785f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.5-SNAPSHOT.jar",
          "url": "injected-client-1.6.5-20200124.000811-1.jar",
          "size": 2224423,
          "sha512": "564f4c65701473eaccf65f1582aaccce04f436b2802179ad2b899b7b8215d4fb15cb69586b804a4589d17228c0257cd97ce8aff5add471f8dc2bf0e207b68083",
          "sha256": "43bf87c92ead9dc011cac0f7db2126e9f59c7ec6005885142e781d6376bc06c2",
          "sha1": "2b144b350d8204a51670b1ece94c33fe02b89ede",
          "md5": "6d4e0a03ebb30561008240b692ad785f"
        }
      ]
    }
  ]
}
