{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "ifuhwtoltfgjrkfuzss572eyki"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.5-SNAPSHOT.jar",
          "url": "injected-client-1.6.5-20200128.000916-1.jar",
          "size": 2224503,
          "sha512": "affeec3b1a248a3e68edaeace650e62a71ace1d49f7aaa8361a38a519bde2ef76e44d12c9b57a82fd8e2f9b8313629bb5691c76a55709566b6e8a402a6819e56",
          "sha256": "7c538d75f6836712b6282948f35b7952518234b5589e575288fcb19843d39373",
          "sha1": "be94fbfb64670aaf2e547832188c462690157de8",
          "md5": "4ca812bd895f82e112dd7d4b8bd9ab3f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.5-SNAPSHOT.jar",
          "url": "injected-client-1.6.5-20200128.000916-1.jar",
          "size": 2224503,
          "sha512": "affeec3b1a248a3e68edaeace650e62a71ace1d49f7aaa8361a38a519bde2ef76e44d12c9b57a82fd8e2f9b8313629bb5691c76a55709566b6e8a402a6819e56",
          "sha256": "7c538d75f6836712b6282948f35b7952518234b5589e575288fcb19843d39373",
          "sha1": "be94fbfb64670aaf2e547832188c462690157de8",
          "md5": "4ca812bd895f82e112dd7d4b8bd9ab3f"
        }
      ]
    }
  ]
}
