{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "35o7ugfvczalxmxd53hde2sfpa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.5-SNAPSHOT.jar",
          "url": "injected-client-1.6.5-20200126.000916-1.jar",
          "size": 2224423,
          "sha512": "66dd028f4f0f0d87402fdffac475e285be406075103a452047c862fd83242edd5b0f1c0f7c03f3c0433310a19c25e7314b82da8bfc08fee99f32fe72e986e35e",
          "sha256": "6202900a2469146903628b982aecd531785740597a5a792c04b2dbc0e5ceb85f",
          "sha1": "d9a3ce15ecd9364c1f6435570331eec33ae79fff",
          "md5": "c24641ca9197cd5843b7c0d4792e6ab7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.5-SNAPSHOT.jar",
          "url": "injected-client-1.6.5-20200126.000916-1.jar",
          "size": 2224423,
          "sha512": "66dd028f4f0f0d87402fdffac475e285be406075103a452047c862fd83242edd5b0f1c0f7c03f3c0433310a19c25e7314b82da8bfc08fee99f32fe72e986e35e",
          "sha256": "6202900a2469146903628b982aecd531785740597a5a792c04b2dbc0e5ceb85f",
          "sha1": "d9a3ce15ecd9364c1f6435570331eec33ae79fff",
          "md5": "c24641ca9197cd5843b7c0d4792e6ab7"
        }
      ]
    }
  ]
}
