{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "6qirsm64zvg2xjjlujl56u5tde"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.8.jar",
          "url": "injected-client-1.6.8.jar",
          "size": 2266314,
          "sha512": "165b9b6df5e8aea622f5825bf79c44774e7dc8c05c28b3aad661b3bf2c860107b6611a65ad49ae2cba2c352c46925b1f1e05a6558f4a7614f4ef1c5a2d6ec70b",
          "sha256": "c9ca5cc7868a004b1d3cd7a9297e5d2ecda9ca2d04372513abc40aa7ce414c88",
          "sha1": "3de49168645094d4b1a3048b2533e3bdccd1ddc7",
          "md5": "522686b0c512ba82792fceee0558e872"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.8.jar",
          "url": "injected-client-1.6.8.jar",
          "size": 2266314,
          "sha512": "165b9b6df5e8aea622f5825bf79c44774e7dc8c05c28b3aad661b3bf2c860107b6611a65ad49ae2cba2c352c46925b1f1e05a6558f4a7614f4ef1c5a2d6ec70b",
          "sha256": "c9ca5cc7868a004b1d3cd7a9297e5d2ecda9ca2d04372513abc40aa7ce414c88",
          "sha1": "3de49168645094d4b1a3048b2533e3bdccd1ddc7",
          "md5": "522686b0c512ba82792fceee0558e872"
        }
      ]
    }
  ]
}
