{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "b54trkceujcplpatavyavejajq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.8.jar",
          "url": "injected-client-1.6.8.jar",
          "size": 2266314,
          "sha512": "a18a644305dc92cd91f9390502b4d1c1d6458e6250d47296d2a102d5417386c0df9e415fa57a9bb8f151cf863a0ef0cfdebbcb3692dec3f6cd83c023b7b182ee",
          "sha256": "9dcf8a91c8176fdc9c2a898cbc00e372d529e2451aa2ca299c21924aac59d1ca",
          "sha1": "ac0f9a00375e287f58b410886aab56d76829984d",
          "md5": "3656b4d66370812f6b4a462382790de0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.8.jar",
          "url": "injected-client-1.6.8.jar",
          "size": 2266314,
          "sha512": "a18a644305dc92cd91f9390502b4d1c1d6458e6250d47296d2a102d5417386c0df9e415fa57a9bb8f151cf863a0ef0cfdebbcb3692dec3f6cd83c023b7b182ee",
          "sha256": "9dcf8a91c8176fdc9c2a898cbc00e372d529e2451aa2ca299c21924aac59d1ca",
          "sha1": "ac0f9a00375e287f58b410886aab56d76829984d",
          "md5": "3656b4d66370812f6b4a462382790de0"
        }
      ]
    }
  ]
}
