{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "eaynwhnouvaevdq6mvhcf54z3q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.8.jar",
          "url": "injected-client-1.6.8.jar",
          "size": 2266314,
          "sha512": "85ab6d06689fd6dd16ec6cbd332a592ea39032fc50d0a81638042d546dab2f85282af75c06d2dc39ccbd4f891bd26a7411b333c674968fb3ae760e877502fb40",
          "sha256": "b87bb3c4e80b3787bd2bc6c14e82194468d94d440d7b75b085248ef1b8716082",
          "sha1": "c9a75585617c1e3e43a8d033b9534e0371e5bb5d",
          "md5": "7d2d38de31cc322fe2a7df5e2203295c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.8.jar",
          "url": "injected-client-1.6.8.jar",
          "size": 2266314,
          "sha512": "85ab6d06689fd6dd16ec6cbd332a592ea39032fc50d0a81638042d546dab2f85282af75c06d2dc39ccbd4f891bd26a7411b333c674968fb3ae760e877502fb40",
          "sha256": "b87bb3c4e80b3787bd2bc6c14e82194468d94d440d7b75b085248ef1b8716082",
          "sha1": "c9a75585617c1e3e43a8d033b9534e0371e5bb5d",
          "md5": "7d2d38de31cc322fe2a7df5e2203295c"
        }
      ]
    }
  ]
}
