{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "7ukznm4zhfczpkbzlvj6brvxs4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.0.7.jar",
          "url": "injected-client-3.0.7.jar",
          "size": 2266379,
          "sha512": "857d987667837c363e5724d340626327dfddd32d3ef1d64b15500d089baab6984e70a5c2eaf10eac8ea02064dbe79b870d4f6a2217c5520ffc4a3d210172db2f",
          "sha256": "6b2e561da899e9a5a219854b60c8775976250d858f597ff845d1edb18246cfa5",
          "sha1": "4f8d27cfd16e6b9484df9eccb64eb3ca0c38e6e0",
          "md5": "b1adeff72086f2da39a9325469f8e354"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.0.7.jar",
          "url": "injected-client-3.0.7.jar",
          "size": 2266379,
          "sha512": "857d987667837c363e5724d340626327dfddd32d3ef1d64b15500d089baab6984e70a5c2eaf10eac8ea02064dbe79b870d4f6a2217c5520ffc4a3d210172db2f",
          "sha256": "6b2e561da899e9a5a219854b60c8775976250d858f597ff845d1edb18246cfa5",
          "sha1": "4f8d27cfd16e6b9484df9eccb64eb3ca0c38e6e0",
          "md5": "b1adeff72086f2da39a9325469f8e354"
        }
      ]
    }
  ]
}
