{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "fv3xrqpvcfgmllx27r5wuy7p5q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.0.7.jar",
          "url": "injected-client-3.0.7.jar",
          "size": 2266379,
          "sha512": "7fc75b60e2f62a87a38e3e5e4fed77a82d374979e2566d5b00b6a1d05eb334631d54f2b95981da9ba90d054551ec17b7bfbae948009c1e34321131a1d3b3a23e",
          "sha256": "fe0c49656e740a8d4f7d6246029c996458ad65a3b9f6a79e6217294eb2912924",
          "sha1": "ca146cbd65dcb3b0c8f589abaa119eb5763022d7",
          "md5": "55fec3e082d59f95e5d4925575188fbf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.0.7.jar",
          "url": "injected-client-3.0.7.jar",
          "size": 2266379,
          "sha512": "7fc75b60e2f62a87a38e3e5e4fed77a82d374979e2566d5b00b6a1d05eb334631d54f2b95981da9ba90d054551ec17b7bfbae948009c1e34321131a1d3b3a23e",
          "sha256": "fe0c49656e740a8d4f7d6246029c996458ad65a3b9f6a79e6217294eb2912924",
          "sha1": "ca146cbd65dcb3b0c8f589abaa119eb5763022d7",
          "md5": "55fec3e082d59f95e5d4925575188fbf"
        }
      ]
    }
  ]
}
