{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "nkjidasifvep7jumf6tquswwy4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": []
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.9.jar",
          "url": "injected-client-3.3.9.jar",
          "size": 2304934,
          "sha512": "d9e1f17c91c9120b6d0a9acce70974f7be4e7bd17ad91c40ad606d020fbb6fbdf995f5a861f0098cfff3614ad763e75a22b67424aa9f69bd740da86047797b4e",
          "sha256": "b9db5a3f173084bd888215632ab57e7f680c66c82ff082097eaae9586f14bf91",
          "sha1": "780adc9ad711b4e019d34db333a81674e2cf926a",
          "md5": "3b19b0e975b303924e8481c9abe0df5b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": []
    }
  ]
}
