{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "ojvjqh4ee5hzfcyqdtq5lejcga"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.0.jar",
          "url": "runelite-api-3.3.0.jar",
          "size": 1179343,
          "sha512": "4c819795652e1c3e82d3b1e43d6b121e9fd35e9e0a4c21ebb08d779269227c6cf51f47f31291585b6350655a627e18539a160ea179b1981ab5c5af30beddfa40",
          "sha256": "779af7723b4c3227a90a7b6edc194f7ce98184d22d5653aee44d31e84ab6e3ee",
          "sha1": "2adba6de55bc090a65b128ed089d145184fc9382",
          "md5": "4b89efff553b1e215b9d9c8b57420353"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.0.jar",
          "url": "runelite-api-3.3.0.jar",
          "size": 1179343,
          "sha512": "4c819795652e1c3e82d3b1e43d6b121e9fd35e9e0a4c21ebb08d779269227c6cf51f47f31291585b6350655a627e18539a160ea179b1981ab5c5af30beddfa40",
          "sha256": "779af7723b4c3227a90a7b6edc194f7ce98184d22d5653aee44d31e84ab6e3ee",
          "sha1": "2adba6de55bc090a65b128ed089d145184fc9382",
          "md5": "4b89efff553b1e215b9d9c8b57420353"
        }
      ]
    }
  ]
}
