{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "qgjqkhrpkvchjjh2hyut7go6dy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.0.jar",
          "url": "runelite-api-3.3.0.jar",
          "size": 1180884,
          "sha512": "b2edeffb4892ab8ceefaf258861ba5e83ba607b8b2b509f3e5abffe686be3c64dcfd4cf6d8952daff84d495e3ee9031b82f7861e576d9942f321ea2ded98b79f",
          "sha256": "f303d93aa0d5d0027f42032b01b5726984db95e881b55cc7412982fd10e020d1",
          "sha1": "8293e874b9e5f2842147140ded23805a2ed48f35",
          "md5": "d0b147a7e0d7d3ec23a1dae1dc5f307f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.0.jar",
          "url": "runelite-api-3.3.0.jar",
          "size": 1180884,
          "sha512": "b2edeffb4892ab8ceefaf258861ba5e83ba607b8b2b509f3e5abffe686be3c64dcfd4cf6d8952daff84d495e3ee9031b82f7861e576d9942f321ea2ded98b79f",
          "sha256": "f303d93aa0d5d0027f42032b01b5726984db95e881b55cc7412982fd10e020d1",
          "sha1": "8293e874b9e5f2842147140ded23805a2ed48f35",
          "md5": "d0b147a7e0d7d3ec23a1dae1dc5f307f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.0-sources.jar",
          "url": "runelite-api-3.3.0-sources.jar",
          "size": 865517,
          "sha512": "ddc85e9990eba30078ad37630ec31e664ad414c33a2a7a0e00e24c2ab21d40baf29f189c76b61cfd6930cb3be3315c1f237a2c814136988603edefcbb13fa8b4",
          "sha256": "490c2bfda69a5b429bdc2ef84d5405f1f65be6dc1fe6c97ced9cb710764d0255",
          "sha1": "416670d4dec0e887cf87b903bfabb986ba7bc979",
          "md5": "dc7997fe81bc5b7e202a9180c659e7ed"
        }
      ]
    }
  ]
}
