{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "mvycwucviza4lmpovgihk7oh3i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.0.jar",
          "url": "runelite-api-3.3.0.jar",
          "size": 1179343,
          "sha512": "b7cbf0eafbe96ab035e93ca529110ec98b09abc643c98c36a0d8689b33185588643dd736997c7a507de2f842195469179798c9644acab5a1bdfe592491e93182",
          "sha256": "8966c4d1b04553c683354103d00822ab96da4d0e81a775e4416c7d6565df58a5",
          "sha1": "0591323e04c6a76ada041117451a369c92c66709",
          "md5": "3ac0bd1532d0730d3204603843ec41ef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.0.jar",
          "url": "runelite-api-3.3.0.jar",
          "size": 1179343,
          "sha512": "b7cbf0eafbe96ab035e93ca529110ec98b09abc643c98c36a0d8689b33185588643dd736997c7a507de2f842195469179798c9644acab5a1bdfe592491e93182",
          "sha256": "8966c4d1b04553c683354103d00822ab96da4d0e81a775e4416c7d6565df58a5",
          "sha1": "0591323e04c6a76ada041117451a369c92c66709",
          "md5": "3ac0bd1532d0730d3204603843ec41ef"
        }
      ]
    }
  ]
}
