{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "okixqif5jraclolqnbcy2mxehu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.8.jar",
          "url": "runescape-api-1.6.8.jar",
          "size": 55336,
          "sha512": "27da9f2eddeb4290af3b67f5555e0133897df1df888561a6d8b5ace7411bddc8c24ca87f08e1bd16aa3a105fdd6da9d4dde2919a8ab5a458a422d5c19a30e4bd",
          "sha256": "3545868c978e84cf6709f70359e0bfa69b3a3ac66fcd3dac2de729731db279d0",
          "sha1": "2e85ff9943b5b413418b826c1c57918ee0800ffc",
          "md5": "70fdf348bbaf0a039eb40291d4bc037c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.8.jar",
          "url": "runescape-api-1.6.8.jar",
          "size": 55336,
          "sha512": "27da9f2eddeb4290af3b67f5555e0133897df1df888561a6d8b5ace7411bddc8c24ca87f08e1bd16aa3a105fdd6da9d4dde2919a8ab5a458a422d5c19a30e4bd",
          "sha256": "3545868c978e84cf6709f70359e0bfa69b3a3ac66fcd3dac2de729731db279d0",
          "sha1": "2e85ff9943b5b413418b826c1c57918ee0800ffc",
          "md5": "70fdf348bbaf0a039eb40291d4bc037c"
        }
      ]
    }
  ]
}
