{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "v3pyrqm6a5chtm36mgrslnsbxm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      }
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.4.4.jar",
          "url": "injected-client-3.4.4.jar",
          "size": 2263568,
          "sha512": "5227fe8ef23e9e72cf6daced85996f5c993d2c355a345a17380fdbaa109a4f27206264b587b78fb26a978bd3d11c9a8266d736d2fbd1a784a3debf8dc18c675d",
          "sha256": "0d04071aee6cf0ee33309971eb07d826f317d80c0773040b277a4ace50a38f17",
          "sha1": "7038b3d8313c91abb9200c69eff2ff85c1618c13",
          "md5": "a041c49e7a3c7edbeec0884ba6d51577"
        }
      ]
    }
  ]
}
