{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "iifjkv76wzfzrinerck3idof3y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.9.jar",
          "url": "injected-client-1.6.9.jar",
          "size": 2266314,
          "sha512": "49f2ce949c9786d42389181ba27286490ebe704772fbe70904def55cfd49b3f42cc5ffd1e6345e13a99a8d3083221e0c47f6a4f61af3aa2e6fa5013ad88b8587",
          "sha256": "98a51a8cbdc86492f33b193da8b030e1a0c71da5399450a1a0570328115bcbe0",
          "sha1": "8193beb8a9fe2b2cb50aa62125cbdd4a3e0630c5",
          "md5": "5a603d4d0f7a4f1debef3bc7b9ddf5be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.9.jar",
          "url": "injected-client-1.6.9.jar",
          "size": 2266314,
          "sha512": "49f2ce949c9786d42389181ba27286490ebe704772fbe70904def55cfd49b3f42cc5ffd1e6345e13a99a8d3083221e0c47f6a4f61af3aa2e6fa5013ad88b8587",
          "sha256": "98a51a8cbdc86492f33b193da8b030e1a0c71da5399450a1a0570328115bcbe0",
          "sha1": "8193beb8a9fe2b2cb50aa62125cbdd4a3e0630c5",
          "md5": "5a603d4d0f7a4f1debef3bc7b9ddf5be"
        }
      ]
    }
  ]
}
