{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "7qfsywvzyveczfcfgmdtcxye2a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.9.jar",
          "url": "injected-client-1.6.9.jar",
          "size": 2266314,
          "sha512": "41bc0b008656eb98de19faf16f93729577cb57c0b5a919a3c7bb34e0a465b5e6ba76057458274863ea605d0fbf428a34d7b5a6629e19278518b85fd46f314a10",
          "sha256": "ea1c2d02c97cc65ba0a8f444c5d07ea306b51be8c53321e929e49a6fe7c6ef04",
          "sha1": "500bbc65c82389e6eab2f06c140a0d86b377134c",
          "md5": "e990061870a1c996f7dd9b67636bcf43"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.9.jar",
          "url": "injected-client-1.6.9.jar",
          "size": 2266314,
          "sha512": "41bc0b008656eb98de19faf16f93729577cb57c0b5a919a3c7bb34e0a465b5e6ba76057458274863ea605d0fbf428a34d7b5a6629e19278518b85fd46f314a10",
          "sha256": "ea1c2d02c97cc65ba0a8f444c5d07ea306b51be8c53321e929e49a6fe7c6ef04",
          "sha1": "500bbc65c82389e6eab2f06c140a0d86b377134c",
          "md5": "e990061870a1c996f7dd9b67636bcf43"
        }
      ]
    }
  ]
}
