{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "6wnuhmf4lnh2hkpdlgbiddxdcm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.1.0.jar",
          "url": "injected-client-3.1.0.jar",
          "size": 2266379,
          "sha512": "99afbd09e6a3c1ab9a824f6a351df646b4303719d47636a2556889b8f4a000f875dd6fa84cf31a3e0488f41f122b60f839e3e7519ced1af37b65ea566392d1bb",
          "sha256": "5b7b31476002f7ffa021e19eb50c95ed6e9592c7ed841abcedd3cdb27d41eb54",
          "sha1": "f0e319ff3f4f0b72098f7868184c4771324ac7aa",
          "md5": "dee47e33c644877f4b00f87e1f648037"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.1.0.jar",
          "url": "injected-client-3.1.0.jar",
          "size": 2266379,
          "sha512": "99afbd09e6a3c1ab9a824f6a351df646b4303719d47636a2556889b8f4a000f875dd6fa84cf31a3e0488f41f122b60f839e3e7519ced1af37b65ea566392d1bb",
          "sha256": "5b7b31476002f7ffa021e19eb50c95ed6e9592c7ed841abcedd3cdb27d41eb54",
          "sha1": "f0e319ff3f4f0b72098f7868184c4771324ac7aa",
          "md5": "dee47e33c644877f4b00f87e1f648037"
        }
      ]
    }
  ]
}
