{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "otqveiv2azb5rmwjys3mkini5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.1.0.jar",
          "url": "injected-client-3.1.0.jar",
          "size": 2266923,
          "sha512": "ef4acc5bc28e03037e83bb3f153f9e56c2945f9dfc85ab341db213ed971aa2a4cf1a6223fb2397d3ff802e7bf88a8b4cb644b8a434243bf2a8cb2e5b035270c4",
          "sha256": "41fb5524bb894c98afe46e45ebd5e4513cf52074e58506fa0b5a98864d52f8a1",
          "sha1": "1919ad5559ddf9e8ed18b20f58df744e06abd27f",
          "md5": "7de6695a1c06fb34dfd49d19f98ebdc4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.1.0.jar",
          "url": "injected-client-3.1.0.jar",
          "size": 2266923,
          "sha512": "ef4acc5bc28e03037e83bb3f153f9e56c2945f9dfc85ab341db213ed971aa2a4cf1a6223fb2397d3ff802e7bf88a8b4cb644b8a434243bf2a8cb2e5b035270c4",
          "sha256": "41fb5524bb894c98afe46e45ebd5e4513cf52074e58506fa0b5a98864d52f8a1",
          "sha1": "1919ad5559ddf9e8ed18b20f58df744e06abd27f",
          "md5": "7de6695a1c06fb34dfd49d19f98ebdc4"
        }
      ]
    }
  ]
}
