{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "7qfsywvzyveczfcfgmdtcxye2a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.9.jar",
          "url": "http-api-1.6.9.jar",
          "size": 164353,
          "sha512": "dab5ac677c74f2fde7ff01a112dcc5d22620e690605b888615c40302e31d22372d2d5505a940d14bcb84a997fd250c0eff90e4e4ac95d82e964d96315678e5c8",
          "sha256": "ce576cd1288ebe23d647889e2f76123fcdb932f02d06ed629261c08d6d2d289e",
          "sha1": "1854a4c0d95b259a6ae0bfa6f504b8d50dd36b92",
          "md5": "eedeafae26481425eb75c76a9acd4cd8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.9"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.9.jar",
          "url": "http-api-1.6.9.jar",
          "size": 164353,
          "sha512": "dab5ac677c74f2fde7ff01a112dcc5d22620e690605b888615c40302e31d22372d2d5505a940d14bcb84a997fd250c0eff90e4e4ac95d82e964d96315678e5c8",
          "sha256": "ce576cd1288ebe23d647889e2f76123fcdb932f02d06ed629261c08d6d2d289e",
          "sha1": "1854a4c0d95b259a6ae0bfa6f504b8d50dd36b92",
          "md5": "eedeafae26481425eb75c76a9acd4cd8"
        }
      ]
    }
  ]
}
