{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "lhkwaiydozhkvfr6zsixl6g2ge"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.1.jar",
          "url": "runescape-api-3.3.1.jar",
          "size": 103468,
          "sha512": "ee4fa086b43a4d2b4c7b78466edd25e11813f71e71b1068d232cb995ee7878bac906c0709f78fdfd49580b3bd9bcef251e706025f0628aee5822ddda85d13684",
          "sha256": "1c33547ffa83795c7cd65284dc4b38fbdcd6af54bc2e739d781c2aaac9790e63",
          "sha1": "e9b7f04d11ae4f08247b60db362b29750957274e",
          "md5": "34101ef296524e759a595ba1aa069b5d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.1.jar",
          "url": "runescape-api-3.3.1.jar",
          "size": 103468,
          "sha512": "ee4fa086b43a4d2b4c7b78466edd25e11813f71e71b1068d232cb995ee7878bac906c0709f78fdfd49580b3bd9bcef251e706025f0628aee5822ddda85d13684",
          "sha256": "1c33547ffa83795c7cd65284dc4b38fbdcd6af54bc2e739d781c2aaac9790e63",
          "sha1": "e9b7f04d11ae4f08247b60db362b29750957274e",
          "md5": "34101ef296524e759a595ba1aa069b5d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.1-sources.jar",
          "url": "runescape-api-3.3.1-sources.jar",
          "size": 99524,
          "sha512": "d07811ecf08ae6d766ef28f115e91e8562720b954d06e755e047a3b1599edbf91759fd30d955d9460f46777bbb370672b8ad8fdcef88ddf6a5760abc5f928006",
          "sha256": "ef60e536c4a173715bdb2f0f8f61d9cd473155370d432390ca8b39f8e4c744f6",
          "sha1": "e251e7465d63ed2e52f0ccd5ecefe1d89738177c",
          "md5": "ba838965b8669fc3bff832748930e7cd"
        }
      ]
    }
  ]
}
