{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "aj25mi6rinfp7bhkyahlp6x37i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.1.jar",
          "url": "runescape-api-3.3.1.jar",
          "size": 103468,
          "sha512": "9af9af5653b0e1e58661810964c32f98933069557bda24db5830f84b8d61faf99f5cad5004bcd221f4c47cfed074d2d5cd8a16d1c76a8272334488f12d1f5132",
          "sha256": "34769c1d644739b500778b1ec7ee7d35df99476264b05814e6add10ae27aed21",
          "sha1": "52babf4ab4d7a21db13760eb8efcfd223a891d6f",
          "md5": "e62ec764d71e30d9efcd5417c33792ee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.1.jar",
          "url": "runescape-api-3.3.1.jar",
          "size": 103468,
          "sha512": "9af9af5653b0e1e58661810964c32f98933069557bda24db5830f84b8d61faf99f5cad5004bcd221f4c47cfed074d2d5cd8a16d1c76a8272334488f12d1f5132",
          "sha256": "34769c1d644739b500778b1ec7ee7d35df99476264b05814e6add10ae27aed21",
          "sha1": "52babf4ab4d7a21db13760eb8efcfd223a891d6f",
          "md5": "e62ec764d71e30d9efcd5417c33792ee"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.1-sources.jar",
          "url": "runescape-api-3.3.1-sources.jar",
          "size": 99524,
          "sha512": "202a55eecbc6e8514ad9efd62b3cf72cd01f55ed77051778f1a396c3df6f144fe0080a5076b6dbe9b62f9213219df0345a5bd2baea575136385e230e1edb9091",
          "sha256": "5709ab185f1d46868b7f09874388c6ae1ed1e3aacee5efcc214fa47d57438605",
          "sha1": "bf6af69323b958d668b2819eac30a03d69f056d7",
          "md5": "460fc0dee3b29d8794dcd3adbc383062"
        }
      ]
    }
  ]
}
