{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "4qos4eovc5cynhm3ez6lblfl4i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.1.jar",
          "url": "runescape-api-3.3.1.jar",
          "size": 103468,
          "sha512": "0c5d935839ff77aac6cd9d237ffe92c0b8c939ac272d473075ee5f8d13e80eb8173e140f189e2d155c26dfc185d03a187061b60eb6a9f666f8c8c1fdbeac725a",
          "sha256": "f17ff2ad39106c39e1b241985e8e1fa756ece58cf8645f2c1ee3110829aa3d10",
          "sha1": "0deda87b64e23bc917658b16504009ce1797d2f6",
          "md5": "195bcb528f33fe396766bc514e54ef23"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.1.jar",
          "url": "runescape-api-3.3.1.jar",
          "size": 103468,
          "sha512": "0c5d935839ff77aac6cd9d237ffe92c0b8c939ac272d473075ee5f8d13e80eb8173e140f189e2d155c26dfc185d03a187061b60eb6a9f666f8c8c1fdbeac725a",
          "sha256": "f17ff2ad39106c39e1b241985e8e1fa756ece58cf8645f2c1ee3110829aa3d10",
          "sha1": "0deda87b64e23bc917658b16504009ce1797d2f6",
          "md5": "195bcb528f33fe396766bc514e54ef23"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.1-sources.jar",
          "url": "runescape-api-3.3.1-sources.jar",
          "size": 99524,
          "sha512": "ca4a45675bb8dced7b74291788b4cee4f2aab024af1af279ad75d1d3289c619ea61ce2c1c52f31fdc2e3f3c1e8cb41b063c2d7aa298230346e78f73bac7f5c1a",
          "sha256": "73a0f0cb487e8146e4f4c2ba283b6100f38915a96722e6fb5371b7aa89e5f8a1",
          "sha1": "013af802585b2ccd7b81a08e854f21bcd225bf32",
          "md5": "304448c1f5a484430c02b5653d07c574"
        }
      ]
    }
  ]
}
