{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "5omm3gf3kfdbxdpibxbt5eh3ja"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": []
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.4.0.jar",
          "url": "injected-client-3.4.0.jar",
          "size": 2305007,
          "sha512": "75a8c589b5c9914bf9b200d3e6ca600fb94350ddf85815027c4a670a5a0a824a56436f9f5ac298441757271d5f04602bd67d930f1c2c3c68b0549f3ed9b89894",
          "sha256": "20298132b77123f5f90b99a15870cf04cc47eeee592f290f5fea340d6e4a17f3",
          "sha1": "3dd4eac40407f235878ca0438277badb467702c6",
          "md5": "f24634bd0f179843eb1118b7f3b70822"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": []
    }
  ]
}
