{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "fvdfoysannanrgww7ewrlon3qi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.2.jar",
          "url": "runescape-api-3.3.2.jar",
          "size": 103485,
          "sha512": "3b6fb70f0a8253c87f50bd1fdcf62486507dd0bf2e8ed6889988e28e17e4585dc095c481e336bbb3849898c5642bc681e6629c38358725b541d7d041885dd7d2",
          "sha256": "06d1776693aa28cb989b9a6209ebbee2ba7ba2865ea6d1ad55f4f6237ba6230a",
          "sha1": "9249fdefcd83a1838e0c6ee7a483130c5467d133",
          "md5": "c42fed5a9ab61a1e376b9e2fb16fe352"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.2.jar",
          "url": "runescape-api-3.3.2.jar",
          "size": 103485,
          "sha512": "3b6fb70f0a8253c87f50bd1fdcf62486507dd0bf2e8ed6889988e28e17e4585dc095c481e336bbb3849898c5642bc681e6629c38358725b541d7d041885dd7d2",
          "sha256": "06d1776693aa28cb989b9a6209ebbee2ba7ba2865ea6d1ad55f4f6237ba6230a",
          "sha1": "9249fdefcd83a1838e0c6ee7a483130c5467d133",
          "md5": "c42fed5a9ab61a1e376b9e2fb16fe352"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.2-sources.jar",
          "url": "runescape-api-3.3.2-sources.jar",
          "size": 99587,
          "sha512": "abf7655eae7d2cea647784c8a165ad3ea8d655818a7aaff3438f2b485de70d98fd890bb7fefb35e96871d69ca5dfb7420ba7e7893233116623e72b02ac910501",
          "sha256": "8ffd4dadcb4d6a8f25f7c167d6ab7b47a8a4e69611e4ea8105967811a06f5e18",
          "sha1": "0a33f4fc15ff15a1e08648949828b4b9baf669d9",
          "md5": "bf272f4cf0a4ac53928d6fe32c0d492c"
        }
      ]
    }
  ]
}
