{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "rgsjahkotbax3llwkocflj34qy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.2.jar",
          "url": "runescape-api-3.3.2.jar",
          "size": 103393,
          "sha512": "3e5e9e4a738f00eda8cb90a4b612722b5e77a2426bcf78feed041372bf4f85028e7e4917d11dfaa75d103cd1b6232c2f6724254029e878d3b0b1409699fc73e5",
          "sha256": "f597ff7918a79a809e6bc0bb1fae215df79a52f2c6bbe97c9f4b5d8741f28c5b",
          "sha1": "f47fc25b023afe5c12b37fadb3d1b9df57fc0c2c",
          "md5": "ffceaff49e2cb03d6f9800bb44732c07"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.2.jar",
          "url": "runescape-api-3.3.2.jar",
          "size": 103393,
          "sha512": "3e5e9e4a738f00eda8cb90a4b612722b5e77a2426bcf78feed041372bf4f85028e7e4917d11dfaa75d103cd1b6232c2f6724254029e878d3b0b1409699fc73e5",
          "sha256": "f597ff7918a79a809e6bc0bb1fae215df79a52f2c6bbe97c9f4b5d8741f28c5b",
          "sha1": "f47fc25b023afe5c12b37fadb3d1b9df57fc0c2c",
          "md5": "ffceaff49e2cb03d6f9800bb44732c07"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.2-sources.jar",
          "url": "runescape-api-3.3.2-sources.jar",
          "size": 99523,
          "sha512": "ea50279041c089cb31ba68c321562e67dfe37e5d0a59e5bee3abec4864f72c5fbad144b0d274ec080c9c5176ab99e750e161071d4e1c8202702f8452ada0b801",
          "sha256": "bfafd64d1e52fa1ca4a7ae6118a88172dd04bdd354bdfb0ec1fd1253dc801746",
          "sha1": "36800ece2a3e013874747a0f0f8f8e23573942f2",
          "md5": "089d8cceae7e6ae114294a4f9baf7041"
        }
      ]
    }
  ]
}
