{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "qhua3n4ec5dqja3otg5t3f4w64"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.2.jar",
          "url": "runescape-api-3.3.2.jar",
          "size": 103485,
          "sha512": "b35b80f2188baff0279ed683cf0c6131698f76ec6113b504c60a714a5ac7187f0be12fa3f5f4e1dca5f6af013647e5760ca48245f8d51e57452f036c8849ff95",
          "sha256": "b21913b70507e565024aba82a456fb95b1872212d1d5c93b22995c10bb5c0529",
          "sha1": "4e1156d63ac230deec4a2884935beabf5b4048fd",
          "md5": "c4223bbacac0250386813368d42909a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.2.jar",
          "url": "runescape-api-3.3.2.jar",
          "size": 103485,
          "sha512": "b35b80f2188baff0279ed683cf0c6131698f76ec6113b504c60a714a5ac7187f0be12fa3f5f4e1dca5f6af013647e5760ca48245f8d51e57452f036c8849ff95",
          "sha256": "b21913b70507e565024aba82a456fb95b1872212d1d5c93b22995c10bb5c0529",
          "sha1": "4e1156d63ac230deec4a2884935beabf5b4048fd",
          "md5": "c4223bbacac0250386813368d42909a7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.2-sources.jar",
          "url": "runescape-api-3.3.2-sources.jar",
          "size": 99587,
          "sha512": "09b7ef2a688bb20ace0a18a9621c6a668c6cad1465c15fca880b632fe581d90ad0f80d74e0fbd05e8157541565ca0ac048c922f7864557e90294e8984d43ea1c",
          "sha256": "b2cf89075ea52957b4dbef2696a8ffaba408726ea3f6297ccda3d975690bb7cd",
          "sha1": "68dac1dd620e9c0f4b0ea9a3de4b608e3878d628",
          "md5": "311bcb8ac6c597e9e748056b9f52f4e2"
        }
      ]
    }
  ]
}
