{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "5vb2hqqn6zavzl4wc5yi2dmkka"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.0.7.jar",
          "url": "runescape-api-3.0.7.jar",
          "size": 55408,
          "sha512": "14c95525ac489221ec8b9d96091b7ef0341af641aa6f16003658f3945f8cd0d1922c61efc08c8a47d0c3052898821b0bf57fa0f9e49857c35445b13d63eac926",
          "sha256": "f934dd29cefef12b1723c2abe7a9ee3da74fb67bf5f9522848635664f475f137",
          "sha1": "b4eb5f4b8c49899ae211a7b572f330ecd9ad1e9b",
          "md5": "48683968a429108ceca45a6c1e638a59"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.0.7.jar",
          "url": "runescape-api-3.0.7.jar",
          "size": 55408,
          "sha512": "14c95525ac489221ec8b9d96091b7ef0341af641aa6f16003658f3945f8cd0d1922c61efc08c8a47d0c3052898821b0bf57fa0f9e49857c35445b13d63eac926",
          "sha256": "f934dd29cefef12b1723c2abe7a9ee3da74fb67bf5f9522848635664f475f137",
          "sha1": "b4eb5f4b8c49899ae211a7b572f330ecd9ad1e9b",
          "md5": "48683968a429108ceca45a6c1e638a59"
        }
      ]
    }
  ]
}
