{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "fj5ipvm2g5hljagfnguvn7yqly"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.5"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.5.jar",
          "url": "runescape-api-3.3.5.jar",
          "size": 103599,
          "sha512": "106b79ea6fde2629fa60dc4e945f76a5cb7d68bd074ff01fc731d53b357db7fdcbc91b3931515b8d5ed60a0459060963c8cff94cfb1ab7a02de800b5b776aadc",
          "sha256": "f82e32f0e47c32b61d7b083e91743e158adcc43d9601f3b5654d51a805ffbc61",
          "sha1": "16e119303a7f5cbd2aa759601f53e0a798ee5700",
          "md5": "39b4ed3831cb232b2d9d5969aa943a54"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.5"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.5.jar",
          "url": "runescape-api-3.3.5.jar",
          "size": 103599,
          "sha512": "106b79ea6fde2629fa60dc4e945f76a5cb7d68bd074ff01fc731d53b357db7fdcbc91b3931515b8d5ed60a0459060963c8cff94cfb1ab7a02de800b5b776aadc",
          "sha256": "f82e32f0e47c32b61d7b083e91743e158adcc43d9601f3b5654d51a805ffbc61",
          "sha1": "16e119303a7f5cbd2aa759601f53e0a798ee5700",
          "md5": "39b4ed3831cb232b2d9d5969aa943a54"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.5-sources.jar",
          "url": "runescape-api-3.3.5-sources.jar",
          "size": 99711,
          "sha512": "d819e32d05cef288b420c253454a6343bb8c252f5ec50dcbeefdc2f30af6870d6fa2de950e150b2084c0c1125312a4be2dedea2e321fc2df09b466d21398f69b",
          "sha256": "96e750e18143d335e934931634fe81e520c2096b3a08510d4554989b19c4a9cc",
          "sha1": "2526c0d61c1c6ac05f1f693e2a84773340e98757",
          "md5": "19335f2d82b7e07cc707abb6c0bae565"
        }
      ]
    }
  ]
}
