{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "vcpwgqy36ja3xgj3ojavxjgsae"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.5"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.5.jar",
          "url": "runescape-api-3.3.5.jar",
          "size": 103730,
          "sha512": "0f3820f36688b5dde47af88f3d11119566decd0176bb264b4654dd6f40e8c29d10460dc0b967d40e9fa4393a5272966b6e6bca562b4ce561b8abfe54fecd4c8c",
          "sha256": "f42f6fbe77ce932a7a3213c695842328f81311176ebf388e920b1cb0dd702d94",
          "sha1": "4831e4afb48b09631c3639764aa8bddda516cb3f",
          "md5": "9ed917314b57e9dce68f326fddb875ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.5"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.5.jar",
          "url": "runescape-api-3.3.5.jar",
          "size": 103730,
          "sha512": "0f3820f36688b5dde47af88f3d11119566decd0176bb264b4654dd6f40e8c29d10460dc0b967d40e9fa4393a5272966b6e6bca562b4ce561b8abfe54fecd4c8c",
          "sha256": "f42f6fbe77ce932a7a3213c695842328f81311176ebf388e920b1cb0dd702d94",
          "sha1": "4831e4afb48b09631c3639764aa8bddda516cb3f",
          "md5": "9ed917314b57e9dce68f326fddb875ba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.5-sources.jar",
          "url": "runescape-api-3.3.5-sources.jar",
          "size": 99829,
          "sha512": "9f39f05a9e4b6c81fd172c3ee25b5a3c24ef8e00fa74d76d5d785bb3da37d0caf6e14d0475f465bb781bb916b7262e77bb409cf850ce724ecd4dafa7cc82614e",
          "sha256": "8c27b00166f1c0b0e51a68f92db5edcd3aba5bb02f16ca96ffaec63f0c1dfef8",
          "sha1": "e81d7806b1b62b07661be1bd62e14aa70e2f28cf",
          "md5": "6b2eaf097d9d42c0947a76e94d2066ee"
        }
      ]
    }
  ]
}
