{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "xye5kk5muffe7bnunguohz2kmq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.1.0.jar",
          "url": "injected-client-3.1.0.jar",
          "size": 2266923,
          "sha512": "d4d8d1a32a76a98c5564c5e9df6f58588309e6daeda0b31d8141ed585188e203f90c69173ace369a46de19d17e73b0f0ecbea056d71f9e302d01b1d557e62b9c",
          "sha256": "2ca1d34be29d8872d01d7d24965fc173053dbb3f7542abdfe97393adf68226e3",
          "sha1": "8f4587d9f9a8b2d6f59f1d62214ddf30d7aa4402",
          "md5": "d7c35726e6a2b46fe8d045f1e21acfed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.1.0.jar",
          "url": "injected-client-3.1.0.jar",
          "size": 2266923,
          "sha512": "d4d8d1a32a76a98c5564c5e9df6f58588309e6daeda0b31d8141ed585188e203f90c69173ace369a46de19d17e73b0f0ecbea056d71f9e302d01b1d557e62b9c",
          "sha256": "2ca1d34be29d8872d01d7d24965fc173053dbb3f7542abdfe97393adf68226e3",
          "sha1": "8f4587d9f9a8b2d6f59f1d62214ddf30d7aa4402",
          "md5": "d7c35726e6a2b46fe8d045f1e21acfed"
        }
      ]
    }
  ]
}
