{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "g7mctotlzzhqlgvpswb7vbseia"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.1.0.jar",
          "url": "injected-client-3.1.0.jar",
          "size": 2266771,
          "sha512": "7fe50cd0ae7fc411c3d6fe870e5d839d7c1b82ef2c104cc715060ef8c76d06abbf59a5ca2942e0edb98884741104c9bc5d6ba12c725dd73523b5498678971d3b",
          "sha256": "49a798a07c7f16081281a091fd4e65a32d13037a52e2da88c95b877a4710aa40",
          "sha1": "ab5ba294947b293ef394e32784fbd096e587cfc4",
          "md5": "5fddd757f845671e9f09b5214fe61844"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.1.0.jar",
          "url": "injected-client-3.1.0.jar",
          "size": 2266771,
          "sha512": "7fe50cd0ae7fc411c3d6fe870e5d839d7c1b82ef2c104cc715060ef8c76d06abbf59a5ca2942e0edb98884741104c9bc5d6ba12c725dd73523b5498678971d3b",
          "sha256": "49a798a07c7f16081281a091fd4e65a32d13037a52e2da88c95b877a4710aa40",
          "sha1": "ab5ba294947b293ef394e32784fbd096e587cfc4",
          "md5": "5fddd757f845671e9f09b5214fe61844"
        }
      ]
    }
  ]
}
