{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "564heovtdvdnfcmljza2a67gcq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.1.0.jar",
          "url": "injected-client-3.1.0.jar",
          "size": 2266771,
          "sha512": "004779edbe6de096e01b7fe52a88a4f71f9f6f36485c9ab299139248ec4205cb5054171f872f2b46d2b2e780ef473f5913a6ac56ea93e3120efe453ac2febe42",
          "sha256": "f807543059f5e6e79eb52415caf48bb4f5770cb05a678ee13bfd338b8d055048",
          "sha1": "55b0eba456086c823b8230c19dd10c411eb3640e",
          "md5": "942e6ec033fe1549c8a94f06bab7a072"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.1.0.jar",
          "url": "injected-client-3.1.0.jar",
          "size": 2266771,
          "sha512": "004779edbe6de096e01b7fe52a88a4f71f9f6f36485c9ab299139248ec4205cb5054171f872f2b46d2b2e780ef473f5913a6ac56ea93e3120efe453ac2febe42",
          "sha256": "f807543059f5e6e79eb52415caf48bb4f5770cb05a678ee13bfd338b8d055048",
          "sha1": "55b0eba456086c823b8230c19dd10c411eb3640e",
          "md5": "942e6ec033fe1549c8a94f06bab7a072"
        }
      ]
    }
  ]
}
