{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "ffjqypbsxneapilie7isekxg5q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200211.034535-2.jar",
          "size": 2265695,
          "sha512": "83e41f5dd5db4d96ac40be20996f01ff9ac4d936b98c3853c057649ff4f94d1ae99cb5f0beac6c17d5ed127b47c1b59f72e620d256d7884c0c8d49a1a3f79025",
          "sha256": "efe13f04cebb651dddc6d8d2b03e1b454c7e5c02db1e55d092afb4462f310370",
          "sha1": "ef2947f1f165ca2beee54265a5fca923bfa786f9",
          "md5": "1d86494e239cc50820bcde2151d5efaa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200211.034535-2.jar",
          "size": 2265695,
          "sha512": "83e41f5dd5db4d96ac40be20996f01ff9ac4d936b98c3853c057649ff4f94d1ae99cb5f0beac6c17d5ed127b47c1b59f72e620d256d7884c0c8d49a1a3f79025",
          "sha256": "efe13f04cebb651dddc6d8d2b03e1b454c7e5c02db1e55d092afb4462f310370",
          "sha1": "ef2947f1f165ca2beee54265a5fca923bfa786f9",
          "md5": "1d86494e239cc50820bcde2151d5efaa"
        }
      ]
    }
  ]
}
