{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "2srzxppmvjc5vd43bqta6w4bpi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200209.161919-2.jar",
          "size": 2265681,
          "sha512": "46b9aed39caf0df5484421626c684fc9807c17500d0ba5c78f570b235aa09d8a5ea303b2278783197a4c4ed445628b08128f4bf13e660f57b8ecefbf9515eaee",
          "sha256": "1293674e6cb9da490fe33cd2375f9e90be6b0f5f47de1797d552cc31831a6dcf",
          "sha1": "a3c283fe25b98c24c28d03a340911cec7a82b25c",
          "md5": "60e6a63d6d76f9cd51e7895ebf03aa12"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200209.161919-2.jar",
          "size": 2265681,
          "sha512": "46b9aed39caf0df5484421626c684fc9807c17500d0ba5c78f570b235aa09d8a5ea303b2278783197a4c4ed445628b08128f4bf13e660f57b8ecefbf9515eaee",
          "sha256": "1293674e6cb9da490fe33cd2375f9e90be6b0f5f47de1797d552cc31831a6dcf",
          "sha1": "a3c283fe25b98c24c28d03a340911cec7a82b25c",
          "md5": "60e6a63d6d76f9cd51e7895ebf03aa12"
        }
      ]
    }
  ]
}
