{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "zob7h3yxe5hupnktgt4o4os32e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200130.102034-2.jar",
          "size": 2264669,
          "sha512": "bb45c7bce8b22993b3b582eb56d90dabdc030cdf1af611f733b9aa47d600df5311f74fa4cf26ec7a2e52e9cdb1b93709d32b8869664a8a3fb9596b0b3b54b758",
          "sha256": "5b7f185fa0896b82bb239bee7ecbdd76aea4eccd18838f8cc11b0f069fbd6aa0",
          "sha1": "b44b5af408712bea12088511522fe5bb4560c2aa",
          "md5": "45c747b25dfbfb567203dbe4c28f89ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200130.102034-2.jar",
          "size": 2264669,
          "sha512": "bb45c7bce8b22993b3b582eb56d90dabdc030cdf1af611f733b9aa47d600df5311f74fa4cf26ec7a2e52e9cdb1b93709d32b8869664a8a3fb9596b0b3b54b758",
          "sha256": "5b7f185fa0896b82bb239bee7ecbdd76aea4eccd18838f8cc11b0f069fbd6aa0",
          "sha1": "b44b5af408712bea12088511522fe5bb4560c2aa",
          "md5": "45c747b25dfbfb567203dbe4c28f89ba"
        }
      ]
    }
  ]
}
