{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "oz3lwfovprdh7luxs6u2rzfbu4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200206.153326-1.jar",
          "size": 2265655,
          "sha512": "6ab5ada83f97f14a97322938ddcdf2e2aa9416eb081f2cacc8ead5bb06fcde01822461cbd085e4f8aa65880f47ccc3034f0e3dac5fe5347c9a8a490f09e6949a",
          "sha256": "6ebdef0f5c6c08ee6b72fffab2ce36f8e8e252fe21844999fd5cf27a1d6a82cb",
          "sha1": "b26c6550e01e39ac29d81ae69739b97196461440",
          "md5": "9b581ff7e717edc5194033ba157a5cd8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200206.153326-1.jar",
          "size": 2265655,
          "sha512": "6ab5ada83f97f14a97322938ddcdf2e2aa9416eb081f2cacc8ead5bb06fcde01822461cbd085e4f8aa65880f47ccc3034f0e3dac5fe5347c9a8a490f09e6949a",
          "sha256": "6ebdef0f5c6c08ee6b72fffab2ce36f8e8e252fe21844999fd5cf27a1d6a82cb",
          "sha1": "b26c6550e01e39ac29d81ae69739b97196461440",
          "md5": "9b581ff7e717edc5194033ba157a5cd8"
        }
      ]
    }
  ]
}
