{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "lhkwaiydozhkvfr6zsixl6g2ge"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.1.jar",
          "url": "http-api-3.3.1.jar",
          "size": 164097,
          "sha512": "a22c243950a1ec9feb72f0ae7c928ae72ef01760065ea9709b8308d7f36c79812b12d87dc4576c701d0f67feb95682a7d23eadee271a53719c590d0f22a44222",
          "sha256": "bc258a3182fd05548774d772f3039a656a62bb3d9d0e9e03b3b39f966077b97d",
          "sha1": "a3946f9f8a81b52dddb6051af4e6128591dc2e0b",
          "md5": "3ea115f263b19843f18433db9b87ea71"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.1.jar",
          "url": "http-api-3.3.1.jar",
          "size": 164097,
          "sha512": "a22c243950a1ec9feb72f0ae7c928ae72ef01760065ea9709b8308d7f36c79812b12d87dc4576c701d0f67feb95682a7d23eadee271a53719c590d0f22a44222",
          "sha256": "bc258a3182fd05548774d772f3039a656a62bb3d9d0e9e03b3b39f966077b97d",
          "sha1": "a3946f9f8a81b52dddb6051af4e6128591dc2e0b",
          "md5": "3ea115f263b19843f18433db9b87ea71"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.1-sources.jar",
          "url": "http-api-3.3.1-sources.jar",
          "size": 107156,
          "sha512": "517aa6e745edbc9ed1837e89e3dd36ffec3bf0f0432fc15aaaab2ce8cea7b52e6f133cb51eaee0e29d137dd94445656461dedb9ffe3a2d43aa4e86a391abe9a9",
          "sha256": "9159fcc17bb4a8bbdc4be1036cf8cc04f47f6f399f5fb29e145ddc7379cfab5b",
          "sha1": "9faf22c04941efad94fd8ac2f14aa1031f3ab024",
          "md5": "7e9aa16baf6cc0bf0857db9df04e705c"
        }
      ]
    }
  ]
}
