{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "i6hnybq5v5av3ljxmgzjnpzo2q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.1.jar",
          "url": "http-api-3.3.1.jar",
          "size": 164096,
          "sha512": "4aa5406c40da86701da7e24a524f481da003eb45cd1e17f2c5d93e670fc092edd32551150acf6a47d56ac0c9d7b5a0fae999c39ffb888703f6d4c07c74cc9f43",
          "sha256": "aab1e7ebb2139f60290fda75588e18fa223a8e320218a7ae78e4fd390f158b04",
          "sha1": "e4af490ecde3965e5ab380d7fd24d68ccc7304e6",
          "md5": "dc72c54fb5175c3c4f11ba23ce1984c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.1.jar",
          "url": "http-api-3.3.1.jar",
          "size": 164096,
          "sha512": "4aa5406c40da86701da7e24a524f481da003eb45cd1e17f2c5d93e670fc092edd32551150acf6a47d56ac0c9d7b5a0fae999c39ffb888703f6d4c07c74cc9f43",
          "sha256": "aab1e7ebb2139f60290fda75588e18fa223a8e320218a7ae78e4fd390f158b04",
          "sha1": "e4af490ecde3965e5ab380d7fd24d68ccc7304e6",
          "md5": "dc72c54fb5175c3c4f11ba23ce1984c2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.1-sources.jar",
          "url": "http-api-3.3.1-sources.jar",
          "size": 107156,
          "sha512": "a376306a151ae4f545baccc26011b8256e6a71f594b3c42a7b997b40371e734cd15cf6679175d6969a87deeb722df03ff2523a06b5fffbe537904fbf6da5f478",
          "sha256": "9262e7112e05783078f31892053bdd67092b9532f262d05ec8a141f1fb5e9b3b",
          "sha1": "cf10da8c46152e014ff75ef0c48f8ed38e196d05",
          "md5": "cd85942cef94391cb4f04608ee3acd7a"
        }
      ]
    }
  ]
}
