{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "u26iuusievfdjnxsrm3fkg4jou"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.1.jar",
          "url": "http-api-3.3.1.jar",
          "size": 164098,
          "sha512": "57dbea371cbe9d71fdbbe46be18ee47ae3749c1bbec3a5d917e773aacc27a4162800619110e3c30398bde16deb9fbe5ab025ad313853e770cdf276322809d337",
          "sha256": "4cdf39b93abb5fab4ddfac04262303e2e8cfd84b5e1a5b8b3ce17b0d4f973b36",
          "sha1": "26820c07b3e03acf19d0c7b908f3dbfed706b9fb",
          "md5": "9ccbe0e9b8ce181d00b3d87dddaffc66"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.1.jar",
          "url": "http-api-3.3.1.jar",
          "size": 164098,
          "sha512": "57dbea371cbe9d71fdbbe46be18ee47ae3749c1bbec3a5d917e773aacc27a4162800619110e3c30398bde16deb9fbe5ab025ad313853e770cdf276322809d337",
          "sha256": "4cdf39b93abb5fab4ddfac04262303e2e8cfd84b5e1a5b8b3ce17b0d4f973b36",
          "sha1": "26820c07b3e03acf19d0c7b908f3dbfed706b9fb",
          "md5": "9ccbe0e9b8ce181d00b3d87dddaffc66"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.1-sources.jar",
          "url": "http-api-3.3.1-sources.jar",
          "size": 107156,
          "sha512": "a3991e402e177460407a39f1a819d6608be19430a9d5a96cb6b802fc3445c0ab2cc080c3d8e84a5fca0002dbf6f619f203ef9a2df9d86f0ea5718fdc5a2f5e30",
          "sha256": "a2ed55c06e3e9764a63aad94eb186bc572c860c9190376bd26ee4ef5e62d4ea3",
          "sha1": "30fbfca96ba70626b8cbd5188e25ee0989d1ebd5",
          "md5": "9d002bf228c2815951b789f698e252b5"
        }
      ]
    }
  ]
}
