{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "jeap5e74azajlbcyaiurdfhiga"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.9.jar",
          "url": "runelite-api-1.6.9.jar",
          "size": 1162957,
          "sha512": "703dfd15cc8db4b9a9006be147bda0858049f35eb06da88ffe561ef324709234266da3bbdffdf22ced3f73397d152fb745786a060bcea7fd64d4ebbb15134258",
          "sha256": "a6462c4dc7117afa4fc732220f0d92303ccac1c5aead5ee36310afb86b8a6ac4",
          "sha1": "61e0fdb82be7e98fbc986ead09882e4809ab2446",
          "md5": "ad23ef33edf14a9932fa88b6445a2642"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.9.jar",
          "url": "runelite-api-1.6.9.jar",
          "size": 1162957,
          "sha512": "703dfd15cc8db4b9a9006be147bda0858049f35eb06da88ffe561ef324709234266da3bbdffdf22ced3f73397d152fb745786a060bcea7fd64d4ebbb15134258",
          "sha256": "a6462c4dc7117afa4fc732220f0d92303ccac1c5aead5ee36310afb86b8a6ac4",
          "sha1": "61e0fdb82be7e98fbc986ead09882e4809ab2446",
          "md5": "ad23ef33edf14a9932fa88b6445a2642"
        }
      ]
    }
  ]
}
