{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "7qfsywvzyveczfcfgmdtcxye2a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.9.jar",
          "url": "runelite-api-1.6.9.jar",
          "size": 1162158,
          "sha512": "b8dd3602ee25ce1e30e863d75fe765cc301ae4cd40916b3928ce4099951b8e62d04262b2d57499097bbe25966c2c76616dd418e5fdb1fed6696ee46ff0d15e4b",
          "sha256": "0cf26fee3a1e0c17c1d74cf1d345ceddf4f73cddcd884cb3af4fbed190f1b109",
          "sha1": "3e6d837c2c1160ef04282532f5da0e5529d477f3",
          "md5": "775f071331ab4a78521d5d9be378361a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.9.jar",
          "url": "runelite-api-1.6.9.jar",
          "size": 1162158,
          "sha512": "b8dd3602ee25ce1e30e863d75fe765cc301ae4cd40916b3928ce4099951b8e62d04262b2d57499097bbe25966c2c76616dd418e5fdb1fed6696ee46ff0d15e4b",
          "sha256": "0cf26fee3a1e0c17c1d74cf1d345ceddf4f73cddcd884cb3af4fbed190f1b109",
          "sha1": "3e6d837c2c1160ef04282532f5da0e5529d477f3",
          "md5": "775f071331ab4a78521d5d9be378361a"
        }
      ]
    }
  ]
}
