{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "5k3z4g54xfhcpjgt7ikx4ks7le"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.7.jar",
          "url": "runelite-api-3.3.7.jar",
          "size": 1214092,
          "sha512": "3ee973bdf1b37b0d836a4b5fb7b1acd416f684c52423ebd39be9f2d38067a3c2fd95da5c0541d6c79a01b4ab2fedff2dedbdd9b80d764ece824782e12dd1e401",
          "sha256": "e207ffb1121c7d975a9ffe1a1ef81b73e359900ea8c481074bdfd4960e24a995",
          "sha1": "ea969ace9f5abb915821a4a83cb19216eb670a33",
          "md5": "cec379b4b31f288063f1114de5288c38"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.7.jar",
          "url": "runelite-api-3.3.7.jar",
          "size": 1214092,
          "sha512": "3ee973bdf1b37b0d836a4b5fb7b1acd416f684c52423ebd39be9f2d38067a3c2fd95da5c0541d6c79a01b4ab2fedff2dedbdd9b80d764ece824782e12dd1e401",
          "sha256": "e207ffb1121c7d975a9ffe1a1ef81b73e359900ea8c481074bdfd4960e24a995",
          "sha1": "ea969ace9f5abb915821a4a83cb19216eb670a33",
          "md5": "cec379b4b31f288063f1114de5288c38"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.7-sources.jar",
          "url": "runelite-api-3.3.7-sources.jar",
          "size": 888865,
          "sha512": "8ea0769c90c9657606d7eb4e2f07b293e50f655e367f0bc3c887158087bd3bd58e87c57e4c55f258e7d65c40f417ee1e1eef40ff60cd42b6c84a86e6aa5e0ca4",
          "sha256": "29e533374fcb58ac5ffc85373001d7a625971507523290d877162bbd385aa426",
          "sha1": "1beaf1ee1b030b2946f059257b67346410013e14",
          "md5": "4aa4b6b0828bfd18e0e46ad4630ea5bf"
        }
      ]
    }
  ]
}
