{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "afq7fhtiknhbre6xb7ivkeez4m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.7.jar",
          "url": "runelite-api-3.3.7.jar",
          "size": 1214092,
          "sha512": "a635643febd5466e41eb3863bf1eb8b21f052303ffc34dbdbcec5b95d4ccebba95379b2890853becad6395374019f6c835ac7d1efb269d5ef892bf9ee50a33d7",
          "sha256": "4b17d0dbed43466970ffb2c8aa0e6c7bda3507ae9a0adc3480e255926a3d430e",
          "sha1": "eb373bc7b076bf8ec844687e5eb346021aba1b38",
          "md5": "43976157552dc23c601e1743f66e6c1a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.7.jar",
          "url": "runelite-api-3.3.7.jar",
          "size": 1214092,
          "sha512": "a635643febd5466e41eb3863bf1eb8b21f052303ffc34dbdbcec5b95d4ccebba95379b2890853becad6395374019f6c835ac7d1efb269d5ef892bf9ee50a33d7",
          "sha256": "4b17d0dbed43466970ffb2c8aa0e6c7bda3507ae9a0adc3480e255926a3d430e",
          "sha1": "eb373bc7b076bf8ec844687e5eb346021aba1b38",
          "md5": "43976157552dc23c601e1743f66e6c1a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.7-sources.jar",
          "url": "runelite-api-3.3.7-sources.jar",
          "size": 888865,
          "sha512": "4f8cf9a2c051b0ea173ebc6808e248dd1bf9b26f351f8a49ff1d594bb26cffbe88d8b403d58e9976bcc18f2c1cc9ce1a6a224f9afa833f993f191ed806dcfceb",
          "sha256": "2d820ba4f12071e632c8bc86a7fb984b7b3db36fd0d682c2badf0e881db7d907",
          "sha1": "4602f4d2037fcf8be59c7fcf2442ff6e6920209e",
          "md5": "4c91a51ae7ae7dc3f05ab7dbfc532e33"
        }
      ]
    }
  ]
}
