{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "yduguelltfgh3aps22qvkjjj2a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.3.jar",
          "url": "http-api-3.3.3.jar",
          "size": 164096,
          "sha512": "2362de1adb4f1f98ff90cf5ec03eee59364bfaca838a3c8419afc0a23ee931f28f4acdfd25034cb21841c876458a131f8b32ef055965a73ce186e91c74846746",
          "sha256": "6bff5355b5230e6d0d3feb6fc846dd15a1aecabdeef7397e20bf75341854984d",
          "sha1": "4e0158b42bc9f02c6af03be4de53dd81f654b735",
          "md5": "cdbad45494871d7c226eda56c58adcf0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.3.jar",
          "url": "http-api-3.3.3.jar",
          "size": 164096,
          "sha512": "2362de1adb4f1f98ff90cf5ec03eee59364bfaca838a3c8419afc0a23ee931f28f4acdfd25034cb21841c876458a131f8b32ef055965a73ce186e91c74846746",
          "sha256": "6bff5355b5230e6d0d3feb6fc846dd15a1aecabdeef7397e20bf75341854984d",
          "sha1": "4e0158b42bc9f02c6af03be4de53dd81f654b735",
          "md5": "cdbad45494871d7c226eda56c58adcf0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.3-sources.jar",
          "url": "http-api-3.3.3-sources.jar",
          "size": 107156,
          "sha512": "9e0f71bfe59dacef0e994f6b52f20b1e09997213729f509d9bd1685fe52fe99c3b4e61bd570b2181c4a04231dfbb43d1a6e6ff5930956c8cbafed17b9d2bd913",
          "sha256": "938d38daa5b84ea9f8b71725434ebfdeb7bf41d78179901e3e0facd584c179e1",
          "sha1": "6622fee4b80842de77d88fef15d15264af676388",
          "md5": "f1426bdd4e891a574dbf42c974f2ea4a"
        }
      ]
    }
  ]
}
