{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "wsjbma225vgvdb7zkkodlxsuhi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.3.jar",
          "url": "http-api-3.3.3.jar",
          "size": 164097,
          "sha512": "7a14cb3e9a14a7fb8e0f09ae83d40041b07eb7f1988aaa817765c9bab85bebafa6759a777029da2fc145e9a08dbf72009462914164360fba063bb94c88f20ee5",
          "sha256": "bb38711dfdd819e3b511bcb1288ef9858c08fafe1e41920e522f3bc1a37d6a30",
          "sha1": "6a7414f5b8efa028423d159c0356ec56cc55be2a",
          "md5": "182151f83df9dc70fb1273aabdd95ea4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.3.jar",
          "url": "http-api-3.3.3.jar",
          "size": 164097,
          "sha512": "7a14cb3e9a14a7fb8e0f09ae83d40041b07eb7f1988aaa817765c9bab85bebafa6759a777029da2fc145e9a08dbf72009462914164360fba063bb94c88f20ee5",
          "sha256": "bb38711dfdd819e3b511bcb1288ef9858c08fafe1e41920e522f3bc1a37d6a30",
          "sha1": "6a7414f5b8efa028423d159c0356ec56cc55be2a",
          "md5": "182151f83df9dc70fb1273aabdd95ea4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.3-sources.jar",
          "url": "http-api-3.3.3-sources.jar",
          "size": 107156,
          "sha512": "623c1c9191a563f4e0fe29b90947ce3cef72faa053c2ccc49c09d55c1fbf5625634c0f12e09d6c2e8395079163dc9c32f1078a89c2c8d0159d4083915aed3b30",
          "sha256": "faaabae3f7b375232785074f4ca4f415d63c118995c139445a83d3466cb7830c",
          "sha1": "d673da3e0634f8ec8eae9169861180c298f2ebef",
          "md5": "cc405152d4b9e21774c7887a3beef4ab"
        }
      ]
    }
  ]
}
