{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "dhpkaf5ijfdmfj7xzzgcfqagiy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.3.jar",
          "url": "http-api-3.3.3.jar",
          "size": 164096,
          "sha512": "3aab77c2fd1d1f80fa72cc2026b10f60d57f0c50c41fc12a5b1efb6ed168536112fa0c7088f00eebe0d81328b9ee75a411c857308afb478860a285f544428068",
          "sha256": "5992ddbf8751a4b03582b00b832300fb576aed21f0865e1834460b5056854e01",
          "sha1": "b2f70f59044ff0df5d2b2ad9ff8d5f22c7b629e2",
          "md5": "817c91651d704ecd46ed5e6e4f2a4ac2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.3.jar",
          "url": "http-api-3.3.3.jar",
          "size": 164096,
          "sha512": "3aab77c2fd1d1f80fa72cc2026b10f60d57f0c50c41fc12a5b1efb6ed168536112fa0c7088f00eebe0d81328b9ee75a411c857308afb478860a285f544428068",
          "sha256": "5992ddbf8751a4b03582b00b832300fb576aed21f0865e1834460b5056854e01",
          "sha1": "b2f70f59044ff0df5d2b2ad9ff8d5f22c7b629e2",
          "md5": "817c91651d704ecd46ed5e6e4f2a4ac2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.3-sources.jar",
          "url": "http-api-3.3.3-sources.jar",
          "size": 107156,
          "sha512": "75840217565f9566e6f8ef816bf79d7713a539515f3f801632ca972a93fe883eb3480e816e440968da983fd1052d6d716bfa07800b723b574a8a84439a37cb26",
          "sha256": "e5c2e8e46655c29f7b7d9b6619d8d89eba0708d25c884e1b9ebab526f233e3cf",
          "sha1": "11e03bdb2142f4876a9586496701771d79302a31",
          "md5": "60fa04598dc9128ba1d6af6fbe0ba577"
        }
      ]
    }
  ]
}
