{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "qdeubasjjzev3in6lrgy2mvbmi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.5.jar",
          "url": "injected-client-3.3.5.jar",
          "size": 2253602,
          "sha512": "b010e49a30c75ead175f9de6ee4642b62a4daf8225f5a112ba053090103ed14c53ca551fa6768b2b7127ac40809186ac65b742a31a57f95ff384752aec383485",
          "sha256": "7c3589b2d907832325adb93bd29d5672d38feb80f80ac9a5e5f2b090ac54c4a4",
          "sha1": "aa2785953173d93014d2dbdc9e46eff224a5c117",
          "md5": "a27d9a683d961c6ea69d08dad8ee180f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.5.jar",
          "url": "injected-client-3.3.5.jar",
          "size": 2253602,
          "sha512": "b010e49a30c75ead175f9de6ee4642b62a4daf8225f5a112ba053090103ed14c53ca551fa6768b2b7127ac40809186ac65b742a31a57f95ff384752aec383485",
          "sha256": "7c3589b2d907832325adb93bd29d5672d38feb80f80ac9a5e5f2b090ac54c4a4",
          "sha1": "aa2785953173d93014d2dbdc9e46eff224a5c117",
          "md5": "a27d9a683d961c6ea69d08dad8ee180f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.5-sources.jar",
          "url": "injected-client-3.3.5-sources.jar",
          "size": 261,
          "sha512": "401a32e33f901fe51e33ad1c7b648d5633e7c6b73572f05f1347248a469db514963ea0fa94a9c50848b4b0d949cc1455c4b706d47ca31e63fca7f4d0eec7c5af",
          "sha256": "dc43ea4b4517aa3e225a5c2f1cd85f9d141b9ada880178f42e7f1afb5c7fcc7f",
          "sha1": "da1ff0a45ece43eb1d82051589deac2b8675a7a9",
          "md5": "8f58575875d34224964acd42fafc33f4"
        },
        {
          "name": "injected-client-3.3.5.jar",
          "url": "injected-client-3.3.5.jar",
          "size": 2253602,
          "sha512": "b010e49a30c75ead175f9de6ee4642b62a4daf8225f5a112ba053090103ed14c53ca551fa6768b2b7127ac40809186ac65b742a31a57f95ff384752aec383485",
          "sha256": "7c3589b2d907832325adb93bd29d5672d38feb80f80ac9a5e5f2b090ac54c4a4",
          "sha1": "aa2785953173d93014d2dbdc9e46eff224a5c117",
          "md5": "a27d9a683d961c6ea69d08dad8ee180f"
        }
      ]
    }
  ]
}
