{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "jsxtqnulcbaztbezobk75lzuw4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.5.jar",
          "url": "injected-client-3.3.5.jar",
          "size": 2253684,
          "sha512": "226a25eeac6df637dfc02e082fe8785127d69c0c346f47b980eaca7b4aa15b155213a61f0f49563fcc04ad6c47b60ab30cd8ab9829982b0e26bf1a1eab4f3f5f",
          "sha256": "377dd24480f887a260f746a40ff179b0f517328a4c7e5b7cd20eaae66a92311b",
          "sha1": "adae33949fa132caa21a5cf6026ccd6ccac1c7e1",
          "md5": "6cbd39028cff682bbc0f1cb85b9ae67b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.5.jar",
          "url": "injected-client-3.3.5.jar",
          "size": 2253684,
          "sha512": "226a25eeac6df637dfc02e082fe8785127d69c0c346f47b980eaca7b4aa15b155213a61f0f49563fcc04ad6c47b60ab30cd8ab9829982b0e26bf1a1eab4f3f5f",
          "sha256": "377dd24480f887a260f746a40ff179b0f517328a4c7e5b7cd20eaae66a92311b",
          "sha1": "adae33949fa132caa21a5cf6026ccd6ccac1c7e1",
          "md5": "6cbd39028cff682bbc0f1cb85b9ae67b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.5-sources.jar",
          "url": "injected-client-3.3.5-sources.jar",
          "size": 261,
          "sha512": "8e0931b07a3a234bed5e11e5f2ba50cd1e55bec19d0c6fe5610ce36fc87deaeb5df468ca1541f1dc934d43aab0bd54838e10e701d92a7814a8426ef19c8a153d",
          "sha256": "c83a8ab30bbec865143254f184aee8fdbd43e7d2aba1699bcc66d958116e959f",
          "sha1": "242bf7d89499bc39931b87bcc614d4ec5c494168",
          "md5": "440e419d73830728affefaac7f52fe73"
        },
        {
          "name": "injected-client-3.3.5.jar",
          "url": "injected-client-3.3.5.jar",
          "size": 2253684,
          "sha512": "226a25eeac6df637dfc02e082fe8785127d69c0c346f47b980eaca7b4aa15b155213a61f0f49563fcc04ad6c47b60ab30cd8ab9829982b0e26bf1a1eab4f3f5f",
          "sha256": "377dd24480f887a260f746a40ff179b0f517328a4c7e5b7cd20eaae66a92311b",
          "sha1": "adae33949fa132caa21a5cf6026ccd6ccac1c7e1",
          "md5": "6cbd39028cff682bbc0f1cb85b9ae67b"
        }
      ]
    }
  ]
}
