{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "puuxp7ebnvgbpmc7vpeiaxefsa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.5.jar",
          "url": "injected-client-3.3.5.jar",
          "size": 2253573,
          "sha512": "caae2eb121f74a782ac230c6fa1715f0faa0139c227ab9ce9f72921fac1130fbae0763effdad9cfbe185ff96508bb2b5c860c6a67e675d36e43c12b5283bfb16",
          "sha256": "5398ffd3721dfe46fe88f2bc795ea207d71afdca0f27ab3b6e6514d3f2bbba8e",
          "sha1": "751f16bb4f6292ad478cbb12e776a99402b3cc17",
          "md5": "605bc1231e5e4b19755acbc6ff547648"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.5.jar",
          "url": "injected-client-3.3.5.jar",
          "size": 2253573,
          "sha512": "caae2eb121f74a782ac230c6fa1715f0faa0139c227ab9ce9f72921fac1130fbae0763effdad9cfbe185ff96508bb2b5c860c6a67e675d36e43c12b5283bfb16",
          "sha256": "5398ffd3721dfe46fe88f2bc795ea207d71afdca0f27ab3b6e6514d3f2bbba8e",
          "sha1": "751f16bb4f6292ad478cbb12e776a99402b3cc17",
          "md5": "605bc1231e5e4b19755acbc6ff547648"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.5-sources.jar",
          "url": "injected-client-3.3.5-sources.jar",
          "size": 261,
          "sha512": "00f852e3d98eabab4cf214179c851b5368ab8764283a62c70e0d386cdeb9fdc6952e8204eb206658e73af26afe10ceb653970d15466d2fd494d45610284acd40",
          "sha256": "cf3557fa8af78dbf9a632a3a7ef4b40a34f1f75f30ee3a3f2be39f1816a51cdb",
          "sha1": "6504345ffa83656fd64a21d5c67f834178ef7a8e",
          "md5": "e5ac219f7b71b5f4378f8b23d2768e69"
        },
        {
          "name": "injected-client-3.3.5.jar",
          "url": "injected-client-3.3.5.jar",
          "size": 2253573,
          "sha512": "caae2eb121f74a782ac230c6fa1715f0faa0139c227ab9ce9f72921fac1130fbae0763effdad9cfbe185ff96508bb2b5c860c6a67e675d36e43c12b5283bfb16",
          "sha256": "5398ffd3721dfe46fe88f2bc795ea207d71afdca0f27ab3b6e6514d3f2bbba8e",
          "sha1": "751f16bb4f6292ad478cbb12e776a99402b3cc17",
          "md5": "605bc1231e5e4b19755acbc6ff547648"
        }
      ]
    }
  ]
}
