{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "3xcuqhh27fbdpmcyy5i5cb3ivm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.4.jar",
          "url": "http-api-3.3.4.jar",
          "size": 153778,
          "sha512": "eb370a8cfe5d4213f0fa704a8f4615de2e97ede33b694769b0a2fc2512c503e4ca3d10025ef5cf4bda03a465cd6314f3f628b017f6127c97262bf2a9db1ee99f",
          "sha256": "406891809249f269a6dffe7d71864424501b1fa628de436e6c74c295b0ff0b11",
          "sha1": "cb5c069825746d7b6da34ce372eb5cca10cac93f",
          "md5": "5db469e76523926787334a47930da3d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.4.jar",
          "url": "http-api-3.3.4.jar",
          "size": 153778,
          "sha512": "eb370a8cfe5d4213f0fa704a8f4615de2e97ede33b694769b0a2fc2512c503e4ca3d10025ef5cf4bda03a465cd6314f3f628b017f6127c97262bf2a9db1ee99f",
          "sha256": "406891809249f269a6dffe7d71864424501b1fa628de436e6c74c295b0ff0b11",
          "sha1": "cb5c069825746d7b6da34ce372eb5cca10cac93f",
          "md5": "5db469e76523926787334a47930da3d4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.4-sources.jar",
          "url": "http-api-3.3.4-sources.jar",
          "size": 101852,
          "sha512": "147a6e5e4bfb08691685721a725c9a3834aaf830d024a77d2b229f66b76952531820f680bf36078517edae87693ecbe746999b63a94b9336b28882299ee2e5f6",
          "sha256": "dd8dea69ae330733094f7f457f29bf9a98d5d94106d4f370037cf610d7a1e142",
          "sha1": "a7c10ebbbf6423a2925f23aec2e82774fea2573a",
          "md5": "ae74d2859c984efe7b9240388788da07"
        }
      ]
    }
  ]
}
