{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "ag7kba57wnhh3fmqilynicfq5m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.4.jar",
          "url": "http-api-3.3.4.jar",
          "size": 164096,
          "sha512": "201ec6d43045e567bd6d87fad7f196dabbc0c19c6ebf63640c874313fa646fc8774d36212d7d96169f28e4a78b9c531b5591160bc9c748c7d09be03e3760b4c4",
          "sha256": "dc2aa0b8f2d33df23ae71d1544d9b9605d7adff3465183c5d6c85eed5ca46dda",
          "sha1": "5940b5af1ada0f7e53ea78b88c5d83c9dc55ac27",
          "md5": "7ae75f2d6570a53c5545a0336aaa089d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.4.jar",
          "url": "http-api-3.3.4.jar",
          "size": 164096,
          "sha512": "201ec6d43045e567bd6d87fad7f196dabbc0c19c6ebf63640c874313fa646fc8774d36212d7d96169f28e4a78b9c531b5591160bc9c748c7d09be03e3760b4c4",
          "sha256": "dc2aa0b8f2d33df23ae71d1544d9b9605d7adff3465183c5d6c85eed5ca46dda",
          "sha1": "5940b5af1ada0f7e53ea78b88c5d83c9dc55ac27",
          "md5": "7ae75f2d6570a53c5545a0336aaa089d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.4-sources.jar",
          "url": "http-api-3.3.4-sources.jar",
          "size": 107156,
          "sha512": "f983a8914b7a56c39ca5f2deaebf3432a6154679a0174c8444e2814bf9bb3e61290b863a821f299c7cb3b69b29d14efc72fcb9a13323195e77b5361324ae301f",
          "sha256": "36da7115162b14b63b6850deb2d45e6095e9858d445f910831267c27448248bf",
          "sha1": "ecca37714d60154b7393d4f210c47e784adf1981",
          "md5": "b06384695e30420acdd2aeb71bf59a52"
        }
      ]
    }
  ]
}
