{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "yrgrwxt35vgsnfumly2dkrrfcm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.9.jar",
          "url": "http-api-3.3.9.jar",
          "size": 154401,
          "sha512": "5f666cef8c4862b2f17c474e0423fb0e768bef289032fd168905aa2bef6d5e9ce171d6db5cc5227927287c118f1509a43265e81a01ba4a6d106e8597971fbe50",
          "sha256": "ce42a5c6e99334b831b933b8f4c09d0c86919b36bd193158404881638c372914",
          "sha1": "5db26dd727a2e649a6fc87ccca4469e07fba0b77",
          "md5": "25bd0ce210ae10248b4fe600cbe384fa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.9.jar",
          "url": "http-api-3.3.9.jar",
          "size": 154401,
          "sha512": "5f666cef8c4862b2f17c474e0423fb0e768bef289032fd168905aa2bef6d5e9ce171d6db5cc5227927287c118f1509a43265e81a01ba4a6d106e8597971fbe50",
          "sha256": "ce42a5c6e99334b831b933b8f4c09d0c86919b36bd193158404881638c372914",
          "sha1": "5db26dd727a2e649a6fc87ccca4469e07fba0b77",
          "md5": "25bd0ce210ae10248b4fe600cbe384fa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.9-sources.jar",
          "url": "http-api-3.3.9-sources.jar",
          "size": 101953,
          "sha512": "4f2cb01c7233546fed61b45fcc3e0b937313ae072addc0e9ff38a9693c0ac0d5897d759129d62d8d7414bc2f7eae741e6df53c27ea11abdc27caf713c06e9344",
          "sha256": "ae084bd837a8f3ac1bfcc2b6237ab8a53b39aea8a2b5035d4255263574409661",
          "sha1": "57b88c8604c71315d1fc15fd6c3de254883c2d23",
          "md5": "bdde84f52142173d48ef1d65c257e667"
        }
      ]
    }
  ]
}
