{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "jrf73pb77va5jdzg4hguqgamem"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.2.1.jar",
          "url": "injected-client-3.2.1.jar",
          "size": 2245481,
          "sha512": "51306d394eaf9c8e938dc55db5a59bd8c2e6c7dda814ba00baff6a38670560297444492022cfedceccf4d7b858e00ed2701b9fd5e8673c5d1d6c590e351e6b5b",
          "sha256": "f12149692133c27dfca69bc8bb20a0c91dc38018a910dc8cd5bc9cc0c368d1bd",
          "sha1": "1f6024026df7dfe1592ee552752e2e96003feabd",
          "md5": "781287732b164734a416293270582ce6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.2.1.jar",
          "url": "injected-client-3.2.1.jar",
          "size": 2245481,
          "sha512": "51306d394eaf9c8e938dc55db5a59bd8c2e6c7dda814ba00baff6a38670560297444492022cfedceccf4d7b858e00ed2701b9fd5e8673c5d1d6c590e351e6b5b",
          "sha256": "f12149692133c27dfca69bc8bb20a0c91dc38018a910dc8cd5bc9cc0c368d1bd",
          "sha1": "1f6024026df7dfe1592ee552752e2e96003feabd",
          "md5": "781287732b164734a416293270582ce6"
        }
      ]
    }
  ]
}
