{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "xzgq6zsu55ey7buzphtobuoczy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.2.1.jar",
          "url": "injected-client-3.2.1.jar",
          "size": 2246757,
          "sha512": "2294f3bf19a606e279d8f236ec79859bba3f3d491a4fc08e29df34ca89a8555e9d414e88e43c910e891416eb0799fcfc2da4d208f702cf34c08d4a8fd4fa5340",
          "sha256": "b88d51636fd3ae6b31cc64f4c5d0165795b730829ba82c1da0ada7e9adeec66c",
          "sha1": "04da321ca4a416d46d75394323cd881193dea6fd",
          "md5": "f288a3f1f7436a51a5538d4fe0247086"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.2.1.jar",
          "url": "injected-client-3.2.1.jar",
          "size": 2246757,
          "sha512": "2294f3bf19a606e279d8f236ec79859bba3f3d491a4fc08e29df34ca89a8555e9d414e88e43c910e891416eb0799fcfc2da4d208f702cf34c08d4a8fd4fa5340",
          "sha256": "b88d51636fd3ae6b31cc64f4c5d0165795b730829ba82c1da0ada7e9adeec66c",
          "sha1": "04da321ca4a416d46d75394323cd881193dea6fd",
          "md5": "f288a3f1f7436a51a5538d4fe0247086"
        }
      ]
    }
  ]
}
