{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "xtscfgf2trfa5mftalxltrxioi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.2.1.jar",
          "url": "injected-client-3.2.1.jar",
          "size": 2252068,
          "sha512": "ec97dab790432e5e1b320e0fb9e94ef856363601f794e482030add98c8a84cd607e68094801aca1025e8c8e9353159f3f5a43e3c09fd751de41680f645d698b2",
          "sha256": "7c4629f1c554bf97ad57a2ff80e6373c3e20ae7bf70a41e5b548390246707230",
          "sha1": "036f20b2588a2877d8decb67af896ed6768b95d8",
          "md5": "6a43288ee5b2b970523693ddfbf819b2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.2.1.jar",
          "url": "injected-client-3.2.1.jar",
          "size": 2252068,
          "sha512": "ec97dab790432e5e1b320e0fb9e94ef856363601f794e482030add98c8a84cd607e68094801aca1025e8c8e9353159f3f5a43e3c09fd751de41680f645d698b2",
          "sha256": "7c4629f1c554bf97ad57a2ff80e6373c3e20ae7bf70a41e5b548390246707230",
          "sha1": "036f20b2588a2877d8decb67af896ed6768b95d8",
          "md5": "6a43288ee5b2b970523693ddfbf819b2"
        }
      ]
    }
  ]
}
