{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "4ul7jtg465dw7nr65j4c2hnf7i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.0.jar",
          "url": "http-api-3.3.0.jar",
          "size": 164004,
          "sha512": "3c84e3457c126e02250a0f02419743388c30fe9166fefcdbaa4d3e0ee7c51a0ac14f6a2f28cc054c8b66c5d3d3a00ddf7eba2dabb35d16722cea28eff0b65085",
          "sha256": "b4633a30c1dcc726c40044fe8393276199cdc0336d6dc01959227e80fbe842eb",
          "sha1": "1286bba6df21143413709ed6a6fbc5f5ea91444b",
          "md5": "dfc26d88e1868d5cdbfce7e0282304c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.0.jar",
          "url": "http-api-3.3.0.jar",
          "size": 164004,
          "sha512": "3c84e3457c126e02250a0f02419743388c30fe9166fefcdbaa4d3e0ee7c51a0ac14f6a2f28cc054c8b66c5d3d3a00ddf7eba2dabb35d16722cea28eff0b65085",
          "sha256": "b4633a30c1dcc726c40044fe8393276199cdc0336d6dc01959227e80fbe842eb",
          "sha1": "1286bba6df21143413709ed6a6fbc5f5ea91444b",
          "md5": "dfc26d88e1868d5cdbfce7e0282304c8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.0-sources.jar",
          "url": "http-api-3.3.0-sources.jar",
          "size": 107148,
          "sha512": "dd9af0d3175f768acda2024986c4592f3413fdf69646a77f519c507c8e4af821239b112632967c781ae626e2966675d7b5d79281b13adec2f03343c6010c15a8",
          "sha256": "288bf9f433a823386555fdfeca6aa441a94127d38dbc891f993e83990962d8a6",
          "sha1": "d1dc3b1692aa3552ba9d715adda81f9c86a80e47",
          "md5": "8e98a7d43450ae4069dea7469e947b8d"
        }
      ]
    }
  ]
}
