{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "ofjaddfu3fcxnc5gpdvv35gy5e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.0.jar",
          "url": "http-api-3.3.0.jar",
          "size": 164003,
          "sha512": "b2174dfa9f4a7b54b6fa138652a40ce61f0c538bf7a476a3e12904fcc57df58a0cf4257b1f4558d6df353d22bfe40a2330169c756ef4c0bb1dd598716b75248a",
          "sha256": "73d74ca69378faae4a4b8f5901407cce3c3a2a0f885c8da0e9680c37cf63e893",
          "sha1": "f78da39bc93d5de2dc6b59cb85da9d1586ec6d78",
          "md5": "52e14618ce9de927b1a5c4162d8db163"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.0.jar",
          "url": "http-api-3.3.0.jar",
          "size": 164003,
          "sha512": "b2174dfa9f4a7b54b6fa138652a40ce61f0c538bf7a476a3e12904fcc57df58a0cf4257b1f4558d6df353d22bfe40a2330169c756ef4c0bb1dd598716b75248a",
          "sha256": "73d74ca69378faae4a4b8f5901407cce3c3a2a0f885c8da0e9680c37cf63e893",
          "sha1": "f78da39bc93d5de2dc6b59cb85da9d1586ec6d78",
          "md5": "52e14618ce9de927b1a5c4162d8db163"
        }
      ]
    }
  ]
}
