{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "okixqif5jraclolqnbcy2mxehu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.8.jar",
          "url": "runelite-api-1.6.8.jar",
          "size": 1162472,
          "sha512": "25faaf7e8afa978e1daacc84a41f82099942a0a991e4bfe470833400719942265d3d3c5dfeb4fd24e7384fcd5ec83eae8fbd7ba01724bdb371188d43fd23da16",
          "sha256": "954e1ae79fff0100c7243bb3592125a34b9bbdf09b0ce6926ca90263e19214d9",
          "sha1": "e03b655906b5bbb7468a8f7021a74d3652d45144",
          "md5": "8d24c53a7467e00fa9d47fa59198deac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.8.jar",
          "url": "runelite-api-1.6.8.jar",
          "size": 1162472,
          "sha512": "25faaf7e8afa978e1daacc84a41f82099942a0a991e4bfe470833400719942265d3d3c5dfeb4fd24e7384fcd5ec83eae8fbd7ba01724bdb371188d43fd23da16",
          "sha256": "954e1ae79fff0100c7243bb3592125a34b9bbdf09b0ce6926ca90263e19214d9",
          "sha1": "e03b655906b5bbb7468a8f7021a74d3652d45144",
          "md5": "8d24c53a7467e00fa9d47fa59198deac"
        }
      ]
    }
  ]
}
