{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "e7z5ufjozbe7tbyy2oqpi6h5by"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.1.0.jar",
          "url": "http-api-3.1.0.jar",
          "size": 164402,
          "sha512": "0998d0f42f2d07814c7c080a0587adda5057f9c29e1e56443926f2086aefe265c200e04f703a87b8b077a1c6c9eade8c9dd88c11c1dcdc5a04574729315a4944",
          "sha256": "6b24977b200bcd06bbba72ad6ca5281c77c1c7cdce6c9a6175a6ce6c340f9d6e",
          "sha1": "f5ff6bb915f306e295bdfddebb697f9ab2f2eec2",
          "md5": "fa2f284f3910bf2acb8a08f5232ce0a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.1.0.jar",
          "url": "http-api-3.1.0.jar",
          "size": 164402,
          "sha512": "0998d0f42f2d07814c7c080a0587adda5057f9c29e1e56443926f2086aefe265c200e04f703a87b8b077a1c6c9eade8c9dd88c11c1dcdc5a04574729315a4944",
          "sha256": "6b24977b200bcd06bbba72ad6ca5281c77c1c7cdce6c9a6175a6ce6c340f9d6e",
          "sha1": "f5ff6bb915f306e295bdfddebb697f9ab2f2eec2",
          "md5": "fa2f284f3910bf2acb8a08f5232ce0a5"
        }
      ]
    }
  ]
}
