{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "qcymmdy7tres5omlgfo2oo6cgu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.1.0.jar",
          "url": "http-api-3.1.0.jar",
          "size": 164404,
          "sha512": "4115c67ea2ad3368aac11b68d386d74597522fdd49389bac98876cd3faf08f65e0890f824bee011ce927a2565e6d89f480a964ad9508aac1453a1c6120e5d546",
          "sha256": "937b6ce20adaa5252584eb02717cc5759b739d00c2159f8ac30a04c607a7280b",
          "sha1": "bf82ab271b66fec5a1814cb53e438d8f76c63568",
          "md5": "c82cf4eb161012d994050621f78f4d00"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.1.0.jar",
          "url": "http-api-3.1.0.jar",
          "size": 164404,
          "sha512": "4115c67ea2ad3368aac11b68d386d74597522fdd49389bac98876cd3faf08f65e0890f824bee011ce927a2565e6d89f480a964ad9508aac1453a1c6120e5d546",
          "sha256": "937b6ce20adaa5252584eb02717cc5759b739d00c2159f8ac30a04c607a7280b",
          "sha1": "bf82ab271b66fec5a1814cb53e438d8f76c63568",
          "md5": "c82cf4eb161012d994050621f78f4d00"
        }
      ]
    }
  ]
}
