{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "5cp5ti5n4jh3jmfgke27mgxlti"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.1.0.jar",
          "url": "http-api-3.1.0.jar",
          "size": 164403,
          "sha512": "e916a95048cdc62281ab4d1c5f2521623372623426490668e7753aa68edf1d0d32d80131de9ed0c5fa4d6fc2e9daecb934c67dcc0f5798b7ac86556cc772b804",
          "sha256": "14bced52c3ff0b3245d5ee97cd777a36db94be3e9d9a1159d05705c93a568276",
          "sha1": "b2de302c3942701cbc92b2df4428dcb894f5b300",
          "md5": "5c1cac67cd23f027f7340d85b214679c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.1.0.jar",
          "url": "http-api-3.1.0.jar",
          "size": 164403,
          "sha512": "e916a95048cdc62281ab4d1c5f2521623372623426490668e7753aa68edf1d0d32d80131de9ed0c5fa4d6fc2e9daecb934c67dcc0f5798b7ac86556cc772b804",
          "sha256": "14bced52c3ff0b3245d5ee97cd777a36db94be3e9d9a1159d05705c93a568276",
          "sha1": "b2de302c3942701cbc92b2df4428dcb894f5b300",
          "md5": "5c1cac67cd23f027f7340d85b214679c"
        }
      ]
    }
  ]
}
