{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "otnd32ax2razbpxgqn4eqp6y24"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.4.1.jar",
          "url": "runelite-api-3.4.1.jar",
          "size": 1225232,
          "sha512": "3a0f6e3c2f235d3923389254319c49fc07a81b6a7b61b66ec81094903ba51ea176283ae6a87beb9b5f26c329d08fb8442121e9c8904d3783b5fd7bc312007bb0",
          "sha256": "9f9f1bbf8bf0d6ae4337eca42f9a56b875a08f0513042b31b05f3958ce951166",
          "sha1": "1c639002265d00bc326aab942b8a77fda8b47ea7",
          "md5": "288a16a56ed210ddc88aa6edf0b6ff74"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.4.1.jar",
          "url": "runelite-api-3.4.1.jar",
          "size": 1225232,
          "sha512": "3a0f6e3c2f235d3923389254319c49fc07a81b6a7b61b66ec81094903ba51ea176283ae6a87beb9b5f26c329d08fb8442121e9c8904d3783b5fd7bc312007bb0",
          "sha256": "9f9f1bbf8bf0d6ae4337eca42f9a56b875a08f0513042b31b05f3958ce951166",
          "sha1": "1c639002265d00bc326aab942b8a77fda8b47ea7",
          "md5": "288a16a56ed210ddc88aa6edf0b6ff74"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.4.1-sources.jar",
          "url": "runelite-api-3.4.1-sources.jar",
          "size": 898207,
          "sha512": "a4015c3367a5f01bd107a31faf5d2f37ba44b41aca1771a709e47bcdfa283717914d55797c6592bcc89d027d126b0ece9c9e5faa252556e4c17a398368c1d68e",
          "sha256": "5017d26295b8e702ec9821554dfd34f08bf9deb651a0987d5ddaec55759473cb",
          "sha1": "3c3cc761aa9895143cab3bf8b54dcb64a80b2f63",
          "md5": "e0a5ad3b9f0dae89b533b8527eae3c56"
        }
      ]
    }
  ]
}
