{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "atbknxixjbgaljjpvkhkmpgxrq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.0.jar",
          "url": "runescape-api-3.3.0.jar",
          "size": 103468,
          "sha512": "8f1118e6f1623d05418f8f62a6e617648a6bc46d35a33af745c8aabd5a9753c42a188c640c730c37d52a30eae97180bc24b1dc2f641822eea04b38eff416804f",
          "sha256": "f49e5d437408cf5698777682534a703961b7d19b3fa52f18bed86412f4baf277",
          "sha1": "7f1301f6e7ad83746c85115cb3a5db4a031087b6",
          "md5": "eccf3d54b7501b4a100fec80c795d5a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.0.jar",
          "url": "runescape-api-3.3.0.jar",
          "size": 103468,
          "sha512": "8f1118e6f1623d05418f8f62a6e617648a6bc46d35a33af745c8aabd5a9753c42a188c640c730c37d52a30eae97180bc24b1dc2f641822eea04b38eff416804f",
          "sha256": "f49e5d437408cf5698777682534a703961b7d19b3fa52f18bed86412f4baf277",
          "sha1": "7f1301f6e7ad83746c85115cb3a5db4a031087b6",
          "md5": "eccf3d54b7501b4a100fec80c795d5a0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.0-sources.jar",
          "url": "runescape-api-3.3.0-sources.jar",
          "size": 99524,
          "sha512": "2075dfb8edc470789ba21ac65d3bba9924ef1e2b8b7fd72add0437cd8a20a41f23b7a184f96ee329d511f2509480a98470f37f1fc8db15df972b413acd283926",
          "sha256": "98864d0222141cb4aebf4df135ac52af063d3cb481b690bb95e6f437377c08f7",
          "sha1": "ac3c7f18f051f4ca4fbed3e5bc528f530ccc893e",
          "md5": "fe3d6889585c4b0df2c36018eeab6ea6"
        }
      ]
    }
  ]
}
