{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "ttjj6ca3xjcddcha25sjayvqi4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      }
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.4.5.jar",
          "url": "injected-client-3.4.5.jar",
          "size": 2263590,
          "sha512": "7846f47990c90a6c5b4009b7e85f8ff04ef6c8d1594ed6bb5fb65d1904f8635dbb1d7cb03a2948225b740d53cf98d114089406a764e5416db3df31f33e74b109",
          "sha256": "ff4a11a4779faac3783620465b26f738cc47698e43eeb54c088389af49a12f3e",
          "sha1": "039ba16f340cfb1fc50dce26ff1cb5ef4d4537ef",
          "md5": "b6aed387e3e2dfbfa7c3dbdba456d561"
        }
      ]
    }
  ]
}
