{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "5k3z4g54xfhcpjgt7ikx4ks7le"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.7.jar",
          "url": "http-api-3.3.7.jar",
          "size": 154402,
          "sha512": "6dfd32ace5ba400c3c34b7de7171b23fe357af488f38a9b732f1d8f12f43f255f4bbf1de50e471d28e83145bad8fcd541410ec888d20f01c6dc4d9ca9863e532",
          "sha256": "897b1efcdeb5fef4565239b813193f2e4ccbb299abecfe58cfb43d9f4d22492f",
          "sha1": "e302cc830d06322a046c6740d39bbff89e412758",
          "md5": "037161d1ba85ba50603b94d24887b9a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.7.jar",
          "url": "http-api-3.3.7.jar",
          "size": 154402,
          "sha512": "6dfd32ace5ba400c3c34b7de7171b23fe357af488f38a9b732f1d8f12f43f255f4bbf1de50e471d28e83145bad8fcd541410ec888d20f01c6dc4d9ca9863e532",
          "sha256": "897b1efcdeb5fef4565239b813193f2e4ccbb299abecfe58cfb43d9f4d22492f",
          "sha1": "e302cc830d06322a046c6740d39bbff89e412758",
          "md5": "037161d1ba85ba50603b94d24887b9a4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.7-sources.jar",
          "url": "http-api-3.3.7-sources.jar",
          "size": 101953,
          "sha512": "bbbdaab057e9c524b249a1a93e19364e526796dcf30a050140ca684c97e84d990b027c65b75680af25844f0c35f698dbf7600d3ffd062c50c919e230f1e48490",
          "sha256": "8c71774e24cb95e5ad15013f0a9aeb28f523c6837e6d8f30678b99229d9b4680",
          "sha1": "92fd865d74b7f2d225900032fdf018b62e3e1b80",
          "md5": "dc2c482275b8c47fb075b8c364cb8c1b"
        }
      ]
    }
  ]
}
