{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "azdorqxvd5gqlic5iruzqx6z3i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.7.jar",
          "url": "http-api-3.3.7.jar",
          "size": 154402,
          "sha512": "9e9ff2883c9d36ecfd93ea64fdaa848c0daac7ec0f176677ee7aae0089e75b7eeed2522e1e5a8af666a7865b81217da5d4e5091ae1d72fc4ee025f925b75255e",
          "sha256": "b7bd759bcdcddb987b120415ee180173099df6fc81685156b5e98be945cd370d",
          "sha1": "37084ff034b8a29b88cb15e7f26762aae4fa05df",
          "md5": "b547192811c57f2e65454bcb43035e5b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.7.jar",
          "url": "http-api-3.3.7.jar",
          "size": 154402,
          "sha512": "9e9ff2883c9d36ecfd93ea64fdaa848c0daac7ec0f176677ee7aae0089e75b7eeed2522e1e5a8af666a7865b81217da5d4e5091ae1d72fc4ee025f925b75255e",
          "sha256": "b7bd759bcdcddb987b120415ee180173099df6fc81685156b5e98be945cd370d",
          "sha1": "37084ff034b8a29b88cb15e7f26762aae4fa05df",
          "md5": "b547192811c57f2e65454bcb43035e5b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.7-sources.jar",
          "url": "http-api-3.3.7-sources.jar",
          "size": 101953,
          "sha512": "0d83e40a798773c2c63bf1b9ed40fef98111fa75e771908ba282dc031afc9b8615648dc885574429422dc5a238d532b392904b1fc05e11798ffa4197c6dac918",
          "sha256": "0cdf12c789a4b1a4e6319cd308e925bbe4b836f90624cb1c708d2cc4f13eea21",
          "sha1": "0688b80aa40dd42285cad8e403a2f55704b82832",
          "md5": "a351bb2efbf0b07573dd0a08e8b90cd8"
        }
      ]
    }
  ]
}
