{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "pri662m42zb7vdjvwk5xly7g5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.7.jar",
          "url": "http-api-3.3.7.jar",
          "size": 154402,
          "sha512": "40e50f92dad61b0018ea1dce0e95d5ea3a4fffb94cd291b3c2d278f5735a8d5afa00898f9558e8ff8bc6f64d982c1b4a55285852250fbe9183ff8b7308e88ed3",
          "sha256": "6920391a4aa7dc70335159fac993fe17105377b35a6e95c56e7221b917916a1f",
          "sha1": "cd1cfc7cce625edf12f6c1e5a28fe5417398364a",
          "md5": "4d0c3fecc1a29e415c659e51fb861623"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.7.jar",
          "url": "http-api-3.3.7.jar",
          "size": 154402,
          "sha512": "40e50f92dad61b0018ea1dce0e95d5ea3a4fffb94cd291b3c2d278f5735a8d5afa00898f9558e8ff8bc6f64d982c1b4a55285852250fbe9183ff8b7308e88ed3",
          "sha256": "6920391a4aa7dc70335159fac993fe17105377b35a6e95c56e7221b917916a1f",
          "sha1": "cd1cfc7cce625edf12f6c1e5a28fe5417398364a",
          "md5": "4d0c3fecc1a29e415c659e51fb861623"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.7-sources.jar",
          "url": "http-api-3.3.7-sources.jar",
          "size": 101953,
          "sha512": "791fdf3979444ed8fd4cafd5023cddcbceeceae60325234d1d84e871459066066534833819cfe37e4f2196a2c6953e97a76dc119fe8e03b495a71d09ebb536cb",
          "sha256": "9aa0cc9acaeced61fb3087d87fb75dfef81da61de8050ea4f84c994ed67ba6a7",
          "sha1": "bc191142bb46308f7b4f602cebae968a0ed9b374",
          "md5": "0c1dd75ada1a7f72e2124c6a262e28bd"
        }
      ]
    }
  ]
}
