{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "qcoltfejfbbndddlyie4erlb5q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.1.0.jar",
          "url": "runelite-api-3.1.0.jar",
          "size": 1174484,
          "sha512": "2ae3ceef892b758265d40a6fc9a40514d6777b3cd8612b457c3ab1d42bad9e03dd0e1ed6b164452074f645e18dc5dff713d9fe182c2b21411aaaef3d2e5bd21e",
          "sha256": "e9a61e1871e0b8b56562f0800da0da68347b1f74eb88c49bb184214d6aecdc9e",
          "sha1": "cfab3eb5cbcab62cf53aaad2a20ea4cb4940369e",
          "md5": "b7db709bc700975c7c41e0abb62c4692"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.1.0.jar",
          "url": "runelite-api-3.1.0.jar",
          "size": 1174484,
          "sha512": "2ae3ceef892b758265d40a6fc9a40514d6777b3cd8612b457c3ab1d42bad9e03dd0e1ed6b164452074f645e18dc5dff713d9fe182c2b21411aaaef3d2e5bd21e",
          "sha256": "e9a61e1871e0b8b56562f0800da0da68347b1f74eb88c49bb184214d6aecdc9e",
          "sha1": "cfab3eb5cbcab62cf53aaad2a20ea4cb4940369e",
          "md5": "b7db709bc700975c7c41e0abb62c4692"
        }
      ]
    }
  ]
}
