{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "njaqswguivh3pfuopby53o5slu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.1.0.jar",
          "url": "runelite-api-3.1.0.jar",
          "size": 1167334,
          "sha512": "30d7af909d3daf03b4cac2e364736f2275addceec462655d2b2e43d056a0d212de695cae0c188d362f957d13559279af7dfd693074f7ca3b2adc3faf534a8388",
          "sha256": "e77cfed4ea5170e08353354eaf2a9fffeff98d970a351bbbe19062689ca0a32e",
          "sha1": "e3f8484a5a3bd0889449acb8c61b00f7a8a4c4cf",
          "md5": "b5ab9d61fa451d94e04f4e578f96782b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.1.0.jar",
          "url": "runelite-api-3.1.0.jar",
          "size": 1167334,
          "sha512": "30d7af909d3daf03b4cac2e364736f2275addceec462655d2b2e43d056a0d212de695cae0c188d362f957d13559279af7dfd693074f7ca3b2adc3faf534a8388",
          "sha256": "e77cfed4ea5170e08353354eaf2a9fffeff98d970a351bbbe19062689ca0a32e",
          "sha1": "e3f8484a5a3bd0889449acb8c61b00f7a8a4c4cf",
          "md5": "b5ab9d61fa451d94e04f4e578f96782b"
        }
      ]
    }
  ]
}
