{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "rkyunk5unfbt5fc7ug56oqq64a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.1.0.jar",
          "url": "runelite-api-3.1.0.jar",
          "size": 1164264,
          "sha512": "5133fcf6690de4a528e7070d8801812fc443f8d3b48b45bb3f451930a5fbf35d6d7d09a9b078f6b3b5046d2244ca4c387d617e560136c1e40de87567a5130f5f",
          "sha256": "0565cbeed022eabdcf84efd09518fc3fc4934557a224cda78b11e955eb6e65e2",
          "sha1": "8c1c574b6f3a44a793d7103629b64cc19cef1057",
          "md5": "f6c92d568376d4bc13299392d47fddbd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.1.0.jar",
          "url": "runelite-api-3.1.0.jar",
          "size": 1164264,
          "sha512": "5133fcf6690de4a528e7070d8801812fc443f8d3b48b45bb3f451930a5fbf35d6d7d09a9b078f6b3b5046d2244ca4c387d617e560136c1e40de87567a5130f5f",
          "sha256": "0565cbeed022eabdcf84efd09518fc3fc4934557a224cda78b11e955eb6e65e2",
          "sha1": "8c1c574b6f3a44a793d7103629b64cc19cef1057",
          "md5": "f6c92d568376d4bc13299392d47fddbd"
        }
      ]
    }
  ]
}
