{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "fvldghacfbckjmgoj444djr2ge"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.7.jar",
          "url": "http-api-1.6.7.jar",
          "size": 165767,
          "sha512": "50a756fada727b99608d4f58f39b0dc5cd5de8027bf029d367117fafda7dcd3bb92fe1a552c42f07cb7f52f456e176be83e629cdd0fbdbd17ecdf60ea45d3ef7",
          "sha256": "d7d90571e88e689dd2c49ef457467943fa20b39617c23a3b4c369fa72d3dd2fe",
          "sha1": "8a3bb49f611461cab0a14b0b1342ad729dbf95cd",
          "md5": "9211e621476f369027d1ece654cda99a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.7.jar",
          "url": "http-api-1.6.7.jar",
          "size": 165767,
          "sha512": "50a756fada727b99608d4f58f39b0dc5cd5de8027bf029d367117fafda7dcd3bb92fe1a552c42f07cb7f52f456e176be83e629cdd0fbdbd17ecdf60ea45d3ef7",
          "sha256": "d7d90571e88e689dd2c49ef457467943fa20b39617c23a3b4c369fa72d3dd2fe",
          "sha1": "8a3bb49f611461cab0a14b0b1342ad729dbf95cd",
          "md5": "9211e621476f369027d1ece654cda99a"
        }
      ]
    }
  ]
}
