{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "odg5knamwbaehhc5e3ideqdcju"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.7.jar",
          "url": "http-api-1.6.7.jar",
          "size": 165948,
          "sha512": "fbc3c6c7d9f045636f22b7ed4f45e580fff5ede63bfbed284e0006d64380d152bf179e8c8f23426c90ac3fd81f8c0b16f2715b43f5b14ae26200376f3a458e54",
          "sha256": "736533039062b853861b30c24aa1f4855a52ee767df91ae9d00c874c93c9f598",
          "sha1": "6a6ad6e3cf7e1828359a71b5ad24e1bdd013b7eb",
          "md5": "5c5a70c8630949d0d1d29582fbc9882c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.7.jar",
          "url": "http-api-1.6.7.jar",
          "size": 165948,
          "sha512": "fbc3c6c7d9f045636f22b7ed4f45e580fff5ede63bfbed284e0006d64380d152bf179e8c8f23426c90ac3fd81f8c0b16f2715b43f5b14ae26200376f3a458e54",
          "sha256": "736533039062b853861b30c24aa1f4855a52ee767df91ae9d00c874c93c9f598",
          "sha1": "6a6ad6e3cf7e1828359a71b5ad24e1bdd013b7eb",
          "md5": "5c5a70c8630949d0d1d29582fbc9882c"
        }
      ]
    }
  ]
}
