{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "dvgrgv5jv5fpvhst277gs744wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.7.jar",
          "url": "http-api-1.6.7.jar",
          "size": 165948,
          "sha512": "38c668532132a8afb1919b76f2dba3b33597ed45bc8b66df9627a0a514b2cf914c33b6de204cdc016a8b786a8b3e0eea4931fdde113fc67b639fe5b6a51db3b2",
          "sha256": "7279e655502cb7679c103b04b8d8db10f0450bf634bc7de5988e1ddcbf179c2c",
          "sha1": "863cd0a3642f39c5a40de373eb7acab4a4081e32",
          "md5": "b5b6fc3fce92f75002ff3d5d85a58340"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.7.jar",
          "url": "http-api-1.6.7.jar",
          "size": 165948,
          "sha512": "38c668532132a8afb1919b76f2dba3b33597ed45bc8b66df9627a0a514b2cf914c33b6de204cdc016a8b786a8b3e0eea4931fdde113fc67b639fe5b6a51db3b2",
          "sha256": "7279e655502cb7679c103b04b8d8db10f0450bf634bc7de5988e1ddcbf179c2c",
          "sha1": "863cd0a3642f39c5a40de373eb7acab4a4081e32",
          "md5": "b5b6fc3fce92f75002ff3d5d85a58340"
        }
      ]
    }
  ]
}
