{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "66kqjmg7lrg33guig5udmisnmy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.3.jar",
          "url": "http-api-3.3.3.jar",
          "size": 164096,
          "sha512": "4fe68b943cd8be5000a0bd23902817b81ac45c5954fb738476ba1285e536a5f83854b45e70e1ed93724083a3ce30ada624d0b3ebabfb8d6fbf2bb8b28a00d991",
          "sha256": "cced5a7cc82d99cbba6e3a0c5f1b9c2e61f10dfacd400d2c2f12fbe3a90cafe7",
          "sha1": "1b972845ea9e3990a18544dc1ff0e7d55381840d",
          "md5": "2994e68b14967dfc1ca504aef50e53df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.3.jar",
          "url": "http-api-3.3.3.jar",
          "size": 164096,
          "sha512": "4fe68b943cd8be5000a0bd23902817b81ac45c5954fb738476ba1285e536a5f83854b45e70e1ed93724083a3ce30ada624d0b3ebabfb8d6fbf2bb8b28a00d991",
          "sha256": "cced5a7cc82d99cbba6e3a0c5f1b9c2e61f10dfacd400d2c2f12fbe3a90cafe7",
          "sha1": "1b972845ea9e3990a18544dc1ff0e7d55381840d",
          "md5": "2994e68b14967dfc1ca504aef50e53df"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.3-sources.jar",
          "url": "http-api-3.3.3-sources.jar",
          "size": 107156,
          "sha512": "53c03f300ee791a0ffa230c5d78f43a9516192eaf3896d75096b8adac05b8239ae394792131595c90f8de2db36c78671892580404749cab91c3265a48e32a18b",
          "sha256": "7cd710b1285ffe3a8b253c92cbf2d82e5c9e601f2e76e27154c79c7a48232bc9",
          "sha1": "4a1aa0e9aabef2a0dcfc92e87c8bb69cbd615aa2",
          "md5": "8b716bcec6db0e94f6663f55fb52a2c5"
        }
      ]
    }
  ]
}
