{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "mfk5xstvi5a55d5dgo4g6qvpvu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.3.jar",
          "url": "runescape-api-3.3.3.jar",
          "size": 103485,
          "sha512": "8e58ccf831a584f0f1e42b2db889e615bfc5666c8a5108d1e62f0aa381ce18925fbfc53daa49e7c0bba827bcc36d3db537935dcfe6c4db9babc6c90a5c21d83c",
          "sha256": "2d3b391c9129f98a51df0fe97dad16bda770a834817684e447040920cfb409fd",
          "sha1": "662f2181bd14d30cef14f3156909f69600eeeb43",
          "md5": "680ac50e04869beec86022f293811642"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.3.jar",
          "url": "runescape-api-3.3.3.jar",
          "size": 103485,
          "sha512": "8e58ccf831a584f0f1e42b2db889e615bfc5666c8a5108d1e62f0aa381ce18925fbfc53daa49e7c0bba827bcc36d3db537935dcfe6c4db9babc6c90a5c21d83c",
          "sha256": "2d3b391c9129f98a51df0fe97dad16bda770a834817684e447040920cfb409fd",
          "sha1": "662f2181bd14d30cef14f3156909f69600eeeb43",
          "md5": "680ac50e04869beec86022f293811642"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.3-sources.jar",
          "url": "runescape-api-3.3.3-sources.jar",
          "size": 99587,
          "sha512": "7d150e1a78da1fe4fccc97104b27ad0712a408b917c0ea310ddd566d5245c5206a0e987c47beb7c80220b4aaa023cd917c34056aff6fb00692f61d6a8216d57f",
          "sha256": "36e3ca56b54b0128af0e3a39cc2a518bac4838a0ffc77e6dffd5867a00c5d6ac",
          "sha1": "e494be942b8f05b01b858efbc004abc48f6105ab",
          "md5": "1df1685b4abf29d3bb457800b216b29d"
        }
      ]
    }
  ]
}
