{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "aloehfunujhqdkgjobesvmrgci"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.3.jar",
          "url": "runescape-api-3.3.3.jar",
          "size": 103485,
          "sha512": "03d5f05859d55c036d6ff97e279cd4b7a9c56c7f350d743995eaec3e55507b645c8f3793b9e0d19b89f966bf22321e8cd9478f567c4bf8c82288406a6d1f533f",
          "sha256": "47afd0d06d2e5b8ab6a56de8c8876fafdbf2f390b10115c333a6af3ac6f32a97",
          "sha1": "f66b4ebbce6ae17e58918dc6f386514254f3ac55",
          "md5": "242f5d6a53afd9c445a20d07b7ee516f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.3.jar",
          "url": "runescape-api-3.3.3.jar",
          "size": 103485,
          "sha512": "03d5f05859d55c036d6ff97e279cd4b7a9c56c7f350d743995eaec3e55507b645c8f3793b9e0d19b89f966bf22321e8cd9478f567c4bf8c82288406a6d1f533f",
          "sha256": "47afd0d06d2e5b8ab6a56de8c8876fafdbf2f390b10115c333a6af3ac6f32a97",
          "sha1": "f66b4ebbce6ae17e58918dc6f386514254f3ac55",
          "md5": "242f5d6a53afd9c445a20d07b7ee516f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.3-sources.jar",
          "url": "runescape-api-3.3.3-sources.jar",
          "size": 99587,
          "sha512": "d700c728a2c9062bedf7810ee86a715be82843a8cb815ca04fc00767de32063586c418a931c10efcdc7622ce4d6830a257efb46a278ac4089a21e85da3188512",
          "sha256": "b3c240b15ff7fcb734b0b346177697a95354dc43d28eff780466d63a7e85ca5c",
          "sha1": "22677cb41ccd7176219aa25eb6ce4d92c15b243e",
          "md5": "9a20696d26d3f7edb91ddc57a099b37d"
        }
      ]
    }
  ]
}
