{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "ijoycxj25zhzndx2xhossoge7q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.3.jar",
          "url": "runescape-api-3.3.3.jar",
          "size": 103485,
          "sha512": "98319e0652dd2363a35e2767d92faf8513c49fe35f0b1498e9031f8743dfb3ce2476505f36c4ac99b358f02e58b248cc7bd34303614ef0a0453bdb712520f1d7",
          "sha256": "796bee43d9a2a67115da9430456c0c874a3e2e86cfe065226aa95a21b8223ac2",
          "sha1": "77215e5fd29027a8720fe1fea0b1d23e1860e232",
          "md5": "50e1d415e834971b8cf30fac5f0b00de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.3.jar",
          "url": "runescape-api-3.3.3.jar",
          "size": 103485,
          "sha512": "98319e0652dd2363a35e2767d92faf8513c49fe35f0b1498e9031f8743dfb3ce2476505f36c4ac99b358f02e58b248cc7bd34303614ef0a0453bdb712520f1d7",
          "sha256": "796bee43d9a2a67115da9430456c0c874a3e2e86cfe065226aa95a21b8223ac2",
          "sha1": "77215e5fd29027a8720fe1fea0b1d23e1860e232",
          "md5": "50e1d415e834971b8cf30fac5f0b00de"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.3-sources.jar",
          "url": "runescape-api-3.3.3-sources.jar",
          "size": 99587,
          "sha512": "73ca99525e8a00cb94dc2135944a834717eb05fc5d465556e3d8a96cad4c9e073b1e1bf1a0366805c5ae7064579144f23ec4cadc795e9259a4e11e08c42a5f8d",
          "sha256": "3fe9cf1970c1e867322e217f4289278446bc06370e12afe4f508d13b19b840a9",
          "sha1": "eb8e9fa024a50db6166cf384974ec8b637f21c86",
          "md5": "eff1cc93916257a5ae66613deb31eb9a"
        }
      ]
    }
  ]
}
