{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "7ukznm4zhfczpkbzlvj6brvxs4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.0.7.jar",
          "url": "runelite-api-3.0.7.jar",
          "size": 1162957,
          "sha512": "17408d02f791c9f998c54514ddca775f0832ac0ef9565aae415f51190e7833fa3badade826692d6668c110a394983b1c5ba0e32d12c34e8c6bd6d2e441c29365",
          "sha256": "96eb01c6622aa2dff4ee5e8a6c350968d37410773551c3f0dddf71ee231110e0",
          "sha1": "c7974f93471071d1cfe81ad7ebb8e86d5ba0e02a",
          "md5": "3d559ad2dc09d3483e80bdb3ec246984"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.0.7.jar",
          "url": "runelite-api-3.0.7.jar",
          "size": 1162957,
          "sha512": "17408d02f791c9f998c54514ddca775f0832ac0ef9565aae415f51190e7833fa3badade826692d6668c110a394983b1c5ba0e32d12c34e8c6bd6d2e441c29365",
          "sha256": "96eb01c6622aa2dff4ee5e8a6c350968d37410773551c3f0dddf71ee231110e0",
          "sha1": "c7974f93471071d1cfe81ad7ebb8e86d5ba0e02a",
          "md5": "3d559ad2dc09d3483e80bdb3ec246984"
        }
      ]
    }
  ]
}
