{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "fv3xrqpvcfgmllx27r5wuy7p5q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.0.7.jar",
          "url": "runelite-api-3.0.7.jar",
          "size": 1162957,
          "sha512": "61cdfb32a4402228a46885b46ff04e2bae03637731f8f076256da9384ff6d19236f4d6bc77070e2bd7aa9b88e9ec2652d85bf95f0407265b28e4cdc9dbf224f5",
          "sha256": "030650ee7b24aeeea7b16fad22312f807e7d01bb8d0cfd71c27458f813bf3c7d",
          "sha1": "c546d6353513a3466db3f34cc231c4c7782fa4f1",
          "md5": "84682d2f723ec475f625ab338a6a5fd3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.0.7.jar",
          "url": "runelite-api-3.0.7.jar",
          "size": 1162957,
          "sha512": "61cdfb32a4402228a46885b46ff04e2bae03637731f8f076256da9384ff6d19236f4d6bc77070e2bd7aa9b88e9ec2652d85bf95f0407265b28e4cdc9dbf224f5",
          "sha256": "030650ee7b24aeeea7b16fad22312f807e7d01bb8d0cfd71c27458f813bf3c7d",
          "sha1": "c546d6353513a3466db3f34cc231c4c7782fa4f1",
          "md5": "84682d2f723ec475f625ab338a6a5fd3"
        }
      ]
    }
  ]
}
