{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "g3zvmnnn2bbczgw7kbb45bq4kq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.1.0.jar",
          "url": "runescape-api-3.1.0.jar",
          "size": 55408,
          "sha512": "2d832fb35d2d38880b4a77c5e085d7d9bee104fa1a2127a28f32addb83874f989d31dfbe07025ab61d1bd03fa473e759f5348ba0b8e4b0a21f0ad9ebd492e06c",
          "sha256": "6a7e9859db7beb96cd8f94e34dcebe1517ad0b30641d0e9307a7846580311951",
          "sha1": "a9f4c0e0bb0af7abb57e4f7fae2cdde07561f3ac",
          "md5": "25b858890cba4f58a1b6344bec793e1e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.1.0.jar",
          "url": "runescape-api-3.1.0.jar",
          "size": 55408,
          "sha512": "2d832fb35d2d38880b4a77c5e085d7d9bee104fa1a2127a28f32addb83874f989d31dfbe07025ab61d1bd03fa473e759f5348ba0b8e4b0a21f0ad9ebd492e06c",
          "sha256": "6a7e9859db7beb96cd8f94e34dcebe1517ad0b30641d0e9307a7846580311951",
          "sha1": "a9f4c0e0bb0af7abb57e4f7fae2cdde07561f3ac",
          "md5": "25b858890cba4f58a1b6344bec793e1e"
        }
      ]
    }
  ]
}
