{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "xye5kk5muffe7bnunguohz2kmq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.1.0.jar",
          "url": "runescape-api-3.1.0.jar",
          "size": 55416,
          "sha512": "dd9fb69b6396a51c90e3e0e116ae1d692bd562184cf18cc6756b2b8032895dbf432e58a1ef9bc7fc426df7f58c24c30318a8c64f701d9911757ed52340cce2ef",
          "sha256": "8f2b91dc743406625bca7c5eabd9827cdd2f7cf3190b9dede30f2086d54b5b4a",
          "sha1": "7642e04014fdd69b7943540a7c56c3742037e29c",
          "md5": "92977307bdd222353aa76ffcedc151d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.1.0.jar",
          "url": "runescape-api-3.1.0.jar",
          "size": 55416,
          "sha512": "dd9fb69b6396a51c90e3e0e116ae1d692bd562184cf18cc6756b2b8032895dbf432e58a1ef9bc7fc426df7f58c24c30318a8c64f701d9911757ed52340cce2ef",
          "sha256": "8f2b91dc743406625bca7c5eabd9827cdd2f7cf3190b9dede30f2086d54b5b4a",
          "sha1": "7642e04014fdd69b7943540a7c56c3742037e29c",
          "md5": "92977307bdd222353aa76ffcedc151d4"
        }
      ]
    }
  ]
}
