{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "pov7w6lk5bai7fjaqkz3alhnxq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.1.jar",
          "url": "runescape-api-3.3.1.jar",
          "size": 103468,
          "sha512": "6639e89af20f6398cc9e7b60398a84c0bf8d14674463f34fddddd7aaff92704de1dc9151420d2543654bf0bb21bb73ce184c9cb98899a7322a38383ac6f06004",
          "sha256": "6a5f4428e8b6d138cacf1f98d937f8a0af402f0afd6281957703746460ae75b8",
          "sha1": "b5e6dc75dcfa4d2e43e9e416adb2c12f0ec5687a",
          "md5": "8a915a91bea97b6f766cb4905c5f6ac9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.1.jar",
          "url": "runescape-api-3.3.1.jar",
          "size": 103468,
          "sha512": "6639e89af20f6398cc9e7b60398a84c0bf8d14674463f34fddddd7aaff92704de1dc9151420d2543654bf0bb21bb73ce184c9cb98899a7322a38383ac6f06004",
          "sha256": "6a5f4428e8b6d138cacf1f98d937f8a0af402f0afd6281957703746460ae75b8",
          "sha1": "b5e6dc75dcfa4d2e43e9e416adb2c12f0ec5687a",
          "md5": "8a915a91bea97b6f766cb4905c5f6ac9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.1-sources.jar",
          "url": "runescape-api-3.3.1-sources.jar",
          "size": 99524,
          "sha512": "df5d89e6fc2aed9fb22b7cb8da30b2405ebf9908472d59a304ece9a5e68dc60d30532b41799e51c6ff899807c952ca8ac108396b38be7bf63e718d5627547605",
          "sha256": "328234b414a9f5879d63414f3040d01853cc9d40074948901f49fad519c7844d",
          "sha1": "ddb5bdaad07cc1b1d1a32e73815a4d19901a9300",
          "md5": "7963485964d17da2f9c2af5728564ec7"
        }
      ]
    }
  ]
}
