{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "k4agbpopejemjpekb3yzjxi3nu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.1.jar",
          "url": "runescape-api-3.3.1.jar",
          "size": 103468,
          "sha512": "afc371ba59febd19bbd444f3b4a70dcf6f454141422216e28699392b34a760b83b637b01a8cc3710a118756ca1ba6995b05fda22df4a3cffac40aedc4b9a0ffe",
          "sha256": "bc25f667e4471c39c1f39e4c23cfe6f3e1946c27a9c0bc42049005948a98d8a1",
          "sha1": "e22a6c5982961e5362ecb3351c26dbc92cd0f29b",
          "md5": "f7172b4e544ec035061bc36593bb1244"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.1.jar",
          "url": "runescape-api-3.3.1.jar",
          "size": 103468,
          "sha512": "afc371ba59febd19bbd444f3b4a70dcf6f454141422216e28699392b34a760b83b637b01a8cc3710a118756ca1ba6995b05fda22df4a3cffac40aedc4b9a0ffe",
          "sha256": "bc25f667e4471c39c1f39e4c23cfe6f3e1946c27a9c0bc42049005948a98d8a1",
          "sha1": "e22a6c5982961e5362ecb3351c26dbc92cd0f29b",
          "md5": "f7172b4e544ec035061bc36593bb1244"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.1-sources.jar",
          "url": "runescape-api-3.3.1-sources.jar",
          "size": 99524,
          "sha512": "221501f944b8c1ef45ff798551264bb5fb11979dfff0607ed0b56fc2ea1b6d6b56cf29005e4aa95ac5c6b00690dd185f4bfdea983fb4af1005781437a6b62839",
          "sha256": "d58259d9df0b2929e414072d2b287bb04c39b23eb03e210553d341248bf5355a",
          "sha1": "63b51c84cb835208106bb6f6e3c9dda3f1c5a1ca",
          "md5": "7e63132349723b338dcf441fd61fbf9e"
        }
      ]
    }
  ]
}
