{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "5jobdrexlvgszjyjphdmonnmk4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.1.jar",
          "url": "runescape-api-3.3.1.jar",
          "size": 103468,
          "sha512": "13ffaaae10897e65d0c8851dab376675f3c822d49bf200da7cbf93a39fad28a1fed9e841cdc33602d5274223c55d6e40dba23c805ee7e3a453d5c4c7c2decb96",
          "sha256": "775718d4f0e0b5335450d7574b49db7b607aab27dd19c49f94cb5e1797658522",
          "sha1": "e6feb47901c7d7c323848b9ce33b1251539fb225",
          "md5": "13667143e92fbd9e291f04c45103e989"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.1.jar",
          "url": "runescape-api-3.3.1.jar",
          "size": 103468,
          "sha512": "13ffaaae10897e65d0c8851dab376675f3c822d49bf200da7cbf93a39fad28a1fed9e841cdc33602d5274223c55d6e40dba23c805ee7e3a453d5c4c7c2decb96",
          "sha256": "775718d4f0e0b5335450d7574b49db7b607aab27dd19c49f94cb5e1797658522",
          "sha1": "e6feb47901c7d7c323848b9ce33b1251539fb225",
          "md5": "13667143e92fbd9e291f04c45103e989"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.1-sources.jar",
          "url": "runescape-api-3.3.1-sources.jar",
          "size": 99524,
          "sha512": "8bc0c1825d04ce820a8ab10ca67a8806b293e863133e5e8ae77b5efaf292058765d14fad187aa73966ff4920d2ee863d720dd3352360f67a1f0945b525084e88",
          "sha256": "5efcb1051331eda562e2d0c49fa06e13b2427fdd9b18ed2e4bdbda0114ccb82f",
          "sha1": "e4c811aad2f7c8efa6ba1be7615b6ad68f0960de",
          "md5": "a91d78b875c6d309026bc98ae9149b72"
        }
      ]
    }
  ]
}
