{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-client",
    "version": "3.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "nuncon336zeubambeenhobop2m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.8"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-client-3.3.8.jar",
          "url": "runelite-client-3.3.8.jar",
          "size": 2666045,
          "sha512": "9d42bad1f248413fc57e99515aae9f91f9df046e28a0a59daf73c035b4426b979bddc1183fcf0ecf23dab73dbe8aee12b5ff78f11e42acfff6d6f3c0fac07dc7",
          "sha256": "d33d92f8df42c1839e169a8f4661e571d42e12b47f6fb83a0279410da6e0b871",
          "sha1": "83e525ff64ef11e71bb665bda5e225429019b26d",
          "md5": "a44e30ce26b78347fb0949b0e5e80cc6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "4.2.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "guice",
              "type": "jar",
              "extension": "jar",
              "classifier": "no_aop"
            }
          }
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "1.4.200"
          }
        },
        {
          "group": "com.jakewharton.rxrelay3",
          "module": "rxrelay",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "org.jgroups",
          "module": "jgroups",
          "version": {
            "requires": "4.2.4.Final"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "net.runelite",
          "module": "discord",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.pushing-pixels",
          "module": "radiance-substance",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "19.0.0"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq",
          "version": {
            "requires": "3.13.2"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq-codegen",
          "version": {
            "requires": "3.13.2"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq-meta",
          "version": {
            "requires": "3.13.2"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-logback",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.github.zafarkhaja",
          "module": "java-semver",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.pf4j",
          "module": "pf4j",
          "version": {
            "requires": "3.3.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.pf4j",
          "module": "pf4j-update",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "http-api",
          "version": {
            "requires": "3.3.8"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.8"
          }
        },
        {
          "group": "org.pushing-pixels",
          "module": "radiance-trident",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injected-client",
          "version": {
            "requires": "3.3.8"
          }
        },
        {
          "group": "com.openosrs.rs",
          "module": "runescape-api",
          "version": {
            "requires": "3.3.8"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-client-3.3.8.jar",
          "url": "runelite-client-3.3.8.jar",
          "size": 2666045,
          "sha512": "9d42bad1f248413fc57e99515aae9f91f9df046e28a0a59daf73c035b4426b979bddc1183fcf0ecf23dab73dbe8aee12b5ff78f11e42acfff6d6f3c0fac07dc7",
          "sha256": "d33d92f8df42c1839e169a8f4661e571d42e12b47f6fb83a0279410da6e0b871",
          "sha1": "83e525ff64ef11e71bb665bda5e225429019b26d",
          "md5": "a44e30ce26b78347fb0949b0e5e80cc6"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-client-3.3.8-shaded.jar",
          "url": "runelite-client-3.3.8-shaded.jar",
          "size": 31459447,
          "sha512": "af618e55f27d5389c9ef7bdeb1b6142ea3f06f9480217190853c159bc5cf667c412c333d8a50e33804d31ded1743b2cda9a278e6289ec7527258379debee58f7",
          "sha256": "193718a2bb6036873192361b2ba7c5513033a07e26bb188312edcc495e8d788c",
          "sha1": "66e3e0ba621dd118e0aa947323ca98d610470cb1",
          "md5": "15b8d55482371e5bee02a63a695b9118"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-client-3.3.8-sources.jar",
          "url": "runelite-client-3.3.8-sources.jar",
          "size": 2317458,
          "sha512": "0d0653e1a3164dff6826bb3eecc7c59abae629568ab539a3764163450b7c5027c9ddcafff923b99d011a2af3ca8b6000be15a6d89b7bff08025f84c551a5a2af",
          "sha256": "5ffd84a0850d5e894197c455b09bc5ff7fccc8326345a58eb521cc5dd2025122",
          "sha1": "8f1fe6e870670af1c63ee11984ec3a58fc1ffba1",
          "md5": "27201899b562d53cf6ef9c6351541c18"
        }
      ]
    }
  ]
}
