{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "2t4sl5lgpjdnvox77vxglkmcxu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.7.jar",
          "url": "runescape-api-1.6.7.jar",
          "size": 55336,
          "sha512": "5bf296dbf35b3c333327bbf15d4732bffe02a8caf8628429aa74c77cef8840697fab24ffe8e2567ba4cbee19baa8c1044c29278a2248c6df30660be7b49e27aa",
          "sha256": "7163d734b4d351c518acddf368f3dd37db52ee3f3bce7500f8f38a006f3429c8",
          "sha1": "beb77d91db5846d61ea9474739858578372d2f29",
          "md5": "b7c114ea8dac3f646dab445625a84649"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.7.jar",
          "url": "runescape-api-1.6.7.jar",
          "size": 55336,
          "sha512": "5bf296dbf35b3c333327bbf15d4732bffe02a8caf8628429aa74c77cef8840697fab24ffe8e2567ba4cbee19baa8c1044c29278a2248c6df30660be7b49e27aa",
          "sha256": "7163d734b4d351c518acddf368f3dd37db52ee3f3bce7500f8f38a006f3429c8",
          "sha1": "beb77d91db5846d61ea9474739858578372d2f29",
          "md5": "b7c114ea8dac3f646dab445625a84649"
        }
      ]
    }
  ]
}
