{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "ohvik6533vgwjjlgurbourb26y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.7.jar",
          "url": "runescape-api-1.6.7.jar",
          "size": 55336,
          "sha512": "1e34a9ed41169d9e839c6ac4d4e361c78f0c9c573b598edd246599de7c94ad468294dc7fb089a1695e96382f45c44ee4daf744459665edc210ac97571d672700",
          "sha256": "6389bd6cf635d60e8c304260a6cd14c194c33dbfafd160e31932c6b6f07a4f7d",
          "sha1": "e9f492449833ea29dbca1961228714ec0537e6f1",
          "md5": "dbdd1e2b4e36807334f4fb5a820560f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.7.jar",
          "url": "runescape-api-1.6.7.jar",
          "size": 55336,
          "sha512": "1e34a9ed41169d9e839c6ac4d4e361c78f0c9c573b598edd246599de7c94ad468294dc7fb089a1695e96382f45c44ee4daf744459665edc210ac97571d672700",
          "sha256": "6389bd6cf635d60e8c304260a6cd14c194c33dbfafd160e31932c6b6f07a4f7d",
          "sha1": "e9f492449833ea29dbca1961228714ec0537e6f1",
          "md5": "dbdd1e2b4e36807334f4fb5a820560f4"
        }
      ]
    }
  ]
}
