{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-client",
    "version": "3.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "m4pd7tuy65cahdjhhfsxxupk44"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-client-3.3.3.jar",
          "url": "runelite-client-3.3.3.jar",
          "size": 2645598,
          "sha512": "3f5b241d006a0ea1a03fdbfc476fddca8a502501dab06fab955db486e5a40a25f56fb6f623fdc598f74bcfcbf45feb7aa200d161be73ae34427b09c1974b3f68",
          "sha256": "35711deb3dfac15e24f4b64a58afbe31b1b5594a053611031d6fd0d5aec3c187",
          "sha1": "7a3a4811ad62f62b6b076665c9965ab8e2923500",
          "md5": "4a7d8260dc2a4e83a9a7cd186f12d7ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "4.2.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "guice",
              "type": "jar",
              "extension": "jar",
              "classifier": "no_aop"
            }
          }
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "1.4.200"
          }
        },
        {
          "group": "com.openosrs.rxrelay3",
          "module": "rxrelay",
          "version": {
            "requires": "3.0.1-SNAPSHOT"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "org.jgroups",
          "module": "jgroups",
          "version": {
            "requires": "4.2.4.Final"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "net.runelite",
          "module": "discord",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "org.pushing-pixels",
          "module": "radiance-substance",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "19.0.0"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq",
          "version": {
            "requires": "3.13.2"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq-codegen",
          "version": {
            "requires": "3.13.2"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq-meta",
          "version": {
            "requires": "3.13.2"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-logback",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.github.zafarkhaja",
          "module": "java-semver",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.pf4j",
          "module": "pf4j",
          "version": {
            "requires": "3.3.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.pf4j",
          "module": "pf4j-update",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "http-api",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.pushing-pixels",
          "module": "radiance-trident",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injected-client",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.openosrs.rs",
          "module": "runescape-api",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-client-3.3.3.jar",
          "url": "runelite-client-3.3.3.jar",
          "size": 2645598,
          "sha512": "3f5b241d006a0ea1a03fdbfc476fddca8a502501dab06fab955db486e5a40a25f56fb6f623fdc598f74bcfcbf45feb7aa200d161be73ae34427b09c1974b3f68",
          "sha256": "35711deb3dfac15e24f4b64a58afbe31b1b5594a053611031d6fd0d5aec3c187",
          "sha1": "7a3a4811ad62f62b6b076665c9965ab8e2923500",
          "md5": "4a7d8260dc2a4e83a9a7cd186f12d7ff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-client-3.3.3-sources.jar",
          "url": "runelite-client-3.3.3-sources.jar",
          "size": 2334393,
          "sha512": "2e6e996bd8b44a85a6ce318863b2f2251c791bfaa1423b424cdaaf974601f7dcbe827985dc1beff5a652f5f139924c874c54006978c493386d4dc4898fc1d2b2",
          "sha256": "470367cdc4cd1aa6ca1e0658f866584e3d40880e7971e7f0aa8ef27bd0c0d31a",
          "sha1": "5dafe79c2fca6d08415c66853ac1b4659f17db91",
          "md5": "595f2773945f8edee8ed6e6d15f3d838"
        }
      ]
    }
  ]
}
