{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "deobfuscator",
    "version": "1.5.44-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "gcilidbgrbfjzfptqcfumthnsq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "deobfuscator-1.5.44-SNAPSHOT.jar",
          "url": "deobfuscator-1.5.44-SNAPSHOT.jar",
          "size": 583012,
          "sha512": "468d2198ea2ac23449458d90748dc968d92951103ccd6832276732557c1e41bb3bf240951b85716252f150b3523f84b0b01dadae8d052c4a702861ccc9ea2024",
          "sha256": "6b2d75c834d48ff3c7644cf65870a940c51ef37c935f41ad2e34a28598459f9a",
          "sha1": "88af88aa1d73b9e55bdb9c8ce3523121832bb12a",
          "md5": "71fe606ac4acd19d43d91f27127f0bec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "18.0.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "7.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.2"
          }
        },
        {
          "group": "net.runelite",
          "module": "fernflower",
          "version": {
            "requires": "07082019"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.29"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.5.44-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs.rs",
          "module": "runescape-api",
          "version": {
            "requires": "1.5.44-SNAPSHOT"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.29"
          }
        }
      ],
      "files": [
        {
          "name": "deobfuscator-1.5.44-SNAPSHOT.jar",
          "url": "deobfuscator-1.5.44-SNAPSHOT.jar",
          "size": 583012,
          "sha512": "468d2198ea2ac23449458d90748dc968d92951103ccd6832276732557c1e41bb3bf240951b85716252f150b3523f84b0b01dadae8d052c4a702861ccc9ea2024",
          "sha256": "6b2d75c834d48ff3c7644cf65870a940c51ef37c935f41ad2e34a28598459f9a",
          "sha1": "88af88aa1d73b9e55bdb9c8ce3523121832bb12a",
          "md5": "71fe606ac4acd19d43d91f27127f0bec"
        }
      ]
    }
  ]
}
