{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "p4awfcoohnfgrk3h777wlgfk5q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.6.jar",
          "url": "injected-client-1.6.6.jar",
          "size": 2265863,
          "sha512": "800a7c63934f4eaedc684d010d8ea2d137276540716ce506546a5d66f4d0cdc7e14afcad1b42c02c891b7d8a9654e25bb49b4a2b840ae200ed246a570879431c",
          "sha256": "e4c294a890c7c60e170be09fbd168d02f1f2b56d70f9b33b1f1dbbf39f332097",
          "sha1": "847ff1808d74438dac3c79ae755b260ef74b2b0b",
          "md5": "aa3bcf241e542621f123ade66ed0a9b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.6.jar",
          "url": "injected-client-1.6.6.jar",
          "size": 2265863,
          "sha512": "800a7c63934f4eaedc684d010d8ea2d137276540716ce506546a5d66f4d0cdc7e14afcad1b42c02c891b7d8a9654e25bb49b4a2b840ae200ed246a570879431c",
          "sha256": "e4c294a890c7c60e170be09fbd168d02f1f2b56d70f9b33b1f1dbbf39f332097",
          "sha1": "847ff1808d74438dac3c79ae755b260ef74b2b0b",
          "md5": "aa3bcf241e542621f123ade66ed0a9b9"
        }
      ]
    }
  ]
}
