{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "ppkx2vnvobgtpgb7auzjikr6sa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.6.jar",
          "url": "injected-client-1.6.6.jar",
          "size": 2265863,
          "sha512": "69935a05970e59d01f2c943a9a2c53e4e6d2788106ae8cd7238373c503924d01e2d51f48d9d0f407fc14a21271d87ec9dcbc6daed8053a35d359992fb1121d3b",
          "sha256": "7d77cbfdbd68b79c6ae5835e5cbcd76169dce5575012e0adb299751fcd6d1ba6",
          "sha1": "de006e188bcd645238a8cf08589400f2c2fd3cf0",
          "md5": "923527ab0dca3b717d8e1833870fd602"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.6.jar",
          "url": "injected-client-1.6.6.jar",
          "size": 2265863,
          "sha512": "69935a05970e59d01f2c943a9a2c53e4e6d2788106ae8cd7238373c503924d01e2d51f48d9d0f407fc14a21271d87ec9dcbc6daed8053a35d359992fb1121d3b",
          "sha256": "7d77cbfdbd68b79c6ae5835e5cbcd76169dce5575012e0adb299751fcd6d1ba6",
          "sha1": "de006e188bcd645238a8cf08589400f2c2fd3cf0",
          "md5": "923527ab0dca3b717d8e1833870fd602"
        }
      ]
    }
  ]
}
