{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "jnxocuj2g5eblo4ooxv4nrjtdm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.6.jar",
          "url": "injected-client-1.6.6.jar",
          "size": 2265863,
          "sha512": "9bac9d073e7e7060f50e2a47a0660a56d3edd3c7d5deca98586fd0962769a163fd9fa63bdbf4a111b9743d7b7696dc62552f4c190034ead44a7e27bcc107e8ce",
          "sha256": "03d04d48f3173833d026c1ab73380ffdc5ee4d23e58fa603814bbc5ab397ecdf",
          "sha1": "6a3ac386ce6fe56efa99bfbe833bdcdcdd926c3b",
          "md5": "325d09b4208ecda48e683267bf51ee55"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.6.jar",
          "url": "injected-client-1.6.6.jar",
          "size": 2265863,
          "sha512": "9bac9d073e7e7060f50e2a47a0660a56d3edd3c7d5deca98586fd0962769a163fd9fa63bdbf4a111b9743d7b7696dc62552f4c190034ead44a7e27bcc107e8ce",
          "sha256": "03d04d48f3173833d026c1ab73380ffdc5ee4d23e58fa603814bbc5ab397ecdf",
          "sha1": "6a3ac386ce6fe56efa99bfbe833bdcdcdd926c3b",
          "md5": "325d09b4208ecda48e683267bf51ee55"
        }
      ]
    }
  ]
}
