{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "kb4uttfxezeyfg22xp6r75tw7i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.9.jar",
          "url": "injected-client-1.6.9.jar",
          "size": 2266314,
          "sha512": "b9679c89fced56544c99907eb30cc3cc2bd969491204374fc99c4e5b1f001081694932249e6f0a2eddb11c93b0f708013a6c3ead190568c985c4d88da51dc651",
          "sha256": "59e006873db44f61f29dc8d9af08bc14b88ed6d6a8e473ff21197bf9c2f0e216",
          "sha1": "4e3660b43456ab6bfeb5a1b671da2af4ee012e64",
          "md5": "c09294d9c859c7e2dc70c1a48f13f0b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.9.jar",
          "url": "injected-client-1.6.9.jar",
          "size": 2266314,
          "sha512": "b9679c89fced56544c99907eb30cc3cc2bd969491204374fc99c4e5b1f001081694932249e6f0a2eddb11c93b0f708013a6c3ead190568c985c4d88da51dc651",
          "sha256": "59e006873db44f61f29dc8d9af08bc14b88ed6d6a8e473ff21197bf9c2f0e216",
          "sha1": "4e3660b43456ab6bfeb5a1b671da2af4ee012e64",
          "md5": "c09294d9c859c7e2dc70c1a48f13f0b9"
        }
      ]
    }
  ]
}
