{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "ikgdvzzfu5awlmc37vrcb7rkde"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.9.jar",
          "url": "injected-client-1.6.9.jar",
          "size": 2266379,
          "sha512": "fa602174df4e49279f98dcd440400cca9832e90e681b315f20b969caf24c45f81bc264c36c7766b35b35b7e179fe130ab7921b7dac6c75c75a9042fe335fa7bc",
          "sha256": "c0f5039f5ff8073387fcaa3165c5ba819304a7e859a6161864ccfae297d733ac",
          "sha1": "321e1050929abaeab5f57bb7aaf9947f413c122e",
          "md5": "64597fba6724fc5a030539cfc10a42b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.9.jar",
          "url": "injected-client-1.6.9.jar",
          "size": 2266379,
          "sha512": "fa602174df4e49279f98dcd440400cca9832e90e681b315f20b969caf24c45f81bc264c36c7766b35b35b7e179fe130ab7921b7dac6c75c75a9042fe335fa7bc",
          "sha256": "c0f5039f5ff8073387fcaa3165c5ba819304a7e859a6161864ccfae297d733ac",
          "sha1": "321e1050929abaeab5f57bb7aaf9947f413c122e",
          "md5": "64597fba6724fc5a030539cfc10a42b1"
        }
      ]
    }
  ]
}
