{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "mnnehigmyjgnvirkmfznj7zv5y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.9.jar",
          "url": "injected-client-1.6.9.jar",
          "size": 2266314,
          "sha512": "c05351619d0ebabca72668392f8212369c5fcb27c91eb74c06073069db25e6693e8cfea4c49530554842044c93241adba403736eca6779ff351c0db025281d84",
          "sha256": "91a3d159c055139b1815273f26dba4d27d1d4e713da1761fb9ba5b7ca6609a57",
          "sha1": "c3fb960ba659454b302d66460bbb596ea3312757",
          "md5": "0204d7cb6045f760ef2b2fe2a3b6e912"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.9.jar",
          "url": "injected-client-1.6.9.jar",
          "size": 2266314,
          "sha512": "c05351619d0ebabca72668392f8212369c5fcb27c91eb74c06073069db25e6693e8cfea4c49530554842044c93241adba403736eca6779ff351c0db025281d84",
          "sha256": "91a3d159c055139b1815273f26dba4d27d1d4e713da1761fb9ba5b7ca6609a57",
          "sha1": "c3fb960ba659454b302d66460bbb596ea3312757",
          "md5": "0204d7cb6045f760ef2b2fe2a3b6e912"
        }
      ]
    }
  ]
}
