{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "ctpmmvrxq5f55dwhudwelce6ge"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.4.3.jar",
          "url": "runelite-api-3.4.3.jar",
          "size": 1232470,
          "sha512": "c470ec9679d4582205dfae576f72e0c558114399d3b65e1cd35e239b856635f685f989cc9b20122fc64f8585d2d20b3aa73bb5e14e1d07542093bae4a2ff1464",
          "sha256": "d88643939ca2d60edbbb5dcfc8bdde3e0790b3e6553dfd2683c41d7c3ed09421",
          "sha1": "36bd0bdf66f582fe3c47af15236f52be5dd2b16d",
          "md5": "979034353431cd7463e26b45d9bc9743"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.4.3.jar",
          "url": "runelite-api-3.4.3.jar",
          "size": 1232470,
          "sha512": "c470ec9679d4582205dfae576f72e0c558114399d3b65e1cd35e239b856635f685f989cc9b20122fc64f8585d2d20b3aa73bb5e14e1d07542093bae4a2ff1464",
          "sha256": "d88643939ca2d60edbbb5dcfc8bdde3e0790b3e6553dfd2683c41d7c3ed09421",
          "sha1": "36bd0bdf66f582fe3c47af15236f52be5dd2b16d",
          "md5": "979034353431cd7463e26b45d9bc9743"
        }
      ]
    }
  ]
}
