{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "4nbdqkdu3rfw3acjxg3dhiorei"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.1.jar",
          "url": "injected-client-3.3.1.jar",
          "size": 2252631,
          "sha512": "3d5161b76d61ab40c6e94f1229d9de2bc21b291e3d65d030427fae17006a66eedcd1a0d30c2c33e5bb59788780f6bd7a8902a05d0552f97bc548374f204b7f27",
          "sha256": "4118ff2eef3e582371be26dcec03b15e05928496202251d1e6a31f6e206baf23",
          "sha1": "d060957457a84b82035aab6b0816b882565bfec4",
          "md5": "bf37b999d811843d7857254a9494b1d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.1.jar",
          "url": "injected-client-3.3.1.jar",
          "size": 2252631,
          "sha512": "3d5161b76d61ab40c6e94f1229d9de2bc21b291e3d65d030427fae17006a66eedcd1a0d30c2c33e5bb59788780f6bd7a8902a05d0552f97bc548374f204b7f27",
          "sha256": "4118ff2eef3e582371be26dcec03b15e05928496202251d1e6a31f6e206baf23",
          "sha1": "d060957457a84b82035aab6b0816b882565bfec4",
          "md5": "bf37b999d811843d7857254a9494b1d0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.1-sources.jar",
          "url": "injected-client-3.3.1-sources.jar",
          "size": 261,
          "sha512": "24816804321fdc881138d7cf77f23e8123455f0e195ffc319a6b06ad844cdbf306af6be3968df2433a308ed9dbb46c07bac83e5571c010c80a84cc4bea0c1d08",
          "sha256": "b3abcc8a7bd3721307c1b482d60882f4662c310a8bbaa9e00632cbc65cce12c6",
          "sha1": "a08caa671817246edcbba18dd0c3a1405cb08efa",
          "md5": "361c8e34a7d02253fd2c3535a7084fe5"
        },
        {
          "name": "injected-client-3.3.1.jar",
          "url": "injected-client-3.3.1.jar",
          "size": 2252631,
          "sha512": "3d5161b76d61ab40c6e94f1229d9de2bc21b291e3d65d030427fae17006a66eedcd1a0d30c2c33e5bb59788780f6bd7a8902a05d0552f97bc548374f204b7f27",
          "sha256": "4118ff2eef3e582371be26dcec03b15e05928496202251d1e6a31f6e206baf23",
          "sha1": "d060957457a84b82035aab6b0816b882565bfec4",
          "md5": "bf37b999d811843d7857254a9494b1d0"
        }
      ]
    }
  ]
}
