{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "5jobdrexlvgszjyjphdmonnmk4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.1.jar",
          "url": "injected-client-3.3.1.jar",
          "size": 2252631,
          "sha512": "dd513e2d514cbcd517aa83f9d0c8f41c77393d907a9cc22633bfd43371a4dbdda55d04ad47767f3b205a1d966b2e1e7568779d871203f101ecd470c62e3df8cf",
          "sha256": "187f144090948fb9d24f82d1e98fb7ed6b42566cb3e173fd6f7c2eaa17bbfcff",
          "sha1": "d7790303d8769a2937ff20f199fb212c9ca9e444",
          "md5": "63bddc2ce07c95be148aa8c6fca543ec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.1.jar",
          "url": "injected-client-3.3.1.jar",
          "size": 2252631,
          "sha512": "dd513e2d514cbcd517aa83f9d0c8f41c77393d907a9cc22633bfd43371a4dbdda55d04ad47767f3b205a1d966b2e1e7568779d871203f101ecd470c62e3df8cf",
          "sha256": "187f144090948fb9d24f82d1e98fb7ed6b42566cb3e173fd6f7c2eaa17bbfcff",
          "sha1": "d7790303d8769a2937ff20f199fb212c9ca9e444",
          "md5": "63bddc2ce07c95be148aa8c6fca543ec"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.1-sources.jar",
          "url": "injected-client-3.3.1-sources.jar",
          "size": 261,
          "sha512": "841548905711c99497a0908a809d2db55dcf07bd3742edf976daed23382397d0aee5e3f9daf4f03aaeb4a7442bb6b1d749ea5d226fc5f3fdd20d321233ffe2c2",
          "sha256": "3349adfde4e35a1652adb302bbfff269f7f72587a5d38b8e7e23a3a1e546be25",
          "sha1": "058eab25f72e9f3b612a625fe75247c0cf95534a",
          "md5": "1ae9f779e06125116b9dd07b21aae3ad"
        },
        {
          "name": "injected-client-3.3.1.jar",
          "url": "injected-client-3.3.1.jar",
          "size": 2252631,
          "sha512": "dd513e2d514cbcd517aa83f9d0c8f41c77393d907a9cc22633bfd43371a4dbdda55d04ad47767f3b205a1d966b2e1e7568779d871203f101ecd470c62e3df8cf",
          "sha256": "187f144090948fb9d24f82d1e98fb7ed6b42566cb3e173fd6f7c2eaa17bbfcff",
          "sha1": "d7790303d8769a2937ff20f199fb212c9ca9e444",
          "md5": "63bddc2ce07c95be148aa8c6fca543ec"
        }
      ]
    }
  ]
}
