{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "wz2qeqexwffqvpltgoizynxt6e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.1.jar",
          "url": "injected-client-3.3.1.jar",
          "size": 2252631,
          "sha512": "5c0a57217778558cb73618e90ff80655e6533803f89be7674797928259cb98310d93bc14f04c21deb2c61affefbd0cdc32b1fff9e7086a10a8f34e938d857085",
          "sha256": "5a3003f348468c40d7ade040ff8f316c8cee03a7a57b152f94ef9fd652c59adb",
          "sha1": "d931e7f9eade78334191f39c875640e708ceaa51",
          "md5": "83aa7a4ef2cf251350e478966df96fc5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.1.jar",
          "url": "injected-client-3.3.1.jar",
          "size": 2252631,
          "sha512": "5c0a57217778558cb73618e90ff80655e6533803f89be7674797928259cb98310d93bc14f04c21deb2c61affefbd0cdc32b1fff9e7086a10a8f34e938d857085",
          "sha256": "5a3003f348468c40d7ade040ff8f316c8cee03a7a57b152f94ef9fd652c59adb",
          "sha1": "d931e7f9eade78334191f39c875640e708ceaa51",
          "md5": "83aa7a4ef2cf251350e478966df96fc5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.1-sources.jar",
          "url": "injected-client-3.3.1-sources.jar",
          "size": 261,
          "sha512": "17de41c34af1ba0b71824b87d0d0373dae6fea2d534e38bee5eaa2f9e6d5771c80bbc890bf02bbd889554d63b997ef3a9c87f6529aba1a9a3424bef95b071841",
          "sha256": "d3eb445c62928120771a2aa5c706415d69689a0ff5aca73374c70c0c6f4746ce",
          "sha1": "89102ffdc8dd43d1ac35f9290238b81b7ad1517b",
          "md5": "1823a61f00f75a91c118ff98a7ad05d6"
        },
        {
          "name": "injected-client-3.3.1.jar",
          "url": "injected-client-3.3.1.jar",
          "size": 2252631,
          "sha512": "5c0a57217778558cb73618e90ff80655e6533803f89be7674797928259cb98310d93bc14f04c21deb2c61affefbd0cdc32b1fff9e7086a10a8f34e938d857085",
          "sha256": "5a3003f348468c40d7ade040ff8f316c8cee03a7a57b152f94ef9fd652c59adb",
          "sha1": "d931e7f9eade78334191f39c875640e708ceaa51",
          "md5": "83aa7a4ef2cf251350e478966df96fc5"
        }
      ]
    }
  ]
}
