{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "4ul7jtg465dw7nr65j4c2hnf7i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.0.jar",
          "url": "runelite-api-3.3.0.jar",
          "size": 1179684,
          "sha512": "7d45bdcd6902afd7a1f0f6d7ea39053791dd769ee056507e4678a177790d5388a6873679f0439ec8947bdf0ed3e7453716a4f55ac6636e4f7e1dd6a016ad4445",
          "sha256": "8315d106cd445bb9e6c495bfba5a69a13795fcc9a2d538393e6130b6a452b400",
          "sha1": "598b5074a5d11c235341e147ed3f385fda86213b",
          "md5": "a4b62ef98ff3043cccde80d5bbecdfe4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.0.jar",
          "url": "runelite-api-3.3.0.jar",
          "size": 1179684,
          "sha512": "7d45bdcd6902afd7a1f0f6d7ea39053791dd769ee056507e4678a177790d5388a6873679f0439ec8947bdf0ed3e7453716a4f55ac6636e4f7e1dd6a016ad4445",
          "sha256": "8315d106cd445bb9e6c495bfba5a69a13795fcc9a2d538393e6130b6a452b400",
          "sha1": "598b5074a5d11c235341e147ed3f385fda86213b",
          "md5": "a4b62ef98ff3043cccde80d5bbecdfe4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.0-sources.jar",
          "url": "runelite-api-3.3.0-sources.jar",
          "size": 865215,
          "sha512": "b3d59414e22f76cbf5510f5a122e215bf28f0b5cbf5555fc3921157984e4cdba239388eff9a6e4c9359828b3e460e7fe0cd50f2b39a4d03af927fe669cd2f5cb",
          "sha256": "ecc0ace74b5fb15e4750cfb089f013b7b361eb9163b98a9ffec26cf689d13a5e",
          "sha1": "0a7eb9837b6ad4bcee993ad3693309fdc888fe64",
          "md5": "6ba20c46d5d5d30e8a2ea0c33507f22c"
        }
      ]
    }
  ]
}
