{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "5pbwxfuunbb6flmlhxndwktfoi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.4.jar",
          "url": "runelite-api-3.3.4.jar",
          "size": 1183603,
          "sha512": "f49d06716b39dde77964e372538866e82026a6d8bcf8d3212a39552fee5337b2e42480c6eadeabc444ea43d1abce8e6f173cb14b0cf0ec7e894b852ac36040fb",
          "sha256": "424759293587edb8860d6b39d26d9352ca7b20095da2ade26f6b0fbcd1d3b7a0",
          "sha1": "6a498a3b745fa221d829273d78bee035af983e77",
          "md5": "4ee1b0d2aed43c00328cddaadd46b94e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.4.jar",
          "url": "runelite-api-3.3.4.jar",
          "size": 1183603,
          "sha512": "f49d06716b39dde77964e372538866e82026a6d8bcf8d3212a39552fee5337b2e42480c6eadeabc444ea43d1abce8e6f173cb14b0cf0ec7e894b852ac36040fb",
          "sha256": "424759293587edb8860d6b39d26d9352ca7b20095da2ade26f6b0fbcd1d3b7a0",
          "sha1": "6a498a3b745fa221d829273d78bee035af983e77",
          "md5": "4ee1b0d2aed43c00328cddaadd46b94e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.4-sources.jar",
          "url": "runelite-api-3.3.4-sources.jar",
          "size": 868075,
          "sha512": "087b2ef2676fcd554afd5441f00c227d588baf9e90ce84cbea4151364d505b94309a6f2307346588167d64f73adca92e80d93ba4035c808d74e6794a9f43e8d4",
          "sha256": "9d5a41f38be847d80d318646af9a1b40b4b2d76316b134128a3ca0a48f9b571b",
          "sha1": "835eb8c816c75a22d3053ef8860e46324767e12d",
          "md5": "e106e2ee3605cd2a2777e54132e0488f"
        }
      ]
    }
  ]
}
