{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "mvrzt6pw3jfrrcblinefu22cwi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.4.jar",
          "url": "runelite-api-3.3.4.jar",
          "size": 1183603,
          "sha512": "a45378b030cdbb00e468d3872a21cfd03bb3b71d4a4b01bc8e49fc4e45b4b024a717fbe17163ca3925d1ca93d654945c88f5c4738a0320c6d92b2bc08e3a1d72",
          "sha256": "20f22252261212e6ddd5a6928c002e8e5b7206664d3dad9b6028763d6faca818",
          "sha1": "978d356e989134cd0e5c9e3cb69c139b953391b0",
          "md5": "3e65a15d6c6243cc4f8fec917032376f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.4.jar",
          "url": "runelite-api-3.3.4.jar",
          "size": 1183603,
          "sha512": "a45378b030cdbb00e468d3872a21cfd03bb3b71d4a4b01bc8e49fc4e45b4b024a717fbe17163ca3925d1ca93d654945c88f5c4738a0320c6d92b2bc08e3a1d72",
          "sha256": "20f22252261212e6ddd5a6928c002e8e5b7206664d3dad9b6028763d6faca818",
          "sha1": "978d356e989134cd0e5c9e3cb69c139b953391b0",
          "md5": "3e65a15d6c6243cc4f8fec917032376f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.4-sources.jar",
          "url": "runelite-api-3.3.4-sources.jar",
          "size": 868075,
          "sha512": "80feb5de9938a44006acfc50b727f26a4f469315c13bca47896f6a0b2778fd76a163d9d2eab13ebf096a8676a56a8761f124c8ad5f6a4c10ca0e60f30fe8d797",
          "sha256": "0f7c27f7469ab99dad65dd6c3c4be7f18a606d2355706dbd30467cfd7e9d4fae",
          "sha1": "24f060317278fe185907c26cc2a9d398b6288f07",
          "md5": "939e8430609b2f757273178307c23bd5"
        }
      ]
    }
  ]
}
