{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "cqq7nc66dva4patoegzemqvkba"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.4.jar",
          "url": "runelite-api-3.3.4.jar",
          "size": 1183603,
          "sha512": "4d22bd7e83114d8fa509e7b9a924229edc626a46869f8f53fe4c3225bc36c850a463af1dc8c010eb212288ae7c61f2654ba879da07cde87fc763a4a98b1ba0f8",
          "sha256": "f882270242e8911ae33b0331039d39e7d9a8fd8b965e9f802023940b07209a5c",
          "sha1": "799bcb2b085672d38e1cdeb948303be9616e149c",
          "md5": "fe9ed64344657819824b2bd37c86f1e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.4.jar",
          "url": "runelite-api-3.3.4.jar",
          "size": 1183603,
          "sha512": "4d22bd7e83114d8fa509e7b9a924229edc626a46869f8f53fe4c3225bc36c850a463af1dc8c010eb212288ae7c61f2654ba879da07cde87fc763a4a98b1ba0f8",
          "sha256": "f882270242e8911ae33b0331039d39e7d9a8fd8b965e9f802023940b07209a5c",
          "sha1": "799bcb2b085672d38e1cdeb948303be9616e149c",
          "md5": "fe9ed64344657819824b2bd37c86f1e5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.4-sources.jar",
          "url": "runelite-api-3.3.4-sources.jar",
          "size": 868075,
          "sha512": "080f70fedfa19b1ac7233b32f074f90afe4946dba44fe3df99ebe4b45cf5502988c0d81d14e1ed3f563d1858ec76376eea10c8a5f1dea0dd4505274ac1d2bd32",
          "sha256": "af43243e5ae24c1f7ddfedf4450a7301a304bd3b0bedf2f86f2d921d66b9e662",
          "sha1": "5ddc56a2ae746c7b7fa34986d2434d980477732a",
          "md5": "e743705fd6a610eeef9a58006455eaf7"
        }
      ]
    }
  ]
}
