{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "isaxeb67jvg53ot6pksjewh2tm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.9"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.9.jar",
          "url": "runescape-api-3.3.9.jar",
          "size": 103804,
          "sha512": "3f76934bc75fcfa71f547f6c6a41c0f95d2e282a0c241288b83c601bbe6c9d30c4ad6677057be0208199fe5140d0e77a0d3303d741b06017adce2333d0fcd5e6",
          "sha256": "a3f9ed70f51012dce123137661d8bcb970601208e3a9f67faf6dc3705d55b77a",
          "sha1": "a5ecdb91d8f2b75dceba401785cbf590692b2c7a",
          "md5": "cccddd84b46efc9e263d4938405a20fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.9"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.9.jar",
          "url": "runescape-api-3.3.9.jar",
          "size": 103804,
          "sha512": "3f76934bc75fcfa71f547f6c6a41c0f95d2e282a0c241288b83c601bbe6c9d30c4ad6677057be0208199fe5140d0e77a0d3303d741b06017adce2333d0fcd5e6",
          "sha256": "a3f9ed70f51012dce123137661d8bcb970601208e3a9f67faf6dc3705d55b77a",
          "sha1": "a5ecdb91d8f2b75dceba401785cbf590692b2c7a",
          "md5": "cccddd84b46efc9e263d4938405a20fb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.9-sources.jar",
          "url": "runescape-api-3.3.9-sources.jar",
          "size": 99887,
          "sha512": "37e9d8ac507c16d2fd844f85809836d97f819f5f30e386c775ec8931d7ad399c83e25083b5fa53664a2e9eedabd00d99101d1466f721be8c8953b7d848abbc58",
          "sha256": "d6edb1b3c110edae22c04db8aa7538e2d1bd43d4325872c3acc23b0a6eded813",
          "sha1": "bf488ee5a0832485cf5c72f47dfb7a042ff61a93",
          "md5": "60186c90e58e64f051fb0e81a38567d6"
        }
      ]
    }
  ]
}
