{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "dzwubkbpxfabrbapxxihl5gwxe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.9"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.9.jar",
          "url": "runescape-api-3.3.9.jar",
          "size": 103937,
          "sha512": "3cd1667956c4632439bdccffb9dc4c32588c769313d9e1018cdf61ee8c47bcefd38c6ee6688762eac3af38380700ee38ed0c686747a956d2380eb088cb1976f5",
          "sha256": "03f75a5aed801a8ea34204d879d148337f50c4d20bdaada08726bc9a6787e201",
          "sha1": "d4e201cb86f6f109cd3c0a2fa9a7e7ef1d1758d3",
          "md5": "f47be9a0a7fce4d5a98744ab4af34429"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.9"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.9.jar",
          "url": "runescape-api-3.3.9.jar",
          "size": 103937,
          "sha512": "3cd1667956c4632439bdccffb9dc4c32588c769313d9e1018cdf61ee8c47bcefd38c6ee6688762eac3af38380700ee38ed0c686747a956d2380eb088cb1976f5",
          "sha256": "03f75a5aed801a8ea34204d879d148337f50c4d20bdaada08726bc9a6787e201",
          "sha1": "d4e201cb86f6f109cd3c0a2fa9a7e7ef1d1758d3",
          "md5": "f47be9a0a7fce4d5a98744ab4af34429"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.9-sources.jar",
          "url": "runescape-api-3.3.9-sources.jar",
          "size": 100717,
          "sha512": "56d866a34f67a9c8c68d85a31b961ec8b373b0d61e21effd7d6847f3920a7b0169ecb922804233edb943fc8a25af604a498695c2cce86479a86e56f225f3930e",
          "sha256": "425da4d869c5eb29d688db421cd869e8b0f4e81b7c021ffa1546ca33ff09407c",
          "sha1": "db0cd913c97fc14bb7171af85a11e2549e679a01",
          "md5": "5df7461944f8d5ce28fef54c2745e400"
        }
      ]
    }
  ]
}
