{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "jtrkyo5cvffqbbwgo2hm7l4vgu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.2.jar",
          "url": "injected-client-3.3.2.jar",
          "size": 2252612,
          "sha512": "297a942b3e31ee5bb1e9727b20faada27f2cf8ca57d9c8f79fe6c869ccf7a608ac9c8409def0a248a32af6ff09b24e2b7e488fd41625c982dca1b6a007974360",
          "sha256": "7a831aae62330b9c73cb36a06f9f33a65af59c3d334cf7aa89f0d59961f58b64",
          "sha1": "3c47a56e27bff13791b720e25b6a31a5724e6349",
          "md5": "2c8a26c55e771f1aa5745879b8e6b268"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.2.jar",
          "url": "injected-client-3.3.2.jar",
          "size": 2252612,
          "sha512": "297a942b3e31ee5bb1e9727b20faada27f2cf8ca57d9c8f79fe6c869ccf7a608ac9c8409def0a248a32af6ff09b24e2b7e488fd41625c982dca1b6a007974360",
          "sha256": "7a831aae62330b9c73cb36a06f9f33a65af59c3d334cf7aa89f0d59961f58b64",
          "sha1": "3c47a56e27bff13791b720e25b6a31a5724e6349",
          "md5": "2c8a26c55e771f1aa5745879b8e6b268"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.2-sources.jar",
          "url": "injected-client-3.3.2-sources.jar",
          "size": 261,
          "sha512": "804dccd5755bdc9901b49ff8aeff45089d1cb0b9adfcb492b3b8223743e743b1e3e9d7d0331f0ba9d79347ac172b6750134c1459cde0367bfee1b52409d4335e",
          "sha256": "49346962306f7d19a15b8d262c2fa1399c82f75c3c59054f7bfc69ce7a8d37db",
          "sha1": "24ca2de28035084003476fc89e25ced319c174d3",
          "md5": "d021b7d8b7383f1c61c3e2af7a23ab98"
        },
        {
          "name": "injected-client-3.3.2.jar",
          "url": "injected-client-3.3.2.jar",
          "size": 2252612,
          "sha512": "297a942b3e31ee5bb1e9727b20faada27f2cf8ca57d9c8f79fe6c869ccf7a608ac9c8409def0a248a32af6ff09b24e2b7e488fd41625c982dca1b6a007974360",
          "sha256": "7a831aae62330b9c73cb36a06f9f33a65af59c3d334cf7aa89f0d59961f58b64",
          "sha1": "3c47a56e27bff13791b720e25b6a31a5724e6349",
          "md5": "2c8a26c55e771f1aa5745879b8e6b268"
        }
      ]
    }
  ]
}
