{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "kvbsbshgerbfxfs3d5yzk7bgge"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.2.jar",
          "url": "injected-client-3.3.2.jar",
          "size": 2253126,
          "sha512": "9c95f4fdab378e90d1fae34d7dde8894c26633a2b8b24d9254b4ca2972585c58f2e36c9775d749f6641f9d8115c442abb857560d250588d4ce2903b4a04e0e23",
          "sha256": "c3e31d78dc0fa4e5535b4fafcfa6411ddc3af117a2df0191bf865bc50380aaa1",
          "sha1": "439ed2c2d625cf9486cf0f31b58c6083bfd9d45a",
          "md5": "e431793a1f8ee587014b8f7595877530"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.2.jar",
          "url": "injected-client-3.3.2.jar",
          "size": 2253126,
          "sha512": "9c95f4fdab378e90d1fae34d7dde8894c26633a2b8b24d9254b4ca2972585c58f2e36c9775d749f6641f9d8115c442abb857560d250588d4ce2903b4a04e0e23",
          "sha256": "c3e31d78dc0fa4e5535b4fafcfa6411ddc3af117a2df0191bf865bc50380aaa1",
          "sha1": "439ed2c2d625cf9486cf0f31b58c6083bfd9d45a",
          "md5": "e431793a1f8ee587014b8f7595877530"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.2-sources.jar",
          "url": "injected-client-3.3.2-sources.jar",
          "size": 261,
          "sha512": "97f5910d4f71a68662b4e6f8f9e26ab0b309144c2937ff49e6c18c4743115a1c6fdd7961421a1e052648f7ffdf4f39e8aec1da9d9af74fbd63f6e2ba9faee0dd",
          "sha256": "68ad3ee9d8058b3886965f9045687d56b91eebbaccd007a9972617be8b8b39c2",
          "sha1": "1e8e10e068918c462c562c54aad69619f8616d5f",
          "md5": "6b4f78341c2c7b5e70e65baceaee178d"
        },
        {
          "name": "injected-client-3.3.2.jar",
          "url": "injected-client-3.3.2.jar",
          "size": 2253126,
          "sha512": "9c95f4fdab378e90d1fae34d7dde8894c26633a2b8b24d9254b4ca2972585c58f2e36c9775d749f6641f9d8115c442abb857560d250588d4ce2903b4a04e0e23",
          "sha256": "c3e31d78dc0fa4e5535b4fafcfa6411ddc3af117a2df0191bf865bc50380aaa1",
          "sha1": "439ed2c2d625cf9486cf0f31b58c6083bfd9d45a",
          "md5": "e431793a1f8ee587014b8f7595877530"
        }
      ]
    }
  ]
}
