{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "txjhv2kfzjgn7itcaysvp4avfa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.2.jar",
          "url": "injected-client-3.3.2.jar",
          "size": 2253448,
          "sha512": "20a580e84da8a8367a5f3f5734285685fc79fac4a36d3e75f0db4b35bb9ef15db3640b762af39918f38117393b8723aed0f82caeff1855338c309b5a14923117",
          "sha256": "b8cd741feb944a6153b258ea26ef82f03c5b8a4fa708e928331850d4ebd94f60",
          "sha1": "24ef842498359e86a3829427cb020b8cff38c8cd",
          "md5": "369d608709d53a639acb8e6583831bf1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.2.jar",
          "url": "injected-client-3.3.2.jar",
          "size": 2253448,
          "sha512": "20a580e84da8a8367a5f3f5734285685fc79fac4a36d3e75f0db4b35bb9ef15db3640b762af39918f38117393b8723aed0f82caeff1855338c309b5a14923117",
          "sha256": "b8cd741feb944a6153b258ea26ef82f03c5b8a4fa708e928331850d4ebd94f60",
          "sha1": "24ef842498359e86a3829427cb020b8cff38c8cd",
          "md5": "369d608709d53a639acb8e6583831bf1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.2-sources.jar",
          "url": "injected-client-3.3.2-sources.jar",
          "size": 261,
          "sha512": "ba0c15da2046e7e7a6b08fcadf5d6acd9e8c0222b5d8f807a1d2515e1baafcdb24fca165ed2605ab39e21168aa651c6bed440eda102bea96d5d3d2a9af1aadbd",
          "sha256": "d02e1aabed5f1c6744b1332e67e5dde75c73f2360f45704e2bd1cbbeeebc011c",
          "sha1": "504dcc8aaeb6b15eaa4942c221735c0468578205",
          "md5": "1bde077532ca1061fe6f0c405a6cf722"
        },
        {
          "name": "injected-client-3.3.2.jar",
          "url": "injected-client-3.3.2.jar",
          "size": 2253448,
          "sha512": "20a580e84da8a8367a5f3f5734285685fc79fac4a36d3e75f0db4b35bb9ef15db3640b762af39918f38117393b8723aed0f82caeff1855338c309b5a14923117",
          "sha256": "b8cd741feb944a6153b258ea26ef82f03c5b8a4fa708e928331850d4ebd94f60",
          "sha1": "24ef842498359e86a3829427cb020b8cff38c8cd",
          "md5": "369d608709d53a639acb8e6583831bf1"
        }
      ]
    }
  ]
}
