{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "yrgrwxt35vgsnfumly2dkrrfcm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.9.jar",
          "url": "runelite-api-3.3.9.jar",
          "size": 1219329,
          "sha512": "399473e8c3fef1736d72de3f5b15b3df8d9b65c6ae78f4021e44ec29029efb313c865383f48ed4d18ad2e86df5a2063390209dd7644a5b7829bab2472f3b3154",
          "sha256": "f94ae7cf5262d4ce158f32dd607bc6974b06f213c82b7ea9f9e2e7935b2e52cd",
          "sha1": "d2070b3fc76fc8a39a4424a4f8e36b247f0b8a2d",
          "md5": "9df9ba9291712e8d07c2065e4da0b0cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.9.jar",
          "url": "runelite-api-3.3.9.jar",
          "size": 1219329,
          "sha512": "399473e8c3fef1736d72de3f5b15b3df8d9b65c6ae78f4021e44ec29029efb313c865383f48ed4d18ad2e86df5a2063390209dd7644a5b7829bab2472f3b3154",
          "sha256": "f94ae7cf5262d4ce158f32dd607bc6974b06f213c82b7ea9f9e2e7935b2e52cd",
          "sha1": "d2070b3fc76fc8a39a4424a4f8e36b247f0b8a2d",
          "md5": "9df9ba9291712e8d07c2065e4da0b0cb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.9-sources.jar",
          "url": "runelite-api-3.3.9-sources.jar",
          "size": 893202,
          "sha512": "4e83a92cb42d8d1fb7ab49f35b38609374ca8bbc28e623ec7bd2052da28540709988acb3fda6d58cca6f99e990cc3a5143fadda80db4b0e487d608c216eade1d",
          "sha256": "27977e4dbf440454031f7be69962cc9c12f911855196d1d9f9178ee96582edf0",
          "sha1": "975675d8447f7fd5d9d9f6282bb8891cf9953a3a",
          "md5": "71dc7d05a0ca83bee6258b58ed24f494"
        }
      ]
    }
  ]
}
