{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "czwcvidwzrditmorkdpzkbnezy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.2.1.jar",
          "url": "http-api-3.2.1.jar",
          "size": 165559,
          "sha512": "1840677a5173829ec5a783d7ebbfac8b54dae3ddf9f17c41b55ecac25ed124f79ac3460243123921c4cc2bb9ac9d4fd050564460ff2e4576d33c076c2027f420",
          "sha256": "761cd092afef6cac59dd6a33e2d31e88eefa9aa297ccbc25627d28740c5085da",
          "sha1": "0a29c0ab57371cac93dd98a908663e5c988c9b3f",
          "md5": "c0a873951f9a05e26bb3f3b6cf21db77"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.2.1.jar",
          "url": "http-api-3.2.1.jar",
          "size": 165559,
          "sha512": "1840677a5173829ec5a783d7ebbfac8b54dae3ddf9f17c41b55ecac25ed124f79ac3460243123921c4cc2bb9ac9d4fd050564460ff2e4576d33c076c2027f420",
          "sha256": "761cd092afef6cac59dd6a33e2d31e88eefa9aa297ccbc25627d28740c5085da",
          "sha1": "0a29c0ab57371cac93dd98a908663e5c988c9b3f",
          "md5": "c0a873951f9a05e26bb3f3b6cf21db77"
        }
      ]
    }
  ]
}
