{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "ayqukufk5rd7fgqq3pqi3qjtji"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.2.1.jar",
          "url": "http-api-3.2.1.jar",
          "size": 163380,
          "sha512": "9aad5bdbbcf2812bc0ee07b55d5c68195dde7cbebbfec199932436a548a6d7dcf046e0dd64e1d4484cb14db7cc7f4c3fe51af2e2b0f46c282a8b85bb9fe120ae",
          "sha256": "593ea02529f2073213aeaa0b62a2bf4223a890079661b3973ad59824cd28551e",
          "sha1": "a339dfffb7843ee77ea4bafc4599ff1b38399673",
          "md5": "16c46bcab53cf04a325786658ea705d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.2.1.jar",
          "url": "http-api-3.2.1.jar",
          "size": 163380,
          "sha512": "9aad5bdbbcf2812bc0ee07b55d5c68195dde7cbebbfec199932436a548a6d7dcf046e0dd64e1d4484cb14db7cc7f4c3fe51af2e2b0f46c282a8b85bb9fe120ae",
          "sha256": "593ea02529f2073213aeaa0b62a2bf4223a890079661b3973ad59824cd28551e",
          "sha1": "a339dfffb7843ee77ea4bafc4599ff1b38399673",
          "md5": "16c46bcab53cf04a325786658ea705d6"
        }
      ]
    }
  ]
}
