{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "cxhso3hhi5gmvbdpof67rgfccu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.2.1.jar",
          "url": "http-api-3.2.1.jar",
          "size": 163641,
          "sha512": "55fb05b160ba9fb3d647bdcb5a1f305e09e569ccea43f062e3313e8783b193df4b435390696a1158741d8890ea0fa26018e32dedb6dfe99c869f2079da51f394",
          "sha256": "ab979bebce3320fadac095950169dfe0f72fc3cfb9173b0523611c10bbaf064f",
          "sha1": "daeb6579744f7f1ef3ec69e48030b7c96863e86b",
          "md5": "68e7221a97a76d26c4d3d24d46bd0f25"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.2.1.jar",
          "url": "http-api-3.2.1.jar",
          "size": 163641,
          "sha512": "55fb05b160ba9fb3d647bdcb5a1f305e09e569ccea43f062e3313e8783b193df4b435390696a1158741d8890ea0fa26018e32dedb6dfe99c869f2079da51f394",
          "sha256": "ab979bebce3320fadac095950169dfe0f72fc3cfb9173b0523611c10bbaf064f",
          "sha1": "daeb6579744f7f1ef3ec69e48030b7c96863e86b",
          "md5": "68e7221a97a76d26c4d3d24d46bd0f25"
        }
      ]
    }
  ]
}
