{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "wearss7mlrhafjozjlmzxt6adm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.4.jar",
          "url": "http-api-1.6.4.jar",
          "size": 165422,
          "sha512": "d49796eb1720620bf2496ba2990ccf2da5fc01539645a72570f1d2b4491666de86d52f4625649fb5c85c50552ffd3caf361f14b572a7474c9e7030fcdebc7486",
          "sha256": "1b779e0080d09cc2da284ecaa51ba6cb191ed88a5ec8f4519078f78ed38c36e2",
          "sha1": "9982acb66725024fb51ea1f80d853d9c375c443d",
          "md5": "29a37815d77e0502a7b4306a4e882524"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.4.jar",
          "url": "http-api-1.6.4.jar",
          "size": 165422,
          "sha512": "d49796eb1720620bf2496ba2990ccf2da5fc01539645a72570f1d2b4491666de86d52f4625649fb5c85c50552ffd3caf361f14b572a7474c9e7030fcdebc7486",
          "sha256": "1b779e0080d09cc2da284ecaa51ba6cb191ed88a5ec8f4519078f78ed38c36e2",
          "sha1": "9982acb66725024fb51ea1f80d853d9c375c443d",
          "md5": "29a37815d77e0502a7b4306a4e882524"
        }
      ]
    }
  ]
}
