{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "u4r4cg2mobdgxanmh64olbas3u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "injector-plugin-1.1.3.jar",
          "url": "injector-plugin-1.1.3.jar",
          "size": 104423,
          "sha512": "915074d39b7a5083a13ceca379232f6d2b2d602dd213bffca390d6b64b325822c1a317aebf2a848c5d9e4f628721a4f5083f7818a11301d23b01cd5025ea41b2",
          "sha256": "59cb14f620cc3cbdc5ea9ced462d6c945209e6ccf20a7c85f5e04252dcacddbd",
          "sha1": "2b8990bc581405745e4186192dd484bb192154ba",
          "md5": "25c82098076228ecf04b508802b2a5da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "19.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.openosrs",
          "module": "deobfuscator",
          "version": {
            "requires": "3.3.8"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "injector-plugin-1.1.3.jar",
          "url": "injector-plugin-1.1.3.jar",
          "size": 104423,
          "sha512": "915074d39b7a5083a13ceca379232f6d2b2d602dd213bffca390d6b64b325822c1a317aebf2a848c5d9e4f628721a4f5083f7818a11301d23b01cd5025ea41b2",
          "sha256": "59cb14f620cc3cbdc5ea9ced462d6c945209e6ccf20a7c85f5e04252dcacddbd",
          "sha1": "2b8990bc581405745e4186192dd484bb192154ba",
          "md5": "25c82098076228ecf04b508802b2a5da"
        }
      ]
    }
  ]
}
