{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "jic23mtasrh2pbenfnuy6w6qpq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.4.4.jar",
          "url": "http-api-3.4.4.jar",
          "size": 160251,
          "sha512": "3f27dc3ebccb7de4ad2e15b1ad740df6fae51b15f6b60693b415646ddedb3e67fb82a7ae5b2e4014901026f60f1680f4fa89f36cb1e12e4c4af01e7be8b26bec",
          "sha256": "73e2584e0b00efeaa8f03cb0b5154baec29fd119fd737a68f9ceab5eb04b6340",
          "sha1": "7a03a81cdfbc82bcd8a0b31b90db161a16d76766",
          "md5": "6e5bf1eefb77150fcecf3c59c7e09c60"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.4.4.jar",
          "url": "http-api-3.4.4.jar",
          "size": 160251,
          "sha512": "3f27dc3ebccb7de4ad2e15b1ad740df6fae51b15f6b60693b415646ddedb3e67fb82a7ae5b2e4014901026f60f1680f4fa89f36cb1e12e4c4af01e7be8b26bec",
          "sha256": "73e2584e0b00efeaa8f03cb0b5154baec29fd119fd737a68f9ceab5eb04b6340",
          "sha1": "7a03a81cdfbc82bcd8a0b31b90db161a16d76766",
          "md5": "6e5bf1eefb77150fcecf3c59c7e09c60"
        }
      ]
    }
  ]
}
