{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "buamwedoajf75nbo7b7edzci3y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.4.4.jar",
          "url": "http-api-3.4.4.jar",
          "size": 160252,
          "sha512": "828605202478144b97c0dbffee3ac0c730a57530cb1f0b54540cc04fc407fdb8e848c68353402663a4530173f2b571b59fabc18b6436241c2c28fc4529cbc34e",
          "sha256": "be1ca59a2ffddc1149942b3484494bc676216ca1c523d846025b53e148a72830",
          "sha1": "336fa327e39dd80a0a2142e31e83261ff8e199a6",
          "md5": "ac7dd8300ce0e1364ec9bb74d270f0f3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.4.4.jar",
          "url": "http-api-3.4.4.jar",
          "size": 160252,
          "sha512": "828605202478144b97c0dbffee3ac0c730a57530cb1f0b54540cc04fc407fdb8e848c68353402663a4530173f2b571b59fabc18b6436241c2c28fc4529cbc34e",
          "sha256": "be1ca59a2ffddc1149942b3484494bc676216ca1c523d846025b53e148a72830",
          "sha1": "336fa327e39dd80a0a2142e31e83261ff8e199a6",
          "md5": "ac7dd8300ce0e1364ec9bb74d270f0f3"
        }
      ]
    }
  ]
}
