{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "4lslj3qyzzfepbbhvfukuyiwda"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.4.4.jar",
          "url": "http-api-3.4.4.jar",
          "size": 160251,
          "sha512": "24cb13bd49fce2e5c7b25c6a59daf50cd93d67748e33456fa05fdbf2d27e3af9e39583eb85e68a3a7936ad46e7de1ff1df611420f2e21b672fd3b16d085707ba",
          "sha256": "cdf5cce9ceb13686099fc9d2894d2fae71f1f600877988fac77e5ff79cb8f433",
          "sha1": "8528cbee8ac67bd104887dd9e20e7366b2c60ac4",
          "md5": "6fde0cb10294b6dd96d63ad71451fc4d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.4.4.jar",
          "url": "http-api-3.4.4.jar",
          "size": 160251,
          "sha512": "24cb13bd49fce2e5c7b25c6a59daf50cd93d67748e33456fa05fdbf2d27e3af9e39583eb85e68a3a7936ad46e7de1ff1df611420f2e21b672fd3b16d085707ba",
          "sha256": "cdf5cce9ceb13686099fc9d2894d2fae71f1f600877988fac77e5ff79cb8f433",
          "sha1": "8528cbee8ac67bd104887dd9e20e7366b2c60ac4",
          "md5": "6fde0cb10294b6dd96d63ad71451fc4d"
        }
      ]
    }
  ]
}
