{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "osqovdextrhlpgi4dibmk7vgmq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.4.1.jar",
          "url": "runelite-api-3.4.1.jar",
          "size": 1225233,
          "sha512": "cb25ee9296381f69bd5c0de2df2eeb9e000e7ca8ef80c7a41bb8814bad40fd20c11e2d9f88d42276ff14d593eca4eb47a37bcb5144582a1a6f08e999e9dfdbc7",
          "sha256": "7ef042ead6d3ccbc08b2a6eab1bbbabffbf3080c4d214601ad67c5cc31690485",
          "sha1": "7892169c199fc0d81f2efe6be1cc7a2e96ab8279",
          "md5": "2ec6f9e9db68dc8570a1c6c64b4a106e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.4.1.jar",
          "url": "runelite-api-3.4.1.jar",
          "size": 1225233,
          "sha512": "cb25ee9296381f69bd5c0de2df2eeb9e000e7ca8ef80c7a41bb8814bad40fd20c11e2d9f88d42276ff14d593eca4eb47a37bcb5144582a1a6f08e999e9dfdbc7",
          "sha256": "7ef042ead6d3ccbc08b2a6eab1bbbabffbf3080c4d214601ad67c5cc31690485",
          "sha1": "7892169c199fc0d81f2efe6be1cc7a2e96ab8279",
          "md5": "2ec6f9e9db68dc8570a1c6c64b4a106e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.4.1-sources.jar",
          "url": "runelite-api-3.4.1-sources.jar",
          "size": 898207,
          "sha512": "53b3d4c4c33bdc144ba67fae459098d4c966b5cd99e167dd456731504f2e547cd7bebbab8d522168789c9266513c956f5a734e3f97be020f2fb5ac90cb2a3f76",
          "sha256": "6b2700a33b3802d2b99927903fb9afe6046d3d0a85505faab6ea46fd8c790991",
          "sha1": "3ea26e7b0c36aa2ff6e822bdabcf4fa770b8fe30",
          "md5": "9204f1e4990e8899cbed04dca7251ea3"
        }
      ]
    }
  ]
}
