{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "p4awfcoohnfgrk3h777wlgfk5q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.6.jar",
          "url": "runelite-api-1.6.6.jar",
          "size": 1158718,
          "sha512": "f67b61b633c5b80280f8cff2317378ce456555cea64f1f5c342e59f838ada167d4bfbfcc942bec2531225a8e846c04718e25cc1aa9038a09dcd600cf5432a262",
          "sha256": "04792b86977ceb8d23110577c20178185e0bb956bb53cecbb6d19e5de9785887",
          "sha1": "d960731a0f04522df33438c528038f3fc1e7e78e",
          "md5": "5b134d1b94b2b27de1dedb80af93c3b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.6.jar",
          "url": "runelite-api-1.6.6.jar",
          "size": 1158718,
          "sha512": "f67b61b633c5b80280f8cff2317378ce456555cea64f1f5c342e59f838ada167d4bfbfcc942bec2531225a8e846c04718e25cc1aa9038a09dcd600cf5432a262",
          "sha256": "04792b86977ceb8d23110577c20178185e0bb956bb53cecbb6d19e5de9785887",
          "sha1": "d960731a0f04522df33438c528038f3fc1e7e78e",
          "md5": "5b134d1b94b2b27de1dedb80af93c3b1"
        }
      ]
    }
  ]
}
