{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "rb5yuoxqkreankmnlkb74x3pse"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.6.jar",
          "url": "runelite-api-1.6.6.jar",
          "size": 1159510,
          "sha512": "1659dfd26bf5fb2a2deaad0781c553813098ac360a0b06cbf949b2d748f5215baa2ee8056c8999e9d362b859620cdbe68bf9a205a3583925d7e9dbbac9377681",
          "sha256": "526c6336ae8ebeb41234bc7cd59d8c169da228efacd58090657b74442bbb6603",
          "sha1": "2b82b7f6fe249ad289088ee0e92dd7628bd5d75a",
          "md5": "da3459e664cf2c1100551b40040b3100"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.6.jar",
          "url": "runelite-api-1.6.6.jar",
          "size": 1159510,
          "sha512": "1659dfd26bf5fb2a2deaad0781c553813098ac360a0b06cbf949b2d748f5215baa2ee8056c8999e9d362b859620cdbe68bf9a205a3583925d7e9dbbac9377681",
          "sha256": "526c6336ae8ebeb41234bc7cd59d8c169da228efacd58090657b74442bbb6603",
          "sha1": "2b82b7f6fe249ad289088ee0e92dd7628bd5d75a",
          "md5": "da3459e664cf2c1100551b40040b3100"
        }
      ]
    }
  ]
}
