{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "hnm3ioumrjab7l5kd35q6h62sm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.6.jar",
          "url": "runelite-api-1.6.6.jar",
          "size": 1158925,
          "sha512": "d74d6273075a924e2f90dc9b194b7b6fa6916d39aac5ef498c30b2bff33fd417ce1e6012f910a8d5b53f0df6ee909a0d0a5766dc3217c65bec66ad926547e6e0",
          "sha256": "333ee6907bacb02f946cafeddba4a18238fb9a503c2292868f5bfdd47b6bd619",
          "sha1": "bea219438468fbfbc489d6d0ab7842229f8c6581",
          "md5": "8efa65b83d29d48f00d307c5d0348ad5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.6.jar",
          "url": "runelite-api-1.6.6.jar",
          "size": 1158925,
          "sha512": "d74d6273075a924e2f90dc9b194b7b6fa6916d39aac5ef498c30b2bff33fd417ce1e6012f910a8d5b53f0df6ee909a0d0a5766dc3217c65bec66ad926547e6e0",
          "sha256": "333ee6907bacb02f946cafeddba4a18238fb9a503c2292868f5bfdd47b6bd619",
          "sha1": "bea219438468fbfbc489d6d0ab7842229f8c6581",
          "md5": "8efa65b83d29d48f00d307c5d0348ad5"
        }
      ]
    }
  ]
}
