{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "7qfsywvzyveczfcfgmdtcxye2a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.9"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.9.jar",
          "url": "runescape-api-1.6.9.jar",
          "size": 55336,
          "sha512": "444949fb22c3366f9512c6fc511b9cf53703f323bf4e4069c80bce7178a98faea7c7f6a5e706bf062a02e3a9a00a4aa48fa678eb4594a7e79606a781c5a4d808",
          "sha256": "3f03853063202a6dbdcfe25f9212caa3df5b55f5639310bca63c7cdcb1ea7383",
          "sha1": "e0635fb708a6d021ecf38475e506988bc5af02e2",
          "md5": "67215e4dceb8a6997e69beab81f81c83"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.9"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.9.jar",
          "url": "runescape-api-1.6.9.jar",
          "size": 55336,
          "sha512": "444949fb22c3366f9512c6fc511b9cf53703f323bf4e4069c80bce7178a98faea7c7f6a5e706bf062a02e3a9a00a4aa48fa678eb4594a7e79606a781c5a4d808",
          "sha256": "3f03853063202a6dbdcfe25f9212caa3df5b55f5639310bca63c7cdcb1ea7383",
          "sha1": "e0635fb708a6d021ecf38475e506988bc5af02e2",
          "md5": "67215e4dceb8a6997e69beab81f81c83"
        }
      ]
    }
  ]
}
