{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "jeap5e74azajlbcyaiurdfhiga"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.9"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.9.jar",
          "url": "runescape-api-1.6.9.jar",
          "size": 55408,
          "sha512": "eedc40dee3c95db530ad6e6ef234f2a1c400b4ee24607a91924098ba2a5d5899fc1ecd43e0cf193811e1891e811d01d4a80925f1d7b70c36fa45954d0ea1dabc",
          "sha256": "9ea0ed3c8e488a8ff2c1f5311210f7d1d66b677662f2788bb084e79f39fe13e9",
          "sha1": "ba3642dda11cd1b494454424cc76548abf2d246d",
          "md5": "ed92f23e3427218a31832d57244bcc71"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.9"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.9.jar",
          "url": "runescape-api-1.6.9.jar",
          "size": 55408,
          "sha512": "eedc40dee3c95db530ad6e6ef234f2a1c400b4ee24607a91924098ba2a5d5899fc1ecd43e0cf193811e1891e811d01d4a80925f1d7b70c36fa45954d0ea1dabc",
          "sha256": "9ea0ed3c8e488a8ff2c1f5311210f7d1d66b677662f2788bb084e79f39fe13e9",
          "sha1": "ba3642dda11cd1b494454424cc76548abf2d246d",
          "md5": "ed92f23e3427218a31832d57244bcc71"
        }
      ]
    }
  ]
}
