{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "75hjafas2bcyriu3ba6eqlelyi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.0.7.jar",
          "url": "runescape-api-3.0.7.jar",
          "size": 55408,
          "sha512": "9166e990a7448d642ed9289be6665a665a009420e2341a555d45753a30718ef6dcb512a4c0e7f8ac961d3fbe5f133417aca2e3e5984ef4b36e32b2218765d315",
          "sha256": "8b0ec7d1e252aa6f8234911413e55bd3b9d5d599764a2adab3675f09e12a80ef",
          "sha1": "5e6bb57ddd30e929652ab18ce9a79c57680dd8bc",
          "md5": "bc57c213ddf0542584f2c4c004bfb0fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.0.7.jar",
          "url": "runescape-api-3.0.7.jar",
          "size": 55408,
          "sha512": "9166e990a7448d642ed9289be6665a665a009420e2341a555d45753a30718ef6dcb512a4c0e7f8ac961d3fbe5f133417aca2e3e5984ef4b36e32b2218765d315",
          "sha256": "8b0ec7d1e252aa6f8234911413e55bd3b9d5d599764a2adab3675f09e12a80ef",
          "sha1": "5e6bb57ddd30e929652ab18ce9a79c57680dd8bc",
          "md5": "bc57c213ddf0542584f2c4c004bfb0fc"
        }
      ]
    }
  ]
}
