{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "nfciutv2ujbjdabtzzanx67oxe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.2.0.jar",
          "url": "injected-client-3.2.0.jar",
          "size": 2245481,
          "sha512": "908c214d2d3ea86b60fa82454974dc937fdae4eb63ff59c2d855c23569992a49064bb056c5eeaaa4c9b94807498fd699c4b45fb633e40d477c115120b2db119e",
          "sha256": "a5ddc19093944887a1cf738ac5f0a6936c668c0814e892f71593713a85f642de",
          "sha1": "aafa8b2b1808c9726647fd45bd8ffe6319620d6e",
          "md5": "8e285790abf3d89c83c47d2ac540692a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.2.0.jar",
          "url": "injected-client-3.2.0.jar",
          "size": 2245481,
          "sha512": "908c214d2d3ea86b60fa82454974dc937fdae4eb63ff59c2d855c23569992a49064bb056c5eeaaa4c9b94807498fd699c4b45fb633e40d477c115120b2db119e",
          "sha256": "a5ddc19093944887a1cf738ac5f0a6936c668c0814e892f71593713a85f642de",
          "sha1": "aafa8b2b1808c9726647fd45bd8ffe6319620d6e",
          "md5": "8e285790abf3d89c83c47d2ac540692a"
        }
      ]
    }
  ]
}
