{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "f3upj6lb25f4dm4sitq246cwr4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.2.0.jar",
          "url": "injected-client-3.2.0.jar",
          "size": 2245481,
          "sha512": "bce822a3c704f2faba1c8c92d54af61d93c382a5c7dfeda46ae991bc89c8b14d49c07261b09b1bf37a17f1a4f29d95d033a8c094824e969706e9b326a66e5597",
          "sha256": "0595f93c013ad70095d90c11d7b9ecd4ae9c9a5ac437f9c9fd6dbb3d58a9e654",
          "sha1": "9d73ce09fa2253d962c489a6055f22b5b260b036",
          "md5": "2b147e864845ca85996d59e8f4220314"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.2.0.jar",
          "url": "injected-client-3.2.0.jar",
          "size": 2245481,
          "sha512": "bce822a3c704f2faba1c8c92d54af61d93c382a5c7dfeda46ae991bc89c8b14d49c07261b09b1bf37a17f1a4f29d95d033a8c094824e969706e9b326a66e5597",
          "sha256": "0595f93c013ad70095d90c11d7b9ecd4ae9c9a5ac437f9c9fd6dbb3d58a9e654",
          "sha1": "9d73ce09fa2253d962c489a6055f22b5b260b036",
          "md5": "2b147e864845ca85996d59e8f4220314"
        }
      ]
    }
  ]
}
