{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "f6pnecnbjrd7hks4kmkv5lumjq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.5.jar",
          "url": "http-api-3.3.5.jar",
          "size": 154170,
          "sha512": "516a415c1b20f0931cdb344cfc5b6697dfad2d4fe335cd4874448897e5b8ceaeb613f4d55ad433b5be5dad07cf405009c21b6846b3dbae1c462d28747c924d54",
          "sha256": "0a7d48c0cc6e1af463caf171ad7cb91602b34a96e027aa3a967b8bd6915d3a10",
          "sha1": "7ef5634ecaf2986f1672129c7b81bac127120261",
          "md5": "bcdc557b4cb9f4ad7e93a0eb51d50387"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.5"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.5.jar",
          "url": "http-api-3.3.5.jar",
          "size": 154170,
          "sha512": "516a415c1b20f0931cdb344cfc5b6697dfad2d4fe335cd4874448897e5b8ceaeb613f4d55ad433b5be5dad07cf405009c21b6846b3dbae1c462d28747c924d54",
          "sha256": "0a7d48c0cc6e1af463caf171ad7cb91602b34a96e027aa3a967b8bd6915d3a10",
          "sha1": "7ef5634ecaf2986f1672129c7b81bac127120261",
          "md5": "bcdc557b4cb9f4ad7e93a0eb51d50387"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.5-sources.jar",
          "url": "http-api-3.3.5-sources.jar",
          "size": 101939,
          "sha512": "3e569560454a3ae5d38a0150a25ccdd24d3ca07062264e6fac525c331a4f01e5cf3d3814401e05b8908c6a528dd5f0d5ee19c91ba41cae363fea07c437303fb4",
          "sha256": "6f1496382c21ff9e748d350b05ecd732a92f3d2c9eff1eff81f320a881d03d0f",
          "sha1": "ca25663a35e980ed1a3d47b8c7d4080f449b738a",
          "md5": "082f2a3b7e239b1d63baf3af696e3506"
        }
      ]
    }
  ]
}
