{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "f75twmv45zbnnnk6kd3v53kpem"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.5.jar",
          "url": "http-api-3.3.5.jar",
          "size": 154171,
          "sha512": "331e1638384c0e3c98a07c91e13a07ebffe23180ae129904da5f117901114024d5861195a7a4638c3286d7ebb5130b83beaf8c8b16d903141d7faa5b96970511",
          "sha256": "814b8ba2ae5ffc88b1705690e49d06f07f35a5c12aef46d147151d55a0eef02d",
          "sha1": "ef900f91fc54ab0ef63747b9f36b32adf440927e",
          "md5": "cd76fb8a9e3156e403c9570816d35ea8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.5"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.5.jar",
          "url": "http-api-3.3.5.jar",
          "size": 154171,
          "sha512": "331e1638384c0e3c98a07c91e13a07ebffe23180ae129904da5f117901114024d5861195a7a4638c3286d7ebb5130b83beaf8c8b16d903141d7faa5b96970511",
          "sha256": "814b8ba2ae5ffc88b1705690e49d06f07f35a5c12aef46d147151d55a0eef02d",
          "sha1": "ef900f91fc54ab0ef63747b9f36b32adf440927e",
          "md5": "cd76fb8a9e3156e403c9570816d35ea8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.5-sources.jar",
          "url": "http-api-3.3.5-sources.jar",
          "size": 101939,
          "sha512": "50358583dd2d90c55819a94da6e0888c21a9ff1f8828f8850f3cbf7213090b7ec1fe60029dca3eb17b9a4c39cb93ca7217f3d7776bb29d455f471cf5fd152478",
          "sha256": "17e7a01d0844425682ab71623042de7520a641f21b25a1a1330cfa048c19655a",
          "sha1": "92e966854d733ff47d864b178a71717f352477e4",
          "md5": "c1080d1488c664c7e5788ce81acc1f1d"
        }
      ]
    }
  ]
}
