{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "fujdrd7w6nh75aw2luhoxfpy4a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.5.jar",
          "url": "http-api-3.3.5.jar",
          "size": 154170,
          "sha512": "f87194307afff6941fae6a628934b9fe4745596df61cf65424fdbae860c98d880d67461a85647aec88ef94fc550b7d76480a1f3eec2780154f5db74500ff9c71",
          "sha256": "fe2737126de42ad0d154fb85d9751c4f9e469de5ec47006830a80669879c7f35",
          "sha1": "adb980b63a6ef246600110c091523dc8e1d90127",
          "md5": "67d9db50c2462b944892b3816bdce011"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.5"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.5.jar",
          "url": "http-api-3.3.5.jar",
          "size": 154170,
          "sha512": "f87194307afff6941fae6a628934b9fe4745596df61cf65424fdbae860c98d880d67461a85647aec88ef94fc550b7d76480a1f3eec2780154f5db74500ff9c71",
          "sha256": "fe2737126de42ad0d154fb85d9751c4f9e469de5ec47006830a80669879c7f35",
          "sha1": "adb980b63a6ef246600110c091523dc8e1d90127",
          "md5": "67d9db50c2462b944892b3816bdce011"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.5-sources.jar",
          "url": "http-api-3.3.5-sources.jar",
          "size": 101939,
          "sha512": "6afbf0b830154aa046105235086378765aea9ab4875de2a14e548d77d20255a18d015dc84c6f0c5f97ec0d086765e263e5b507f770e36a9bd55c1443cafbb3be",
          "sha256": "0bdf4f9f9c813f009f21218ae3fb838dc27083998c4d224aa55dd3b14c67a51b",
          "sha1": "866c633419f123d4c098d4604e0d29b86ae2e1b4",
          "md5": "4f146787343b70916ec56116b45b6ff7"
        }
      ]
    }
  ]
}
