{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "vx4j32fr2fbu7ojjflkx2qfvfa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.3.jar",
          "url": "runelite-api-3.3.3.jar",
          "size": 1182890,
          "sha512": "8c1fed032b026fccdadab1d11632a22e79d297a74609fcc5cefe1da3686331b05a99e3f19dd97d72455eb4c508683c1db211e0398e8f604d58b6793b8371b5e2",
          "sha256": "62a8990ee589e482b27a31395bfc172a9dcfe3a48faf12bb1d742f77ab9a5f90",
          "sha1": "dd2fe8239026b07ab764cf43883b91fc6f9cf4a0",
          "md5": "e692601ed9b294f973b07efce49bf2af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.3.jar",
          "url": "runelite-api-3.3.3.jar",
          "size": 1182890,
          "sha512": "8c1fed032b026fccdadab1d11632a22e79d297a74609fcc5cefe1da3686331b05a99e3f19dd97d72455eb4c508683c1db211e0398e8f604d58b6793b8371b5e2",
          "sha256": "62a8990ee589e482b27a31395bfc172a9dcfe3a48faf12bb1d742f77ab9a5f90",
          "sha1": "dd2fe8239026b07ab764cf43883b91fc6f9cf4a0",
          "md5": "e692601ed9b294f973b07efce49bf2af"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.3-sources.jar",
          "url": "runelite-api-3.3.3-sources.jar",
          "size": 866930,
          "sha512": "fed69b213a957b7c0eb0039393de9f4428a4cd5cea171e77bb00e378f396c09855e668ab104fd3ea4006cf871fa056dab0973f8c31cad68cb4fd2826a966e8a7",
          "sha256": "bafe672a2b469551531cf7071171ac9958b287e01e31cd84068348cc98f79211",
          "sha1": "42f8a286063b47cb5fdfab6f8965b1a089b71a62",
          "md5": "66bf331f958617615293d51c418b0eb7"
        }
      ]
    }
  ]
}
