{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "iks2trtmgbahnbbyhrvehc5f3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.3.jar",
          "url": "runelite-api-3.3.3.jar",
          "size": 1182890,
          "sha512": "f35831a57b7c4d6ff8e70df7ae55d7e221febaf36b96a0aca69d3f8b02d483cf9340c3fe6dccf68a8cbf1ab9abd6fb728ee54a2f4ea3b9e646a2fe196c8a0d59",
          "sha256": "fa150ca87f163c48caabcf21eb2ed257f9b78c47922fd3134ebddc249b2bdbf6",
          "sha1": "dc39c0c12f2039c4e3565a4dbeac88cdc2297002",
          "md5": "1e00821c05409f47789bb45527ed11ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.3.jar",
          "url": "runelite-api-3.3.3.jar",
          "size": 1182890,
          "sha512": "f35831a57b7c4d6ff8e70df7ae55d7e221febaf36b96a0aca69d3f8b02d483cf9340c3fe6dccf68a8cbf1ab9abd6fb728ee54a2f4ea3b9e646a2fe196c8a0d59",
          "sha256": "fa150ca87f163c48caabcf21eb2ed257f9b78c47922fd3134ebddc249b2bdbf6",
          "sha1": "dc39c0c12f2039c4e3565a4dbeac88cdc2297002",
          "md5": "1e00821c05409f47789bb45527ed11ce"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.3-sources.jar",
          "url": "runelite-api-3.3.3-sources.jar",
          "size": 866930,
          "sha512": "8cf9e43f7435d83dc6ef62c3b1c9d2c1bd3e8a850ce1367051f44c1438afd26ab566a97d24600a3271116b2fac6e1d1ad585591cba3c814b9f823941ddae3306",
          "sha256": "2fa2fa88294fe735e0cff68234940e8c6fdae1ba23d5ee53a9141800299e69dc",
          "sha1": "ac6a78733ac1a5e70677f21eb3d31c6eacf0b993",
          "md5": "768f55d6ed4d7a507e970d2aebcd136e"
        }
      ]
    }
  ]
}
