{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "mfk5xstvi5a55d5dgo4g6qvpvu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.3.jar",
          "url": "runelite-api-3.3.3.jar",
          "size": 1182890,
          "sha512": "e5ae3bd056ec90416cd0aeff427efa6b9a47d4684dff526a492ee77b0d4f1c7063c34c8d6c4b4713c50def0382b8fa66ccdf79623b830577e092a2840e0cad64",
          "sha256": "cf16a1045d2d269f089f5d0a2878d3b217f207901d946cd0137a54c287e54cf9",
          "sha1": "b0535bdfe3fe7edc70647d64cbe87a7873f200a8",
          "md5": "7096766c1bd4a10aa82ddc6b599b3328"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.3.jar",
          "url": "runelite-api-3.3.3.jar",
          "size": 1182890,
          "sha512": "e5ae3bd056ec90416cd0aeff427efa6b9a47d4684dff526a492ee77b0d4f1c7063c34c8d6c4b4713c50def0382b8fa66ccdf79623b830577e092a2840e0cad64",
          "sha256": "cf16a1045d2d269f089f5d0a2878d3b217f207901d946cd0137a54c287e54cf9",
          "sha1": "b0535bdfe3fe7edc70647d64cbe87a7873f200a8",
          "md5": "7096766c1bd4a10aa82ddc6b599b3328"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.3-sources.jar",
          "url": "runelite-api-3.3.3-sources.jar",
          "size": 866930,
          "sha512": "0436035a47b19742dca361c7ea91cd4c1a4aece971c711f7490777b4c99f0d4f8e392c1966d18fa758b1fbbbf0020978c9291fc5b29ff3792a413600f1b7e62e",
          "sha256": "f25ffe7afd631d892f487f2cdca2ed74e19d9da5d1de83bba39dcd466a7c4ad4",
          "sha1": "be7f4fee38ecd6fc09bcdd434deacfc91c5cb3b6",
          "md5": "75bcfffad4d35ac1f7d29028fa326bfd"
        }
      ]
    }
  ]
}
