{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "yykte3y2und5nae235jacyr7j4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.4.3.jar",
          "url": "runescape-api-3.4.3.jar",
          "size": 104879,
          "sha512": "eb793866c371d5574beb140d8732833f68ad130a60a9d53322418e87369d370ab3668b04e5c6f0fc1a48013ce8e23d68224905f0cc662950a150019d6f65b4a6",
          "sha256": "ad654e2c51676afba43b0460346903d7a3465341241e28cf1296a8d66ee11b31",
          "sha1": "fa9881b3c04f5adeb9e5aa410caafa526e711aab",
          "md5": "0945d80cb7a45ff4c6de37cbb8e2e571"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.4.3.jar",
          "url": "runescape-api-3.4.3.jar",
          "size": 104879,
          "sha512": "eb793866c371d5574beb140d8732833f68ad130a60a9d53322418e87369d370ab3668b04e5c6f0fc1a48013ce8e23d68224905f0cc662950a150019d6f65b4a6",
          "sha256": "ad654e2c51676afba43b0460346903d7a3465341241e28cf1296a8d66ee11b31",
          "sha1": "fa9881b3c04f5adeb9e5aa410caafa526e711aab",
          "md5": "0945d80cb7a45ff4c6de37cbb8e2e571"
        }
      ]
    }
  ]
}
