{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "nqlfmjcxz5h67nny7rfnubzij4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.8.jar",
          "url": "runelite-api-1.6.8.jar",
          "size": 1160493,
          "sha512": "c09347312057a341251b021ad76a046f28f3ca4f5658efb73741a44efdd1a713c18706200d673c76729cd6200fca7162b93cee4a5fc3c4d92aa3d6e7e0dd91e0",
          "sha256": "8ff24a6c12235fd9861a709027b78b2f759d1e326b71f61412dac623285e754d",
          "sha1": "f11f63454d26398e2e3bc4cd723781c36407a849",
          "md5": "18c039df4956250d8da55cc3672f17ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.8.jar",
          "url": "runelite-api-1.6.8.jar",
          "size": 1160493,
          "sha512": "c09347312057a341251b021ad76a046f28f3ca4f5658efb73741a44efdd1a713c18706200d673c76729cd6200fca7162b93cee4a5fc3c4d92aa3d6e7e0dd91e0",
          "sha256": "8ff24a6c12235fd9861a709027b78b2f759d1e326b71f61412dac623285e754d",
          "sha1": "f11f63454d26398e2e3bc4cd723781c36407a849",
          "md5": "18c039df4956250d8da55cc3672f17ba"
        }
      ]
    }
  ]
}
