{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "leakwrsravf5ncbsvtpid7nkfy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.8.jar",
          "url": "runelite-api-1.6.8.jar",
          "size": 1162472,
          "sha512": "cc6946799901882be6d3685ee142713f346468994780ad1459d63fa90f27817d929cb487c9728f91b0020a7a26cd9368337ee92ed936c23eb25d284d8f45118c",
          "sha256": "27ae270136df80f12582d1c474a31e33d5b41a73be57c4989ad5f7bae7f9eafd",
          "sha1": "5cee56920f07bc800d25777391a911492307b0f2",
          "md5": "a0e150509bd56b0ea07c30c81d937b76"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.8.jar",
          "url": "runelite-api-1.6.8.jar",
          "size": 1162472,
          "sha512": "cc6946799901882be6d3685ee142713f346468994780ad1459d63fa90f27817d929cb487c9728f91b0020a7a26cd9368337ee92ed936c23eb25d284d8f45118c",
          "sha256": "27ae270136df80f12582d1c474a31e33d5b41a73be57c4989ad5f7bae7f9eafd",
          "sha1": "5cee56920f07bc800d25777391a911492307b0f2",
          "md5": "a0e150509bd56b0ea07c30c81d937b76"
        }
      ]
    }
  ]
}
