{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "6qirsm64zvg2xjjlujl56u5tde"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.8.jar",
          "url": "runelite-api-1.6.8.jar",
          "size": 1162472,
          "sha512": "126fdd3f7cf7b47b7823ded5ca4356ba4ecd319c059846bc820b68f2f8901c74f376381d331cd28ffa1eed81d9129acb4b27a32c523d78e2aeed56cc0a39c526",
          "sha256": "25d3a497c9ab714df40c528935a6046e45deabeec524f679efb3abc6834d55f2",
          "sha1": "250ec72465a6324b8034738f7991165c748c56b0",
          "md5": "360b715793ed1c1c1a800cf709b064f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.8.jar",
          "url": "runelite-api-1.6.8.jar",
          "size": 1162472,
          "sha512": "126fdd3f7cf7b47b7823ded5ca4356ba4ecd319c059846bc820b68f2f8901c74f376381d331cd28ffa1eed81d9129acb4b27a32c523d78e2aeed56cc0a39c526",
          "sha256": "25d3a497c9ab714df40c528935a6046e45deabeec524f679efb3abc6834d55f2",
          "sha1": "250ec72465a6324b8034738f7991165c748c56b0",
          "md5": "360b715793ed1c1c1a800cf709b064f5"
        }
      ]
    }
  ]
}
