{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "kmst4dhb4jecnbwxs45e6lypim"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.5.jar",
          "url": "runelite-api-1.6.5.jar",
          "size": 1150995,
          "sha512": "7699cda3d5ca033a160695f73cf88b2b22a7d7e9d821e81d0a6c663f772d5506b8f2af23316688e6a6318dd1765fded8cd0c7d6a94e6f45cc58649f0c995c568",
          "sha256": "799df3a6aa23a9feed4141f9a280c8274aef9b71d6c26925754eb9e9fd209abf",
          "sha1": "aaf70e317d0a024dbfd70fcf17eb8da910b9384c",
          "md5": "38288984ea151211fa188a5c4328f9ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.5.jar",
          "url": "runelite-api-1.6.5.jar",
          "size": 1150995,
          "sha512": "7699cda3d5ca033a160695f73cf88b2b22a7d7e9d821e81d0a6c663f772d5506b8f2af23316688e6a6318dd1765fded8cd0c7d6a94e6f45cc58649f0c995c568",
          "sha256": "799df3a6aa23a9feed4141f9a280c8274aef9b71d6c26925754eb9e9fd209abf",
          "sha1": "aaf70e317d0a024dbfd70fcf17eb8da910b9384c",
          "md5": "38288984ea151211fa188a5c4328f9ba"
        }
      ]
    }
  ]
}
