{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-client",
    "version": "3.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "kvbsbshgerbfxfs3d5yzk7bgge"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-client-3.3.2.jar",
          "url": "runelite-client-3.3.2.jar",
          "size": 2644659,
          "sha512": "aa2e61a75e61cc206408f18768712cdc8432d591f9a80e96b6d01e1a2bbb72618480f1f7afcc9cac21366823fd9481da0dda241f28c33628e32773044a3f8dca",
          "sha256": "42fc50705c53c82c99297f2d04bbece6604e3ae0aac002efe145d77227569e19",
          "sha1": "d949a49754c0f823ea4819758a0f675fbee498ce",
          "md5": "47f185515ebdd745bdd8fde543e42cf3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "4.2.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "guice",
              "type": "jar",
              "extension": "jar",
              "classifier": "no_aop"
            }
          }
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "1.4.200"
          }
        },
        {
          "group": "com.openosrs.rxrelay3",
          "module": "rxrelay",
          "version": {
            "requires": "3.0.1-SNAPSHOT"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "org.jgroups",
          "module": "jgroups",
          "version": {
            "requires": "4.2.3.Final"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "net.runelite",
          "module": "discord",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "org.pushing-pixels",
          "module": "radiance-substance",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "19.0.0"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq",
          "version": {
            "requires": "3.13.2"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq-codegen",
          "version": {
            "requires": "3.13.2"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq-meta",
          "version": {
            "requires": "3.13.2"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-logback",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.github.zafarkhaja",
          "module": "java-semver",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.pf4j",
          "module": "pf4j",
          "version": {
            "requires": "3.3.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.pf4j",
          "module": "pf4j-update",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "http-api",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.pushing-pixels",
          "module": "radiance-trident",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injected-client",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "com.openosrs.rs",
          "module": "runescape-api",
          "version": {
            "requires": "3.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-client-3.3.2.jar",
          "url": "runelite-client-3.3.2.jar",
          "size": 2644659,
          "sha512": "aa2e61a75e61cc206408f18768712cdc8432d591f9a80e96b6d01e1a2bbb72618480f1f7afcc9cac21366823fd9481da0dda241f28c33628e32773044a3f8dca",
          "sha256": "42fc50705c53c82c99297f2d04bbece6604e3ae0aac002efe145d77227569e19",
          "sha1": "d949a49754c0f823ea4819758a0f675fbee498ce",
          "md5": "47f185515ebdd745bdd8fde543e42cf3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-client-3.3.2-sources.jar",
          "url": "runelite-client-3.3.2-sources.jar",
          "size": 2333767,
          "sha512": "fc98418750532da8d36132f9a99e5efb22be008a37e961f611017f889986c2c25abbea251b7dc9ff6bc4e83b1b0d09e4d07198df47764faccf27dd19956cb09e",
          "sha256": "27ce23d6e6e406f3a2be17b3d5c320a0ddda5ec994b853bcc3a727359a942ff4",
          "sha1": "903f2dc4388d62f5510768ed9d64a7f43f673b50",
          "md5": "6b0dfe9d5eaad33ac2de7bc32fef77c1"
        }
      ]
    }
  ]
}
