{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "ep3rchk6fvb5xlwli3cl4rxldi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": []
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.9.jar",
          "url": "injected-client-3.3.9.jar",
          "size": 2304988,
          "sha512": "a6de2ce843fd7fba3ba32863ae2a151fe14ca7c82d20fc62922f970571cecef8db60b1dfd66498a867c201df26af2cc36a0a516c436ab71ebf5bb94880b0311f",
          "sha256": "3b5d64f4ba389798c15a9eee089c7f81b12329365c264c82138a25be22328f29",
          "sha1": "c5632fa44a246110ed9bcce35a13d4fecc75d04c",
          "md5": "cdb676076eaa7eeef78e44495c9988e9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": []
    }
  ]
}
