{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "rzh3oxmlprcgpjr2rvoevxpita"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": []
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.9.jar",
          "url": "injected-client-3.3.9.jar",
          "size": 2304979,
          "sha512": "7ce2561c6a436eebb9c2bbfec06e64217b8ae895d91770aa5b22058d3a1b896e11b10168c94067b0e3600edb7b50cfe939d5db447aafe24de3c243f5b9a4311a",
          "sha256": "c69e9d4ce09c79888dd35a27d8b91dec3676158a16a88c99cd4830d69fe6b1a1",
          "sha1": "65fd5de36ba9e796ae030f10b49bb97aa1a106c5",
          "md5": "5541f3b9cb838610ffe86d06f6bad6f2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": []
    }
  ]
}
