{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "6sntp6srbfhbhitopmjtqf2rme"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.9.jar",
          "url": "injected-client-3.3.9.jar",
          "size": 2304102,
          "sha512": "e88af33c4be370699ea279ee2388c16a64e362a164ccaf1a2e245f459662594ed3976e8ba2a2e95dd7bf2b82090392365874a3fb05ec4a97a1b0de6b34b0f9ba",
          "sha256": "14d6da7c6acb2d10503c3c1bfb2ae6af99ef66af54da42b726aed856bc97a0d0",
          "sha1": "b4ddb7aa10484470793087cbbf6a84c879cb1f1c",
          "md5": "e0f8155e938355e0ac19a8932e391c52"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.9.jar",
          "url": "injected-client-3.3.9.jar",
          "size": 2304102,
          "sha512": "e88af33c4be370699ea279ee2388c16a64e362a164ccaf1a2e245f459662594ed3976e8ba2a2e95dd7bf2b82090392365874a3fb05ec4a97a1b0de6b34b0f9ba",
          "sha256": "14d6da7c6acb2d10503c3c1bfb2ae6af99ef66af54da42b726aed856bc97a0d0",
          "sha1": "b4ddb7aa10484470793087cbbf6a84c879cb1f1c",
          "md5": "e0f8155e938355e0ac19a8932e391c52"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.9-sources.jar",
          "url": "injected-client-3.3.9-sources.jar",
          "size": 261,
          "sha512": "79fc6455cffea280e7cd32195d7a29d171a21ee3f0594c68ba46fbcb7c8863b3f9893e2450f23632f86a133b0853fce160d86538c9301e406b3b2221efa786d6",
          "sha256": "b1474d5324d04ad764b479b513fc56e140fba1d95031b34f3a9599f99bc6522e",
          "sha1": "b173eb3266b6bd0b9a36d6a198f355268521508f",
          "md5": "40eb0ec99921b81621a3db021f520f75"
        },
        {
          "name": "injected-client-3.3.9.jar",
          "url": "injected-client-3.3.9.jar",
          "size": 2304102,
          "sha512": "e88af33c4be370699ea279ee2388c16a64e362a164ccaf1a2e245f459662594ed3976e8ba2a2e95dd7bf2b82090392365874a3fb05ec4a97a1b0de6b34b0f9ba",
          "sha256": "14d6da7c6acb2d10503c3c1bfb2ae6af99ef66af54da42b726aed856bc97a0d0",
          "sha1": "b4ddb7aa10484470793087cbbf6a84c879cb1f1c",
          "md5": "e0f8155e938355e0ac19a8932e391c52"
        }
      ]
    }
  ]
}
