{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "pds6qty7m5cs5a7wj2ns2pst3q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.2.1.jar",
          "url": "runescape-api-3.2.1.jar",
          "size": 55416,
          "sha512": "dea59064a20a600f12f141ca6fdc21349118d427cffa956c337a4cf522bd35260afc5e8188acdc8d76784083578ff8684ef7247c2a15459aac8665fb21ab2876",
          "sha256": "bc3c77c7626b75c35d3c26c05e3d2647c3524774f5660e8a9d50ed9bf493f0dd",
          "sha1": "10352b7caf90ab2745d3b6084c160a61355a3ed8",
          "md5": "15f2071b371ed21718db17b7960c4a2d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.2.1.jar",
          "url": "runescape-api-3.2.1.jar",
          "size": 55416,
          "sha512": "dea59064a20a600f12f141ca6fdc21349118d427cffa956c337a4cf522bd35260afc5e8188acdc8d76784083578ff8684ef7247c2a15459aac8665fb21ab2876",
          "sha256": "bc3c77c7626b75c35d3c26c05e3d2647c3524774f5660e8a9d50ed9bf493f0dd",
          "sha1": "10352b7caf90ab2745d3b6084c160a61355a3ed8",
          "md5": "15f2071b371ed21718db17b7960c4a2d"
        }
      ]
    }
  ]
}
