{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "ndbbolkjzbcjjgwekas4zmnnfa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.2.1.jar",
          "url": "runescape-api-3.2.1.jar",
          "size": 103399,
          "sha512": "a92a603b4e6192a38464f323dc7b9e6e01980f26b5ea98312b6b399cefbc8beb4b64d345d7e52a64b1fd97368e41f68a9112c653c7b4976bafb497f510c78db8",
          "sha256": "d6c249332c424e22cc5841cf28700a0666c9b312a7b32687ddb9cabfa6e2a577",
          "sha1": "a1444750841db3461602cc21d5b7b3f5e704a5e1",
          "md5": "5331539ce9586a481307136608b689e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.2.1.jar",
          "url": "runescape-api-3.2.1.jar",
          "size": 103399,
          "sha512": "a92a603b4e6192a38464f323dc7b9e6e01980f26b5ea98312b6b399cefbc8beb4b64d345d7e52a64b1fd97368e41f68a9112c653c7b4976bafb497f510c78db8",
          "sha256": "d6c249332c424e22cc5841cf28700a0666c9b312a7b32687ddb9cabfa6e2a577",
          "sha1": "a1444750841db3461602cc21d5b7b3f5e704a5e1",
          "md5": "5331539ce9586a481307136608b689e1"
        }
      ]
    }
  ]
}
