{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "zwqiea7fyjdfpd4o36qjkshjby"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.2.1.jar",
          "url": "runescape-api-3.2.1.jar",
          "size": 55427,
          "sha512": "0e85e99b581235fb5c3e90650cc678f16890c0b097a78ca15ad6f530ef96a85219e09797e6f0c7e50d284a5669a7dce6d2cee8ffa1868d8076cb3ea6b773c009",
          "sha256": "11f72bb81e86da4c3fff1fdc8b12535861d12dbd3f886d67ac66193ce508b46a",
          "sha1": "6d06b32baaafca4ad0896c2c2513b37b2d437030",
          "md5": "810a9134b6b1e1cd8da5d347b1a13c9a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.2.1.jar",
          "url": "runescape-api-3.2.1.jar",
          "size": 55427,
          "sha512": "0e85e99b581235fb5c3e90650cc678f16890c0b097a78ca15ad6f530ef96a85219e09797e6f0c7e50d284a5669a7dce6d2cee8ffa1868d8076cb3ea6b773c009",
          "sha256": "11f72bb81e86da4c3fff1fdc8b12535861d12dbd3f886d67ac66193ce508b46a",
          "sha1": "6d06b32baaafca4ad0896c2c2513b37b2d437030",
          "md5": "810a9134b6b1e1cd8da5d347b1a13c9a"
        }
      ]
    }
  ]
}
