{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "yrgrwxt35vgsnfumly2dkrrfcm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.9"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.9.jar",
          "url": "runescape-api-3.3.9.jar",
          "size": 103804,
          "sha512": "43603a3bf1b59d6b9bbae2fb53fba9bcc1978f71c9d5fc01a21281cecb712c01b4d88497ddf714ef49a6b7d46ecabd5cb0021ffc5715699eb0fdd820c887e1f5",
          "sha256": "ce7335bd0e26bf95452aa1905b48d1bde8b7958ae36ed40dabb1b52c7ac3110c",
          "sha1": "19480790f5aebd05b39249e2326c1f726df3588a",
          "md5": "029c767cbfa349b1260babfde3ce7ea1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.9"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.9.jar",
          "url": "runescape-api-3.3.9.jar",
          "size": 103804,
          "sha512": "43603a3bf1b59d6b9bbae2fb53fba9bcc1978f71c9d5fc01a21281cecb712c01b4d88497ddf714ef49a6b7d46ecabd5cb0021ffc5715699eb0fdd820c887e1f5",
          "sha256": "ce7335bd0e26bf95452aa1905b48d1bde8b7958ae36ed40dabb1b52c7ac3110c",
          "sha1": "19480790f5aebd05b39249e2326c1f726df3588a",
          "md5": "029c767cbfa349b1260babfde3ce7ea1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.9-sources.jar",
          "url": "runescape-api-3.3.9-sources.jar",
          "size": 99887,
          "sha512": "afc4c59b4bba462c2fb5e2a20ec3117455bb82eae23ff80af98dcfbee6ccf353f0625884403cd739b60caaf5bf5314da1404bac4fc7c1359beaf020139f0e0ad",
          "sha256": "0695d1cebb3d29b11c427df0cf419b1ad673b4af5a945843f1060297d79ed66b",
          "sha1": "d204bd92715f9eae34f0dc6c1d1482b776517eb1",
          "md5": "3cad4d6b13ccb2ef2055398452131498"
        }
      ]
    }
  ]
}
