{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "ag7kba57wnhh3fmqilynicfq5m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.4"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.4.jar",
          "url": "runescape-api-3.3.4.jar",
          "size": 103527,
          "sha512": "29bcfe03f9f2e0d8177f11b04750171536f51502d551c78acf4e3f7881d69ac8426ad24eb9dc316a58d73545368231ac127127db2ac108d1363232b9e6a8ebe2",
          "sha256": "4a2bc073ca5e5e4f1022ca1f93be6fce934f46df322eea9667bf7603b6d90ea2",
          "sha1": "d9b1eb1f18bb885b2ef76b702ca0bff029426842",
          "md5": "0945ae4fcef1d14f376cf62c21fdb253"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.4"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.4.jar",
          "url": "runescape-api-3.3.4.jar",
          "size": 103527,
          "sha512": "29bcfe03f9f2e0d8177f11b04750171536f51502d551c78acf4e3f7881d69ac8426ad24eb9dc316a58d73545368231ac127127db2ac108d1363232b9e6a8ebe2",
          "sha256": "4a2bc073ca5e5e4f1022ca1f93be6fce934f46df322eea9667bf7603b6d90ea2",
          "sha1": "d9b1eb1f18bb885b2ef76b702ca0bff029426842",
          "md5": "0945ae4fcef1d14f376cf62c21fdb253"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.4-sources.jar",
          "url": "runescape-api-3.3.4-sources.jar",
          "size": 99648,
          "sha512": "d7b0890dfc3e9f77ac1398d7ee42de072dee20d6ae3665ba9e9ec367c1240c44b72603951e8ffeb55e3383689ea3dece987d5a75c808a94f170fdc91e3207225",
          "sha256": "5176d999e912811c7cc61ca25b286c1d257ec4e56554f04657e10656ecafc2dc",
          "sha1": "0acfff4e2a68c1450a2979be336e37a7e2699a2a",
          "md5": "80e4f85cccf5675ca08813f1a3f69053"
        }
      ]
    }
  ]
}
