{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "lbk2szqrgbh5xm42c6tnlvu5kq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.4"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.4.jar",
          "url": "runescape-api-3.3.4.jar",
          "size": 103527,
          "sha512": "7bc99cdee8f095ec54a3710e0379f4435a9c719511e44d3724bd682a2252bd3ef44f8c0ca1681db94140a4a70ae905d4fec4068089264eaba27c82800a0e1cc3",
          "sha256": "95dc44ec34c308f3eb1f2bd20c28ade1c5956fade11fdd3ed04e756628a6c234",
          "sha1": "65b5b53596434a74588ce9d6d1a3f43f96713d7e",
          "md5": "6fd90eed53a9d08953f21cfa11c2bfbb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.4"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.4.jar",
          "url": "runescape-api-3.3.4.jar",
          "size": 103527,
          "sha512": "7bc99cdee8f095ec54a3710e0379f4435a9c719511e44d3724bd682a2252bd3ef44f8c0ca1681db94140a4a70ae905d4fec4068089264eaba27c82800a0e1cc3",
          "sha256": "95dc44ec34c308f3eb1f2bd20c28ade1c5956fade11fdd3ed04e756628a6c234",
          "sha1": "65b5b53596434a74588ce9d6d1a3f43f96713d7e",
          "md5": "6fd90eed53a9d08953f21cfa11c2bfbb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.4-sources.jar",
          "url": "runescape-api-3.3.4-sources.jar",
          "size": 99648,
          "sha512": "7d0c82d55322710b9a434be5629e7c79e132846b63336863b4e9fdb59c1931e849bf6961cb1ff936fd3b17fa842e43e6c27e779930f2fcdbf7ca3f882a0d6191",
          "sha256": "ee59c14f303dd251b37ec7244527d85492324635027b092dd3ac73857e8c887b",
          "sha1": "9beb068457bc29179fd2eb9614c55b803a0a92bf",
          "md5": "6416f6e709e1b59a5bdc53897b2d4d92"
        }
      ]
    }
  ]
}
