{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "qhua3n4ec5dqja3otg5t3f4w64"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.2.jar",
          "url": "http-api-3.3.2.jar",
          "size": 164095,
          "sha512": "81f24c39786b2cc22003b848d1ae745cde668d8af09bb23d9542ef673cdadac5658e4b30d22ef7a1b72d972601957adeadc0f99d2d29fff8579695d0732ae561",
          "sha256": "87237f79261d6fec1710e57e09bd55b0b2ffe48f087f79e606917338f2b382a9",
          "sha1": "5623ebde26d1e6c0e64a4da89e092ffb6e807ef4",
          "md5": "3b6295cbe870b2c5db97ec31dcf8cc2d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.2.jar",
          "url": "http-api-3.3.2.jar",
          "size": 164095,
          "sha512": "81f24c39786b2cc22003b848d1ae745cde668d8af09bb23d9542ef673cdadac5658e4b30d22ef7a1b72d972601957adeadc0f99d2d29fff8579695d0732ae561",
          "sha256": "87237f79261d6fec1710e57e09bd55b0b2ffe48f087f79e606917338f2b382a9",
          "sha1": "5623ebde26d1e6c0e64a4da89e092ffb6e807ef4",
          "md5": "3b6295cbe870b2c5db97ec31dcf8cc2d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.2-sources.jar",
          "url": "http-api-3.3.2-sources.jar",
          "size": 107156,
          "sha512": "4b6e5a1e61f5e1576216cb231d0ac859249ca3b466be192e7ff78a98f5066d23b7e98347ae752e1ef95e81f3643300e5675be010426a302de71a2ef5d6774c30",
          "sha256": "0a2c7d858abbe172958c65f08d624e1e2392879508d020cd7582589094f1e4e3",
          "sha1": "7e277a8a2cb464020a634d9eff3f480947f3b56d",
          "md5": "888ebbec6ce8fda4fd0c5a40ac726f1e"
        }
      ]
    }
  ]
}
