{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "yu5kkbhjerekljhtwxuz3g6oay"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.2.jar",
          "url": "http-api-3.3.2.jar",
          "size": 164097,
          "sha512": "ddc801986f20334ba7b57c10d9068047034a73552dd3a526ad99e463a9b0cdad24a612b57010d287b3cec28cd8731198599e9eb99e4cadba0a75eb75cff71b0a",
          "sha256": "fcae2de2cba374a0ca0e042cbd18f57cbd1cd7a6e3ce8603c8c36e474ba1f0dc",
          "sha1": "00ef404df9aa88101d13efc9537ca0eee5cc722f",
          "md5": "0030cd97bc03fe761f918995c93d1099"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.2.jar",
          "url": "http-api-3.3.2.jar",
          "size": 164097,
          "sha512": "ddc801986f20334ba7b57c10d9068047034a73552dd3a526ad99e463a9b0cdad24a612b57010d287b3cec28cd8731198599e9eb99e4cadba0a75eb75cff71b0a",
          "sha256": "fcae2de2cba374a0ca0e042cbd18f57cbd1cd7a6e3ce8603c8c36e474ba1f0dc",
          "sha1": "00ef404df9aa88101d13efc9537ca0eee5cc722f",
          "md5": "0030cd97bc03fe761f918995c93d1099"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.2-sources.jar",
          "url": "http-api-3.3.2-sources.jar",
          "size": 107156,
          "sha512": "329edfc593edd06e07cc4d1c0656ee28ef28b6572421e2d3673fabf6a3ad0c00f1ce894b7b6756156d2a770c60aa2d1165fa79e105edc026d8f1cde4ef0e4f25",
          "sha256": "6ca5c3ae57343f8c26fcbad1aab2860ebcc8f1efb4d9504dcc71d87e032f75d9",
          "sha1": "cd33568b92058b9fc9753da1215a296c3cc2ddc3",
          "md5": "35d29e65a5a79454d534a6ecebaa8f17"
        }
      ]
    }
  ]
}
