{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "kwxhedpo4zgwvfvzlx6kunma3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.2.jar",
          "url": "http-api-3.3.2.jar",
          "size": 164095,
          "sha512": "b44864e16829863afe7a19c1134c257b0f7ebd9f15710c55519be0af304251600d44be7bfd731507c119be8d9abb846617e8cf05b625baedbd5c455d7643e098",
          "sha256": "85fb27aad3c138b530794aad20250dc6561e1b23105178b01e5bfa9d325bb2fe",
          "sha1": "46a8c83664ad7102f5ff74f34fb0c2575e4c4c6c",
          "md5": "d79e9c77cf5de296b6d923a3873de0b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.2.jar",
          "url": "http-api-3.3.2.jar",
          "size": 164095,
          "sha512": "b44864e16829863afe7a19c1134c257b0f7ebd9f15710c55519be0af304251600d44be7bfd731507c119be8d9abb846617e8cf05b625baedbd5c455d7643e098",
          "sha256": "85fb27aad3c138b530794aad20250dc6561e1b23105178b01e5bfa9d325bb2fe",
          "sha1": "46a8c83664ad7102f5ff74f34fb0c2575e4c4c6c",
          "md5": "d79e9c77cf5de296b6d923a3873de0b3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.2-sources.jar",
          "url": "http-api-3.3.2-sources.jar",
          "size": 107156,
          "sha512": "1844b2871c93a463ccbecb0d7675b0988be5100742421040a1ba0ed99cf93452c3c09c7fe288213f1e8eaa1098ebef2c5a18ddfe3c2ef1e3b445c86b6f2a6c74",
          "sha256": "57543f27e5f08920cabbaa5ea3f848f85b7cc376670e2551e5f6c6435a4d273e",
          "sha1": "8199f74822a848e5eb10dc3e3953418d4c677611",
          "md5": "62151d75f980dfb96361ceda7aed865e"
        }
      ]
    }
  ]
}
