{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "jngamcpxfzgoves7ilesk3hvq4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.7.jar",
          "url": "injected-client-3.3.7.jar",
          "size": 2253215,
          "sha512": "adac35b8e1d08ec97740dbbe66d65c6c37b61e351f5ea947d3c5fa141bdccc2ec3732e974c00f44700268ad371bc72efa835651896031506d26086680f59f678",
          "sha256": "2d15f832ac9fabb2946c6fd26f763e420fe491d57c01c3476fa4b3e83147a18e",
          "sha1": "699fe917f3674f19a92bca0ce610df667d5b176d",
          "md5": "e454afb62a4b584708d4c72d4b3691d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.7.jar",
          "url": "injected-client-3.3.7.jar",
          "size": 2253215,
          "sha512": "adac35b8e1d08ec97740dbbe66d65c6c37b61e351f5ea947d3c5fa141bdccc2ec3732e974c00f44700268ad371bc72efa835651896031506d26086680f59f678",
          "sha256": "2d15f832ac9fabb2946c6fd26f763e420fe491d57c01c3476fa4b3e83147a18e",
          "sha1": "699fe917f3674f19a92bca0ce610df667d5b176d",
          "md5": "e454afb62a4b584708d4c72d4b3691d2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.7-sources.jar",
          "url": "injected-client-3.3.7-sources.jar",
          "size": 261,
          "sha512": "496607b305120e90c615126e2836c10b7d0fdee7cbc21e4d8ddff7b3f43d5821fbc790fd38d3c969b928ee5e58edb34a7c065b861bfeddc4873af7643f0bd13f",
          "sha256": "4402606f3979193d1dad34e5c67f9cb3b9ffb63cac06891e7f1e9d1c761f8493",
          "sha1": "0c9c8d25c3911edaf49eb47482559a32a3a18e21",
          "md5": "72f7816977af7e53e97dd387bb745b40"
        },
        {
          "name": "injected-client-3.3.7.jar",
          "url": "injected-client-3.3.7.jar",
          "size": 2253215,
          "sha512": "adac35b8e1d08ec97740dbbe66d65c6c37b61e351f5ea947d3c5fa141bdccc2ec3732e974c00f44700268ad371bc72efa835651896031506d26086680f59f678",
          "sha256": "2d15f832ac9fabb2946c6fd26f763e420fe491d57c01c3476fa4b3e83147a18e",
          "sha1": "699fe917f3674f19a92bca0ce610df667d5b176d",
          "md5": "e454afb62a4b584708d4c72d4b3691d2"
        }
      ]
    }
  ]
}
