{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ikmit3cvcbedtnwpv62fw77rhm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.8.jar",
          "url": "injected-client-3.3.8.jar",
          "size": 2304102,
          "sha512": "447f151a134617549e8af330e2547990d90f35ff4c3798713cd1019af613d4560968dcc30dfc6b42b64123fd3ab1198af5c8c3c9086a01385fb41c48aa0c95c4",
          "sha256": "d7abcc087a5fabb8c16fb8d1869ecfb6de679f6da1f1c21ffd44eaff06e3cd7d",
          "sha1": "e94abf246216b4c1071bc25291c055d1dd57b2aa",
          "md5": "d3a5b3f053528b697f47e3d519e1d106"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.8.jar",
          "url": "injected-client-3.3.8.jar",
          "size": 2304102,
          "sha512": "447f151a134617549e8af330e2547990d90f35ff4c3798713cd1019af613d4560968dcc30dfc6b42b64123fd3ab1198af5c8c3c9086a01385fb41c48aa0c95c4",
          "sha256": "d7abcc087a5fabb8c16fb8d1869ecfb6de679f6da1f1c21ffd44eaff06e3cd7d",
          "sha1": "e94abf246216b4c1071bc25291c055d1dd57b2aa",
          "md5": "d3a5b3f053528b697f47e3d519e1d106"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.8-sources.jar",
          "url": "injected-client-3.3.8-sources.jar",
          "size": 261,
          "sha512": "fd69544c5a14919e6e6fdb8e93fbf9d592f67fa8df670c290935b8cfcd86c06856a3b82653e6f79ea86fdcad59839aa2882aeac8502862b0f3814a424ff653a4",
          "sha256": "e335e10b523d5b05ef95ddf3fa0865c7bb5ae0cda804dfd6c9138e9e7f2c48fc",
          "sha1": "bac237812b85fc0c0ab8b5a27dba502d54c56ea1",
          "md5": "a057df7bdbbf6367276d0ff604f64077"
        },
        {
          "name": "injected-client-3.3.8.jar",
          "url": "injected-client-3.3.8.jar",
          "size": 2304102,
          "sha512": "447f151a134617549e8af330e2547990d90f35ff4c3798713cd1019af613d4560968dcc30dfc6b42b64123fd3ab1198af5c8c3c9086a01385fb41c48aa0c95c4",
          "sha256": "d7abcc087a5fabb8c16fb8d1869ecfb6de679f6da1f1c21ffd44eaff06e3cd7d",
          "sha1": "e94abf246216b4c1071bc25291c055d1dd57b2aa",
          "md5": "d3a5b3f053528b697f47e3d519e1d106"
        }
      ]
    }
  ]
}
