{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "nzaq77z37bdffixaxh3x3rbw2y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.8.jar",
          "url": "injected-client-3.3.8.jar",
          "size": 2304102,
          "sha512": "d3a868b4a8d460933e7ec34bf9d07ec89f4a115051aab90adc429dbb9a3a32be3e7fdf4550824225c6f39c41d19261df635f22e4e782447d224c775bfe0eea99",
          "sha256": "7ca6738d4f6a458abfa1b5606e29513b0928798f27a50ee43b7e6a0570599306",
          "sha1": "7818be4ca3d1986da44eda970d3faf8a3478bbdd",
          "md5": "e1bddbe040b85166ed248d44a5c64def"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.8.jar",
          "url": "injected-client-3.3.8.jar",
          "size": 2304102,
          "sha512": "d3a868b4a8d460933e7ec34bf9d07ec89f4a115051aab90adc429dbb9a3a32be3e7fdf4550824225c6f39c41d19261df635f22e4e782447d224c775bfe0eea99",
          "sha256": "7ca6738d4f6a458abfa1b5606e29513b0928798f27a50ee43b7e6a0570599306",
          "sha1": "7818be4ca3d1986da44eda970d3faf8a3478bbdd",
          "md5": "e1bddbe040b85166ed248d44a5c64def"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.8-sources.jar",
          "url": "injected-client-3.3.8-sources.jar",
          "size": 261,
          "sha512": "f3d8482d885c96deb025ef408995ec29991b7bd9ccb32e1cc49dc2dfbf3173b516b38070ad321e4c397a71d3a7fb3da9142859cd075834838a61d02712e5265b",
          "sha256": "ddd132e96413065dc91be16839ec7d29c24d6467a9e7511527bd07ccb74a4c59",
          "sha1": "a30fb0273692bb60ada6abf8d90c2aed65bf7293",
          "md5": "057dde15b9b14281e77ce950c0b4036b"
        },
        {
          "name": "injected-client-3.3.8.jar",
          "url": "injected-client-3.3.8.jar",
          "size": 2304102,
          "sha512": "d3a868b4a8d460933e7ec34bf9d07ec89f4a115051aab90adc429dbb9a3a32be3e7fdf4550824225c6f39c41d19261df635f22e4e782447d224c775bfe0eea99",
          "sha256": "7ca6738d4f6a458abfa1b5606e29513b0928798f27a50ee43b7e6a0570599306",
          "sha1": "7818be4ca3d1986da44eda970d3faf8a3478bbdd",
          "md5": "e1bddbe040b85166ed248d44a5c64def"
        }
      ]
    }
  ]
}
