{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "fydfladsszgijcgklcx6mw76by"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.8.jar",
          "url": "injected-client-3.3.8.jar",
          "size": 2304105,
          "sha512": "f889499c62ea8fd7d9208e396e316160877c25ebd7d208b37746702c895dc822803b33e74f6031c0b31dfd1aa71c58cb8f3a5d77edb0670b00522c52c9414f3a",
          "sha256": "adb95c678e8e06517e447fff59d80864fdff4bb21a0dc30567c650954132f926",
          "sha1": "b04811e4d8325c1dff8140d019054d2c752b354a",
          "md5": "458147af43c9f80e0c8c36b299c453a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.8.jar",
          "url": "injected-client-3.3.8.jar",
          "size": 2304105,
          "sha512": "f889499c62ea8fd7d9208e396e316160877c25ebd7d208b37746702c895dc822803b33e74f6031c0b31dfd1aa71c58cb8f3a5d77edb0670b00522c52c9414f3a",
          "sha256": "adb95c678e8e06517e447fff59d80864fdff4bb21a0dc30567c650954132f926",
          "sha1": "b04811e4d8325c1dff8140d019054d2c752b354a",
          "md5": "458147af43c9f80e0c8c36b299c453a4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.8-sources.jar",
          "url": "injected-client-3.3.8-sources.jar",
          "size": 261,
          "sha512": "0c3044ea4edb5ca10e6338fe3b579c73483c17842cbc262ed028f286e87c5f722e10518e314de305927e9fd20d5b310adbd927880e0d45f17fc0d0275aa87c32",
          "sha256": "040f7b25cb48278b6b3ff64cecef9a1f6725cf9cce3a0148edf43a3bb15f7377",
          "sha1": "6d17885f78c548d831d1ae22b33f6da7d5c7d222",
          "md5": "ae0182e495e09fa456b2d57bf17972d2"
        },
        {
          "name": "injected-client-3.3.8.jar",
          "url": "injected-client-3.3.8.jar",
          "size": 2304105,
          "sha512": "f889499c62ea8fd7d9208e396e316160877c25ebd7d208b37746702c895dc822803b33e74f6031c0b31dfd1aa71c58cb8f3a5d77edb0670b00522c52c9414f3a",
          "sha256": "adb95c678e8e06517e447fff59d80864fdff4bb21a0dc30567c650954132f926",
          "sha1": "b04811e4d8325c1dff8140d019054d2c752b354a",
          "md5": "458147af43c9f80e0c8c36b299c453a4"
        }
      ]
    }
  ]
}
