{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "7a6kzebvnjhcxbagy7cskuh2gy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.2.1.jar",
          "url": "injected-client-3.2.1.jar",
          "size": 2245481,
          "sha512": "63eb47a06a1fc8a9d157e90715f961c1c6a54edf245eb1b582e3f0ce06e088ce8a6e77345c606d56803b2fd765f000d590d94214d40092b12eb88ab5655b12e0",
          "sha256": "b399d0e8228c2c4929e5b1780091bd630670d1e84549dd65bd827a4d53561c8e",
          "sha1": "26386e19e63c0e46ec2fb6dd3f28d57b09092f69",
          "md5": "d5a6a734a80bc899c83a33c6d7a42829"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.2.1.jar",
          "url": "injected-client-3.2.1.jar",
          "size": 2245481,
          "sha512": "63eb47a06a1fc8a9d157e90715f961c1c6a54edf245eb1b582e3f0ce06e088ce8a6e77345c606d56803b2fd765f000d590d94214d40092b12eb88ab5655b12e0",
          "sha256": "b399d0e8228c2c4929e5b1780091bd630670d1e84549dd65bd827a4d53561c8e",
          "sha1": "26386e19e63c0e46ec2fb6dd3f28d57b09092f69",
          "md5": "d5a6a734a80bc899c83a33c6d7a42829"
        }
      ]
    }
  ]
}
