{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "isaxeb67jvg53ot6pksjewh2tm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.9.jar",
          "url": "runelite-api-3.3.9.jar",
          "size": 1218932,
          "sha512": "a215d8b0b201ab71b6095e27022e2387fe87e0753b5a2a17c290ce5d39d820efc08958dfa9b91b5b308679353e4c710c6e1f82130d3347e9c87d594a560f63f8",
          "sha256": "1c18aacdf2bf31c78d25d95d4ffed8eae8ce93b9bcec4d135c66b6c3c1fe6bb8",
          "sha1": "9eeb7d00a6bf8509f429f24f3045e0cbc107f2fe",
          "md5": "502b2cc53a9f848e8734a1d8a6896f71"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.9.jar",
          "url": "runelite-api-3.3.9.jar",
          "size": 1218932,
          "sha512": "a215d8b0b201ab71b6095e27022e2387fe87e0753b5a2a17c290ce5d39d820efc08958dfa9b91b5b308679353e4c710c6e1f82130d3347e9c87d594a560f63f8",
          "sha256": "1c18aacdf2bf31c78d25d95d4ffed8eae8ce93b9bcec4d135c66b6c3c1fe6bb8",
          "sha1": "9eeb7d00a6bf8509f429f24f3045e0cbc107f2fe",
          "md5": "502b2cc53a9f848e8734a1d8a6896f71"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.9-sources.jar",
          "url": "runelite-api-3.3.9-sources.jar",
          "size": 892214,
          "sha512": "ce68303c9e0cae0e2dee5f0fc11ce359e513834652e1a8abcd1f8952b79c181416ab210a60d5440f0bb3c4fed1d2750c180ab324da940d1b11e8c58f0acd4b0d",
          "sha256": "1260b1663aecc396cde3680008c73ee95e37dab068ba7e2d56611b1347c7d383",
          "sha1": "b5c5afe5b85e8eb3acc188030eedb7b1bc62565b",
          "md5": "7488d0dd70646382b266fb60d0771443"
        }
      ]
    }
  ]
}
