{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ypdns3u64rhjllm45ktm7fqcce"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.9.jar",
          "url": "runelite-api-3.3.9.jar",
          "size": 1219266,
          "sha512": "71b0a23be6cffc754d0390777970b6c88fa7e39f2276e0bafb9fd919ffa50f6109b9e266368db1cefb436593680217d4b81e26c5dc66939a4a805373d2c67200",
          "sha256": "122a17993c85a746fe23158495df7caed22320e9feeae0464990a48feb1175d0",
          "sha1": "31219c66c7745a90b35b3a23d82ff80c18a9dc7f",
          "md5": "b9b40d0367d12f87fb9f7ea747ec4fb9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.9.jar",
          "url": "runelite-api-3.3.9.jar",
          "size": 1219266,
          "sha512": "71b0a23be6cffc754d0390777970b6c88fa7e39f2276e0bafb9fd919ffa50f6109b9e266368db1cefb436593680217d4b81e26c5dc66939a4a805373d2c67200",
          "sha256": "122a17993c85a746fe23158495df7caed22320e9feeae0464990a48feb1175d0",
          "sha1": "31219c66c7745a90b35b3a23d82ff80c18a9dc7f",
          "md5": "b9b40d0367d12f87fb9f7ea747ec4fb9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.9-sources.jar",
          "url": "runelite-api-3.3.9-sources.jar",
          "size": 893198,
          "sha512": "ac38760515f1390f29ff62b00d23a587b9ecde621b09dd519d916dd7c859b8a0988e7c13b72a250368e8be01790f082b4af758612120ca3ab63ca20e5290377d",
          "sha256": "d63f4231bce1ffda022ebc451763b634a60f41d9fe6ff09ad0bdc66a3c7c8263",
          "sha1": "08ee16f67ccdb46afe5384fd33402583751f1d86",
          "md5": "833c8b8e72f776d99d2a6ddf6d3f2bbc"
        }
      ]
    }
  ]
}
