{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "oxealgw66fhjddcrzop6pkp5da"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.9.jar",
          "url": "runelite-api-3.3.9.jar",
          "size": 1218932,
          "sha512": "8e60ef07f6b98da0030e494046378e163f51efcf817299a05956ec555090a983575ab1659b7fea076cf92fb9a8f93574fbed578544ac59792218577ce89179c8",
          "sha256": "b2e5c94c29694f7cb436fe035a70207c5a0aaa3140ce8960fe160aa585450cc0",
          "sha1": "a1c6f87beaaf3f01ef6b82e5f566c4f83e0b8e19",
          "md5": "97d7d8d770dd73a10414ff514809cd8d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.9.jar",
          "url": "runelite-api-3.3.9.jar",
          "size": 1218932,
          "sha512": "8e60ef07f6b98da0030e494046378e163f51efcf817299a05956ec555090a983575ab1659b7fea076cf92fb9a8f93574fbed578544ac59792218577ce89179c8",
          "sha256": "b2e5c94c29694f7cb436fe035a70207c5a0aaa3140ce8960fe160aa585450cc0",
          "sha1": "a1c6f87beaaf3f01ef6b82e5f566c4f83e0b8e19",
          "md5": "97d7d8d770dd73a10414ff514809cd8d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.9-sources.jar",
          "url": "runelite-api-3.3.9-sources.jar",
          "size": 892214,
          "sha512": "dd9d4a08bc4e0e257127273523a84fed6e5a0c12d63f561b25cc172a121e7bb68292885a422a283c15ca2e6bcc92069e729f64b2a2726183fdd64de4b6be9a09",
          "sha256": "fb1b484d93c2c3d75f6a65665484453a9cfd242acec0abff6ea360c53c838b03",
          "sha1": "0fbee61121f6f1eef5c1702452316dc09770e8d6",
          "md5": "b042cdc539bc81a9f16bd66976b60af3"
        }
      ]
    }
  ]
}
