{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "ikgdvzzfu5awlmc37vrcb7rkde"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.9.jar",
          "url": "runelite-api-1.6.9.jar",
          "size": 1162957,
          "sha512": "6cb74f5f419da7ad2d1941c31bf49599b9142642a02266dc17d10506501964a0b0a61b8118c78106c05c368eb273b3c3024ae910d1f1170363be8d6c2c48b21b",
          "sha256": "bb3dd177cf8ab30d5de1aa82dd6693b65fb08f1865a70e2bbd214ce4350a3dc2",
          "sha1": "f9d9b73b14581c242be841f8ebbf04871474028f",
          "md5": "b7b927fcc7b6b97c2c3124584e93070b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.9.jar",
          "url": "runelite-api-1.6.9.jar",
          "size": 1162957,
          "sha512": "6cb74f5f419da7ad2d1941c31bf49599b9142642a02266dc17d10506501964a0b0a61b8118c78106c05c368eb273b3c3024ae910d1f1170363be8d6c2c48b21b",
          "sha256": "bb3dd177cf8ab30d5de1aa82dd6693b65fb08f1865a70e2bbd214ce4350a3dc2",
          "sha1": "f9d9b73b14581c242be841f8ebbf04871474028f",
          "md5": "b7b927fcc7b6b97c2c3124584e93070b"
        }
      ]
    }
  ]
}
