{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "2c3ukkycprglrc6ddokf4panqa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.9.jar",
          "url": "runelite-api-1.6.9.jar",
          "size": 1162158,
          "sha512": "9b7cc0e6f949fbe3d58f275009638d369963dc47c13d254e4078c96a1949f9995a81420f701199d923bc77679ed1e3907af1b4ea0fe951b4049a540b25d83079",
          "sha256": "5b12209676c4b91bc355b5a1a2ed623633c8c3f7e4fa2bdd29866ed4111b8bc2",
          "sha1": "ae3f03eecbedd4ac8d20d5ca8f23888f86012bbe",
          "md5": "a3cf0c2d3626a837f9d71a1ecd3f7038"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.9.jar",
          "url": "runelite-api-1.6.9.jar",
          "size": 1162158,
          "sha512": "9b7cc0e6f949fbe3d58f275009638d369963dc47c13d254e4078c96a1949f9995a81420f701199d923bc77679ed1e3907af1b4ea0fe951b4049a540b25d83079",
          "sha256": "5b12209676c4b91bc355b5a1a2ed623633c8c3f7e4fa2bdd29866ed4111b8bc2",
          "sha1": "ae3f03eecbedd4ac8d20d5ca8f23888f86012bbe",
          "md5": "a3cf0c2d3626a837f9d71a1ecd3f7038"
        }
      ]
    }
  ]
}
