{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "1.6.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "cskcfoke6rdynfykhrg3hp6afq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.6.9.jar",
          "url": "runelite-api-1.6.9.jar",
          "size": 1162158,
          "sha512": "c4862b5d5ef1538261bed6fc005084a5ea3b0ffa2396bd91b77af061d5bfda91d33ca70dce3f672930e9f91052d830360108501cd28cf484e5d1ed28f9391779",
          "sha256": "97f4aa484bd0fc0f71e34cce939ebeb389db03f2186eb09a3adbde0795758151",
          "sha1": "85db25417e09f21c4efdd25c0340e65031b2cfe0",
          "md5": "a318a9652912cb164b2cdf04a0b810e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.6.9.jar",
          "url": "runelite-api-1.6.9.jar",
          "size": 1162158,
          "sha512": "c4862b5d5ef1538261bed6fc005084a5ea3b0ffa2396bd91b77af061d5bfda91d33ca70dce3f672930e9f91052d830360108501cd28cf484e5d1ed28f9391779",
          "sha256": "97f4aa484bd0fc0f71e34cce939ebeb389db03f2186eb09a3adbde0795758151",
          "sha1": "85db25417e09f21c4efdd25c0340e65031b2cfe0",
          "md5": "a318a9652912cb164b2cdf04a0b810e7"
        }
      ]
    }
  ]
}
