{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "dekystweubc2fkvltozeuescuy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.6.jar",
          "url": "runelite-api-3.3.6.jar",
          "size": 1202812,
          "sha512": "3b02c0cda1b4dc716e105f1475e8f02c0817bde8b5dd706d8402a8735cc5a0784ae375cbe5504c7ec97ce5326cb41474c506d402c624b4a047f2a4b7f6837b71",
          "sha256": "753282d50a51565bd9510a2a64fb0baadf9cf2777f5e3eb7dc4b888df7e636cb",
          "sha1": "2c56548cc79e1c13edf0034057a5caddf1e997ea",
          "md5": "8dd79740477ecc5a05aec25e088eddc2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.6.jar",
          "url": "runelite-api-3.3.6.jar",
          "size": 1202812,
          "sha512": "3b02c0cda1b4dc716e105f1475e8f02c0817bde8b5dd706d8402a8735cc5a0784ae375cbe5504c7ec97ce5326cb41474c506d402c624b4a047f2a4b7f6837b71",
          "sha256": "753282d50a51565bd9510a2a64fb0baadf9cf2777f5e3eb7dc4b888df7e636cb",
          "sha1": "2c56548cc79e1c13edf0034057a5caddf1e997ea",
          "md5": "8dd79740477ecc5a05aec25e088eddc2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.6-sources.jar",
          "url": "runelite-api-3.3.6-sources.jar",
          "size": 881983,
          "sha512": "9e8e6668e82c75161ae6a82c9513cfe17cb712bba7a48e954aad4edc000c3c6539eff2e31203e94d214fdf9300ec8cf8e3079222a2302d31ba4d9b0c9fe0a4ea",
          "sha256": "9267d911057e773548bf662907a3ca4f0849072958ce404560a54aa75f285f85",
          "sha1": "e1f48102d5727f716ed656273713562824ff4e97",
          "md5": "0f3508ac71f07b9bb18e7a887486f70d"
        }
      ]
    }
  ]
}
