{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "7hipqha6nva27lqgxfy3r4htzy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.5.jar",
          "url": "injected-client-3.3.5.jar",
          "size": 2253602,
          "sha512": "3252aa459a855c69a468665f45099c436c42e7b62509908e975d472c497c4183c10f27da616c49a5080cfac7d09f55ce84a48c351f336459d3931209dfa28e31",
          "sha256": "44cb3d40f381a15e72c87afd6ee5720a89a03f91921ee751d4bcea338a009bed",
          "sha1": "2b41b6827217460fd421d4b8ea4fb0ed404f2a1e",
          "md5": "67eee221fb5bff705508d7b237d8783f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.5.jar",
          "url": "injected-client-3.3.5.jar",
          "size": 2253602,
          "sha512": "3252aa459a855c69a468665f45099c436c42e7b62509908e975d472c497c4183c10f27da616c49a5080cfac7d09f55ce84a48c351f336459d3931209dfa28e31",
          "sha256": "44cb3d40f381a15e72c87afd6ee5720a89a03f91921ee751d4bcea338a009bed",
          "sha1": "2b41b6827217460fd421d4b8ea4fb0ed404f2a1e",
          "md5": "67eee221fb5bff705508d7b237d8783f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.5-sources.jar",
          "url": "injected-client-3.3.5-sources.jar",
          "size": 261,
          "sha512": "2b6bb3fea8870e24fbc191502730fb270e138edc38dff9f5f5c5c0034c036728e39f6fc7de7f02913ca9fc9b0acde72bbab3a08f686b064133dde06a3dd04e31",
          "sha256": "55420ce389b776ff3ae5d3fd283aa03995eb7254b4f9549bad4c1ec8d0a9850c",
          "sha1": "ac4f6f54f293ecc1f6a81efd5e159b81af84e9f6",
          "md5": "1c1a087ad4285280eeca6a27534cab0e"
        },
        {
          "name": "injected-client-3.3.5.jar",
          "url": "injected-client-3.3.5.jar",
          "size": 2253602,
          "sha512": "3252aa459a855c69a468665f45099c436c42e7b62509908e975d472c497c4183c10f27da616c49a5080cfac7d09f55ce84a48c351f336459d3931209dfa28e31",
          "sha256": "44cb3d40f381a15e72c87afd6ee5720a89a03f91921ee751d4bcea338a009bed",
          "sha1": "2b41b6827217460fd421d4b8ea4fb0ed404f2a1e",
          "md5": "67eee221fb5bff705508d7b237d8783f"
        }
      ]
    }
  ]
}
