{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "7ery2omxijfmhd3z7dftf2faee"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.5.jar",
          "url": "injected-client-3.3.5.jar",
          "size": 2253602,
          "sha512": "10a4f34469f94075e944bd50fc4fa8b1e01d20e1fdba8c3b83ace6099db60f96e9bf624df3fd9f236d232232be877e8ed2f67138f02e48c45dbd4f624598f74b",
          "sha256": "bbe39eecd3a2adc3afd2795755937053f2ae4245b18f90283fe2946be37f5968",
          "sha1": "a1853da035a3f5b7318814d45068fe5dcfb39b3d",
          "md5": "1320a58e33153a9707f2563b86f082ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.5.jar",
          "url": "injected-client-3.3.5.jar",
          "size": 2253602,
          "sha512": "10a4f34469f94075e944bd50fc4fa8b1e01d20e1fdba8c3b83ace6099db60f96e9bf624df3fd9f236d232232be877e8ed2f67138f02e48c45dbd4f624598f74b",
          "sha256": "bbe39eecd3a2adc3afd2795755937053f2ae4245b18f90283fe2946be37f5968",
          "sha1": "a1853da035a3f5b7318814d45068fe5dcfb39b3d",
          "md5": "1320a58e33153a9707f2563b86f082ca"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.5-sources.jar",
          "url": "injected-client-3.3.5-sources.jar",
          "size": 261,
          "sha512": "bb30f4140f5d849953085f8e622ce9944b615f2319d2893b845d16ad44c53fda1a320478c6d024e161525014d472050fe1c188eb88d20fa99448a760320d5c12",
          "sha256": "0eede68c277e72a1aefc08d5f644dd485f7f1ccf1f1d1532b2e3de5f99023621",
          "sha1": "4c760f6a31cfe9f16d030680d3c467ad657eec6d",
          "md5": "a44a26fa66f79f7fd2a4f3c3ef517e1f"
        },
        {
          "name": "injected-client-3.3.5.jar",
          "url": "injected-client-3.3.5.jar",
          "size": 2253602,
          "sha512": "10a4f34469f94075e944bd50fc4fa8b1e01d20e1fdba8c3b83ace6099db60f96e9bf624df3fd9f236d232232be877e8ed2f67138f02e48c45dbd4f624598f74b",
          "sha256": "bbe39eecd3a2adc3afd2795755937053f2ae4245b18f90283fe2946be37f5968",
          "sha1": "a1853da035a3f5b7318814d45068fe5dcfb39b3d",
          "md5": "1320a58e33153a9707f2563b86f082ca"
        }
      ]
    }
  ]
}
