{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "o6zngoutazcp5ij7sb6whi2v3e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.5.jar",
          "url": "injected-client-3.3.5.jar",
          "size": 2253877,
          "sha512": "74b7e998e51237237be606b7dde9cdc134ce9d460537ea54a4bb5cdb4cc29b06d9637d1eb8f1287f4754a03c7022aca339c608670a85ffa22665a4393568256c",
          "sha256": "f96b75077ba4fd6bf7ba4df2e2aa2f075f8e3637ec2b5865ad383837e6dd2279",
          "sha1": "14d5644f4658beb46bc0079627d27af53725446c",
          "md5": "62fb8564f0ca1112c80219de4c5021cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.5.jar",
          "url": "injected-client-3.3.5.jar",
          "size": 2253877,
          "sha512": "74b7e998e51237237be606b7dde9cdc134ce9d460537ea54a4bb5cdb4cc29b06d9637d1eb8f1287f4754a03c7022aca339c608670a85ffa22665a4393568256c",
          "sha256": "f96b75077ba4fd6bf7ba4df2e2aa2f075f8e3637ec2b5865ad383837e6dd2279",
          "sha1": "14d5644f4658beb46bc0079627d27af53725446c",
          "md5": "62fb8564f0ca1112c80219de4c5021cb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.5-sources.jar",
          "url": "injected-client-3.3.5-sources.jar",
          "size": 261,
          "sha512": "daa0bb99c9e06f761c813493e01e3b6a1badb0f907f326160b17a46eb50f1c622c027a854bdea42d52a85287ab5a0396f73e7ce8482caa11ff40d96ecbf9983e",
          "sha256": "c896ece3484eb769cbca2b471b0e85193a0042d1e1e94949150083d69058ffb4",
          "sha1": "144df8dd25036a9d8f3469e827b87981486ba06f",
          "md5": "315815a12085a3dffffd0cae3347462f"
        },
        {
          "name": "injected-client-3.3.5.jar",
          "url": "injected-client-3.3.5.jar",
          "size": 2253877,
          "sha512": "74b7e998e51237237be606b7dde9cdc134ce9d460537ea54a4bb5cdb4cc29b06d9637d1eb8f1287f4754a03c7022aca339c608670a85ffa22665a4393568256c",
          "sha256": "f96b75077ba4fd6bf7ba4df2e2aa2f075f8e3637ec2b5865ad383837e6dd2279",
          "sha1": "14d5644f4658beb46bc0079627d27af53725446c",
          "md5": "62fb8564f0ca1112c80219de4c5021cb"
        }
      ]
    }
  ]
}
