{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "qzmbipda5jfznlm2sxelz6imfy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.1.0.jar",
          "url": "runescape-api-3.1.0.jar",
          "size": 55408,
          "sha512": "b8b88006112bfe0255c2b99e4885d657e3b49d89e6934d49bc5b5fffdbe9b638b6c2a12bd0bbc167f2e25a584b6414a1e2aa557674e7c54776a5f28f1bed7cd0",
          "sha256": "7781126a7e98a1e7209719f98c2e54d01860fa1fe748ef2dea1245e5bfc54cc1",
          "sha1": "cec892647532502d0880adc9f63b8fb6f3585907",
          "md5": "60bc560ce29730bce8265338062d42b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.1.0.jar",
          "url": "runescape-api-3.1.0.jar",
          "size": 55408,
          "sha512": "b8b88006112bfe0255c2b99e4885d657e3b49d89e6934d49bc5b5fffdbe9b638b6c2a12bd0bbc167f2e25a584b6414a1e2aa557674e7c54776a5f28f1bed7cd0",
          "sha256": "7781126a7e98a1e7209719f98c2e54d01860fa1fe748ef2dea1245e5bfc54cc1",
          "sha1": "cec892647532502d0880adc9f63b8fb6f3585907",
          "md5": "60bc560ce29730bce8265338062d42b1"
        }
      ]
    }
  ]
}
