{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "otqveiv2azb5rmwjys3mkini5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.1.0.jar",
          "url": "runescape-api-3.1.0.jar",
          "size": 55416,
          "sha512": "77f5bdf409714f182d27805205bcbef6cf478101bac5d7c662eaa0a2b7b3df449221400cfa2404e08d082ae01acbf017dabe546e7c905330c8d20a8c5db132a2",
          "sha256": "aae0c115312a1864a469eccb5d16d91b6bab366cd41b1f4cc4acdb9c5ac42738",
          "sha1": "d128fc053330b620e394f20e9034696e101d548f",
          "md5": "01af977c96e0e5a994de1c2ffd1994e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.1.0.jar",
          "url": "runescape-api-3.1.0.jar",
          "size": 55416,
          "sha512": "77f5bdf409714f182d27805205bcbef6cf478101bac5d7c662eaa0a2b7b3df449221400cfa2404e08d082ae01acbf017dabe546e7c905330c8d20a8c5db132a2",
          "sha256": "aae0c115312a1864a469eccb5d16d91b6bab366cd41b1f4cc4acdb9c5ac42738",
          "sha1": "d128fc053330b620e394f20e9034696e101d548f",
          "md5": "01af977c96e0e5a994de1c2ffd1994e7"
        }
      ]
    }
  ]
}
