{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "6wnuhmf4lnh2hkpdlgbiddxdcm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.1.0.jar",
          "url": "runescape-api-3.1.0.jar",
          "size": 55408,
          "sha512": "b9662edef8df8dc372b213ed654c915655d05cab68fc6e88bab913ddd4cb1d5bcb99f6e3b967a815412211d487d919a7753da7f1877aef26759e0d6ffaa72289",
          "sha256": "30de2d43ab192103dca1fbc3227e39ebdc809064d659b580c36df5fdfb31753b",
          "sha1": "e355b9290e05403d100447c30e121e31152c189d",
          "md5": "b4eda67c1b5df6e5e6d7a08ad6d4719e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.1.0.jar",
          "url": "runescape-api-3.1.0.jar",
          "size": 55408,
          "sha512": "b9662edef8df8dc372b213ed654c915655d05cab68fc6e88bab913ddd4cb1d5bcb99f6e3b967a815412211d487d919a7753da7f1877aef26759e0d6ffaa72289",
          "sha256": "30de2d43ab192103dca1fbc3227e39ebdc809064d659b580c36df5fdfb31753b",
          "sha1": "e355b9290e05403d100447c30e121e31152c189d",
          "md5": "b4eda67c1b5df6e5e6d7a08ad6d4719e"
        }
      ]
    }
  ]
}
