{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "mrii4sqkqvf4znlodbpmkkl2ce"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.5.jar",
          "url": "runelite-api-3.3.5.jar",
          "size": 1184063,
          "sha512": "86bf22d425f19a194780a1caf395dd2d4cdba099163e91dcdffab606719896f0c73c06bc94f1cd15d2d3dbd0ad4851a769373ee7477ad7e819b484408ca66c86",
          "sha256": "516eecbdfc4dbdaaa984062e996de9fbcc314248b0deb04260b429ada491db09",
          "sha1": "9853509e483494bf1355115910ebc8cc0293d8b1",
          "md5": "8847d5c333e5f8cb3c9acf485a66248b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.5.jar",
          "url": "runelite-api-3.3.5.jar",
          "size": 1184063,
          "sha512": "86bf22d425f19a194780a1caf395dd2d4cdba099163e91dcdffab606719896f0c73c06bc94f1cd15d2d3dbd0ad4851a769373ee7477ad7e819b484408ca66c86",
          "sha256": "516eecbdfc4dbdaaa984062e996de9fbcc314248b0deb04260b429ada491db09",
          "sha1": "9853509e483494bf1355115910ebc8cc0293d8b1",
          "md5": "8847d5c333e5f8cb3c9acf485a66248b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.5-sources.jar",
          "url": "runelite-api-3.3.5-sources.jar",
          "size": 868748,
          "sha512": "2f227bacc19060fc3d64c04773b0366715b47db1217a259a1f2adb34793e5540dbc28af3da12038638721df98fd4500fb0814276cebd2c2f8927e21c0052069a",
          "sha256": "d99b0b675492487c0d291fa38fd3c1ec14cccb93755a138beba6ea29766dbbac",
          "sha1": "8ddb2eb7048bdb66de7d4a06009a5b1633076383",
          "md5": "0a941a13aa22e30368dbd607f2bdf999"
        }
      ]
    }
  ]
}
