{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "fujdrd7w6nh75aw2luhoxfpy4a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.5.jar",
          "url": "runelite-api-3.3.5.jar",
          "size": 1184063,
          "sha512": "aa518377e7ceeba0fba2a5e9bacdc1260a21374a97f870882de23bdfb859dc752aaad2b3a27842590dd420172b8772a523c4950a9f3da5c79a1d809600afb4bd",
          "sha256": "47ef1ffdd7bfdb120bf7d556a7dd886a296d8a39cab9e4f8ddf17d461381f937",
          "sha1": "e25ab2a9f61e4a96892aff50cd0f43a65e37055a",
          "md5": "a7e7e8bd7ec7a0993ff5f58272a704f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.5.jar",
          "url": "runelite-api-3.3.5.jar",
          "size": 1184063,
          "sha512": "aa518377e7ceeba0fba2a5e9bacdc1260a21374a97f870882de23bdfb859dc752aaad2b3a27842590dd420172b8772a523c4950a9f3da5c79a1d809600afb4bd",
          "sha256": "47ef1ffdd7bfdb120bf7d556a7dd886a296d8a39cab9e4f8ddf17d461381f937",
          "sha1": "e25ab2a9f61e4a96892aff50cd0f43a65e37055a",
          "md5": "a7e7e8bd7ec7a0993ff5f58272a704f9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.5-sources.jar",
          "url": "runelite-api-3.3.5-sources.jar",
          "size": 868748,
          "sha512": "9611ee4d0cc3562b9bb7007b109db2f5ab88b354e24e5b0ab1ccc9796459bef3362160f8c015c5c131ce10c8dcd7a8438e48622ccb87e7d28ea23ea311b3002e",
          "sha256": "34c924c6a7d237d492bacbf8fc5dd67cc4b79fd9dceb6c7c01ffd48214dd81c3",
          "sha1": "5f424d4486c7f54272e3c3dc0766b60a9e73a9dc",
          "md5": "dcf6e7177b1209c7835320964708dfd2"
        }
      ]
    }
  ]
}
