{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "lbjchl7vojad5hso6dnxtq4a3y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.5.jar",
          "url": "runelite-api-3.3.5.jar",
          "size": 1184063,
          "sha512": "5625c53e9016f9dd9d8c7eae0efbc6ada1f65d7ccddee93c64865f42d2d5c8750ae13c7344cf4cf546bfd411267a89e5e7a2cc6820702ea83f9f64b239a027bd",
          "sha256": "6772e5a0337a9e787d102ffae5a4f8668acd2de76f9a39d22a02e828d62cde58",
          "sha1": "93072bfc2dc2c8f785c601dc3790f7c3fbcd27f0",
          "md5": "f8943fa301a376865d05946fd9bda23b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.5.jar",
          "url": "runelite-api-3.3.5.jar",
          "size": 1184063,
          "sha512": "5625c53e9016f9dd9d8c7eae0efbc6ada1f65d7ccddee93c64865f42d2d5c8750ae13c7344cf4cf546bfd411267a89e5e7a2cc6820702ea83f9f64b239a027bd",
          "sha256": "6772e5a0337a9e787d102ffae5a4f8668acd2de76f9a39d22a02e828d62cde58",
          "sha1": "93072bfc2dc2c8f785c601dc3790f7c3fbcd27f0",
          "md5": "f8943fa301a376865d05946fd9bda23b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.5-sources.jar",
          "url": "runelite-api-3.3.5-sources.jar",
          "size": 868748,
          "sha512": "81b3e526d6e43b6891d398f40eae198e0ec374edff7df7df6dee112580ff44d00772f23963825b7a78779b8660a4dad16e5353a5703ac9271a8f69ad75305ee1",
          "sha256": "69f38560be66d5c68acaef3cbc67a1afefd4ec0dab3d50020adaee7c1df160cc",
          "sha1": "9a3684370425dcd26491dda683758e739692c0d7",
          "md5": "436064402961e2d9fde1e53d537218d3"
        }
      ]
    }
  ]
}
