{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "jngamcpxfzgoves7ilesk3hvq4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.7.jar",
          "url": "runelite-api-3.3.7.jar",
          "size": 1214092,
          "sha512": "60ee5337a6b64e14da215721a6d8a604cf8e3fb733ca98885c39458d89fa58bd1dfc59643e1c605faf1401f1963bf368a319ca866abb17b606bf369a91536e5b",
          "sha256": "6e8d1df7ab2aeda44079588ed2279b60a70d41145a5b0b52a7585f825c1b0d9e",
          "sha1": "2333ba0ab1c6bec5dc38ee8ee5d3f42f0575bd00",
          "md5": "0eb0e5b56178036c98cbb28bad485e8b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.7.jar",
          "url": "runelite-api-3.3.7.jar",
          "size": 1214092,
          "sha512": "60ee5337a6b64e14da215721a6d8a604cf8e3fb733ca98885c39458d89fa58bd1dfc59643e1c605faf1401f1963bf368a319ca866abb17b606bf369a91536e5b",
          "sha256": "6e8d1df7ab2aeda44079588ed2279b60a70d41145a5b0b52a7585f825c1b0d9e",
          "sha1": "2333ba0ab1c6bec5dc38ee8ee5d3f42f0575bd00",
          "md5": "0eb0e5b56178036c98cbb28bad485e8b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.7-sources.jar",
          "url": "runelite-api-3.3.7-sources.jar",
          "size": 888865,
          "sha512": "af6fbbf4d65e55057e84400d7cbb43845515d74a1bbee29574d5e42b69544e73f959cf7f1f46176ebc6ad75fe01d80f4fca35e25dd170eba57e6552626d979f0",
          "sha256": "fe4441a359df98f38e60eb58c29671c43bd6da31561a89c2c2f03d41ef0cff19",
          "sha1": "cbfb291165f86698a39392be3d8f282c325dfbc8",
          "md5": "0670d03931fe221ae33b312fe19e5b98"
        }
      ]
    }
  ]
}
