{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "3yeprqic7nhydhhejnplopuewq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.7.jar",
          "url": "http-api-1.6.7.jar",
          "size": 165768,
          "sha512": "ad1c4661302e03354f529f7178af4680eeff1e5436495fd738e7ba6ea5041f6eacf8fc3e8637e89012e42e7a0b618a139ef7a036eaf2bdc17982ff51564d1ae5",
          "sha256": "5435714c4362121185ef5311f292236d901438c5be5e0cdb81744b15e7c21559",
          "sha1": "f734e61efdf6b13da5304fb8b57f5c822d41cd80",
          "md5": "69fd7bcd091ecce3b602eeaed347d570"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.7.jar",
          "url": "http-api-1.6.7.jar",
          "size": 165768,
          "sha512": "ad1c4661302e03354f529f7178af4680eeff1e5436495fd738e7ba6ea5041f6eacf8fc3e8637e89012e42e7a0b618a139ef7a036eaf2bdc17982ff51564d1ae5",
          "sha256": "5435714c4362121185ef5311f292236d901438c5be5e0cdb81744b15e7c21559",
          "sha1": "f734e61efdf6b13da5304fb8b57f5c822d41cd80",
          "md5": "69fd7bcd091ecce3b602eeaed347d570"
        }
      ]
    }
  ]
}
