{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "qwkihedazrfibkaaa45s3q2vmu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.7.jar",
          "url": "http-api-1.6.7.jar",
          "size": 165946,
          "sha512": "931977093eeb88a7300ea3133bf945fab05f59c184f9e57a064560ba5739968fd85b309cd7228dee1aaea8ffff656e8b8167795893ccf32ed558d34a5fdacd9e",
          "sha256": "bf26cadc319e470f30c07f0bc796dd1aa8a1d5d27cdcda970125976fcd6f7358",
          "sha1": "52a23b0c84824080425f38ddb324dde266de76b7",
          "md5": "a62428c0f6f7106c0e119d8f3d832490"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.7.jar",
          "url": "http-api-1.6.7.jar",
          "size": 165946,
          "sha512": "931977093eeb88a7300ea3133bf945fab05f59c184f9e57a064560ba5739968fd85b309cd7228dee1aaea8ffff656e8b8167795893ccf32ed558d34a5fdacd9e",
          "sha256": "bf26cadc319e470f30c07f0bc796dd1aa8a1d5d27cdcda970125976fcd6f7358",
          "sha1": "52a23b0c84824080425f38ddb324dde266de76b7",
          "md5": "a62428c0f6f7106c0e119d8f3d832490"
        }
      ]
    }
  ]
}
