{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "dhs5o6xuyfce3ar2l7tu6uetgu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.7.jar",
          "url": "http-api-1.6.7.jar",
          "size": 165767,
          "sha512": "029b2b4d4b5e810ae6e4c2b265a62737e779c1018f4b91c8ef3e8e5995e26cecf069ad3baba4871d2e0a0563df670bfb9dcee34691f7437afdc3109bd487f403",
          "sha256": "3c631e541a8833c42bee34bc46d33cd7fc6d368d3316ebc32d0ae1cb9c4d560b",
          "sha1": "9dcb246e4fe1424cc41a59ba05f3e44e14162521",
          "md5": "3072a0ea6b86f3f222e1c016b318f233"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.7.jar",
          "url": "http-api-1.6.7.jar",
          "size": 165767,
          "sha512": "029b2b4d4b5e810ae6e4c2b265a62737e779c1018f4b91c8ef3e8e5995e26cecf069ad3baba4871d2e0a0563df670bfb9dcee34691f7437afdc3109bd487f403",
          "sha256": "3c631e541a8833c42bee34bc46d33cd7fc6d368d3316ebc32d0ae1cb9c4d560b",
          "sha1": "9dcb246e4fe1424cc41a59ba05f3e44e14162521",
          "md5": "3072a0ea6b86f3f222e1c016b318f233"
        }
      ]
    }
  ]
}
