{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "a2gjxh77vngi3krupglpd6imgi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.0.7.jar",
          "url": "runelite-api-3.0.7.jar",
          "size": 1162957,
          "sha512": "d9d688230bce5a02f6f9c846ba27e6056121880ab2001f373b2d5ddd4aae97e182c78b4a86dd6bd5dbdf7e756d486c6d47ad2dec198ca6ef627864c5f8fbd6b8",
          "sha256": "5ca7b0a0db6b727f71db691076d8570aef0ba799b1ea61eabe4d67a9f36e2ab0",
          "sha1": "fea8eb7ecc26d587270bb60cc0d90744d709d392",
          "md5": "bc57e0af2612d4f0800f7cdd475803f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.0.7.jar",
          "url": "runelite-api-3.0.7.jar",
          "size": 1162957,
          "sha512": "d9d688230bce5a02f6f9c846ba27e6056121880ab2001f373b2d5ddd4aae97e182c78b4a86dd6bd5dbdf7e756d486c6d47ad2dec198ca6ef627864c5f8fbd6b8",
          "sha256": "5ca7b0a0db6b727f71db691076d8570aef0ba799b1ea61eabe4d67a9f36e2ab0",
          "sha1": "fea8eb7ecc26d587270bb60cc0d90744d709d392",
          "md5": "bc57e0af2612d4f0800f7cdd475803f8"
        }
      ]
    }
  ]
}
