{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "75hjafas2bcyriu3ba6eqlelyi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.0.7.jar",
          "url": "runelite-api-3.0.7.jar",
          "size": 1162957,
          "sha512": "96ff42a3166d69332585d9c7f6b6e3419a8bf63f76700ecda9edf396840625f7c7f7fc35a373abc4c1648f92801e6c6a26a3e2482cb76aa2caae2dc22c88b0eb",
          "sha256": "2b7bbe6b69a3dda2a6056e32e4df952f709ce39bf3241c9478a888fa159ec8c1",
          "sha1": "5d52f11a938dc516ccf5a48a45caba788d8f4c4d",
          "md5": "410dd6992741ba6118d5343125fd03d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.0.7.jar",
          "url": "runelite-api-3.0.7.jar",
          "size": 1162957,
          "sha512": "96ff42a3166d69332585d9c7f6b6e3419a8bf63f76700ecda9edf396840625f7c7f7fc35a373abc4c1648f92801e6c6a26a3e2482cb76aa2caae2dc22c88b0eb",
          "sha256": "2b7bbe6b69a3dda2a6056e32e4df952f709ce39bf3241c9478a888fa159ec8c1",
          "sha1": "5d52f11a938dc516ccf5a48a45caba788d8f4c4d",
          "md5": "410dd6992741ba6118d5343125fd03d4"
        }
      ]
    }
  ]
}
