{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "36hbq5herfeilevtvng3rccmvu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.0.7.jar",
          "url": "runelite-api-3.0.7.jar",
          "size": 1164264,
          "sha512": "fffc977e9d3c172fa4bba1166ab174df9355ddc022e1aef58f5be3030011441ca6d54621068407b2821f21011aec5cc90c8982d0d7a1999529812c99a7920bee",
          "sha256": "a82e8c9458c3e2df857409411e4d189683e81ee8e827ac914c6e7c4d162de05c",
          "sha1": "590186b453f92e4e651b044b3343672449e2b251",
          "md5": "1828d42043339c35d95aced266d7a0f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.0.7.jar",
          "url": "runelite-api-3.0.7.jar",
          "size": 1164264,
          "sha512": "fffc977e9d3c172fa4bba1166ab174df9355ddc022e1aef58f5be3030011441ca6d54621068407b2821f21011aec5cc90c8982d0d7a1999529812c99a7920bee",
          "sha256": "a82e8c9458c3e2df857409411e4d189683e81ee8e827ac914c6e7c4d162de05c",
          "sha1": "590186b453f92e4e651b044b3343672449e2b251",
          "md5": "1828d42043339c35d95aced266d7a0f1"
        }
      ]
    }
  ]
}
