{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "cmh5tj3225allmu3g7pomyp7n4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.5.jar",
          "url": "http-api-3.3.5.jar",
          "size": 154170,
          "sha512": "b6153cb6c20090f9447a0f818ad22b397cc5f253f24b88a79228189ec25022a99b71b8ea31dc5336419d05413be239fcf88b7972572d361698397e21aefbe6a7",
          "sha256": "8a2ee5a48af3b78dc18719ad2aeb38b1199f8875bcc3af1b0600ea48dbe499f1",
          "sha1": "2e0600c2de7fd8386aee466f80e82c1b5c834f19",
          "md5": "145066df92bdda3dbd8a70f8acf0aa54"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.5"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.5.jar",
          "url": "http-api-3.3.5.jar",
          "size": 154170,
          "sha512": "b6153cb6c20090f9447a0f818ad22b397cc5f253f24b88a79228189ec25022a99b71b8ea31dc5336419d05413be239fcf88b7972572d361698397e21aefbe6a7",
          "sha256": "8a2ee5a48af3b78dc18719ad2aeb38b1199f8875bcc3af1b0600ea48dbe499f1",
          "sha1": "2e0600c2de7fd8386aee466f80e82c1b5c834f19",
          "md5": "145066df92bdda3dbd8a70f8acf0aa54"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.5-sources.jar",
          "url": "http-api-3.3.5-sources.jar",
          "size": 101939,
          "sha512": "ab951649cf86faf91b479be23cbeb08339ac5ce5911a9cf803ce0bfebcfd04e1faaae504b621e10028aa34dc3528539ccb7c5dbdc04a52d7e16bed965982fb05",
          "sha256": "3d67f4301f879818be2e0eecf2786608ae0b234cc641641bf6cbf7e6f3f0958d",
          "sha1": "fc850b5eb6e4fc6644310bd6fee53e562be1f9bb",
          "md5": "1241a57bcb5109e6c23814afccc8705e"
        }
      ]
    }
  ]
}
