{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "fj5ipvm2g5hljagfnguvn7yqly"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.5.jar",
          "url": "http-api-3.3.5.jar",
          "size": 154238,
          "sha512": "c4fac017dcc2f605b8f3b5d4a9d5711b90269ffcdd6f363469e1445ac704fdb7c1c2fa1c54e481c2f6604f2885135d94f11ae4a25aa2938e2cd968cc4ae5e3dd",
          "sha256": "02d1dab48046dc0a1a29e673c148bdaf24a88aacc2bf4183e4699662ce0aeee4",
          "sha1": "32f0f9572409b6f5ac122655875b5b9b7b9de3e4",
          "md5": "36f6489824e6195683ab3d3c12f9a0ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.5"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.5.jar",
          "url": "http-api-3.3.5.jar",
          "size": 154238,
          "sha512": "c4fac017dcc2f605b8f3b5d4a9d5711b90269ffcdd6f363469e1445ac704fdb7c1c2fa1c54e481c2f6604f2885135d94f11ae4a25aa2938e2cd968cc4ae5e3dd",
          "sha256": "02d1dab48046dc0a1a29e673c148bdaf24a88aacc2bf4183e4699662ce0aeee4",
          "sha1": "32f0f9572409b6f5ac122655875b5b9b7b9de3e4",
          "md5": "36f6489824e6195683ab3d3c12f9a0ea"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.5-sources.jar",
          "url": "http-api-3.3.5-sources.jar",
          "size": 101948,
          "sha512": "34221a4cdd852f55e26a473184e37a66077b7d623b09492cfd5b5f3d6d8c234bfbc7917d2127383efc86cb564bfb3961fbbf29be4fd930566af00659cd2b6860",
          "sha256": "df08110f18834b99aeeb58cb0870577afa94bb2993d13b3475eba5b7da56503d",
          "sha1": "79367994416e8e323b8f64c18209348788490c1f",
          "md5": "0a8b2a383eaf1688b74782e1d2035f76"
        }
      ]
    }
  ]
}
