{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "wisuq2chzfd6zkotqzcpndniwy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.5.jar",
          "url": "http-api-3.3.5.jar",
          "size": 154170,
          "sha512": "7a3528a297a757ad5bbf932eced44b5102a64a095bc563604e1d2f722e09c6b7bbdf43b035702de95df9b9deb2ce0fdfa3970085626b2220613eee82de20a950",
          "sha256": "1e1134c755e4be6c9c2a86ad9395fdaff6243eb3ae4679c265ce34b62cfb3b63",
          "sha1": "adc48b86d1eb334c1acb37887a021799629c893f",
          "md5": "85e8cdaef11d58a43b742d3788569509"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.5"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.5.jar",
          "url": "http-api-3.3.5.jar",
          "size": 154170,
          "sha512": "7a3528a297a757ad5bbf932eced44b5102a64a095bc563604e1d2f722e09c6b7bbdf43b035702de95df9b9deb2ce0fdfa3970085626b2220613eee82de20a950",
          "sha256": "1e1134c755e4be6c9c2a86ad9395fdaff6243eb3ae4679c265ce34b62cfb3b63",
          "sha1": "adc48b86d1eb334c1acb37887a021799629c893f",
          "md5": "85e8cdaef11d58a43b742d3788569509"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.5-sources.jar",
          "url": "http-api-3.3.5-sources.jar",
          "size": 101939,
          "sha512": "73427ad8ac3519c0271ea3e525823361007c914d5b5858307aa7344c80bfdf59e0cf2dde69d42493cdc3c1eb401d746adca6d6d1103c1bf8fc3b0839dca7c630",
          "sha256": "8752b48a0b01fad41139dda274bdb0890b648c9aa98b29eed9cdaf9011ce263b",
          "sha1": "d46ea9d028f62331f91fa107523e015bf8c2f6fb",
          "md5": "75a0e3ac9662c3838b782279dc511ad4"
        }
      ]
    }
  ]
}
