{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "li2nsmyq7bc6jiqb2eic42qkhq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200130.005027-1.jar",
          "size": 2264669,
          "sha512": "7fc21d11c6311dfd836c4dcff2021c32173c396d2d51cbe92a561291fc722ed498d9e59a0bf78267d57607a02542e92e92082b81fed28cc97e46184c56ce89e8",
          "sha256": "9d511b6fe0b8eaed6e4e7f17f3ef242d23c27965b559b2fbd366e54b6aab30e4",
          "sha1": "2c73fa1476d3b9a9eb70a990678b6c4c79543cd6",
          "md5": "f9b2feb5f68c9ddca81fa383af616a79"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200130.005027-1.jar",
          "size": 2264669,
          "sha512": "7fc21d11c6311dfd836c4dcff2021c32173c396d2d51cbe92a561291fc722ed498d9e59a0bf78267d57607a02542e92e92082b81fed28cc97e46184c56ce89e8",
          "sha256": "9d511b6fe0b8eaed6e4e7f17f3ef242d23c27965b559b2fbd366e54b6aab30e4",
          "sha1": "2c73fa1476d3b9a9eb70a990678b6c4c79543cd6",
          "md5": "f9b2feb5f68c9ddca81fa383af616a79"
        }
      ]
    }
  ]
}
