{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "tiztyuvfznfixlzvedzgio4hpu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200208.000922-1.jar",
          "size": 2265655,
          "sha512": "369b9bf111784891fad37f4c48cb488c1f85ec151f88c8ae352a0366e59affcbea05f084602a7e1d5ec093110737b1ce326d1ab6709bf9c37360116801aa654c",
          "sha256": "2ffdbb0eebcb2ac3f7e87c075ca42f01c3dcab51df87227fd5855a69996a66b7",
          "sha1": "f687111b68685e799dcf7f53ed568717c247f975",
          "md5": "95e99cba251d5b01196ac7ddda09e998"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200208.000922-1.jar",
          "size": 2265655,
          "sha512": "369b9bf111784891fad37f4c48cb488c1f85ec151f88c8ae352a0366e59affcbea05f084602a7e1d5ec093110737b1ce326d1ab6709bf9c37360116801aa654c",
          "sha256": "2ffdbb0eebcb2ac3f7e87c075ca42f01c3dcab51df87227fd5855a69996a66b7",
          "sha1": "f687111b68685e799dcf7f53ed568717c247f975",
          "md5": "95e99cba251d5b01196ac7ddda09e998"
        }
      ]
    }
  ]
}
