{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "ryrj5ynzmvd4hnzdtpuifkq3hu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200131.203926-1.jar",
          "size": 2264669,
          "sha512": "94631dba9a74feca2e34e17ef4a8add8fa880d59e7a619715a5de89e124ebd462ce5b0a7871effba5962c24d0ae28f681bbba0f34cdcd894f23330be2bdea94a",
          "sha256": "415288607d4b9eaa0f96853d69690120d480548a9a1d6c5449f75dc76dd538d2",
          "sha1": "b80f4344c533b3fd645b558b38c37edc491c7d41",
          "md5": "10842955c4d8cbbcb115db0be3f29479"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200131.203926-1.jar",
          "size": 2264669,
          "sha512": "94631dba9a74feca2e34e17ef4a8add8fa880d59e7a619715a5de89e124ebd462ce5b0a7871effba5962c24d0ae28f681bbba0f34cdcd894f23330be2bdea94a",
          "sha256": "415288607d4b9eaa0f96853d69690120d480548a9a1d6c5449f75dc76dd538d2",
          "sha1": "b80f4344c533b3fd645b558b38c37edc491c7d41",
          "md5": "10842955c4d8cbbcb115db0be3f29479"
        }
      ]
    }
  ]
}
