{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "2rfhatrcbvgzjmlhghyvxvfy2a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200205.000903-1.jar",
          "size": 2265655,
          "sha512": "9f1cbac1f799fc004f2722bf9807774657579c7214bd1fee71a9308ed9deaa3764dc5666f7eda94ae57249f43bfa3eec0ddd22f9e5ac757c44fed373a4481717",
          "sha256": "0a992876b4a733f534474717a65d4e7ff183db9982c4ac45fce92ee61d41285b",
          "sha1": "47a4f7259f56baac909bbbc02c0d23021e46d83a",
          "md5": "c755eb7dc8dc3499eb30f5184079eb04"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200205.000903-1.jar",
          "size": 2265655,
          "sha512": "9f1cbac1f799fc004f2722bf9807774657579c7214bd1fee71a9308ed9deaa3764dc5666f7eda94ae57249f43bfa3eec0ddd22f9e5ac757c44fed373a4481717",
          "sha256": "0a992876b4a733f534474717a65d4e7ff183db9982c4ac45fce92ee61d41285b",
          "sha1": "47a4f7259f56baac909bbbc02c0d23021e46d83a",
          "md5": "c755eb7dc8dc3499eb30f5184079eb04"
        }
      ]
    }
  ]
}
