{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "hd2x4jqv4vcatk3rjnrmy3xgta"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200129.140204-1.jar",
          "size": 2264665,
          "sha512": "65e1f9de897b1859814a772ba6f5c47da643f556d490bd8ec6262905fd937f15a86c02848b7248efd8adb8f9543f5e61daf9bc1cb5c860e2c089d991db47e975",
          "sha256": "b6714b2429bc3edbbabdf735a2557299671a956aaecc906c403f95c3dee0ab1a",
          "sha1": "100c0f56702012ef7ddf3b6c58a63ffca4ef6bdf",
          "md5": "3c87a2a3b75f3934e0e7002f51b9edb8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200129.140204-1.jar",
          "size": 2264665,
          "sha512": "65e1f9de897b1859814a772ba6f5c47da643f556d490bd8ec6262905fd937f15a86c02848b7248efd8adb8f9543f5e61daf9bc1cb5c860e2c089d991db47e975",
          "sha256": "b6714b2429bc3edbbabdf735a2557299671a956aaecc906c403f95c3dee0ab1a",
          "sha1": "100c0f56702012ef7ddf3b6c58a63ffca4ef6bdf",
          "md5": "3c87a2a3b75f3934e0e7002f51b9edb8"
        }
      ]
    }
  ]
}
