{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "f4uoenkc5bdpvjswckxlmyq7le"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200201.000847-1.jar",
          "size": 2264669,
          "sha512": "d65ebaeb529b685f1950406cf77e1ac5139fffbcbda614ec73eb52ca1ce687349a545a5b22861ae08c5d8c8e06528b5ca8f7b80da9b3be16e8ecf05870a4a5e4",
          "sha256": "5618195dfdbfc3f4c868f4e78846e2985426ea8993a7bf47f855bd07714cbb1b",
          "sha1": "500a0b76d9570b1815fe0ddfac1dcee902af0d86",
          "md5": "d2a115de7f6008a38e5898d61ea10163"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200201.000847-1.jar",
          "size": 2264669,
          "sha512": "d65ebaeb529b685f1950406cf77e1ac5139fffbcbda614ec73eb52ca1ce687349a545a5b22861ae08c5d8c8e06528b5ca8f7b80da9b3be16e8ecf05870a4a5e4",
          "sha256": "5618195dfdbfc3f4c868f4e78846e2985426ea8993a7bf47f855bd07714cbb1b",
          "sha1": "500a0b76d9570b1815fe0ddfac1dcee902af0d86",
          "md5": "d2a115de7f6008a38e5898d61ea10163"
        }
      ]
    }
  ]
}
