{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "rflxfeooujgrngzzx5e4sekc2q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200130.000948-1.jar",
          "size": 2264666,
          "sha512": "12a3b59cdc8ba8d37ff8018a19a17765841cb5fd6241747b75f70fb71d6e4de1818d72e7222735ebad76d4a443b9476195392a0b06e2d35f2b5ec2300930b11b",
          "sha256": "92ff4e22df81ecad6daa97e7d069324f64dce7ff4f27002f6ae8e2543f9a4fba",
          "sha1": "ac25ceff35eb25438adca8b9990c6849beadefe0",
          "md5": "54c47d56d58c26af174b5ad946782e83"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200130.000948-1.jar",
          "size": 2264666,
          "sha512": "12a3b59cdc8ba8d37ff8018a19a17765841cb5fd6241747b75f70fb71d6e4de1818d72e7222735ebad76d4a443b9476195392a0b06e2d35f2b5ec2300930b11b",
          "sha256": "92ff4e22df81ecad6daa97e7d069324f64dce7ff4f27002f6ae8e2543f9a4fba",
          "sha1": "ac25ceff35eb25438adca8b9990c6849beadefe0",
          "md5": "54c47d56d58c26af174b5ad946782e83"
        }
      ]
    }
  ]
}
