{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "2fhdwpc6yvhqjmw3p4di3i632q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200210.001228-1.jar",
          "size": 2265695,
          "sha512": "8873b69efee4d34f1de2b98fe4deebcf780e226fc63fddb8c03fbf903a8345d0473c7afb5a47662274c71d194abea8e5fbe3d3f07b5322636291f1d81aa7123b",
          "sha256": "4e23f0f25c9b9cff2e0b5307e2a06f6330abcc5a7a87aeab0467b5b53ccbd498",
          "sha1": "482bce8b813edbdc7b55e73323db6133d0b2e01c",
          "md5": "aba95d57f1dfdd45caeacbfb198e6d36"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200210.001228-1.jar",
          "size": 2265695,
          "sha512": "8873b69efee4d34f1de2b98fe4deebcf780e226fc63fddb8c03fbf903a8345d0473c7afb5a47662274c71d194abea8e5fbe3d3f07b5322636291f1d81aa7123b",
          "sha256": "4e23f0f25c9b9cff2e0b5307e2a06f6330abcc5a7a87aeab0467b5b53ccbd498",
          "sha1": "482bce8b813edbdc7b55e73323db6133d0b2e01c",
          "md5": "aba95d57f1dfdd45caeacbfb198e6d36"
        }
      ]
    }
  ]
}
