{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "ac6pd77vwnduxh5v2pbsddkgfi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200213.001218-1.jar",
          "size": 2266794,
          "sha512": "a544a5596545f39391467629b1c136636ab619d815ed1b656e8373e529042491b0a72e457d7c2abfc4ad66611b45870a41765a2a2e244c7b0a003019ddcf73ff",
          "sha256": "71051a21c5e65430bad5c8061c6f20bcb5cccdd3cd13550c31ddee3465066ee4",
          "sha1": "7c39fb99eefdcb2c0025a63509ed1da24351f87a",
          "md5": "93a426e9827cda33f6836ca8f5fa68ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200213.001218-1.jar",
          "size": 2266794,
          "sha512": "a544a5596545f39391467629b1c136636ab619d815ed1b656e8373e529042491b0a72e457d7c2abfc4ad66611b45870a41765a2a2e244c7b0a003019ddcf73ff",
          "sha256": "71051a21c5e65430bad5c8061c6f20bcb5cccdd3cd13550c31ddee3465066ee4",
          "sha1": "7c39fb99eefdcb2c0025a63509ed1da24351f87a",
          "md5": "93a426e9827cda33f6836ca8f5fa68ae"
        }
      ]
    }
  ]
}
