{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "3h3babsauzdcnjcduoss5gpsie"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200212.001207-1.jar",
          "size": 2266789,
          "sha512": "853b8b3e53724fd8421757c556683f21fdc7676793c1952b42d5b920b5dc159953d1c01c66de026b109c2820230e3c2b5feb9898866c56bfb14e2d034b37d243",
          "sha256": "526a9f9912f367cef2896727de3bdd845b90467e688591653c47371db04f94b6",
          "sha1": "0b3ddaae83a9ea913a93d8b2177a0da446daf62e",
          "md5": "95813e00a163b5c970a5b5af481db670"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200212.001207-1.jar",
          "size": 2266789,
          "sha512": "853b8b3e53724fd8421757c556683f21fdc7676793c1952b42d5b920b5dc159953d1c01c66de026b109c2820230e3c2b5feb9898866c56bfb14e2d034b37d243",
          "sha256": "526a9f9912f367cef2896727de3bdd845b90467e688591653c47371db04f94b6",
          "sha1": "0b3ddaae83a9ea913a93d8b2177a0da446daf62e",
          "md5": "95813e00a163b5c970a5b5af481db670"
        }
      ]
    }
  ]
}
