{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "cxdydctyfrczzaqicpgqhx2bau"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200202.000831-1.jar",
          "size": 2264669,
          "sha512": "3de5b0fd1104b3960b28081b11a3c6cc7629b045ac65dc37137d48005e3bddf54b217660f80349275c281b2bbdbb9d88cd0d9e8293d72a95e5cf42eb88903748",
          "sha256": "52435ad87fd1cbafe83fecbb0daf46701e3550ea0ad3630ca40402b8a4a9ad21",
          "sha1": "ca0ce8b839962ec308fe182d1f6d4a65a2b6bfa9",
          "md5": "85eb83084ff688d2dc5c16d4610ba790"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200202.000831-1.jar",
          "size": 2264669,
          "sha512": "3de5b0fd1104b3960b28081b11a3c6cc7629b045ac65dc37137d48005e3bddf54b217660f80349275c281b2bbdbb9d88cd0d9e8293d72a95e5cf42eb88903748",
          "sha256": "52435ad87fd1cbafe83fecbb0daf46701e3550ea0ad3630ca40402b8a4a9ad21",
          "sha1": "ca0ce8b839962ec308fe182d1f6d4a65a2b6bfa9",
          "md5": "85eb83084ff688d2dc5c16d4610ba790"
        }
      ]
    }
  ]
}
