{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "nks3juklb5eunefxms6kyelpry"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200131.175257-1.jar",
          "size": 2264669,
          "sha512": "cf5ce5c5fffe2410c98cf40c949b214eddb6e65d01192c32171857a6311b8c0d031ffa03158febfbde40bb0c47f68563a98b7c8307e2336c410ec8919ad810b8",
          "sha256": "8c8511a925460f14649e3915e586cc49fcf27911d4e13054ef723bae37c2f347",
          "sha1": "5d1d012687310b889c14a147b4bf6fbc2066a7cc",
          "md5": "d27dc6260f7b1ca41a2b359625142b92"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200131.175257-1.jar",
          "size": 2264669,
          "sha512": "cf5ce5c5fffe2410c98cf40c949b214eddb6e65d01192c32171857a6311b8c0d031ffa03158febfbde40bb0c47f68563a98b7c8307e2336c410ec8919ad810b8",
          "sha256": "8c8511a925460f14649e3915e586cc49fcf27911d4e13054ef723bae37c2f347",
          "sha1": "5d1d012687310b889c14a147b4bf6fbc2066a7cc",
          "md5": "d27dc6260f7b1ca41a2b359625142b92"
        }
      ]
    }
  ]
}
