{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "42df6ild3ndbvawwmbvzhjzodi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200209.222509-1.jar",
          "size": 2265695,
          "sha512": "d2e6436df449ae374d95cf867f7a6b0a3290e25524cb23bd7b586f3af027358a6441d1fac248a06aec19e8a5f41beb070bc69064f0f57fc5e02c915d7fbd903f",
          "sha256": "27eaa192ce1b0b448813bccb79a8f6583f4870722d44c6ffeec6e11df9799f80",
          "sha1": "642b1204cfe2340fbcc56056c83ec1fce9cc6c78",
          "md5": "a6627289e6245fef92046bc7a4f7c5d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200209.222509-1.jar",
          "size": 2265695,
          "sha512": "d2e6436df449ae374d95cf867f7a6b0a3290e25524cb23bd7b586f3af027358a6441d1fac248a06aec19e8a5f41beb070bc69064f0f57fc5e02c915d7fbd903f",
          "sha256": "27eaa192ce1b0b448813bccb79a8f6583f4870722d44c6ffeec6e11df9799f80",
          "sha1": "642b1204cfe2340fbcc56056c83ec1fce9cc6c78",
          "md5": "a6627289e6245fef92046bc7a4f7c5d1"
        }
      ]
    }
  ]
}
