{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "x5na3rh3jvcb5g2x2nwm5bocru"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200214.001210-1.jar",
          "size": 2265863,
          "sha512": "b0cf7a8c6e3435fcbb2d7a3405761a3233cc4d7a4e324e2c636745d7fa49963b08ed9368fb2b47f1a1a9d92473bc8a97464991103147214c58e32f5707b37307",
          "sha256": "58896eddcf70c054aac4e851bf2b0e70b286427862eff2abe5586caaa137d27d",
          "sha1": "3aab308f2b5f42ffceef486bbc56034012eef2d9",
          "md5": "111e6430d29e47f7552b05d98aafe4b8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200214.001210-1.jar",
          "size": 2265863,
          "sha512": "b0cf7a8c6e3435fcbb2d7a3405761a3233cc4d7a4e324e2c636745d7fa49963b08ed9368fb2b47f1a1a9d92473bc8a97464991103147214c58e32f5707b37307",
          "sha256": "58896eddcf70c054aac4e851bf2b0e70b286427862eff2abe5586caaa137d27d",
          "sha1": "3aab308f2b5f42ffceef486bbc56034012eef2d9",
          "md5": "111e6430d29e47f7552b05d98aafe4b8"
        }
      ]
    }
  ]
}
