{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "heis4syj6vaddkvwvzyfe5bm44"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200209.202448-1.jar",
          "size": 2265695,
          "sha512": "8865c36d37cbe53bf9929b702078fb7b210606dde5d4167b2e6695a2bcbac392eb49c61df7e0e0a3fc932487484c3de538d79df2faaa6c53a9854f51a0cc611d",
          "sha256": "511aa39f6a8687d64d9dbd3a9172078f3d5c8f6685e8328974c8602c4abf691f",
          "sha1": "1acb44e839d7b13abef1ba91ab25cf934b51a19d",
          "md5": "3932ca89ea052d6adfc0a12efcb6fb42"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200209.202448-1.jar",
          "size": 2265695,
          "sha512": "8865c36d37cbe53bf9929b702078fb7b210606dde5d4167b2e6695a2bcbac392eb49c61df7e0e0a3fc932487484c3de538d79df2faaa6c53a9854f51a0cc611d",
          "sha256": "511aa39f6a8687d64d9dbd3a9172078f3d5c8f6685e8328974c8602c4abf691f",
          "sha1": "1acb44e839d7b13abef1ba91ab25cf934b51a19d",
          "md5": "3932ca89ea052d6adfc0a12efcb6fb42"
        }
      ]
    }
  ]
}
