{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "n5ytgqpd4vcmzlxxlmf3hpe33e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200206.153516-1.jar",
          "size": 2265655,
          "sha512": "feb14ac301b5a7523fb137da0a3bf8b5e7d992ca1436ca20e0c74fd209ccee076acc941e6e3bc2343197bd33d89ab94e980a852120df9eea81ded7d66488ce40",
          "sha256": "4a4fc6d27d235c8e31c1455b1625e84712ef9739686d23588c53b266a3a4fced",
          "sha1": "d834b7700d6dc08ab5c022d5dc8a5dac808317eb",
          "md5": "de938a2bee561f041732c089b5ec80d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200206.153516-1.jar",
          "size": 2265655,
          "sha512": "feb14ac301b5a7523fb137da0a3bf8b5e7d992ca1436ca20e0c74fd209ccee076acc941e6e3bc2343197bd33d89ab94e980a852120df9eea81ded7d66488ce40",
          "sha256": "4a4fc6d27d235c8e31c1455b1625e84712ef9739686d23588c53b266a3a4fced",
          "sha1": "d834b7700d6dc08ab5c022d5dc8a5dac808317eb",
          "md5": "de938a2bee561f041732c089b5ec80d7"
        }
      ]
    }
  ]
}
