{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "atn5szyjkbgknkfynn5acvixwy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200209.001152-1.jar",
          "size": 2265655,
          "sha512": "3eb48b081cc0fccfe84f3d533d6101168e1a73538129faac42a940217da6ea85c991449addf5df58c233278eb1f8da015f6ac55091a862c209759d80bc741575",
          "sha256": "80fe8b5ff3785a118bbee530941ec59129220370d115f0afc77e440008fc15fd",
          "sha1": "ea609a3dcc69d86c18c58afa17d9270a59e49923",
          "md5": "c4e1a401ab9079d4ac924f3e8efa881d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200209.001152-1.jar",
          "size": 2265655,
          "sha512": "3eb48b081cc0fccfe84f3d533d6101168e1a73538129faac42a940217da6ea85c991449addf5df58c233278eb1f8da015f6ac55091a862c209759d80bc741575",
          "sha256": "80fe8b5ff3785a118bbee530941ec59129220370d115f0afc77e440008fc15fd",
          "sha1": "ea609a3dcc69d86c18c58afa17d9270a59e49923",
          "md5": "c4e1a401ab9079d4ac924f3e8efa881d"
        }
      ]
    }
  ]
}
