{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "6garymirazahvbgjp3g6xxwspu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200207.000935-1.jar",
          "size": 2265655,
          "sha512": "14a293ebcb95814a8f2bbb010b7f85d1c9f0461b20b122e67d46a2e5b26c0bbba40b81ea44e4485c09fdedf05b5e959eaff3e06e00818082daab5ea52812859b",
          "sha256": "5c53acbb073ac5f28bbba3c323cb68be5ae1efca7bb94cbae7da33197d8142c5",
          "sha1": "36e25a5a9b0e0ec22238ded77ed4a42b2770eb36",
          "md5": "ed18f3bc3f3b81b13aa965ea9a69718f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.6-SNAPSHOT.jar",
          "url": "injected-client-1.6.6-20200207.000935-1.jar",
          "size": 2265655,
          "sha512": "14a293ebcb95814a8f2bbb010b7f85d1c9f0461b20b122e67d46a2e5b26c0bbba40b81ea44e4485c09fdedf05b5e959eaff3e06e00818082daab5ea52812859b",
          "sha256": "5c53acbb073ac5f28bbba3c323cb68be5ae1efca7bb94cbae7da33197d8142c5",
          "sha1": "36e25a5a9b0e0ec22238ded77ed4a42b2770eb36",
          "md5": "ed18f3bc3f3b81b13aa965ea9a69718f"
        }
      ]
    }
  ]
}
