{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "eongyiozrfavviwrnwrp3tln3a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.3-SNAPSHOT.jar",
          "url": "injected-client-1.6.3-20200119.000043-1.jar",
          "size": 2224272,
          "sha512": "496c85bded75759907d964bef74f1dc14c268a0c815a63de81aa690115f552351b30241e0c73a6ca0a5cd64d93d591cc687fb8af91131f3638d41df2902a9e04",
          "sha256": "c94f618267abe12ae105e442828afaa27f215c645d57ec6d0900c21e19db6842",
          "sha1": "18b1df040f7a44ec73e12c8edc3d64ca3108c860",
          "md5": "004d626b80b04029104de930bab79042"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.3-SNAPSHOT.jar",
          "url": "injected-client-1.6.3-20200119.000043-1.jar",
          "size": 2224272,
          "sha512": "496c85bded75759907d964bef74f1dc14c268a0c815a63de81aa690115f552351b30241e0c73a6ca0a5cd64d93d591cc687fb8af91131f3638d41df2902a9e04",
          "sha256": "c94f618267abe12ae105e442828afaa27f215c645d57ec6d0900c21e19db6842",
          "sha1": "18b1df040f7a44ec73e12c8edc3d64ca3108c860",
          "md5": "004d626b80b04029104de930bab79042"
        }
      ]
    }
  ]
}
