{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "6dutw6n66bfa5ixhpcwiotkkci"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.4.3.jar",
          "url": "runelite-api-3.4.3.jar",
          "size": 1231886,
          "sha512": "403624304c2ba9262f14d3b68131357129d62392fde791e590dee6f534c8ceff7f7e2f1cae2cbb040038925352e0ddd4265cb280022fc5366077aa985415d63e",
          "sha256": "a8afe6224b1614365bd30ce8c5fe885ae085e558d1d49dcb2221221d50577176",
          "sha1": "003f0b5b37caf0e64e5663edf21386fd6602926b",
          "md5": "8bac9d6e3241288cf70789d888b50dff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.4.3.jar",
          "url": "runelite-api-3.4.3.jar",
          "size": 1231886,
          "sha512": "403624304c2ba9262f14d3b68131357129d62392fde791e590dee6f534c8ceff7f7e2f1cae2cbb040038925352e0ddd4265cb280022fc5366077aa985415d63e",
          "sha256": "a8afe6224b1614365bd30ce8c5fe885ae085e558d1d49dcb2221221d50577176",
          "sha1": "003f0b5b37caf0e64e5663edf21386fd6602926b",
          "md5": "8bac9d6e3241288cf70789d888b50dff"
        }
      ]
    }
  ]
}
