{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "bmjwgkx5vfd2rjsdkpde7u4nve"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.6.jar",
          "url": "http-api-1.6.6.jar",
          "size": 165766,
          "sha512": "4b6893ba7581dabd692e9c4548a695f1fc31efc9646f168faad6853b245012b885d6a37b7b197935b62fb5939128a24aced3841888ea9152ff91e5c79f879b96",
          "sha256": "65f137d6ee2dcbff086f467e0d0eeaa4091941a8f56adffbbdb4268d6c7cf168",
          "sha1": "a8202295f4c802534f779686eced8474b745214e",
          "md5": "953f733ef1fdd19847a6c8a350db95b2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.6.jar",
          "url": "http-api-1.6.6.jar",
          "size": 165766,
          "sha512": "4b6893ba7581dabd692e9c4548a695f1fc31efc9646f168faad6853b245012b885d6a37b7b197935b62fb5939128a24aced3841888ea9152ff91e5c79f879b96",
          "sha256": "65f137d6ee2dcbff086f467e0d0eeaa4091941a8f56adffbbdb4268d6c7cf168",
          "sha1": "a8202295f4c802534f779686eced8474b745214e",
          "md5": "953f733ef1fdd19847a6c8a350db95b2"
        }
      ]
    }
  ]
}
