{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "sgsnhkex2nct5gfzg5oz63fg7u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.9.jar",
          "url": "http-api-1.6.9.jar",
          "size": 164353,
          "sha512": "9d46bebd31690fc1256e6949efec7f9f33b6d0bb610dba2b2a88a012768a3753742b667d31742d3b540b956ea478cee710a301c37958bb4092efa4d704a93a5d",
          "sha256": "fad54bf8cb55e9a91885d17c16081e8fe41139a6c30cf8ee86a6f2f1fccbf644",
          "sha1": "bc1c143c9d158e47663a5b22510a719eb2818b67",
          "md5": "d9a3dbd0fb71cf443244e30db2796398"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.9"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.9.jar",
          "url": "http-api-1.6.9.jar",
          "size": 164353,
          "sha512": "9d46bebd31690fc1256e6949efec7f9f33b6d0bb610dba2b2a88a012768a3753742b667d31742d3b540b956ea478cee710a301c37958bb4092efa4d704a93a5d",
          "sha256": "fad54bf8cb55e9a91885d17c16081e8fe41139a6c30cf8ee86a6f2f1fccbf644",
          "sha1": "bc1c143c9d158e47663a5b22510a719eb2818b67",
          "md5": "d9a3dbd0fb71cf443244e30db2796398"
        }
      ]
    }
  ]
}
