{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "2c3ukkycprglrc6ddokf4panqa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.9.jar",
          "url": "http-api-1.6.9.jar",
          "size": 164353,
          "sha512": "c52aca2579ded7207020476662b8e61dce9b784ede6243593f5e388bd3bbded1aa4b87a40ea7eaeb8a38d495d27f8ac4f01e9db917f62e3518d806c647dd7125",
          "sha256": "83a9afbaf995e8f1cd70da2a643cbc75b2dc2d48d89de3cddb1900ec26b7d8c5",
          "sha1": "0fef3bcbab413e52c48889cd7a65ad461ad9458f",
          "md5": "f8105c9f1dc8ce134f1b3af064abd150"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.9"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.9.jar",
          "url": "http-api-1.6.9.jar",
          "size": 164353,
          "sha512": "c52aca2579ded7207020476662b8e61dce9b784ede6243593f5e388bd3bbded1aa4b87a40ea7eaeb8a38d495d27f8ac4f01e9db917f62e3518d806c647dd7125",
          "sha256": "83a9afbaf995e8f1cd70da2a643cbc75b2dc2d48d89de3cddb1900ec26b7d8c5",
          "sha1": "0fef3bcbab413e52c48889cd7a65ad461ad9458f",
          "md5": "f8105c9f1dc8ce134f1b3af064abd150"
        }
      ]
    }
  ]
}
