{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "ikgdvzzfu5awlmc37vrcb7rkde"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.9.jar",
          "url": "http-api-1.6.9.jar",
          "size": 164354,
          "sha512": "8d19828b6066f3fd876d40de19580b7e0403d39decb7160ea45b4516be17f9d666f7838533f4aadd571179377073207d0046509d5f0315394563fe9fb1a71194",
          "sha256": "f85fd941440e275f8cc5a34754b1cc4a0195b9ee628d44e7e46bbd12e906161b",
          "sha1": "d62e2a515d073b5ae0ac2a2dd1dac48df9466925",
          "md5": "dd76d19d150f9a4f36f409c49a236781"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.9"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.9.jar",
          "url": "http-api-1.6.9.jar",
          "size": 164354,
          "sha512": "8d19828b6066f3fd876d40de19580b7e0403d39decb7160ea45b4516be17f9d666f7838533f4aadd571179377073207d0046509d5f0315394563fe9fb1a71194",
          "sha256": "f85fd941440e275f8cc5a34754b1cc4a0195b9ee628d44e7e46bbd12e906161b",
          "sha1": "d62e2a515d073b5ae0ac2a2dd1dac48df9466925",
          "md5": "dd76d19d150f9a4f36f409c49a236781"
        }
      ]
    }
  ]
}
