{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "txcgaj4s3vaq3culwrlvhwkotm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.4.4.jar",
          "url": "http-api-3.4.4.jar",
          "size": 160251,
          "sha512": "ee8af20030b29a5fff9fb75461e0e09675e26ecba2d1af1f3e57a121e80bef888c5404bfac36fe2a97cfd4c48d45bc118c869df17c6b44877a44775c7dee7b3f",
          "sha256": "a652c75048637cf393bebaf042e33330a55b32bcea700574a32b92f595a44a72",
          "sha1": "e77c07bfc73babcf3469a06aa1ba8d197e7db396",
          "md5": "1f3b966ea9ae6ffbc3dcf91fb21df786"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.4.4.jar",
          "url": "http-api-3.4.4.jar",
          "size": 160251,
          "sha512": "ee8af20030b29a5fff9fb75461e0e09675e26ecba2d1af1f3e57a121e80bef888c5404bfac36fe2a97cfd4c48d45bc118c869df17c6b44877a44775c7dee7b3f",
          "sha256": "a652c75048637cf393bebaf042e33330a55b32bcea700574a32b92f595a44a72",
          "sha1": "e77c07bfc73babcf3469a06aa1ba8d197e7db396",
          "md5": "1f3b966ea9ae6ffbc3dcf91fb21df786"
        }
      ]
    }
  ]
}
