{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "pri662m42zb7vdjvwk5xly7g5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.7.jar",
          "url": "injected-client-3.3.7.jar",
          "size": 2253215,
          "sha512": "63be4dcc1077958042571d1f0a73cdd06ab20fa802f1049168b4b55ac7dcfcdd8148b127503afb8d63f62f49b3b36c2b944c00b62be8f00614152c6e5f58ac1f",
          "sha256": "2d5794d73857c53094d7f8472d566ad7a0ea9b51e0adc13400bfd4db1adb9b72",
          "sha1": "f2e0ebe097ab0eee95d444a0ee0624683f0bf93c",
          "md5": "80039ce13b0fbef962ad7e27c3649e00"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.7.jar",
          "url": "injected-client-3.3.7.jar",
          "size": 2253215,
          "sha512": "63be4dcc1077958042571d1f0a73cdd06ab20fa802f1049168b4b55ac7dcfcdd8148b127503afb8d63f62f49b3b36c2b944c00b62be8f00614152c6e5f58ac1f",
          "sha256": "2d5794d73857c53094d7f8472d566ad7a0ea9b51e0adc13400bfd4db1adb9b72",
          "sha1": "f2e0ebe097ab0eee95d444a0ee0624683f0bf93c",
          "md5": "80039ce13b0fbef962ad7e27c3649e00"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.7-sources.jar",
          "url": "injected-client-3.3.7-sources.jar",
          "size": 261,
          "sha512": "aaed125f9e4f146f9cc86439bde8acc3345fe5b9e52a0490f586d0578ceb30fcc291c0cb13bfb919d503f81d207964db151e0593cba1731f1417cc8c383e643a",
          "sha256": "2e819ec2f1af74689c061f2ed63527f102bbaf764b9a5b518de63dc3ce795b36",
          "sha1": "c1b259ab08dd79c7340e83cbc368fc5bc63b373a",
          "md5": "d9427990cbbaba9cd12d01d43e88d8f8"
        },
        {
          "name": "injected-client-3.3.7.jar",
          "url": "injected-client-3.3.7.jar",
          "size": 2253215,
          "sha512": "63be4dcc1077958042571d1f0a73cdd06ab20fa802f1049168b4b55ac7dcfcdd8148b127503afb8d63f62f49b3b36c2b944c00b62be8f00614152c6e5f58ac1f",
          "sha256": "2d5794d73857c53094d7f8472d566ad7a0ea9b51e0adc13400bfd4db1adb9b72",
          "sha1": "f2e0ebe097ab0eee95d444a0ee0624683f0bf93c",
          "md5": "80039ce13b0fbef962ad7e27c3649e00"
        }
      ]
    }
  ]
}
