{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "azdorqxvd5gqlic5iruzqx6z3i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.7.jar",
          "url": "injected-client-3.3.7.jar",
          "size": 2253215,
          "sha512": "6a7889b00171eef1c2680c51772ad8312adff66812aa0946eab3c973286a0f66a186335d6446536cd85a72a1777421beed4df3f404be3703f5c9b4160274f93a",
          "sha256": "7d25340e378cf3d96cde3ff9be0e5aeb715a9336c6106cae29204bf8465d7f67",
          "sha1": "0fac22f77a5aab313c62fc188f607a9a9919dfa7",
          "md5": "ab28f1b7ac6871e635b9d70d90c39393"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.7.jar",
          "url": "injected-client-3.3.7.jar",
          "size": 2253215,
          "sha512": "6a7889b00171eef1c2680c51772ad8312adff66812aa0946eab3c973286a0f66a186335d6446536cd85a72a1777421beed4df3f404be3703f5c9b4160274f93a",
          "sha256": "7d25340e378cf3d96cde3ff9be0e5aeb715a9336c6106cae29204bf8465d7f67",
          "sha1": "0fac22f77a5aab313c62fc188f607a9a9919dfa7",
          "md5": "ab28f1b7ac6871e635b9d70d90c39393"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.7-sources.jar",
          "url": "injected-client-3.3.7-sources.jar",
          "size": 261,
          "sha512": "6e6268a96bd0229b699e2415c685440225c96d048ff6b4921beb50ac8c29bee84e63f74c3777783fb185c11fcafefbbc20d97353593b695042281385549a0e3c",
          "sha256": "66357e9871bab199d071fb6a8e4a99ffa2f112cde707a1a0c6f5e3ca795e211e",
          "sha1": "12e5f706f1d3add569cfe79c49f0877c260c4252",
          "md5": "b48419aa203db79721b5d4459e3f3542"
        },
        {
          "name": "injected-client-3.3.7.jar",
          "url": "injected-client-3.3.7.jar",
          "size": 2253215,
          "sha512": "6a7889b00171eef1c2680c51772ad8312adff66812aa0946eab3c973286a0f66a186335d6446536cd85a72a1777421beed4df3f404be3703f5c9b4160274f93a",
          "sha256": "7d25340e378cf3d96cde3ff9be0e5aeb715a9336c6106cae29204bf8465d7f67",
          "sha1": "0fac22f77a5aab313c62fc188f607a9a9919dfa7",
          "md5": "ab28f1b7ac6871e635b9d70d90c39393"
        }
      ]
    }
  ]
}
