{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "lbk2szqrgbh5xm42c6tnlvu5kq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.4.jar",
          "url": "injected-client-3.3.4.jar",
          "size": 2252824,
          "sha512": "6c62a0a2d98a50b3640e58efdfd5d8d7d0ccc20e3b260888a388d04449433a5e7db6f0104af01dd992d2245929e4a02306a7bcfa48a063bf10dae6d4d8a5d503",
          "sha256": "ec583f445bc1a05eb535bdc6b916e0107cd60f2b71cdc9e54aa78161b161084f",
          "sha1": "ca079ed18a2fce2f2672df062a3ea70229525946",
          "md5": "0589227a3d19ac78ba5a6e21a95e8332"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.4.jar",
          "url": "injected-client-3.3.4.jar",
          "size": 2252824,
          "sha512": "6c62a0a2d98a50b3640e58efdfd5d8d7d0ccc20e3b260888a388d04449433a5e7db6f0104af01dd992d2245929e4a02306a7bcfa48a063bf10dae6d4d8a5d503",
          "sha256": "ec583f445bc1a05eb535bdc6b916e0107cd60f2b71cdc9e54aa78161b161084f",
          "sha1": "ca079ed18a2fce2f2672df062a3ea70229525946",
          "md5": "0589227a3d19ac78ba5a6e21a95e8332"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.4-sources.jar",
          "url": "injected-client-3.3.4-sources.jar",
          "size": 261,
          "sha512": "14be623b7dbe468664afc6460a9eff064c3001ae50973b3f363524892e8b6babceaf0f652f466eb99a2f0c67d9b3e2befa6a42edc2d58f512eab22e26bf92689",
          "sha256": "2a09ddacf84db272ff2ff48d41ee96ee8afa32af1019beb0b92a6ef7d5a71083",
          "sha1": "91d81d06c5952c373880c087e8faaa84f8ac8ea5",
          "md5": "82ac2598318dd93ac8c9959f200ef198"
        },
        {
          "name": "injected-client-3.3.4.jar",
          "url": "injected-client-3.3.4.jar",
          "size": 2252824,
          "sha512": "6c62a0a2d98a50b3640e58efdfd5d8d7d0ccc20e3b260888a388d04449433a5e7db6f0104af01dd992d2245929e4a02306a7bcfa48a063bf10dae6d4d8a5d503",
          "sha256": "ec583f445bc1a05eb535bdc6b916e0107cd60f2b71cdc9e54aa78161b161084f",
          "sha1": "ca079ed18a2fce2f2672df062a3ea70229525946",
          "md5": "0589227a3d19ac78ba5a6e21a95e8332"
        }
      ]
    }
  ]
}
