{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "ag7kba57wnhh3fmqilynicfq5m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.4.jar",
          "url": "injected-client-3.3.4.jar",
          "size": 2252824,
          "sha512": "b44ad88d4d03a04a48db228aa1f9b626a141563ad23206fd4e3649dee3d494cf9eeada0f544238e96148e9b57e5dd2aba11e4ebc5e7f3be0f23db76ca9f95277",
          "sha256": "5d91bcb6474827d4f403e5a21fa0b14dde2c34285121aaf7196cc33261e1670c",
          "sha1": "88c20bfdb1336c4805d8213da8bafb3fd147182f",
          "md5": "26cfd931aebb3b442dd545c3f5ca0f01"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.4.jar",
          "url": "injected-client-3.3.4.jar",
          "size": 2252824,
          "sha512": "b44ad88d4d03a04a48db228aa1f9b626a141563ad23206fd4e3649dee3d494cf9eeada0f544238e96148e9b57e5dd2aba11e4ebc5e7f3be0f23db76ca9f95277",
          "sha256": "5d91bcb6474827d4f403e5a21fa0b14dde2c34285121aaf7196cc33261e1670c",
          "sha1": "88c20bfdb1336c4805d8213da8bafb3fd147182f",
          "md5": "26cfd931aebb3b442dd545c3f5ca0f01"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.4-sources.jar",
          "url": "injected-client-3.3.4-sources.jar",
          "size": 261,
          "sha512": "346b080b2e60c8ee3bd730984f9c34c17f6959759d5ce41dc669db638cf28e12509118ecfb08d16d2ba3d169e77d9d5778f55664402b750efa70fd65fc6213b2",
          "sha256": "0a2b76c44a425bd3f6cc45a95af9360fb9e95685a46c3558b94b631eb88d6c0d",
          "sha1": "75f39f29e5a531936eaf5f0574b009a447018579",
          "md5": "7b523777fb9058167496e811f5176c5d"
        },
        {
          "name": "injected-client-3.3.4.jar",
          "url": "injected-client-3.3.4.jar",
          "size": 2252824,
          "sha512": "b44ad88d4d03a04a48db228aa1f9b626a141563ad23206fd4e3649dee3d494cf9eeada0f544238e96148e9b57e5dd2aba11e4ebc5e7f3be0f23db76ca9f95277",
          "sha256": "5d91bcb6474827d4f403e5a21fa0b14dde2c34285121aaf7196cc33261e1670c",
          "sha1": "88c20bfdb1336c4805d8213da8bafb3fd147182f",
          "md5": "26cfd931aebb3b442dd545c3f5ca0f01"
        }
      ]
    }
  ]
}
