{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "irwk6tfda5ggthdjh4gmblg62q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.4.jar",
          "url": "injected-client-3.3.4.jar",
          "size": 2252824,
          "sha512": "db144cf40b2a39ec2c75dc04c8b2a752b868e719059367965d3780e97d32a71badd4f86c7542cde87b17ee375c95f9bc266dedb70fce612235684d15f0a9f2d0",
          "sha256": "1dee6d2f17036ed59b7c0ca429fbba11b80af090985240ec5b8b9e591ec712b7",
          "sha1": "3ad5b5a864addb41061b152650d79cb60c4ab193",
          "md5": "176dee7de7670882e25e796c8c8ea5e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.4.jar",
          "url": "injected-client-3.3.4.jar",
          "size": 2252824,
          "sha512": "db144cf40b2a39ec2c75dc04c8b2a752b868e719059367965d3780e97d32a71badd4f86c7542cde87b17ee375c95f9bc266dedb70fce612235684d15f0a9f2d0",
          "sha256": "1dee6d2f17036ed59b7c0ca429fbba11b80af090985240ec5b8b9e591ec712b7",
          "sha1": "3ad5b5a864addb41061b152650d79cb60c4ab193",
          "md5": "176dee7de7670882e25e796c8c8ea5e9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.4-sources.jar",
          "url": "injected-client-3.3.4-sources.jar",
          "size": 261,
          "sha512": "c56a4adfc8277a6485f98e2b5b1ce05ed68c7f51f594315ee5dc36ab94a2292e376c01030f7b835b45096bd3b7b5f92ee5d8ae1b94e8b578e9017fa6fc693eda",
          "sha256": "9a3632319b0d09ee962d4e60e5d637639875d79589a82cb76075a10d8e78aa7e",
          "sha1": "4ffa8c72c0bb806e661ddff5afa05452b499ab62",
          "md5": "c4fda31046e40cd5f90701fd600e0e1f"
        },
        {
          "name": "injected-client-3.3.4.jar",
          "url": "injected-client-3.3.4.jar",
          "size": 2252824,
          "sha512": "db144cf40b2a39ec2c75dc04c8b2a752b868e719059367965d3780e97d32a71badd4f86c7542cde87b17ee375c95f9bc266dedb70fce612235684d15f0a9f2d0",
          "sha256": "1dee6d2f17036ed59b7c0ca429fbba11b80af090985240ec5b8b9e591ec712b7",
          "sha1": "3ad5b5a864addb41061b152650d79cb60c4ab193",
          "md5": "176dee7de7670882e25e796c8c8ea5e9"
        }
      ]
    }
  ]
}
