{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "zzyga5hsi5gp5ontg42542od5q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.5.1.jar",
          "url": "http-api-3.5.1.jar",
          "size": 160353,
          "sha512": "423af89005907a37acc3611f33db68f41ac2a622ae142754ad1298e7ed7b05a78425d8b5c1033ee3c6bdf87fcc32072f4cf783c1fa2a8a6869d91bfdbf6c2229",
          "sha256": "3eb934002b32b5ed8e55438ad87056a973d81036a42446b174819931ec32a7fd",
          "sha1": "4241a06d8f0280f677c33d919a0a7ad9003d4c2a",
          "md5": "9f1dcf51161e987f383fbbc56745b186"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.5.1.jar",
          "url": "http-api-3.5.1.jar",
          "size": 160353,
          "sha512": "423af89005907a37acc3611f33db68f41ac2a622ae142754ad1298e7ed7b05a78425d8b5c1033ee3c6bdf87fcc32072f4cf783c1fa2a8a6869d91bfdbf6c2229",
          "sha256": "3eb934002b32b5ed8e55438ad87056a973d81036a42446b174819931ec32a7fd",
          "sha1": "4241a06d8f0280f677c33d919a0a7ad9003d4c2a",
          "md5": "9f1dcf51161e987f383fbbc56745b186"
        }
      ]
    }
  ]
}
