{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "2ouu4rxnazbz5px7qn2hsvdtga"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.4.0.jar",
          "url": "runelite-api-3.4.0.jar",
          "size": 1220447,
          "sha512": "b219d453e127be39adcd541a60a6fce0bdf6b986f077221a594b78c76891429a6e1e0523c85a12ba3d0fc0b8c1841471d509b7782bdf268917c3e2045bc8b3ba",
          "sha256": "d3c8253c2b95ece9d2a0771aa34e11f1888c273b346289637eb6cd05999a2c74",
          "sha1": "68e918dd3a02372c08738e8fa2bf3aaeea6e3f99",
          "md5": "7ee54346e06a8861637b44f668a52c38"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.4.0.jar",
          "url": "runelite-api-3.4.0.jar",
          "size": 1220447,
          "sha512": "b219d453e127be39adcd541a60a6fce0bdf6b986f077221a594b78c76891429a6e1e0523c85a12ba3d0fc0b8c1841471d509b7782bdf268917c3e2045bc8b3ba",
          "sha256": "d3c8253c2b95ece9d2a0771aa34e11f1888c273b346289637eb6cd05999a2c74",
          "sha1": "68e918dd3a02372c08738e8fa2bf3aaeea6e3f99",
          "md5": "7ee54346e06a8861637b44f668a52c38"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.4.0-sources.jar",
          "url": "runelite-api-3.4.0-sources.jar",
          "size": 895340,
          "sha512": "ba8309659d3158869ee0965e1aa5db3cf97715c973eed8fe61b5874bf5c09177d9cfbf04580d6693b9bbbddc33bd5716d8722fd0bd263ad704d3686abfd741f6",
          "sha256": "4e7c110090070b6fc0dd16102654e2784d6714bf7928c3284b7b156328a92844",
          "sha1": "e9c7f70f7f3e5b673b914ef5e7a2925da29113cd",
          "md5": "397933c121497a073a65d2928df14049"
        }
      ]
    }
  ]
}
