{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "j6pxo2ojijhmvf3hnwfgfa47oa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6-SNAPSHOT.jar",
          "url": "runescape-api-1.6.6-20200211.230220-1.jar",
          "size": 55272,
          "sha512": "611e4204ca3f03e427b1d6c6be835f0fefda4eb7fab1f362b49caf51cb0a6e8b7b3016e863136400d3892c6856692931f52f2682381160ed65e8315b42a4be28",
          "sha256": "7204ac85ea7e4882576d0391c6e7cdcd5f218cee8d952e9eb865c4930bc900ed",
          "sha1": "482f6db74e0c3cd1f7bb994c9099988dbecf3c66",
          "md5": "91457d2895c44ae2007bbf06e3093773"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6-SNAPSHOT.jar",
          "url": "runescape-api-1.6.6-20200211.230220-1.jar",
          "size": 55272,
          "sha512": "611e4204ca3f03e427b1d6c6be835f0fefda4eb7fab1f362b49caf51cb0a6e8b7b3016e863136400d3892c6856692931f52f2682381160ed65e8315b42a4be28",
          "sha256": "7204ac85ea7e4882576d0391c6e7cdcd5f218cee8d952e9eb865c4930bc900ed",
          "sha1": "482f6db74e0c3cd1f7bb994c9099988dbecf3c66",
          "md5": "91457d2895c44ae2007bbf06e3093773"
        }
      ]
    }
  ]
}
