{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "bwmewskbhjgmvi3c4nnhj5tox4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6-SNAPSHOT.jar",
          "url": "runescape-api-1.6.6-20200129.203857-1.jar",
          "size": 55272,
          "sha512": "f43bdf5a08ffb1fe6586de775a274e82daf15038aa84cb847bdf852e3d8327d56a608c0c5751957921e4b0687dd6dd9608606205abee9a260b61afdbe90b6c2c",
          "sha256": "7165f54154d75dde87d160d745c00b407059901c5600039f0fe99d1d37b5aec0",
          "sha1": "31bf381dd6cdd9d976c0050637eaee4e3d53cc6a",
          "md5": "cd999eab3a34d17e10f720b142c9519e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6-SNAPSHOT.jar",
          "url": "runescape-api-1.6.6-20200129.203857-1.jar",
          "size": 55272,
          "sha512": "f43bdf5a08ffb1fe6586de775a274e82daf15038aa84cb847bdf852e3d8327d56a608c0c5751957921e4b0687dd6dd9608606205abee9a260b61afdbe90b6c2c",
          "sha256": "7165f54154d75dde87d160d745c00b407059901c5600039f0fe99d1d37b5aec0",
          "sha1": "31bf381dd6cdd9d976c0050637eaee4e3d53cc6a",
          "md5": "cd999eab3a34d17e10f720b142c9519e"
        }
      ]
    }
  ]
}
