{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "rtcykgnj6zeuledgys4z7sqyzu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6-SNAPSHOT.jar",
          "url": "runescape-api-1.6.6-20200129.160358-1.jar",
          "size": 55272,
          "sha512": "b87fa50186b24d33c1fdac685c40b7dbaa0c026e57d1b40a86b24120f66bc6700c4d5023950ea6fd342b5d885664c437dd68f3495bc3f88c5d4767075febbb93",
          "sha256": "85f54af4cf1bbb754021a72348e3927b07af80bad4bd14d2f1211f4f61fa6128",
          "sha1": "87dba350e6c46d152690fff9bc99c78d20ba58f4",
          "md5": "ae5ce09eb8642871e104ee56a7bc970b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6-SNAPSHOT.jar",
          "url": "runescape-api-1.6.6-20200129.160358-1.jar",
          "size": 55272,
          "sha512": "b87fa50186b24d33c1fdac685c40b7dbaa0c026e57d1b40a86b24120f66bc6700c4d5023950ea6fd342b5d885664c437dd68f3495bc3f88c5d4767075febbb93",
          "sha256": "85f54af4cf1bbb754021a72348e3927b07af80bad4bd14d2f1211f4f61fa6128",
          "sha1": "87dba350e6c46d152690fff9bc99c78d20ba58f4",
          "md5": "ae5ce09eb8642871e104ee56a7bc970b"
        }
      ]
    }
  ]
}
