{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "zob7h3yxe5hupnktgt4o4os32e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6-SNAPSHOT.jar",
          "url": "runescape-api-1.6.6-20200130.102034-2.jar",
          "size": 55272,
          "sha512": "724907956d06efe752e787f99d6cebb9405210634f9d44cc9541a9488c70e6ba4b6dab48b38dd45d77fee4ee3f4f9a1de95d4812c481a594d2fb9589077d5f0a",
          "sha256": "f778a13c190e3c9d71f977f9f8e2db19050a4bf33063a3a9423aa036c77d4917",
          "sha1": "b70f7df76c8b781978e8e823f70e9aef170eda3c",
          "md5": "5743e38c98314de6702b21041253d3dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.6-SNAPSHOT.jar",
          "url": "runescape-api-1.6.6-20200130.102034-2.jar",
          "size": 55272,
          "sha512": "724907956d06efe752e787f99d6cebb9405210634f9d44cc9541a9488c70e6ba4b6dab48b38dd45d77fee4ee3f4f9a1de95d4812c481a594d2fb9589077d5f0a",
          "sha256": "f778a13c190e3c9d71f977f9f8e2db19050a4bf33063a3a9423aa036c77d4917",
          "sha1": "b70f7df76c8b781978e8e823f70e9aef170eda3c",
          "md5": "5743e38c98314de6702b21041253d3dd"
        }
      ]
    }
  ]
}
