{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "2rfhatrcbvgzjmlhghyvxvfy2a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.6-SNAPSHOT.jar",
          "url": "http-api-1.6.6-20200205.000903-1.jar",
          "size": 165434,
          "sha512": "324e751b94bd8ee208a754f13e21bb7852671e8701d89f0b69fbbffb2825ac2f17663504f14d25900c2e33a377ba47ccf255c5d49850cad57a16a32e8732fb96",
          "sha256": "1423eb76b6d56a85a6d395946f49ac3948bbd5b1c919b8cada8616295f3356a2",
          "sha1": "3736fbc8d03b46ceb81f7b9b5de2f7e7a461f292",
          "md5": "f242a6f383950e7c2daa23ea653426dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.6-SNAPSHOT.jar",
          "url": "http-api-1.6.6-20200205.000903-1.jar",
          "size": 165434,
          "sha512": "324e751b94bd8ee208a754f13e21bb7852671e8701d89f0b69fbbffb2825ac2f17663504f14d25900c2e33a377ba47ccf255c5d49850cad57a16a32e8732fb96",
          "sha256": "1423eb76b6d56a85a6d395946f49ac3948bbd5b1c919b8cada8616295f3356a2",
          "sha1": "3736fbc8d03b46ceb81f7b9b5de2f7e7a461f292",
          "md5": "f242a6f383950e7c2daa23ea653426dd"
        }
      ]
    }
  ]
}
