{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "f4uoenkc5bdpvjswckxlmyq7le"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.6-SNAPSHOT.jar",
          "url": "http-api-1.6.6-20200201.000847-1.jar",
          "size": 165434,
          "sha512": "85b0a1bdc9c1a89ea3f30e7c4602ef05c74fec9d3510d5006694a12feb4abee5ce4e3150c2db7072d655307551aa40e006c79eb0877375e6680697a1773e52de",
          "sha256": "7fecdf7c5558ad2ef3b9b6bdee247906405b3850c5621d0ff88ff3312e53ad53",
          "sha1": "c11959188686e2197544e60586f315deb7be9bab",
          "md5": "d694b8fe36cad27802c23b795b2e19ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.6-SNAPSHOT.jar",
          "url": "http-api-1.6.6-20200201.000847-1.jar",
          "size": 165434,
          "sha512": "85b0a1bdc9c1a89ea3f30e7c4602ef05c74fec9d3510d5006694a12feb4abee5ce4e3150c2db7072d655307551aa40e006c79eb0877375e6680697a1773e52de",
          "sha256": "7fecdf7c5558ad2ef3b9b6bdee247906405b3850c5621d0ff88ff3312e53ad53",
          "sha1": "c11959188686e2197544e60586f315deb7be9bab",
          "md5": "d694b8fe36cad27802c23b795b2e19ca"
        }
      ]
    }
  ]
}
