{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "7rrh2oeceremxmn6hdow7wjqwi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.6-SNAPSHOT.jar",
          "url": "http-api-1.6.6-20200131.000935-1.jar",
          "size": 165434,
          "sha512": "91c5d64f466f3600bbc447f68efbdb535ff5d25ad067af6cc8ba654cc5fbee3eeb27a6b8ec3867b1190279e721f8fb0ed75449931a6d77d5076f650de1f3a9b4",
          "sha256": "a64048a57f573fa5926e49e041e1c9865572034f225a80d61f8a1866025ac264",
          "sha1": "bfb39132069f99885ce73ccc24dec4c41a3aa75a",
          "md5": "ec13235bff349c272aea4e3de9f481b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.6-SNAPSHOT.jar",
          "url": "http-api-1.6.6-20200131.000935-1.jar",
          "size": 165434,
          "sha512": "91c5d64f466f3600bbc447f68efbdb535ff5d25ad067af6cc8ba654cc5fbee3eeb27a6b8ec3867b1190279e721f8fb0ed75449931a6d77d5076f650de1f3a9b4",
          "sha256": "a64048a57f573fa5926e49e041e1c9865572034f225a80d61f8a1866025ac264",
          "sha1": "bfb39132069f99885ce73ccc24dec4c41a3aa75a",
          "md5": "ec13235bff349c272aea4e3de9f481b4"
        }
      ]
    }
  ]
}
