{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "nks3juklb5eunefxms6kyelpry"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.6-SNAPSHOT.jar",
          "url": "http-api-1.6.6-20200131.175257-1.jar",
          "size": 165434,
          "sha512": "ed77a341b704a6b429e287daed7f097d5f939a52768bbc3bb0ae4cfb5f87928e9901d964e93e8588559c61478d3e664656dcdfd864cc8d9119f6ccfc8d4287a7",
          "sha256": "2b4d8aba9af0d97ddd8a6c0bb5c648991b2cd05cefab0549b9bef529a6a39775",
          "sha1": "bd57880a0d67c9e2cc33596a335de7b12a0da8de",
          "md5": "56a08a916cb1d919466bd669d56d453c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.6-SNAPSHOT.jar",
          "url": "http-api-1.6.6-20200131.175257-1.jar",
          "size": 165434,
          "sha512": "ed77a341b704a6b429e287daed7f097d5f939a52768bbc3bb0ae4cfb5f87928e9901d964e93e8588559c61478d3e664656dcdfd864cc8d9119f6ccfc8d4287a7",
          "sha256": "2b4d8aba9af0d97ddd8a6c0bb5c648991b2cd05cefab0549b9bef529a6a39775",
          "sha1": "bd57880a0d67c9e2cc33596a335de7b12a0da8de",
          "md5": "56a08a916cb1d919466bd669d56d453c"
        }
      ]
    }
  ]
}
