{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "n5ytgqpd4vcmzlxxlmf3hpe33e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.6-SNAPSHOT.jar",
          "url": "http-api-1.6.6-20200206.153516-1.jar",
          "size": 165511,
          "sha512": "796355ef4e29c0e3968c8741c951724ac8dbb3918fb4ce70a7348deaaf37a6d2ab3d1b21a43148c1ef4cca24fca7b9c68b14d08c6debe63c497cdbd0fed048cf",
          "sha256": "ff1330ea746574effbe8f8d313efb73ddb9f4f2b5bce4595b75682558c3f5f55",
          "sha1": "f5ed61fef99f97f7a5a74818987670300041e356",
          "md5": "0d9f945616796dc11ab0f61329a15e37"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.6-SNAPSHOT.jar",
          "url": "http-api-1.6.6-20200206.153516-1.jar",
          "size": 165511,
          "sha512": "796355ef4e29c0e3968c8741c951724ac8dbb3918fb4ce70a7348deaaf37a6d2ab3d1b21a43148c1ef4cca24fca7b9c68b14d08c6debe63c497cdbd0fed048cf",
          "sha256": "ff1330ea746574effbe8f8d313efb73ddb9f4f2b5bce4595b75682558c3f5f55",
          "sha1": "f5ed61fef99f97f7a5a74818987670300041e356",
          "md5": "0d9f945616796dc11ab0f61329a15e37"
        }
      ]
    }
  ]
}
