{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "atn5szyjkbgknkfynn5acvixwy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.6-SNAPSHOT.jar",
          "url": "http-api-1.6.6-20200209.001152-1.jar",
          "size": 165513,
          "sha512": "8757ccfd754d00101abca3f32c3ae30a4b415f500da4ff2ecfcb64e80525cab1a7e28a9589ed12423cfdd5f9dbae0b4e9d295ba4b820a8796385d1060e8c4cc1",
          "sha256": "1435e4773bde46deabcc41624d4ebc26e8d115b772ae98dde66aae4a00733fdd",
          "sha1": "ede64ef8caa54a018df04668836240fa38958810",
          "md5": "1494de72fa6ee335a0300c74b8c96cb8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.6-SNAPSHOT.jar",
          "url": "http-api-1.6.6-20200209.001152-1.jar",
          "size": 165513,
          "sha512": "8757ccfd754d00101abca3f32c3ae30a4b415f500da4ff2ecfcb64e80525cab1a7e28a9589ed12423cfdd5f9dbae0b4e9d295ba4b820a8796385d1060e8c4cc1",
          "sha256": "1435e4773bde46deabcc41624d4ebc26e8d115b772ae98dde66aae4a00733fdd",
          "sha1": "ede64ef8caa54a018df04668836240fa38958810",
          "md5": "1494de72fa6ee335a0300c74b8c96cb8"
        }
      ]
    }
  ]
}
