{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "ngufdodlkffovk7g43cul6w3sm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.6-SNAPSHOT.jar",
          "url": "http-api-1.6.6-20200130.102031-1.jar",
          "size": 165434,
          "sha512": "ab879fbdded5df059f62ef91873b489c49877bcfb6ce0636c5c2903b16b66569ee08fc2b2c103baa09f6d780571e90026172cfdb6b6601713713808745547e53",
          "sha256": "d0a0b165a5cd77ecb160104e9f879aba9868d7fa3009a0da516051b6d38858be",
          "sha1": "5f663dd117ad0f30a05242bf54e14c0201cc5a10",
          "md5": "8d6873693c7807ba27a92f77ddd7320e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.6-SNAPSHOT.jar",
          "url": "http-api-1.6.6-20200130.102031-1.jar",
          "size": 165434,
          "sha512": "ab879fbdded5df059f62ef91873b489c49877bcfb6ce0636c5c2903b16b66569ee08fc2b2c103baa09f6d780571e90026172cfdb6b6601713713808745547e53",
          "sha256": "d0a0b165a5cd77ecb160104e9f879aba9868d7fa3009a0da516051b6d38858be",
          "sha1": "5f663dd117ad0f30a05242bf54e14c0201cc5a10",
          "md5": "8d6873693c7807ba27a92f77ddd7320e"
        }
      ]
    }
  ]
}
