{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "6xohw4nhqnbwhmfyrl4nugivku"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.6-SNAPSHOT.jar",
          "url": "http-api-1.6.6-20200203.000816-1.jar",
          "size": 165434,
          "sha512": "a701be9303594b11fd1df956c6341f72b5ee9d2ebe2a7bb1e5dac4cfc823cbcc374e60b53fbac7d4998510a21820c812f11c92be44ced574d2edd8e021c3b9b3",
          "sha256": "a79980760c9ffeecd189e89269b572c3d0e62d8a077cacf6cd383bc20eb37ede",
          "sha1": "b28196d35b9b43550b1c4f7389d3b17c0cf4ed5d",
          "md5": "e8e9ebea5973151df97749b908711381"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.6-SNAPSHOT.jar",
          "url": "http-api-1.6.6-20200203.000816-1.jar",
          "size": 165434,
          "sha512": "a701be9303594b11fd1df956c6341f72b5ee9d2ebe2a7bb1e5dac4cfc823cbcc374e60b53fbac7d4998510a21820c812f11c92be44ced574d2edd8e021c3b9b3",
          "sha256": "a79980760c9ffeecd189e89269b572c3d0e62d8a077cacf6cd383bc20eb37ede",
          "sha1": "b28196d35b9b43550b1c4f7389d3b17c0cf4ed5d",
          "md5": "e8e9ebea5973151df97749b908711381"
        }
      ]
    }
  ]
}
