{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "ac6pd77vwnduxh5v2pbsddkgfi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.6-SNAPSHOT.jar",
          "url": "http-api-1.6.6-20200213.001218-1.jar",
          "size": 165551,
          "sha512": "c700b69e17e18dedc91101885072bd2a5ae679424738f9c81e9f491014b949fd5a1aefa631b28a45a9db960d901f76fd3520477107821be36385b000812d69b6",
          "sha256": "63f214579eaaad7463be79acf0da6162722a45054af77ec32c0d2a03ccaeff76",
          "sha1": "cdd0b2964c95f545b6eff9eba385c9ec268c23cf",
          "md5": "39bce00bcf0fc8a1a91c563b40c5f4f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.6-SNAPSHOT.jar",
          "url": "http-api-1.6.6-20200213.001218-1.jar",
          "size": 165551,
          "sha512": "c700b69e17e18dedc91101885072bd2a5ae679424738f9c81e9f491014b949fd5a1aefa631b28a45a9db960d901f76fd3520477107821be36385b000812d69b6",
          "sha256": "63f214579eaaad7463be79acf0da6162722a45054af77ec32c0d2a03ccaeff76",
          "sha1": "cdd0b2964c95f545b6eff9eba385c9ec268c23cf",
          "md5": "39bce00bcf0fc8a1a91c563b40c5f4f9"
        }
      ]
    }
  ]
}
