{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "6garymirazahvbgjp3g6xxwspu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.6-SNAPSHOT.jar",
          "url": "http-api-1.6.6-20200207.000935-1.jar",
          "size": 165511,
          "sha512": "e303a113df85ffb28094360405e88b5444319d24304f88754d5383f31f9adb1e62110bfd1d5f701204bceca7ce846638409e809bbca891d40561d8e1ae6a5a6c",
          "sha256": "09f45480fd0a09cf9819ace80435f4ac36b55c0a90590546d0ffbc230284d78e",
          "sha1": "ad593be96595228e008953321cfeaa9fd9a78e99",
          "md5": "f157b90b8d1814934f612bf15c24155a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.6-SNAPSHOT.jar",
          "url": "http-api-1.6.6-20200207.000935-1.jar",
          "size": 165511,
          "sha512": "e303a113df85ffb28094360405e88b5444319d24304f88754d5383f31f9adb1e62110bfd1d5f701204bceca7ce846638409e809bbca891d40561d8e1ae6a5a6c",
          "sha256": "09f45480fd0a09cf9819ace80435f4ac36b55c0a90590546d0ffbc230284d78e",
          "sha1": "ad593be96595228e008953321cfeaa9fd9a78e99",
          "md5": "f157b90b8d1814934f612bf15c24155a"
        }
      ]
    }
  ]
}
