{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "hd2x4jqv4vcatk3rjnrmy3xgta"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.6-SNAPSHOT.jar",
          "url": "http-api-1.6.6-20200129.140204-1.jar",
          "size": 165434,
          "sha512": "b8c37f3d283c1f9d3088ac886dbf36cf2fb6ebab7b235501bc3df2eba5beeaef447687d937f59b258f2fc62b319451cef75b5585f25f21760a957332bb26e59e",
          "sha256": "c131825e39c904b56265827fe8217beb4c088440cc8b933b69a0aef86f8237bf",
          "sha1": "1145fc0de6b387e8db2118b4d5cbdb93cbfbd9e6",
          "md5": "acc2b91cb49598944718a26197c17eac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.6-SNAPSHOT.jar",
          "url": "http-api-1.6.6-20200129.140204-1.jar",
          "size": 165434,
          "sha512": "b8c37f3d283c1f9d3088ac886dbf36cf2fb6ebab7b235501bc3df2eba5beeaef447687d937f59b258f2fc62b319451cef75b5585f25f21760a957332bb26e59e",
          "sha256": "c131825e39c904b56265827fe8217beb4c088440cc8b933b69a0aef86f8237bf",
          "sha1": "1145fc0de6b387e8db2118b4d5cbdb93cbfbd9e6",
          "md5": "acc2b91cb49598944718a26197c17eac"
        }
      ]
    }
  ]
}
