{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "1.6.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "rflxfeooujgrngzzx5e4sekc2q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.6.6-SNAPSHOT.jar",
          "url": "http-api-1.6.6-20200130.000948-1.jar",
          "size": 165434,
          "sha512": "0501f8d1f65bc55854252feb477595ab1e82e8968949083301d8075685f615f1fb484c5d5f72e7875a1939d078606bfaf8e130be6d214243acbb7cbbc5cc0970",
          "sha256": "62ea3f9d171111be8943bae7f56150ad2752e14d5a78d9804f4813cbbce71e45",
          "sha1": "540cabe26d08ad283bf5bc7dbd883710c13eb8d7",
          "md5": "0aa1f5a1fcbedcddd3f06dcc87f0956d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.16"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.6-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.6.6-SNAPSHOT.jar",
          "url": "http-api-1.6.6-20200130.000948-1.jar",
          "size": 165434,
          "sha512": "0501f8d1f65bc55854252feb477595ab1e82e8968949083301d8075685f615f1fb484c5d5f72e7875a1939d078606bfaf8e130be6d214243acbb7cbbc5cc0970",
          "sha256": "62ea3f9d171111be8943bae7f56150ad2752e14d5a78d9804f4813cbbce71e45",
          "sha1": "540cabe26d08ad283bf5bc7dbd883710c13eb8d7",
          "md5": "0aa1f5a1fcbedcddd3f06dcc87f0956d"
        }
      ]
    }
  ]
}
