{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "pov7w6lk5bai7fjaqkz3alhnxq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.1.jar",
          "url": "http-api-3.3.1.jar",
          "size": 164097,
          "sha512": "70877fd0a2fb026935d78a1b65ca6fcddc693a469958c070c1968dd9cc40f2e0cd016818eefd81a7ffce8d72dabccd14eca62305daa6f1c65c79da366ae6272b",
          "sha256": "24f206f99dcb6ba85bb15be4836c900bb8dd30306a5ff02f69d26b54cb004d83",
          "sha1": "7a6fad76ae80a1ef2c18da2332bbc1bf912e2d7c",
          "md5": "3a31f496abbf35430cebe99654766639"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.1.jar",
          "url": "http-api-3.3.1.jar",
          "size": 164097,
          "sha512": "70877fd0a2fb026935d78a1b65ca6fcddc693a469958c070c1968dd9cc40f2e0cd016818eefd81a7ffce8d72dabccd14eca62305daa6f1c65c79da366ae6272b",
          "sha256": "24f206f99dcb6ba85bb15be4836c900bb8dd30306a5ff02f69d26b54cb004d83",
          "sha1": "7a6fad76ae80a1ef2c18da2332bbc1bf912e2d7c",
          "md5": "3a31f496abbf35430cebe99654766639"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.1-sources.jar",
          "url": "http-api-3.3.1-sources.jar",
          "size": 107156,
          "sha512": "ba2421a8504b39d431c7fe4e8f5efa0c0e97007a4df9777aec37b3f8f59ed73f18e0ce1fff375fba33f1fc85c04dbd646e068f13f27c2e3fa5b7eb89b8df6ae0",
          "sha256": "b0cda7e3110bac8701767159a5cb249497509f211bcdca9535ca003e68737ac6",
          "sha1": "dad3bf025797b30926f1307aee74cff60e806a89",
          "md5": "759569686872264da2814dd5b6168fac"
        }
      ]
    }
  ]
}
