{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "udnvgsnbxjglxoahj725uaezmu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.1.jar",
          "url": "http-api-3.3.1.jar",
          "size": 164097,
          "sha512": "bb16a1eb4ab4acdccddb3e4bc1db236b34c915f78c0d1aa0c53d192405c327d71a4e29000507091c88679e246d37f0f96e848a1b9abbfcc429702c20681f0937",
          "sha256": "8d740ac7ad1123adf6a4a0f4816e07e805f13db1df67d8c4217ca0799ca1ec76",
          "sha1": "52c51c93f7b9917ad8b6c159c7da54d194a6515f",
          "md5": "aa410a83fcaf1c0421afd49ff32b3bed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.1.jar",
          "url": "http-api-3.3.1.jar",
          "size": 164097,
          "sha512": "bb16a1eb4ab4acdccddb3e4bc1db236b34c915f78c0d1aa0c53d192405c327d71a4e29000507091c88679e246d37f0f96e848a1b9abbfcc429702c20681f0937",
          "sha256": "8d740ac7ad1123adf6a4a0f4816e07e805f13db1df67d8c4217ca0799ca1ec76",
          "sha1": "52c51c93f7b9917ad8b6c159c7da54d194a6515f",
          "md5": "aa410a83fcaf1c0421afd49ff32b3bed"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.1-sources.jar",
          "url": "http-api-3.3.1-sources.jar",
          "size": 107156,
          "sha512": "a9b95c33586e9c691f01627a3a6bd4e1c4142bfc21739aa4eec5ee17d9c796b4005f56812b6f768756efd3fe87e2e301e95bc2984540ddf8ca4c45341d1d1bca",
          "sha256": "46c7858540c4a38af71b2d011e39bbb316f0af62c010f2cdf34706a43c308116",
          "sha1": "4dfcda956354a026c127f4b2d1e4affab21bc1d5",
          "md5": "f8bba9a5be27e6f1b413318a575ce8f8"
        }
      ]
    }
  ]
}
