{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "ctnfc5twxrc7vcntzpdw4juyci"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.1.jar",
          "url": "http-api-3.3.1.jar",
          "size": 164096,
          "sha512": "a345b0ad488998b36cecaa79c8452b3893bf60f5f9173a421d641b35e20866e8148e42b07523fa07ce1c19f1c00b3e8c1bea8a756eda7f8c7276c4c19471ed54",
          "sha256": "2966c37092b28f92afd3919557d98b99dfd611abf8203103b85aa9d1660cc23d",
          "sha1": "e263ade927141a545f4fa3693f2e664600f64d7c",
          "md5": "fec8c7ca13cb4040531309f14f850ebd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.1.jar",
          "url": "http-api-3.3.1.jar",
          "size": 164096,
          "sha512": "a345b0ad488998b36cecaa79c8452b3893bf60f5f9173a421d641b35e20866e8148e42b07523fa07ce1c19f1c00b3e8c1bea8a756eda7f8c7276c4c19471ed54",
          "sha256": "2966c37092b28f92afd3919557d98b99dfd611abf8203103b85aa9d1660cc23d",
          "sha1": "e263ade927141a545f4fa3693f2e664600f64d7c",
          "md5": "fec8c7ca13cb4040531309f14f850ebd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.1-sources.jar",
          "url": "http-api-3.3.1-sources.jar",
          "size": 107156,
          "sha512": "17a81000552b79b0313e196681d4f6fa56ed2269ca394ed9cc6154275b9e3f7aa943ed2744fb0cf8d29c811ca9b0621701ff08fc7371f8e32b46d24bd7cbffb8",
          "sha256": "6b3f951376b7511b1e0f31997484babb0d20e5d209e0e27ba6442fe3e79028bf",
          "sha1": "e5fabcd59f54efd7dc4eefdeb883a7e405c81ae8",
          "md5": "10322b3e7f31e9ae5e0d6bff38ec264f"
        }
      ]
    }
  ]
}
