{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "pm5dghtclbcubpxtbvhoindwni"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      }
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.4.3.jar",
          "url": "injected-client-3.4.3.jar",
          "size": 2263641,
          "sha512": "77d9bb22b63e79596b8d2af6371d61561acb83f98180ed5ff8d8f8cc5d1fa33a7e226d3c8674482c34e98bc34d17e5b8f7a8dbbaf2a15877a9e5303de83c9a6f",
          "sha256": "98087c70a2c3f7049a7096995d5086676b30c87d05f8dbea6e581ab800ef52cc",
          "sha1": "f7db29e06ac0f0afa743cbb9a644c5971160d5f3",
          "md5": "f67dba63cb9707c084ba45451cbc6ecb"
        }
      ]
    }
  ]
}
