{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "cqvevgiylrdxxcroskdws55k7e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.2.1.jar",
          "url": "runelite-api-3.2.1.jar",
          "size": 1176252,
          "sha512": "1e74e74a5df7e7825566955036fa5f5dd95c349d01461713396c5c609a41555ebdadf0444e06741eda1bb3face6e536fbb492d1f4692bd69fec0ed7957379399",
          "sha256": "d1a8b7d0ad4dba262455321a5132418d8a4eb93a9921e829797f349ff7989416",
          "sha1": "a67a8a8ccb18e216aa7a8dff5b280ba002457d28",
          "md5": "9507e8165c562f20cf1fcb48961f3cec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.2.1.jar",
          "url": "runelite-api-3.2.1.jar",
          "size": 1176252,
          "sha512": "1e74e74a5df7e7825566955036fa5f5dd95c349d01461713396c5c609a41555ebdadf0444e06741eda1bb3face6e536fbb492d1f4692bd69fec0ed7957379399",
          "sha256": "d1a8b7d0ad4dba262455321a5132418d8a4eb93a9921e829797f349ff7989416",
          "sha1": "a67a8a8ccb18e216aa7a8dff5b280ba002457d28",
          "md5": "9507e8165c562f20cf1fcb48961f3cec"
        }
      ]
    }
  ]
}
