{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "acot6363bjefjl4swbtgglg2u4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.2.1.jar",
          "url": "runelite-api-3.2.1.jar",
          "size": 1177469,
          "sha512": "a37e9d2079c5029fa978dcea988a72548f6bbac6548290c52047861c76081964632e9b05f19acc46d2f2630ad15da7430ccd9fea254e0e35d350d7d427961903",
          "sha256": "52fe34ee9b12e1c9d0c167b59186462180a52c31fa551b8627ff2c2ac0a3abde",
          "sha1": "c0404a5eeed1e9fc288fe56d2a7d8f228fed6d42",
          "md5": "12d1103da9a79b8392f7cb885f1d6abf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.2.1.jar",
          "url": "runelite-api-3.2.1.jar",
          "size": 1177469,
          "sha512": "a37e9d2079c5029fa978dcea988a72548f6bbac6548290c52047861c76081964632e9b05f19acc46d2f2630ad15da7430ccd9fea254e0e35d350d7d427961903",
          "sha256": "52fe34ee9b12e1c9d0c167b59186462180a52c31fa551b8627ff2c2ac0a3abde",
          "sha1": "c0404a5eeed1e9fc288fe56d2a7d8f228fed6d42",
          "md5": "12d1103da9a79b8392f7cb885f1d6abf"
        }
      ]
    }
  ]
}
