{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "7d3pzqyttfg4fpbv5oipdmjvu4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.2.1.jar",
          "url": "runelite-api-3.2.1.jar",
          "size": 1175857,
          "sha512": "abaf2851c25e4d4f17cfa4a4b9efb1aced6ce05c406455c2eeaedde5fb0e3d22e01b9587c6bb683005bb3d6b3c570590cd33983f15464f4ce2b556544f3651d8",
          "sha256": "a8878682b57bc045e51d93e6631011858fdd437e39380b4f46c67b35b6251e32",
          "sha1": "81f5ba45c0385922c6c47e7b9ff9ec8cd686b13f",
          "md5": "02c53fca02abb9e2d5e33f81662cfaa1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.2.1.jar",
          "url": "runelite-api-3.2.1.jar",
          "size": 1175857,
          "sha512": "abaf2851c25e4d4f17cfa4a4b9efb1aced6ce05c406455c2eeaedde5fb0e3d22e01b9587c6bb683005bb3d6b3c570590cd33983f15464f4ce2b556544f3651d8",
          "sha256": "a8878682b57bc045e51d93e6631011858fdd437e39380b4f46c67b35b6251e32",
          "sha1": "81f5ba45c0385922c6c47e7b9ff9ec8cd686b13f",
          "md5": "02c53fca02abb9e2d5e33f81662cfaa1"
        }
      ]
    }
  ]
}
