{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "iv6li4obfnevhl3zfxj2esjmjm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.2.2.jar",
          "url": "http-api-3.2.2.jar",
          "size": 164002,
          "sha512": "3ff1f199441586f7c97d7368d0fec49359f050fbe0811231ac955badef305b63c23b82f74627cabd389c55f15be963cfdc4fa18c59cafa6fc65769ddfff0a80a",
          "sha256": "4197308ce5bc17fd152d622f12f4b301ccd892e07ec5db174c95d02d11109a6e",
          "sha1": "1881ca72ee610438252af9b4e8d9cc35fc79887a",
          "md5": "ab968f3c0bab66644536362b0bf53585"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.2.2.jar",
          "url": "http-api-3.2.2.jar",
          "size": 164002,
          "sha512": "3ff1f199441586f7c97d7368d0fec49359f050fbe0811231ac955badef305b63c23b82f74627cabd389c55f15be963cfdc4fa18c59cafa6fc65769ddfff0a80a",
          "sha256": "4197308ce5bc17fd152d622f12f4b301ccd892e07ec5db174c95d02d11109a6e",
          "sha1": "1881ca72ee610438252af9b4e8d9cc35fc79887a",
          "md5": "ab968f3c0bab66644536362b0bf53585"
        }
      ]
    }
  ]
}
