{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "k5lwdxgx2ne6xofpjqaxgaqsmm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.2.2.jar",
          "url": "runelite-api-3.2.2.jar",
          "size": 1177131,
          "sha512": "c2f3362fef90286c43a1817d9c26d337b739ecfefae14e403a2fb1ccad8085a7bfc5de4f1a387fdea9e11e9d098a3de50f34844a8f3ad3e9f4ed2ae6c5e96e5b",
          "sha256": "b82dd52d37aaf35b2d563d5c58af2c6f4691f00ed61736916036839604ba8ef6",
          "sha1": "f9d539383a499c4c101297bc7cd5d50d77013b8e",
          "md5": "74ca44d6d11f9f4fbdc6504045c0dfc0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.2.2.jar",
          "url": "runelite-api-3.2.2.jar",
          "size": 1177131,
          "sha512": "c2f3362fef90286c43a1817d9c26d337b739ecfefae14e403a2fb1ccad8085a7bfc5de4f1a387fdea9e11e9d098a3de50f34844a8f3ad3e9f4ed2ae6c5e96e5b",
          "sha256": "b82dd52d37aaf35b2d563d5c58af2c6f4691f00ed61736916036839604ba8ef6",
          "sha1": "f9d539383a499c4c101297bc7cd5d50d77013b8e",
          "md5": "74ca44d6d11f9f4fbdc6504045c0dfc0"
        }
      ]
    }
  ]
}
