{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "iv6li4obfnevhl3zfxj2esjmjm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.2.2.jar",
          "url": "runelite-api-3.2.2.jar",
          "size": 1177131,
          "sha512": "a046659bbfa7b1f56953cfa22e987726710679372db7127f8b8ac6edd74e4f9ec92ced7c71e7055908698cfb27379053dbfad5e309264ab45c5440d606c6c090",
          "sha256": "8169c247e5ae8658cf83522614fb14fc3a8478db616700397b03a0578fc6fa4e",
          "sha1": "9e5e8b088043b60871ec0e45d770c6cff6c29c09",
          "md5": "b991320f58402d171ce107d71c984b3b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.2.2.jar",
          "url": "runelite-api-3.2.2.jar",
          "size": 1177131,
          "sha512": "a046659bbfa7b1f56953cfa22e987726710679372db7127f8b8ac6edd74e4f9ec92ced7c71e7055908698cfb27379053dbfad5e309264ab45c5440d606c6c090",
          "sha256": "8169c247e5ae8658cf83522614fb14fc3a8478db616700397b03a0578fc6fa4e",
          "sha1": "9e5e8b088043b60871ec0e45d770c6cff6c29c09",
          "md5": "b991320f58402d171ce107d71c984b3b"
        }
      ]
    }
  ]
}
