{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "5vbyyaqmcramrbqo7yp7hanwxm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.5-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.5-SNAPSHOT.jar",
          "url": "runescape-api-1.6.5-20200129.000856-1.jar",
          "size": 55269,
          "sha512": "1b114ab9add1b5fa582eeb68670c9bf121e9b5cc1829541ed41ed27528ae6179e8cc9c6fb96aabaf8fc3e4fd10a762bd8bcd567c9f21d32c712ac80f1fd2fe2b",
          "sha256": "23eb5257499b6cc152a176ae080ace7563e6f50a9387fd8e2fc2fdcfc14eb178",
          "sha1": "b2003c789055341fb60328bf136b63478b5dcba5",
          "md5": "0ca1ddc64677a7979ac2390aa5955f79"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.5-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.5-SNAPSHOT.jar",
          "url": "runescape-api-1.6.5-20200129.000856-1.jar",
          "size": 55269,
          "sha512": "1b114ab9add1b5fa582eeb68670c9bf121e9b5cc1829541ed41ed27528ae6179e8cc9c6fb96aabaf8fc3e4fd10a762bd8bcd567c9f21d32c712ac80f1fd2fe2b",
          "sha256": "23eb5257499b6cc152a176ae080ace7563e6f50a9387fd8e2fc2fdcfc14eb178",
          "sha1": "b2003c789055341fb60328bf136b63478b5dcba5",
          "md5": "0ca1ddc64677a7979ac2390aa5955f79"
        }
      ]
    }
  ]
}
