{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "1.6.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "4xf677b2avckpl5ja35dtrbb34"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.5-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.5-SNAPSHOT.jar",
          "url": "runescape-api-1.6.5-20200127.000806-1.jar",
          "size": 55242,
          "sha512": "183022ba190e58ad9781411bd33aeba7f5c01d1a315aa0bb9f49c07f100daace9634214a715a17fcb354a32165a8300fe4eed69937dd20f9c138decdeb5e374b",
          "sha256": "80788856475bfe2bc9312f7fa17c1b177daacfc8a4ed02713543607c8f92c15c",
          "sha1": "e695cf190a6521b7f16d74388739ced9840d564c",
          "md5": "1b581dbc042076cc598d297581616acb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "1.6.5-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.6.5-SNAPSHOT.jar",
          "url": "runescape-api-1.6.5-20200127.000806-1.jar",
          "size": 55242,
          "sha512": "183022ba190e58ad9781411bd33aeba7f5c01d1a315aa0bb9f49c07f100daace9634214a715a17fcb354a32165a8300fe4eed69937dd20f9c138decdeb5e374b",
          "sha256": "80788856475bfe2bc9312f7fa17c1b177daacfc8a4ed02713543607c8f92c15c",
          "sha1": "e695cf190a6521b7f16d74388739ced9840d564c",
          "md5": "1b581dbc042076cc598d297581616acb"
        }
      ]
    }
  ]
}
