{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "ksej45x3zfak5gcgy55cz3rgo4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.6.jar",
          "url": "injected-client-1.6.6.jar",
          "size": 2265863,
          "sha512": "876bcd29f29d4b488c2ea9406e1b6c3044ffcdd3d3d9c65919a58aef0696ac188f8d7d4f14161cbeccad3b932b8a04708c53d08b5f5ba34850732141d2045b96",
          "sha256": "b17bae025ab7851cde601007f4ef0a19764e626880e548c2afa66f05973cd3da",
          "sha1": "3180b2939e45f51cccc286dba2b03b65ffc12ef6",
          "md5": "bc940962ddd96f63209e28bec90b2175"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.6.jar",
          "url": "injected-client-1.6.6.jar",
          "size": 2265863,
          "sha512": "876bcd29f29d4b488c2ea9406e1b6c3044ffcdd3d3d9c65919a58aef0696ac188f8d7d4f14161cbeccad3b932b8a04708c53d08b5f5ba34850732141d2045b96",
          "sha256": "b17bae025ab7851cde601007f4ef0a19764e626880e548c2afa66f05973cd3da",
          "sha1": "3180b2939e45f51cccc286dba2b03b65ffc12ef6",
          "md5": "bc940962ddd96f63209e28bec90b2175"
        }
      ]
    }
  ]
}
