{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "1.6.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "2fravd3gq5cdxhu5oal4s4is4a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-1.6.6.jar",
          "url": "injected-client-1.6.6.jar",
          "size": 2265863,
          "sha512": "5f78127d61e007603c274bcb7271e3ad9b5fed60291c4a08921541bf17ca7e1a4a0429e32bf726a4d101b327dfc97925fc55719bbbd01d5cd9b10d4957a8f2b0",
          "sha256": "320b120940b575349faf46505b704ebcd88621857b7d5b08a0856c78b5f70b83",
          "sha1": "60d3b7be055bab01f50eb7632c6a0d748cce3357",
          "md5": "6d505da6ab827b00eebea7a74163acf9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-1.6.6.jar",
          "url": "injected-client-1.6.6.jar",
          "size": 2265863,
          "sha512": "5f78127d61e007603c274bcb7271e3ad9b5fed60291c4a08921541bf17ca7e1a4a0429e32bf726a4d101b327dfc97925fc55719bbbd01d5cd9b10d4957a8f2b0",
          "sha256": "320b120940b575349faf46505b704ebcd88621857b7d5b08a0856c78b5f70b83",
          "sha1": "60d3b7be055bab01f50eb7632c6a0d748cce3357",
          "md5": "6d505da6ab827b00eebea7a74163acf9"
        }
      ]
    }
  ]
}
